googleapis/google-cloud-python

gcloud/bigtable/happybase/__init__.py, gcloud/bigtable/happybase/connection.py, gcloud/bigtable/happybase/pool.py, gcloud/bigtable/happybase/table.py, gcloud/bigtable/happybase/test_connection.py, gcloud/bigtable/happybase/test_pool.py, gcloud/bigtable/happybase/test_table.py, gcloud/bigtable/row.py, gcloud/bigtable/table.py, gcloud/bigtable/test_row.py, gcloud/bigtable/test_table.py, system_tests/bigtable_happybase.py
=> Convert `gcloud.bigtable.happybase` to V2 patterns

.travis.yml, setup.cfg
See: https://github.com/GoogleCloudPlatform/gcloud-python/issues/1879#issuecomment-229444782
=> Disable broken wheel building

docs/logging-usage.rst
@dhermes per https://github.com/GoogleCloudPlatform/gcloud-python/pull/1905/files/1e4405eff5c4cc34870d5c6e0082728091631af0#r69016554
=> Fix typos in logging documentation

setup.py
After merging #1932.  Other PRs on `master`:
```bash
1a2fa6cb61e3eb3079af19879d7403baa899e6ca
$ git log 0.16.0..HEAD | grep 'Merge pull request ' |  awk -F ' ' '{print $4}' | sort
```
yields
#1877
#1878
#1880
#1882
#1884
#1887
#1888
#1892
#1894
#1900
#1901
#1902
#1903
#1905
#1907
#1908
#1910
#1912
#1913
#1915
#1916
#1919
#1923
#1924
#1925
#1926
#1930
#1931
#1932
#1938
#1941
=> Prepare 0.17.0 release.

docs/bigtable-instance-api.rst, docs/bigtable-usage.rst, gcloud/bigtable/client.py
Lost between review and merge of of #1932.  See also #1945.
=> Bigtable V2 docs fixes lost in merge

gcloud/_testing.py, gcloud/pubsub/_gax.py, gcloud/pubsub/test__gax.py
I know this is probably up for debate, I just wanted to learn more about this.
If you guys do want to re-enable this(#1911) I'll make whatever changes are needed!
Or let me know and I'll close this if you want to go in a different direction.
=> Re-enable bundling (for consideration)

gcloud/pubsub/test_topic.py, gcloud/pubsub/topic.py
Possible fix for #1955, checking the length of `self.messages` before `__exit__`.
=> Fix pubsub context manager exit error

gcloud/logging/_gax.py, gcloud/logging/test__gax.py, system_tests/logging_.py
Logging system tests now pass both **with** `GCLOUD_ENABLE_GAX` **and** without it.
The `_retry_backoff` function added in  3a3613e may help toward #1619.
=> Fix GAX logging system tests

README.rst, docs/index.rst, docs/logging-client.rst, docs/logging-usage.rst, docs/monitoring-client.rst, docs/monitoring-usage.rst, gcloud/logging/__init__.py, gcloud/logging/client.py, gcloud/logging/connection.py, gcloud/logging/entries.py, gcloud/logging/metric.py, gcloud/logging/sink.py, gcloud/monitoring/__init__.py, gcloud/monitoring/client.py, gcloud/monitoring/connection.py, gcloud/monitoring/metric.py, gcloud/monitoring/query.py, gcloud/monitoring/resource.py, gcloud/monitoring/timeseries.py, system_tests/logging_.py
Per: https://github.com/GoogleCloudPlatform/gcloud-common/issues/147
=> Update references from Cloud Logging to Stackdriver Logging

appveyor.yml
- Put `_testing` on PYTHONPATH only for Py3k (debug grpico-on-Py3k issues later).
- Use `setup.py develop` rather than `setup.py build` to get dependencies installed.
- Run `pip list` afterwards to show what got installed.
Toward #1863.
=> Attempt to un-break Appveyor:

gcloud/_testing.py, gcloud/pubsub/_gax.py, gcloud/pubsub/test__gax.py
Reverts GoogleCloudPlatform/gcloud-python#1950
Apparently, we have a [much tinier fix possible](\https://github.com/GoogleCloudPlatform/gcloud-python/pull/1950#issuecomment-230064438).
=> Revert "Re-enable bundling (for consideration)"

scripts/run_pylint.py
Probably should discuss?
https://github.com/PyCQA/pylint/blob/master/ChangeLog
> The docstring for a function or method should summarize its behavior and document its arguments, return value(s), side effects, exceptions raised, and restrictions on when it can be called (all if applicable). Optional arguments should be indicated. It should be documented whether keyword arguments are part of the interface.
From:  https://www.python.org/dev/peps/pep-0257/
=> Update disabled messages so new pylint passes

gcloud/credentials.py, gcloud/test_credentials.py
Change message when calling `generate_signed_url` on Blob if credentials with insufficient parameters are used.
See: #1964
The tests should actually be failing here. I'm still looking into why they aren't.
=> Change error for generating signed URL

appveyor.yml
Install GAX-related wrappers via pip to work around #1972.
=> Appveyor: this-time-for-sure-rocky

docs/bigquery-usage.rst, docs/bigquery_snippets.py, docs/pubsub_snippets.py
~~Uses #1831 as a base.~~
Toward a real fix for #1786 and related issues (usage docs out-of-sync with API surface).
=> Make dataset snippets testable

gcloud/bigquery/test_dataset.py, gcloud/bigquery/test_query.py, gcloud/bigquery/test_table.py, gcloud/dns/test_changes.py, gcloud/storage/test_acl.py, scripts/pylintrc_default, scripts/run_pylint.py
Work around https://github.com/PyCQA/pylint/issues/998
Globally disable new warnings (rather than just for tests, as in #1967).
Run pylint a single file at a time:  if any exits with a non-zero status, record the name and status and continue (this helped debug the issue above).
=> Disable pylint 1.6 warnings / work around breakage

gcloud/_helpers.py, gcloud/test__helpers.py
@tseaver not sure how I feel about the `NO COVER`'s.  The only other option I could think of was skipping tests on windows.
Appveyor: https://ci.appveyor.com/project/daspecster/gcloud-python-utjkc
LMKWYT
=> Attempt to fix windows path crash

docs/dns-usage.rst
I don't get why you need a `.` after domains though?
Is that something we should do for people? It seems so counterintuitive.
=> Update DNS resource_record_set()

docs/bigquery-usage.rst, docs/bigquery_snippets.py, gcloud/bigquery/client.py, gcloud/bigquery/query.py, gcloud/bigquery/test_client.py, gcloud/bigquery/test_query.py
=> Make synchronous query snippets testable

docs/pubsub-usage.rst, docs/pubsub_snippets.py, gcloud/pubsub/subscription.py, gcloud/pubsub/test_subscription.py
Follows @tmatsuo's [suggested implementation](https://github.com/GoogleCloudPlatform/gcloud-python/issues/798#issuecomment-91136888).
Closes #798.
Hold off merging until comparing with the alternate implementation suggested by @jgeewax. (#1637)
=> #798: Add support for auto-acknowledging pulled messages.

gcloud/logging/test__gax.py, gcloud/pubsub/test__gax.py, scripts/run_pylint.py, tox.ini
Fixes in [pylint 1.6.2 and 1.6.3](https://github.com/PyCQA/pylint/issues/998) mean we can test the files that caused it to barf in 1.6.0.
=> Pylint 1.6.3 compatibility

gcloud/streaming/test_transfer.py, scripts/run_pylint.py
Introduced in PR #1914.
Bump pylint's max line count for test modules accordingly.
=> Fix branch coverage miss in 'gcloud.streaming.transfer'.

gcloud/bigquery/job.py, gcloud/bigquery/query.py, gcloud/bigquery/test_job.py, gcloud/bigquery/test_query.py
=> Adding BigQuery support for legacy SQL.

gcloud/bigtable/happybase/connection.py, gcloud/bigtable/happybase/test_connection.py
Fixes #1989.
/cc @mbrukman @tswast
=> Making HappyBase enabled/disabled checks into no-ops.

gcloud/bigtable/happybase/__init__.py, gcloud/bigtable/happybase/table.py, gcloud/bigtable/happybase/test_table.py
Note this is "broken" in some sense though matches the semantics of the original. Fixes #1549. See also the discussion in #1989.
Also updating docs for differences of HappyBase.
/cc @garye @tswast @mbrukman
=> Make counter_set in HappyBase agree with HBase impl. semantics

gcloud/datastore/__init__.py
This fixes the issue with datastore index doc not rendering the examples.
http://daspecster.github.io/gcloud-python/#/docs/master/gcloud/datastore
@dhermes, one small step closer but far far from perfect. I need to detect lists so that renders better.
=> Fix datastore __init__ docstring.

gcloud/bigtable/column_family.py, gcloud/bigtable/happybase/connection.py, gcloud/bigtable/happybase/test_connection.py, gcloud/bigtable/table.py, gcloud/bigtable/test_column_family.py, gcloud/bigtable/test_table.py
In the process, adding a column families option to `Table.create()` in the low-level API.
Fixes #1524.
/cc @garye @tswast
=> Making HappyBase create_table() atomic.

scripts/pycodestyle_on_repo.py, tox.ini
Switch over to pycodestyle from pep8.
=> Switch from pep8 to pycodestyle

gcloud/pubsub/test__gax.py, setup.py, tox.ini
Rationalize tox vs. gRPC:
- Install `grpcio` and related deps by default, and omit adding `_testing` to PYTHONPATH.
- For Python 2.6, and lint, RTD, suppress installing gRPC-related deps, and add `_testing` to PYTHONPATH.
Bump minimum version for `grpcio` to 0.15.0.
Fix up Py3k failures with `grpcio` installed.
@daspecster, @dhermes Maybe this should land before 0.17.0?
=> Install gRPC et al for testing except py26/lint/docs-rtd

tox.ini
First seen https://github.com/GoogleCloudPlatform/gcloud-python/pull/1946#issuecomment-234667091
Not sure how this got through?
=> Add Sphinx as a dependency for linting

scripts/run_pylint.py, tox.ini
Reverts #2019 by removing sphinx dependency from tox lint and ignores verify_included_modules.py.
=> Exclude verify_included_modules.py from lint

docs/error-reporting-client.rst, docs/error-reporting-usage.rst, docs/index.rst, gcloud/error_reporting/__init__.py, gcloud/error_reporting/client.py, gcloud/error_reporting/test_client.py, scripts/verify_included_modules.py
This is another baby step, this time towards addressing #1881. 
Once again, probably goes into a feature branch.
First of all, this just piggybacks on the Logging client by directly extending it. Error Reporting has its own API, but is still rolling out support for the most important call, which is to actually post an error. 
This PR just adds a single function which reports the exception detail through Error Reporting using the Logging API.
If we want to add a system test, then we should add the functionality to actually get the details about the reported error. 
https://cloud.google.com/error-reporting/reference/rest/v1beta1/projects.events/list
If we think that's necessary I'll do it.
There is some intersection between Error Reporting and Logging in that we might want a logging handler …
=> Add Error Reporting Client

gcloud/bigquery/job.py, gcloud/bigquery/query.py, gcloud/bigquery/test_job.py, gcloud/bigquery/test_query.py, tox.ini
Re-fork and fix of [#2015](https://github.com/GoogleCloudPlatform/gcloud-python/pull/2015) with no further messed-up authorship.
=> refork and fix of #2015 (UDF Support)

docs/index.rst, docs/logging-handlers.rst, docs/logging-transports-base.rst, docs/logging-transports-sync.rst, docs/logging-transports-thread.rst, docs/logging-usage.rst, gcloud/logging/handlers/__init__.py, gcloud/logging/handlers/handlers.py, gcloud/logging/handlers/test_handlers.py, gcloud/logging/handlers/transports/__init__.py, gcloud/logging/handlers/transports/background_thread.py, gcloud/logging/handlers/transports/base.py, gcloud/logging/handlers/transports/sync.py, gcloud/logging/handlers/transports/test_background_thread.py, gcloud/logging/handlers/transports/test_base.py, gcloud/logging/handlers/transports/test_sync.py, gcloud/logging/logger.py, gcloud/logging/test_logger.py, scripts/verify_included_modules.py, system_tests/logging_.py
Next step: asynchronous transport using a background thread.
Some notes:
1) This includes a bugfix where Batch entries were writing logNames incorrectly
2) Background thread just writes to an entry and keeps re-using it. Seemed ok?
3) I didn't add a base Transport class yet, though possibly I should? With just a send message that raises NotImpementedException
4) Background thread will pretty much write an entry as soon as it shows up, although it's possible for a few entries to be written before it's scheduled. I want to run some performance tests on all these handlers and at that point I will start seeing if it would make a difference to wait for more entries to be written before committing them
5) Docs are getting kind of messy, feel like I might need more nesting. If other people agree …
=> Add Async Background Thread transport

docs/json/toc-all.json, docs/json/toc.json, scripts/generate_json_docs.py
Fixes #2024 and adds Error Reporting module.
=> Fix doc line linking

scripts/run_pylint.py
A developer who has set the variables can unset them to do diagnostics, and the fallback makes the run too painfully long (scrolling the interestng info off the screen if one Ctrl-C's it).
=> Drop the fallback to linting everything.

gcloud/_helpers.py, gcloud/monitoring/query.py, gcloud/monitoring/test_client.py, gcloud/monitoring/test_query.py, gcloud/test__helpers.py
The helper function _format_timestamp in gcloud.monitoring.query is
superseded by this updated helper function.
=> Update the helper _datetime_to_rfc3339 to handle time zones.

system_tests/bigquery.py, system_tests/retry.py
So I was playing with getting the retries working on the bigquery system3 tests.
I'm not sure what fixtures need to be created to get all the tests passing but this seemed to get the bigquery tests to pass.
Also, I have the retry set pretty long, looks like it takes about an average of 20 seconds for it to eventually be consistent.
=> Playing with retries.

setup.py
(redone from #2044)
27248053f1b26cf784a0ca650a64d7c10249d8d1
[/home/tseaver/projects/agendaless/Google/src/gcloud-python] 
$ git log 0.17.0..HEAD | grep 'Merge pull request ' |  awk -F ' ' '{print $4}' | sort
#1636
#1775
#1832
#1833
#1836
#1876
#1914
#1943
#1945
#1946
#1948
#1950
#1952
#1954
#1956
#1958
#1962
#1965
#1966
#1967
#1971
#1973
#1974
#1976
#1977
#1985
#1990
#1992
#1994
#1996
#1997
#1999
#2000
#2002
#2003
#2004
#2005
#2006
#2008
#2016
#2019
#2021
#2025
#2026
#2029
#2033
#2036
#2040
#2041
~~#3~~  stray comment from #1914
=> Prepare 0.18.0 release.

.travis.yml, CONTRIBUTING.rst, gcloud/_helpers.py, gcloud/bigtable/column_family.py, gcloud/bigtable/happybase/table.py, gcloud/error_reporting/client.py, gcloud/exceptions.py, gcloud/test__helpers.py, setup.py, tox.ini
=> Drop support for Python 2.6.

gcloud/bigquery/table.py, gcloud/bigquery/test_table.py
This adds the ability to create a partitioned table.  It would be nice to expose a table.list_partitions() method, but currently there is not an API-based way of returning partitions.  So, for now, it simply allows users to interact with the current partitioning API.
=> Add partition support to BigQuery

gcloud/logging/client.py, gcloud/pubsub/client.py, setup.py, tox.ini
Note that we have to adjust imports, because the GAX-generated wrappers are now in `google.cloud.logging.v2` and `google.cloud.pubsub.v1`.
/cc @bjwatson, @geigerj
=> Bump GAX dependencies to Py3k-compatible versions.

gcloud/logging/client.py, gcloud/pubsub/client.py, setup.py, tox.ini
Issue #2065 brownbags our 0.18.0 release.
=> Backport PR #2065 to address issue #2066, then bump version to 0.18.1 for urgent release.

system_tests/attempt_system_tests.py, system_tests/bigquery.py, system_tests/bigtable.py, system_tests/logging_.py, system_tests/pubsub.py, system_tests/retry.py, system_tests/run_system_test.py, system_tests/storage.py
Toward #2042.
This PR tries to rationalize the retries in our system tests into three types:
- Retry methods which raise particular exceptions (the class @daspecster implemented already)
- Retry methods until the result passes a predicate (generalizing the backoff stuff in `logging_`).
- Retry methods until a predicate on the instance's `__self__` passes (e.g., until `job.state == "done"`).
The PR adds classes for each of these categories, and attempts to use them where appropriate, replacing manual `time.sleep()` calls and existing "backoff" functions / loops.
It also tweaks the `tox -e system-tests` runner to attempt all system test modules, even if one fails, and tries to run them in order from least to most flake.
BTW,  cannot figure out how to get the `translate` tests to run at all, …
=> Consolidate retry logic

gcloud/exceptions.py
We do see such (transient) errors in the wild.
=> Add missing exception class for '502 Bad Gateway' response code.

gcloud/_helpers.py, gcloud/bigtable/client.py, gcloud/bigtable/test_client.py, gcloud/test__helpers.py
Also changing the metadata plugin to take credentials and user agent directly instead of inferring those values from a client (this is because the Bigtable client is unique in it's attributes).
This is in preparation for gRPC support for datastore as is #2081
=> Moving gRPC stub-with-auth helpers out of bigtable package.

docs/logging-usage.rst, docs/pubsub-usage.rst, gcloud/logging/client.py, gcloud/pubsub/client.py
As of the `0.8.1` versions of the wrappers, the pubsub and logging system tests pass on Python3.4 with GAX enabled.
=> Re-enable GAX by default if it is importable.

appveyor.yml
=> Appveyor:  force install grpcio >= 1.0rc1.

appveyor.yml, appveyor/requirements.txt
Avoids quoting interactions between pinned dependencies and Windows command shell syntax.
@dhermes Once again, I will push ASAP to trigger another Appveyor build.
=> Move requirements out to a separate 'requirements.txt' file.

system_tests/system_test_utils.py
Fixes #2084.
/cc @geigerj
----
Sample output
```bash
$ env | grep GCLOUD
$ env | grep GOOG
$
$ python system_tests/run_system_test.py --package datastore
D0811 08:35:27.609354178    9997 ev_posix.c:101]             Using polling engine: poll
To run the system tests, you need to set some environment variables.
Please check the CONTRIBUTING guide for instructions.
Missing variables: GCLOUD_TESTS_PROJECT_ID, GOOGLE_APPLICATION_CREDENTIALS
$
$ GOOGLE_APPLICATION_CREDENTIALS=bye GCLOUD_TESTS_PROJECT_ID=hi \
> python system_tests/run_system_test.py --package datastore
D0811 08:35:13.398294691    9979 ev_posix.c:101]             Using polling engine: poll
To run the system tests, you need to set some environment variables.
Please check the CONTRIBUTING guide for instructions.
The …
```
=> Distinguishing between unset env. var. and missing file in system test.

gcloud/logging/_gax.py, gcloud/logging/test__gax.py
=> logger_delete: map gRPC 'NOT_FOUND' error onto our 'NotFound' exception.

system_tests/bigquery.py
=> Normalize handling 403 for rate limits on 'dataset.create()'.

system_tests/bigtable_happybase.py
Previously shared the format with the Bigtable system tests but there was contention, possibly caused by the tests each running less than a second apart from each other.
Fixes #2076.
=> Using distinct instance name in Happybase system tests.

system_tests/pubsub.py
=> Address flaky pubsub system tests

system_tests/pubsub.py
=> Wait even longer for orphan's topic to be None.

scripts/generate_json_docs.py
So the `ABSOLUTE_LIBRARY_PATH` is used when trying this out locally, but on travis it appears to be pulling it from one of the sys.path's.
closes #2102, #2046.
=> Remove sys.path's from source link.

.travis.yml, README.rst, codecov.yml, tox.ini
This also removes codecov references.
=> Manually run tox -e cover to check for 100% test coverage.

gcloud/datastore/client.py, gcloud/datastore/connection.py, scripts/generate_json_docs.py
Fixes #2037.
This is a partial fix for the datastore docstring issue.
The original issue was actually, in part, due to the examples being in the datastore.Connection class. Sphinx put them all on one page for some reason.
=> Fix docs datastore examples

gcloud/logging/_gax.py, gcloud/pubsub/_gax.py, scripts/pylintrc_default, tox.ini
Rationale:
pylint tries to guess at imports in the `google` namespace, and fails miserably.  We test that those imports are valid all the time in unit tests anyway, so just disable them in pylint.
=> Install 'grpc' deps into 'lint' environ; ignore 'google' imports under pylint

gcloud/datastore/connection.py, gcloud/datastore/test_connection.py
This is in preparation for a gRPC equivalent of that API.
=> Factor out datastore API surface.

docs/json/json/master/toc.json, docs/json/toc-all.json
This is causing the docsite to crash and not get past the front page.
=> Fix JSON formatting and docsite crashing. Fixes #2114

gcloud/datastore/_generated/datastore_grpc_pb2.py, gcloud/datastore/connection.py, gcloud/datastore/test_connection.py, scripts/make_datastore_grpc.py
~~**NOTE**: Has #2097 as diffbase.~~
=> Enable gRPC for datastore API.

system_tests/monitoring.py
- Add retries for 503 ServiceUnavailable (eventual) on creation.
- Add retries for 404 NotFound (eventual consistency) on deletion.
- Ensure that parent groups get cleaned up even if child group deletion fails.
Towards:  #2092, #2093.
=> Reduce flakiness of Monitoring system tests.

gcloud/datastore/client.py
Fixes this error: 
http://stackoverflow.com/questions/30454549/a-literal-in-restructuredtext
Seems simplest/cleanest thing to do is just drop the *.s. Could alternatively follow that accepted answer's hacky solution or follow up with Sphinx, I don't see an issue about it in their issue tracker
=> Remove *s from kwargs in docstrings

scripts/update_json_docs.sh
@dhermes what do you think of moving the documentation generation to `after_success`?
Fixes #2121
=> Allows build to fail if JSON docs fail to generate.

gcloud/monitoring/client.py, gcloud/monitoring/metric.py, gcloud/monitoring/resource.py, gcloud/monitoring/test_client.py, gcloud/monitoring/timeseries.py
@rimey @supriyagarg 
cc @sharbison3
=> Add Factory Methods for Metric/Resource/Timeseries

docs/vision-usage.rst
Add the Vision docs to master per discussion with @dhermes.
=> Add Vision API usage documentation.

docs/dns-usage.rst
Was originally in #2062 but I gave it it's own PR here.
=> Fixing eash->each typo in DNS usage doc.

gcloud/bigquery/_helpers.py, gcloud/bigquery/dataset.py, gcloud/bigquery/job.py, gcloud/bigquery/query.py, gcloud/bigquery/schema.py, gcloud/bigquery/table.py, gcloud/datastore/batch.py, gcloud/datastore/client.py, gcloud/datastore/connection.py, gcloud/datastore/entity.py, gcloud/datastore/helpers.py, gcloud/datastore/key.py, gcloud/datastore/query.py, gcloud/dns/changes.py, gcloud/dns/client.py, gcloud/dns/resource_record_set.py, gcloud/iterator.py, gcloud/logging/connection.py, gcloud/logging/logger.py, gcloud/pubsub/connection.py, gcloud/pubsub/message.py, gcloud/pubsub/subscription.py, gcloud/resource_manager/client.py, gcloud/storage/batch.py, gcloud/storage/blob.py, gcloud/streaming/exceptions.py, gcloud/streaming/http_wrapper.py, gcloud/streaming/stream_slice.py
A 30 min quick, but slow and deliberate, review of the existing codebase.
- Multiple typos and misspellings 
- Multiple missing or incorrect punctuation
- Unused variables
The library is also wildly inconsistent  on its usage of % vs the format function for  string interpolation. I suggest format, but that belongs in its own PR.
http://stackoverflow.com/questions/12382719/python-way-of-printing-with-format-or-percent-form
=> Fix Numerous Spelling, Style, English Issues

gcloud/logging/_gax.py, gcloud/pubsub/_gax.py
Introduced in #2124. Fixes #2140.
=> Converting None page tokens into the GAX INITIAL_PAGE.

.travis.yml, docs/index.rst
Also adding Vision usage doc to the main index since without it the Sphinx build fails.
=> Adding Sphinx docs build check to Travis.

appveyor.yml, docs/bigtable-client-intro.rst, gcloud/_helpers.py, gcloud/_testing.py, gcloud/bigtable/__init__.py, gcloud/bigtable/_testing.py, gcloud/bigtable/client.py, gcloud/bigtable/cluster.py, gcloud/bigtable/column_family.py, gcloud/bigtable/instance.py, gcloud/bigtable/row.py, gcloud/bigtable/row_data.py, gcloud/bigtable/table.py, gcloud/bigtable/test_client.py, gcloud/bigtable/test_cluster.py, gcloud/bigtable/test_column_family.py, gcloud/bigtable/test_instance.py, gcloud/bigtable/test_row.py, gcloud/bigtable/test_row_data.py, gcloud/bigtable/test_table.py, gcloud/datastore/connection.py, gcloud/datastore/test_connection.py, gcloud/logging/_gax.py, gcloud/logging/test__gax.py, gcloud/pubsub/_gax.py, gcloud/test__helpers.py, scripts/make_datastore_grpc.py, scripts/make_operations_grpc.py, system_tests/bigtable.py, system_tests/logging_.py
Fixes #2130.
Most noteworthy is that the "stable" gRPC doesn't have `__exit__` and `__enter__` and that the stubs are actual classes (instead of some instance of a private and esoteric class).
When scanning for the case-insenstive string grpc I also found some things to change in other parts of the codebase I came across (e.g. a virtualenv root path falling back to `protoc`)
----
@nathanielmanistaatgoogle PTAL
In particular we went from the public exception type `grpc.framework.interfaces.face.face.AbortionError` to the private `grpc._channel._Rendezvous`.
How are we or users supposed to build in error handling? Should we catch `grpc.Error` (which `_Rendezvous` inherits from)?
BIG WORRY: Every system tests finishes with
```
E0819 12:40:27.346506119   22315 network_status_tracker.c:48] …
```
=> Removing usage of the gRPC beta subpackage.

CONTRIBUTING.rst, docs/index.rst, docs/logging-handlers.rst, docs/logging-transports-base.rst, docs/logging-transports-sync.rst, docs/logging-transports-thread.rst, docs/logging-usage.rst, gcloud/logging/handlers.py, gcloud/logging/handlers/__init__.py, gcloud/logging/handlers/handlers.py, gcloud/logging/handlers/test_handlers.py, gcloud/logging/handlers/transports/__init__.py, gcloud/logging/handlers/transports/background_thread.py, gcloud/logging/handlers/transports/base.py, gcloud/logging/handlers/transports/sync.py, gcloud/logging/handlers/transports/test_background_thread.py, gcloud/logging/handlers/transports/test_base.py, gcloud/logging/handlers/transports/test_sync.py, gcloud/logging/logger.py, gcloud/logging/test_handlers.py, gcloud/logging/test_logger.py, scripts/verify_included_modules.py, system_tests/logging_.py
Fixes #2102
Will likely fail the CLA check (since it contains someone else's commits) but we can just merge with a failed check.
/cc @waprin
=> Merging logging-stdlib-handler-feature branch back into master

docs/index.rst, docs/language-usage.rst
/cc @omaray are you in the org yet (I can't assign you to this PR)
=> Adding usage doc for Natural Language API.

system_tests/storage.py
Showed up when Travis when 3 merge builds right on top of each other:
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154249353
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154251510
@tseaver I am trying to force the failure locally so I can see more fine-grained error info but 429 is pretty specific so I'm not that worried. I also would like to add a debug flag so we get more error info in our failure messages on Travis.
=> Adding 429 retry in storage for bucket create and delete.

docs/index.rst, docs/language-client.rst, gcloud/language/__init__.py, gcloud/language/client.py, gcloud/language/connection.py, gcloud/language/test_client.py, gcloud/language/test_connection.py, scripts/generate_json_docs.py, scripts/verify_included_modules.py
~~**NOTE**: Has #2062 as base.~~
=> Implement basic connection and client for Natural Language API

README.rst
@tswast Sorry I wanted to get rid of the branch in https://github.com/GoogleCloudPlatform/gcloud-python and the PR went stale.
----
@daspecster We previously followed the readthedocs.org of docs at
```
{URI}/stable -- last release
{URI}/latest -- HEAD of source
{URI}/0.1.0
{URI}/0.2.0
{URI}/0.2.1
...
```
Can we restore this (outside of this PR)?
=> Updating docs link in README.

docs/index.rst, docs/json/json/master/toc.json, docs/vision-client.rst, gcloud/vision/__init__.py, gcloud/vision/connection.py, gcloud/vision/test_connection.py, scripts/generate_json_docs.py, scripts/verify_included_modules.py
As per a conversation about small PR's with @dhermes, here is Vision's connection class.
This is pretty simple, just adding the needed scope.
=> Add Vision API connection.

docs/index.rst, docs/language-document.rst, docs/language-usage.rst, gcloud/language/__init__.py, gcloud/language/client.py, gcloud/language/document.py, gcloud/language/test_client.py, gcloud/language/test_document.py
~~**NOTE**: Has #2162 as diffbase.~~
@tseaver and @jgeewax this PR (namely the last 4 commits) make the discussion in #2062 / earlier today more concrete. Is this what you had in mind?
=> Implement Document factory constructors on language client

docs/index.rst, docs/language-responses.rst, docs/language-usage.rst, gcloud/language/document.py, gcloud/language/entity.py, gcloud/language/test_document.py, gcloud/language/test_entity.py, system_tests/attempt_system_tests.py, system_tests/language.py, system_tests/run_system_test.py
Also adding system tests and the class needed for the return value.
~~**NOTE**: Has #2164 as diffbase.~~
=> Adding Document.analyze_entities() in language package

docs/conf.py
During a docs build, each of the two changed links prints a warning:
```
intersphinx inventory has moved: https://docs.python.org/ -> https://docs.python.org/2
intersphinx inventory has moved: http://oauth2client.readthedocs.org/en/latest/ -> http://oauth2client.readthedocs.io/en/latest
```
=> Updating Intersphinx links.

docs/index.rst, docs/operation-api.rst, gcloud/bigtable/cluster.py, gcloud/bigtable/instance.py, gcloud/bigtable/test_cluster.py, gcloud/bigtable/test_instance.py, gcloud/operation.py, gcloud/test_operation.py, scripts/generate_json_docs.py, system_tests/bigtable.py
Intended to replace the versions currently in `.bigtable.instance` and `bigtable.cluster`.  Differences in approach from those:
- No parsing / reconstruction of operation's `name`:  the new class just holds the name as retrieved.
- Add a `from_pb` classmethod factory, which attempts to parse out the `metadata` Any, IFF the `type_url` on the Any is set, and there is a class registered for it.
- Drops the complicated `__eq__`/`__ne__` as YAGNI:  if needed, reimplement using just the `name` attr.
Use new `gcloud.operations.Operation` for long-running ops.
=> Factor out shared 'Operation' class and helpers.

system_tests/storage.py
=> Add eventual consistency check for storage list_blobs()

scripts/update_docs.sh, scripts/update_json_docs.sh
Fairly important update, I'll get with you on chat @dhermes. There might be some other changes that will need to happen.
=> Clean up doc site scripts.

scripts/verify_included_modules.py, tox.ini
It was previously broken because module verification assumed the docs were built in the `_build` directory.
=> Fixing docs-rtd tox rule.

docs/language-usage.rst, gcloud/language/__init__.py, gcloud/language/client.py, gcloud/language/document.py, gcloud/language/entity.py, gcloud/language/test_client.py, system_tests/language.py
In particular:
- Updating docs after discussion on #2062 
- Removing `document_from_blob()` helper in language.
- Removing `project` from the `Client` constructor since it isn't needed by
- Adding another system test for `analyze_entities()` that uses docs stored on GCS
=> Updating language implementation after some review comments

system_tests/pubsub.py
The hypothesis is that we are seeing flakiness due to rapid creation / deletion cycles on topics with the shared name.
Towards #2163, #2192.
=> Kill off 'DEFAULT_TOPIC_NAME'.

system_tests/monitoring.py
=> Retry on 500 from 'descriptor.{create,delete}'.

docs/bigtable-client-intro.rst, docs/bigtable-client.rst, docs/bigtable-cluster.rst, docs/bigtable-column-family.rst, docs/bigtable-data-api.rst, docs/bigtable-instance-api.rst, docs/bigtable-instance.rst, docs/bigtable-row-data.rst, docs/bigtable-row-filters.rst, docs/bigtable-row.rst, docs/bigtable-table-api.rst, docs/bigtable-table.rst, docs/bigtable-usage.rst
=> Remove stale gRPC warning from Bigtable docs.

docs/language-responses.rst, gcloud/language/document.py, gcloud/language/sentiment.py, gcloud/language/test_document.py, gcloud/language/test_sentiment.py, system_tests/language.py
~~**NOTE**: Has #2187 as diffbase.~~
=> Implementing analyze sentiment method and helpers in language

gcloud/bigtable/cluster.py, gcloud/bigtable/instance.py
There are no such endpoints in the Bigtable V2 API.
Closes #2209.
=> Remove all traces of 'undelete'.

gcloud/_helpers.py, gcloud/test__helpers.py
As upper-case letters are illegal per http2 spec.
=> Use lower-case gRPC header keys

system_tests/monitoring.py
When run on Travis, the `unique_resource_id()` function causes the type name to exceed 40 characters:  reducing the prefix length empirically allows the `create()` | `delete()` pair to work as intended.
Towards #2176.
=> Shorten custom metric type used for system testing.

system_tests/pubsub.py
=> Add retry for flaky 'topic.exists()' check.

system_tests/pubsub.py
See:
https://github.com/GoogleCloudPlatform/gcloud-python/issues/2080#issuecomment-242987151
Closes #2080.
=> Drop the ultra-flaky test for orphaned subscriptions.

gcloud/monitoring/query.py, gcloud/monitoring/test_query.py
Google Monitoring API filters support <,<=,>,>= operators as described
in its documentation:
https://cloud.google.com/monitoring/api/v3/filters.
Current version of the library only has mappings of:
1. ’{key}_prefix:{value}' -> '{key} = starts_with("{value}")'
2. ’{key}_suffix:{value}' -> '{key} = ends_with("{value}")'
This patch introduces additional mappings of:
3. ’{key}_greater:{value}' -> '{key} > {value}'
4. ’{key}_greaterequal:{value}' -> '{key} >= {value}'
5. ’{key}_less:{value}' -> '{key} < {value}'
6. ’{key}_lessequal:{value}' -> '{key} <= {value}'
So that it is possible, for example, to filter based on the
response_code values range, as shown below:
metric.type = "appengine.googleapis.com/http/server/response_count"
AND metric.label.response_code < 600
AND …
=> Add support for the comparison filters of Google Monitoring API

gcloud/streaming/http_wrapper.py, gcloud/streaming/transfer.py, gcloud/streaming/util.py, unit_tests/streaming/test_http_wrapper.py, unit_tests/streaming/test_util.py
=> Remove some unused features of gcloud.streaming.

docs/json/json/master/toc.json
Partial resolution for #2246.
The table of contents references were wrong.
=> Fix monitoring documentation TOC.

docs/bigquery-usage.rst
=> Poll async jobs using correct state logic in BQ usage docs.

system_tests/logging_.py, system_tests/pubsub.py
Broken  after #2223.
- Namespace packages break use of 'Client' from package.
- Shorten bucket / topic names to match limits.
- Stop sharing sink / metric names across tests (brush clearing to find the real issue with bucket / topic names).
=> Fix logging/pubub system tests

system_tests/bigtable.py
Longer instance ID in #2223 breaks creation.
See: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/158235243#L1292
=> Shorten instance ID to match restrictions.

system_tests/storage.py
The storage API is not guaranteed to be strongly consistent, so we retry to allow for eventual consistency.
Came up in https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/157997410
=> Adding a retry for storage list_blobs().

google/cloud/pubsub/_gax.py, unit_tests/pubsub/test__gax.py
=> Map pb 'publish_time' -> JSON 'publishTimestamp' for received messges.

CONTRIBUTING.rst, docs/logging-usage.rst, docs/pubsub-usage.rst, google/cloud/_helpers.py, google/cloud/bigtable/client.py, google/cloud/datastore/connection.py, google/cloud/environment_vars.py, google/cloud/logging/client.py, google/cloud/pubsub/client.py, system_tests/run_emulator.py, tox.ini, unit_tests/bigtable/test_client.py, unit_tests/datastore/test_connection.py, unit_tests/test__helpers.py
This change ended up "inspiring" a few related changes, see commit messages for details.
----
@pcostell Do I need to make a note about the minimum version of the `gcloud` CLI needed for
- The existence of the `cloud-datastore-emulator` (over the legacy `gcd-emulator`)
- The support in the emulator for `v1` of the API
=> Upgrading datastore emulator to work with gRPC

google/cloud/datastore/batch.py, google/cloud/datastore/client.py, google/cloud/streaming/exceptions.py, google/cloud/streaming/http_wrapper.py
Follow-up to PR #2223. The Sphinx mechanism of using a `.` to mean "go find this class" can be confusing, so we make sure the `.` also is a relative path.
=> Updating some Sphinx class links.

google/cloud/pubsub/_gax.py, google/cloud/pubsub/client.py, google/cloud/pubsub/connection.py, unit_tests/pubsub/test__gax.py, unit_tests/pubsub/test_client.py, unit_tests/pubsub/test_connection.py
In the process, removing the `api_base_url` from the Pub / Sub Connection class.
~~**NOTE**: Has #2244 as diffbase~~
=> Updating Pub / Sub GAX calls to work with emulator.

google/cloud/bigquery/client.py, google/cloud/resource_manager/client.py, unit_tests/bigquery/test_client.py
=> Add 'Client.list_projects'.

google/cloud/bigtable/client.py, google/cloud/environment_vars.py, unit_tests/bigtable/test_client.py
System test will be updated soon, once some issues with the emulator are worked out.
----
Message was previously:
Currently does not work as-is since most of the methods (most notable row.commit()) result in `UNAVAILABLE` from the backend.
----
Towards #2242.
/cc @garye Could you check out this branch and run `tox -e bigtable-emulator` to see the failures?
~~**NOTE**: Has #2245 as diffbase.~~
=> Updating Bigtable stub creation to work with emulator.

google/cloud/logging/handlers/handlers.py, google/cloud/monitoring/label.py
Renaming some APIs to Stackdriver brand
=> Stackdriver product rename

.travis.yml, README.rst, scripts/get_version.py, scripts/update_docs.sh
Switching back to Sphinx.
We will need to update the index.html on the `gh-pages` branch I believe to make this work.
@dhermes I'm not sure where the content for the index.html files in `latest/` and `stable/` get generated from.  They have the wrong example code in them.
Testing: http://daspecster.github.io/google-cloud-python
=> Switch back to Sphinx.

google/cloud/bigquery/_helpers.py, unit_tests/bigquery/test__helpers.py
See: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2265#issuecomment-245656215
Note that the added tests uncovered a bug in unmarshalling `RECORD`-type fields with non-string subfields.
/cc @thejens
=> Add explicit tests for column-marshalling helpers.

google/cloud/bigquery/job.py, unit_tests/bigquery/test_job.py
We use the gcloud Python libraries for some pretty heavy lifting BQ jobs, and were hitting the billing tier restriction. This should allow for those fields to be configured.
=> Bigquery: Adding configuration properties for maximumBillingTier and maximumBytesBilled for QueryJobs

docs/logging-usage.rst
=> Update 'filter' -> 'filter_' in logging examples.

system_tests/language.py
Fixes #2274. However, the test will likely remain flaky if the output is a moving target.
=> Widening the salience range for natural language system tests.

google/cloud/_helpers.py, google/cloud/bigquery/_helpers.py, unit_tests/bigquery/test__helpers.py, unit_tests/test__helpers.py
Change-Id: I158b48b6470ff44ff006e18d5eb8e3540749670b
=> Support parsing DATE columns from Standard SQL tables

google/cloud/_helpers.py, google/cloud/bigtable/client.py, google/cloud/connection.py, unit_tests/test__helpers.py, unit_tests/test_connection.py
Fixes #2271.
See https://github.com/GoogleCloudPlatform/gcloud-common/issues/179 for context.
Also moving gRPC user-agent from plugin to channel options. For context on that change, see the comment by @murgatroid99: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1568/files#r77727186
As for `grpc.primary_user_agent` vs `grpc.secondary_user_agent`, @nathanielmanistaatgoogle said
> That way the user agent as it appears on the wire should be "primarily gRPC, secondarily gcloud" rather than "primarily gcloud <no secondary>".
=> Reverting user-agent change that came with rename.

docs/index.rst, docs/vision-face.rst, docs/vision-image.rst, docs/vision-usage.rst, google/cloud/vision/__init__.py, google/cloud/vision/_fixtures.py, google/cloud/vision/client.py, google/cloud/vision/face.py, google/cloud/vision/feature.py, google/cloud/vision/geometry.py, google/cloud/vision/image.py, google/cloud/vision/likelihood.py, unit_tests/vision/test_client.py, unit_tests/vision/test_face.py, unit_tests/vision/test_image.py
Initial add for face detection.
I'm not sure about the way I have `Likelihood` and `FaceLandmarkTypes` setup.
If you have some ideas on how that could be improved I would love to hear them.
This looks large, but it's mostly DTOs for the API response.
LMKWYT!
=> Add Vision API Face detection.

google/cloud/_helpers.py, unit_tests/test__helpers.py
Follow on to #2284.
PS I just replaced the only occurrences of `secondary` with `primary`, didn't run tests, so fingers crossed.
=> Upgrading gRPC user agent from secondary to primary.

CONTRIBUTING.rst, google/cloud/environment_vars.py, system_tests/bigquery.py, system_tests/bigtable.py, system_tests/clear_datastore.py, system_tests/datastore.py, system_tests/language.py, system_tests/local_test_setup.sample, system_tests/logging_.py, system_tests/monitoring.py, system_tests/populate_datastore.py, system_tests/pubsub.py, system_tests/storage.py, system_tests/system_test_utils.py
This is because the project ID can be determined directly from the file pointed to by `GOOGLE_APPLICATION_CREDENTIALS`.
Fixes #2263.
=> Stop using a designated tests project ID.

system_tests/storage.py
Fixes #2289.
----
I ran it locally until I could force the error:
```
(system-tests) $ .tox/system-tests/bin/nosetests system_tests/storage.py -vv --nocapture
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
test_create_bucket (storage.TestStorageBuckets) ... ok
test_list_buckets (storage.TestStorageBuckets) ... ok
test_list_files (storage.TestStorageListFiles) ... ok
test_paginate_files (storage.TestStorageListFiles) ... ok
400 No file found in request. (POST https://www.googleapis.com/storage/v1/b/new_1473450503532/o/file01.txt/copyTo/b/new_1473450503532/o/parent%2Fchild%2Ffile21.txt), Trying again in 1 seconds...
400 No file found in request. (POST https://www.googleapis.com/storage/v1/b/new_1473450503532/o/file01.txt/copyTo/b/new_1473450503532/o/parent%2Fchild% …
```
=> Adding retries for failed copy_blob() calls in system tests.

docs/index.rst, docs/vision-entity.rst, google/cloud/vision/entity.py, google/cloud/vision/feature.py, google/cloud/vision/geometry.py, google/cloud/vision/image.py, unit_tests/vision/_fixtures.py, unit_tests/vision/test_client.py, unit_tests/vision/test_entity.py
Based off #2224.
This adds EntityAnnotation, which is used by LOGO_DETECTION, LANDMARK_DETECTION, LABEL_DETECTION and TEXT_DETECTION.
Small PRs for the other three detection types will follow.
✅ ~~I'll rebase this after #2224 gets merged in.~~
=> Vision logo detection

system_tests/pubsub.py
Though the [most recent build][1] went green, it leaked the subscription (since it was expected to fail, it never reaches the deletion line). This is very much related to #2080.
@tmatsuo Can we actually get a real chat with someone on the eng. team about the value of this system test?
[1]: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/158893503
=> Correctly clean-up subscription in pubsub system test.

docs/conf.py
The old URL raises a 404, rather than redirecting. :(
=> httplib2 Sphinx docs have moved to RTD.

google/cloud/vision/entity.py, google/cloud/vision/geometry.py, google/cloud/vision/image.py, unit_tests/vision/_fixtures.py, unit_tests/vision/test_client.py
Based off of #2235.
Add `LocationInformation` for LANDMARK_DETECTION support.
I will rebase with master after #2224 and #2235 are merged.
=> Add vision landmark detection

CONTRIBUTING.rst, system_tests/attempt_system_tests.py, tox.ini
=> Allow positional arguments tox -e system-tests.

README.rst
The current PyPI install command, links, and images point to the wrong package. I suppose this might be due to the new auto-generated documentation platform in use.
=> fix README installation command and PyPI links

.gitignore
Also removing the `_build_rtd` directory that we no longer use.
H/T to @Ofekmeister for pointing out that we don't `.gitignore` the JetBrains config directory
=> Updating .gitignore for JetBrains.

system_tests/bigquery.py
As with #2307, I took down a bunch of failures last week and can't track down where this occurred, sorry.
=> Adding 409 retry on bucket delete in BigQuery system test.

google/cloud/vision/entity.py, google/cloud/vision/geometry.py, google/cloud/vision/image.py, unit_tests/vision/_fixtures.py, unit_tests/vision/test_client.py
Based off of #2236.
I was able to DRY up the requests code for the `EntityAnnotation` based detection types.
✅ Waiting for #2236 before rebasing.
=> Add vision label detection

docs/vision-usage.rst, google/cloud/vision/entity.py, google/cloud/vision/image.py, unit_tests/vision/_fixtures.py, unit_tests/vision/test_client.py
Based off #2237.
Adds text detection.
This is the last of the Entity based detections.
Safe Search and Image properties are left.
=> Vision text detection

google/cloud/bigquery/job.py, google/cloud/bigquery/table.py, system_tests/bigquery.py, unit_tests/bigquery/test_job.py
Closes #2133.
/cc @jonparrott, @matheuspatury
I will cancel the PR job on Travis, as this PR changes only system tests.
=> Add a system test for 'Table.upload_from_file'.

appveyor/requirements.txt, google/cloud/bigtable/__init__.py, setup.py, system_tests/attempt_system_tests.py, tox.ini
~~Adding support for an environment variable that App Engine users can use to disable installing gRPC packages into their application.~~
Follow-up to #2304.
@jonparrott Can you weigh in here on the GAE env. var. in `setup.py`?
=> Remove gRPC/GAX conditional checks.

docs/index.rst, docs/vision-safe-search.rst, google/cloud/vision/image.py, google/cloud/vision/safe.py, unit_tests/vision/_fixtures.py, unit_tests/vision/test_client.py
This adds Safe Search detection to the Vision API.
Safe Search isn't an EntityAnnotation based call so a new SafeSearchAnnotation was created.
=> Add Vision safe search detection.

system_tests/logging_.py
Sometimes when tests run quicker than usual or multiple builds run tests at once, the backend gives a 429 response to rate-limit our clients using one service account.
I took down a bunch of failures last week and can't track down where this occurred, sorry.
=> Adding retry for bucket creation to logging system test.

docs/bigquery-usage.rst, google/cloud/bigquery/_helpers.py, google/cloud/bigquery/job.py, google/cloud/bigquery/query.py, unit_tests/bigquery/test__helpers.py, unit_tests/bigquery/test_job.py, unit_tests/bigquery/test_query.py
Closes #2083.
/cc @jonparrott, @tswast
=> Add 'QueryJob.results' method

system_tests/bigquery.py
Avoids eventual consistency clashes.
Closes #2318.
=> Remove sharing dataset name across system tests.

system_tests/language.py
=> Loosening salience assumptions in language system test.

system_tests/storage.py
This is not just "taking the easy way out", it's really the most appropriate fix since there are so many
assertions that can fail due to eventual consistency. (For example, asking for 2 blobs should have a next page when 3 are in the bucket, but this may break down due to eventual consistency.)
Fixes #2217.
Also
- restoring `test_second_level()` to pre-#2252 (by retrying the entire test case)
- restoring `test_list_files()` to pre-#2181 (by retrying the entire test case)
- adding retries around remaining test cases that call `list_blobs()`: `test_root_level_w_delimiter()`, `test_first_level()` and `test_third_level()`
- adding a helper to empty a bucket in `setUpClass()` helper (which also uses `list_blobs()`) in both `TestStoragePseudoHierarchy` and `TestStorageListFiles`
----
@tseaver I …
=> Retry entire test_paginate_files() storage system test.

google/cloud/logging/__init__.py, google/cloud/logging/_gax.py, google/cloud/logging/client.py, google/cloud/logging/connection.py, google/cloud/logging/logger.py, google/cloud/pubsub/__init__.py, setup.py, unit_tests/logging/test__gax.py, unit_tests/logging/test_client.py, unit_tests/logging/test_connection.py, unit_tests/logging/test_logger.py
Fixes #2258.
See 73d2986b78922930e11258e375cc7f2bb7ce13c8 for the initial commit that removed the original contents of `__init__.py` (from #2223).
/cc @bjwatson
=> Removing pubsub and logging as namespace packages.

CONTRIBUTING.rst, system_tests/local_test_setup.sample
1. @tseaver Didn't this have an issue somewhere?
1. Should I move the env. var. into the `environment_vars` module? I originally elected not to since it is only used once and is testing only.
=> Adding more info about setting up translate test.

google/cloud/datastore/batch.py, google/cloud/datastore/client.py, google/cloud/datastore/transaction.py, unit_tests/datastore/test_batch.py, unit_tests/datastore/test_client.py, unit_tests/datastore/test_transaction.py
- Ensuring that `Batch` methods `put()`, `delete()`, `commit()` and `rollback()` are only called when the batch is in progress.
- In `Batch.__enter__()` make sure the batch is only put on the stack after `begin()` succeeds.
- `Client.delete_multi()` and `Client.put_multi()` (and downstream methods) now call `begin()` on new `Batch` (since required to be in progress).
- `Transaction.begin()` if `begin_transaction()` API call fails, make sure to change the status to `ABORTED` before raising the exception from the failure.
Fixes #2297.
=> Making datastore batch/transaction more robust to failure.

system_tests/bigquery.py
=> Retry 400s during dataset teardown.

docs/resource-manager-api.rst
=> Add note about resource_manager projects being an alpha feature.

google/cloud/_helpers.py, google/cloud/bigtable/row_data.py, google/cloud/bigtable/table.py, google/cloud/datastore/connection.py, google/cloud/exceptions.py, google/cloud/logging/_gax.py, google/cloud/pubsub/_gax.py, system_tests/bigtable.py, system_tests/logging_.py, system_tests/pubsub.py, unit_tests/_testing.py, unit_tests/datastore/test_connection.py, unit_tests/logging/test__gax.py, unit_tests/pubsub/test__gax.py, unit_tests/test__helpers.py
~~This PR is currently incomplete (hence the "don't merge").~~
I wanted @bjwatson @geigerj et al to see what fix was needed.
This may be broken from https://github.com/googleapis/gax-python/pull/127 or this may be the intended behavior.
I filed https://github.com/googleapis/gax-python/issues/129 and https://github.com/googleapis/gax-python/issues/130 as well
=> Fixing broken exception handling after GAX 0.13.0 upgrade.

google/cloud/bigquery/_helpers.py, unit_tests/bigquery/test__helpers.py
=> Add support for Standard SQL dialect 'INT64' and 'FLOAT64' types.

.travis.yml, README.rst, docs/vision-usage.rst, google/cloud/bigquery/client.py, google/cloud/resource_manager/client.py, setup.py
This is the first release after the rename.
Also updated the account that does deployment from Silvio's to one shared by google-cloud. We'll likely need to ditch the `deploy` section and write a more customized script using `twine` once we deploy versions for each sub-package.
Closes #2264.
=> Cut 0.19.0 release.

docs/monitoring-usage.rst, google/cloud/monitoring/client.py, google/cloud/monitoring/metric.py, google/cloud/monitoring/resource.py, google/cloud/monitoring/timeseries.py, system_tests/monitoring.py, unit_tests/monitoring/test_client.py, unit_tests/monitoring/test_metric.py, unit_tests/monitoring/test_resource.py, unit_tests/monitoring/test_timeseries.py
This kicks off the PR for #1867 with the usage docs. Implementation is started and will follow this soon.
@rimey is primary reviewer here, largely just took most of his suggestions but some followup comments here:
1) Keyword arguments sounds like a good idea and not too tricky, we can do that now.
2) re: a way to write multiple TimeSeries in one go. I did add the suggested method.
Currently, there is no way to write more than one point in a TimeSeries. The only way we could batch writes is doing something like this: 
https://developers.google.com/api-client-library/python/guide/batch
This might involve some changes to the core client library here, how important do we think this is?
In general, what are the main use cases for writing multiple TimeSeries at once? Is it just batching to …
=> Monitoring Custom Metrics

docs/monitoring-usage.rst, google/cloud/monitoring/timeseries.py
From dhermes review comments:
1) Two spaces before hash in line comments
2) Single quotes
3) Trailing commas in mult-line dicts
=> Monitoring: Minor Style Fixups

system_tests/bigtable.py, system_tests/pubsub.py, system_tests/run_emulator.py, tox.ini
Also updating the pubsub system test with similar support for detection of the emulator at run-time rather than import time.
Fixes #2242.
FYI @garye this is the current output:
```
$ tox -e bigtable-emulator
GLOB sdist-make: .../google-cloud-python/setup.py
bigtable-emulator inst-nodeps: .../google-cloud-python/.tox/dist/google-cloud-0.18.0.zip
bigtable-emulator installed: enum34==1.1.6,future==0.15.2,futures==3.0.5,gax-google-logging-v2==0.8.1,gax-google-pubsub-v1==0.8.1,google-cloud==0.18.0,google-gax==0.12.5,googleapis-common-protos==1.3.4,grpc-google-logging-v2==0.8.1,grpc-google-pubsub-v1==0.8.1,grpcio==1.0.0,httplib2==0.9.2,oauth2client==3.0.0,ply==3.8,protobuf==3.0.0,psutil==4.3.1,py==1.4.31,pyasn1==0.1.9,pyasn1-modules==0.0.8,pytest==3.0.2,rsa==3.4.2,six==1.10.0
bigtable-emulator …
```
=> Adding bigtable-emulator tox environment.

google/cloud/bigquery/table.py, unit_tests/bigquery/test_table.py
=> Handle error responses in 'Table.upload_from_file'.

system_tests/bigquery.py, system_tests/pubsub.py, system_tests/retry.py
Closes #2315.
Updates coming to remove redundant tests of assertions after retry.
=> Raise exception if retry-backoff fails to pass predicate.

system_tests/bigtable.py
Five tests were being skipped due to false positves (testing `if Config.IN_EMULATOR is not None:` vs. `if Config.IN_EMULATOR:`).
=> 'Config.IN_EMULATOR' is a boolean.

google/cloud/bigquery/query.py, unit_tests/bigquery/test_query.py
=> Ensure that 'QueryResults.from_query_job' copies 'job.name'.

google/cloud/bigquery/job.py, system_tests/bigquery.py, unit_tests/bigquery/test_job.py
=> Model/parse 'job.cancel' API response correctly.

google/cloud/exceptions.py, unit_tests/test_exceptions.py
See https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2346
@dhermes looking at the magic methods and playing with `__bytes__` and `__unicode__`, the solutions I had felt really hacky. i.e. checking for `six.PY3` in `__str__` and then just calling `self.__bytes__()` instead. 
I'm not sure if it's good form to use `__future__` here but it seems to be a valid way to [solve the issue](http://python-future.org/unicode_literals.html).
=> Fix unicode message in exceptions

google/cloud/dns/client.py, google/cloud/logging/_gax.py, google/cloud/storage/_helpers.py, google/cloud/storage/bucket.py, system_tests/logging_.py, unit_tests/_testing.py, unit_tests/dns/test_client.py, unit_tests/logging/test__gax.py, unit_tests/monitoring/test_group.py, unit_tests/monitoring/test_metric.py, unit_tests/storage/test_blob.py
This is now possible after dropping support for Python 2.6.
Also tweaking a few places `dict(...)` was used to copy a dictionary to just use `.copy()`.
We also have a lot of `dict(parse_qsl(...))` going on, maybe we should use `parse_qs` and just deal with the slightly different output.
Also, we have
```
google/cloud/storage/batch.py:204:        return dict(multi._headers), body
google/cloud/storage/batch.py:319:        msg_headers = dict(sub_message._headers)
```
@tseaver I seem to recall a discussion as to why this wouldn't clobber any repeated headers, but would like some clarification.
=> Using dictionary comprehensions in place of dict().

google/__init__.py, google/cloud/__init__.py, scripts/run_pylint.py, scripts/verify_included_modules.py
This change started out in #2367 but I figured we'd get it out of the way here since it's not as much in dispute.
=> Preparing PyLint for subpackage breakup.

README.rst, google/cloud/pubsub/_gax.py, google/cloud/pubsub/client.py, google/cloud/pubsub/connection.py, google/cloud/pubsub/iam.py, google/cloud/pubsub/message.py, google/cloud/pubsub/subscription.py, google/cloud/pubsub/topic.py
It appears that the pubsub doc links have changed on us.
Before: https://cloud.google.com/pubsub/reference/rest
After: https://cloud.google.com/pubsub/docs/reference/rest
See: https://github.com/GoogleCloudPlatform/gcloud-common/issues/190
https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1609
=> Fix links to pubsub documentation.

setup.py
~~**NOTE**: Has #2392 as diffbase.~~
=> Modifying setup.py to separate duplicated content.

CONTRIBUTING.rst
In the process, also
- Replacing env. var. refs. `$FOO` with `${FOO}`
- Replacing references to `~` with `${HOME}`
- Removing outdated workarounds using `gcloud` CLI
----
Changes inspired by discussion in #2359.
=> Updating CONTRIBUTING doc to discourage "setup.py develop".

google/cloud/dns/zone.py, google/cloud/monitoring/client.py, google/cloud/pubsub/_gax.py, google/cloud/pubsub/connection.py, scripts/pylintrc_default
Reducing the max line length from 80 to 100 revealed several docstrings in violation, so those have been fixed as well.
The other change was restricting to UNIX linefeed.
----
@tseaver mentioned in https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1256#issuecomment-164012842 that the linefeed change may be problematic:
> If we ever get Windows contributors, we'll need to allow them to run the linter without barfing on their own machines.  Maybe do this check only in Travis, and document that they need to use [`core.autocrlf'](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace).
=> Tweaking new PyLint config values.

.travis.yml
As we split out into many packages, Travis won't be able to handle our deploy process, so we'll need to write a custom one.
=> Removing PyPI deploy step from Travis config.

system_tests/monitoring.py
=> Add More Retries to 400 on Query

datastore/google/cloud/datastore/connection.py, datastore/unit_tests/test_connection.py
~~**NOTE** Has #2417 as diffbase.~~
Fixes #2422.
=> Translating INVALID_ARGUMENT on datastore commit to standard exception.

docs/requirements.txt
Already updated the settings on RTD:
Followed the format suggested for `pip`: https://pip.pypa.io/en/latest/reference/pip_install/#requirements-file-format
=> Adding docs/requirements.txt to allow RTD local deps.

docs/index.rst, docs/json/json/master/overview.html
We still have documentation in `CONTRIBUTING` for how one might go about this, it just isn't necessary in the basic user-facing documentation.
Fixes #2437.
=> Removing "install from source" instructions.

Makefile.bigtable_v2, Makefile.datastore, bigtable/google/cloud/bigtable/_generated/bigtable_instance_admin_pb2.py, bigtable/google/cloud/bigtable/_generated/bigtable_pb2.py, bigtable/google/cloud/bigtable/_generated/bigtable_table_admin_pb2.py, scripts/make_datastore_grpc.py
In the process, also updating a hardcoded path in make_datastore_grpc.
Also, re-running `make generate` in each of these introduced small changes to the autogenerated bigtable modules.
(This PR needed due to subpackages moving into their own self-contained folders.)
=> Updating Bigtable and Datastore autogenerate makefiles.

core/setup.py
See https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2405#issuecomment-250037457 and #2453 for context.
=> Upgrading version of oauth2client due to GAPIC/GAX conflict.

storage/google/cloud/storage/bucket.py, storage/unit_tests/test_bucket.py
See: #2389
ACL settings are not held when copying a blob or renaming a blob.
Adds `preserve_acl` to `Bucket.copy_blob` and `Bucket.rename_blob`.
=> Preserve ACL when copying or renaming blob.

docs/monitoring-usage.rst
Fixes #2459 , cc @rimey @supriyagarg
=> Clarify docs on last 5 minutes query

index.html
Also changing a meta description to refer to Python, not Node.
Fixes #2470.
=> Updating docs landing page title to google-cloud-python.

bigquery/google/cloud/bigquery/table.py, bigquery/unit_tests/test_table.py
=> Raise from 'Table.insert_data' if schema not set.

MANIFEST.in, bigquery/google/cloud/__init__.py, bigtable/google/cloud/__init__.py, core/google/cloud/__init__.py, datastore/google/cloud/__init__.py, dns/google/cloud/__init__.py, docs/conf.py, error_reporting/google/cloud/__init__.py, language/google/cloud/__init__.py, logging/google/cloud/__init__.py, monitoring/google/cloud/__init__.py, pubsub/google/cloud/__init__.py, resource_manager/google/cloud/__init__.py, scripts/update_docs.sh, scripts/update_json_docs.sh, scripts/verify_included_modules.py, speech/google/cloud/__init__.py, storage/google/cloud/__init__.py, system_tests/bigtable.py, tox.ini, translate/google/cloud/__init__.py, vision/google/cloud/__init__.py
- Removing `graft google` from `MANIFEST` for umbrella package. It isn't needed since the umbrella package has no source
- Updating license year on copy-pasted namespace package `__init__.py` files. Done via: https://gist.github.com/dhermes/a0e88f891ffffc3ecea5c9bb2f13e4f5
- Removing unused HTML context from `docs/conf.py`
- Setting `GH_OWNER` and `GH_PROJECT_NAME` (which together make the `REPO_SLUG`) manually in the docs update scripts. This way the env. variables don't need to be set in the Travis UI / CLI. Also updating `tox.ini` to stop passing those variables through
- Removing the root package from `verify_included_modules.py` since it no longer has any source
- Updated a docstring reference to a moved class in the Bigtable system test
- Removing redundant `GOOGLE_CLOUD_*` in `tox` …
=> General clean-up after rename.

CONTRIBUTING.rst, README.rst, setup.py
Also
- Updating umbrella README to also point out the HappyBase support
- Make distinction in umbrella README between Homepage and API Documentation (they used to point to the same place)
- Updating some HTTP links to HTTPS in README and CONTRIBUTING (I was surprised to find out that semver.org and Flask docs don't have HTTPS support.)
=> Adding HappyBase to the umbrella package.

.travis.yml, scripts/run_unit_tests.py, tox.ini
This script will be extended a great deal in coming commits.
Note that this doesn't actually make the tests run faster, but it's a minimal change for a PR and I will be sending lots of changes on top of it.
Also, this fixes the current b0rken state of AppVeyor, so that's a plus.
Also, the 2nd commit uses a lesser known feature of `tox`:
- http://tox.readthedocs.io/en/latest/config.html#factors-and-factor-conditional-settings
- http://tox.readthedocs.io/en/latest/config-v2.html
=> Collapsing sub-package explosion in Travis config into a script.

.travis.yml, CONTRIBUTING.rst, scripts/run_unit_tests.py, tox.ini
- Upgrading the `get_tox_env()` helper to support the `TOXENV` env. var. and the current system Python
- Ditching `tox` on Travis for `py27`, `py34` and `isolated-cover`, this is because those `tox` environments just farm out the work to `tox` environments for each sub-package, so it isn't worth waiting for the extra `tox` env. setup time
- Changing back from `--tox-env-dir` to `--tox-env` flag in `run_unit_tests.py` script (it could always go back but isn't needed. Also could use the `VIRTUAL_ENV` env. var. set by the `activate` script from the `virtualenv` tool)
- Adding `py27,py34,py35` back to the `tox` env. list
- Letting `tox -e py27`, etc. allow the current Python to determine their `tox` env. value
- Allowing a subset of packages to be passed to `run_unit_tests` from the command …
=> Adding flexibility to how run_unit_tests determines what to run.

scripts/run_unit_tests.py, scripts/script_utils.py, tox.ini
**NOTE**: Has #2475 as diffbase.
=> Running restricted set of unit tests on Travis PR.

core/google/cloud/_helpers.py, datastore/google/cloud/datastore/connection.py, datastore/google/cloud/datastore/helpers.py, logging/google/cloud/logging/_gax.py, pubsub/google/cloud/pubsub/_gax.py, pubsub/google/cloud/pubsub/client.py, scripts/pylintrc_default, system_tests/pubsub.py
We share the `google` namespace with third-party packages.  PEP 8 wants "local" imports to be separated fro "third-party" imports, which is more important than pylint's attempt to group them by name alone.
=> Disable pylint's 'ungrouped-imports' error.

scripts/pycodestyle_on_repo.py, scripts/run_pylint.py, scripts/script_utils.py
Speeds it up, plus reduces spew when testing locally.
=> Use 'diff_base' for pycodestyle check, if set.

datastore/google/cloud/datastore/connection.py, datastore/unit_tests/test_connection.py
=> Catching gRPC error in datastore run_query and converting to our error.

scripts/run_unit_tests.py, scripts/script_utils.py, tox.ini
#2487 could be incorporated into this as well, since we should follow the dependencies from the local diff
=> Allowing local env. vars. to be used for running unit tests.

core/google/cloud/iterator.py, core/unit_tests/test_iterator.py, resource_manager/google/cloud/resource_manager/client.py, storage/google/cloud/storage/bucket.py, storage/google/cloud/storage/client.py
In the process, also making sure to lower `maxResults` on subsequent requests.
Fixes #1467.
=> Making max_results part of the base Iterator class.

CONTRIBUTING.rst
- Fixes upstream URL in `CONTRIBUTING.rst`.
@dhermes, this is the real issue anyway. If you think any of the other stuff from #2501 was worth while, let me know and I can add it.
Redux from #2501
=> Update upstream URI.

system_tests/storage.py
See [Travis post-merge failure in `system-tests3`](https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/165608811#L4427-L4441)
=> Py3k fix for #2506.

docs/index.rst, docs/speech-sample.rst, docs/speech-usage.rst, speech/google/cloud/speech/__init__.py, speech/google/cloud/speech/client.py, speech/google/cloud/speech/sample.py, speech/unit_tests/test_client.py, speech/unit_tests/test_sample.py
See: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2344#issuecomment-248681832
- Update `async_recognize()` and `sync_recognize()` method signatures and examples.
- Add more examples showing usage of other options.
=> Updates from #2344 for speech API.

core/google/cloud/connection.py, core/unit_tests/test_connection.py
Needed to support oddball out-of-band encryption headers for `Blob.rewrite`.
=> Allow passing extra headers to 'Connection.api_request'.

storage/google/cloud/storage/blob.py, storage/google/cloud/storage/bucket.py, storage/unit_tests/test_blob.py, storage/unit_tests/test_bucket.py
Avoids the need to plumb it through all the `upload_*` and `download_*` methods.
Convert `_set_encryption_headers(key, headers)` into a pure function, `_get_encryption_headers(key)`, returning a new dict.
Preparing for use of encryption in to-be-added `Blob.rewrite(source_blob)` method.  See: #1960.
=> Make 'encryption_key' an attribute of the Blob.

.travis.yml, scripts/travis_coveralls.sh, tox.ini
First, swapping the cover envs. in the umbrella tox config:
```
isolated-cover --> cover
cover --> umbrella-cover
```
and dropping the (now redunant) `tox -e cover` from `.travis.yml`. Finally, wrapping the `after_success:` Travis call to `tox -e coveralls` in a check to make sure it only runs on push builds (to speed up PR builds).
**NOTE**: This means that Coveralls will no longer be a check on PRs.
=> Restricting when the umbrella cover runs

docs/speech-usage.rst, speech/google/cloud/speech/client.py, speech/unit_tests/test_client.py
This adds an exception if any encoding other than `LINEAR16` is used for asyn recognition.
> Uncompressed 16-bit signed little-endian samples. This is the only encoding that may be used by AsyncRecognize.
See: https://cloud.google.com/speech/reference/rpc/google.cloud.speech.v1beta1#audioencoding
=> Tighten Speech Asynchronous encoding support.

scripts/generate_json_docs.py, scripts/make_datastore_grpc.py, scripts/run_pylint.py, scripts/run_unit_tests.py, scripts/script_utils.py, scripts/verify_included_modules.py
Alternative approach to #2487
This may expand the list, for example if `core` is among the changed packages then all downstream packages need to be tested.
Also in the process, moving `PROJECT_ROOT` variable into `script_utils` and using it in all `scripts/`.
=> Follow package dependency graph from changed packages.

speech/google/cloud/speech/client.py, speech/unit_tests/test_client.py
Handling bytes when encoding the request content was failing in Python 3.5.
Closes #2519.
=> Speech Python 3.5 encoding content - 'not JSON serializable'

storage/google/cloud/storage/blob.py, storage/unit_tests/test_blob.py, system_tests/storage.py
~~Uses #2507 as a base.~~
~~NOTE: New system tests cannot be exercised until #2509 is merged.~~
Closes: #1960.
=> Add 'Blob.rewrite' API wrapper method. 

pubsub/google/cloud/pubsub/message.py, pubsub/unit_tests/test_message.py, system_tests/pubsub.py
=> Use correct 'publishTime' field name for server-set message timestamp.

docs/pubsub-usage.rst, pubsub/google/cloud/pubsub/message.py, pubsub/unit_tests/test_message.py
This just catches the exception and then tries to use the raw data instead of decoding it.
If we want to try and verify the padding I can try mod 4 the length of the string to make sure it's padded correctly like is mentioned [here](http://stackoverflow.com/a/9807138/89702). I'm not sure this is the right way to go or if it's possibly another edge case?
Closes #2513.
=> Fix pubsub errors when receiving unencoded message.

vision/google/cloud/vision/image.py, vision/unit_tests/test_client.py, vision/unit_tests/test_image.py
Image content was not being properly encoded before being JSON serialized for the request.
Fixes #2525.
=> Properly encode image content.

bigquery/google/cloud/bigquery/job.py, bigquery/unit_tests/test_job.py
=> Capture 'query' attr when loading 'QueryJob' from JSON resource.

datastore/setup.py
/cc @jonparrott 
Note we still don't have an automated story for `twine` uploads (and can't really get one until we straighten out tags)
=> Cut 0.20.1 datastore release.

core/google/cloud/_helpers.py, core/unit_tests/test__helpers.py
If SDK configuration is missing the `project` key, then `_default_service_project()` should return `None` instead of throwing `KeyError`.
Fixes #2536
=> Return None if project key is missing.

pubsub/README.rst
Broken by back-end move w/o redirect.  Hissssss.
Closes #2541.
/cc @bjwatson
=> Fix link to pubsub API docs.

core/google/cloud/iterator.py, core/unit_tests/test_iterator.py, resource_manager/google/cloud/resource_manager/client.py, resource_manager/unit_tests/test_client.py, storage/google/cloud/storage/bucket.py, storage/google/cloud/storage/client.py, storage/unit_tests/test_bucket.py, storage/unit_tests/test_client.py, system_tests/storage.py
This is to lower the burden on implementers. The previous approach (requiring a `Page` and `Iterator` subclass) ended up causing lots of copy-pasta docstrings that were just a distraction.
Follow up to #2531.
=> Moving backend specific behavior from Page to Iterator.

core/google/cloud/iterator.py, core/unit_tests/test_iterator.py, resource_manager/google/cloud/resource_manager/client.py, resource_manager/unit_tests/test_client.py, storage/google/cloud/storage/bucket.py, storage/google/cloud/storage/client.py, storage/unit_tests/test_bucket.py, storage/unit_tests/test_client.py
Instead require `Iterator` takes:
- a well-formed path for the request
- a callable to convert a JSON item to native obj.
- (optional) the key in a response holding all items
- (optional) a `page_start` (acts as proxy for `Page.__init__`)
=> Removing Iterator and Page subclasses.

dns/google/cloud/dns/client.py, dns/google/cloud/dns/zone.py, dns/unit_tests/test_client.py, dns/unit_tests/test_zone.py
~~Alternative to #2532 with #2558 as diffbase.~~
=> Moving to iterators in DNS.

.github/ISSUE_TEMPLATE
I would guess that after the 1.0 release, there could be an elevated number of issue reports for a a little while.
Adding something like this might help us handle those more efficiently.
Reference: https://help.github.com/articles/creating-an-issue-template-for-your-repository/
LMKWYT
=> Add issue template.

storage/google/cloud/storage/blob.py, storage/google/cloud/storage/bucket.py, storage/unit_tests/test_bucket.py
=> Update Google Cloud Storage bucket classes.

bigquery/google/cloud/bigquery/dataset.py, bigquery/google/cloud/bigquery/job.py, bigquery/google/cloud/bigquery/query.py, bigquery/google/cloud/bigquery/table.py, core/google/cloud/streaming/buffered_stream.py, core/google/cloud/streaming/exceptions.py, core/google/cloud/streaming/http_wrapper.py, core/google/cloud/streaming/stream_slice.py, core/google/cloud/streaming/transfer.py, core/google/cloud/streaming/util.py, datastore/google/cloud/datastore/key.py, datastore/google/cloud/datastore/query.py, dns/google/cloud/dns/resource_record_set.py, dns/google/cloud/dns/zone.py, monitoring/google/cloud/monitoring/client.py, monitoring/google/cloud/monitoring/query.py, storage/google/cloud/storage/_helpers.py, storage/google/cloud/storage/blob.py, storage/google/cloud/storage/bucket.py, storage/google/cloud/storage/client.py
Sister PR to https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2579
=> Replaces integer with int in types and rtypes.

core/google/cloud/exceptions.py
Add the GatewayTimeout exception for when gRPC DEADLINE_EXCEEDED message is raised.
See #2574
=> Add Gateway Timeout exception.

README.rst, bigquery/README.rst, bigtable/README.rst, core/README.rst, datastore/README.rst, dns/README.rst, error_reporting/README.rst, language/README.rst, logging/README.rst, monitoring/README.rst, pubsub/README.rst, resource_manager/README.rst, speech/README.rst, storage/README.rst, translate/README.rst, vision/README.rst
Towards #2404.
FYI doing this at @jonparrott's request (not because `::` is invalid RST)
=> Replace :: with `.. code-block:: console`.

error_reporting/google/cloud/error_reporting/client.py, logging/google/cloud/logging/client.py, logging/unit_tests/test_client.py, pubsub/google/cloud/pubsub/client.py, pubsub/unit_tests/test_client.py
Currently gax can’t log nested structs, so this is a workaround to allow forced HTTP logging.
Workaround to resolve #2521 until #2552 is resolved.
=> Allows Explicitly Enabling/Disabling GAX for Logging/Pubsub

system_tests/language.py
The backend is finally recognizing "The Calling of Saint Matthew" as a work of art, rather than an event.
It has failed approximately 4 times in the 24H, e.g.: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/169633373
=> Fixing system test value in Natural Language.

docs/pubsub-usage.rst, pubsub/google/cloud/pubsub/connection.py, pubsub/google/cloud/pubsub/message.py, pubsub/google/cloud/pubsub/topic.py, pubsub/unit_tests/test_connection.py, pubsub/unit_tests/test_message.py, pubsub/unit_tests/test_subscription.py, pubsub/unit_tests/test_topic.py
Protobuf encodes pubsub messages, and google-cloud-python did as well which resulted in a double encoding of the message when protobuf was in use.
Fixes: #2577
=> Do not encode pubsub message for gRPC requests. 

core/google/cloud/iterator.py, core/unit_tests/test_iterator.py
This is in advance of supporting GAX page iterators within our Iterator class.
`Iterator.reset()` isn't a feature that a typical Python user expects to exist, and restarting an iterator can be as easy as:
```python
>>> my_iter = client.list_foo(*args, **kwargs)
>>> consume_it(my_iter)
>>> restarted_iter = client.list_foo(*args, **kwargs)
```
=> Removing Iterator.reset().

datastore/google/cloud/datastore/connection.py, datastore/unit_tests/test_connection.py
Fixes #2497.
(Relevant to #2583 as well.)
FYI @jonparrott
=> Remapping (almost) all RPC status codes to our exceptions in datastore.

docs/speech-usage.rst, speech/google/cloud/speech/__init__.py, speech/unit_tests/test_client.py
@dhermes per our discussion the other day, this moves Encoding to speech.
=> Make Encoding accessible from speech.Encoding.

logging/google/cloud/logging/_gax.py, logging/unit_tests/test__gax.py, system_tests/logging_.py
Fixes #2552.
@waprin Do you think it's worthwhile to add a system test for this / update an existing system test with a nested dictionary?
=> Allowing for arbitrarily nested dictionaries in _log_entry_mapping_pb.

datastore/google/cloud/datastore/connection.py
=> Adding _grpc_catch_rendezvous to _DatastoreAPIOverGRPC.lookup.

bigquery/unit_tests/test_client.py, core/google/cloud/iterator.py, core/unit_tests/test_iterator.py, dns/unit_tests/test_client.py, dns/unit_tests/test_zone.py, resource_manager/unit_tests/test_client.py, storage/unit_tests/test_bucket.py, storage/unit_tests/test_client.py, system_tests/storage.py
Fixes #2548. As mentioned in #2529, this came from trying to design for the case that a page of responses came from GAX instead of from an HTTP response.
I have left alone `Iterator.next_page_token` and `Iterator.page_number` for now but think the token should be moved to the `Page` and the page number should just be removed (people can just use `enumerate(iterator.pages)` if they want the page number).
~~**NOTE**: Has #2592 as diffbase.~~
=> Implement Iterator.pages and simplify items iteration

runtimeconfig/.coveragerc, runtimeconfig/MANIFEST.in, runtimeconfig/README.rst, runtimeconfig/google/__init__.py, runtimeconfig/google/cloud/__init__.py, runtimeconfig/google/cloud/runtimeconfig/__init__.py, runtimeconfig/google/cloud/runtimeconfig/_helpers.py, runtimeconfig/google/cloud/runtimeconfig/client.py, runtimeconfig/google/cloud/runtimeconfig/config.py, runtimeconfig/google/cloud/runtimeconfig/connection.py, runtimeconfig/google/cloud/runtimeconfig/variable.py, runtimeconfig/setup.cfg, runtimeconfig/setup.py, runtimeconfig/tox.ini, runtimeconfig/unit_tests/__init__.py, runtimeconfig/unit_tests/test__helpers.py, runtimeconfig/unit_tests/test_client.py, runtimeconfig/unit_tests/test_config.py, runtimeconfig/unit_tests/test_connection.py, runtimeconfig/unit_tests/test_variable.py
Supports listing and getting variables, but not the other methods of the RuntimeConfig API, since
I didn't need those, yet.
First step of https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2476
=> Add support for RuntimeConfig API.

runtimeconfig/unit_tests/test_config.py
Broken by simultaneous merges of #2594 and #2485.
/fyi @tswast
See broken builds:
https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-python/build/1.0.826.master
=> Fixing b0rken runtimeconfig unit tests.

core/google/cloud/_testing.py, core/google/cloud/iterator.py, core/unit_tests/test_iterator.py, docs/pubsub_snippets.py, pubsub/google/cloud/pubsub/_gax.py, pubsub/google/cloud/pubsub/client.py, pubsub/google/cloud/pubsub/connection.py, pubsub/unit_tests/test__gax.py, pubsub/unit_tests/test_client.py, pubsub/unit_tests/test_connection.py, system_tests/pubsub.py
In the process, had to add custom support for the GAX page iterator in our core Iterator implementation.
@tseaver @jonparrott I am sending this out as-is hoping for some feedback (`list_subscriptions` and `topic_list_subscriptions` also need to be done). I don't feel that great about the way I did custom paging in `Iterator`, maybe it's worth defining a GAX subclass of `Iterator`?
Also, in order to avoid too many radical changes to the code, I punted on getting a `client` into the `Iterator` returned by the `_gax` / `connection` implementations. As can be seen by the unit tests, this effectively makes them useless (more-so in the HTTP case than in the GAX case). I'd be happy to send a follow-up PR to make `client` accessible in the `_PublisherAPI` implementation, but again, wanted to make …
=> Using Iterators for list_topics() in Pub/Sub.

docs/speech-usage.rst, speech/google/cloud/speech/__init__.py, speech/google/cloud/speech/client.py, speech/google/cloud/speech/operation.py, speech/google/cloud/speech/transcript.py, speech/unit_tests/test_client.py, speech/unit_tests/test_transcript.py
In the spirit of smaller PRs. I started switching sync to GAPIC again and I realized that this is required first.
=> Use Transcript object in sync and async.

speech/google/cloud/speech/_gax.py, speech/google/cloud/speech/client.py, speech/google/cloud/speech/transcript.py, speech/setup.py, speech/unit_tests/test_client.py
This adds GAPIC support to speech sync_recognize().
=> Add Speech GAPIC for sync_recognize.

docs/speech-usage.rst
A small message stating that `google-cloud-speech` isn't released yet.
See #2515.
=> Add message about API not being available yet.

storage/google/cloud/storage/bucket.py
Bucket CORS property docs only say retrieve but it actually has a setter as well.
See #1838.
=> Mention that cors property has a setter.

bigquery/google/cloud/bigquery/client.py, core/google/cloud/_testing.py, core/google/cloud/iterator.py, core/unit_tests/test_iterator.py, dns/google/cloud/dns/client.py, dns/google/cloud/dns/zone.py, logging/unit_tests/test__gax.py, pubsub/google/cloud/pubsub/_gax.py, pubsub/google/cloud/pubsub/connection.py, pubsub/unit_tests/test__gax.py, pubsub/unit_tests/test_client.py, resource_manager/google/cloud/resource_manager/client.py, resource_manager/unit_tests/test_client.py, runtimeconfig/google/cloud/runtimeconfig/config.py, runtimeconfig/unit_tests/test_client.py, runtimeconfig/unit_tests/test_config.py, runtimeconfig/unit_tests/test_variable.py, storage/google/cloud/storage/bucket.py, storage/google/cloud/storage/client.py, storage/unit_tests/test_bucket.py, storage/unit_tests/test_client.py
**NOTE**: I'm happy to split this PR into tiny PRs if it makes review easy, though the commits are all pretty compact, so it should be reviewable commit-by-commit.
=> Refactor iterator to separate into HTTP/GAX iterators

docs/pubsub_snippets.py, pubsub/google/cloud/pubsub/_gax.py, pubsub/google/cloud/pubsub/connection.py, pubsub/google/cloud/pubsub/topic.py, pubsub/unit_tests/test__gax.py, pubsub/unit_tests/test_connection.py, pubsub/unit_tests/test_topic.py, system_tests/pubsub.py
~~**NOTE**: Has #2617 as diffbase, though has only one commit.~~
**NOTE**: `_item_to_subscription` is identically defined in `_gax` and `connection`, since in either case the API just returns strings.
Also worth noting that the mocks in the unit tests were returning values different from what the actual responses returned.
=> Converting Pub/Sub topic->list_subscriptions to iterator.

core/google/cloud/_helpers.py, core/google/cloud/_testing.py, core/google/cloud/exceptions.py
This is because a relative import (in Python 2.7) was causing failures when `google.cloud.grpc` was side-by-side with `google.cloud._helpers`, etc.
For example, see the failure: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/171149390#L1738-L1750
FYI @geigerj @bjwatson 
To repro (before this PR):
```
$ cd ${GIT_ROOT}
$ tox -e system-tests --recreate --notest
$ source .tox/system-tests/bin/activate
$ .tox/system-tests/bin/py.test system_tests/datastore.py --pdb
...
>       transport_creds = grpc.ssl_channel_credentials()
E       AttributeError: 'module' object has no attribute 'ssl_channel_credentials'
.tox/system-tests/local/lib/python2.7/site-packages/google/cloud/_helpers.py:643: AttributeError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> …
```
=> Using absolute imports in core modules that import grpc.

core/google/cloud/operation.py
Usually `prefix` is passed to `def _compute_type_url(klass, prefix)` so this should be a low/no impact change.
However I don't see where Bigtable passes `prefix`...
=> Actual type_url URI is type.googleapis.com.

speech/google/cloud/speech/_gax.py, speech/unit_tests/test__gax.py
Since this actually returned `StreamingRecognizeRequest`, I renamed it to `_make_streaming_request`.
=> Add _make_streaming_request, formerly _make_streaming_config.

docs/speech-usage.rst, speech/google/cloud/speech/operation.py, speech/unit_tests/test_operation.py
@dhermes mentioned this in a previous review.
This is correct and I also cleaned up the docs.
In my testing with async, I haven't gotten more than one alternative to show up, even whith `max_alternatives=2`. So that's why there isn't two in the doc example.
=> Clean up async docs and unify for future GAPIC async.

docs/pubsub_snippets.py, pubsub/google/cloud/pubsub/_gax.py, pubsub/google/cloud/pubsub/client.py, pubsub/google/cloud/pubsub/connection.py, pubsub/unit_tests/test__gax.py, pubsub/unit_tests/test_client.py, pubsub/unit_tests/test_connection.py
There is surprisingly no system test for `Client.list_subscriptions()`. After seeing how different the implementations of `Client.list_subscriptions()` and `Topic.list_subscriptions()` are, I am strongly for adding such a system test.
~~Sending this out without fixing unit tests to get it in the hands of reviewers. The unit tests may take me a non-trivial time, but I am working on them.~~
=> Converting Pub/Sub client->list_subscriptions to iterator.

speech/google/cloud/speech/client.py, speech/unit_tests/test_client.py
`Operation.poll` uses the `connection` to make the request.  This was missed in the tests since they set `connection` to `_Connection()`.
=> Expose connection property on _JSONSpeechAPI.

speech/google/cloud/speech/transcript.py, speech/unit_tests/test_transcript.py
When `max_alternitives` > 1, the `confidence` field is omitted entirely. So `Transcript` needs to set `confidence` to `None`.
```
{
"results": [
{
"alternatives": [
{
"transcript": "hello thank you for using Google Cloud platform",
"confidence": 0.95869493
},
{
"transcript": "thank you for using Google Cloud platform"
},
{
"transcript": "hello thank you for using Google Cloud platforms"
}
]
}
]
}
```
=> Allow Transcript to handle missing 'confidence' fields

bigtable/google/cloud/bigtable/cluster.py, bigtable/google/cloud/bigtable/instance.py, bigtable/unit_tests/test_cluster.py, bigtable/unit_tests/test_instance.py, core/google/cloud/operation.py, core/unit_tests/test_operation.py
This is in preparation to support JSON/HTTP operations as well and also to ensure that **all** of the operation PB is parsed when polling.
=> Re-factoring Operation base class.

bigtable/google/cloud/bigtable/cluster.py, bigtable/google/cloud/bigtable/instance.py, bigtable/unit_tests/test_cluster.py, bigtable/unit_tests/test_instance.py, core/google/cloud/operation.py, core/unit_tests/test_operation.py
Also renaming register_type_url to register_type.
~~**NOTE**: Has #2641 as diffbase~~
=> Make type_url optional when registering types.

core/google/cloud/operation.py, core/unit_tests/test_operation.py
Will likely need updates to Speech operation class.
~~**NOTE**: Has #2641 as diffbase.~~
=> Adding HTTP support to core Operation class.

core/google/cloud/iterator.py, core/unit_tests/test_iterator.py, docs/logging-usage.rst, logging/README.rst, logging/google/cloud/logging/_gax.py, logging/google/cloud/logging/_helpers.py, logging/google/cloud/logging/client.py, logging/google/cloud/logging/connection.py, logging/google/cloud/logging/logger.py, logging/unit_tests/test__gax.py, logging/unit_tests/test__helpers.py, logging/unit_tests/test_client.py, logging/unit_tests/test_connection.py, logging/unit_tests/test_logger.py, system_tests/logging_.py
@waprin @jonparrott I just realized how weird the logging HTTP/JSON API is. For `/entries:list`, [POST is used](https://cloud.google.com/logging/docs/api/reference/rest/v2/entries/list) instead of GET, and the "query params" come in the payload instead of as query params.
~~Just as #2633 started, I'm sending this out without fixing unit tests to get it in the hands of reviewers. The unit tests may take me a non-trivial time, but I am working on them.~~
=> Converting Logging client->list_entries to iterator.

speech/google/cloud/speech/metadata.py, system_tests/speech.py
This adds JSON/REST system tests for speech's `async_recognize()` method.
=> Add speech async JSON/REST system tests.

speech/google/cloud/speech/_gax.py, speech/google/cloud/speech/sample.py, speech/unit_tests/test__gax.py
This method creates the configuration request before making content requests and yields them to the caller.
=> Add _stream_requests() for managing speech streaming configuration

logging/google/cloud/logging/_gax.py, logging/google/cloud/logging/client.py, logging/google/cloud/logging/connection.py, logging/unit_tests/test__gax.py, logging/unit_tests/test_client.py, logging/unit_tests/test_connection.py
This is in preparation for making `list_sinks()` and `list_metrics()` use `Iterator`.
=> Passing Client through to low-level logging API objects.

logging/google/cloud/logging/client.py, logging/unit_tests/test_client.py
These changes are also in #2652 (just so the tests would pass) but they are simple enough to stand on their own.
/cc @waprin
=> Using Logging client's use_gax attr. in API properties.

datastore/google/cloud/datastore/__init__.py, docs/datastore-usage.rst, docs/index.rst, scripts/verify_included_modules.py
This in turn required a fix in verify_included_modules to turn `__init__.py` files into the correct module / package name.
This is towards getting doctests running in `datastore`
=> Add datastore.__init__ to docs.

bigquery/google/cloud/bigquery/_helpers.py, bigquery/google/cloud/bigquery/dataset.py, bigquery/google/cloud/bigquery/table.py, bigquery/unit_tests/test_dataset.py, bigquery/unit_tests/test_table.py, core/google/cloud/iterator.py, docs/bigquery-usage.rst, docs/bigquery_snippets.py, scripts/run_pylint.py, system_tests/bigquery.py
Follow up to #2561. This only covers `Dataset.list_tables()` and `Table.fetch_data()`. It may also be "correct" to use an Iterator in
- `QueryResults.fetch_data`
- `QueryResults.run` (via `QueryResults._build_resource`)
but I wanted to get eyes on this change first / opinion from the original author (@tseaver) before moving forward.
=> Move BigQuery list_ methods to use iterators

docs/logging-usage.rst, logging/google/cloud/logging/_gax.py, logging/google/cloud/logging/client.py, logging/google/cloud/logging/connection.py, logging/unit_tests/test__gax.py, logging/unit_tests/test_client.py, logging/unit_tests/test_connection.py, system_tests/logging_.py
~~**NOTE**: Has #2651 as diffbase. Unit test changes will be forthcoming.~~
=> Updating list_metrics() to Iterator pattern.

datastore/google/cloud/datastore/client.py, datastore/google/cloud/datastore/connection.py, datastore/google/cloud/datastore/entity.py, datastore/google/cloud/datastore/key.py, datastore/google/cloud/datastore/transaction.py, docs/bigquery-usage.rst, docs/dns-usage.rst, docs/error-reporting-usage.rst, docs/logging-usage.rst, docs/monitoring-usage.rst, docs/pubsub-usage.rst, error_reporting/google/cloud/error_reporting/client.py, logging/google/cloud/logging/handlers/handlers.py, storage/google/cloud/storage/client.py
This way we can gradually turn them on with **doctest** and make sure they work piece by piece.
Also converted some implicit code blocks (`::`) and some implicit doctest blocks (`:` followed by `>>>`) into explicit code blocks.
Related to #2656.
-----
Aside: Where did these changes come from? I started a branch to run datastore doctests side-by-side with system tests. Before over-engineering some handrolled solution I just wanted to get `sphinx-build -b doctest` working. So, each of these changes came from modules that resulted in failed doctests. Not all of the changes were actually interpreted as doctests (e.g. implicit code blocks via `::`) however, isolating them / designating them as `.. code-block:: python` gives a clearer target to come back at a later time and convert into a …
=> Removing explicit (and implicit) doctest blocks from Sphinx docs.

docs/index.rst, docs/speech-alternative.rst, docs/speech-transcript.rst, speech/google/cloud/speech/__init__.py, speech/google/cloud/speech/_gax.py, speech/google/cloud/speech/alternative.py, speech/google/cloud/speech/client.py, speech/google/cloud/speech/operation.py, speech/unit_tests/test_alternative.py, speech/unit_tests/test_client.py, speech/unit_tests/test_operation.py, system_tests/speech.py
=> Rename Transcript to Alternative.

speech/google/cloud/speech/client.py
I mentioned this in #2664 and this delivers on it.
We should also get rid of all the instances of this in other packages. LMK what you both think (and @jonparrott I'd be interested in what you think, i.e. importing `grpc` on GAE)
=> Removing ImportError check in Speech client.

speech/google/cloud/speech/_gax.py, speech/google/cloud/speech/client.py, speech/setup.py, speech/unit_tests/test_client.py, system_tests/speech.py
~~This will need #2661 in order for travis-ci to pass since I don't need `metadata.py` and `operation.py` after @dhermes refactored the core `operation.py`@ Thanks!~~
@dhermes, I think we talked about this back and forth a little bit, but as you can see from the system tests, the surface is much different between `sync_recognize()`'s results and `async_recognize()`'s results.
There will be some updates for the gRPC version of `sync_recognize()` that will follow this as well.
=> Add speech async gapic

speech/unit_tests/test_client.py
Some test cleanup that was missed or not relevant on the #2663 PR.
=> Speech unit tests cleanup.

bigquery/README.rst, bigtable/README.rst, core/README.rst, datastore/README.rst, dns/README.rst, error_reporting/README.rst, language/README.rst, logging/README.rst, monitoring/README.rst, pubsub/README.rst, resource_manager/README.rst, storage/README.rst, translate/README.rst, vision/README.rst
`runtimeconfig` and `speech` don't get badges because they aren't on PyPI yet
- @tswast what is the plan for publishing `runtimeconfig`?
- @daspecster can you add the "add badge to README" to your release checklist for `speech`?
=> Adding PyPI badges to package READMEs.

scripts/generate_json_docs.py, tox.ini
Here's an example of what I was talking about in https://github.com/GoogleCloudPlatform/gcloud-python/pull/2019#issuecomment-234672491.
pycodestyle reference: https://github.com/PyCQA/pycodestyle/issues/550
=> Change [pep8]-> [pycodestyle] in tox.ini

core/google/cloud/_helpers.py, core/unit_tests/test__helpers.py, logging/google/cloud/logging/_gax.py, logging/google/cloud/logging/client.py, logging/unit_tests/test__gax.py, logging/unit_tests/test_client.py, pubsub/google/cloud/pubsub/_gax.py, pubsub/unit_tests/test__gax.py, speech/google/cloud/speech/_gax.py, speech/unit_tests/test_client.py
Fixes #2631. @jonparrott I'm not sure if your work makes this a temporary fix or a permanent one?
Also, some of these unit tests I just edited definitely made me shudder ¯\\_(ツ)\_/¯
/cc @bjwatson
=> Explicitly passing a channel to GAPIC-generated API classes

docs/index.rst, docs/runtimeconfig-client.rst, docs/runtimeconfig-config.rst, docs/runtimeconfig-usage.rst, docs/runtimeconfig-variable.rst, scripts/verify_included_modules.py, tox.ini
The runtimeconfig-usage doc (or the `runtimeconfig/google/cloud/runtimeconfig/__init__.py` file) should add some examples of library usage.
@tswast once this is merged, care to take the reins on adding some usage examples?
=> Adding docs for the Runtime Config API.

core/unit_tests/streaming/test_transfer.py, docs/bigquery_snippets.py, docs/pubsub_snippets.py
Failure e.g.: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/173368127
=> Lint fixes needed for the latest (2.1) pycodestyle.

core/google/cloud/_helpers.py, core/unit_tests/test__helpers.py
See https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1783#issuecomment-258663547
=> Handle missing nanos.

docs/index.rst, docs/logging-stdlib-usage.rst, docs/logging-usage.rst, docs/logging_snippets.py
Move usage docs for integration with Python stdlib 'logging' module into a separate file, sorted in front of the relevant API docs.
Reworks #2556 after other merges (iterators, doctest removal) made fixing that PRs branch too painful.
=> Convert logging doctest examples to testable snippets.

docs/logging_snippets.py
See: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/174057513#L1262
I'm going to merge ASAP to get the build green.
=> Putting 2 empty lines after function definiton in logging snippets.

bigquery/tox.ini, bigtable/tox.ini, datastore/tox.ini, dns/tox.ini, error_reporting/tox.ini, language/tox.ini, logging/tox.ini, monitoring/tox.ini, pubsub/tox.ini, resource_manager/tox.ini, runtimeconfig/tox.ini, speech/tox.ini, storage/tox.ini, tox.ini, translate/tox.ini, vision/tox.ini
This is done by manually installing via `pip install --upgrade` every time a command is run.
This is suboptimal for many reasons, but is a less contentious fix than #2698 and can at least be a stop-gap until #2698 is merged / agreed on.
=> Keeping local (filesystem) deps from going stale in tox.ini

docs/speech-usage.rst, speech/google/cloud/speech/_gax.py, speech/google/cloud/speech/client.py, speech/unit_tests/test__gax.py, speech/unit_tests/test_client.py, system_tests/speech.py
Towards #2522. Add `streaming_recognition()` to speech API.
~~I will rebase #2676 before merging.~~
=> Add speech streaming recognition.

.travis.yml
~~Also removing unit tests on Travis for Python 3.4 (to keep the builds fast, if possible).~~
=> Adding Python 3.5 on Travis.

.travis.yml, circle.yml, docs/logging_snippets.py, scripts/coveralls.sh, system_tests/system_test_utils.py, tox.ini
Trying out CircleCI in earnest since Travis throttles us every day.
Most of our tooling is Travis centric, so this alone is insufficient, but it's worth seeing if we can at least go green on Circle CI.
I have been working on https://github.com/dhermes/ci-diff-helper in the last few weeks, so hopefully I can factor out our Travis-dependent code and replace it with more generic "help me in any CI" code.
/cc @omaray @jgeewax @jonparrott
=> Adding basic CircleCI configuration.

datastore/google/cloud/datastore/client.py, datastore/google/cloud/datastore/query.py, datastore/unit_tests/test_query.py, system_tests/clear_datastore.py, system_tests/datastore.py
I considered
- Making `offset` and `end_cursor` read-only public properties on the subclass
- Making a `@property` alias `start_cursor` that just returns the value of `next_page_token`
- Making a `@property` alias `limit` that just returns the value of `max_results`
I elected not to make anything **new** public since the original implementation didn't.
@jonparrott PTAL as well (do you think this will be too jarring a change?).
=> Migrate datastore iterator to use base iterator class

speech/README.rst
This adds the PyPI badges to the speech README.
I was waiting on this but since we have the placeholder package on PyPI I guess this can go anytime.
=> Add PyPI badges for speech

speech/google/cloud/speech/_gax.py, speech/unit_tests/test__gax.py, system_tests/speech.py
I believe this is the correct resolution to 
> Update SpeechContext in tests. See: #2700.
mentioned in #2522.
Speech streaming wasn't converting the list of hints to an instance of `SpeechContext` before flight.
=> Fix bug with speech streaming speech_context.

README.rst, runtimeconfig/README.rst, setup.py
Also updating Runtime Config README with badges and updating the main README to refer to the Runtime Config API.
Worth noting that I just manually push https://pypi.python.org/pypi/google-cloud-runtimeconfig from 7e2eb335346ff45ce972df0b051114dab23ac022 via:
```
$ cd runtimeconfig
$ python setup.py sdist bdist_wheel
$ twine upload dist/*
```
=> Adding Runtime Config API to umbrella config.

tox.ini
Also re-factoring the tox config a little bit to reuse a base passenv rather than passing around the system-tests passenv everywhere.
See https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/119 for an example failure that shouldn't have failed (since the env. var. is set in the CircleCI UI).
=> Passing through COVERALLS_REPO_TOKEN to tox coveralls env.

docs/index.rst, docs/speech-result.rst, docs/speech-usage.rst, speech/google/cloud/speech/client.py, speech/google/cloud/speech/result.py, speech/unit_tests/test_client.py, system_tests/speech.py
Towards #2522.
This changes the surface, since `is_final` and `stability` are per-result and not a per-alternative.
=> Add stability information to streaming results.

tox.ini
Also skipping the install (which would install from PyPI if the localdeps weren't added). The deps are not needed since the lint tools just reads the source.
=> Removing local dependencies from lint tox env.

circle.yml
This way CircleCI can ignore this branch for builds.
I'm fairly certain this will mean we now serve the file https://googlecloudplatform.github.io/google-cloud-python/circle.yml which makes me sad. Also empirically it seems that CircleCI won't pick up `.circle.yml`, only `circle.yml`, so we don't really have a choice.
And this is annoying:
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/tree/gh-pages
=> Adding CircleCI config to gh-pages branch.

bigquery/tox.ini, bigquery/unit_tests/test_table.py, datastore/tox.ini, datastore/unit_tests/test__http.py, datastore/unit_tests/test_client.py, storage/tox.ini, storage/unit_tests/test__helpers.py, storage/unit_tests/test_blob.py, storage/unit_tests/test_bucket.py, tox.ini
This was done only in bigquery, datastore and storage packages. Still needs updates in bigtable, core, logging, monitoring, pubsub and speech.
From discussion with @tseaver in #2681.
=> Dropping usage of _Monkey in favor of mock.patch.

docs/vision-usage.rst, vision/google/cloud/vision/image.py, vision/unit_tests/test_client.py
This is a step towards adding the manual detect method.
See: #2697
=> Refactor _detect_annotation() to support all annotation types.

docs/speech-usage.rst, speech/google/cloud/speech/client.py, speech/google/cloud/speech/sample.py, speech/unit_tests/test_client.py, system_tests/speech.py
Cleans up the surface a little bit but moving `sync_recognize`, `async_recognize` and `streaming_recognize` to the `Sample` class.
Fixes #2516.
=> Move speech methods to sample.

logging/tox.ini, logging/unit_tests/test__gax.py, logging/unit_tests/test__helpers.py, logging/unit_tests/test_client.py, pubsub/tox.ini, pubsub/unit_tests/test__gax.py, pubsub/unit_tests/test__http.py, pubsub/unit_tests/test_client.py, pubsub/unit_tests/test_topic.py
PS I didn't run `tox -e lint` locally, so fingers crossed. Naughty naughty.
=> Removing use of _Monkey in pubsub and logging.

core/google/cloud/streaming/transfer.py, system_tests/storage.py
=> Pass headers for streaming download.

docs/speech-usage.rst
Last checkbox for releasing was to remove the warning about `google-cloud-speech` not being available on PyPI.
Do not merge until **after** release to PyPI.
=> Remove speech package not yet released warning.

bigquery/tox.ini, bigtable/tox.ini, datastore/tox.ini, dns/tox.ini, docs/requirements.txt, error_reporting/tox.ini, language/tox.ini, logging/tox.ini, monitoring/tox.ini, pubsub/tox.ini, resource_manager/tox.ini, runtimeconfig/tox.ini, speech/tox.ini, storage/tox.ini, tox.ini, translate/tox.ini, vision/tox.ini
Also
- adding RTD  dependency for runtimeconfig.
- adding local paths to umbrella tox config "deps"
as was done in #2733.
=> Fixing accidental removal of {localdeps}

system_tests/language.py
The API has started returning metadata, e.g.
{u'mid': u'/m/020bg'}
and has added "painter" as a mention of Michelangelo.
=> Accounting extra data in language system test.

monitoring/tox.ini, monitoring/unit_tests/test_client.py, monitoring/unit_tests/test_query.py
Drops `_Monkey` usage from Monitoring API tests in favor of `mock.patch()`.
=> Swap _Monkey for mock.patch().

language/tox.ini, language/unit_tests/test_client.py, language/unit_tests/test_document.py
~~Also using PEP8 valid names in place of `_makeOne` and `_getTargetClass` and making all the `_get_target_class` methods a `@staticmethod` (since they don't use self).~~
@tseaver LMKWYT, I know you are somewhat unsure of the `mock` library, so I wanted to give it a spin here to see what you think.
=> Use mock library in natural language tests.

vision/google/cloud/vision/image.py, vision/unit_tests/test_client.py
Fixes #2749.
- Added tests for no results coming from service.
- Fixed bug introduced by #2712.
=> Fix vision error when no results returned.

bigtable/google/cloud/bigtable/client.py, bigtable/google/cloud/bigtable/instance.py, bigtable/google/cloud/bigtable/row.py, docs/bigtable-client-intro.rst, docs/bigtable-data-api.rst, docs/bigtable-instance-api.rst, docs/bigtable-row-filters.rst, docs/bigtable-table-api.rst, docs/bigtable-usage.rst
Summary of edits:
* "a instance" -> "an instance" consistency (some are correct, some not)
* removed extraneous words, added missing words in sentences
* minor grammatical edits for readability
=> Fixed grammar in comments and docs.

tox.ini
Addresses #2670 
CC @jonparrott @dhermes
=> Update tox to run system tests under Python 3.5 instead of 3.4

vision/google/cloud/vision/color.py, vision/unit_tests/test_color.py
Fixes #2757 
I didn't add tests for the other classes, but I can if needed. Honestly, I'm not sure if and when to count on the data being there so my strategy was to try and default to `None`.
=> Expect vision response data to have missing keys.

bigquery/setup.py, bigtable/setup.py, datastore/setup.py, dns/setup.py, error_reporting/setup.py, language/setup.py, logging/setup.py, monitoring/setup.py, pubsub/setup.py, resource_manager/setup.py, runtimeconfig/setup.py, storage/setup.py, translate/setup.py, vision/setup.py
Installing a prior version of a package or umbrella pulls in an incompatible version of `google-cloud-core` since it has a version specifier of `>=`.
Ref: https://www.python.org/dev/peps/pep-0440/#compatible-release
Fixes #2742.
=> Set core version compatible specifier to packages.

docs/index.rst, docs/logging-handlers-app-engine.rst, docs/logging-handlers-container-engine.rst, docs/logging-usage.rst, docs/logging_snippets.py, logging/google/cloud/logging/client.py, logging/google/cloud/logging/handlers/__init__.py, logging/google/cloud/logging/handlers/_helpers.py, logging/google/cloud/logging/handlers/app_engine.py, logging/google/cloud/logging/handlers/container_engine.py, logging/google/cloud/logging/handlers/handlers.py, logging/google/cloud/logging/handlers/transports/background_thread.py, logging/unit_tests/handlers/test_app_engine.py, logging/unit_tests/handlers/test_container_engine.py, logging/unit_tests/handlers/test_handlers.py, logging/unit_tests/handlers/transports/test_background_thread.py, logging/unit_tests/handlers/transports/test_sync.py, logging/unit_tests/test_client.py
On GAE and GKE with the plugin installed, there is a fluentd plugin that collects logs from files. However without the right formatting, metadata like log_level is lost. Furthermore, the fluentd agents are configured to set the  correct resources types, which could be  done in the main handler as well, but it’s easier to rely on the fluentd configurations.
This adds two new handlers and some helper functions to detect when they should be used.
=> Add GAE and GKE fluentd Handlers

core/google/cloud/_testing.py, pubsub/google/cloud/pubsub/_gax.py, pubsub/unit_tests/test__gax.py
Based from #2575.
Implement exception for pubsub subscription pull.
Fixes: #2574
=> Add gateway timeout to pubsub pull

pubsub/google/cloud/pubsub/_http.py, pubsub/unit_tests/test__http.py
Fixes #2771 
This copies the `messages` variable instead of transforming it in place so that if a `commit()` fails, the messages aren't double encoded.
=> Fix double encoding of messages when commit() fails.

docs/vision-usage.rst
There will be more for this to come, but I just wanted to get it accurate to the library.
As I add the features back, I will add them to the docs again.
=> Cleaning up docs and fixing typos

docs/index.rst, docs/vision-annotations.rst, docs/vision-usage.rst, vision/google/cloud/vision/annotations.py, vision/google/cloud/vision/image.py, vision/unit_tests/test_client.py
=> Add image.detect() for detecting multiple types.

vision/google/cloud/vision/annotations.py
=> Make annotation constants private.

CONTRIBUTING.rst
Updated the syntax used for headings according to:
http://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html#headings
----
See it live: https://github.com/dhermes/google-cloud-python/blob/local-contents-in-contrib/CONTRIBUTING.rst
=> Updating CONTRIBUTING doc with a contents tree at top.

docs/storage_snippets.py, storage/google/cloud/storage/__init__.py, storage/google/cloud/storage/acl.py, storage/google/cloud/storage/blob.py, storage/google/cloud/storage/bucket.py, storage/google/cloud/storage/client.py
These snippets don't run yet but the docs build and pull them.
@dhermes [suggested](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2609#issuecomment-256111601) I could merged this in before getting them to run.
I'm not sure about removing the imports for some snippets. It seems like those a nice to have?
=> Pull snippets from docstrings.

docs/vision-usage.rst, vision/google/cloud/vision/image.py, vision/tox.ini, vision/unit_tests/test_image.py
Towards #2753
Adding support to pass in a filename when instantiating an `Image`.
=> Add loading image from filename.

docs/vision-usage.rst, vision/google/cloud/vision/face.py, vision/unit_tests/test_face.py
Towards: #2753.
This is a breaking change for Vision since the names of the accessors are changing.
Is there a place we should keep track of that for releases and such?
=> Move emotions to Face class.

docs/error-reporting-usage.rst, docs/error-reporting-util.rst, docs/index.rst, error_reporting/google/cloud/error_reporting/__init__.py, error_reporting/google/cloud/error_reporting/util.py, error_reporting/tox.ini, error_reporting/unit_tests/test_util.py
=> Add Flask Helper to Error Reporting

README.rst
@jonparrott and I hang out here, it might be worth adding a link, sometimes people have smaller discussions that people feel weird filing issues for.
Maybe people think this fragments the discussion which should stay on Issues? I could see it going either way, but Kubernetes seems to have had success with Slack. /cc @jgeewax
=> Add Link to Slack Community

vision/google/cloud/vision/client.py, vision/unit_tests/test_client.py
Towards #2753 
Essentially I forgot to add this to the `client.image()` proxy.
=> Add filename parameter to client image proxy.

bigquery/google/cloud/bigquery/_helpers.py, bigquery/unit_tests/test__helpers.py, bigquery/unit_tests/test_table.py, system_tests/bigquery.py
=> Correctly model JSON repr of complex nested records.

datastore/google/cloud/datastore/__init__.py, datastore/google/cloud/datastore/entity.py, datastore/google/cloud/datastore/key.py, datastore/unit_tests/test_entity.py, system_tests/datastore.py, tox.ini
Since Travis / CircleCI won't run this by default, here is some sample output:
```
$ tox -e system-tests -- datastore
GLOB sdist-make: .../setup.py
system-tests inst-nodeps: .../.tox/dist/google-cloud-0.21.0.zip
...
system-tests runtests: commands[1] | python 
.../system_tests/attempt_system_tests.py datastore
test_it (datastore.TestDoctest) ... Running Sphinx v1.4.8
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [doctest]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] contents
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
running tests...
Document: contents …
```
=> Adding ability to run doctests with datastore system tests.

bigquery/google/cloud/bigquery/__init__.py, bigquery/google/cloud/bigquery/_helpers.py, bigquery/google/cloud/bigquery/client.py, bigquery/google/cloud/bigquery/job.py, bigquery/google/cloud/bigquery/query.py, bigquery/unit_tests/test__helpers.py, bigquery/unit_tests/test_client.py, bigquery/unit_tests/test_job.py, bigquery/unit_tests/test_query.py, docs/bigquery-usage.rst, docs/bigquery_snippets.py
=> Add support for query parameters

logging/google/cloud/logging/_gax.py, logging/setup.py, logging/unit_tests/test__gax.py, pubsub/google/cloud/pubsub/_gax.py, pubsub/setup.py, pubsub/unit_tests/test__gax.py, speech/google/cloud/speech/_gax.py, speech/setup.py, speech/unit_tests/test_client.py
In the process, ditching **hard** deps on protobufs, `grpcio`, and `google-gax` in those packages. Also had
to upgrade calls to `list_log_entries()` based on: https://github.com/googleapis/api-client-staging/pull/118/files/2bcd2875a578ae525d2aabb862cf9c131b4665f5#r90422054
/cc @geigerj @bjwatson 
@waprin I could not for the life of me figure out how to use `resource_names` instead of the deprecated `project_ids`. Can you explain? (Trying `foo` --> `project/foo` did not work)
=> Upgrading GAPIC deps to 0.14 series.

bigquery/google/cloud/bigquery/_helpers.py, bigquery/unit_tests/test__helpers.py, bigquery/unit_tests/test_job.py, bigquery/unit_tests/test_query.py
Also, distinguish parsing 'DATETIME' vs. 'TIMESTAMP' properly when processing row data.
Closes #2799.
=> Coerce query parameter values from native types to JSON-appropriate types

bigquery/google/cloud/bigquery/table.py, bigquery/unit_tests/test_table.py
=> Allow timestamp strings in 'Table.insert_data'.

bigquery/google/cloud/bigquery/_helpers.py, bigquery/unit_tests/test__helpers.py, core/google/cloud/_helpers.py, core/unit_tests/test__helpers.py, system_tests/bigquery.py
=> Marshal 'BYTES' and 'TIME' column / paramter types

core/google/cloud/_helpers.py, core/tox.ini, core/unit_tests/test__helpers.py
=> Make make_secure_channel use google-auth

bigquery/google/cloud/bigquery/client.py, bigquery/google/cloud/bigquery/dataset.py, bigquery/unit_tests/test_client.py, bigquery/unit_tests/test_dataset.py, system_tests/bigquery.py
=> Allow overriding dataset's project during construction.

storage/google/cloud/storage/bucket.py
This was caused by a new release of Sphinx (1.5) on December 5, 2016 (i.e. today).
=> Fixing bug in Bucket.delete_blobs().

bigquery/setup.py, core/setup.py, language/setup.py
H/T to
- @jmdobry for #2798 forcing the NL release
- @tseaver for #2809, #2806, #2805, #2803, #2776, #2787 and #2789 forcing the BQ release
- @jonparrott #2808, #2801, #2726 forcing the core release
Proposed tags after merge:
- `bigquery-0.22.0`
- `core-0.22.0`
- `language-0.22.0`
I'll start going through `$ git log 0.21.0..HEAD -- bigquery/ core/ language/` now to figure out release notes.
=> Cutting new releases for BigQuery, Language and Core.

bigquery/google/cloud/bigquery/_helpers.py, bigquery/unit_tests/test__helpers.py
JSON decodes the base64-encoded bits as text, which cannot be passed to 'base64.decodestring' on Py3k.
`tox -e system-tests3` was failing for me locally before this patch, and passes with it.
=> Fix 'BYTES' field handling on Py3k.

translate/google/cloud/translate/client.py, translate/unit_tests/test_client.py
Fixes #2734.
/cc @jonparrott @jgeewax
=> Removing support for API_KEY auth in translate.

docs/vision-usage.rst, vision/google/cloud/vision/face.py, vision/google/cloud/vision/likelihood.py, vision/setup.py, vision/tox.ini, vision/unit_tests/test_client.py, vision/unit_tests/test_face.py
Towards #2753
Switching `Likelihood` and `LandmarkTypes` to `Enum`'s.
=> Switch to enums and clean up names.

circle.yml, scripts/circleci_tagged_pkg.py, scripts/circleci_twine_upload.sh
See #2810 for discussion of which tags are used.
`twine upload` will "just work" since we have set the ``TWINE_USERNAME`` and ``TWINE_PASSWORD`` env. vars on CircleCI.
=> Adding helpers to push to PyPI on tags.

bigquery/unit_tests/test_client.py, bigtable/unit_tests/test_client.py, core/google/cloud/client.py, core/unit_tests/test_client.py, datastore/unit_tests/test_client.py, dns/tox.ini, dns/unit_tests/test_client.py, error_reporting/unit_tests/test_client.py, logging/unit_tests/test__gax.py, logging/unit_tests/test__http.py, logging/unit_tests/test_client.py, logging/unit_tests/test_logger.py, monitoring/unit_tests/test_client.py, pubsub/unit_tests/test__gax.py, pubsub/unit_tests/test__http.py, pubsub/unit_tests/test_client.py, pubsub/unit_tests/test_topic.py, resource_manager/tox.ini, resource_manager/unit_tests/test_client.py, runtimeconfig/tox.ini, runtimeconfig/unit_tests/test_client.py, speech/tox.ini, speech/unit_tests/test__gax.py, speech/unit_tests/test_client.py, storage/unit_tests/test_batch.py, storage/unit_tests/test_client.py, vision/unit_tests/test_client.py
=> Raise ValueError if credentials are not from google-auth

language/google/cloud/language/client.py
@dhermes Eliminates accidental conflict on common class name, 'Document'.
=> Update language docs to use explicit path to Document.

datastore/google/cloud/datastore/__init__.py, datastore/google/cloud/datastore/client.py, datastore/google/cloud/datastore/entity.py, datastore/google/cloud/datastore/key.py, datastore/google/cloud/datastore/transaction.py, system_tests/datastore.py
It's worth noting that I delegated clean-up to `system_tests/datastore.py::tearDownModule`. This is because (in my experimenting) I discovered that the `sphinx.ext.doctest` directive `testcleanup` doesn't run when the thing being tested fails. (FWIW, I think it'd be fairly easy for one of us to send a PR to the Sphinx project and fix that behavior, but that was outside the scope of this PR.)
----
To make dev a little faster I did the following:
```
$ tox -e system-tests --recreate --notest
$ source .tox/system-tests/bin/activate
$ GOOGLE_CLOUD_DISABLE_GRPC=true \
> .tox/system-tests/bin/py.test system_tests/datastore.py \
> -k TestDoctest -s -vv
```
and every time I made a change I just re-installed into the env
```
$ .tox/system-tests/bin/pip install --upgrade datastore/
```
Might be …
=> Converting remaining datastore snippets to doctests

README.rst
=> Add alpha and beta references to README.rst.

docs/vision-usage.rst
Towards #2753 
Old references to `bounding_poly` -> `bounds`.
=> Update reference to bounds.

logging/unit_tests/test_client.py
Fixes #2843. This doesn't clean up the file after but it does make it a temp file, @dhermes let me know if you think this is sufficient which I think it is.
=> Make logging unit test file a temp file

system_tests/vision.py
Towards #2753 
Adds the system tests for `detect_properties()`.
```bash
test_detect_properties_content (vision.TestVisionClientImageProperties) ... ok
test_detect_properties_filename (vision.TestVisionClientImageProperties) ... ok
test_detect_properties_gcs (vision.TestVisionClientImageProperties) ... ok
...
----------------------------------------------------------------------
Ran 18 tests in 25.420s
OK
________________________________________________________ summary ________________________________________________________
system-tests: commands succeeded
congratulations :)
```
The last method!
=> Add Vision detect_properties() system tests.

logging/unit_tests/test_client.py
Allow tempdir cleanup to work as expected on Windows.
=> Force close logging handler.

README.rst
=> Add speech to alpha list. Closes #2869

logging/google/cloud/logging/logger.py, logging/unit_tests/test_logger.py
The timestamp parameter is useful when one sends batches of log records. In this case, every log record in a batch will have the same timestamp. The timestamp equals the date of insertion in the google cloud logging API. 
If one uses the `asctime` attribute from the [LogRecord](https://docs.python.org/2/library/logging.html#logging.LogRecord) instances as timestamp value, a log record would have a propre date.
=> Add a timestamp parameter to the logger.

bigquery/google/cloud/bigquery/client.py, core/google/cloud/client.py, core/tox.ini, core/unit_tests/test_client.py, datastore/google/cloud/datastore/client.py, datastore/unit_tests/test_client.py, dns/google/cloud/dns/client.py, language/google/cloud/language/client.py, logging/google/cloud/logging/client.py, monitoring/google/cloud/monitoring/client.py, pubsub/google/cloud/pubsub/client.py, resource_manager/google/cloud/resource_manager/client.py, runtimeconfig/google/cloud/runtimeconfig/client.py, speech/google/cloud/speech/client.py, storage/google/cloud/storage/client.py, translate/google/cloud/translate/client.py, vision/google/cloud/vision/client.py
This is part of #2606. The idea behind this PR: we can drop support for `Connection` classes on a package-by-package basis rather than all at once.
/cc @tseaver and @mckoss this will have teeny implications on downstream clients
=> Remove connection from base Client class

vision/google/cloud/vision/_http.py, vision/google/cloud/vision/client.py, vision/google/cloud/vision/image.py, vision/unit_tests/test__http.py, vision/unit_tests/test_client.py
Towards #2753 for adding GAPIC support.
Separates out the REST client in preparation to add the GAPIC client alongside.
=> Separate HTTP client.

logging/google/cloud/logging/_gax.py, logging/google/cloud/logging/_http.py, logging/google/cloud/logging/handlers/transports/background_thread.py, logging/unit_tests/handlers/transports/test_background_thread.py, logging/unit_tests/test__gax.py, logging/unit_tests/test__http.py, logging/unit_tests/test_client.py
~~**NOTE**: Has #2870 as diffbase~~
=> Removing most (direct) connection usage in Logging

pubsub/google/cloud/pubsub/subscription.py, pubsub/unit_tests/test_subscription.py
=> Do not attempt to acknowledge 0 messages

circle.yml, scripts/circleci_tagged_pkg.py
@tseaver I have a feeling you could craft better regexes than me here if you feel like it.
=> Fixing regex for package deployment.

pubsub/google/cloud/pubsub/_gax.py, pubsub/google/cloud/pubsub/_http.py, pubsub/google/cloud/pubsub/client.py, pubsub/unit_tests/test__gax.py, pubsub/unit_tests/test__http.py, pubsub/unit_tests/test_client.py
~~**NOTE**: Has #2870 as diffbase.~~
=> Removing most (direct) connection usage in Pub / Sub

bigquery/google/cloud/bigquery/_helpers.py, bigquery/unit_tests/test__helpers.py, system_tests/bigquery.py
- *Not* the float-time-since-epoch-in-seconds which Bigquery uses for all other `TIMESTAMP` values. :(
- *Not* RFC3339, but the SQL-mandated format with an embedded space. :(
Closes: #2886.
/cc @tswast
=> Send TIMESTAMP query parameters as strings.

bigquery/google/cloud/bigquery/_helpers.py, bigquery/unit_tests/test__helpers.py, system_tests/bigquery.py
=> Conform to expected wire format for struct query parameters.

bigquery/google/cloud/bigquery/job.py, bigquery/unit_tests/test_job.py
Such jobs would be created via another client:  we map that configuration onto a sequence of tables containing only the one item.
Closes: #2882.
=> Accept copy jobs with single 'sourceTable' config.

vision/google/cloud/vision/_gax.py, vision/google/cloud/vision/client.py, vision/unit_tests/test__gax.py, vision/unit_tests/test_client.py
Towards #2753
TL;DR This PR just adds the beginning of the `_GAPICVisionAPI` class and `Client` branching.
I started just doing the straight up conversion but it got huge.
Then I tried just converting face annotations and that got huge.
So this is part 1 of many, hopefully small PRs to add this in.
There are a lot of classes that will need the `from_pb` added to them and also test splitting to support both since the JSON responses vary in the value names a lot from the proto responses.
So for starters this was the smallest chunk I could come up with. Next up I will be adding the `annotate` method which requires some interesting helpers to translate `Feature` and `Image`s.
=> Add a starter class for _gax.

pubsub/google/cloud/pubsub/client.py
Closes #2908
I'm not sure this is the right way to go about fixing this. But it works!
=> Fix for pubsub scope error.

vision/google/cloud/vision/_gax.py, vision/setup.py, vision/unit_tests/test__gax.py, vision/unit_tests/test_client.py
Towards #2753 
This adds two helper functions to convert internal `Image` and `Feature` classes to gRPC versions of those classes to use when making GAPIC requests.
=> Add Vision Image and Feature gRPC conversion helper functions.

bigtable/google/cloud/bigtable/client.py, bigtable/unit_tests/test_client.py, core/google/cloud/_helpers.py, core/unit_tests/test__helpers.py, system_tests/bigtable.py
Closes #2880 
/cc @nathanielmanistaatgoogle @sduskis
=> Add max_message_length for larger rows.

datastore/google/cloud/datastore/helpers.py
This way **all** public functions will be documented.
=> Removing __all__ from datastore helpers.

.travis.yml
It's worth noting that we are "one foot out the door" with Travis, so this change is just a temporary kludge to keep push builds from erroring out (due to timeout).
The "correct" long-term solution is:
-   run a nightly cron job which runs everything
-   run **everything** on "tag" builds
-   on all other non-PR builds, run a restricted set of tests based on the new changes added since the last build. It's worth noting that CircleCI makes these commits easy to access in the UI (unclear if easy in the VMs):
=> Only running 3.4 tests on PR builds.

speech/google/cloud/speech/_gax.py, speech/google/cloud/speech/client.py, speech/google/cloud/speech/sample.py, speech/unit_tests/test__gax.py, speech/unit_tests/test_client.py, speech/unit_tests/test_sample.py, system_tests/speech.py
Towards: #2842
See: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2680#discussion_r86612107
This PR attempts to handle both bytes and file objects passed to `Sample.content`.
I added `Sample.stream` to distinguish between raw bytes and a file like object.
`Sample.stream` cannot be set, and is derived from `Sample._content`, which can be either bytes or a file.
I'm sure you guys will have some great feedback for this. I'm totally open to suggestions.
=> Make sample.content handle bytes and files.

logging/google/cloud/logging/_gax.py, logging/google/cloud/logging/handlers/transports/background_thread.py, logging/unit_tests/handlers/transports/test_background_thread.py, logging/unit_tests/test__gax.py
See:
https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/191433056#L2195
This is a band-aid for now. I caused it in #2875 and will roll-back this roll-back at a later time.
@daspecster fixed a similar breakage in #2909.
=> Fixing credentials without scopes issue in logging.

storage/google/cloud/storage/blob.py, storage/unit_tests/test_blob.py
This is a super small PR which adds storage.blob property time_created (timeCreated) which I found myself needing recently. It's basically a copy paste of time_deleted. Unit test added.
=> Add storage.blob property time_created (timeCreated)

system_tests/vision.py, vision/google/cloud/vision/_gax.py, vision/google/cloud/vision/_http.py, vision/google/cloud/vision/annotations.py, vision/google/cloud/vision/entity.py, vision/google/cloud/vision/geometry.py, vision/google/cloud/vision/image.py, vision/unit_tests/test__gax.py, vision/unit_tests/test__http.py, vision/unit_tests/test_annotations.py, vision/unit_tests/test_client.py, vision/unit_tests/test_entity.py
Towards #2753 
This adds support for `EntityAnnotation` types of detection.
Face, Safe Search and Image Properties is what's left.
Also, system tests have `use_gax` set for detection types that don't yet have `from_pb` defined.
=> Add gax support for entity annotations.

core/google/cloud/_testing.py
Some APIs are beginning to pass extra error information in the `trailing_metadata` field (e.g., retry intervals).
=> Testing support for creating gRPC errors w/ tralling metadata.

resource_manager/google/cloud/resource_manager/project.py, resource_manager/unit_tests/test_project.py
Fixes #2940 by including parent field in the update.
=> Add Parent Field to Resource Manager

core/google/cloud/iterator.py
There's no mention of this handy property in the core docs, so I thought I'd add an example of its usage.
=> Make note of num_results property on iterators

system_tests/vision.py, vision/google/cloud/vision/_gax.py, vision/google/cloud/vision/annotations.py, vision/google/cloud/vision/client.py, vision/google/cloud/vision/face.py, vision/google/cloud/vision/geometry.py, vision/google/cloud/vision/image.py, vision/unit_tests/test__gax.py, vision/unit_tests/test_annotations.py, vision/unit_tests/test_client.py, vision/unit_tests/test_face.py, vision/unit_tests/test_geometry.py, vision/unit_tests/test_image.py
~Based from #2918~
This adds gRPC support for `face_detect()`.
=> Vision: Add gRPC support for face detection.

system_tests/speech.py
The score dropped for Speech and so the assertions were failing. This switches that to just type checking.
See: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/193242535#L2056
=> Assert type check instead of value for Speech.

docs/vision-usage.rst, system_tests/vision.py, vision/google/cloud/vision/annotations.py, vision/google/cloud/vision/color.py, vision/unit_tests/test_annotations.py, vision/unit_tests/test_client.py, vision/unit_tests/test_color.py
~~Based from #2922~~
Adds gRPC support for image properties detection.
=> Vision: Add gRPC support for image properties.

docs/monitoring-usage.rst
Slight typo in the docs as we use `type_` instead of the Python keyword `type`.
=> Fix monitoring usage doc

docs/vision-safe-search.rst, docs/vision-usage.rst, system_tests/vision.py, vision/google/cloud/vision/annotations.py, vision/google/cloud/vision/face.py, vision/google/cloud/vision/likelihood.py, vision/google/cloud/vision/safe_search.py, vision/unit_tests/test_annotations.py, vision/unit_tests/test_client.py, vision/unit_tests/test_safe_search.py
~~Based from #2937~~
There's a few things I don't like about this that I'll comment on. I'm not sure how to solve them right now. Maybe you guys have some ideas?
=> Vision: Add gRPC support for safe search.

system_tests/vision.py
This resolves the `text_detect` system test errors in Travis.
See: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/193935352#L2071-L2073
=> Loosen system tests for Vision Text detection.

speech/google/cloud/speech/sample.py, speech/unit_tests/test_sample.py
=> Remove default sample_rate.

docs/speech-usage.rst, speech/google/cloud/speech/_gax.py, speech/google/cloud/speech/client.py, speech/google/cloud/speech/operation.py, speech/google/cloud/speech/result.py, speech/setup.py, speech/unit_tests/test__gax.py, speech/unit_tests/test_alternative.py, speech/unit_tests/test_client.py, speech/unit_tests/test_operation.py
This commit also:
* adds `transcript` and `confidence` convenience methods
on result objects
* updates unit tests appropriately
* moves from google.cloud.grpc.* to google.cloud.proto.*
* updates dependencies accordingly
Fixes #2947.
=> Cloud Speech Veneer does not raise for > 1 result.

bigquery/google/cloud/bigquery/client.py, core/google/cloud/_helpers.py, core/google/cloud/client.py, core/unit_tests/test__helpers.py, core/unit_tests/test_client.py, dns/google/cloud/dns/client.py, logging/google/cloud/logging/client.py, monitoring/google/cloud/monitoring/client.py, pubsub/google/cloud/pubsub/client.py, runtimeconfig/google/cloud/runtimeconfig/client.py, storage/google/cloud/storage/client.py, vision/google/cloud/vision/client.py
Also using empty-tuple default as `extra_options` (avoids a branch).
=> Renaming JSONClient -> ClientWithProject.

pubsub/google/cloud/pubsub/topic.py, pubsub/unit_tests/test_topic.py
This PR adds some functionality to the Batch object:
* The ability to specify `max_messages` and have the batch
automatically call `commit` when the number of messages
gets that high.
* The ability to specify `max_interval` and have the batch
automatically commit when a publish occurs and the batch
is at least as old as the specified interval.
This is one of two changes requested by the PubSub team.
=> Pubsub batch autocommitting.

vision/google/cloud/vision/_gax.py, vision/google/cloud/vision/_http.py, vision/google/cloud/vision/image.py, vision/unit_tests/_fixtures.py, vision/unit_tests/test__gax.py, vision/unit_tests/test__http.py, vision/unit_tests/test_client.py
This just get's the under the hood changes ready for the most part.
=> Vision support for batch processing part one.

vision/google/cloud/vision/annotations.py, vision/unit_tests/test_annotations.py
=> Fix KeyError for unsupported annotation types.

bigquery/unit_tests/test_dataset.py, bigquery/unit_tests/test_job.py, bigquery/unit_tests/test_table.py, bigtable/unit_tests/test_instance.py, core/unit_tests/test_exceptions.py, datastore/google/cloud/datastore/transaction.py, datastore/unit_tests/test__http.py, datastore/unit_tests/test_batch.py, datastore/unit_tests/test_client.py, datastore/unit_tests/test_query.py, dns/google/cloud/dns/changes.py, dns/unit_tests/test_changes.py, dns/unit_tests/test_zone.py, resource_manager/unit_tests/test_project.py, runtimeconfig/unit_tests/test_config.py, runtimeconfig/unit_tests/test_variable.py, scripts/pycodestyle_on_repo.py, storage/unit_tests/test_batch.py, storage/unit_tests/test_bucket.py
These changes allow pycodestyle to pass.
Closes #2974
=> Updates for pycodestyle.

docs/speech-usage.rst, speech/google/cloud/speech/_gax.py, speech/google/cloud/speech/client.py, speech/google/cloud/speech/result.py, speech/unit_tests/test_client.py, system_tests/speech.py
This is an update to fill out the HTTP side of #2962 and I have a hacky but effective way to handle the new LRO.
I tried using the `OperationsClient` but for some reason it just kept 404ing. I'm not sure what I was doing wrong.
/cc @lukesneeringer
=> Fix Speech LRO handling and add HTTP side for multiple results. 

language/google/cloud/language/document.py, language/unit_tests/test_document.py
The language API auto-detects language if not is not provided, so defaulting to English is incorrect.
=> Do not include a default language.

language/google/cloud/language/client.py, language/unit_tests/test_client.py
This change was requested by the NL team, since we only accept GCS URLs, and `document_from_url` implies anything.
Rather than a flat rename, I am having the original method warn a `DeprecationWarning`. We do not really have a process for deprecating or keeping up with them, so for the time being I am noting the date in the docstring.
=> Rename `document_from_url` to `document_from_gcs_url`.

docs/index.rst, docs/vision-batch.rst, docs/vision-usage.rst, system_tests/vision.py, vision/google/cloud/vision/_gax.py, vision/google/cloud/vision/_http.py, vision/google/cloud/vision/batch.py, vision/google/cloud/vision/client.py, vision/google/cloud/vision/image.py, vision/unit_tests/test__gax.py, vision/unit_tests/test__http.py, vision/unit_tests/test_batch.py, vision/unit_tests/test_client.py
I wasn't sure the best way to add the context manager to `Batch` since there needs to be a result returned.  I'm not sure of a good way to do that from a context manager's `__exit__` without attaching the results to something.
Closes #2897
=> Vision: Add batch processing

storage/google/cloud/storage/blob.py, storage/unit_tests/test_blob.py
Resolves #1240
(Aside: wow this code is complicated)
=> Add create_resumable_upload_session

bigquery/google/cloud/bigquery/query.py, bigquery/unit_tests/test_query.py
The first commit adds explicit unit test coverage for the scalar properties of `Query` (previously covered implicitly via tests of other methods).
The second commit adds the convert-to-int logic, because the back-end is marshalling integers as JSON-be-damned strings.
Closes #3004.
=>  Return int from 'total_rows'/'total_bytes_processed', if present.

bigquery/google/cloud/bigquery/query.py, bigquery/unit_tests/test_query.py
If the `_job` attribute is not set, but we have a `jobId` in our properties, we still don't want to re-run the query.
Closes #3003.
=> Check running status via 'job' property.

speech/unit_tests/test_client.py, vision/unit_tests/test_annotations.py, vision/unit_tests/test_entity.py
Build is failing due to float precision.
See: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/876
Clarification: `float` (i.e. single) vs. `double`. Double values are being cast down into `float` (which is correct, but is also a breaking change). For example
```python
>>> (0.9224355).hex()
'0x1.d849774256bcap-1'
>>> from google.cloud.grpc.vision.v1 import image_annotator_pb2
>>> e = image_annotator_pb2.EntityAnnotation(score=0.9224355)
>>> e.score
0.9224355220794678
>>> e.score.hex()
'0x1.d849780000000p-1'
```
=> Fix build failing with float precision mismatch

bigtable/google/cloud/bigtable/row_data.py, bigtable/unit_tests/test_row_data.py
=> Remove invalid chunk validation

bigtable/setup.py, dns/setup.py, error_reporting/setup.py, language/setup.py, monitoring/setup.py, pubsub/setup.py, resource_manager/setup.py, speech/setup.py, translate/setup.py, vision/setup.py
=> Update Beta classifiers to Alpha for specified services.

docs/storage_snippets.py, storage/google/cloud/storage/bucket.py, storage/unit_tests/test_bucket.py
=> Add generate_upload_policy

bigquery/unit_tests/test__helpers.py, bigquery/unit_tests/test_table.py, core/unit_tests/test__helpers.py, error_reporting/unit_tests/test__gax.py, error_reporting/unit_tests/test__logging.py, error_reporting/unit_tests/test_client.py, logging/unit_tests/handlers/test_handlers.py, logging/unit_tests/handlers/transports/test_background_thread.py, logging/unit_tests/handlers/transports/test_base.py, logging/unit_tests/handlers/transports/test_sync.py, logging/unit_tests/test__gax.py, spanner/unit_tests/test__helpers.py, spanner/unit_tests/test_batch.py, spanner/unit_tests/test_client.py, spanner/unit_tests/test_database.py, spanner/unit_tests/test_instance.py, spanner/unit_tests/test_keyset.py, spanner/unit_tests/test_pool.py, spanner/unit_tests/test_session.py, spanner/unit_tests/test_snapshot.py, spanner/unit_tests/test_streamed.py, spanner/unit_tests/test_transaction.py
Mostly just changing /_makeOne/_make_one`/ and adding a space after the imports of unit_tests.
=> Spanner, BigQuery, Core, Error Reporting, Logging formatting style updates.

spanner/google/cloud/spanner/session.py, spanner/unit_tests/test_pool.py, spanner/unit_tests/test_session.py
Also the mocked-up versions used to test pools.
Rationale:  Some pools store them in priority queues, with a leading timestamp: if two entries have the same timestamp, then the sessions need to be orderable.
Closes #3011.
=> Ensure that 'Session' instances are orderable.

error_reporting/unit_tests/test_client.py, logging/unit_tests/handlers/transports/test_background_thread.py, monitoring/unit_tests/test_metric.py, monitoring/unit_tests/test_resource.py
`assertEquals` is [deprecated](https://docs.python.org/2/library/unittest.html#deprecated-aliases).
Simple find/replace.
=> Rename deprecated assertEquals to assertEqual.

docs/spanner-instance-usage.rst
In the docs, the method is listed as `list_instance_configurations`, but in the [code](https://github.com/supertom/google-cloud-python/blob/d80953d520a51a91fbc43c22fc2821a01900e5e6/spanner/google/cloud/spanner/client.py#L182) (and as in version 0.23.0 installed by pip) it is `list_instance_configs`
=> Document correct method name: 'list_instance_configs'

docs/spanner-client-usage.rst
Use "Client" as the header for the client docs, not "Base for Everything".
This makes it consistent with every other Google API.
=> Spanner Docs Consistency

core/google/cloud/_http.py, core/unit_tests/test__http.py, datastore/google/cloud/datastore/_http.py, datastore/unit_tests/test__http.py, storage/google/cloud/storage/_http.py, storage/unit_tests/test__http.py
Added an "extra headers" feature to enable this. I am not a fan
of changing `Connection()` so haphazardly, but I hope to
completely re-factor / destory `Connection()` in the near-term
so I am less worried.
This only adds the storage and datastore header info, for the
purposes of a simple review. Once we agree on the approach,
I can add support in the other subpackages.
=> Adding ability to send version info header on HTTP requests.

spanner/google/cloud/spanner/__init__.py, spanner/google/cloud/spanner/client.py, spanner/google/cloud/spanner/database.py, spanner/setup.py, spanner/unit_tests/test_client.py, spanner/unit_tests/test_database.py
This PR adds the `gccl/x.y.z` portion of the metrics header in the Spanner client library.
=> Add gccl metrics header to Spanner.

pubsub/google/cloud/pubsub/subscription.py
=> Expand motivation in 'Subscription.reload' docstring.

vision/google/cloud/vision/_gax.py, vision/google/cloud/vision/annotations.py, vision/google/cloud/vision/client.py, vision/google/cloud/vision/color.py, vision/google/cloud/vision/entity.py, vision/google/cloud/vision/face.py, vision/google/cloud/vision/geometry.py, vision/google/cloud/vision/likelihood.py, vision/google/cloud/vision/safe_search.py, vision/setup.py, vision/unit_tests/test__gax.py, vision/unit_tests/test_annotations.py, vision/unit_tests/test_color.py, vision/unit_tests/test_entity.py, vision/unit_tests/test_face.py, vision/unit_tests/test_safe_search.py
@daspecster Would you please take a longer look at this one? I found the "two clients" thing really confusing and am not sure I did this correctly.
In particular, I am pretty sure the existing code threw away the `credentials` argument when being used with GAX. (Not sure how anyone would successfully set any of the _other_ arguments, either.) I updated this and added a test for it.
=> GAPIC Header Consistency: Vision

error_reporting/google/cloud/error_reporting/_gax.py, error_reporting/unit_tests/test__gax.py, logging/google/cloud/logging/_gax.py, logging/google/cloud/logging/handlers/transports/background_thread.py, logging/unit_tests/test__gax.py, speech/google/cloud/speech/_gax.py, speech/google/cloud/speech/_http.py, speech/google/cloud/speech/client.py, speech/unit_tests/test__gax.py, speech/unit_tests/test_client.py, vision/google/cloud/vision/_http.py, vision/google/cloud/vision/client.py, vision/unit_tests/test_client.py
This is a work-in-progress for now, but `vision` and `speech` are done. Will also be doing `logging`, `pubsub` and **maybe** `error_reporting`.
FWIW, this is a result of me working on #2746.
=> Isolating Connection objects in _http modules (where relevant).

datastore/google/cloud/datastore/_http.py, datastore/google/cloud/datastore/query.py, datastore/unit_tests/test__http.py, datastore/unit_tests/test_query.py
Towards #2746 (as is #3064). This approach is to slowly transition from our current approach to use the GAPIC generated surface.
These unit tests weren't so bad to update. I did "editorialize" as I went, downgrading constants to just variables, renamining for PEP8, etc.
=> Making datastore Connection.run_query() return low-level protobuf.

datastore/google/cloud/datastore/_http.py, datastore/google/cloud/datastore/batch.py, datastore/unit_tests/test__http.py, datastore/unit_tests/test_batch.py, datastore/unit_tests/test_client.py, datastore/unit_tests/test_transaction.py
Towards #2746. This approach is to slowly transition from our current approach to use the GAPIC generated surface.
It is unfortunately tangled quite a bit (partly because we may have too much mocked in the tests).
=> Making datastore Connection.commit() return low-level protobuf.

docs/speech-usage.rst
Sample class can take in content, source_uri or stream, should be stream here.
```
:type content: bytes
:param content: (Optional) Bytes containing audio data.
:type stream: file
:param stream: (Optional) File like object to stream.
```
the type is deduced using:
```sources = [content is not None, source_uri is not None, stream is not None]```
=> for streaming sample should have "stream=" param

error_reporting/google/cloud/error_reporting/client.py, error_reporting/unit_tests/test_client.py
Also changed a lot of the unit tests. Fixes #3071.
----
Between #3063 and this, my confidence in the `error_reporting` package is pretty shaken.
/cc @jonparrott @waprin
=> Passing along client instead of project when creating error API.

storage/google/cloud/storage/blob.py, storage/google/cloud/storage/bucket.py, storage/unit_tests/test_blob.py
=> Add 'Blob.update_storage_class' API method.

vision/unit_tests/test__gax.py, vision/unit_tests/test__http.py, vision/unit_tests/test_annotations.py, vision/unit_tests/test_batch.py, vision/unit_tests/test_client.py, vision/unit_tests/test_color.py, vision/unit_tests/test_crop_hint.py, vision/unit_tests/test_entity.py, vision/unit_tests/test_face.py, vision/unit_tests/test_feature.py, vision/unit_tests/test_geometry.py, vision/unit_tests/test_image.py, vision/unit_tests/test_safe_search.py
Some cleanup from some original unit test inconsistencies.
=> Clean up Vision unit tests.

error_reporting/unit_tests/test__gax.py, error_reporting/unit_tests/test__logging.py, error_reporting/unit_tests/test_client.py, logging/unit_tests/test_client.py, vision/unit_tests/test__gax.py, vision/unit_tests/test_batch.py, vision/unit_tests/test_client.py
@lukesneeringer @tseaver any ideas on an easy "lint"-like check that will scream if people create a `Mock()` without a `spec`?
SIDEBAR: The error reporting unit tests are in a **very bad state**. This change opened my eyes to that fact, but I fear there is more hiding under the surface.
=> Drop usage of overly broad mock.Mock() in tests.

datastore/google/cloud/datastore/_http.py, datastore/google/cloud/datastore/transaction.py, datastore/unit_tests/test__http.py, datastore/unit_tests/test_transaction.py
Towards #2746 (as were #3064 and #3066). This approach is to slowly transition from our current approach to use the GAPIC generated surface.
=> Making datastore Connection.begin_transaction() return low-level protobuf.

datastore/google/cloud/datastore/_http.py, datastore/google/cloud/datastore/transaction.py, datastore/unit_tests/test__http.py
Towards #2746 (as were #3064 and #3066 and #3091). This approach is to slowly transition from our current approach to use the GAPIC generated surface.
=> Making datastore Connection.rollback() return low-level protobuf.

bigtable/google/cloud/bigtable/__init__.py, bigtable/google/cloud/bigtable/client.py, bigtable/setup.py, bigtable/unit_tests/test_client.py
We missed this because it does not use GAPIC (the most recent generated Bigtable GAPIC surface is 5+ months old).
----
**NOTE**: This will fail all CI since `google-gax==0.15.7` isn't out yet, but I wanted to get reviewers a chance to see it before `0.15.7` gets released tomorrow. (I have personally run the tests locally by installed `google-gax` from `HEAD`.)
=> Sending x-goog-api-client header in Bigtable.

datastore/google/cloud/datastore/_http.py, datastore/google/cloud/datastore/client.py, datastore/unit_tests/test__http.py, datastore/unit_tests/test_client.py
Towards #2746 (as were #3064, #3066, #3091 and #3092). This approach is to slowly transition from our current approach to use the GAPIC generated surface.
=> Making datastore Connection.allocate_ids() return low-level protobuf.

bigtable/setup.py
Only commits since the last release came from #3089, so release notes will be easy.
```
$ git log bigtable-0.23.0..cut-bigtable-0.23.1 -- bigtable/
commit f99fb80baf810ca4447c7f1bc6b39a9f430f7072
Author: Danny Hermes <daniel.j.hermes@gmail.com>
Date:   Fri Mar 3 11:18:05 2017 -0800
Cut version 0.23.1 of Bigtable.
commit 20ffd2be9b31bbff9bca8bd698c941da5a7f1951
Author: Danny Hermes <daniel.j.hermes@gmail.com>
Date:   Thu Mar 2 16:54:21 2017 -0800
Sending x-goog-api-client header in Bigtable.
We missed this because it does not use GAPIC (the most
recent generated Bigtable GAPIC surface is 5+ months old).
```
=> Cut version 0.23.1 of Bigtable.

datastore/google/cloud/datastore/_http.py, datastore/google/cloud/datastore/client.py, datastore/unit_tests/test__http.py, datastore/unit_tests/test_client.py
Towards #2746 (as were #3064, #3066, #3091, #3092 and #3093). This approach is to slowly transition from our current approach to use the GAPIC generated surface. This is the sixth and final API method to be converted in this fashion.
=> Making datastore Connection.lookup() return low-level protobuf.

docs/index.rst
This is a minor documentation change, to order the services on the left-side panel alphabetically.
=> Order documentation alphabetically by service.

language/google/cloud/language/document.py, language/unit_tests/test_document.py, system_tests/language.py
It turns out that Python actually does not encode strings in UTF-8 by default, but actually in UTF-16 or UTF-32, depending on the system. Since Unicode is a variable length format, this distinction does not matter unless you are using characters outside of UTF-8's range.
However, we want our character offsets that we send back from the language API to be correct, so we should provide the correct default encoding request.
=> Provide correct default encoding.

datastore/google/cloud/datastore/_gax.py, datastore/google/cloud/datastore/_http.py, datastore/google/cloud/datastore/client.py, datastore/unit_tests/test__gax.py, datastore/unit_tests/test__http.py, datastore/unit_tests/test_client.py
Includes
- ``use_gax`` argument in Client constructor
- ``make_datastore_api`` helper to make a gRPC channel with
the correct credentials
- A basic ``HTTPDatastoreAPI`` class to act as the equivalent
to the GAPIC ``DatastoreClient``
- A lazy property on ``Client`` that will hold the API
object.
Towards #2746.
=> Add basic helpers needed for GAPIC client in datastore.

datastore/google/cloud/datastore/_http.py, datastore/unit_tests/test__http.py
This is to prepare for a removal of the Connection class (relates to #2746 and #3105).
=> Moving _request and _rpc off the datastore HTTP helper.

language/setup.py
Based on `git log a3596d6..HEAD language/`...
* Fixes default encoding to correctly detect based on `sys.maxunicode`. (#3102)
=> Bump language version to 0.23.1

README.rst, vision/setup.py
This PR officially makes `google-cloud-vision` a beta library.
@daspecster What else (besides a release, of course) is needed to accomplish this? Do the docs proclaim Vision as alpha right now? If so, we need to update that. (Also, we will need a manual docs trigger once this is pushed out.)
=> Vision Beta

storage/setup.py
- #2991 (de5d8e1) Add 'Blob.update_storage_class' API method.
=> Storage release 0.23.1

datastore/google/cloud/datastore/_http.py, datastore/unit_tests/test__http.py
**NOTE**: Has #3108 as diffbase.
=> Only requiring HTTP object to make datastore RPC-over-HTTP.

datastore/google/cloud/datastore/_gax.py, datastore/google/cloud/datastore/_http.py, datastore/google/cloud/datastore/client.py, datastore/unit_tests/test__gax.py, datastore/unit_tests/test__http.py, datastore/unit_tests/test_client.py
This is progress towards #2746 and makes Connection() act as a proxy for the contents of Client (as intended).
=> Moving datastore host configuration into Client.

system_tests/bigquery.py
=> Add system tests for legacy data types.

error_reporting/setup.py
Patch release for Error Reporting. 
See: #3071.
- Bugfix: Passing along client instead of project when creating error API. (#3075)
PyPI: https://pypi.python.org/pypi/google-cloud-error-reporting/0.23.1
=> Release Error Reporting 0.23.1.

CONTRIBUTING.rst
>141.0.0 (2017-01-25) (Google Cloud SDK) The deprecated gcloud preview app and gcloud preview datastore have been removed. Commands are available under the GA release track.
See: https://cloud.google.com/sdk/docs/release-notes
=> 'gcloud preview' command no longer supported.

spanner/google/cloud/spanner/database.py, spanner/unit_tests/test_database.py
Fixes #3020.
Note: I want to make sure the Spanner system tests run, and it is hard to run them locally. System tests' passing is a prerequisite for merging this.
=> Remove _BrokenResultFuture

datastore/google/cloud/datastore/_http.py, datastore/google/cloud/datastore/client.py, datastore/unit_tests/test__http.py, datastore/unit_tests/test_client.py
=> Using GAPIC datastore object (and an HTTP equivalent) for allocate_ids.

datastore/google/cloud/datastore/_http.py, datastore/google/cloud/datastore/transaction.py, datastore/unit_tests/test__http.py, datastore/unit_tests/test_transaction.py
=> Using GAPIC datastore object (and an HTTP equivalent) for rollback.

datastore/google/cloud/datastore/_gax.py, datastore/google/cloud/datastore/_http.py, datastore/google/cloud/datastore/batch.py, datastore/unit_tests/test__gax.py, datastore/unit_tests/test__http.py, datastore/unit_tests/test_batch.py, datastore/unit_tests/test_client.py, datastore/unit_tests/test_transaction.py, system_tests/datastore.py
This is a bit more involved since
- The signature requires the **caller** to determine the mode
- The signature receives a list of mutations, so we no longer collect mutations within a `CommitRequest` object
- The exception re-mapping must be done, so we can't use the base `datastore_client.DatastoreClient` GAPIC object
----
~~**NOTE**: I have yet to write unit tests, but have the system tests passing and wanted to get some eyeballs on this before I dive into unit test hell.~~
=> Using GAPIC datastore object (and an HTTP equivalent) for commit.

datastore/google/cloud/datastore/_gax.py, datastore/google/cloud/datastore/_http.py, datastore/google/cloud/datastore/transaction.py, datastore/unit_tests/test__gax.py, datastore/unit_tests/test__http.py, datastore/unit_tests/test_transaction.py
Man this process is getting old.
Only two methods left for #2746 to be "done".
=> Using GAPIC datastore object (and an HTTP equivalent) for begin_transaction.

datastore/google/cloud/datastore/_gax.py, datastore/google/cloud/datastore/_http.py, datastore/google/cloud/datastore/batch.py, datastore/google/cloud/datastore/client.py, datastore/google/cloud/datastore/query.py, datastore/google/cloud/datastore/transaction.py, datastore/unit_tests/test__gax.py, datastore/unit_tests/test__http.py, datastore/unit_tests/test_client.py
This is the last method to be ported over so the `Connection()` base class as well as the `_DatastoreAPIOverGRPC` and `_DatastoreAPIOverHttp` helper classes have been totally removed.
**NOTE**: This temporarily breaks our emulator support, but I plan on restoring that support in a follow-up PR.
=> Using GAPIC datastore object (and an HTTP equivalent) for lookup.

pubsub/google/cloud/pubsub/_gax.py, pubsub/unit_tests/test__gax.py
Fixes #2993, #2983
This is for the gRPC side **only**.
=> Add timeout for topic_publish() for gRPC side.

system_tests/bigquery.py, system_tests/bigquery_test_schema.json
Derived from schema from @tswast.
Toward #3029.
=> Add system test for 'Table.create' using nested schema

spanner/unit_tests/test_session.py
=> Make run_in_transaction w/ timeout test deterministic.

datastore/google/cloud/datastore/_gax.py, datastore/unit_tests/test__gax.py, system_tests/system_test_utils.py, tox.ini
Sorry for the delay. I made a few wrong turns (e.g. using `hostname` instead of `netloc`) and debugging with gRPC is **not** fun.
=> Adding (back) support for datastore emulator.

language/google/cloud/language/entity.py, language/unit_tests/test_api_responses.py, language/unit_tests/test_document.py, language/unit_tests/test_entity.py, system_tests/language.py
=> Provide full Mention objects, not just the content.

error_reporting/google/cloud/error_reporting/_gax.py, error_reporting/unit_tests/test__gax.py
Fixes #3158
I'm not sure if `Client._project` should be a public property in this case but if so I can change it. This PR just correctly access the desired data.
=> Fix make_report_error_api usage of Client._project.

logging/google/cloud/logging/_gax.py, logging/google/cloud/logging/logger.py, logging/unit_tests/test__gax.py, logging/unit_tests/test_logger.py, system_tests/logging_.py
Fixes: #3129
This should fix the double conversion issue.
/cc @waprin
=> Fix double conversion of datetime for log entries.

datastore/google/cloud/datastore/_gax.py, datastore/unit_tests/test__gax.py
Fixes #2746.
See [previous source][1] for reference.
@lukesneeringer I don't really like doing this, but I'm not sure if there's a better way to remap the `GaxError`-s to our `google.cloud` exceptions.
[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/datastore-0.23.0/datastore/google/cloud/datastore/_gax.py#L70
=> Restoring datastore Gax exception re-mapping.

pubsub/google/cloud/pubsub/topic.py, pubsub/unit_tests/test_topic.py
=> Add a `max_size` argument to Pub / Sub Batch.

pubsub/google/cloud/pubsub/topic.py
Following up on a @dhermes suggestion.
=> Add Batch._reset_state for DRY.

storage/google/cloud/storage/_helpers.py, storage/google/cloud/storage/bucket.py, storage/unit_tests/test__helpers.py
=> Raise ValueError exception if bucket name is invalid.

datastore/google/cloud/datastore/_gax.py, datastore/unit_tests/test__gax.py
=> Removing unused code-path for remapping raw gRPC exceptions in datastore.

system_tests/vision.py, vision/google/cloud/vision/image.py, vision/unit_tests/test_client.py
Fixes: #3124
Towards:  #3132.
Support `language_hints` argument for `detect_full_text()`.
=> Add language_hints support to detect_full_text.

spanner/setup.py, spanner/unit_tests/test_session.py
The GRPC team released grpcio 1.2.0 yesterday, and renamed an internal method that we were using directly in our Spanner unit tests. This PR updates us to use the new name.
See #3170 for the [original build failure][1].
[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1291
=> Adjust Spanner tests for grpcio 1.2.0

bigquery/google/cloud/bigquery/_helpers.py, bigquery/unit_tests/test__helpers.py, system_tests/bigquery.py
Toward #3029.
Fix two issues found by the new tests:
- `BYTES` values must *not* have the trailing newline introduced by the stdlib's "legacy" `base64.encodestring` API.
- `DATETIME` values must *not* have a trailing `Z`:  they are conceptually "naive" / zoneless.
=> Add system tests for all scalar query parameter types. 

error_reporting/google/cloud/error_reporting/client.py, error_reporting/unit_tests/test_client.py
=> Use ClientWithProject superclass for error reporting.

storage/google/cloud/storage/blob.py, storage/unit_tests/test_blob.py
- The new test fails with the KeyError experienced by customer.
- Tests passing on Python 2.7 and 3.4 (I don't have 3.5 on my env).
=> Fixes #3150 - Ignores resource key when it isn't present

appveyor.yml
Right now, we run the unit tests on AppVeyor six times:
* Python 2.7, 3.4, and 3.5
* 32-bit and 64-bit.
This takes well over **90 minutes** to complete. The results:
* We tend not to wait on AppVeyor to actually merge (meaning it loses its value).
* Extremely obnoxious queue times.
Therefore, let's test on 32-bit 2.7 and 64-bit 3.5 (which will generally take about 30 minutes) and call it soup.
I am making this change on the `ci` branch also, for the same reasons, although the `ci` branch is still in mysterious AppVeyor hell.
=> Reduce AppVeyor testing matrix.

storage/google/cloud/storage/acl.py, storage/google/cloud/storage/blob.py, storage/google/cloud/storage/bucket.py
Documentation link updates. Fixed 404s and 301 redirects.
=> Update 301 redirects for storage documentation.

bigquery/google/cloud/bigquery/_helpers.py, bigquery/unit_tests/test__helpers.py
=> Ensure that base64-encoded bytes get decoded to text for JSON.

docs/translate-usage.rst, translate/google/cloud/translate/client.py
Bad continuation for a link. Update `translation` to `translate`.
=> Fix translate links.

docs/storage_snippets.py
Update for https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3183#issuecomment-288540500.
=> Remove storage acl chaining from docs.

docs/vision-usage.rst, vision/google/cloud/vision/face.py, vision/google/cloud/vision/feature.py, vision/google/cloud/vision/geometry.py, vision/google/cloud/vision/likelihood.py
=> Fix vision documentation redirects and references.

bigquery/nox.py, bigtable/nox.py, core/nox.py, datastore/nox.py, dns/nox.py, error_reporting/nox.py, language/nox.py, logging/nox.py, monitoring/nox.py, pubsub/nox.py, resource_manager/nox.py, runtimeconfig/nox.py, spanner/nox.py, speech/nox.py, storage/nox.py, test_utils/scripts/get_target_packages.py, translate/nox.py, vision/nox.py
Using `STRING_TEMPLATE % VARIABLE` can introduce hard-to-find bugs if `VARIABLE` is expected to be a string but ends up being a tuple. Instead of using percent formatting, just using `.format`.
Also making tweaks to `get_target_packages` to make some path manipulation / checks OS-independent.
=> Fixing up some format strings in nox configs.

error_reporting/setup.py
Draft changelog for release:
- Bugfix: Fix make_report_error_api usage of Client._project. (#3159)
=> Prep error-reporting-0.23.2

storage/google/cloud/storage/_helpers.py, storage/google/cloud/storage/bucket.py, storage/tests/system.py, storage/tests/unit/test__helpers.py, storage/tests/unit/test_bucket.py
This is a port of GoogleCloudPlatform/google-cloud-dotnet#933.
This also exposes the fact that Python 2 cannot handle some Unicode in URLs at all, because `urllib.quote` raises `KeyError` (wha....?) if you use Unicode. That is an issue with the Python standard library, however.
=> Add integration test for Unicode filenames.

test_utils/scripts/update_docs.sh
This commit moves docs publishing to use SSH instead of an OAuth key
over HTTP. The SSH key is attached to a robot user configured in
CI.
@dhermes: Please review, but there might be some unavoidable post-merge
thrashing if problems arise.
=> Check out docs submodule with SSH.

docs/storage_snippets.py, storage/google/cloud/storage/bucket.py
This removes the policy document example. I'm not sure why it's failing at the moment.
Also adds a line to the encryption key example to make it work out of the box.
=> Fix storage encryption example, remove policy document example.

docs/vision-usage.rst
Towards #3172 
Fixed image properties color accessor and some of the output `__repr__`s.
=> Small updates to Vision examples.

docs/storage_snippets.py, storage/google/cloud/storage/bucket.py
Closes #3222 
Updated per @jonparrott's feedback in #3222.
=> Add policy_document snippet back.

docs/language-usage.rst
@dhermes I think you meant to attach `Document` to `Client` but for the sake of the timeline I just updated the examples.
=> Fix broken language examples.

core/google/cloud/client.py, core/tests/unit/test_client.py
=> Make clients explicitly unpickleable.

docs/logging-stdlib-usage.rst, logging/google/cloud/logging/handlers/handlers.py
These snippets aren't covered in `logging_snippets.py` and they had a couple small syntax issues.
=> Fix untested logging snippet examples.

docs/speech-usage.rst
Towards: #3172
Test script: https://gist.github.com/daspecster/718d01c7896ee576743292549cfb6927
=> Update speech usage examples.

docs/speech-usage.rst, speech/tests/system.py
Closes #3166.
Updated the docs and added a system test for using `result_index`.
=> Add docs for 'result_index'  usage and a system test.

core/tests/unit/test_client.py
Issue caused by two unrelated PRs merging in close proximity: #3235 and #3230.
=> Fixing usage of http= vs. _http= in core unit test.

logging/nox.py
@dhermes This is a more permanent change we can make for the logging system tests while we are watching them over the next few days.
=> Make logging system tests verbose.

docs/speech-usage.rst, speech/tests/system.py
Reverts GoogleCloudPlatform/google-cloud-python#3241
=> Revert "Add docs for 'result_index'  usage and a system test."

.circleci/config.yml
For context see:
- https://discuss.circleci.com/t/build-on-tag/9864/30
- https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/8
- https://circleci.com/gh/keybits/circulate/58#config/containers/0
=> Adding CircleCI 1.0 config into our 2.0 config to support tag builds.

test_utils/scripts/circleci/get_tagged_package.py
See carnage:
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1502
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1503
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1504
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1505
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1506
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1507
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1508
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1509
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1510
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1511
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1512
- …
=> Fixing "repo-relative" directory in `get_tagged_package`.

.circleci/config.yml
This is a "temporary" fix, these dependencies should be in the docker image?
=> Add twine and setuptools install as step before twine upload.

.circleci/config.yml, test_utils/scripts/circleci/twine_upload.sh
@dhermes This should fix your issue.
=> Use Python 3 for package build.

bigquery/google/cloud/bigquery/_helpers.py
Just a spelling error fix in the docstrings.
s/paramter/parameter
=> Fix repeated spelling error

docs/spanner-session-implicit-txn-usage.rst, docs/spanner-snapshot-usage.rst, docs/spanner-transaction-usage.rst
=> Drop fossil docs refs to 'read_streaming'/'execute_streaming_sql'.

logging/google/cloud/logging/_gax.py, logging/google/cloud/logging/_http.py, logging/google/cloud/logging/entries.py, logging/google/cloud/logging/logger.py, logging/tests/system.py, logging/tests/unit/test__gax.py, logging/tests/unit/test_entries.py
Fixes #2674.
@lukesneeringer @tseaver I am unfortunately "out of time" until Wednesday so if either of you want to take this over the finish line (e.g. unit tests and maybe a system test with an unregistered type URL?) I would not protest.
=> Gracefully continue if LogEntry.proto_payload type URL is not in registry.

error_reporting/setup.py, logging/setup.py, logging/tests/unit/test__gax.py, setup.py
Should be OK after #3270? I made this branch on the `GoogleCloudPlatform` remote so that system tests are run in this PR.
=> Cut release 1.0.0 of logging package.

speech/setup.py
I will release once this is merged. Following up momentarily with release notes.
=> Bump Speech to 0.25.0.

language/google/cloud/language/_http.py, language/google/cloud/language/client.py, language/google/cloud/language/document.py, language/google/cloud/language/entity.py, language/tests/unit/test_document.py, language/tests/unit/test_entity.py
This commit adds an `api_version` parameter to the `Client` constructor to provide access to the v1beta2 API methods.
Instantiation looks like:
```python
client = Client(api_version='v1beta2')
```
The default value is `'v1'`, and anything other than `'v1'` or `'v1beta2'` is an error.
Note that using the `'v1beta2'` version will route _all_ calls made to the object through that endpoint, and so existing methods will also get `v1beta2` behavior.
Note that neither `v1` nor `v1beta2` actually use the GAPIC.
=> Language: Expose an api_version parameter on the Client.

speech/google/cloud/speech/encoding.py
=> Add new encodings.

error_reporting/google/cloud/error_reporting/client.py, error_reporting/tests/unit/test_client.py
This fixes #2877 and probably fixes #3263 .
I will work on a followup system test since clearly needed. 
NB: The reason for this bug and lack of system test is the pre-gRPC code went through Logging which was basically untyped, the errors were showing up despite the incorrect parameter names (and at the time without the full API there was no good way to system test).
=> Replace httpContext with httpRequest

spanner/google/cloud/spanner/streamed.py, spanner/tests/unit/test_streamed.py
Client needs to know which merger to use when merging column type BYTES that is consumed in chunks as part of a read. Without this fix, client gives a traceback:
```
.../venv/lib/python2.7/site-packages/google/cloud/spanner/streamed.py", line 262, in _merge_by_type
merger = _MERGE_BY_TYPE[type_.code]
KeyError: 7
```
Type 7 is BYTES from the [proto](https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/type.proto) definition 
The error condition will arise if you write an image (a few MB in size) as base64 encoded in a bytes column. When trying to read the column back using the client, the above traceback will be given. With this fix, the client will use the string merger (treating bytes as a string) and allow the row to be consumed. The test is to read the entire column …
=> Fix missing BYTES merger

core/google/cloud/iam.py, core/tests/unit/test_iam.py, pubsub/google/cloud/pubsub/iam.py, pubsub/tests/unit/test_iam.py
The legacy accessors still return frozensets, as they cannot safely be mutated in plcae.
=> Store policy bindings as sets, not frozensets.

core/google/cloud/iam.py, core/tests/unit/test_iam.py, pubsub/google/cloud/pubsub/iam.py, pubsub/tests/unit/test_iam.py, storage/google/cloud/storage/blob.py, storage/google/cloud/storage/bucket.py, storage/google/cloud/storage/iam.py, storage/tests/unit/test_blob.py, storage/tests/unit/test_bucket.py, storage/tests/unit/test_iam.py
Uses #3309 as a base.
Closes #1679.
=> Add IAM handlers to blobs

pubsub/google/cloud/pubsub/_gax.py, pubsub/google/cloud/pubsub/_http.py, pubsub/google/cloud/pubsub/client.py, pubsub/google/cloud/pubsub/snapshot.py, pubsub/google/cloud/pubsub/subscription.py, pubsub/tests/system.py, pubsub/tests/unit/test__gax.py, pubsub/tests/unit/test__http.py, pubsub/tests/unit/test_client.py, pubsub/tests/unit/test_snpashot.py, pubsub/tests/unit/test_subscription.py
Notes:
- cloud.google.com links do not yet work
- SeekResponse exists but is empty; the corresponding methods return
None instead
- It's not documented whether the deleted topic path applies to
snapshots analogous to how it applies to subscriptions, but it seems
logical to assume so.
- The new Subscription fields are part of this release but will come
shortly as a separate PR. (They can be done independently of the
snap-seek work.)
=> Add Pub/Sub snapshot and seek functionality

pubsub/tests/system.py
This should prevent the (as of yet, unexperienced) error case where
the API deletes the acked messages before we have a chance to seek
to them.
=> Set `retain_acked_messages` in seek system test

datastore/nox.py
/cc @jonparrott 
@lukesneeringer You mentioned that you'd prefer a standalone session for this. I am unclear why you prefer this. To me, checking that the `README` isn't invalid in `setup.py` **is** linting.
=> Adding check (in datastore) that setup.py README is valid RST.

bigquery/nox.py, bigtable/nox.py, core/nox.py, dns/nox.py, error_reporting/nox.py, language/nox.py, logging/README.rst, logging/nox.py, monitoring/README.rst, monitoring/nox.py, nox.py, pubsub/nox.py, resource_manager/nox.py, runtimeconfig/nox.py, spanner/nox.py, speech/nox.py, storage/nox.py, translate/nox.py, vision/nox.py
Follow up to #3316. Fixes #2446.
=> Adding check that **all** setup.py README's are valid RST.

bigquery/setup.py, bigtable/setup.py, core/setup.py, datastore/setup.py, dns/setup.py, error_reporting/setup.py, language/setup.py, logging/setup.py, monitoring/setup.py, pubsub/setup.py, resource_manager/setup.py, runtimeconfig/setup.py, spanner/setup.py, speech/setup.py, storage/setup.py, translate/setup.py, vision/setup.py
These seem to have lost their intent during the one-big-giant-test-config PR.
/cc @jonparrott Since I think he was the original author of the `exclude=` argument.
=> Ignore tests (rather than unit_tests) in setup.py files.

storage/google/cloud/storage/blob.py, storage/google/cloud/storage/bucket.py, storage/nox.py, storage/setup.py, storage/tests/unit/test_blob.py
Check out https://googlecloudplatform.github.io/google-resumable-media-python/0.0.2/ for details on the new library.
=> Swapping out google.streaming for google-resumable-media in GCS downloads.

spanner/google/cloud/spanner/client.py, spanner/tests/unit/test_client.py
=> Pass client credentials through to instance / database admin API instances

logging/tests/system.py
Tries to update a `frozenset()`.
This guy has been failing for awhile, e.g.
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1671
Likely related to one of the recent IAM PRs: #3188, #3308, #3309, #3311
=> Fixing broken logging system test.

storage/google/cloud/storage/blob.py, storage/tests/unit/test_blob.py
In some sense, this setter should be **disabled** for objects / blobs that already exist, but there is no way to tell without calling `exists()` and we SHOULD NOT require a round trip just to use a `@property` setter.
Instead, we rely on the backend (and the documentation) to inform users when it is OK to use the setter.
=> Making Blob.storage_class settable.

translate/tests/system.py
This test has been non-deterministic for some reason, e.g.:
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1682
=> Allowing "dank" or "danke" when "dankon" translated from Esperanto to German.

storage/google/cloud/storage/blob.py, storage/tests/unit/test_blob.py
I "need" to get this in before I can do a release (i.e. #3332).
=> Adding error remapping for Blob.download_to_file().

bigquery/google/cloud/bigquery/query.py
Update BigQuery Query parameter reference to indicate that timeout_ms sets timeout on the request, not on the query. Should address https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3317
=> Update BQ Query parameter reference

docs/speech-usage.rst
Fix speech context example in speech-usage docs to match argument name change in a9268a3e2777c35405c6c114c6b358e4d4c02335.
Closes #3349.
=> Fix `speech_context` typo in speech-usage docs.

storage/google/cloud/storage/blob.py, storage/tests/unit/test_blob.py
=> Only using Blob.updated if it is set in download_to_filename().

storage/setup.py
Release notes will be simple
- Bug fix: Only using `Blob.updated` if it is set in `download_to_filename()`. (#3352)
/cc @danigosa
=> Bugfix release of Storage.

storage/google/cloud/storage/blob.py, storage/tests/system.py, storage/tests/unit/test_blob.py
@lukesneeringer, you might be thinking: "What does this have to do with `google-resumable-media`?"
But, alas, it does have something to do with this because both a multipart upload and resumable upload require JSON encoding `{'name': name, ...}` and `bytes` objects are **explicitly not** JSON serializable in Python 3.
=> Enforcing explicit UTF-8 blob name.

storage/google/cloud/storage/blob.py, storage/tests/unit/test_blob.py
This is prep work for swapping out the upload implementation to use `google-resumable-media`.
I just wanted to get "unrelated" and non-controversial changes out of the way before a big PR.
=> Factoring out some Blob helpers.

storage/google/cloud/storage/blob.py, storage/setup.py, storage/tests/unit/test_blob.py
Some notes:
- ~~For now, the [build][1] is failing unit tests, because I haven't done those (what I'm sure will be very time-consuming) updates~~
- The **ACTUAL IMPORTANT** thing to note is that the system tests in the [build][1] **are passing**
- ~~I haven't yet updated `create_resumable_upload_session()`, but I can (it should be fairly straightforward, but I'd rather do it in a separate PR)~~
- I would **really** like some suggestions about what to do about the `num_retries` argument. IMO supporting it is a "bad idea™"
- I have ever-so-slightly changed the behavior of `upload_from_file()` when `size` is passed in. This is mostly because the existing implementation is **confused** about what the size / `chunk_size` combination should mean. The implementation now does the "sane" thing: …
=> Changing over Blob.upload*() methods to use google-resumable-media.

error_reporting/nox.py, error_reporting/tests/system.py
This actually uses the gapic client to verify counts.
It doesn't expose the gapic client outside of the system methods since unlikely they will need to be used (and we can wait on the general gapic doc improvements for those who do want it).
Fixes #3335.
=> Add error reporting system test

speech/google/cloud/speech/operation.py
ValueError is raised when there are no results, not when there is more than one result, which is what the docstring says.
=> Correct speech Operation docstring

bigquery/tests/system.py
=> Using binary streams for uploads in BigQuery system tests.

datastore/google/cloud/datastore/entity.py, datastore/google/cloud/datastore/helpers.py
H/T to @GustavoRPS for bringing this up in #3361.
Also snuck in a change in `google.cloud.datastore.helpers` to use `six.binary_type` in place of `(str, bytes)`. (It wasn't a Py3 error before because that check came **after** a `six.text_type` check.)
=> Add better documentation for support types in datastore Entity.

spanner/tests/system.py
- `batch`
- `snapshot`
- `read`
- `run_with_transaction`
- `execute_sql`
Closes #3015.
=> Add system test for Database convenience methods:

vision/tests/system.py
Flaky in:
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1694
=> Adding retry to test_detect_web_images_from_gcs() system test.

vision/setup.py
Fixes #3398.
----
After using this and running the unit tests, the dependency is indeed only present in Python 2.7:
```bash
$ .nox/unit_tests-python_version-2-7/bin/pip freeze > 27.txt
$ .nox/unit_tests-python_version-3-4/bin/pip freeze > 34.txt
$ .nox/unit_tests-python_version-3-5/bin/pip freeze > 35.txt
$ .nox/unit_tests-python_version-3-6/bin/pip freeze > 36.txt
$
$ diff -s 34.txt 35.txt
Files 34.txt and 35.txt are identical
$ diff -s 34.txt 36.txt
Files 34.txt and 36.txt are identical
$
$ diff -s 27.txt 34.txt
--- 27.txt      2017-05-11 10:28:41.369890164 -0700
+++ 34.txt      2017-05-11 10:28:36.081426963 -0700
@@ -2,10 +2,7 @@
cachetools==2.0.0
coverage==4.4
dill==0.2.6
-enum34==1.1.6
-funcsigs==1.0.2
future==0.16.0
-futures==3.1.1
gapic-google-cloud-vision-v1==0.90.3 …
```
=> Making enum34 dependency conditional on Python version.

bigtable/google/cloud/bigtable/row.py, bigtable/tests/unit/test_row.py
Pulling out non-controversial part of #3401 for #2411.
=> Getters for row key and row table

bigquery/google/cloud/bigquery/table.py, bigquery/tests/unit/test_table.py
[This is a re-do of the pull request #3366 to fix the author email address to use my `google.com` email]
I moved the `partitioning_type` check into the `if` / `elif` block to avoid a `ValueError` that should not have been thrown.
See:
https://cloud.google.com/bigquery/docs/creating-partitioned-tables#creating_a_partitioned_table and the "API" example.
Before my change, the following code failed with the `ValueError` thrown by this function, but with my change, I was able to successfully create the partitioned table:
```python
destination_table = dataset.table(table_shortname)
if not destination_table.exists(): 
destination_table.partitioning_type = 'DAY'
destination_table.create()
destination_partition = dataset.table(table_shortname + '$' + partition_date)
```
=> Fix new partitioned table

docs/pubsub_snippets.py, pubsub/google/cloud/pubsub/client.py, pubsub/tests/unit/test_client.py
Fixes #3369.
/cc @kir-titievsky
=> Adding subscription factory on Pub / Sub client.

storage/google/cloud/storage/blob.py
Many of the links were formatted incorrectly, etc.
**NOTE**: These changes **were** in #3375 but I've moved them here.
=> Clean up a documentation for the storage blob module.

docs/logging-usage.rst, pubsub/google/cloud/pubsub/client.py, storage/google/cloud/storage/blob.py
Examples:
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1895
https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1896
```
Warning, treated as error:
/var/code/gcp/docs/logging-usage.rst.rst:25:Over dedent has detected
```
Caused by new release of Sphinx:
https://pypi.python.org/pypi/Sphinx/1.6.1
----
I was **hoping** that this meant that Sphinx had added some magic dedent detection and we were contradicting it, but this is not the case:
=> Fix "broken" docs build.

pubsub/google/cloud/pubsub/snapshot.py, pubsub/google/cloud/pubsub/subscription.py, pubsub/tests/unit/test__gax.py, pubsub/tests/unit/test__http.py, pubsub/tests/unit/test_client.py, pubsub/tests/unit/test_subscription.py
Also: 
- removing `Subscription._project` and `Snapshot._project` since they are never used (and they shadow data that they shouldn't).
- my auto-save got rid of a lot of trailing whitespace
=> Making Subscription.reload() update the topic if unset.

core/google/cloud/iam.py, core/tests/unit/test_iam.py
=> iam.Policy: return empty set on missing key.

storage/google/cloud/storage/acl.py
=> Scrub mention of no-longer-chainable ACL methods.

spanner/google/cloud/spanner/session.py, spanner/tests/system/test_system.py, spanner/tests/unit/test_session.py
=> Ensure 'session._transaction' is cleared after 'run_in_transaction' succeeds

logging/google/cloud/logging/client.py, logging/google/cloud/logging/handlers/app_engine.py, logging/google/cloud/logging/handlers/handlers.py, logging/google/cloud/logging/handlers/transports/background_thread.py, logging/google/cloud/logging/handlers/transports/base.py, logging/google/cloud/logging/handlers/transports/sync.py, logging/tests/unit/handlers/test_app_engine.py, logging/tests/unit/handlers/test_handlers.py, logging/tests/unit/handlers/transports/test_background_thread.py, logging/tests/unit/handlers/transports/test_base.py, logging/tests/unit/handlers/transports/test_sync.py, logging/tests/unit/test_client.py
For #2997 .  Modified the AppEngineHandler to extend the CloudLoggingHandler and directly write logs to Stackdriver Logging API.
Screenshot of the gae_app log with AppEngineHandler:
=> Stop writing to '/var/log/app_engine/' and write logs to Stackdriver logging API

spanner/setup.py
Release notes:
- Correctly marshall `float("+inf")`/`float("-inf")` values to JSON (issue #3016).
- Ensure `session._transaction` is cleared after `run_in_transaction` succeeds. (issue #3434).
=> Prepare spanner-0.24.2 release.

bigquery/google/cloud/bigquery/_helpers.py, bigquery/google/cloud/bigquery/table.py, bigquery/tests/unit/test__helpers.py, bigquery/tests/unit/test_table.py
=> Marshal row data correctly in 'Table.insert_data()'

logging/tests/unit/handlers/transports/test_background_thread.py
I'm going to merge this ASAP because it blocks all other CI.
=> Remove uncovered / pointless branch.

videointelligence/google/cloud/videointelligence_v1beta1/__init__.py, videointelligence/google/cloud/videointelligence_v1beta1/types.py
I think the package we released actually had these fixed, because otherwise there is no way it worked at all.
=> Fix a couple of video intelligence issues.

docs/google-cloud-auth.rst
Show how to create credentials object on python sdk
=> Show how to create credentials object

bigquery/google/cloud/bigquery/query.py, bigquery/tests/unit/test_query.py
Read-only, set from servier-provided `numDmlAffectedRows` field.
Closes #2920.
=> Add 'Query.num_dml_affected_rows' property.

bigquery/tests/system.py
e.g. https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2065
Error introduced in #3426.
/cc @liyanhui1228
=> Reloading BigQuery table in system test before fetching data.

language/google/cloud/language/syntax.py, language/tests/unit/test_api_responses.py, language/tests/unit/test_document.py, language/tests/unit/test_syntax.py
Hi,
This PR add the missing data returned by the API to the Token, before only the Tag was being returned, I added all the data to the existing PartOfSpeech object and replaced it's hydratation on the Token as well
=> Add Part Of Speech missing data to Token

docs/logging/usage.rst, nox.py, pubsub/google/cloud/pubsub/client.py, storage/google/cloud/storage/blob.py
This reverts commit a849060a505d5b891b68df679ac36ee79f1e9414.
~~**NOTE**: This is labeled "don't merge" because the `Sphinx` [fix][1] hasn't been released to PyPI yet (note the change in `nox.py`, which is the part that shouldn't be merged).~~
[1]: https://github.com/sphinx-doc/sphinx/issues/3755
=> Revert "Fix "broken" docs build. (#3422)"

language/tests/system.py
`Token.part_of_speech` is now a `PartOfSpeech `rather than a string scalar. (This test breakage was accidentally introduced in #3457.)
See [breakage][1]
[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2088
=> Using part of speech "tag" in system test.

bigtable/google/cloud/bigtable/client.py, core/google/cloud/client.py, core/nox.py, core/tests/unit/test_client.py, spanner/google/cloud/spanner/client.py
Fixes #1883.
@lukesneeringer This is a long-standing bug but should really make it into a `google-cloud-core` release. I know you hate releasing `core`.
=> Adding optional switch to capture project ID in from_service_account_json().

test_utils/scripts/get_target_packages.py
Fixes #3466.
@lukesneeringer PTAL, I **think** this is the right move, but I may have a case of temporary ~~insaninty~~ insanity misunderstanding the existing behavior.
=> Reverse direction of dependencies when determining target packages.

storage/google/cloud/storage/bucket.py, storage/tests/unit/test_blob.py, storage/tests/unit/test_bucket.py
See: https://cloud.google.com/storage/docs/json_api/v1/buckets#labels
Closes #3473.
=> Add 'Bucket.labels' property.

storage/google/cloud/storage/bucket.py
=> Expose that settable properties are so.

core/google/cloud/_testing.py, pubsub/google/cloud/pubsub/_gax.py, pubsub/tests/system.py, pubsub/tests/unit/test__gax.py
Closes #3175.
Note:  this is a pubsub-only fix for the `ALREADY_EXISTS` error code change.
Note:  also updates `core._testing` to ease generation of errors with that code.
=> Remap new Gax conflict error code

docs/language/usage.rst
Remove an erroneous reference to the language API as beta.
=> Remove a reference to language API as beta.

bigquery/google/cloud/bigquery/_helpers.py, bigquery/google/cloud/bigquery/query.py, bigquery/google/cloud/bigquery/table.py, bigquery/tests/system.py, bigquery/tests/unit/test_query.py, docs/bigquery/snippets.py
Add a system test which exercises it.
Update snippets to match the new usage.
Closes #2840.
=> Make 'QueryResponse.fetch_data' return an iterator.

storage/google/cloud/storage/bucket.py, storage/google/cloud/storage/client.py, storage/tests/system.py, storage/tests/unit/test_bucket.py, storage/tests/unit/test_client.py
Toward #3474.
Note that the new system test is skipped, because `Buckets.insert` fails with the `billing/requesterPays` field set, both in our system tests and in the 'Try It!' form in the docs.
=> Add 'Bucket.requester_pays' property.

storage/google/cloud/storage/_helpers.py, storage/google/cloud/storage/blob.py, storage/google/cloud/storage/bucket.py, storage/tests/unit/test__helpers.py, storage/tests/unit/test_blob.py, storage/tests/unit/test_bucket.py
=> Add '{Bucket,Blob}.user_project' properties.

storage/google/cloud/storage/bucket.py, storage/tests/unit/test_bucket.py
~~Uses #3490 as a base.~~
This PR might best be reviewed commit-by-commit (one API call at a time).
Toward #3474.
=> Pass 'user_project' if set for Bucket API requests

storage/google/cloud/storage/blob.py, storage/tests/unit/test_blob.py
~~Uses #3492 as a base.~~
Toward #3474.
=> Pass 'user_project' if set for Blob API requests

storage/google/cloud/storage/acl.py, storage/tests/unit/test_acl.py
=> Pass 'user_project' if set for BucketACL/BlobACL API requests

bigtable/google/cloud/bigtable/row_data.py
I'm not sure if this is the best place for this, but we want to make sure it's documented that rows are returned in row key order.
=> Add sentence about row ordering

bigquery/google/cloud/bigquery/_helpers.py
I found this very small bug in the error message, so I fixed it!
=> BigQuery _EnumProperty ValueError messages are not displayed properly

storage/google/cloud/storage/blob.py, storage/tests/unit/test_blob.py
Fixes an oversight in #3495:  server-set `mediaLink` triggers a separate branch when computing download URL.
Toward #3474.
=> Pass 'user_project' if set for blob downloads w/ 'mediaLink' set

storage/google/cloud/storage/_helpers.py, storage/google/cloud/storage/acl.py, storage/google/cloud/storage/blob.py, storage/google/cloud/storage/bucket.py, storage/google/cloud/storage/client.py, storage/tests/system.py, storage/tests/unit/test__helpers.py, storage/tests/unit/test_acl.py, storage/tests/unit/test_blob.py, storage/tests/unit/test_bucket.py, storage/tests/unit/test_client.py
The feature is not GA, which makes system testing problematic.
Development continues on the `storage-requester_pays-feature` [branch](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/storage-requester_pays-feature)..
=> Back out support for 'requester pays' buckets.

core/setup.py
Draft release notes
- Set correct project when using `from_service_account_json()` (PR #3436, issue #1883)
- `iam.Policy`: return empty set on missing key. (PR #3424, issue #3346)
-----
- Add testing support for 'ALREADY_EXISTS' gRPC error code. (PR #3443)
- Fix broken link in the client Google Auth credentials help text (#3517)
- Add back pylint as info-only for core (#3515)
- Vision semi-GAPIC (#3373) (docstring tweaks)
=> Prep core-0.25.0 release.

datastore/setup.py
Draft release notes
- Add `Key.(to|from)_legacy_urlsafe`. (PR #3491)
----
- Vision semi-GAPIC (#3373) (docstring tweaks)
- Add better documentation for support types in datastore Entity. (#3363)
- Adding check (in datastore) that setup.py README is valid RST. (#3316)
=> Prep datastore-1.1.0 release.

logging/setup.py
Requires merge of #3526 to bump `core` to 0.25.0.
- Send trace context with logs from web applications (PR #3448, issue #3359)
- Write logs via Stackdriver logging API, rather than writing to `/var/log/app_engine/` (PR #3410, issue #2997)
- Implement `flush` for cloud logging handlers (PR #3413)
- Call `start` when creating a background thread transport (PR #3412)
- Add monitored resource support to Logging (PR #3386, issues #2673, #3377)
----
- Vision semi-GAPIC (#3373) (docstring tweaks)
- Remove uncovered / pointless branch. (#3445)
- Fixing broken logging system test. (#3325)
- Ignore tests (rather than unit_tests) in setup.py …
=> Prep logging-1.1.0 release.

storage/setup.py
Supersedes #3529.
- Document that  `Bucket.lifecycle_rules`, `Bucket.storage_class` are settable properties. (PR #3472, issue #2610).
- Add `Bucket.labels` property. (PR #3478, issue #3473)
- Remove mention of no-longer-chainable ACL methods. (PR #3428, issue #3181)
- Restore support for retries in storage uploads. (PR #3378)
- Drop internal usage of `rewind` in `Blob.upload_from_string()`. (PR #3365)
- Change `Blob.upload*()` and `Blob.create_resumable_upload_session()` methods to use `google-resumable-media`. (PRs #3362, #3357)
- Enforce explicit UTF-8 blob name. (#3354)
----
- Revert "Fix 'broken' docs build. (#3422)" (#3439)
- Vision …
=> Prep storage-1.2.0 release.

bigquery/setup.py
- Fix display of `_EnumProperty` ValueError messages. (PR #3520)
- Make `QueryResponse.fetch_data` return an iterator. (PR #3484, issue #2840)
- Add read-only `Query.num_dml_affected_rows` property. (PR #3460, issue #2920)
- Marshal row data correctly in `Table.insert_data()` (PR #3426, issue #2957)
- Fix support for loading AVRO files from the local filesystem (PR #3427, issue #3416)
- Fix support for creating partitioned tables. (PR #3381)
- Update BigQuery Query parameter reference to better indicate that `timeout_ms` sets timeout on the request, not on the query. (PR #3320, issue #3317)
----
- Re-enable pylint in info-only mode for all …
=> Prep bigquery-0.25.0 release.

pubsub/setup.py
- Provide more useful exception (from `google.cloud.exceptions`) when trying to create a topic/subscription that already exists, i.e. a "Conflict" (PR #3443, issue #3175).
- Make `Subscription.reload()` update the topic if unset. (#3397)
- Add `Client.subscription` factory (PR #3370, issue #3369).
----
- Revert "Fix 'broken' docs build. (#3422)" (#3439)
- Re-organize the documentation structure in preparation to split docs among subpackages (#3459)
- Fix "broken" docs build. (#3422)
=> Prep pubsub-0.26.0 release.

bigtable/setup.py
- Allow bulk update of records via `MutateRows` API (PR #3401, issue #2411)
- Add getters for `Row.row_key` and `Row.table` (PR #3408)
----
- Add optional switch to capture project ID in `from_service_account_json()`. (PR #3436, issue #1883).
- Add sentence about row ordering (#3504)
- Updating Bigtable Client docstring to reflect new credentials. (#3477)
=> Prep bigtable-0.25.0 release.

language/setup.py
- Upgrade Part Of Speech from a string to a container for all returned data (PR #3457)
----
- Using part of speech "tag" in system test. (#3471)
=> Prep language-0.25.0 release.

spanner/setup.py
----
- Add optional switch to capture project ID in `from_service_account_json()`. (PR #3436, issue #1883)
=> Prep spanner-0.25.0 release.

dns/setup.py
=> Prep dns-0.25.0 release.

monitoring/setup.py
=> Prep monitoring-0.25.0 release.

resource_manager/setup.py
=> Prep resource-manager-0.25.0 release.

runtimeconfig/setup.py
=> Prep runtimeconfig-0.25.0 release.

speech/setup.py
----
- Correct speech Operation docstring (#3379)
=> Prep speech-0.26.0 release.

translate/setup.py
----
- Allowing "dank" or "danke" when "dankon" translated from Esperanto to German. (#3337)
=> Prep translate-0.25.0 release.

error_reporting/setup.py
----
- Increasing retries from 4 to 6 for error reporting system test.
- Add error reporting system test (#3348)
=> Prep error-reporting-0.25.0 release.

vision/setup.py
Note that the version number was bumped prematurely in 72e6e522.
@lukesneeringer can you please suggest a better description for PR #3373?
- Make `enum34` dependency conditional on Python version. (PR #3402, issue #3398)
- Replace the manual wrapper with a thin wrapper around the GAPIC (PR #3373).
----
- Adding retry to test_detect_web_images_from_gcs() system test. (#3339)
=> Prep vision-0.25.0 release.

bigquery/nox.py, bigquery/tests/system.py, bigquery/tests/unit/test_table.py
Errors I fixed.
(google-cloud-python-2)
$ flake8 tests
tests/system.py:178:32: F812 list comprehension redefines 'dataset' from line 170
tests/system.py:233:30: F812 list comprehension redefines 'table' from line 225
tests/system.py:841:9: F841 local variable 'dataset' is assigned to but never used
tests/unit/test_table.py:406:23: W291 trailing whitespace
tests/unit/test_table.py:1052:9: F841 local variable 'ROWS' is assigned to but never used
I've also added the tests folder to flake8 in the nox config.
=> BQ: cleanup flake8 errors in tests

vision/google/cloud/vision/decorators.py, vision/tests/unit/test_decorators.py
This commit makes it such that any other part of an `AnnotateImageRequest` can be specified on the single-feature methods as a keyword argument. Needed for crop hints.
=> Add the ability to specify AnnotateImageRequest items in single-feature methods.

datastore/google/cloud/datastore/key.py, datastore/tests/unit/test_key.py
Hi,
I am proposing a change to the Google Cloud Platform Datastore's Python client library, specifically the Key module. @dhermes and I have discussed about removing the padding characters ("=") from regular b64encoded urlsafe to match the version that is used in Datastore (which does not have the padding character "="). This is done to ensure consistency in using and reproducing Datastore's convention for urlsafe key.
Please let me know if there is any other steps I may not have included and are needed to do to improve the changes.
=> strip padding characters from urlsafe

test_utils/setup.py
@lukesneeringer Why is this a dependency in the `test_utils` package?
=> Removing google-cloud-core dependency in test_utils package.

.circleci/config.yml, appveyor/requirements.txt, bigquery/nox.py, bigtable/nox.py, datastore/nox.py, error_reporting/nox.py, language/nox.py, logging/nox.py, monitoring/nox.py, pubsub/nox.py, spanner/nox.py, speech/nox.py, storage/nox.py, translate/nox.py, vision/nox.py
This is labeled "don't merge" because it is **wrong** in it's current state.
So @lukesneeringer @tseaver @jonparrott WDYT the "correct" form should be? We don't want it to raise on PRs, we want it to gracefully do nothing. Otherwise, this is a helpful message and status for people running tests locally with a "bad" setup.
=> Skipping system tests when credentials env. var is unset.

.circleci/config.yml
Now `openssl` is included in the Docker image.
Thanks a lot @lukesneeringer for updating the image twice!
This should not go in until #3475 does.
=> Remove `apt-get install openssl` from CircleCI config.

speech/google/cloud/speech/_http.py, speech/tests/unit/test_client.py
Append 's' to speechContext in order to work with the API. Stracktrace without:
File "/usr/local/lib/python2.7/dist-packages/google/cloud/speech/sample.py", line 300, in recognize
profanity_filter, speech_contexts)
File "/usr/local/lib/python2.7/dist-packages/google/cloud/speech/_http.py", line 165, in recognize
method='POST', path='speech:recognize', data=data)
File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 303, in api_request
error_info=method + ' ' + url)
google.cloud.exceptions.BadRequest: 400 Invalid JSON payload received. Unknown name "speech_context" at 'config': Cannot find field. (POST https://speech.googleapis.com/v1/speech:recognize)
Aborted (core dumped)
=> Change speechContext to speechContexts.

core/google/cloud/credentials.py, storage/google/cloud/storage/bucket.py
First commit to the repo. The error sends you to a dead page. I updated the reference. I signed a CLA.
=> update doc reference for setting up a service account

bigquery/google/cloud/bigquery/query.py
=> Update 'QueryResponse.fetch_data' docstring to match changes from #3484.

error_reporting/setup.py
See #3579 and #3586 for context.
=> Making requirements tighter for "stable" packages in error reporting 0.25.1 release.

logging/google/cloud/logging/handlers/_helpers.py, logging/nox.py, logging/tests/unit/handlers/test__helpers.py
Code was added in #3448 that set the trace-id when used in the
flask or django web frameworks.
This extends that to also support webapp2.
webapp2 is not cutting edge technology anymore -- it doesn't even work
on python3 -- but a lot of legacy GAE classic apps use webapp2, so I
think it makes sense to support it.
I tested this by running `nox` in the `logging/` directory, which as far
as I can tell is current state of the art for running tests.
=> Add support for logging the trace-id in webapp2 apps.

bigquery/google/cloud/bigquery/dbapi/__init__.py, bigquery/google/cloud/bigquery/dbapi/_helpers.py, bigquery/google/cloud/bigquery/dbapi/connection.py, bigquery/google/cloud/bigquery/dbapi/cursor.py, bigquery/google/cloud/bigquery/dbapi/exceptions.py, bigquery/google/cloud/bigquery/dbapi/types.py, bigquery/tests/system.py, bigquery/tests/unit/test_dbapi__helpers.py, bigquery/tests/unit/test_dbapi_connection.py, bigquery/tests/unit/test_dbapi_cursor.py, bigquery/tests/unit/test_dbapi_types.py
Implements `Cursor.execute()` and `Cursor.fetchone()` without support
for query parameters.
Tested manually with a Jupyter notebook
```
from google.cloud import bigquery
from google.cloud.bigquery import bqdb
connection = bqdb.connect()
cursor = connection.cursor()
cursor.execute("SELECT (1 + 2) AS s;")
cursor.fetchone()
cursor.fetchone()
cursor.description
cursor.rowcount
cursor.execute("DELETE FROM `swast-scratch.hello_world.hello` WHERE id = 1;")
cursor.rowcount
```
Makes progress on https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2434
=> Implementation of DB-API for BigQuery.

spanner/tests/system/test_system.py
Uses #3599 as a base.
Additional system tests for `Snapshot.read`:
- Read timestamp.
- Min read timestamp.
- Max staleness.
- Exact staleness.
- Strong.
=> Spanner p0 system tests (batch #2)

bigquery/README.rst
closes issue https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3610
=> fix big query documentation broken link

bigtable/google/cloud/bigtable/table.py, bigtable/tests/unit/test_table.py
=> Using `CopyFrom` to set protobuf message fields (instead of `MergeFrom`).

bigquery/tests/unit/test_dbapi_cursor.py, logging/tests/unit/handlers/test__helpers.py
`assertEquals` is deprecated (but still is a synonym).
/cc @tswast FYI
=> Using assertEqual instead of assertEquals.

bigquery/google/cloud/bigquery/dbapi/cursor.py, bigquery/google/cloud/bigquery/schema.py, bigquery/tests/unit/test_schema.py
=> BigQuery: Add `is_nullable` method to check for `NULLABLE` mode

storage/tests/unit/test_blob.py
These were "broken" by the release of `google-resumable-media==0.2.0`, but it just revealed that mocked response content was `unicode` when it should have been `bytes`.
=> Fix "bad" storage unit tests.

core/google/cloud/future/base.py, core/google/cloud/future/operation.py, core/setup.py, core/tests/unit/future/test_base.py, core/tests/unit/future/test_operation.py
*Note*: This adds a dependency on the `tenacity` library. It's worth it.
Towards #3617
=> Add operation future

translate/README.rst
due to the change of the Python Client library doc link
=> update the documentation link

spanner/tests/unit/test__helpers.py, spanner/tests/unit/test_batch.py, spanner/tests/unit/test_client.py, spanner/tests/unit/test_database.py, spanner/tests/unit/test_instance.py, spanner/tests/unit/test_session.py, spanner/tests/unit/test_snapshot.py, spanner/tests/unit/test_streamed.py, spanner/tests/unit/test_transaction.py, speech/tests/unit/test_client.py
Any usage of `self.assertTrue(a is b)` has become `self.assertIs(a, b)`.
I used a Python script to make this change:
```python
import collections
def main():
with open('change_it.txt', 'r') as file_obj:
lines = file_obj.read().strip().split('\n')
by_file = collections.defaultdict(dict)
for line in lines:
filename, line_no, content = line.split(':')
line_no = int(line_no)
in_file = by_file[filename]
if line_no in in_file:
raise KeyError('WAT', filename, line_no)
if content[:24] != '        self.assertTrue(':
raise ValueError(line, 'bad 1')
if content[-1] != ')':
raise ValueError(line, 'bad 2')
left, right = content[24:-1].split(' is ')
if ' ' in left or ' ' in right:
raise ValueError(line, 'bad 3')
actual = '        self.assertIs({}, {})'.format(left, right)
in_file[line_no] = (content, …
```
=> Using assertIs in unit tests where appropriate.

speech/README.rst
since it moved to a new URL https://googlecloudplatform.github.io/google-cloud-python/stable/speech/usage.html
=> update documentation link

bigquery/README.rst, bigtable/README.rst, core/README.rst, core/google/cloud/credentials.py, datastore/README.rst, dns/README.rst, error_reporting/README.rst, language/README.rst, logging/README.rst, monitoring/README.rst, pubsub/README.rst, resource_manager/README.rst, runtimeconfig/README.rst, spanner/README.rst, speech/README.rst, storage/README.rst, storage/google/cloud/storage/bucket.py, translate/README.rst, videointelligence/README.rst, vision/README.rst
Done via:
```
$ git grep -l 'google-cloud-auth.html' | \
> xargs sed -i s/'google-cloud-auth.html'/'core\/auth.html'/g
$ git grep -l 'http\:\/\/google-cloud-python.readthedocs.io' | \
> xargs sed -i s/'http\:\/\/google-cloud-python.readthedocs.io'/\
> 'https\:\/\/google-cloud-python.readthedocs.io'/g
```
Fixes #3531.
=> Fixing references to "dead" docs links.

storage/google/cloud/storage/blob.py, storage/google/cloud/storage/bucket.py, storage/tests/unit/test_bucket.py
This PR adds `kwargs` to the `get_blob` method of `google.cloud.storage.Bucket` to support passing `chunk_size`, `encryption_key` and any future parameters the `Blob` constructor may have.
=> Add keyword arguments to google.cloud.storage.Bucket.get_blob.

CONTRIBUTING.rst, README.rst, bigquery/README.rst, bigtable/README.rst, core/README.rst, datastore/README.rst, dns/README.rst, docs/bigtable/usage.rst, docs/index.rst, docs/spanner/usage.rst, error_reporting/README.rst, language/README.rst, logging/README.rst, monitoring/README.rst, pubsub/README.rst, resource_manager/README.rst, runtimeconfig/README.rst, speech/README.rst, storage/README.rst, translate/README.rst, vision/README.rst
Done via
```
$ export OLD='https\:\/\/pypi.python.org\/pypi\/'
$ export NEW='https\:\/\/pypi.org\/project\/'
$ git grep -l ${OLD} | xargs sed -i s/${OLD}/${NEW}/g
```
Then manually going through and adding a trailing slash to all
warehouse links.
(Though I did undo changes to `docs/json/`.)
=> Changing all pypi.python.org links to warehouse links.

spanner/google/cloud/spanner/database.py, spanner/google/cloud/spanner/instance.py, spanner/tests/unit/test_database.py, spanner/tests/unit/test_instance.py
Spanner's docstrings were actually incorrect, as spanner is using gax futures but was documented as using google.cloud.operation. gax futures will be replaced by google.cloud.future.operation and in the meantime the interface is the same. This change removes references to google.cloud.operation.
This is *not* a breaking change for spanner.
Towards #3617
=> Remove references to google.cloud.operation from spanner

README.rst
Add Video Intelligence to list of APIs supported at Beta.  Link to PyPi and package README.
=> Add Video Intelligence to README

bigtable/google/cloud/bigtable/cluster.py, bigtable/tests/unit/test_cluster.py
=> Adding Bigtable Cluster location on create() request.

bigtable/google/cloud/bigtable/cluster.py, bigtable/google/cloud/bigtable/instance.py, bigtable/tests/system.py, bigtable/tests/unit/test_cluster.py, bigtable/tests/unit/test_instance.py
Towards #3617 
**NOTE**: This is a **breaking change**. Bigtable previously returned `google.cloud.operation` instances from long-running operations, it now returns `google.cloud.future.operation` instances.
=> Update bigtable to use operation.future

bigquery/google/cloud/bigquery/job.py, bigquery/tests/system.py, bigquery/tests/unit/test_job.py
=> Add Future interface to BigQuery jobs

core/.flake8, core/google/__init__.py, core/google/cloud/__init__.py, core/google/cloud/_helpers.py, core/google/cloud/_http.py, core/google/cloud/_testing.py, core/google/cloud/client.py, core/google/cloud/future/operation.py, core/google/cloud/iam.py, core/google/cloud/iterator.py, core/google/cloud/operation.py, core/nox.py
NOTE: Pylint is still failing against tests, I have a longer-term strategy to address this which I'll propose later.
=> Fix pylint for the main package

bigquery/google/cloud/bigquery/dbapi/_helpers.py, bigquery/google/cloud/bigquery/dbapi/cursor.py, bigquery/google/cloud/bigquery/job.py, bigquery/tests/unit/test_dbapi__helpers.py, bigquery/tests/unit/test_dbapi_cursor.py, bigquery/tests/unit/test_job.py
=> Remove QueryJob.results()

core/.flake8, core/google/cloud/_helpers.py, core/google/cloud/_http.py, core/google/cloud/client.py, core/google/cloud/credentials.py, core/google/cloud/exceptions.py, core/google/cloud/future/operation.py, core/nox.py, core/tests/unit/test_credentials.py, core/tests/unit/test_iam.py
Note to reviewers: this is intentionally 2 commits. The first re-enables linting, the second addresses lint issues.
=> Re-enable flake8 for core package and tests

spanner/tests/system/test_system.py
Include `NULL` values in `ARRAY<INT64>`.
=> Add systest for round-trip of NULL INT64.

storage/google/cloud/storage/blob.py
=> Adding getter/setter note for Blob.metadata property.

core/google/cloud/_http.py, core/tests/unit/test__http.py
Issue can easily be reproduce with API using list parameters such as `testIamPermissions` in Cloud Storage.
Before the fix, using a list end up with this error:
```
bucket.test_iam_permissions(['storage.buckets.delete','storage.buckets.get'])
```
=> Fix url encoding of list parameters

bigtable/google/cloud/bigtable/client.py, bigtable/nox.py, bigtable/tests/unit/test_client.py, spanner/google/cloud/spanner/client.py, spanner/nox.py, spanner/tests/unit/test_client.py
=> Simplifying Client constructor's for Bigtable and Spanner.

spanner/google/cloud/spanner/database.py, spanner/google/cloud/spanner/session.py, spanner/google/cloud/spanner/snapshot.py, spanner/google/cloud/spanner/streamed.py, spanner/google/cloud/spanner/transaction.py, spanner/tests/system/test_system.py, spanner/tests/unit/test_database.py, spanner/tests/unit/test_session.py, spanner/tests/unit/test_snapshot.py, spanner/tests/unit/test_streamed.py, spanner/tests/unit/test_transaction.py
Multi-use snapshots trigger an "implicit" server-side transaction, and capture its ID on the first request.  Subsequent requests return that ID, allowing for isolation from other changes.  We default to `multi_use=False` because that mode is much more performant for the simple case.
This feature is one which we originally decided to leave out, but the P0 system test list requires that it be implemented.
I *think* that a commitwise review might be easier than reviewing the whole enchilada.
=> Implement multi-use snapshots

README.rst
This change also brings "Cloud Bigtable" together with "Cloud Bigtable -
HappyBase" and adds "Google" prefix to "Cloud Spanner" for consistency with
other products.
=> Alphabetize products for easier visual scanning.
