language/setup.py

```bash
$ git log language-0.25.0..HEAD language/ | grep "^commit"
commit a813160b0e3de635cfba6e5f46099debcd77a08e
commit 14e570a3f435f8904ed9fa52d545a35ba5868ad1
commit 3d9461b91963fcc6e6a864f6f0eacad3d92bbf2d
commit da3a7bbe8c7770540c2149fabfc6f74db89f7ce4
commit bc7b0fdb9fd99b2c86de9830a25cfaaa295b1c45
commit b9cb6d17236528ddce982c3e802af3221de80880
commit 39feb3e23d451963ca31b383d8b395afcf7ab817
commit 6ab3e0127a1edf8b1f9f1603f3c1342473563ea7
```
All except the last (PR #3679) are internal / housekeeping / testing.  So, draft release notes:
----
- Adding a (mostly) autogenerated surface side-by-side with the previously provided Client (#3679)

Prep langauge-0.26.0 release.

---

spanner/google/__init__.py
spanner/google/cloud/__init__.py
spanner/google/cloud/spanner/_helpers.py
spanner/google/cloud/spanner/database.py
spanner/google/cloud/spanner/instance.py
spanner/google/cloud/spanner/pool.py
spanner/google/cloud/spanner/session.py
spanner/google/cloud/spanner/snapshot.py
spanner/google/cloud/spanner/streamed.py
spanner/google/cloud/spanner/transaction.py

- Document missing ':raises:', ':rtype:', and ':returns:'.
- Use ':raises <exception_type>:'.
- Add pro-forma docstrings to namespace package initializers.
- Avoid using 'len(seq) == 0' (or '!=') for boolean tests.
pylint still complains about import cycles:
```
************* Module google.cloud.spanner.streamed
R:  1, 0: Cyclic import (google.cloud.spanner ->
google.cloud.spanner.client -> google.cloud.spanner.instance ->
google.cloud.spanner.database) (cyclic-import)
R:  1, 0: Cyclic import (google.cloud.spanner ->
google.cloud.spanner.client) (cyclic-import)
```

Appease current pylint opinions:

---

bigquery/google/cloud/bigquery/dbapi/__init__.py

Increment to 2 per https://www.python.org/dev/peps/pep-0249/#threadsafety. The cursor object includes some state for paging through results and other things which are not protected by locks.
Closes #3522.

Increment BQ DB-API thread safety.

---

spanner/google/cloud/spanner/__init__.py
spanner/google/cloud/spanner/types.py
spanner/tests/unit/test_types.py

Add factories to ease creation of array / struct parameter types.

---

language/setup.py

* The `encoding_type` is now optional consistently.

Language 0.26.1

---

bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_table.py
storage/google/cloud/storage/blob.py
storage/tests/unit/test_blob.py

BigQuery & Storage: use client http for resumable media

---

storage/google/cloud/storage/bucket.py

`cors`, `labels`, and `lifecycle_rules` all return copies of the values:  changes to them have no effect until the copy is reassigned via the property's setter.
Closes #3710

Document deepcopy semantics of complex bucket properties.

---

storage/google/cloud/storage/blob.py
storage/setup.py
storage/tests/unit/test_blob.py

This won't work until `google-resumable-media==0.2.2` is actually out, but I did install it locally and the unit tests are passing.
Fixes #3703.

Streaming directly into file on storage downloads.

---

pubsub/tests/system.py

Sprinkle majyk retry fairy dust.

---

core/google/cloud/obselete.py
core/tests/unit/test_obselete.py

This will be used to complain if `gapic-google-cloud-{api}-{version}` or `proto-google-cloud-{api}-{version}` are still installed after they are vendored (for GA libraries only).

Add a function to complain about obselete packages.

---

vision/nox.py
vision/setup.py
vision/tests/system_old.py

Fixes #3681.
Also updating the `nox` configuration to allow posargs pass through and be a little more Windows path friendly.

Expanding the allowable descriptions for vision system tests.

---

docs/language/usage.rst
language/tests/system.py

Fixes #3731.
Also relaxing the sentiment score expected range for "Jogging is fun" (the same backend update that changed HTTP to HTTPS changed the score from 0.5 to 0.7).
Also updating the language usage doc with the correct (and HTTPS) URLs for the 3 examples.

Using HTTPS wikipedia links in language system tests.

---

storage/google/cloud/storage/_helpers.py
storage/google/cloud/storage/bucket.py
storage/tests/system.py
storage/tests/unit/test__helpers.py

Uses #3714 as a base.
Note that the test uses the new `Bucket.update` method, rather than `Bucket.patch`, because patch semantics might require that we remember deleted labels (in order to pass `null` as their value).
Closes #7311

Add system test of updating/deleting bucket labels.

---

bigquery/google/cloud/bigquery/_helpers.py
bigquery/google/cloud/bigquery/job.py
bigquery/tests/unit/test__helpers.py

BigQuery: Remove client-side enum validation.

---

storage/setup.py

Did this to update the google-resumable-media dependency to allow for empty files.
See #3685

Update storage to 1.3.1.

---

bigtable/google/cloud/bigtable/table.py
bigtable/tests/unit/test_table.py

This commit adds the `end_inclusive` keyword argument, which can be explicitly passed to get `[start:end]` rather than `[start:end)`.
Fixes #3592.

Allow Table.read_rows to take an inclusive end key.

---

bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_table.py

Add 'Table.row_from_mapping' helper.

---

spanner/google/cloud/spanner/database.py
spanner/tests/unit/test_client.py
spanner/tests/unit/test_database.py

- Preserves "custom" credentials (existing code worked only with implicit credentials from the environment).
- Add tests ensuring scopes are set for correctly for all GAX apis (client uses admin scope, which do not grant data access, while database uses data scope, which does not grant admin access).
Closes #3718.

Reuse explicit credentials when creating 'database.spanner_api'.

---

spanner/google/cloud/spanner/session.py
spanner/tests/unit/test_database.py
spanner/tests/unit/test_session.py

This makes it so `session.run_in_transaction` returns the callback's return value, rather than the commit timestamp.
Fixes #3493.

session.run_in_transaction returns the callback's return value.

---

language/setup.py
speech/setup.py
videointelligence/setup.py
vision/setup.py

Bump GAX dependency to 0.15.14.

---

bigquery/google/cloud/bigquery/table.py

Fixes #3417.
The mentioned `=None` thing is how Sphinx works, and not something we will be changing. The textual descriptions are adequate.

Reference valid input formats in API docs.

---

datastore/google/cloud/datastore/entity.py

Tagging everyone for review since I want to make sure nobody objects.
Note: This is a breaking change for anyone who previously relied on the private `_exclude_from_indexes`. I still consider it to be semver-minor since this was marked private.
Fixes #3508.

Make exclude_from_indexes a set, and public API.

---

index.html

Per https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3595#issuecomment-321019971 `latest` is more frequently updated and `stable` is meaningless.

Change docs link from stable/ to latest/

---

README.rst
bigquery/README.rst
bigtable/README.rst
core/README.rst
datastore/README.rst
dns/README.rst
error_reporting/README.rst
language/README.rst
logging/README.rst
monitoring/README.rst
pubsub/README.rst
resource_manager/README.rst
speech/README.rst
storage/README.rst
trace/README.rst
translate/README.rst
vision/README.rst

See also: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3763
$ sed -i '' 's/googlecloudplatform.github.io\/google-cloud-python\/stable\//googlecloudplatform.github.io\/google-cloud-python\/latest\//g' **/*.rst

Use latest/ directory for docs instead of stable/

---

bigquery/google/cloud/bigquery/_helpers.py
bigquery/google/cloud/bigquery/dataset.py
bigquery/google/cloud/bigquery/schema.py
bigquery/tests/unit/test__helpers.py
bigquery/tests/unit/test_dataset.py
bigquery/tests/unit/test_schema.py
bigtable/google/cloud/bigtable/cluster.py
bigtable/google/cloud/bigtable/column_family.py
bigtable/google/cloud/bigtable/instance.py
bigtable/google/cloud/bigtable/row_data.py
bigtable/google/cloud/bigtable/row_filters.py
bigtable/google/cloud/bigtable/table.py
bigtable/tests/unit/test_column_family.py
datastore/google/cloud/datastore/entity.py
datastore/google/cloud/datastore/helpers.py
datastore/google/cloud/datastore/key.py
monitoring/google/cloud/monitoring/label.py
monitoring/tests/unit/test_label.py
spanner/google/cloud/spanner/database.py
spanner/google/cloud/spanner/instance.py

This updates `__eq__` to do type-checking correctly on all classes (except mock classes defined in unit test modules):
```
def __eq__(self, other):
if not isinstance(other, type(self)):
return NotImplemented
```
It also updates `__ne__` to be _exactly_:
```
def __ne__(self, other):
return not self == other
```
Fixes #3455.

Fix __eq__ and __ne__.

---

monitoring/tests/system.py

Fixes #3739. The max waiting time will be 2 * (1+3+9+27+81) = 242 seconds.

Increase backoff to fix monitoring system test

---

bigquery/google/cloud/bigquery/job.py
bigquery/tests/unit/test_job.py

This provides the nullMarker config option (--null_marker option for CLI) for load jobs.

nullMarker support for BigQuery Load Jobs (#3449)

---

bigquery/google/cloud/bigquery/dbapi/cursor.py
bigquery/tests/unit/test_dbapi_cursor.py

Allow job_id to be explicitly specified.

---

pubsub/tests/system.py

De-flake the snapshot system test.

---

spanner/google/cloud/spanner/session.py
spanner/tests/system/test_system.py

~~Uses #3615 as a base. ca441f7 is the only change from that PR.~~

 Add a test which provokes abort-during-read during 'run_in_transaction'.

---

bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_table.py

Add support for a custom null marker.

---

datastore/google/cloud/datastore/key.py

Document to_legacy_urlsafe as being equivalent (but not identical) to ndb.

---

spanner/google/cloud/spanner/session.py
spanner/google/cloud/spanner/transaction.py
spanner/tests/unit/test_transaction.py

Block creation of transaction for session w/ existing txn.

---

bigquery/google/cloud/bigquery/schema.py
bigquery/tests/unit/test_schema.py

Add SchemaField serialization and deserialization.

---

storage/google/cloud/storage/_helpers.py
storage/google/cloud/storage/bucket.py
storage/tests/system.py
storage/tests/unit/test__helpers.py
storage/tests/unit/test_bucket.py

Uses #3715 as a base.
This PR adds tracking for deleted labels on the `Bucket` object, and causes the appropriate data to be sent when `Bucket.patch` is called.
Fixes #3711.

Storage: Track deleted labels; make Bucket.patch() send them.

---

docs/spanner/snapshot-usage.rst
spanner/google/cloud/spanner/database.py
spanner/tests/system/test_system.py
spanner/tests/unit/test_database.py

Because the context managers they use returned the session to the database's pool, application code could not safely iterate over the result sets returned by the methods.
Update docs for `Snapshot.read` and `Snapshot.execute_sql` to emphasize iteration of their results sets before the session is returned to the database pool (i.e., within the `with` block which constructs the snapshot).
Closes #3769.

Drop 'Database.read' and 'Database.execute_sql' convenience methods.

---

spanner/google/cloud/spanner/database.py
spanner/tests/unit/test_database.py

Fixes #3476.
/cc @vkedia
Note that there is still some limitation on how much we can stop people from firing a blowgun into their foot. Someone could conceivably have two database objects, for example. But this is well within the limits of what we need to check for, in my opinion, especially given that you have to do pretty unusual stuff to even get _this_ far.

Prevent nested transactions.

---

bigquery/tests/system.py

Specify job ID in BQ DB-API DML tests to allow for further test flake
debugging.
Attempting to debug #3742

Wait for load jobs to complete in system tests.

---

docs/spanner/snapshot-usage.rst

See: #3775.
This PR does *not* close that issue:  it only documents the actual, current retry semantics, instead of the intended-but-not-yet-implemented semantics in the current docs.

Document retry of exceptions while streaming 'read'/'execute_sql' results

---

spanner/README.rst

As @vkedia (/cc) pointed out, the existing README is pretty sparse. This improves it.
That said, I have barely _used_ this library and would like to ensure that what I have here is correct and in line with the recommended ways to use the API.
Fixes #3238.

Make the Spanner README better.

---

spanner/google/cloud/spanner/streamed.py
spanner/tests/unit/test_streamed.py

@tseaver @jonparrott @vkedia This is a proposal that fixes #3021. I have not implemented tests yet because I want feedback on the surface first.
I basically followed the SQLAlchemy model; the iterator that comes back gets a `.one()` and `.one_or_none()` method, in lieu of a `read_row()` method on `Database` objects (although it would be easy to implement one and have it call this).
Essentially, where a developer calls `.read()` now, he or she could call `.read().one()` and get the single-result behavior.
If this is workable, then I will write tests.

Spanner: Add a .one and .one_or_none method.

---

datastore/google/cloud/datastore/client.py
datastore/google/cloud/datastore/entity.py
datastore/google/cloud/datastore/transaction.py

Fixes #3232.
Running `nox -s doctests` passes locally (I expect CI will not check it until post-merge):
```
$ nox -s doctests
nox > Running session doctests
nox > The virtualenv name was hashed to avoid being too long.
nox > virtualenv /usr/local/google/home/lukesneeringer/Code/Google/google-cloud-python/datastore/.nox/765eb60c -p python3.6
nox > chdir /usr/local/google/home/lukesneeringer/Code/Google/google-cloud-python/datastore
nox > pip install --upgrade mock pytest sphinx ../core/
nox > pip install --upgrade ../test_utils/
nox > pip install --upgrade .
nox > py.test --quiet tests/doctests.py
.
1 passed in 12.24 seconds
nox > Session doctests successful. :)
```

Make Datastore doctests use a namespace.

---

storage/google/cloud/storage/_signing.py
storage/google/cloud/storage/bucket.py

Make unsigned credentials error DRY.

---

spanner/README.rst

This fixes the mistakes in my previous README (#3791).
/cc @vkedia

Fix Spanner README.

---

storage/setup.py

Did this to update the lower bound on the `requests` dependency (see #3736).
This PR is an alternative to #3812. Note the diffbase is `GoogleCloudPlatform:storage-1.3.2`, which is at the same point as the `storage-1.3.1` branch:
https://github.com/GoogleCloudPlatform/google-cloud-python/commits/storage-1.3.1
https://github.com/GoogleCloudPlatform/google-cloud-python/commits/storage-1.3.2

Update storage to 1.3.2.

---

storage/google/cloud/storage/blob.py

Update reference to bytes signing issue in blob.py

---

core/google/api/core/exceptions.py
core/google/api/core/helpers/datetime_helpers.py
core/google/api/core/retry.py
core/tests/unit/api_core/helpers/test_datetime_helpers.py
core/tests/unit/api_core/test_retry.py

Additionally:
* Add google.api.core.exceptions.RetryError
* Add google.api.core.helpers package
* Add google.api.core.helpers.datetime_helpers module

Add google.api.core.retry with base retry functionality

---

bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_job.py

- Rename class: `jobs.LoadTableFromStorageJob` -> `jobs.LoadJob`.
- Rename class: `jobs.ExtractTableToStorageJob` -> `jobs.ExtractJob`.

Rename job classes

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/dataset.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_dataset.py
bigquery/tests/unit/test_job.py

Rename class: 'dataset.AccessGrant' -> 'dataset.AccessEntry'.

---

bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/query.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py

This method calls the getQueryResults API directly and returns a
QueryResults object. Note: the response from this API does not include
the query, so I modified the constructor to make query optional in this
case.
Addresses #3506

BigQuery - add get_query_results method.

---

bigquery/google/cloud/bigquery/dbapi/cursor.py
bigquery/google/cloud/bigquery/job.py
bigquery/tests/system.py
bigquery/tests/unit/test_dbapi_cursor.py
bigquery/tests/unit/test_job.py

This modifies the QueryJob's Futures interface implementation to poll
using getQueryResults instead of jobs.get. This was recommended by
BigQuery engineers because getQueryResults does HTTP long-polling for
closer to realtime results.
Follow-up to https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3556.

BigQuery: Poll via getQueryResults method.

---

bigquery/google/cloud/bigquery/dbapi/cursor.py
bigquery/google/cloud/bigquery/query.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/system.py
bigquery/tests/unit/test_dbapi_cursor.py
core/google/api/core/page_iterator.py

Allow fetching more than the first page when max_results is set.

---

core/google/api/core/path_template.py
core/tests/unit/api_core/test_path_template.py

Add google.api.core.path_template

---

logging/google/cloud/logging/_helpers.py
logging/google/cloud/logging/client.py
logging/tests/unit/test__helpers.py
logging/tests/unit/test_client.py

For #3622. This fixes the `get_default_handler()` method to let it return the `ContainerEngineHandler` when in GKE environment using the `cluster_name` attribute from the metadata server. If this attribute exists, it should be in GKE environment.

Use metadata server to detect GKE environment

---

pubsub/setup.py

Re-adds the `google-cloud-core` dependency with the new version.
Fixes #3863.

Re-add core dependency

---

dns/setup.py
error_reporting/setup.py
language/setup.py
logging/setup.py
monitoring/setup.py
resource_manager/setup.py
runtimeconfig/setup.py
setup.py
speech/setup.py
translate/setup.py
vision/setup.py

- dns
- error_reporting
- language
- logging
- monitoring
- resource_manager
- runtimeconfig
- speech
- translate
- vision
Also updating bounds on these in `google-cloud` uber-package.
Release notes will be forthcoming as comments on this PR.

Updating 10 packages after google-cloud-core==0.27.0

---

bigtable/setup.py
setup.py

Release notes:
* @lukesneeringer Allow `Table.read_rows` to take an inclusive end key. (#3744)
* @jonparrott Move `google.cloud.future` to `google.api.core` (#3764)
* @tswast Use `latest/` directory for docs instead of `stable/` (#3766)
* @lukesneeringer Fix `__eq__` and `__ne__`. (#3765)
* @lukesneeringer Bump core version number (#3864)

Bigtable 0.27.0

---

setup.py
videointelligence/setup.py

Release notes:
* Fixed incorrect import from `google.cloud.gapic.videointelligence_v1beta1` (should omit `.gapic.`) (#3447)
* Missed an `.items()` on an iteration over a dict. (#3447)
* Fixed references to "dead" docs links. (#3631)
* Tests are now included in `manifest.in` (#3552)
* Update broken links to video intelligence docs in package README (#3458)

Update video intelligence to 0.26.0

---

bigquery/setup.py
setup.py

* Remove client-side enum validation. (#3735)
* Add `Table.row_from_mapping` helper. (#3425)
* Move `google.cloud.future` to `google.api.core` (#3764)
* Fix `__eq__` and `__ne__`. (#3765)
* Move `google.cloud.iterator` to `google.api.core.page_iterator` (#3770)
* `nullMarker` support for BigQuery Load Jobs (#3777), h/t @leondealmeida
* Allow `job_id` to be explicitly specified. (#3779)
* Add support for a custom null marker. (#3776)
* Add `SchemaField` serialization and deserialization. (#3786)
* Add `get_query_results` method. (#3838)
* Poll via `getQueryResults` method. (#3844)
* Allow fetching more than the first page when `max_results` is set. (#3845)
* Bump `requests` minimum bound to 2.18.0 (#3748)
* Reference valid input formats in API docs. (#3758)
* Use `latest/` directory for …

Bump BigQuery to 0.27.0

---

core/google/api/core/retry.py
core/tests/unit/api_core/test_retry.py

Permit application code to reset / fix-up state before retrying.
See: #3889

Add 'on_error' argument to 'retry.retry_target' and 'Retry'.

---

core/setup.py

Draft release notes
- Pin dependency: `six >= 0.10.1`. (issue #3880, PR #3881)
- Add optional `on_error` support to `google.api.core.retry.retry_target`, and the `Retry` wrapper class. (PR #3891)

Prep core-0.27.1 release.

---

runtimeconfig/google/cloud/runtimeconfig/config.py

Typo correction.

---

bigquery/google/cloud/bigquery/_helpers.py
bigquery/tests/unit/test__helpers.py

This is a follow-up to #3901.
Also made sure to return an explicit None in the "field is null" branch. This follows the pattern of "all returns should be explicit or implicit, but don't mix".

Use boolean instead of exception for BigQuery flow control.

---

docs/conf.py
nox.py

Use Sphinx 1.6.3 on local and RTD.

---

pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py

Bugfix
Fix for a new Queue being instantiated regardless of whether a queue is passed in or not.

Use queue if provided in kwargs

---

bigquery/tests/system.py

Follow-up to #3901.
Closes #3870.

BigQuery: Add system tests for microsecond-level precision datetimes

---

bigquery/google/cloud/bigquery/job.py
bigquery/tests/unit/test_job.py

Add 'QueryJob.query_plan' property.

---

bigquery/google/cloud/bigquery/job.py
bigquery/tests/unit/test_job.py

- `total_bytes_processed`
- `total_bytes_billed`
- `billing_tier`
- `cache_hit`
- `num_dml_affected_rows`
- `statement_type`
~~Uses #3799 as a base.~~
Cherry-picked / fixed up from PR #3721.

Add new scalar statistics properties to 'QueryJob'

---

bigquery/google/cloud/bigquery/job.py
bigquery/tests/unit/test_job.py

~~Uses #3800 as a base.~~
Cherry-picked / fixed up from PR #3721.

Add 'QueryJob.referenced_tables' property.

---

bigquery/tests/system.py

I plan to auto-merge here, as it fixes system test breakage on the `bigquery-b2` branch.

Fix system test broken by PR #3798.

---

datastore/google/cloud/datastore/entity.py
datastore/google/cloud/datastore/helpers.py
datastore/tests/unit/test_helpers.py

Allowing `dict` (as an `Entity`) for property values.

---

bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/dbapi/cursor.py
bigquery/google/cloud/bigquery/job.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_job.py

Based on feedback from others in the redesign plan.
The `get_query_results()` function is too low level to expose directly to users.
The result() object should just return the rows as an iterator. This simplifies the proposed query interface to:
job = client.query('MY QUERY')
rows = job.result()
No need for separate fetch_data() call after calling result().

BigQuery: make get_query_results private. Return rows for QueryJob.result()

---

bigquery/.coveragerc
bigquery/google/cloud/bigquery/_helpers.py
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/job.py
bigquery/tests/unit/test__helpers.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_job.py

Note that 177caa5 fixes a longstanding bug:  `Job` configuration properties were not replaced when loading a job from the server.  Unfortunately,  I can't find the bug after the huge pile of issue closures this week.
The helper for constructing concrete query params added in cc4ba04 is a more general form of the one I did in-place in #3802, and should replace that version.

Add 'Client.get_job' API wrapper.

---

bigquery/google/cloud/bigquery/job.py
bigquery/tests/unit/test_job.py

~~Uses #3799 as a base.~~
Cherry-picked / fixed up from PR #3721.
~~Note:  this may need to be fixed up if #3797 merges first.~~

Add 'ExtractTableStorageJob.destination_uri_file_counts' property.

---

docs/bigquery/usage.rst

The following note was listed under "Inserting data (asynchronous)":
* google.cloud.bigquery generates a UUID for each job.
This is incorrect: run_async_query requires a name, which gets passed
as the jobId field to the REST API. For the synchronous case,
run_sync_query calls the query REST API which does not require an ID.
The BigQuery API currently makes no use of UUIDs, so remove the note.

docs/bigquery/usage.rst: Remove incorrect note about UUIDs

---

bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/dataset.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_dataset.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_table.py

The base of this commit is https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3942

BigQuery: Modify client.dataset() to return DatasetReference instead of Dataset.

---

spanner/tests/system/test_system.py
spanner/tests/system/utils/populate_streaming.py
spanner/tests/system/utils/scrub_instances.py

We don't have enough quota to risk orphans.
- Fix `tests/system/utils/populate_streaming` script after PR #3787.
- Add utility for scrubbing orphaned instances.

Suppress instance creation tests by default on CI

---

bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_dataset.py
bigquery/tests/unit/test_table.py

Rename to dataset to be consistent with Client.dataset. Both
methods actually return a DatasetReference.

bigquery: rename TableReference.dataset_ref

---

bigquery/google/cloud/bigquery/dataset.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/query.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_dataset.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_table.py

Rename the former dataset_id property to full_dataset_id.
Also rename Table.dataset_name to Table.dataset_id.
Perform other renamings (of various variables and constants).
These names match usage better. The API's Dataset.id field is
"project:dataset_id", which is confusing and basically useless,
so it's a mistake to call that dataset_id.

bigquery: rename name field of Dataset to dataset_id

---

bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_dataset.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_table.py

bigquery: rename name field of Table to table_id

---

storage/google/cloud/storage/notification.py
storage/tests/unit/test_notification.py

Maps the ['notifications' resource](https://cloud.google.com/storage/docs/json_api/v1/notifications).
Toward #3956.

Add 'BucketNotification' class.

---

storage/google/cloud/storage/bucket.py
storage/tests/unit/test_bucket.py

Uses #3957 as a base.
Toward #3956.

Add 'Bucket.notification' factory

---

bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/query.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_query.py

To go with all our other renames.

BQ: rename XJob.name to XJob.job_id.

---

bigquery/google/cloud/bigquery/_helpers.py
bigquery/tests/system.py
bigquery/tests/unit/test__helpers.py

The timestamp format in query parameters follows the [canonical format](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#timestamp-type).
This fixes a system test error which was happening in the bigquery-b2 branch.
/cc @alixhami

Parse timestamps in query parameters using canonical format

---

storage/google/cloud/storage/notification.py
storage/tests/unit/test_notification.py

Add 'BucketNotification.create' API wrapper.

---

videointelligence/setup.py

Video Intelligence: Bump version to 0.27.0

---

storage/google/cloud/storage/notification.py
storage/tests/unit/test_notification.py

Add 'BucketNotification.delete' API wrapper.

---

storage/google/cloud/storage/notification.py
storage/tests/unit/test_notification.py

Uses #3984 as a base.
Toward #3956.

Add 'BucketNotification.reload' API wrapper.

---

videointelligence/google/cloud/videointelligence_v1beta1/gapic/video_intelligence_service_client.py
videointelligence/google/cloud/videointelligence_v1beta2/gapic/video_intelligence_service_client.py

This fixes an issue where the wrong service address was passed to the LRO client, so `operation.result()` would return a 404.

Pass service address to OperationsClient.

---

bigquery/google/cloud/bigquery/dataset.py
bigquery/tests/system.py
bigquery/tests/unit/test_dataset.py

Dataset won't be able to support this method when we remove its client.  
Don't add `Client.dataset_exists`; the user can use `Client.get_dataset` and catch NotFound.

bigquery: remove dataset.exists

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/_helpers.py
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/job.py
bigquery/tests/system.py
bigquery/tests/unit/test__helpers.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_job.py

Also, add system tests for extract_table.
I introduce a new property type so that the `_properties` dictionary can be more-or-less unmodified from the actual API resource representation.

BQ: client.extract_table starts extract job

---

logging/google/cloud/logging/handlers/transports/background_thread.py
logging/tests/system.py
logging/tests/unit/test_client.py

Fixes #3931.
When GOOGLE_CLOUD_DISABLE_GRPC=true, the logging will have `'AuthorizedSession' object has no attribute 'credentials'` exception.
The line `http = copy.deepcopy(client._http)` is a relic when httplib2 was used. Removing it and directly use the `client` passed in instead of re-initialize with the deepcopied http object solved the problem.

Remove deepcopy of client._http

---

bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/system.py
bigquery/tests/unit/test_dataset.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_table.py

The dataset property (of type DatasetReference) in the TableReference class was primarily being used for the dataset_id and project properties. This change replaces the dataset property with dataset_id and project properties to make TableReference consistent with the Table class.

BigQuery: Remove dataset property from TableReference and add project/dataset_id properties

---

bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/dataset.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_dataset.py

bigquery: add client.list_dataset_tables

---

storage/google/cloud/storage/bucket.py
storage/google/cloud/storage/notification.py
storage/tests/unit/test_bucket.py
storage/tests/unit/test_notification.py

Uses #3983 as a base.
Toward #3956.

Add 'Bucket.list_notifications' API wrapper.

---

spanner/google/cloud/spanner/session.py
spanner/google/cloud/spanner/snapshot.py
spanner/google/cloud/spanner/streamed.py
spanner/tests/unit/test_session.py
spanner/tests/unit/test_snapshot.py
spanner/tests/unit/test_streamed.py

Supersedes #3930.
Closes #3775.
/cc vkedia

Retry streaming exceptions (this time for sure, Rocky!)

---

README.rst
spanner/setup.py

Bitflip to beta.

---

bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/query.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_query.py

Change the type of the Job.default_dataset and Query.default_dataset properties to DatasetReference.

bigquery: Job and Query default_dataset is DatasetReference

---

bigquery/google/cloud/bigquery/_helpers.py
bigquery/tests/system.py
bigquery/tests/unit/test__helpers.py

Adds special cases for loading an array query parameter resource that
contains structs.
Similarly, adds special cases for loading a struct query parameter when
it contains nested structs or arrays.
Note: this is a PR against master since the parsing bug applies there as well.
Closes #4023.

BigQuery: fix parsing for array parameter with struct type.

---

bigquery/google/cloud/bigquery/dataset.py
bigquery/google/cloud/bigquery/schema.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_dataset.py
bigquery/tests/unit/test_table.py

Also, implement equality and hashing for Table & Dataset references.
This will make it easier to use the TableReference and DatasetReference
classes as typed properties in the QueryJob and other job classes.

BigQuery: add to/from API representation for Table & Dataset references.

---

bigquery/google/cloud/bigquery/_helpers.py

Got duplicate definitions after the rebase.

BQ: remove redundant __eq__ from Query Parameters.

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/_helpers.py
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/job.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_job.py

Update CopyJob and CopyJobConfig to conform to the new design for jobs.

bigquery: modify CopyJob

---

docs/spanner/api-reference.rst
docs/spanner/database-usage.rst
docs/spanner/instance-usage.rst
docs/spanner/usage.rst

This improves the left nav for Spanner and generally makes it make more sense.
Fixes the sixth item on @jonparrott's documentation hotlist.

Fix up the documentation nav for Spanner.

---

docs/spanner/database-usage.rst

This corrects the fifth identified documentation item in @jonparrott's notes.

Improve the session pool documentation.

---

docs/spanner/database-usage.rst

This addresses the fourth of @jonparrott's bullet points.

Provide correct API for monitoring an LRO (database).

---

docs/spanner/database-usage.rst

@jonparrott I assume that #4044 also applies to the database iterator, yes?
You did not explicitly say it did, and it is late so my brain is only partially working. Please advise.

Correctly iterate over list_databases.

---

docs/spanner/database-usage.rst

Addresses the third of @jonparrott's individual documentation concerns.

Just refer to operations as being like Future.

---

docs/spanner/instance-usage.rst

Corrects the item thus identified in @jonparrott's comment.

Correct documentation about instance iterators.

---

core/google/api/core/gapic_v1/method.py
core/tests/unit/api_core/gapic/test_method.py

Add google.api.core.gapic_v1.method

---

core/google/api/core/gapic_v1/method.py
core/tests/unit/api_core/gapic/test_method.py

Add wrap_with_paging

---

storage/google/cloud/storage/_helpers.py
storage/tests/unit/test__helpers.py

Support 'user_project' in '{Bucket,Blob}.update'

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/query.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py

The query_rows() method will be the new way to run a query
synchronously. It starts a query job, then waits for the results,
returning the rows as results.

BigQuery: add client.query_rows(), remove client.run_sync_query().

---

core/google/api/core/gapic_v1/__init__.py
core/google/api/core/gapic_v1/method.py
core/tests/unit/api_core/gapic/test_method.py

This is needed because the wrapped gapic methods can't discern between "unspecified" and "None" because the gapic clients will *always* specify retry and timeout, e.g.:
```python
def get_operation(name, retry=None, timeout=None):
request = operations_pb2.GetOperationRequest(name=name)
return self._get_operation(request, retry=retry, timeout=timeout)
```
gapic methods will use this sentinel to indicate unspecified:
```python
def get_operation(name, retry=gapic_v1.method.DEFAULT, timeout=gapic_v1.method.DEFAULT):
request = operations_pb2.GetOperationRequest(name=name)
return self._get_operation(request, retry=retry, timeout=timeout)
```

Add DEFAULT sentinel for gapic_v1.method

---

storage/google/cloud/storage/client.py
storage/nox.py
storage/tests/system.py
storage/tests/unit/test_client.py

Skips the new test unless an environment variable, `GOOGLE_CLOUD_TESTS_USER_PROJECT`, is set.
@lukesneeringer What project should that be set to for CI?

Extend test of 'requester_pays' bucket to include RUD w/ 'user_project' set

---

storage/tests/system.py

Test bucket IAM/ACL methods w/ 'user_project' set.

---

storage/tests/system.py

Test blob ACL methods w/ 'user_project' set.

---

core/setup.py
language/setup.py
logging/setup.py
pubsub/setup.py
spanner/setup.py
speech/setup.py
trace/setup.py
videointelligence/setup.py
vision/setup.py

This is due to `google-gax` doing the same, which has broken
RTD builds:
https://readthedocs.org/projects/google-cloud-python/builds/6063446/
The motivation for avoiding `grpcio==1.6.0` is:
https://github.com/grpc/grpc/issues/12455
----
@lukesneeringer I'm unclear, but it's possible that `googleapis-common-protos` will need to have the strict upper bound set as well (it currently has `>= 1.0.0`).

Avoiding `grpcio==1.6.0` in deps.

---

storage/tests/system.py

~~Uses #4099 as a base.~~
Closes #4100.

Lengthen expiration for signed URL.

---

storage/tests/system.py

Supersedes PR #4032.
Allows 429 errors to be handled by retry.
See:
https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4032#issuecomment-332032204

Remove use of batch when cleaning up buckets.

---

bigquery/nox.py
bigtable/nox.py
datastore/nox.py
firestore/nox.py
language/nox.py
logging/nox.py
monitoring/nox.py
pubsub/nox.py
spanner/nox.py
speech/nox.py
storage/nox.py
translate/nox.py

Done via:
```
$ git grep -l virutal | xargs sed -i s/virutal/virtual/g
```

Fixing virutal->virtual typo.

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/job.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_job.py

This PR handles loading from GCS. Loading from a local file will be done separately.

bigquery: modify LoadJob

---

core/setup.py
language/setup.py
logging/setup.py
pubsub/setup.py
spanner/setup.py
speech/setup.py
trace/setup.py
videointelligence/setup.py
vision/setup.py

Also
- removing `grpcio` from non-`core` packages.
- manually specifying the `grpcio` dep in core (rather than getting it from `googleapis-common-protos[grpc]`)
(**NOTE**: This is a followup to #4096.)

Removing `googleapis-common-protos` from deps in non-`core` packages.

---

docs/pubsub/index.rst

Fix pubsub landing page example for 'create_topic'.

---

storage/tests/system.py

Note that both new tests are failing.
Because they have to be explicitly enabled (via the `GOOGLE_CLOUD_TESTS_USER_PROJECT`` environment variable, which we aren't yet setting for CI), this PR is OK to merge.

Test 'Blob.rewrite' w/ 'user_project' set.

---

storage/google/cloud/storage/bucket.py
storage/google/cloud/storage/notification.py
storage/nox.py
storage/tests/system.py
storage/tests/unit/test_bucket.py
storage/tests/unit/test_notification.py

N.B.:  the tests currently fail with a 403:
```python
____________ TestStorageNotificationCRUD.test_notification_explicit ____________
File "/home/tseaver/projects/agendaless/Google/src/google-cloud-python/storage/tests/system.py", line 628, in test_notification_explicit
retry_429(notification.create)()
File "/home/tseaver/projects/agendaless/Google/src/google-cloud-python/storage/.nox/sys-3-6/lib/python3.6/site-packages/test_utils/retry.py", line 95, in wrapped_function
return to_wrap(*args, **kwargs)
File "/home/tseaver/projects/agendaless/Google/src/google-cloud-python/storage/google/cloud/storage/notification.py", line 243, in create
data=properties,
File "/home/tseaver/projects/agendaless/Google/src/google-cloud-python/storage/.nox/sys-3-6/lib/python …
```

Add system tests for bucket notifications.

---

core/google/api/core/operation.py
core/google/api/core/operations_v1/__init__.py
core/google/api/core/operations_v1/operations_client.py
core/google/api/core/operations_v1/operations_client_config.py
core/tests/unit/api_core/operations_v1/test_operations_client.py
core/tests/unit/api_core/test_operation.py

Add google.api.core.operations_v1

---

core/tests/unit/api_core/gapic/test_method.py

Fix test assertion in test_wrap_method_with_overriding_retry_deadline

---

bigquery/google/cloud/bigquery/client.py
bigquery/tests/system.py

BigQuery was only returning the first column when passing in a list
instead of a comma-separated string.

BQ: Pass selected_fields as a string to tabledata.list.

---

bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/dbapi/cursor.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/query.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_dbapi_cursor.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_query.py

Based on https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4143.
Now QueryResults is just a container for the getQueryResults response.

BQ: remove fetch_data and client references from QueryResults

---

trace/google/cloud/trace/__init__.py
trace/google/cloud/trace/client.py

Adding the scope needed when setting credentials file via `$GOOGLE_APPLICATION_CREDENTIALS`.

Add scope for trace client

---

bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_table.py

Unfortunately there's no good way to write a system test for this,
since you can never be sure that one gets created. But I informally
verified that the code works by running create_rows a lot until
I got a streaming buffer.

bigquery: add streaming buffer info

---

storage/google/cloud/storage/_helpers.py
storage/google/cloud/storage/acl.py
storage/google/cloud/storage/blob.py
storage/google/cloud/storage/bucket.py
storage/google/cloud/storage/client.py
storage/tests/system.py
storage/tests/unit/test__helpers.py
storage/tests/unit/test_acl.py
storage/tests/unit/test_blob.py
storage/tests/unit/test_bucket.py
storage/tests/unit/test_client.py

Closes #3474.
Needs extra system tests which pass `user_project` to the various APIs which take it, in the context of a bucket which is created with `requester_pays` enabled.

Re-enable 'Bucket.requester_pays' feature

---

bigquery/tests/system.py

This should prevent failures like https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3684
> Conflict: 409 POST https://www.googleapis.com/bigquery/v2/projects/precise-truck-742/jobs: Already Exists: Job precise-truck-742:test_query_w_query_params_3684_1507750606

BQ: use random job ID for system tests.

---

bigquery/google/cloud/bigquery/client.py
bigquery/tests/unit/test_client.py

If the user doesn't provide row IDs, create unique IDs for them.

bigquery: generate row IDs in create_rows

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/_helpers.py
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/job.py
bigquery/tests/unit/test_client.py

Add retry logic to every RPC for which it makes sense.
Following the BigQuery team, we ignore the error code and
use the "reason" field of the error to determine whether
to retry.

bigquery: retry idempotent RPCs

---

bigquery/google/cloud/bigquery/client.py
bigquery/tests/unit/test_client.py

This will match behavior of copy_table and remove the need for special
formatting of the keyword arguments.

BQ: use a string or list of string for client.extract_table.

---

storage/google/cloud/storage/notification.py
storage/tests/system.py
storage/tests/unit/test_notification.py

Add 'user_project' support to BucketNotification API methods.

---

pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py

Move debug statement with blocking future.result() call to add_done_callback

---

pubsub/setup.py

Release notes will be:
* Fix a bug with debug logging causing unintentional blocking behavior (#4174, h/t @jeffkpayne)
* Fix a bug where explicitly-provided queues were ignored (#3924, h/t @garykrige)
* Remove of `grpcio` as an explicit dependency; now a transitive dependency of `google-gax` only (#4098)
* Update `gcloud-common` nomenclature to `google-cloud-common` (#4180)

Pub/Sub version bump: 0.28.4

---

spanner/google/cloud/spanner_v1/session.py
spanner/nox.py
spanner/tests/system/test_system.py
spanner/tests/unit/test_session.py

That helper raises non-`ABORTED` exceptions, which makes reusing the session impossible if the transaction is not cleared.
Closes #4181.
/cc @vkedia

Clear 'session._transaction' before calling '_delay_unitl_retry'. 

---

setup.py
storage/google/cloud/storage/blob.py
storage/setup.py
storage/tests/unit/test_blob.py

This change depends on https://github.com/GoogleCloudPlatform/google-resumable-media-python/pull/31

Catch checksum validation failure from download, delete corrupt file

---

README.rst
bigquery/README.rst
bigtable/README.rst
core/README.rst
datastore/README.rst
dns/README.rst
docs/index.rst
error_reporting/README.rst
firestore/README.rst
language/README.rst
logging/README.rst
monitoring/README.rst
pubsub/README.rst
resource_manager/README.rst
runtimeconfig/README.rst
spanner/README.rst
speech/README.rst
storage/README.rst
trace/README.rst
translate/README.rst
videointelligence/README.rst
vision/README.rst

As requested in b/64770713.
Considering the structure of documentation it makes more sense to add the setup guide here as well as in the documentation.

Add Links to Python Setup Guide

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/external_config.py
bigquery/tests/unit/test_external_config.py

These classes will be used to configure external table
definitions for queries (transient external tables)
as well as external data configurations for tables (permanent
external tables).
This PR just establishes the classes. Subsequent PRs will
wire them into query jobs and tables.

bigquery: classes to support external table config

---

bigquery/google/cloud/bigquery/_helpers.py
bigquery/google/cloud/bigquery/external_config.py
bigquery/google/cloud/bigquery/job.py
bigquery/nox.py
bigquery/tests/system.py
bigquery/tests/unit/test_external_config.py
bigquery/tests/unit/test_job.py

Also, set ExternalConfig.options based on source_format, and
make read-only.
Also, change from_api_repr functions in external_config.py so that
they don't modify their resource argument. This simplifies tests.

bigquery: support external table definitions for query jobs

---

bigquery/nox.py
docs/bigquery/snippets.py

Converts snippet function names to pytest conventions (shouldn't affect
the docs, as the docs use region tags to grab sub-sections to include.
I had to make some minor changes to ensure that the samples work on both
Python 2 and Python 3, which is why I didn't try to bulk update the
snippets for all the other products.

BQ: Make snippets.py run as system tests.

---

storage/google/cloud/storage/_helpers.py
storage/google/cloud/storage/acl.py
storage/google/cloud/storage/blob.py
storage/google/cloud/storage/bucket.py
storage/google/cloud/storage/client.py
storage/google/cloud/storage/notification.py

Clarify 'user_project' semantics for API wrapper methods.

---

core/google/api/core/future/polling.py

Working towards https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4135

Clarify that PollingFuture timeout is in seconds.

---

pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/tests/system.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py

@lukesneeringer Here's my attempt at a system test for the fix in #4174 
Let me know how I can improve it, etc.  Thanks.

Add PubSub system test for fix in #4174

---

bigquery/google/cloud/bigquery/job.py
bigquery/tests/system.py
bigquery/tests/unit/test_job.py

Validations in the `LoadJob` class were set to disallow a schema to be set while autodetect is True. This raised an error when running `client.get_job()` and `client.list_jobs()` for LoadJobs that were created with `autodetect=True` because the jobs came back with the schema having been set. The additional code added in system tests shows how to reproduce the bug.

BigQuery: removes LoadJob error for autodetect=True and schema set

---

bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/job.py
bigquery/tests/unit/test_job.py

This will allow QueryJob to respect the timeout value for futures.
Closes #4135.

BigQuery: populate timeout parameter for getQueryResults

---

bigquery/google/cloud/bigquery/_helpers.py
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test__helpers.py

New helper function to factor out repetitive code in client.py and table.py

BigQuery: Adds helper function for snake to camel case conversion

---

spanner/google/cloud/spanner_v1/streamed.py
spanner/tests/unit/test_streamed.py

Fixes #4164.
(Uses #4169 as a _de facto_ base.)

Be permissive about merging an empty list.

---

bigquery/google/cloud/bigquery/client.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py

Renamed so we can add functionality to use URIs that point to [Bigtable instances](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load.sourceUris)

BigQuery: Renames client.load_table_from_storage() to client.load_table_from_uri()

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/_helpers.py
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/dataset.py
bigquery/google/cloud/bigquery/dbapi/__init__.py
bigquery/google/cloud/bigquery/external_config.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/query.py
bigquery/google/cloud/bigquery/schema.py
bigquery/google/cloud/bigquery/table.py
bigtable/google/cloud/bigtable/table.py
docs/bigquery/client.rst
docs/bigquery/dataset.rst
docs/bigquery/dbapi.rst
docs/bigquery/job.rst
docs/bigquery/query.rst
docs/bigquery/reference.rst
docs/bigquery/schema.rst
docs/bigquery/table.rst
docs/bigquery/usage.rst

All the public classes we expect developers to use are included in the
`google.cloud.bigquery` module, and it is this module that we use in
code samples.
Also, I found one error in the Bigtable docs where `Row` was not being
used as a local reference and conflicted with the BigQuery Row.

BigQuery: make docstrings use bigquery module, like the samples do.

---

bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/job.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py

This covers the primary reason one would want the job ID from an
exception in query rows: to cancel the job.
Replaces https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4240.

BigQuery: cancel query on exception in query_rows.

---

storage/setup.py
storage/tests/unit/test_blob.py

Fixes #4243.
Also increasing the lower-bound on `google-resumable-media` to `0.3.1`.

Updating some storage mocks after `google-resumable-media==0.3.1` release.

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/dataset.py
bigquery/google/cloud/bigquery/external_config.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/query.py
bigquery/google/cloud/bigquery/schema.py
bigquery/google/cloud/bigquery/table.py
docs/bigquery/reference.rst

Basically a revert of https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4236.
The reason is that I did not see references to any of the properties on QueryJobConfig such as https://github.com/GoogleCloudPlatform/google-cloud-python/blob/09cf23a0f83baaaea95cd98c260ab7c2f8e4f699/bigquery/google/cloud/bigquery/job.py#L1386 in the docs I built with `nox -s docs`. I tried a few thing to get them to render, but with no success.
Per http://www.sphinx-doc.org/en/stable/ext/autodoc.html
> Note that attributes from imported modules will not be documented, because attribute documentation is discovered by parsing the source file of the current module.
So, we can't use imported modules from the `google.cloud.bigquery` package and also show the attribute docs. This change allows Sphinx to …

BigQuery: use full sub-module aliases in docstrings.

---

api_core/google/api_core/gapic_v1/method.py
api_core/google/api_core/operations_v1/operations_client.py
api_core/tests/unit/gapic/test_method.py

Remove gapic_v1.method.wrap_with_paging

---

README.rst

Correcting Firestore release level Beta, not Alpha
@dhermes apologies I missed this on your previous change.

Bump Firestore to Beta

---

pubsub/google/cloud/pubsub_v1/publisher/batch/base.py
pubsub/google/cloud/pubsub_v1/publisher/batch/thread.py
pubsub/tests/unit/pubsub_v1/publisher/batch/test_thread.py

Fixes a bug where `max_messages` is not honored when autocommit is on.

Honor max_messages always.

---

docs/bigtable/data-api.rst
docs/bigtable/instance-api.rst
docs/pubsub/index.rst
docs/pubsub/subscriber/index.rst

Fixed some typos in docs about following services.
- Bigtable
- PubSub

Fix some typos

---

api_core/google/api_core/protobuf_helpers.py
api_core/tests/unit/test_protobuf_helpers.py

Closes #3842 
Note: this is directly ported from gax, barring minor changes, this code has already been reviewed.

Add final set of protobuf helpers to api_core

---

docs/pubsub/index.rst
docs/pubsub/subscriber/index.rst
pubsub/google/cloud/pubsub_v1/exceptions.py
pubsub/google/cloud/pubsub_v1/futures.py
pubsub/google/cloud/pubsub_v1/publisher/batch/base.py
pubsub/google/cloud/pubsub_v1/publisher/batch/thread.py
pubsub/google/cloud/pubsub_v1/publisher/futures.py
pubsub/google/cloud/pubsub_v1/subscriber/futures.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/tests/unit/pubsub_v1/publisher/test_futures.py
pubsub/tests/unit/pubsub_v1/subscriber/test_futures_subscriber.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py

This causes the `.open` method on subscriptions to return a future, which can be used to block the main thread or trap exceptions.
Fixes #3888.
Fixes #4019.
@jonparrott A couple items we should nail down and possibly tweak before merging this:
* The current interface has a three-object pass to start consuming messages: instantiate a client, instantiate a subscription, then call `.open` on the subscription, which now returns a future. However, we currently have some shortcut logic that lets you pass a `callback` on step 2. You still get the subscription back, but `.open` is called implicitly; there's no good place for me to return the future in that case.
* This is kind of a big deal; this future is basically _the_ way to both block and handle errata.
* On the other hand, maybe this is …

Add futures for subscriptions.

---

bigquery/benchmark/README.md
bigquery/benchmark/benchmark.py
bigquery/benchmark/queries.json

Runs queries and measure time to first response
and time to iterate all rows

bigquery: add simple benchmark

---

api_core/setup.py
core/setup.py

This is to make it clear the code is between releases. Towards #4208.
See: https://snarky.ca/how-i-manage-package-version-numbers/

Explicitly marking `google-cloud-core` and `google-api-core` as "dev".

---

bigquery/setup.py

This is to make it clear the code is between releases. Towards #4208.
See: https://snarky.ca/how-i-manage-package-version-numbers/
/cc @tswast

Explicitly marking `google-cloud-bigquery` as "dev".

---

bigtable/setup.py
datastore/setup.py
dns/setup.py
error_reporting/setup.py
firestore/setup.py
language/setup.py
logging/setup.py
monitoring/setup.py
pubsub/setup.py
resource_manager/setup.py
runtimeconfig/setup.py
setup.py
spanner/setup.py
speech/setup.py
storage/setup.py
trace/setup.py
translate/setup.py
videointelligence/setup.py
vision/setup.py

This is to make it clear the code is between releases. Any code that relies on a **new** feature (e.g. of `google-api-core`) will then be able to **explicitly** make this clear by using the lower bound of the `devN` version.
Fixes #4208.
See: https://snarky.ca/how-i-manage-package-version-numbers/

Marking all remaining versions as "dev".

---

README.rst
bigquery/README.rst
bigtable/README.rst
core/README.rst
datastore/README.rst
dns/README.rst
docs/index.rst
error_reporting/README.rst
firestore/README.rst
logging/README.rst
monitoring/README.rst
pubsub/README.rst
resource_manager/README.rst
runtimeconfig/README.rst
spanner/README.rst
speech/README.rst
storage/README.rst
trace/README.rst
translate/README.rst
videointelligence/README.rst
vision/README.rst

Also obeying an 80-column limit for the content and adding a missing "``virtualenv``" in the phrase "``pip`` and ``virtualenv``" in some of the docs.

Fixing "Fore" -> "For" typo in README docs.

---

trace/tests/unit/test__gax.py

Doing this because [on Windows][1], when parsed into a protobuf and converted back to a string, trailing zeros are truncated.
[1]: https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-python/build/1.0.2506.master/job/xl4wk678mibxw0wa

Comparing `datetime.datetime`-s in trace unit tests.

---

CONTRIBUTING.rst
api_core/nox.py
appveyor.yml
bigquery/nox.py
bigtable/nox.py
core/nox.py
datastore/nox.py
dns/nox.py
error_reporting/nox.py
firestore/nox.py
language/nox.py
logging/nox.py
monitoring/nox.py
pubsub/nox.py
resource_manager/nox.py
runtimeconfig/nox.py
spanner/nox.py
speech/nox.py
storage/nox.py
trace/nox.py
translate/nox.py
videointelligence/nox.py
vision/nox.py

Ok yeah, this didn't take a lot of manual editing (j/k).  If this is the way we go, that should do it.

Closes #4319 - shorten test names

---

CHANGELOG.md
language/CHANGELOG.md
language/setup.py
setup.py

[![release level](https://img.shields.io/badge/release%20level-beta-yellow.svg?style&#x3D;flat)](https://cloud.google.com/terms/launch-stages)
* This update is considered a final "release candidate", and the `google-cloud-language` package is preparing for a GA release in the near future.
* Some rarely-used arguments to the `LanguageServiceClient` constructor have been removed (in favor of a subclass or a custom gRPC channel). It is unlikely that you used these, but if you did, then this update will represent a breaking change.
* The removed arguments are: `client_config`, `lib_name`, `lib_version`, `metrics_headers`, `ssl_credentials`, and `scopes`.
* Added the `classify_text` method on the primary (`v1`) endpoint. (#4283)

Version bump for language / metapackage.

---

api_core/google/api_core/retry.py
bigtable/google/cloud/bigtable/table.py
bigtable/tests/unit/test_table.py

Trying a new PR in place of (https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4116). 
Reason: A mistake was made in `git rebase` commits that are already pushed to remote, where a `git merge` should have been done.

Retry for 'mutate_rows' that return retryable errors.

---

bigtable/google/cloud/bigtable/row_data.py
bigtable/tests/unit/read-rows-acceptance-test.json
bigtable/tests/unit/test_row_data.py

This problem was reported by a customer. As background, the empty string is a valid column qualifier. A missing qualifier, as opposed to the empty string, means the previously seen qualifier should be applied instead.
I added a new test case that has a cell with a column qualifier of empty string arriving after a cell with a non-empty qualifier. The code fails to distinguish between a missing qualifier and an empty qualifier and overwrites the empty string with the first qualifier.
With no code changes the new test case fails. I attempted to fix the bug in `row_data.py` but this causes other failures. I was hoping someone could pick this up and investigate.

Bigtable ReadRows doesn't handle empty string column qualifier

---

bigtable/google/cloud/bigtable/table.py
bigtable/tests/unit/test_table.py

BigTable: Small docs/hygiene tweaks after #4256.

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/_helpers.py
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/query.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test__helpers.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_table.py
bigtable/google/cloud/bigtable/table.py

- Imports `Row` in `__init__.py`
- Moves `Row` from `_helpers.py` to `table.py` because it is a public class
- Updates incorrect docstrings for functions returning an `Iterator` of `Row` objects

BigQuery: moves Row class out of helpers and updates docstrings

---

docs/language/releases.rst
docs/releases.rst
language/setup.py
setup.py

In particular:
- Marking the package versions as "dev"
- Updating the `releases.rst` for the packages
(Again, this showcases a "need" for the `releases.rst` files to be checked in some automated way.)

Post-release cleanup for language and `google-cloud`.

---

bigtable/google/cloud/bigtable/table.py
bigtable/tests/unit/test_table.py

/cc @dhermes 
As discussed in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4333, this change addresses the input retry=None for `mutate_rows`. @jonparrott I made an internal error `_BigtableRetryableError` and have it be used to trigger the retry instead of raising a fake `SerivceUnavailable`. Would like to get your opinion regarding this use.
Also factored out test response creation and replaced the magic numbers with constants for RPC Status Code. And removed the extra `the` from the error message.

Handle retry=None for mutate_rows, and some refactoring in test

---

api_core/google/api_core/gapic_v1/method.py
api_core/tests/unit/gapic/test_method.py

One change I liked from @eoogbe's now closed #4322 is to make the `_GapicCallable` method use a generic `metadata` argument. This does *not* add a generic metadata argument to `wrap_method`.

Make gapic's wrapper accept generic metadata

---

spanner/tests/system/test_system.py

Abrupt shutdown (maybe CircleCI auto-cancellation?) can cause them not to be cleaned up.

Avoid sharing database name between testcase classes.

---

storage/google/cloud/storage/client.py
storage/setup.py
storage/tests/system.py
storage/tests/unit/test_client.py

Enable anonymous access to blobs in public buckets

---

bigquery/tests/unit/test_dataset.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_query.py
bigquery/tests/unit/test_schema.py
bigquery/tests/unit/test_table.py
dns/tests/unit/test_changes.py
dns/tests/unit/test_zone.py

Done via:
```
$ git grep -l makeResource | xargs sed -i s/makeResource/make_resource/g
```

Renaming `makeResource` -> `make_resource`.

---

api_core/google/api_core/gapic_v1/routing_header.py
api_core/tests/unit/gapic/test_routing_header.py

Example:
```python
routing_header = google.api_core.gapic_v1.routing_header(
[('name', name), ('book.read', book.read)])
self._create_book(request, retry=retry, timeout=timeout, metadata=[routing_header])
```

api_core: Add routing header

---

datastore/google/cloud/datastore/client.py
datastore/google/cloud/datastore/helpers.py
datastore/google/cloud/datastore/query.py
datastore/tests/unit/test_client.py
datastore/tests/unit/test_helpers.py

Allow specifying read consistency

---

spanner/tests/system/test_system.py

Because of quota, we are sharing the instance we use to test CRUD of databases: we therefore cannot rely on having only the expected databases present, as other tests may be running simultaneously, or may have failed
in ways which left 'stray' databases in the instance.

Harden spanner system tests against stray databases

---

datastore/google/cloud/datastore/client.py
datastore/google/cloud/datastore/helpers.py

@dhermes Some cosmetic changes to #4343.  I must have forgotten a comment there regarding the alignment and moved the imports back to where they were.

cosmetic changes to address #4343

---

spanner/tests/_fixtures.py
spanner/tests/system/test_system.py

- Write / read back null string.
- Write / read back empty array of string.
- Write / read back null array of string.
- Write / read back array of string with mixed null / non-null values.
Toward #4364.

Add spanner system tests:

---

datastore/google/cloud/datastore/query.py
datastore/tests/unit/test_query.py

Depending on empty value of `response_pb.batch.end_cursor` is not reliable as the behaviour is not documented. It's better to check API response field `moreResults`, see
https://cloud.google.com/datastore/docs/reference/rpc/google.datastore.v1#google.datastore.v1.QueryResultBatch.
Closes #4347.

Set next_page_token to none if there are no more result

---

storage/google/cloud/storage/bucket.py
storage/google/cloud/storage/client.py
storage/google/cloud/storage/notification.py
storage/tests/unit/test_bucket.py
storage/tests/unit/test_client.py
storage/tests/unit/test_notification.py

Make 'project' optional / overridable for storage client

---

datastore/google/cloud/datastore/_http.py
datastore/google/cloud/datastore/client.py
datastore/tests/unit/test__http.py
datastore/tests/unit/test_client.py

- Making the method arguments (both in position and name) match the arguments for `google.cloud.datastore_v1.gapic.datastore_client.DatastoreClient`
- Passing positional as positional and keyword as keyword when using the low-level API client in `Client.get()` (was previously using all keyword arguments to `.lookup()`, which caused this issue)
- Updating mock call assertions to match the change in calling behavior.
Fixes #4387.

Updating datastore HTTP wrapper.

---

bigquery/tests/unit/test_job.py

This happened because #4350 was sent before #4355 was merged.
/cc @alixhami This may have been avoidable (e.g. with a rebase) but since there were no changes needed in the review, it's likely that this was just unavoidable (except for superhumans).

Post #4350 cleanup: Missed a rename of a test helper due to concurrent merges

---

pubsub/README.rst

Ensure that quickstart examples actually work.

---

api_core/google/api_core/datetime_helpers.py
api_core/setup.py
api_core/tests/unit/test_datetime_helpers.py
core/google/cloud/_helpers.py
core/tests/unit/test__helpers.py

Move datetime helpers from google.cloud._helpers to google.api_core.datetime_helpers

---

bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_table.py

I forgot to ask for these in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4393 before I merged.

BigQuery: docs for Row.keys, items, values, and get functions.

---

bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_table.py

Reverts GoogleCloudPlatform/google-cloud-python#4410
Broke system tests.

Revert "BigQuery: docs for Row.keys, items, values, and get functions."

---

bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_table.py

The table list response only includes a subset of all table properties.
This commit adds a new type to document explicitly which properties are
included, but also make it clear that this object should not be used in
place of a full Table object.
Towards #4373 (needs a similar change for dataset listing before closing that issue)

BigQuery: Use TableListItem for table listing.

---

bigquery/google/cloud/bigquery/dataset.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_dataset.py
bigquery/tests/unit/test_table.py

This makes it easier to call `get_table`, `get_dataset`, or other
functions that want just a reference, not a full resource.
Closes https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4327

BigQuery: add reference property to Table and Dataset

---

pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
pubsub/pylint.config.py

- Configured PyLint to ignore generated code
- Addressed all PyLint failures in `subscriber.policy.base`

Some lint hygiene for Pub/Sub.

---

pubsub/tests/system.py

Also
- Using `topic_path()` and `subscription_path()` (along with `unique_resource_id()`) rather than a hard-coded path in `_resource_name()`
- Dropping the usage of `mock` in favor of `__call__`-able types
- Re-using the **same** publisher and subscriber via module-level fixtures
- Adding a `cleanup` fixture instead of the `try/finally` indirection
- Making sure that `call_count` (now named `calls`) is thread safe
- Cleaning up subscriptions that are created (they were previously leaked)

Using `pytest` fixtures in Pub/Sub system tests.

---

pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_base.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py

**NOTE**: I am **NOT** comfortable with this as a fix, it seems **WAAAAAY** too bolted on.
- ~~I'm surprised the retry strategy doesn't come into play here~~
- ~~There should a less hard-coded way to map to the idempotent retry codes~~
- ~~The method should have a straightforward way to determine the gRPC status code from the exception~~
- `RuntimeError: set_exception can only be called once` occurs if I don't filter out the `UNAVAILABLE` ([e.g.][1]). This seems like a bug in a different code path than is covered here.
----
- Adding special handling for API core exceptions
- Retrying on both types of idempotent error
- Also doing a "drive-by" hygiene fix changing a global from `logger` to `_LOGGER`
Towards #4234.
[1]: https://gist.github.com/dhermes/488bf528e10456d3e2266e163ae1a72d

PubSub: Making `thread.Policy.on_exception` more robust.

---

docs/bigquery/snippets.py
docs/bigquery/usage.rst

I created a new test user and shared the login info with cloud devrel folks.
Also, splits out access control sample for datasets into a standalone snippet for use in cloud.google.com docs.
Closes #4457.

Use a valid email address in access control snippets.

---

pubsub/nox.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py

Also modifying a unit test to call `policy.on_exception()` **outside** of an "assert raises".
I noticed these issues during review of #4380.

Passing `posargs` to `nox -s unit` in Pub / Sub.

---

firestore/tests/unit/test__helpers.py

Saw this as I was adding in functionality.  Making separate PR to clean up.

Firestore: Import column lengths pass 79

---

pubsub/setup.py

This is a follow-up to #4462, where I forgot to add it. In
the current form, `pip` adds a 0 at the end for us:
```
$ virtualenv venv
$ venv/bin/pip install pubsub/
$ venv/bin/pip show google-cloud-pubsub
Name: google-cloud-pubsub
Version: 0.29.2.dev0
...
```

Changing `dev` to `dev1` in Pub / Sub version.

---

docs/bigquery/reference.rst

This PR adds headers to visually separate the sections in the API reference page of the BigQuery client library docs.

BigQuery docs: adds headers to API reference page

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py

Uses newline character when logging protobufs that may end up having newlines in them. These are harder to grok in the log output since it "blends" the protobuf and the description. For example.
```
Received response: received_messages {
ack_id: "Pn41MEV..."
message {
data: ...
```
vs.
```
Received response:
received_messages {
ack_id: "Pn41MEV..."
message {
data: ...
```
Also
- replaced a `lambda` with a simple function
- added docstrings to two default callbacks used by the `policy.thread.Policy` implementation.
- updated grammatical error in a comment
- replaced a bare `if future` with `if future is not None`
----
Context: I have discovered each of these "issues" while dealing with #4463 and #4234.

Pub/Sub logging hygiene.

---

pubsub/google/cloud/pubsub_v1/publisher/batch/thread.py

@lukesneeringer Is there a reason you were using the root logger?

Using logger for module in Pub/Sub publisher.

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/_helper_threads.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py

Now names will show up in logs as
```
Thread-ConsumerHelper-CallbackRequestsWorker
Thread-ConsumerHelper-ConsumeBidirectionalStream
```
instead of as
```
Consumer helper: callback requests worker
Consumer helper: consume bidirectional stream
```
This is a follow up to #4474.

Renaming "Consumer helper" threads in Pub/Sub.

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/futures.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py

PubSub: `Policy.on_exception` actually used to make consumer go inactive.

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/_helper_threads.py
pubsub/google/cloud/pubsub_v1/subscriber/message.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py

- Using `%`-formatting in all `logging.log()` calls (e.g. `info()`). I am not opposed to using `.format()` but `logging` "prefers" `%`-formatting (and I wanted to be consistent because hobgoblins).
- Adding non-public globals for helper thread names, this was especially needed because I accidentally broke this in #4476 when I changed `callback requests worker` to `CallbackRequestsWorker` in one place, not two.
- Adding docstring to `QueueCallbackThread` that explains what it does (I'll refactor this class in a follow-up)
- Adding a logging statement when a `QueueCallbackThread` exits
- Changing indents / using much more vertical space in calls to `request_queue.put()` in `subscriber.message.Message`. (I came across these when trying to understand how `QueueCallbackThread` interacts with …

Various hygiene changes to Pub / Sub subscriber.

---

bigquery/google/cloud/bigquery/client.py
bigquery/tests/unit/test_client.py

This makes `update_table` consistent with `update_dataset`. Also,
documents the arguments to `update_table`.
Closes #4452.

BigQuery: Rename `properties` arg to `fields` in `update_table`

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/_helper_threads.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
pubsub/tests/unit/pubsub_v1/subscriber/test_helper_threads.py

Actually **stopping** the Pub / Sub consumer on an exception.

---

pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py

This is a follow-on to  #4474 and #4476.

Adding thread prefix for ThreadPoolExecutor in Pub/Sub.

---

pubsub/CHANGELOG.md
pubsub/setup.py
setup.py
videointelligence/setup.py

Follow-up to today's releases.
Has #4500 as diffbase.
@lukesneeringer Do we have a tag for the "uber"-package / umbrella-package?

Adding `.dev1` suffix to recently released packages.

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/_helper_threads.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
pubsub/tests/unit/pubsub_v1/subscriber/test_helper_threads.py

~~This makes the `request_queue` used by `Consumer._request_generator_thread()` local to the caller. This way on recovery a new queue can be used for the new thread.~~

Make sure inactive request generator is stopped before spawning new one in Pub / Sub consumer.

---

logging/nox.py

See:
https://www.djangoproject.com/weblog/2017/dec/02/django-20-released/
Python 2.7 support is explicitly removed.

Pinning `django` test dependency to < 2.0 in Python 2.7.

---

spanner/tests/_fixtures.py
spanner/tests/system/test_system.py

I'm trying for smaller PRs to simplify debugging/code writing for other issues.

Spanner: Read single key with index

---

pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_base.py

The original intent was to keep `bytes` at or above `0` but `min([-n, 0]) == -n` and more importantly `min([n, 0]) = 0` so that `bytes` would be artificially dropped to `0` when `drop()` is called.
FWIW I was worried this was a data race issue, but I'm fairly certain it isn't. If in fact it turns out to be, we can add a no-op lock class on `base.BasePolicy`
```python
import contextlib
@contextlib.contextmanager
def _no_op_lock():
"""No-op context manager."""
yield
class BasePolicy(object):
_LOCK_TYPE = _no_op_lock
def __init__(self, ...):
...
self._bytes_lock = self._LOCK_TYPE()
```
and then define `_LOCK_TYPE = threading.Lock` on our concrete implementation and use `self._bytes_lock` whenever modifying `Policy().bytes`.
Fixes #4516.

Bugfix: Using `max` where `min` was used by mistake to ensure a value is non-negative

---

logging/nox.py

See failure:
https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-python/build/1.0.2663.master/job/rfi7n10xteq2r4xp
/cc @jonparrott Worth having some `nox` helper to tell the active Python or naw?

Adding another check for Python 2.7 in Logging `nox -s default`.

---

api_core/setup.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/setup.py

See: https://github.com/agronholm/pythonfutures/issues/63
----
ASIDE: For the first time, the `.dev1` versions come in handy to specify the actual ways a package depends on **in development** vs. published.

Requiring latest release of concurrent futures backport.

---

bigtable/google/cloud/bigtable/table.py

Bigtable tables cannot be renamed.  I'm removing the comment that says that rename is allowed.

Removing "rename" from bigtable table.py comments

---

pubsub/CHANGELOG.md
pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/_helper_threads.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/tests/unit/pubsub_v1/subscriber/test_helper_threads.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py

- Renaming `QueueCallbackThread` -> `QueueCallbackWorker`.
- Also fixing a few typos nearby a mention of `QueueCallbackThread` in `pubsub/CHANGELOG.md`.
- Making `Policy.on_callback_request()` less open-ended (renaming to `dispatch_callback` to make it clear that it's essentially acting as a dispatch table for a given action)

Refactor Pub / Sub callback queue

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py

Doing so to make it clearer what is happening during construction.
Also
- removing the `_callback_requests` member (not needed)
- modifying some docstrings in the `pubsub_v1.subscriber._constructor`
module so that it is valid Sphinx/rST
---
This is just "hygiene" to keep my head less cluttered as I attempt a larger re-factor.

Re-factoring `Policy` constructor.

---

pubsub/google/cloud/pubsub_v1/subscriber/_helper_threads.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_base.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py

~~Has #4535 as diffbase.~~
I'll follow this up with a PR that completely removes the `HelperThreadRegistry`.

Dropping usage of `HelperThreadRegistry` in Pub / Sub policy.

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/_helper_threads.py
pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
pubsub/tests/unit/pubsub_v1/subscriber/test_helper_threads.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py

I'll likely put back in **some** of the features (especially the concept of the namedtuple that knows about the thread **AND** the queue / threading.Event).

Removing Pub / Sub HelperThreadRegistry.

---

docs/trace/releases.rst
trace/CHANGELOG.md
trace/setup.py

@dhermes I need to bump the version number from 0.16.0 to 0.17.0 to avoid breaking the OpenCensus package which is depending on `google-cloud-trace>=0.16.0, <0.17dev`. Could you do a release for the trace package? Thanks a lot!

Preparing release 0.17.0 of trace

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_base.py

Also renaming `Consumer._exiting` as `Consumer.stopped` (and making it a public member).

Removing redundant Pub / Sub `Consumer.active` member.

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/_histogram.py
pubsub/google/cloud/pubsub_v1/subscriber/client.py
pubsub/google/cloud/pubsub_v1/subscriber/message.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py

Make `Policy` the parent of `Consumer` and explicitly require passing a `policy` into `Consumer.start_consuming()` (and its helpers).

Break Policy<->Consumer reference cycle.

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_base.py

Using these (rather then open/close on the subscription Policy) when the flow control signals the message load is too great.

Adding pause/resume to Pub / Sub consumer.

---

datastore/google/cloud/datastore/client.py
datastore/google/cloud/datastore/transaction.py
datastore/tests/system/test_system.py
datastore/tests/unit/test_client.py
datastore/tests/unit/test_transaction.py

Changes reflecting review and Luke's autogen (please see #4348 for issues regarding his autogen).  A manual fix has been included.
Closes #4335.  This includes reviews and changes from there.

Datastore: Add support for 'TransactionOptions'

---

api_core/CHANGELOG.md
api_core/setup.py
pubsub/CHANGELOG.md
pubsub/setup.py

@jonparrott I would like to squeeze in a change to `api_core/CHANGELOG.md` to this PR as well with the updates based on the (currently not mentioned in notes) PRs #4339, #4336, #4367, #4399.

Post PR #4559: add back `.dev1` to version numbers.

---

storage/google/cloud/storage/notification.py
storage/tests/unit/test_notification.py

ProjectID description from https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects#Project.FIELDS.project_id
#4447

Storage: ProjectID Regex

---

spanner/tests/system/test_system.py

For some reason, a similar code wasn't working for me the other day and failed with:
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Endpoint read failed)>
But it now works.

Spanner: Range read with keys and index

---

spanner/tests/system/test_system.py

I'm separating the tests into different PRs to minimize the damage.  I plan to do the refactor once all the tests are all in and I'll do it separately so I don't change too much code at once.

Spanner: Range single keys index

---

spanner/google/cloud/spanner_v1/streamed.py
spanner/tests/system/test_system.py
spanner/tests/unit/test_snapshot.py
spanner/tests/unit/test_streamed.py

Spanner: Make rows, consume_all and consume_next private

---

firestore/google/cloud/firestore_v1beta1/collection.py
firestore/tests/unit/test_collection.py

This PR removes `{'i', 'I', 'l', 'o', 'O', '0', '1'}` from the set of characters used in automatically-generated IDs, because it is easy to mis-read them if you are in a situation where you need to do that.
Exact set of blacklisted characters is loaned from Django's [`make_random_password`](https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#django.contrib.auth.models.BaseUserManager.make_random_password).
/cc @schmidt-sebastian

Do not use easily-misread glyphs in Firestore auto-IDs.

---

spanner/tests/system/test_system.py
spanner/tests/unit/test_streamed.py

Spanner: Rows_  to list in test_streamed

---

api_core/google/api_core/gapic_v1/method.py

It looks like it was moved to `google.api_core.gapic_v1.client_info` and during the move the delete was forgotten.

Removing redundant constant.

---

firestore/google/cloud/firestore_v1beta1/collection.py
firestore/tests/unit/test_collection.py

Reverts GoogleCloudPlatform/google-cloud-python#4107

Revert "Do not use easily-misread glyphs in Firestore auto-IDs."

---

api_core/google/api_core/grpc_helpers.py
api_core/tests/unit/test_grpc_helpers.py

Apply scopes to explicitly provided credentials if needed

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_base.py

**NOTE**: Has #4603 as diffbase.
I think the function call overhead is worth the trade-off of a "clean" surface (i.e. we could swap out `Consumer` for a `multiprocessing` implementation if need be).

Adding a `Consumer.active` property to Pub / Sub.

---

pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py

Similar with `Policy.close()`.
Fixes #4488.

Making it impossible to call `Policy.open()` on an already opened policy.

---

pubsub/google/cloud/pubsub_v1/publisher/batch/base.py
pubsub/nox.py
pubsub/tests/unit/pubsub_v1/publisher/batch/test_base.py

Also adding a note about the fleeting nature of the "will accept?" check.

Adding extra check in `Batch.will_accept` for the number of messages.

---

pubsub/google/cloud/pubsub_v1/publisher/client.py
pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py

This is the first stage of moving that check directly into `Batch.publish()`. This check **must** occur when the message is being published because concurrent access to the messages and futures on a `Batch` make it impossible to reliably do an LBYL "will accept?" check.
Towards #4575.

Moving `will_accept()` check out of `PublisherClient.batch()` factory.

---

pubsub/google/cloud/pubsub_v1/publisher/batch/base.py
pubsub/google/cloud/pubsub_v1/publisher/batch/thread.py
pubsub/tests/unit/pubsub_v1/publisher/batch/test_thread.py

Adding a "STARTING" status for Pub / Sub `Batch.commit()`.

---

spanner/tests/system/test_system.py

Spanner: multiple ranges single key

---

spanner/tests/unit/test_session.py

Stop using a non-public `grpcio` API in Spanner tests.

---

pubsub/google/cloud/pubsub_v1/publisher/batch/base.py
pubsub/google/cloud/pubsub_v1/publisher/batch/thread.py
pubsub/google/cloud/pubsub_v1/publisher/client.py
pubsub/tests/unit/pubsub_v1/publisher/batch/test_thread.py
pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py

Unit tests will be coming in the next commit.
Fixes #4575.

Checking Pub / Sub `Batch.will_accept` in thread-safe way.

---

CHANGELOG.md
bigquery_datatransfer/setup.py
container/setup.py
docs/pubsub/releases.rst
docs/releases.rst
pubsub/CHANGELOG.md
pubsub/setup.py
setup.py
trace/setup.py

Also:
- Making a release of the umbrella package (since `google-cloud-pubsub` has transition from `0.29.x` to `0.30.x`)
- Updating version with `.dev1` suffix in `bigquery_datatransfer`, `container` and `trace` packages
- Adding `google-cloud-bigquery-datatransfer` and `google-cloud-container` to umbrella package
~~**NOTE**: This **must** wait on #4616.~~

Creating `google-cloud-pubsub==0.30.0` release.

---

spanner/tests/system/test_system.py

This got closed inadvertently in #4434 
Breaking this up for integration 7 test.

Spanner: invalid type test

---

CHANGELOG.md
pubsub/CHANGELOG.md
pubsub/setup.py
setup.py

Also
- Removing "Pub / Sub" mention from the Pub / Sub changelog since it is redundant.
- Fixing a bad link (to vision package on PyPI) in the umbrella package changelog

Adding back `.dev1` suffixes after #4619.

---

pubsub/google/cloud/pubsub_v1/publisher/batch/base.py
pubsub/google/cloud/pubsub_v1/publisher/batch/thread.py
pubsub/google/cloud/pubsub_v1/publisher/client.py
pubsub/tests/unit/pubsub_v1/publisher/batch/test_thread.py
pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py

Allowing over-ride for lock used in publisher client.

---

dataproc/google/cloud/dataproc_v1/gapic/cluster_controller_client.py
dataproc/setup.py
pubsub/google/cloud/pubsub_v1/publisher/client.py

Also:
- Fix an ambiguous name (`type`) in Pub / Sub (was introduced
because I merged with the docs build failing)
- Marking the `dataproc` version as `.dev1`

Fix build issue with dataproc docs.

---

pubsub/google/cloud/pubsub_v1/futures.py

Similar to [`STOP`][1]. ~~Though empirically I'm not seeing the object ID change across threads or across `multiprocessing` processes.~~
Since I wanted to be thorough, here is why we do this. An object ID won't change (on unix) when using "fork". Running
```python
import multiprocessing
import sys
SENTINEL = object()
def f():
process = multiprocessing.current_process()
print('multiprocessing.current_process(): {}'.format(process))
print('SENTINEL: {}'.format(SENTINEL))
def main():
multiprocessing.set_start_method(sys.argv[1])
print(SENTINEL)
proc1 = multiprocessing.Process(target=f)
proc2 = multiprocessing.Process(target=f)
proc1.start()
proc2.start()
proc1.join()
proc2.join()
if __name__ == '__main__':
main()
```
we see:
```
$ python do_it.py fork
<object object at 0x7ff33c64c180> …
```

Use a UUID (rather than a sentinel object) for sentinel on Pub / Sub `Future`.

---

spanner/google/cloud/spanner_v1/database.py
spanner/tests/system/test_system.py
spanner/tests/unit/test_database.py

Spanner: Database not found

---

pubsub/tests/system.py

This was a programming error on my part (using a brand new lock every time it was held).
See recent failure: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/4853

Fixing race condition in Pub / Sub system tests.

---

bigquery_datatransfer/README.rst
bigquery_datatransfer/docs/index.rst
container/README.rst
container/docs/index.rst
dataproc/README.rst
dataproc/docs/index.rst
test_utils/scripts/update_docs.sh

Also fixing some bad links in the 3 newest packages.
(This is only for **our** docs, projects that don't secretly contain 15+ subprojects typically have useful `stable/` docs.)
Related to #4637.

Replacing references to `stable/` docs with `latest/`.

---

logging/google/cloud/logging/_gax.py
logging/google/cloud/logging/_http.py
logging/google/cloud/logging/sink.py
logging/tests/unit/test__gax.py
logging/tests/unit/test__http.py
logging/tests/unit/test_sink.py

#4578 Not sure if this is right, but an attempt.

Logging: Unique Writer Identity

---

datastore/google/cloud/datastore/key.py
datastore/tests/unit/test_key.py

Fixes #3597
I encountered an issue with respect to urlsafe keys in a system that is using _both_ `google-cloud-datastore` and `ndb` in different services.  I was receiving incompatible urlsafe keys when using the _output_ of `to_legacy_urlsafe` in things like `ndb.Key(urlsafe=<output_from_legacy_urlsafe>)` running under App Engine. I received the following error:
```
BadRequestError: app s~your-app-id cannot access app your-app-id's data
```
I then tried the suggestion as per #3597 of adding the location prefix to the project under cloud-datastore like so:
`datastore.Client(project='s~your-app-id')`
Unfortunately, I was met with this error (where `your-app-id` is a real project, with active datastore db which I can access via the Google Cloud Console):
```
The project s~your-app-id does …
```

Adds optional location_prefix kwarg in to_legacy_urlsafe

---

api_core/setup.py
core/setup.py
pubsub/setup.py

This is due to a nasty spinlock [bug][1] that has been partially [fixed][2] in `1.8.2`.
[1]: https://github.com/grpc/grpc/issues/9688
[2]: https://github.com/grpc/grpc/pull/13665

Requiring 'grpcio >= 1.8.2'.

---

api_core/CHANGELOG.md
api_core/setup.py
docs/core/releases.rst
docs/pubsub/releases.rst
pubsub/CHANGELOG.md
pubsub/setup.py

Also making `google-api-core==0.1.3` release.
This settles my "should I or shouldn't I?" hesitation about explicitly depending on `grpcio` in `google-cloud-pubsub`.

Making `google-cloud-pubsub==0.30.1` release.

---

storage/google/cloud/storage/bucket.py
storage/tests/unit/test_bucket.py

Storage: support 'sourceGeneration' in 'copy_blob'

---

bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/dbapi/cursor.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/query.py
bigquery/tests/unit/test_dbapi_cursor.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_query.py

The QueryResults object is not necessary to be used by external
developers, but it is still needed internally for the getQueryResults
API response.
From BigQuery team's GA review of the library.

BQ: remove QueryJob.query_results(), make QueryResults private

---

bigquery/CHANGELOG.md
bigquery/google/cloud/bigquery/client.py
bigquery/tests/system.py
docs/bigquery/snippets.py
docs/bigquery/usage.rst

`list_dataset_tables` was needlessly verbose. Feedback from BQ GA review.
Even though we aren't GA yet, I deprecate rather than remove because we've just done a ton of breaking changes with 0.28.0 release and I'd rather not increase the fatigue of upgrading versions needlessly.

BigQuery: deprecate list_dataset_tables in favor of list_tables

---

bigtable/google/cloud/bigtable/row_filters.py

end points excluded
closes #4666

Bigtable: Row filter end points documentation error

---

bigquery_datatransfer/README.rst
bigquery_datatransfer/docs/index.rst

BigQueryDataTransfer: update 404 link for API documentation

---

bigquery_datatransfer/README.rst

Package name is google-cloud-bigquery-datatransfer not google-cloud-bigquerydatatransfer

bq-data-transfer: fix package name in readme

---

bigquery/nox.py

Resolves https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4587

BigQuery: skips pandas when running python 3.4 nox session

---

bigquery/CHANGELOG.md
bigquery/google/cloud/bigquery/client.py
bigquery/tests/system.py
docs/bigquery/snippets.py
docs/bigquery/usage.rst

`insert_rows` aligns better with API request (Tabledata.insertAll). Feedback from BQ GA review.
Note that the [`create_rows()` sample in the Python migration guide](https://cloud.google.com/bigquery/docs/python-client-migration#streaming_data_into_a_table) already points to a commit hash, so this should be safe to merge whenever.

BigQuery: Add Client.insert_rows, deprecate Client.create_rows

---

appveyor.yml
bigquery_datatransfer/nox.py
container/nox.py
dataproc/nox.py

Manually changed.  Where do I change the generator?
@dhermes @lukesneeringer

nox unittest updates

---

bigquery/google/cloud/bigquery/client.py
core/google/cloud/client.py

Also, use Napoleon-style docs for the changed docs.

DOCS: DefaultCredentialsError could be raised if credentials not supplied

---

bigquery/CHANGELOG.md
bigquery/setup.py
docs/bigquery/releases.rst

-  Remove `QueryJob.query_results()`. Use `QueryJob.result()` instead (#4652).
-  Remove `Client.query_rows()`. Use `Client.query()` instead (#4429).
-  Make `Client.list_tables` return an iterator of `TableListItem`, because the API only returns a subset of properties of a table when listing (#4427).
-  Make `Client.list_datasets` return an iterator of `DatasetListItem`, because the API only returns a subset of properties of a dataset when listing (#4439).
-  Add `Client.insert_rows()` and `Client.insert_rows_json()`, deprecate `Client.create_rows()` and `Client.create_rows_json()` (#4657).
-  Add `Client.list_tables`, deprecate `Client.list_dataset_tables` (#4653).
-  Add `to_dataframe()` method to row iterators. When Pandas is installed, it returns a `DataFrame` …

Prep bigquery-0.29.0 release.

---

bigquery/CHANGELOG.md
bigquery/setup.py

Mark bigquery as back under dev after 0.29.0 release.

---

logging/google/cloud/logging/sink.py
logging/tests/unit/test_sink.py

Accomodate back-end change making 'Sink.filter' optional.

---

logging/tests/unit/test__helpers.py

Harden test for 'retrieve_metadata_server' against transparent DNS proxies

---

logging/google/cloud/logging/sink.py
logging/tests/unit/test_sink.py

Expose writerIdentity returned in sink resource.

---

api_core/google/api_core/page_iterator.py
api_core/tests/unit/test_page_iterator.py
bigquery/tests/unit/test_table.py
datastore/google/cloud/datastore/query.py
datastore/tests/unit/test_query.py

This is necessary because some clients, such as Spanner, will basically hand the user the page iterator returned from gapic, but need to apply their own transformer.

api_core: Make PageIterator.item_to_value public.

---

logging/google/cloud/logging/sink.py
logging/tests/unit/test_sink.py

Preps support for passing it to 'update' as well.
See:
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4703#issuecomment-355622741

Move 'unique_writer_identity' from LogSink ctor to 'create'

---

logging/google/cloud/logging/_gax.py
logging/google/cloud/logging/_http.py
logging/google/cloud/logging/sink.py
logging/tests/unit/test__gax.py
logging/tests/unit/test__http.py
logging/tests/unit/test_sink.py

Capture server-generated 'writerIdentity' during 'LogSink.create'

---

api_core/google/api_core/grpc_helpers.py
api_core/tests/unit/operations_v1/test_operations_client.py
api_core/tests/unit/test_grpc_helpers.py

This is intended to help with testing *all* grpc-based clients. With this, we should be able to mostly avoid using mock/fakes/stubs and instead use this channel-based approach. This means that *every* layer of the client is tested and there is less concern about a mock/stub/fake not matching its upstream target. This is akin to mocking at the requests level for HTTP clients.
@dhermes: I considered putting this into a package like `api_core.testing.grpc_stub`, but I decided against it. I'm happy to reconsider.

api_core: Add grpc.Channel stub to grpc_helpers

---

logging/google/cloud/logging/_gax.py
logging/google/cloud/logging/_http.py
logging/google/cloud/logging/sink.py
logging/tests/unit/test__gax.py
logging/tests/unit/test__http.py
logging/tests/unit/test_sink.py

~~Uses #4707 as a base.~~
Also, capture server-set read-only properties returned from `sinks.update`, such as `writerIdentity`.

Support passing 'uniqueWriterIdentity' to 'Sink.update'.

---

bigquery/google/cloud/bigquery/job.py
bigquery/tests/unit/test_job.py

BigQuery: missing return value in LoadJobConfig.from_api_repr and LoadJobConfig Tests

---

api_core/google/api_core/page_iterator.py
api_core/tests/unit/test_page_iterator.py
bigquery/tests/unit/test_table.py
datastore/google/cloud/datastore/query.py
datastore/tests/unit/test_query.py
spanner/google/cloud/spanner_v1/client.py
spanner/google/cloud/spanner_v1/instance.py

This reverts commit 813a27e80a879fe9129ad7f5db83387c3387cff0.
This is done to prevent a release-the-world scenario in order to release bigquery, spanner, and datastore. It will be re-reverted before the next minor release of api_core.

Revert "api_core: Make PageIterator.item_to_value public. (#4702)"

---

spanner/google/cloud/spanner_v1/keyset.py
spanner/tests/unit/test_keyset.py

Please make sure that this is the behavior wanted!
I documented it to state that.

Spanner: Keyset defaults to start or end_closed = []

---

docs/spanner/transaction-usage.rst

Spanner documentation to suggest use run_in_transaction and add in commit and rollback should not be used manually.  See #4710

Spanner: Update documentation to explicitly discourage manual transaction management

---

spanner/tests/system/test_system.py

There are still a couple of them that use session, I'll look later on them.

Spanner: system tests use database instead of session

---

docs/storage/releases.rst
storage/CHANGELOG.md
storage/setup.py

- Enable anonymous access to blobs in public buckets (#4315).
- Make `project` optional / overridable for storage client (#4381).
- Relax regex used to test for valid project IDs (#4543).
- Add support for `source_generation` parameter to `Bucket.copy_blob` (#4546).

Prep storage-1.7.0 release.

---

spanner/tests/unit/test_keyset.py

Also reworked the `to_pb()` tests to just create a protobuf and
just use one assertion.
--------------------------------------------------------------------------------------------------
This test got reverted and I think it should still be there.

Adding a unit test with the empty list case in `KeyRange.to_pb()`.

---

bigquery/google/cloud/bigquery/schema.py
bigquery/tests/unit/test_schema.py

This should fix #4456 
I added safe attribute access to the optional properties `mode` and `fields` in the param dictionary, using the default parameteres from the constructor as fallback values.
I couldn't find the appropiate place to update the docs if it's necessary, so any pointer is greatly appreciated. :)
🐍

Add handling of missing properties in SchemaField.from_api_repr()

---

docs/bigquery/snippets.py

This was causing some fun failures: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/5213?utm_campaign=build-failed&utm_medium=email&utm_source=notification

Make row assertion in sample tests account for non-deterministic order

---

storage/google/cloud/storage/blob.py

In the  _download_to_file_ function within _blob.py_ I think the line in the docstring is supposed to read "For more fine-grained **control** over the download process..." where the word "control" has been accidentally omitted.

Missing word in docstring

---

dataproc/docs/index.rst
dataproc/docs/releases.rst
dataproc/setup.py

This step was also straightforward. 
Maybe put a template in the doc for how to format the releases.rst if it can't be generated? I copied/modified from another api.

Updated version number for 0.1.0 release

---

bigquery/google/cloud/bigquery/client.py

Closes #3928 
Clarifies the page token parameter.

BigQuery: Documentation clarification for page_token

---

docs/bigquery/snippets.py
docs/bigquery/usage.rst

Samples for each API tab in https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-json
Also: use `delete_contents=True` on dataset clean-up so that they are still cleaned up if there are errors loading the table.

BigQuery: samples for loading JSON from Cloud Storage.

---

speech/google/cloud/speech_v1/helpers.py
speech/tests/unit/gapic/v1/test_helpers.py

Actual fix for #4820 (caused by regenerating the gapic layer)

Fix speech helpers to properly pass retry and timeout args

---

bigtable/google/cloud/bigtable/row.py
bigtable/tests/unit/test_row.py
core/google/cloud/exceptions.py

Added retry logic for commit on a DirectRow. The retry uses the retry.py module and performs retry when a Rendezvous exception is thrown due to a disconnect on the channel. The retry will call MutateRow on the original protobuf request with a timeout backoff algorithm provided in retry.py. This has been tested using an endurance test framework that runs for 23 hours and was receiving 8+ exceptions previously. Now all the retries are successful.

refactor retry logic on mutate row

---

docs/spanner/releases.rst
spanner/CHANGELOG.md
spanner/setup.py

Spanner 1.0.0 Release

---

spanner/tests/system/test_system.py

I didn't think we should retry all the `ClientErrors`, so maybe just deal with it if they happen.

Spanner: retry conflict errors in system test

---

pubsub/google/cloud/pubsub_v1/types.py

The Pub/Sub default is 10 MB. This allows sending the max batch size unless the user intervenes.

Pub/Sub: Update default batch size to 10 MB

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_table.py

As part of a query, load job, or create table request, you can specify the encryption configuration, which just consists of a single string field containing the KMS key to use.

Add support for EncryptionConfiguration

---

docs/bigquery/snippets.py
docs/bigquery/usage.rst

Also, removes assert for state == 'RUNNING' from snippets, as this is flaky for small jobs that complete very quickly.
The key used is one that I've created which is accessible to all users. This means anyone can still run the system tests.
Based on https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4845

 BigQuery: add code snippet for CMEK table loading.

---

pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py

Fix unit test for default `max_bytes` value

---

logging/google/cloud/logging/handlers/transports/background_thread.py
logging/tests/unit/handlers/transports/test_background_thread.py

This PR adds a new parameter `max_latency` to `BackgroundThreadTransport` in logging. It can be used to enforce batching by asking the transport to wait for new log messages for a specified amount of time. This is useful to avoid hitting the Stackdriver Logging rate limit.
This PR is written on behalf of Spotify, who, as a company, has signed a corporate CLA. The idea for this PR is based on a support case with Google.

Add max_latency to BackgroundThreadTransport

---

bigquery/google/cloud/bigquery/job.py
bigquery/tests/system.py
bigquery/tests/unit/test_job.py

Resolves https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4246 by bypassing property validation in `QueryJobConfig.from_api_repr()`. A `QueryJobConfig` object can be created for an invalid job retrieved from the API, but validation will still occur when assigning invalid property values through the setters.

Allow listing/getting jobs even when there is an "invalid" job.

---

bigquery/tests/system.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_job.py

BigQuery: Use constant strings for job properties

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/google/cloud/pubsub_v1/types.py
pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_base.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py

This change includes the consumer's pending request backlog in the policy's load calculations. This allows the policy to pause (and resume) the response stream if there are a large number of outstanding requests to be send on the stream. This additionally adds `max_requests` to `FlowControl` to allow tweaking this number.
Resolves: #4792
Related: #4841

Add pending request backpressure for subscriber.

---

pubsub/google/cloud/pubsub_v1/subscriber/_helper_threads.py
pubsub/google/cloud/pubsub_v1/subscriber/message.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/google/cloud/pubsub_v1/types.py
pubsub/tests/unit/pubsub_v1/subscriber/test_helper_threads.py
pubsub/tests/unit/pubsub_v1/subscriber/test_message.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_base.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py

The size of the batches and the rate at which they are submitted is controlled by two new flow control settings, `max_request_batch_size` and `max_request_batch_latency`.
Closes #4893

Add ability for subscriber to batch requests.

---

api_core/setup.py
bigquery/setup.py
bigquery_datatransfer/setup.py
bigtable/setup.py
container/setup.py
core/setup.py
dataproc/setup.py
datastore/setup.py
dlp/setup.py
dns/setup.py
error_reporting/setup.py
firestore/setup.py
language/setup.py
logging/setup.py
monitoring/setup.py
oslogin/setup.py
pubsub/setup.py
resource_manager/setup.py
runtimeconfig/setup.py
spanner/setup.py
speech/setup.py
storage/setup.py
trace/setup.py
translate/setup.py
videointelligence/setup.py
vision/setup.py

This was done with this script: https://gist.github.com/jonparrott/34fa5e883ddff596a0a4529199022bb2
/cc @lukesneeringer the generator should be updated to output setup.py files in this format.

Normalize all setup.py files

---

datastore/google/cloud/datastore/helpers.py
datastore/tests/unit/test_helpers.py

Closes #3152.
Adds a breaking unit test for the bug in the first commit, and fixes it in the second commit.
Supersedes PRs #3767 and #4778

Don't check 'exclude_from_indexes' for empty lists.

---

storage/google/cloud/storage/blob.py
storage/tests/system.py
storage/tests/unit/test_blob.py

Closes #3809.
As noted on that issue, the `public_url` and `generate_signed_url` methods use the XML endpoints, which allow for / expect the slash not to be quoted.  All other methods use the JSON endpoints, which *require* quoting the embedded slashes.

Do not quote embedded slashes for public / signed URLs

---

test_utils/scripts/get_target_packages.py

This is in preparation for both a repository split and for api_core v1.0.0.

Don't run tests for every package when api_core is modified

---

api_core/google/api_core/page_iterator.py
api_core/tests/unit/test_page_iterator.py
bigquery/setup.py
bigquery/tests/unit/test_table.py
datastore/google/cloud/datastore/query.py
datastore/setup.py
datastore/tests/unit/test_query.py
spanner/google/cloud/spanner_v1/client.py
spanner/google/cloud/spanner_v1/instance.py
spanner/setup.py

Reverts GoogleCloudPlatform/google-cloud-python#4731
Do not merge until api_core 0.2.0 is being prepped for release.
Context: 
> This is done to prevent a release-the-world scenario in order to release bigquery, spanner, and datastore. It will be re-reverted before the next minor release of api_core.

Revert "Revert "api_core: Make PageIterator.item_to_value public. (#4702)""

---

storage/google/cloud/storage/acl.py
storage/google/cloud/storage/blob.py
storage/tests/system.py
storage/tests/unit/test_acl.py
storage/tests/unit/test_blob.py

Implement predefined acl

---

bigquery/setup.py
datastore/setup.py
logging/setup.py
spanner/setup.py
trace/setup.py

Note: has #4945 as a diffbase. Needs to be rebased before merging.

Update minimum api-core version to 1.0.0 for Datastore, BigQuery, Logging, Trace, and Spanner

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/job.py
docs/bigquery/snippets.py

Bigquery: Job string constant parameters in init and snippets documentation

---

api_core/google/api_core/datetime_helpers.py
api_core/tests/unit/test_datetime_helpers.py

Move TimestampNanoSeconds to api_core

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/magics.py
bigquery/nox.py
bigquery/tests/system.py
bigquery/tests/unit/test_magics.py
docs/bigquery/reference.rst
docs/requirements.txt

The intent of this PR is to create an IPython magic that can be used in any IPython notebook (whether hosted or local), and open the potential for future magics and integrations with notebooks.

BigQuery: Integration with IPython including cell magic for running queries

---

firestore/google/cloud/firestore_v1beta1/client.py
firestore/google/cloud/firestore_v1beta1/document.py
firestore/tests/system.py
firestore/tests/unit/test_client.py
firestore/tests/unit/test_document.py

Firestore: return non existent snapshot if document not found instead of raising NotFound exception

---

pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py

Nack messages when the subscriber callback errors

---

pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py

Retry subscription stream on InternalServerError, Unknown, and GatewayTimeout

---

pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
pubsub/google/cloud/pubsub_v1/types.py
pubsub/tests/unit/pubsub_v1/subscriber/test_policy_base.py

Drop leased messages after flow_control.max_lease_duration has passed.

---

bigtable/google/cloud/bigtable/row_data.py
bigtable/tests/unit/test_row_data.py

Add methods to provide better access to cell values, with performance and ease of use being additional goals.

BigTable: provide better access to cell values 

---

storage/google/cloud/storage/batch.py

This is in line with documentation at https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch.

Change GCS batch endpoint from /batch to /batch/storage/v1

---

bigtable/google/cloud/bigtable/row_filters.py
bigtable/tests/system.py
bigtable/tests/unit/test_row_filters.py

Closes #4932. 
But.  @tswast Should we have this and change it if/when BigTable supports microseconds or should we have the users handle it themselves and just document?

Bigtable: TimestampRanges must be milliseconds granularity

---

storage/google/cloud/storage/bucket.py

Link out to requester pays docs instead of stating there are no existing docs.

Link out to requester pays docs.

---

bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_job.py

Use more standard autospec mock for Connection mock class in job and client tests.

BigQuery: Use autospec for Connection in tests.

---

firestore/google/cloud/firestore_v1beta1/_helpers.py
firestore/tests/unit/test__helpers.py

~~Please wait until #4392 and #4464 is merged first.~~ 
Merged

Distinguish FieldPath classes from field path strings

---

storage/google/cloud/storage/client.py

Raised by @tswast, users[1] are confused by this method when trying to define storage class and location. There's no clear way to define these properties using this method and adding a link to `Bucket.create` method call.
I added a short `see also` to documentation. I have the following two questions:
1. Is this an expected way to define links out to other methods (trying to understand Python documentation). 
2. How is documentation for this client library updated at https://googlecloudplatform.github.io/google-cloud-python/latest/storage/client.html#google.cloud.storage.client.Client.create_bucket? Is it automatic when merged?
References:
[1]: https://stackoverflow.com/questions/44019273/python-to-create-google-storage-buckets/44035030#44035030

Add see also for Bucket.create method call for Client.create_bucket() documentation.

---

storage/google/cloud/storage/client.py

Update doc reference in GCS to correctly reference associated method and attribute.

Update doc reference links in GCS client documentation

---

storage/google/cloud/storage/blob.py
storage/tests/unit/test_blob.py

added start and end support for download_as_ methods. ChunckedDownload class works in a different way than Download (it does not accept start to be None, that why the start check is being done.

added range downloads

---

test_utils/scripts/get_target_packages.py

Mostly reverts #5018 just to get the tests to trigger.
Perhaps there's a better way to do #5018.

fix_circle_ci

---

api_core/setup.py
vision/setup.py

According to this [comment ]( https://github.com/pypa/pipenv/issues/1547#issuecomment-370778759) the current extras_require format to specify platform dependencies is deprecated, so moving it upwards
Also look here at the [documentation](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies) and at [SO](https://stackoverflow.com/questions/21082091/install-requires-based-on-python-version)

futures now install_requires

---

spanner/google/cloud/spanner.py
spanner/google/cloud/spanner_v1/__init__.py
spanner/tests/_fixtures.py
spanner/tests/system/test_system.py

/cc @vkedia
Export `COMMIT_TIMESTAMP` constant.
Magic string value for timestamp columns to be populated on the backend with the commit timestamp of the corresponding insert / update operation.
Add a system test which shows using it with a table whose `commit_ts` column supports it.

Add spanner commit timestamp support.

---

bigquery/setup.py

This will allow downstream packages (like pandas-gbq) to check for this
version when using the package at HEAD in CI tests.
Specifically, I'm thinking about https://github.com/pydata/pandas-gbq/pull/152 which updates pandas-gbq to account for my breaking change in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5036

BigQuery: Add dev version for 0.32.0 release

---

docs/bigquery/snippets.py

The `list_jobs` snippet was taking a very long time in the CI tests.
This should keep it from timing out.
Closes https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5095

BigQuery: Limit number of jobs in list_jobs snippet.

---

bigquery/google/cloud/bigquery/schema.py
bigquery/tests/unit/test_schema.py

Hi,
I fixed a problem that the description was not reflected in the `SchemaField` via `from_api_repr` method.

BigQuery: Make SchemaField be able to include description via from_api_repr method

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py

Make the pausable response iterator aware of the RPC state to prevent deadlock

---

bigquery/tests/system.py

See [CI failure](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6104) on Py3k.

Use bytes literals to initialize 'BytesIO'.

---

docs/bigquery/snippets.py
docs/bigquery/usage.rst

I was wondering if it was possible to run a dry run query. (It is.)
The reason I wondered is that a dry run query does not preserve its job ID. No job is actually created, so calling `query_job.result()` will fail.

BigQuery: Add snippet to run a dry run query.

---

pubsub/google/cloud/pubsub_v1/publisher/batch/thread.py
pubsub/tests/unit/pubsub_v1/publisher/batch/test_thread.py

Surface publish RPC errors back to the publish futures

---

bigquery/tests/unit/test_job.py

The way the `_Table` class is used in test_job.py is redundant with the
TABLE_REF property.

BigQuery: Remove unnecessary _Table class from test_job.py

---

firestore/tests/unit/test__helpers.py

See [related CircleCI failure](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6145).

Fix over-long line.

---

bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_table.py

The Table class had several special methods to convert properties to/from API representation. This PR updates the properties so they are all stored in `_properties` in API format. This moves all property conversion logic to the getters and setters, which will be easier to understand and maintain for contributors.

BigQuery: Moves all Table property conversion logic into properties

---

bigquery/CHANGELOG.md
bigquery/setup.py

Release bigquery 0.32.0

---

runtimeconfig/google/cloud/runtimeconfig/variable.py
runtimeconfig/tests/unit/test_config.py

@tswast Thanks for the hint.
Closes #4807

Fix variable nanosecond timestamp update_time from response

---

firestore/google/cloud/firestore.py
firestore/google/cloud/firestore_v1beta1/__init__.py
firestore/google/cloud/firestore_v1beta1/_helpers.py
firestore/google/cloud/firestore_v1beta1/batch.py
firestore/google/cloud/firestore_v1beta1/client.py
firestore/google/cloud/firestore_v1beta1/document.py
firestore/tests/system.py
firestore/tests/unit/test__helpers.py
firestore/tests/unit/test_batch.py
firestore/tests/unit/test_client.py
firestore/tests/unit/test_cross_language.py
firestore/tests/unit/test_document.py

Should close #4111
The first and second commits is #4654.

Implement `MergeOption` as an option

---

docs/error-reporting/usage.rst

Fix snippets showing use of 'error_reporting.HTTPContext'.

---

bigquery/google/cloud/bigquery/client.py
bigquery/tests/unit/test_client.py

Remove the `Client.list_dataset_tables()` method (replaced by
`Client.list_tables()`), the `Client.create_rows()` method (replaced by
`Client.insert_rows()`), and the `Client.create_rows_json()` method
(replaced by `Client.insert_rows_json()`).
Towards 1.0.0 release #5153

BigQuery: Remove deprecated Client methods

---

docs/bigquery/snippets.py
docs/bigquery/usage.rst

There were many redundant samples between google-cloud-python and python-docs-samples. This repo is the primary source of code samples and only had a few missing that were still being sourced from python-docs-samples. This PR adds those few remaining samples so that all samples except quickstart, simple app, and user credentials can be deleted from python-docs-samples.

BigQuery: Adds samples from python-docs-samples

---

pubsub/google/cloud/pubsub_v1/subscriber/_protocol/bidi.py
pubsub/tests/unit/pubsub_v1/subscriber/test_bidi.py

This is the foundation of the Pub/Sub subscriber refactor. It exposes a socket-like interface for gRPC streams and builds a robust, resumable stream on top of that. Finally, it adds a class for consuming the stream in the background using callbacks.
This code will replace the code in the current `google.cloud.pubsub_v1.subscriber._consumer` module.

Add bi-directional stream consumption helpers.

---

bigquery/nox.py

CI aborts the run if the test goes longer than 10 minutes without emitting any output.
This change also eases running with verbose output for debugging long-running tests, e.g., `nox -e snippets -- --verbose`.
See #5003.

Don't suppress 'dots' output for snippets tests.

---

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py
pubsub/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py
pubsub/google/cloud/pubsub_v1/subscriber/_protocol/helper_threads.py
pubsub/google/cloud/pubsub_v1/subscriber/_protocol/requests.py
pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py
pubsub/google/cloud/pubsub_v1/subscriber/subscriber.py
pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
pubsub/tests/unit/pubsub_v1/subscriber/test_dispatcher.py
pubsub/tests/unit/pubsub_v1/subscriber/test_helper_threads.py

Dispatcher handles sending requests *back* from callbacks. This is the *second* helper (after `BackgroundStreamConsumer`) that will be used by the `Subscriber` class.
Still trying to be minimally invasive, but I did move the `helper_threads` module to its final place under `_protocol`. 
Don't give the subscriber class much scrutiny right now, I just need *some* interface for the autospec in tests.

Add subscriber dispatcher

---

storage/google/cloud/storage/blob.py
storage/tests/unit/test_blob.py

Change the logic to elect to use multipart or resumable media for upload requests.

Allow uploading files larger than 2GB by using Resumable Media Requests

---

docs/bigquery/snippets.py

Listing all jobs can take a very long time, especially on a project used
by CI which starts many jobs every test run.

BigQuery: limit list_jobs sample to 10 most recent jobs

---

bigquery/google/cloud/bigquery/job.py

Per https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load.encoding the encoding value should be ISO-8859-1 ("Latin alphabet no. 1"). It was ISO-8559-1 ("anthropometric measurements that can be used for the creation of size and shape profiles and their application in the field of clothing").
cc @mtai

BigQuery: Fix typo in Encoding.ISO_8859_1 enum value

---

bigquery/google/cloud/bigquery/client.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py

This allows a Client to list datasets or jobs in projects other than the
default project.
Closes #5216

BigQuery: Add optional project parameter to `list_datasets` and `list_jobs`

---

pubsub/google/cloud/pubsub_v1/subscriber/client.py
pubsub/google/cloud/pubsub_v1/types.py
pubsub/setup.py

Lower the flow control defaults, remove psutil dependency

---

logging/tests/system/test_system.py

Plug leaky sink in logging systests.

---

bigquery/google/cloud/bigquery/dataset.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_dataset.py
bigquery/tests/unit/test_table.py

To make it easier to construct Datasets and Tables when the
full-qualified ID is known ahead of time, this PR adds helper methods
called `from_string` to Dataset, DatasetReference, Table, and
TableReference. In each case, the expected format is a fully-qualified
ID (including the project ID) in standard SQL format.
```
dataset = client.create_dataset(
bigquery.Dataset(
client.dataset('mydataset', project='other-project')
)
)
```
becomes
```
dataset = client.create_dataset(
bigquery.Dataset.from_string('other-project.mydataset')
)
```
Also, while writing doctests/examples, I noticed `__repr__` was
inconsistent with the actual constructor on some of these classes. I
fixed that while I was here so those string representations don't cause
confusion.
/cc @maxim-lian

BigQuery: add from_string factory methods to Dataset and Table

---

test_utils/scripts/get_target_packages.py

`storage` and `bigquery` are both GA:  we should be able to rely on testing against released versions.
Closes #5253.

Drop systest dependency expansion for bigquery/storage.

---

storage/google/cloud/storage/blob.py

This showed up in a flake8 warning when I was looking at #5277 
Let me know if this is right vs. using `_raise_from_invalid_response()`.

Remove unused var (flake8 warning)

---

storage/google/cloud/storage/blob.py
storage/google/cloud/storage/bucket.py

I am not sure if 1 MB was an old default or the units, but I think it's a typo either way? The current default seems to be `None` (which shows up in the generated docs), and I believe the unit is bytes, correct?

Update docstring to reflect correct units

---

bigquery/google/cloud/bigquery/job.py

The docstrings for format constants were inconsistent, did not show the string values they represent, and could not be linked to in the documentation. This PR standardizes the docstrings for constants to provide more information and allow linking to individual constants (ex. linking to docs for SourceFormat.CSV). Here is the example of the effects when rendered:
Before:
After:

BigQuery: Standardize docstrings for constants

---

api_core/nox.py
bigquery/nox.py
bigquery_datatransfer/nox.py
bigtable/nox.py
container/nox.py
core/nox.py
dataproc/nox.py
datastore/nox.py
dlp/nox.py
dns/nox.py
error_reporting/nox.py
firestore/nox.py
language/nox.py
logging/nox.py
monitoring/nox.py
oslogin/nox.py
pubsub/google/cloud/pubsub_v1/subscriber/scheduler.py
pubsub/nox.py
resource_manager/nox.py
runtimeconfig/nox.py
speech/nox.py
storage/nox.py
texttospeech/nox.py
trace/nox.py
translate/nox.py
videointelligence/nox.py
vision/nox.py
websecurityscanner/nox.py

There are *very* few people using 3.4 and 3.7 is coming up. A few of the packages cannot use 3.7 yet
PubSub: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5292
Monitoring: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5293
BigQuery: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5294

Add Test runs for Python 3.7 and remove 3.4

---

storage/google/cloud/storage/blob.py
storage/google/cloud/storage/bucket.py
storage/tests/system.py
storage/tests/unit/test_blob.py
storage/tests/unit/test_bucket.py

Merge is blocked for public beta of the KMS support.  We will need to adjust the system tests at that time to switch from using keys in the `global` location to keys in the same location as the bucket.

Storage: add support for KMS keys

---

bigquery/google/cloud/bigquery/job.py
bigquery/tests/system.py
bigquery/tests/unit/test_job.py

Part 2 of 2.  Expose the query timeline as a list of TimelineEntry objects.  Each sample provides progress information for a query query in terms of input units, as well as cumulative attribution of slot-millisecond resources.
Additionally, expose slot-milliseconds usage as a top-level field from the query statistics.

Add timeline and top-level slot-millis to query statistics.

---

bigquery/tests/system.py

Before, running the system tests verbosely with timing, top three slowest tests running on my local workstation:
90.16s call     bigquery/tests/system.py::TestBigQuery::test_query_many_columns
60.80s call     bigquery/tests/system.py::TestBigQuery::test_load_table_from_file_w_explicit_location
34.53s call     bigquery/tests/system.py::TestBigQuery::test_list_rows_many_columns
With these changes:
30.34s call     bigquery/tests/system.py::TestBigQuery::test_query_many_columns
21.44s call     bigquery/tests/system.py::TestBigQuery::test_load_table_from_file_w_explicit_location
(removed)      bigquery/tests/system.py::TestBigQuery::test_list_rows_many_columns
Changes to test_query_many_columns:
Previously, the wide column tests generated row data for a large (10k) column table locally, sent …

BigQuery:  improve system test performance

---

storage/google/cloud/storage/blob.py
storage/google/cloud/storage/bucket.py
storage/tests/unit/test_blob.py
storage/tests/unit/test_bucket.py
storage/tests/unit/test_notification.py

As the Storage UI on the console allows for easy toggling of public-private settings on objects and buckets, I figured it would be nice to add the support in the python package as well. 
This adds a new method to both storage's bucket and blob called `make_private` that undoes the actions of the `make_public` command.

Added make_private to Storage bucket and blob

---

bigquery/google/cloud/bigquery/client.py

Was missing a comma between types in get_job and cancel_job functions.

BigQuery: fix typo in Client docstrings

---

error_reporting/setup.py

This PR makes the dependency on `google-cloud-python` less restrictive in `google-cloud-error-reporting`. Currently, it is not possible to install `google-cloud-error-reporting` alongside other up-to-date `google-cloud-python` packages.
Of course, there may be great reasons why it was so restrictive in the first place, in which case I'd love for the author to explain the cause.
If this change is fine, it would be great if this was merged swiftly and published to PyPI with an updated version number.

make dependency on logging less restrictive in error_reporting

---

pubsub/google/cloud/pubsub_v1/publisher/batch/base.py
pubsub/google/cloud/pubsub_v1/publisher/batch/thread.py
pubsub/google/cloud/pubsub_v1/publisher/client.py
pubsub/tests/unit/pubsub_v1/publisher/batch/test_base.py
pubsub/tests/unit/pubsub_v1/publisher/batch/test_thread.py
pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py

Implements [plan](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4608#issuecomment-389963542) outlined in #4608.
Closes #4608

Normalize overflow handling for max count and bytes

---

bigquery/google/cloud/bigquery/table.py
docs/_templates/autosummary/class.rst
docs/_templates/autosummary/module.rst
docs/bigquery/.gitignore
docs/bigquery/reference.rst
docs/conf.py
test_utils/scripts/update_docs.sh
third_party/sphinx/LICENSE
third_party/sphinx/README.md
third_party/sphinx/sphinx/ext/autosummary/templates/autosummary/class.rst
third_party/sphinx/sphinx/ext/autosummary/templates/autosummary/module.rst

@alixhami and I have heard from several folks that the [BigQuery API Reference docs](https://google-cloud-python.readthedocs.io/en/latest/bigquery/reference.html) are pretty impossible to navigate. This PR uses the [autosummary](http://www.sphinx-doc.org/en/master/ext/autosummary.html) module to split the docs into separate pages with an easier to browse summary table.

BigQuery: use autosummary to split up API reference docs

---

docs/bigquery/snippets.py

This PR adds a load sample for column based time partitioning, and updates the create table and query samples. The create table and query samples were leveraged from the alpha documentation, but they were not as simple as possible, which is preferred for samples. To resolve this, I used data with a simpler schema and ran a full query instead of a dry run.
These samples are meant to be similar to the other load samples, which use US state data. I uploaded a csv file to the shared bucket so that other language samples can use the same data. I also used print statements rather than asserts so that the other languages can more closely follow these samples. I noticed that when the Python sample is canonical and uses asserts, the other language samples tend to print inconsistent messages …

BigQuery: adds load partitioned table sample and reworks create/query samples

---

pubsub/google/cloud/pubsub_v1/subscriber/_protocol/bidi.py
pubsub/tests/unit/pubsub_v1/subscriber/test_bidi.py

Make re-open failures bubble to callbacks

---

resource_manager/google/cloud/resource_manager/client.py
resource_manager/tests/unit/test_client.py

The filter_params parameter of resource_manager.Client.list_projects is
a dict (of properties to filter on and the desired value for each property).
Prior to this commit, this dict was passed into the HTTPIterator constructor
in extra_params['filter'].
This didn't work, because extra_params values can't be dicts. They *can* be
iterables, but since the iterable of a dict is its keys, this resulted in only
the properties being sent along in the 'filter' query param, while the desired
values for those properties were discarded.
This commit transforms the filter_params dict into a simple list prior to
shoving it in extra_params, which fixes the bug.

ResourceManager: fix list_projects(filter_params)

---

bigquery/google/cloud/bigquery/job.py
bigquery/tests/system.py
bigquery/tests/unit/test_job.py

python library already supported statement type, so its possible to determine if a query was a DDL statement based on the classification (e.g. CREATE_TABLE.
This adds ddl target table and operation performed.  The first identifies the resolved table being manipulated via a DDL statement, and the operation performed provides insight into whether that table was created, replaced, etc.

BigQuery: add ddl-related query stats.

---

translate/google/cloud/translate_v2/client.py

Fix error in documentation. In case of single value the function "detect_language" returns a dictionary (not a string).

fix docstring: str -> dict

---

bigtable/google/cloud/bigtable/table.py
bigtable/tests/unit/test_table.py

Add ability to specify the app_profile_id to use for the following Table methods:
read_rows
mutate_rows
sample_row_keys

BigTable: Add data app profile id 

---

datastore/tests/system/test_system.py
datastore/tests/system/utils/clear_datastore.py
datastore/tests/system/utils/populate_datastore.py

This time, use integer timestamps for the entity keys.
The new system test passes.
Closes #4264.

 Attempt again to reproduce #4264. 

---

pubsub/google/cloud/pubsub_v1/subscriber/_protocol/bidi.py
pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py

Fix retrying of bidirectional RPCs and closing the streaming pull manager

---

spanner/google/cloud/spanner_v1/database.py

Currently `process_read_batch` mutates the batch dict passed to it, which might be unexpected behavior for the caller. This change copies the dictionary before mutating.

Spanner: prevent process_read_batch from mutating params

---

bigquery/google/cloud/bigquery/client.py
bigquery/tests/unit/test_client.py

datetime.datetime will be easier to work with for filtering things like
"all the jobs run last month" or "all the jobs in the past 5 minutes".
Follow-up to https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5429#discussion_r192791719
Addresses https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5067 further.
Note, I sent this PR ASAP because I got a [request for a BigQuery package release](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5432) this (so numerics support can get out there) and I'd like to avoid any breaking changes.

BigQuery: Use datetime for jobs listing filter args.

---

bigquery/google/cloud/bigquery/client.py

I merged https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5431 too quick.

BigQuery: fix datetitme typo in list_jobs docstring

---

bigquery/CHANGELOG.md
bigquery/setup.py

Closes https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5432

Release BigQuery 1.3.0

---

bigtable/tests/system.py

Unmark most of the xfailed tests.

---

docs/bigquery/usage.rst
docs/bigtable/usage.rst
docs/datastore/usage.rst
docs/dns/usage.rst
docs/error-reporting/usage.rst
docs/firestore/index.rst
docs/index.rst
docs/language/usage.rst
docs/logging/usage.rst
docs/pubsub/index.rst
docs/releases.rst
docs/resource-manager/api.rst
docs/runtimeconfig/usage.rst
docs/spanner/usage.rst
docs/speech/index.rst
docs/storage/client.rst
docs/translate/usage.rst
docs/videointelligence/index.rst
docs/vision/index.rst

* Add installation instructions to subpackage pages that were missing them.
* Add deprecation notice to google-cloud releases page.
Closes https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5455

Use subpackage installation instructions on main index.

---

spanner/google/cloud/spanner_v1/snapshot.py
spanner/tests/unit/test_snapshot.py

Ensure that initial resume token is bytes, not text.

---

docs/bigquery/reference.rst

I think I accidentally dropped these classes in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5340.

Add DatasetListItem and TableListItem back to docs.

---

spanner/google/cloud/spanner_v1/_helpers.py
spanner/tests/system/test_system.py
spanner/tests/unit/test__helpers.py

Add support for Spanner struct params.

---

bigtable/tests/system.py

See: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6862

Harden 'test_list_instances' against simultaneous test runs.

---

.circleci/config.yml
test_utils/scripts/get_target_packages.py

This version emits debugging output from `get_target_packages.py`, in "comment" form.
It also updates the grep commands used to detect individual API packages to use whole-line matching only (`grep -x`).
See #5018, #5083

Redo 5018: run only needed systests

---

texttospeech/README.rst
texttospeech/docs/api.rst
texttospeech/docs/index.rst

Add top-level 'api' page (to pick up the derived client, enums, and types).
Closes #5193.

Fix docs links for TTS.

---

test_utils/scripts/get_target_packages.py

Drop running 'error_reporting' tests for changes in 'logging'.

---

storage/google/cloud/storage/blob.py
storage/tests/unit/test_blob.py

/cc @dhermes 
When raised by `google.resumable_media` for responses without an error payload, the message and args are the only clue to the cause.
Closes #4222.

Preserve the message / args from an InvalidResponse.

---

api_core/google/api_core/gapic_v1/routing_header.py

Rename x-goog-header-params -> x-goog-request-params

---

datastore/google/cloud/datastore/query.py
datastore/tests/system/test_system.py
datastore/tests/unit/test_query.py

This fixes the issue at GoogleCloudPlatform/google-cloud-python#4675 where fetch executions that pass the offset parameter would return incorrect result values
Closes #4675.

The offset param to the fetch method of a query did not work properly one there was a cursor

---

bigtable/google/cloud/bigtable_v2/gapic/bigtable_client.py
bigtable/tests/system.py

Remove 'xfail' for the large cell test which needs the override.
Closes #5362.

Override gRPC max message lengths.

---

logging/google/cloud/logging/handlers/middleware/request.py
logging/nox.py

This commit allows the Django Request Middleware to be compatible with
all versions of Django.
This references the official upgrade Docs @
https://docs.djangoproject.com/en/2.0/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware
#5024

#5024 Django Versioning Compatability for RequestMiddleware

---

docs/logging/usage.rst

Closes #4118.
Note that those API docs won't be as useful as they could be without either making `_BaseEntry` public (see #5511) or going to extra effort to propagate the signature docs for `__init__`.

Link concrete entry classes into usage docs

---

storage/tests/system.py

Harden 'create_bucket' systest against 429 responses.

---

bigtable/google/cloud/bigtable/client.py
bigtable/google/cloud/bigtable/instance.py
bigtable/tests/system.py
bigtable/tests/unit/test_client.py
bigtable/tests/unit/test_instance.py

A Cloud Bigtable instance is a collection of clusters.  Each cluster has a node count and a location.  The python Cloud Bigtable client needs a bit of refactoring to better represent the distinction between instances and clusters.
Long term, Instance.create() should take in a complete set of variables required for creating an [instance](https://github.com/googleapis/googleapis/blob/c89b6330b6386298f8ea65e47e0b77b28294e3e7/google/bigtable/admin/v2/instance.proto#L34) and a collection of [cluster](https://github.com/googleapis/googleapis/blob/c89b6330b6386298f8ea65e47e0b77b28294e3e7/google/bigtable/admin/v2/instance.proto#L104)s.
This is PR is related to issue #5454

Bigtable: Instance creation cleanup.

---

bigquery/google/cloud/bigquery/__init__.py
bigquery/google/cloud/bigquery/_helpers.py
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/retry.py
bigquery/tests/unit/test__helpers.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_retry.py
docs/bigquery/reference.rst

Publish it, w/ its docstring, in the reference docs.
Per @tswast in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5550#discussion_r198953348

Move 'DEFAULT_RETRY' (w/ its predicate) to a new public 'retry' module.

---

docs/bigquery/snippets.py

This aligns the load job BigQuery samples with the Cloud DPE sample
rubric guidelines and makes it easier to align samples across languages.

Print job progress in load job examples.

---

logging/google/cloud/logging/handlers/transports/background_thread.py

The function print sends the output to stdout disturbing the output of
the application.
Use logging instead which sends the logs to stderr by default or to the
destination configured by the application.
Closes #5565

Logging: s/print/logging.info/

---

bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/job.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_job.py

Removes check for missing schema on Client.list_rows. This allows the
rows of an empty table to be listed. Such a table might be the
"destination table" for a DML or DDL query.
Closes https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5583

Allow listing rows on an empty table.

---

bigtable/google/cloud/bigtable/row.py
bigtable/google/cloud/bigtable/table.py
bigtable/tests/unit/test_row.py

Allowing `DirectRow`s to be created without a call to `table.row()` or without a table passed in the constructor. `DirectRow`s that are passed to `Table.mutate_rows()` don't need their own reference to a table.  More importantly, Dataflow needs the separation of concerns between the data that needs to be operated on, adn the Service which will perform operations.
This PR also changes the dynamics of how `DirectRow.commit()` is performed.  `DirectRow.commit()` now defers implementation details to `Table.mutate_rows()`.  Until now, there was validation duplication, as well as some duplication around complexities of retrying.  Validation and retries now only happen in `Table.mutate_rows()` simplifying the codebase.
This is a replacement for PR #5417.  The intent of the PRs are the same, but …

Bigtable: DirectRow without a table

---

bigquery/google/cloud/bigquery/retry.py
bigquery/tests/unit/test_retry.py

Add 'internalError' to retryable error reasons.

---

bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_table.py
docs/bigquery/snippets.py

CREATE VIEW DDL queries set a "destination table" field, but that table
is actually a view. If you attempt to list rows on the view table, it
results in an error.
The fix is to avoid listing rows altogether if `getQueryResults()` says
that a query has completed but the number of rows in the result set is
undefined.

Don't raise exception when fetching CREATE VIEW query results

---

firestore/google/cloud/firestore_v1beta1/document.py
firestore/tests/system.py
firestore/tests/unit/test_document.py

Returns 'CollectionRefs' for nested collections of a document.
Closes #5480.

Add 'Document.collections' method.

---

docs/bigquery/snippets.py

We don't use this helper anymore because we use shared files that are always up on storage.

Removes unused helper function

---

docs/bigquery/snippets.py

`to_delete()` had already been updated to delete the Dataset as well as its contents. Therefore, deleting individual tables is unnecessary. This PR removes individual table deletion in order to simplify code and leave a good example for future tests.

Refactors snippets to only delete datasets + contents rather than tables

---

bigtable/google/cloud/bigtable/client.py
bigtable/google/cloud/bigtable/enums.py
bigtable/google/cloud/bigtable/instance.py
bigtable/tests/system.py
bigtable/tests/unit/test_client.py
bigtable/tests/unit/test_instance.py

Added optional type and labels to instance
Toward #5454.

Bigtable:  Add 'instance_type', 'labels' to 'Instance' ctor

---

bigtable/tests/system.py

Shorten instance / cluster name to fix CI breakage.

---

storage/tests/system.py

Add system test: signed URLs w/ non-ASCII blob name.

---

pubsub/google/cloud/pubsub_v1/subscriber/message.py
pubsub/tests/unit/pubsub_v1/subscriber/test_message.py

Pubsub: Make 'Message.publish_time' return datetime

---

bigquery/google/cloud/bigquery/job.py
bigquery/tests/unit/test_job.py

Shares the unit test backfill stuff (515a0f5) with PR #5654.
Closes #5646.

BigQuery: Add 'QueryJob.estimated_bytes_processed' property

---

bigquery/google/cloud/bigquery/dataset.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_dataset.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_table.py

The huge majority of this PR is backfilling explicit unit test support for `_AsyncJob` and `_JobConfig`.  I uncovered some doc nits because of that work, as well.
Closes #5645.

BigQuery:  add support for job labels

---

firestore/google/cloud/firestore_v1beta1/document.py

Currently the return type is specified as `Sequence[~.firestore_v1beta1.collection.CollectionReference[`. Changing to `Sequence[~.firestore_v1beta1.collection.CollectionReference]`. (Note the difference in the last symbol.)

Firestore API: Fix return type name (unbalanced brackets) in pydoc.

---

bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_table.py

Documented as `[Output-only]` in the API reference.
Closes #5686.

Make 'Table.location' read-only.

---

bigquery/google/cloud/bigquery/client.py
bigquery/tests/unit/test_client.py

Plumb it through as the default-default for all `Client` methods taking an optional `location`.
Closes #5148.

BigQuery add default location to client

---

pubsub/google/cloud/pubsub_v1/subscriber/message.py
pubsub/tests/unit/pubsub_v1/subscriber/test_message.py

Also, add explicit test for 'Message.size' property.
Closes #5691.

Add 'Message.ack_id' property.

---

datastore/CHANGELOG.md
datastore/setup.py

Release datastore 1.7.0

---

bigtable/tests/system.py

An overlapping CI run might delete one or more instances which were present
at the beginning of a given run.
Closes #5695.

Bigtable: further harden 'test_list_instances' systest

---

.gitignore
api_core/google/api_core/grpc_helpers.py
api_core/nox.py
api_core/tests/unit/test_grpc_helpers.py
spanner/MANIFEST.in
spanner/google/cloud/spanner_v1/gapic/spanner.grpc.config
spanner/google/cloud/spanner_v1/gapic/spanner_client.py
spanner/nox.py
spanner/tests/unit/gapic/v1/test_spanner_client_v1.py

Add optional grpc_gcp dependency for api_core and spanner_v1. If user has installed grpcio-gcp, then the connection management feature will be enabled, and with the configuration specified in spanner.grpc.config . Otherwise, grpc_gcp won't be imported and everything works as usual.

Connection management support (with optional grpc_gcp dependency)

---

docs/bigquery/snippets.py

BigQuery: Harden 'test_list_datasets_by_label' against overlapping CI runs.

---

spanner/tests/system/test_system.py

Pending advice from the back-end team.
Closes #5629.

Skip the flaky 'test_update_database_ddl' systest.

---

logging/tests/system/test_system.py

Closes #5543.
Closes #5632.
Closes #5692.
Closes #5556.

Logging: unflake systests

---

storage/tests/system.py

Storage: Harden systest 'tearDownModule' against 429 TooManyRequests.

---

bigquery/google/cloud/bigquery/_helpers.py
bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/system.py
bigquery/tests/unit/test__helpers.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_table.py

Add 'clustering_fields' support for load / query jobs. 
Include a system test creating a table w/ time partitioning and
clustering, including fetching the created table resource.
Previously reviewed in the private repository.  The feature is
scheduled to be in public beta 2018-07-19:  do not merge / release
until public beta is confirmed.

 Add 'Table.clustering_fields' property.

---

bigtable/tests/system.py

Fixes issue #5716 
Shorten cluster ID addition to just `'c1'` and `'c2'` in both 
`test_create_instance_w_two_clusters` and `test_create_cluster system` tests

Bigtable: shortening cluster ID in system tests

---

docs/spanner/usage.rst

References are to `google.cloud.storage.client.Client` instead of `google.cloud.spanner.client.Client`, which I believe is a typo.
In addition, the client self-links don't seem to work via https://googlecloudplatform.github.io, and seems like there are some differences in the side menu between
http://gcloud-python.readthedocs.io/en/latest/spanner/client-usage.html
and 
https://googlecloudplatform.github.io/google-cloud-python/latest/spanner/usage.html
?
Also, I don't see how to get to the main generated docs of the parameters for each method.

Fix typo in Client links

---

bigquery/tests/system.py

Reverts #5590.
Closes #5588.
Closes #5589.

BigQuery: Reenable systests for 'dataset.update'/'table.update'.

---

bigtable/google/cloud/bigtable/cluster.py
bigtable/google/cloud/bigtable/instance.py
bigtable/tests/system.py

Converting `instance.labels` public API to dictionary from protobuf `ScalarMapContainer`
Reroute to use `_update_from_pb` to set properties of instance and cluster in `list_instances` and `list_clusters`  methods.

BIgtable: public API 'instance.labels' type to dictionary

---

storage/tests/system.py

Retry 'notification.create()' on '503 ServiceUnavailable'.

---

spanner/tests/system/test_system.py

Retry 'test_transaction_read_and_insert_then_rollback' when aborted.

---

bigquery/google/cloud/bigquery/_helpers.py
bigquery/tests/unit/test__helpers.py

See #5750.
The issue remains in 'google.cloud._helpers._time_from_iso8601_time_naive',
but I don't want to have BigQuery wait on a release of core.

Fix '_time_from_json' for values with micros.

---

core/google/cloud/_helpers.py
core/tests/unit/test__helpers.py

Fix '_time_from_iso8601_time_naive' for values with micros.

---

spanner/google/cloud/spanner_v1/database.py
spanner/google/cloud/spanner_v1/pool.py
spanner/google/cloud/spanner_v1/session.py
spanner/tests/system/test_system.py
spanner/tests/unit/test_database.py
spanner/tests/unit/test_pool.py
spanner/tests/unit/test_session.py

Labels are assigned to a pool at creation time, and then get propagated to the sessions created by the pool.

Spanner: add support for session / pool labels

---

pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py

Ensure SPM methods check that 'self._consumer' is not None before use.

---

bigtable/google/cloud/bigtable/enums.py
bigtable/google/cloud/bigtable/table.py
bigtable/tests/system.py
bigtable/tests/unit/test_table.py

1. Updated table.exists(), now using NAME_ONLY view in get_table() call.
2. Added system test around table.exists()

Bigtable optimize 'Table.exists' performance

---

docs/bigquery/snippets.py

Introduced in #5760.
CI failure on `master`: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/7615

BigQuery: fix snippets lint issue.

---

storage/google/cloud/storage/client.py
storage/tests/system.py
storage/tests/unit/test_client.py

Returns email address of service account of a given project, defaulting to the client's project.
Closes #5635.

Storage: Add 'Client.get_service_account_email'.

---

trace/google/cloud/trace/__init__.py
trace/google/cloud/trace/_gapic.py
trace/google/cloud/trace/v1/_gapic.py

`make_trace_api` currently ignores the credentials configured in the `Client`

Trace: Pass credentials into TraceServiceClient

---

storage/google/cloud/storage/blob.py
storage/google/cloud/storage/bucket.py

Also note how to enable anonymous access to 'Blob.public_url'.
Closes #5457.

Storage: elaborate docs for '{Bucket,Blob}.make_{public,private}'.

---

storage/google/cloud/storage/bucket.py
storage/google/cloud/storage/client.py
storage/tests/unit/test_bucket.py

Addresses #5194 by labeling setting location deprecated. Support setting location on create method of bucket.

Move location specification to Bucket.create and deprecate location setter

---

docs/storage/client.rst

/cc @BrandonY
Also note general best practice for multiprocessing use.
Closes #5685.

Storage: document thread-safety of client.

---

docs/spanner/usage.rst

Broken by move to 'spanner_v1' (the aliases in 'spanner' are not honored).
Closes #5723.

Spanner: fix Sphinx crossrefs to 'Client'.

---

pubsub/google/cloud/pubsub_v1/_gapic.py

Fix classmethod wrapping

---

storage/nox.py
storage/tests/system.py

Test should use service account of current user. KMS cannot be run without setup or CI account.
fixes #5830

Storage: Fix failing system tests

---

vision/google/cloud/vision_helpers/__init__.py
vision/google/cloud/vision_helpers/decorators.py

Use iteration over the 'Type' enum, rather than reaching around to its `__dict__`, which isn't populated the same way on Python 3.4.x.
Fixes #5814.

Vision: Clean up feature introspection.

---

bigtable/google/cloud/bigtable/row_data.py
bigtable/google/cloud/bigtable/table.py
bigtable/tests/system.py
bigtable/tests/unit/test_row_data.py
bigtable/tests/unit/test_table.py

- Fold `YieldRowsData` functionality into `PartialRowsData`
- Using the name `__iter__()` instead of `read_rows()` so that `PartialRowsData` is now an iterable.
- `Table.yield_rows()` just calls `Table.read_rows()`, making `Table.yield_rows` obsolete, but required for backwards compatiblity.

Bigtable: consolidating read_rows and yield_rows

---

bigquery/nox.py

Full support still blocked on pyarrow support for Python 3.7.
See #5294.

Test pandas support under Python 3.7.

---

monitoring/nox.py
monitoring/setup.py

Declare full support for Python 3.7.
Closes #5293.

Monitoring: test pandas under all supported Python versions

---

storage/tests/system.py

- Don't set keyring IAM policy for existing keyrings.
- Make path generation more legible.
Closes #5852.

Clean up KMS test setup.

---

docs/resource-manager/api.rst

No longer alpha / invite-only.
Closes #5772.

Resource_manager: Remove alpha warning for 'projects.create' API.

---

datastore/google/cloud/datastore/client.py
datastore/tests/unit/test_client.py

Allows setting to alternate endpoints, e.g. for non-prod or use via something
like 'batch-datastore.googleapis.com'.
Closes #5801.

Datastore: Expose 'Client.base_url' property.

---

bigquery/nox.py
bigtable/nox.py
container/nox.py
core/nox.py
datastore/nox.py
dns/nox.py
error_reporting/nox.py
firestore/nox.py
language/nox.py
logging/nox.py
pubsub/nox.py
redis/nox.py
resource_manager/nox.py
spanner/nox.py
storage/nox.py
trace/nox.py
translate/nox.py
websecurityscanner/google/cloud/websecurityscanner_v1alpha/types.py
websecurityscanner/nox.py

The overall intent here is to use in-place installs for all local packages, to ease debugging using the "mainline" versions of the packages.

Nox: use inplace installs

---

bigquery/google/cloud/bigquery/table.py

Avoid pulling entire result set into memory when constructing dataframe.

---

logging/google/cloud/logging/entries.py
logging/google/cloud/logging/logger.py
logging/tests/unit/test_entries.py
logging/tests/unit/test_logger.py

Add traceID parameter for logentries:
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5505

Add trace to logentry types

---

logging/google/cloud/logging/entries.py
logging/google/cloud/logging/logger.py
logging/tests/unit/test_entries.py
logging/tests/unit/test_logger.py

Add `span_id` to `LogEntry`
Note `trace` should get specified if `span_id` is set.  The logging API does not currently return an error and while the final displayed log line does have a `span_id`, its not too useful.  Instead of client-side validation, CloudLogging would return exception later (i'll file internal FR for that)
ref:
- https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5505

Add span_id to LogEntry

---

bigtable/google/cloud/bigtable/client.py
bigtable/google/cloud/bigtable/table.py
bigtable/tests/system.py
bigtable/tests/unit/test_client.py
bigtable/tests/unit/test_table.py

- Remove spurious check for the `admin` flag in `Client.table_data_client`: that flag is supposed to cover only access the the admin clients.
- Use the `table_data_client` to generate table_name path.
- Add a system test exercising non-admin access to table data.
Supersedes #5875.
Closes #5874.

Bigtable: fix non admin client access (minimal version)

---

bigtable/google/cloud/bigtable/instance.py
bigtable/google/cloud/bigtable/policy.py
bigtable/tests/unit/test_instance.py
bigtable/tests/unit/test_policy.py

Implemented iam policy for an instance.

Bigtable: iam policy implementation for an instance.

---

docs/storage/snippets.py
storage/google/cloud/storage/bucket.py
storage/tests/system.py
storage/tests/unit/test_bucket.py

@frankyn Note that the system test added in the last commit currently fails.  It is sending the POST body as
```python
{'lifecycle': {'rule': [{'action': {'type': 'Delete'},
'condition': {'age': 42}},
{'action': {'type': 'SetStorageClass'},
'condition': {'isLive': False,
'matchesStorageClass': 'NEARLINE'},
'storageClass': 'COLDLINE'}]},
'name': 'w-lifcycle-rules-1535755546278'}
```
and fails with a 400:
```python
{'error': {'code': 400,
'errors': [{'domain': 'global',
'message': 'Invalid argument',
'reason': 'invalid'}],
'message': 'Invalid argument'}}
```
I'd like help tracking down what is causing that error from the back-end's perspective.

Storage: add lifecycle rules helpers to bucket

---

spanner/tests/unit/gapic/v1/test_spanner_client_v1.py

That bit of configuration is a class attribute, and may be changed, e.g. to point at non-production endpoints.

Avoid hardcoding endpoint URL in grpc_gcp unit tests.

---

pubsub/google/cloud/pubsub_v1/types.py
pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py

It is documented as '10MB', but enforced as 10000000 bytes.
Closes #5898.

Change 'BatchSettings.max_bytes' default.

---

storage/google/cloud/storage/blob.py
storage/google/cloud/storage/bucket.py
storage/tests/unit/test_blob.py
storage/tests/unit/test_bucket.py

Add test assertion for warning from 'Bucket.location' setter.

Storage: Add 'stacklevel=2' to deprecation warnings.

---

index.html

`pip install --upgrade google-cloud` is no longer a thing.
Closes #5906.

Don't suggest installing umbrella package

---

logging/google/cloud/logging/handlers/transports/background_thread.py
logging/google/cloud/logging/handlers/transports/base.py
logging/google/cloud/logging/handlers/transports/sync.py
logging/tests/unit/handlers/transports/test_background_thread.py
logging/tests/unit/handlers/transports/test_sync.py

Follow up to #5885 and #5878. Add function parameters on the logging async API to allow API logging with trace and span_id in a non-blocking way.

Add trace and span_id to logging async API

---

api_core/setup.py
spanner/setup.py

Add grpcio-gcp as extra dependency in google-api-core
Add grpcio-gcp as hard dependency in google-cloud-spanner

Add grpcio-gcp dependency for cloud spanner

---

spanner/nox.py

We made it an unconditional dependency in #5904.
See #5925.

Drop separate testing for grpcio-gcp.

---

spanner/CHANGELOG.md
spanner/setup.py

Release spanner 1.5.0

---

bigquery/google/cloud/bigquery/retry.py
bigquery/tests/unit/test_retry.py

Retry '502 Bad Gateway' errors by default.

---

docs/bigquery/snippets.py

Removing samples that are being removed from the docs

BigQuery: Remove append sample for orc and parquet formats

---

pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py

Fix race condition where pending Ack IDs can be modified by another thread.

---

bigtable/google/cloud/bigtable/row_data.py
bigtable/google/cloud/bigtable/table.py
bigtable/tests/unit/test_row_data.py

This work is on behalf of understanding the issues behind issue #5876 where InvalidChunk is thrown due to row keys being processed out of order.
About this PR
- introducing `PartialRowsData._process_chunk` to break up logic in `__iter__`, and allow for additional testability.  `__iter__` is responsible to get chunks, call `_process_chunk`, and manage `last_scanned_row_key`.
- removed `_copy_from_current`
- _state is now explicitly set
- fixed a bug in `PartialRowsData.counter` which was counting chunks instead of rows.  This counter is used in reconstructing requests for "smart retries" that update the request on transient exceptions

Bigtable: refactoring read_rows infrastructure

---

redis/CHANGELOG.md
redis/setup.py

Release redis 0.2.0

---

datastore/docs/usage.html
docs/conf.py
language/docs/usage.html
logging/docs/usage.html
spanner/docs/usage.html
storage/docs/client.html
translate/docs/usage.html

Redirect spanner 'usage.html' -> 'index.html'.

---

bigtable/google/cloud/bigtable/row_data.py
bigtable/tests/unit/test_row_data.py

Attempt to fix #5876 
Added logic to create a `RowRange(start_key_open=last_scanned_key)` if `current_request.rows` is empty.
This will cover `table.read_rows()` and `table.read_rows(rows_limit)` requests.

Bigtable: smart retry logic to cover errors in 'read_rows()' and 'read_rows(rows_limit)' requests

---

docs/conf.py
language/docs/usage.html
logging/docs/usage.html
translate/docs/usage.html

Redirect file is not needed for 'translate'.
See #5996.

Translate: restore detailed usage docs.

---

docs/conf.py
test_utils/scripts/update_docs.sh

- Run docs build during nox w/ better debug output (the colorized mode tends to hide some info).
- Fix loop boundary bug in copying static HTML files.
- Log each static HTML file copied.

Docs: debug broken docs build

---

bigquery/google/cloud/bigquery/retry.py
bigquery/tests/unit/test_retry.py

BigQuery: add support for retrying unstructured 429 / 500 / 502 responses.

---

storage/google/cloud/storage/blob.py
storage/tests/system.py
storage/tests/unit/test_blob.py

Storage: no longer enforce 'destination.content_type' in 'Blob.compose'.

---

spanner/docs/transaction-usage.rst

/cc @snehashah16
Use `session.transaction()` instead.
Use ReST markup to set off notes about manual transaction usage.
Closes #6029.

Remove bogus examples of 'database.transaction()'.

---

bigtable/google/cloud/bigtable/row_set.py
bigtable/tests/unit/test_row_set.py

1. __eq__ and __ne__ methods for RowSet and RowRange.
2. Unit tests.

Bigtable:Adding __eq__ and __ne__ methods for row set

---

videointelligence/README.rst
videointelligence/docs/index.rst

Videointelligence: Harmonize / DRY 'README.rst' / 'docs/index.rst'.

---

bigquery/google/cloud/bigquery/job.py
bigquery/tests/system.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_job.py

Before this change, the location field was not populated after
inititial construction. This is a problem when no location is
provided but it has been auto-detected based on the resources
referenced in the job (such as via the tables referenced in a
query).

Populate the jobReference from the API response.

---

firestore/google/cloud/firestore_v1beta1/_helpers.py
firestore/tests/unit/test__helpers.py

Firestore: don't omit originally-empty map values when processing timestamps.

---

spanner/nox.py

#5904 made 'grpcio-gcp' an unconditional dependency.

Spanner: remove extra 'grpc_gcp' system tests.

---

resource_manager/google/cloud/resource_manager/_http.py

Reverts #6041.
We need to review more deeply. Per @enriquejosepadilla's testing, the changes in the API from `v1beta1` -> `v1` are breaking for us.

Resource Manager: 'v1' API is not forward compatible.

---

storage/google/cloud/storage/blob.py
storage/tests/system.py
storage/tests/unit/test_blob.py

Storage: ensure that 'method' for 'Blob.generate_signed_url' is uppercase.

---

.circleci/config.yml
.kokoro/continuous/translate.cfg
.kokoro/presubmit/translate.cfg
translate/README.rst

These Kokoro jobs have configs in google3 and GitHub and should build successfully:
* API Core
* Video Intelligence
* Vision
These Kokoro jobs do not have configs in GitHub yet and will fail:
* Speech
* Storage
* Trace
* Translate

Add kokoro for translate, remove translate from CircleCI

---

api_core/nox.py
api_core/setup.cfg

Type-checks all of api_core outside of tests with [pytype](https://github.com/google/pytype).
* Adds pytype options to setup.cfg so the code can be type-checked with `pytype -V{major.minor}`.
* Runs `pytype -V3.5` and `pytype -V3.6` under nox.
Manually tested by pip-installing `pytype` and `nox-automation` in a Python 3.6 virtualenv.
@theacodes cc-ing you on this PR as you requested

Add type-checking via pytype to api_core.

---

logging/google/cloud/logging/client.py
logging/google/cloud/logging/handlers/app_engine.py
logging/tests/unit/handlers/test_app_engine.py

The python37 runtime provides the GOOGLE_CLOUD_PROJECT environment variable instead of GCLOUD_PROJECT, and for log messages to be correlated with the request in StackDriver, their 'trace' value has to be passed as a top level member of the log record rather than as an appengine.googleapis.com/trace_id label.

Logging: support request-correlated logging in App Engine standard python37 runtime

---

pubsub/setup.py

Closes #6128.
~~Blocked on merge of #6133 / release of `google.api_core 1.4.1`.~~

Bump minimum 'api_core' version to '1.4.1'.

---

storage/google/cloud/storage/blob.py

The line 'If you are on Google Compute Engine, you can't generate a signed URL' wrongly implies URL generation is impossible from GCE. Adding clarification that this line only holds true when GCE is using GCE service account.

Clarify GCS URL signing limitations on GCE

---

storage/google/cloud/storage/blob.py
storage/google/cloud/storage/bucket.py
storage/tests/system.py
storage/tests/unit/test_blob.py
storage/tests/unit/test_bucket.py

(Already reviewed in the private repo).
Merge is blocked pending public beta of the feature on the back-end.
@frankyn Please approve the PR once the back-end is ready.

Add support for bucket retention policies

---

spanner/google/cloud/spanner_v1/database.py
spanner/google/cloud/spanner_v1/snapshot.py
spanner/google/cloud/spanner_v1/transaction.py
spanner/tests/system/test_system.py
spanner/tests/unit/test_database.py
spanner/tests/unit/test_snapshot.py
spanner/tests/unit/test_transaction.py

/cc @snehashah16
DML / PDML system tests will fail until the production endpoint support is rolled out.  Do not merge until then.

Spanner: add DML / PDML support

---

bigquery/google/cloud/bigquery/_helpers.py
bigquery/google/cloud/bigquery/schema.py
bigquery/tests/system.py
bigquery/tests/unit/test__helpers.py

Previously reviewed in private repo.

BigQuery: add support for GEOGRAPHY type

---

spanner/google/cloud/spanner_v1/database.py
spanner/google/cloud/spanner_v1/snapshot.py
spanner/google/cloud/spanner_v1/transaction.py
spanner/tests/system/test_system.py
spanner/tests/unit/test_database.py
spanner/tests/unit/test_snapshot.py
spanner/tests/unit/test_transaction.py

Blocked pending new rollout of back-end feature.

Spanner: add support for DML/PDML

---

bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/job.py
bigquery/tests/unit/test_client.py
bigquery/tests/unit/test_job.py

Leave `_build_resource` behind as a backward-compatibility alias.
Closes #5866.

BigQuery: expose 'to_api_repr' method for jobs.

---

logging/tests/system/test_system.py

Also, make logger names unique between test runs, in an attempt to avoid race condition in deletion of a logger from a previous test run, vs. current logger.
Closes #5303.

Logging:  allow more tries on inner retry for '_list_entries'.

---

logging/tests/system/test_system.py

Logging: harden 'test_list_entry_with_unregistered' against 429 errors.

---

logging/tests/unit/handlers/test_app_engine.py

Updated TestAppEngineHandler.test_constructor to test that the project environment variables from GAE flex and GAE standard are both correctly handled, as per @tseaver's request in #6118.

Logging: test both GCLOUD_PROJECT and GOOGLE_CLOUD_PROJECT env vars

---

logging/tests/system/test_system.py

Also, remove deprecated use of 'failIf'.
Closes #5931.

Logging: harden sink creation against transient errors.

---

logging/tests/system/test_system.py

Logging: harden systest teardown vs 'DeadlineExceeded' retry errors

---

bigquery/google/cloud/bigquery/dbapi/cursor.py

When getting a `Cannot query over table (...) without a filter over
column(s) (...)`, the re-raising happening gobbles up the error message
and the context is lost.
This may or may not be the right fix, but clearly highlights the issue
of `self._query_job.errors` being `None` in that particular context.
When that is the case, the only context available is that of
`DatabaseError` without any details which clearly isn't enough detail.
```
After this fix is applied (wrapping the exception into another exception) both stack traces are shown:
File "/home/mbeauchemin/incubator-superset/env/lib/python3.4/site-packages/google/cloud/bigquery/job.py", line 2685, in result
super(QueryJob, self).result(timeout=timeout)
File "/home/mbeauchemin/incubator-superset/env/lib/python3.4/site-packages/google/c …
```

BigQuery: fix swallowed error message

---

language/docs/usage.rst

entities no longer have `entity_type`, just `type`.

fix usage docs example for entity extraction

---

videointelligence/README.rst

The current `pip install` command incorrectly references `google-cloud-datastore`, this PR is correcting the `pip install` instructions to correctly reference `google-cloud-videointelligence`

Correction to the pip install command

---

bigquery/google/cloud/bigquery/client.py
bigquery/tests/unit/test_client.py

This makes it easier to create an empty dataset or table when all you
care about is the ID and not any of the extra metadata. When creating an
empty dataset, the default location is included.
Follow-up to #6164. Closes #6055

Allow strings or references in create_dataset and create_table

---

pubsub/README.rst

Update subscriber example in README to current patterns.

---

api_core/README.rst
asset/README.rst
automl/README.rst
core/README.rst
dlp/README.rst
dns/README.rst
iot/README.rst
kms/README.rst
oslogin/README.rst
redis/README.rst
speech/README.rst
tasks/README.rst
texttospeech/README.rst
websecurityscanner/README.rst

We could still do with another normalization pass (e.g., standardize on use of `|alpha|` / `|beta|` badges).
~~Note that the change to `asset/README.rst` will have broken badges until we land a release of `google-cloud-asset` (vs. `google-cloud-cloudasset`, see #6154).~~  `oslogin/README.rst` is likewise going to show broken badges, because it has never been released.

Docs: Add / fix badges for PyPI / versions.

---

api_core/tests/unit/test_bidi.py

Error left from PR #6211, when Kokoro was blithely skipping tests.
See: https://source.cloud.google.com/results/invocations/25ee204c-3118-4148-a530-0ad5e0fffc32/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-python%2Fpresubmit%2Fapi_core/log

api_core: fix import order, appeasing lint.

---

api_core/tests/unit/test_bidi.py

Use `mock.Mock()` w/ `return_value` True, rather than inlining `lambda _: True` in cases where the callback doesn't get called.

Fix branch coverage for un-called callbacks.

---

bigquery/google/cloud/bigquery/job.py
bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_job.py
bigquery/tests/unit/test_table.py

Closes #5093.
This PR includes a bunch of new explicit unit test cases / assertions for `LoadJobConfig`, and reorders the properties alphabetically, to make it easier to match up with the docs.
/cc @yiga2.

BigQuery: add destination table properties to 'LoadJobConfig'.

---

ndb/MIGRATION_NOTES.md
ndb/docs/blobstore.rst
ndb/docs/conf.py
ndb/docs/django-middleware.rst
ndb/docs/exceptions.rst
ndb/docs/index.rst
ndb/docs/metadata.rst
ndb/docs/msgprop.rst
ndb/docs/polymodel.rst
ndb/docs/query.rst
ndb/docs/stats.rst
ndb/src/google/cloud/ndb/__init__.py
ndb/src/google/cloud/ndb/exceptions.py
ndb/src/google/cloud/ndb/key.py
ndb/src/google/cloud/ndb/model.py
ndb/src/google/cloud/ndb/query.py
ndb/tests/unit/test_key.py
ndb/tests/unit/test_query.py

In the process also:
- Renaming `_exceptions` module to `exceptions` so that it could be documented
- Adding the package (`google.cloud.ndb`) documentation to `index.rst` and making sure only `__all__` and `__version__` get documented
- Adding `nitpicky = True` to `docs/conf.py` to make sure all references are valid
- Excluding `Rollback` from `model.rst` since it is a borrowed type from `exceptions`
- Populating `__all__` for `exceptions` module
- Removing references to non-existent `query.Parameter.set()` and to undocumented `model.ModelAttribute._fix_up` (these were found by nitpicky)

Adding documentation for all `ndb` modules.

---

dlp/CHANGELOG.md
dlp/setup.py

Release dlp 0.9.0

---

firestore/google/cloud/firestore_v1beta1/document.py
firestore/tests/unit/test_document.py

Firestore: block calling 'DocumentRef.get()' with a single string.

---

ndb/MIGRATION_NOTES.md
ndb/src/google/cloud/ndb/key.py
ndb/src/google/cloud/ndb/model.py

See the comment in `MIGRATION_NOTES.md` about the rampant use (and abuse) of `__new__()` rather than `__init__()` as a constructor.
Updated `MIGRATION_NOTES.md` to make a note about the difference in internal state between old and new versions of `ndb`. In particular, the new version has dropped usage of "private" (e.g. `self.__foo`) variables.
Removed `__slots__` from classes that didn't have them in the old implementation.
----
@theacodes and I discussed this and the conclusion was that "the old way" should be preserved as often as possible

Restoring some `__new__()` constructors for `ndb`.

---

logging/docs/entries.rst
logging/google/cloud/logging/_helpers.py
logging/google/cloud/logging/entries.py
logging/google/cloud/logging/logger.py
logging/tests/system/test_system.py
logging/tests/unit/test__helpers.py
logging/tests/unit/test_entries.py
logging/tests/unit/test_logger.py

/cc @salrashid123.
Note that this PR refactors the log entry implementation pretty heavily:  log entry classes are now based on named tuples, and should be a) smaller, b) faster, and c) better documented.
Closes #5601 (includes its commits).
Closes #6094.

Logging: add support for additional 'LogEntry' fields

---

ndb/src/google/cloud/ndb/model.py
ndb/tests/unit/test_model.py

This is used to wrap values returned from the datastore so that they can be differentiated by values set by the user.
Worth noting: It's unclear if this would be needed by the "best" implementation, but I think it's "best" to leave it in for now.

Implementing `model._BaseValue` for `ndb`.

---

ndb/MIGRATION_NOTES.md
ndb/src/google/cloud/ndb/exceptions.py
ndb/src/google/cloud/ndb/key.py
ndb/src/google/cloud/ndb/model.py
ndb/src/google/cloud/ndb/query.py
ndb/tests/unit/test_query.py

In particular
- `query.Node`
- `query.FalseNode`
- Most of `query.ParameterNode`. The remaining part (`ParameterNode.resolve()`) depends on as-yet-unimplemented features of `model.Property`.
- Most of `query.FilterNode`. With two "missing" parts.
- `FilterNode._to_filter` raises `NotImplementedError` instead of creating a filter object. This is because the old implementation relies on the `google.appengine.datastore.datastore_query` module for low-level filters. At some point we'll need to replace that with the new protobuf [Filter][1]
- If `value` is a `model.Key`, this just does what the original implementation did: call `Key.to_old_key`. This must be changed to actual convert it to a protobuf `Key` for the new proto API
- `query.PostFilterNode`. I slightly modified the `__eq__` …

Adding all `Node` implementations for the `ndb.query` module

---

ndb/MIGRATION_NOTES.md
ndb/src/google/cloud/ndb/blobstore.py
ndb/src/google/cloud/ndb/context.py
ndb/src/google/cloud/ndb/django_middleware.py
ndb/src/google/cloud/ndb/eventloop.py
ndb/src/google/cloud/ndb/metadata.py
ndb/src/google/cloud/ndb/model.py
ndb/src/google/cloud/ndb/msgprop.py
ndb/src/google/cloud/ndb/polymodel.py
ndb/src/google/cloud/ndb/query.py
ndb/src/google/cloud/ndb/stats.py
ndb/src/google/cloud/ndb/tasklets.py

This is a spin-off of the discussion in #6258 with @theacodes and @tseaver.
I have added `__slots__` to **all** classes except for `Property`. The reason I didn't with `Property` is because the implementation actual depends on `'foo' in self.__dict__` (AFAICT just for `repr()`) to determine if a given attribute is the default (provided by the class) or set explicitly on the instance.
To see why `__slots__` don't work when a class uses a fallback:
```python
>>> class A:
...     __slots__ = ("a", "b")
...     a = 10
...     b = 11
...     def __init__(self, *, a=None, b=None):
...         if a is not None:
...             self.a = a
...         if b is not None:
...             self.b = b
...
File "<stdin>", line 1, in <module>
ValueError: 'a' in __slots__ …
```

Adding `__slots__` throughout `ndb`.

---

bigquery_datatransfer/README.rst
dataproc/README.rst
iot/README.rst
monitoring/README.rst
vision/google/cloud/vision_helpers/__init__.py

In package `README.rst` files, where `CallOptions` was being shown as a way to trigger paged iteration, usse idiomatic `pages` attribute of iterators
For `VisionHelper.annotate_image`, update docstring to reflect the actual signature, which takes `retry` and `timeout` rather than `options`.
Closes #5560.
Other elements of that bug will be fixed in [`gapic-generator`](googleapis/gapic-generator#2388) and propagated via autosynth.

Docs: fix 'CallOptions' examples

---

bigtable/google/cloud/bigtable/row.py
bigtable/tests/unit/test_row.py

Fixes #6292 
- `predicate_filter` and `*_mutation` parameters are getting passed again to `check_and_mutate_row`
- Remove erroneous index from `resp`, since it already is a single `google.cloud.bigtable_v2.types.CheckAndMutateRowResponse`
Unsure how to make the tests more sensible to this kind of error.

Bigtable: Fix ConditionalRow interaction with check_and_mutate_row

---

bigtable/google/cloud/bigtable/table.py

Presumably, anyway, as the line of code in question hasn't changed for
almost a year.

Bigtable: fix error from new flake8 version.

---

tasks/docs/index.rst

Separate / distinguish API docs for different API versions.

---

ndb/MIGRATION_NOTES.md
ndb/src/google/cloud/ndb/exceptions.py
ndb/src/google/cloud/ndb/model.py
ndb/src/google/cloud/ndb/query.py
ndb/tests/unit/test_model.py
ndb/tests/unit/test_query.py

~~**NOTE**: This has #6250 as diffbase (since `Property.__eq__` relies on `query.Node` implementations)~~
- `Property.__repr__`
- `Property._comparison`, which provides the nifty ORM feature that makes `MyModel.foo == 10` spit out a filter
- `Property.__eq__` and friends (all just call `_comparison`)
- `Property.IN`
- `+Property` and `-Property` (this is just a stub, but they **should** create `Order` objects)
- `Property._datastore_type` (used to convert from Python types to protobuf types when needed)
- Completes the implementation of `query.ParameterNode.resolve()`

Implementing more of `ndb` Property

---

api_core/google/api_core/gapic_v1/routing_header.py
api_core/tests/unit/gapic/test_routing_header.py

Per internal document go/api-url-encoding (approved on 2017-04-20),
> the client library will %-encode everything except "/" and unreserved
> characters, and the server will %-decode everything except "%2F"
> and %2f
This is currently affecting a private API which passes a resource name
(containing slashes) as a query parameter over gRPC.

Don't URL-encode slashes in gRPC request headers.

---

firestore/tests/unit/test_cross_language.py

Note that this will conflict with #6291, but the master is red.

Firestore: fix error from new flake8 version.

---

ndb/src/google/cloud/ndb/model.py
ndb/tests/conftest.py
ndb/tests/unit/test_model.py

~~**NOTE**: Has #6295 as diffbase.~~
- Adds `Property._code_name` class and instance attribute
- `Property._fix_up`
- `Property._store_value`
- `Property._set_value`
- `Property._has_value`
- `Property._retrieve_value`
- Modifies `property_clean_cache` fixture to make sure the cache is empty on fixture entry and make sure the cache is non-empty before clearing

Continuation of `ndb` Property implementation (part 3)

---

logging/google/cloud/logging/handlers/transports/background_thread.py
logging/tests/unit/handlers/transports/test_background_thread.py

To enable JSON detection in StackDriver, `jsonPayload` should
have no fields other than `message`. This patch lets clients
opt-in to this behavior, by creating a custom Transport.
Fixes https://github.com/googleapis/google-cloud-python/issues/5799

Allow turning on JSON Detection in StackDriver

---

ndb/src/google/cloud/ndb/model.py
ndb/tests/unit/test_model.py

- `Property._apply_to_values`
- `Property._opt_call_to_base_type`
- `Property._call_from_base_type`
- `Property._opt_call_from_base_type`
- `Property._value_to_repr`
- `Property._get_user_value`
- `Property._get_base_value`
- `Property._get_base_value_unwrapped_as_list`

Continuation of `ndb` Property implementation (part 4)

---

ndb/src/google/cloud/ndb/model.py
ndb/tests/unit/test_model.py

- `Property._get_value`
- `Property._delete_value`
- `Property._is_initialized`
- Descriptors for `Property` (i.e. `__get__`, `__set__` and `__delete__`)
- `Property._prepare_for_put`
- `Property._check_property`
- `Property._get_for_dict`
----
Luckily this class is almost finished, with `_serialize`, `_deserialize`, `_prepare_for_put` (a no-op), `_check_property` and `_get_for_dict` the last remaining methods. I **think** I'll be able to port `_serialize|_deserialize` to the new [protobuf definitions][1] but I haven't looked into it deeply.
~~I'll probably update this PR with the implementations for `_prepare_for_put`, `_check_property` and `_get_for_dict` as well.~~
[1]: …

Continuation of `ndb` Property implementation (part 5)

---

bigtable/google/cloud/bigtable/row_data.py
bigtable/google/cloud/bigtable/table.py
bigtable/tests/unit/test_row_data.py
bigtable/tests/unit/test_table.py

Bigtable: Add retry parameter to 'Table.read_rows()'.

---

bigquery/google/cloud/bigquery/magics.py
bigquery/tests/unit/test_magics.py

Often it is useful to be able to parametrize query strings. While there is the option of parametrizing queries [using the raw sdk](https://cloud.google.com/bigquery/docs/parameterized-queries), there is no option to do so using the `%%bigquery` magic in Jupyter notebooks. 
This is useful for several reasons, specially when the same parameter appears several times in the query. This could be for example a cutoff date appearing in several `JOIN` conditions.
This PR adds the option `--params` to the `%%bigquery` magic for Jupyter notebooks. `--params` accepts a JSON string that will be used to format the string contained in the query. 
An example of how this would work:
```
%%bigquery df --params {"max_question_length":300,"limit":10}
SELECT
posts.id AS post_id,
posts.creation_date AS …
```

Add --params option to %%bigquery magic

---

bigtable/docs/snippets.py
bigtable/google/cloud/bigtable/instance.py
bigtable/noxfile.py
bigtable/tests/unit/test_instance.py

Closes #6337.
Refactor instance tests to mock 'instance_admin_client' directly, rather than underlying channel.
Normalize instance method order, and make testcase order match.  For the testcase changes, it might be easier to review commit-by-commit, at least up through fa5602c.

Bigtable: fix instance IAM methods

---

pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py

Trivial lint fix.  I will merge when green to get `master` green again for pubsub.

Pubsub: fix error from new flake8 version.

---

api_core/google/api_core/future/polling.py
api_core/tests/unit/future/test_polling.py

api_core: retry transient errors in 'PollingFuture.result'.

---

asset/google/cloud/asset_v1beta1/gapic/asset_service_client.py
asset/google/cloud/asset_v1beta1/gapic/transports/asset_service_grpc_transport.py
asset/google/cloud/asset_v1beta1/proto/asset_service_pb2.py
asset/google/cloud/asset_v1beta1/proto/asset_service_pb2_grpc.py
asset/google/cloud/asset_v1beta1/proto/assets_pb2.py
asset/synth.py

Exclude `nox.py` / `noxfile.py` from synth.
Closes #6348.

Asset: synth docstring changes generated from updated protos

---

logging/google/cloud/logging/handlers/transports/background_thread.py
logging/tests/unit/handlers/transports/test_background_thread.py

This reverts commit d72f44344b92c9e3d2806b815330189ee2cd43a8. (PR #6293).
As @yuvipanda [points out](https://github.com/googleapis/google-cloud-python/issues/5799#issuecomment-434798311), PR #6293 was the wrong solution for the issue.

Revert "Allow turning on JSON Detection in StackDriver"

---

api_core/setup.py
asset/noxfile.py
automl/noxfile.py
iot/noxfile.py
kms/noxfile.py
oslogin/noxfile.py
tasks/noxfile.py
texttospeech/noxfile.py
videointelligence/noxfile.py

Install `api_core` dependency in-place in affected packages.

Avoid broken 'google-common-apis 1.5.4' release.

---

asset/google/cloud/asset_v1beta1/proto/assets_pb2.py
asset/synth.py

Asset: fix docs build.

---

bigtable/tests/unit/test_row_data.py

Fixes broken coverage on 'master'.

Bigtable: add explicit coverage for 'row_data._retry_read_rows_exception'.

---

bigtable/docs/snippets.py
bigtable/tests/system.py

Harden table existence checks for eventual consistency.
Closes #6245
Use smaller number of clusters to avoid quota exhaustion during simultaneous CI runs.
Closes #6366
Avoid using Python `is` keyword in assertions where identity is not guaranteed.

Bigtable: fix flaky systests / snippets

---

ndb/MIGRATION_NOTES.md
ndb/src/google/cloud/ndb/eventloop.py
ndb/tests/unit/test_eventloop.py

Does not implement RPC integration.

WIP. First pass at ndb.eventloop.EventLoop implementation.

---

storage/google/cloud/storage/bucket.py
storage/tests/unit/test_bucket.py

Closes #6347.
This version of the PR preserves the copy operation (as requested by @frankyn) and only avoids the deletion.  It also neatens up how the copy / rename tests create mock blobs.

Storage: avoid deleting blob renamed to itself

---

pubsub/google/cloud/pubsub_v1/subscriber/client.py

The futures module used in the code is
google.cloud.pubsub_v1.subscriber.futures, not
google.cloud.pubsub_v1.futures. Also, the latter
doesn't seem to have a StreamingPullFuture.

Fix docstring reference to wrong class.

---

storage/google/cloud/storage/bucket.py
storage/tests/unit/test_bucket.py

Storage: accomodate new back-end restriction on retention period.

---

translate/README.rst

Correcting installation package from `google-cloud-datastore` to `google-cloud-translate`

Translate: Update README, correcting installation package

---

bigquery/google/cloud/bigquery/job.py
bigquery/tests/unit/test_job.py

Adds the option to specify job configuration class properties in the constructors. Resolves https://github.com/googleapis/google-cloud-python/issues/6386

BigQuery: Add properties to job config constructors

---

ndb/src/google/cloud/ndb/model.py
ndb/tests/unit/test_model.py

The `_db_set_value()` and `_db_get_value()` methods are just helpers for `Property._serialize()` and `Property._deserialize()`. As in #6389, I'm fairly certain that this won't be needed so for now I'm not implementing. (The previous implementation relies on the old protobuf definition, which is "stuck" inside Google App Engine standard.)

Implementing `BooleanProperty` in `ndb`.

---

translate/tests/system.py

The back-end used to translate "Me llamo Jeff" into German as "Mein Name ist Jeff";  now it uses the more idiomatic "Ich heiße Jeff".

Translate: adapt system test to updated back-end translation.

---

ndb/src/google/cloud/ndb/model.py
ndb/tests/unit/test_model.py

The `_db_set_value()` and `_db_get_value()` methods are just helpers for `Property._serialize()` and `Property._deserialize()`. As in #6389, I'm fairly certain that this won't be needed so for now I'm not implementing. (The previous implementation relies on the old protobuf definition, which is "stuck" inside Google App Engine standard.)

Implementing `IntegerProperty` in `ndb`.

---

ndb/docs/conf.py
ndb/noxfile.py
ndb/src/google/cloud/ndb/model.py

In the process:
- Removing `sphinx-docstring-typing` from the `ndb` docs process (the extension made it impossible to refer to `TextProperty`)
- Adding the Python `typing` helpers to `nitpick_ignore`
- Adding `autoclass` and `automethod` for some public members that have non-public names
----
I've marked this "do not merge" because there are several things that need discussion:
-   Is there a better way to handle the "`Text` gets replaced by `~typing.Text`" issue caused by `sphinx-docstring-typing`? (cc @theacodes) **UPDATE**: Sphinx does have support for type annotations, so maybe we should just do that?
-   @chrisrossi This would be a good time for us to decide which non-public methods should be documented as public. The [docs][1] you previously pointed to just repeat what's in the …

Adding class docstring for `ndb` `Property`.

---

error_reporting/google/cloud/errorreporting_v1beta1/gapic/enums.py
error_reporting/google/cloud/errorreporting_v1beta1/gapic/error_group_service_client.py
error_reporting/google/cloud/errorreporting_v1beta1/gapic/error_stats_service_client.py
error_reporting/google/cloud/errorreporting_v1beta1/gapic/report_errors_service_client.py
error_reporting/google/cloud/errorreporting_v1beta1/gapic/transports/report_errors_service_grpc_transport.py
error_reporting/synth.py

Remove now-spurious replacements from synth.
Fix newly-generated raw HTML junk in docstrings.
Closes #6411.

Error Reporting: fix client_info bug, update docstrings via synth.

---

storage/tests/system.py

Storage: harden teardown in system tests.

---

pubsub/google/cloud/pubsub_v1/publisher/client.py
pubsub/google/cloud/pubsub_v1/subscriber/client.py
pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py
pubsub/tests/unit/pubsub_v1/subscriber/test_subscriber_client.py

The `_gapic.add_methods` decorator doesn't quite get them right, so blacklist them from it and create them locally.
Closes #5903.

Pubsub: override client classmethod factories inherited from GAPIC.

---

ndb/src/google/cloud/ndb/_eventloop.py
ndb/src/google/cloud/ndb/exceptions.py
ndb/tests/unit/test__eventloop.py

This has little to do with the function of the same name from the original
NDB, since the way of managing the current event loop has changed.

Implement `get_event_loop`.

---

spanner/tests/_fixtures.py
spanner/tests/system/test_system.py

- Expand `all_types` table to include arrays of all types. 
- Remove redundant query param bindings tests using `all_types` table.
- Add tableless tests for float bindings with transfinite values.
- Add tableless tests for queries returning explicit transfinite values.
- Refactor `all_types` data to make feature coverage obvious (null values, non-null values, empty arrays, non-empty arrays w/ mixed non-null and null items).

Spanner: rationalize 'all_types' round-trip systest

---

api_core/setup.py
spanner/setup.py

In pip 8, which is currently used on ubuntu 16.04 LTS, extras with hyphens are ignored and not installed.

remove hyphen from named extra in api_core

---

api_core/google/api_core/protobuf_helpers.py
bigquery/google/cloud/bigquery/client.py
bigquery/google/cloud/bigquery/dbapi/_helpers.py
bigquery/google/cloud/bigquery/dbapi/cursor.py
core/google/cloud/iam.py
firestore/google/cloud/firestore_v1beta1/_helpers.py

On Python 2.7, fall back to 'collections'.
Closes #6450.

Import stdlib ABCs from 'collections.abc' rather than 'collections'.

---

firestore/google/cloud/firestore_v1beta1/query.py
firestore/tests/unit/test_query.py

Added 'array_contains' to the _COMPARISON_OPERATORS dict, to enable using array_contains in firestore queries.

---

ndb/MIGRATION_NOTES.md
ndb/src/google/cloud/ndb/model.py
ndb/src/google/cloud/ndb/query.py
ndb/tests/unit/test_model.py
ndb/tests/unit/test_query.py

This also required adding a small modification to `Property.__repr__` to change how it behaves for `KeyProperty`.

Implementing `KeyProperty` constructor in `ndb`.

---

ndb/src/google/cloud/ndb/_eventloop.py
ndb/src/google/cloud/ndb/exceptions.py
ndb/tests/unit/test__eventloop.py

Implementations for the relatively trivial helper/wrapper functions that merely get the current event loop and then call the corresponding method on the loop.

Ndb eventloop helpers

---

ndb/docs/async.rst
ndb/docs/context.rst
ndb/docs/index.rst
ndb/src/google/cloud/ndb/__init__.py
ndb/src/google/cloud/ndb/_eventloop.py
ndb/src/google/cloud/ndb/_runstate.py
ndb/src/google/cloud/ndb/exceptions.py
ndb/tests/unit/test__eventloop.py
ndb/tests/unit/test__runstate.py

The state managed by `_runstate` will eventually manage all of the runtime
state that falls under the aegis of `context.Context` and `tasklets._State`
in the legacy code.

Generalize `_eventloop.async_context` into `_runstate.ndb_context`.

---

spanner/google/cloud/spanner_admin_database_v1/gapic/database_admin_client.py
spanner/google/cloud/spanner_admin_database_v1/gapic/transports/database_admin_grpc_transport.py
spanner/google/cloud/spanner_admin_instance_v1/gapic/instance_admin_client.py
spanner/google/cloud/spanner_admin_instance_v1/gapic/transports/instance_admin_grpc_transport.py
spanner/google/cloud/spanner_v1/gapic/spanner_client.py
spanner/google/cloud/spanner_v1/gapic/transports/spanner_grpc_transport.py
spanner/synth.py
spanner/tests/unit/gapic/v1/test_database_admin_client_v1.py
spanner/tests/unit/gapic/v1/test_instance_admin_client_v1.py
spanner/tests/unit/gapic/v1/test_spanner_client_v1.py

- googleapis/gapic-generator#2407 (closing googleapis/gapic-generator#2389)
- googleapis/gapic-generator#2396 (for #5523 and dupes).
Includes changes to *all* generated tests.
Removes now-spurious docstring fixups.
Closes #6507.

Spanner: pick up fixes to GAPIC generator.

---

trace/google/cloud/trace_v1/gapic/trace_service_client.py
trace/google/cloud/trace_v1/gapic/transports/trace_service_grpc_transport.py
trace/google/cloud/trace_v2/gapic/trace_service_client.py
trace/google/cloud/trace_v2/gapic/transports/trace_service_grpc_transport.py
trace/synth.py
trace/tests/unit/gapic/v1/test_trace_service_client_v1.py
trace/tests/unit/gapic/v2/test_trace_service_client_v2.py

- googleapis/gapic-generator#2407 (closing googleapis/gapic-generator#2389)
- googleapis/gapic-generator#2396 (for #5523 and dupes).
Removes now-spurious docstring fixups.
Closes #6511.

Trace: pick up fixes to GAPIC generator.

---

vision/google/cloud/vision_v1/gapic/image_annotator_client.py
vision/google/cloud/vision_v1/gapic/product_search_client.py
vision/google/cloud/vision_v1/gapic/transports/image_annotator_grpc_transport.py
vision/google/cloud/vision_v1/gapic/transports/product_search_grpc_transport.py
vision/google/cloud/vision_v1/proto/image_annotator_pb2.py
vision/google/cloud/vision_v1/proto/product_search_service_pb2_grpc.py
vision/google/cloud/vision_v1/proto/text_annotation_pb2.py
vision/google/cloud/vision_v1p1beta1/gapic/image_annotator_client.py
vision/google/cloud/vision_v1p1beta1/gapic/transports/image_annotator_grpc_transport.py
vision/google/cloud/vision_v1p2beta1/gapic/image_annotator_client.py
vision/google/cloud/vision_v1p2beta1/gapic/transports/image_annotator_grpc_transport.py
vision/google/cloud/vision_v1p3beta1/gapic/image_annotator_client.py
vision/google/cloud/vision_v1p3beta1/gapic/product_search_client.py
vision/google/cloud/vision_v1p3beta1/gapic/transports/image_annotator_grpc_transport.py
vision/google/cloud/vision_v1p3beta1/gapic/transports/product_search_grpc_transport.py
vision/tests/unit/gapic/v1/test_image_annotator_client_v1.py
vision/tests/unit/gapic/v1/test_product_search_client_v1.py
vision/tests/unit/gapic/v1p1beta1/test_image_annotator_client_v1p1beta1.py
vision/tests/unit/gapic/v1p2beta1/test_image_annotator_client_v1p2beta1.py
vision/tests/unit/gapic/v1p3beta1/test_image_annotator_client_v1p3beta1.py
vision/tests/unit/gapic/v1p3beta1/test_product_search_client_v1p3beta1.py

Vision: pick up fixes to GAPIC generator.

---

bigtable/google/cloud/bigtable/row_data.py
bigtable/tests/unit/test_row_data.py

Bigtable: remove 'deepcopy' from 'PartialRowData.cells' property.

---

container/noxfile.py

This is useful for automated testing, and it makes the tests more consistent with the other system tests.

Pass posargs to py.test in Container system tests

---

firestore/google/cloud/firestore_v1beta1/document.py
firestore/tests/system.py
firestore/tests/unit/test_cross_language.py
firestore/tests/unit/test_document.py

Update conformance test to actually run for 'get'.
Toward #6533.

Firestore: refactor 'Document.get' to use the 'GetDocument' API.

---

firestore/google/cloud/firestore_v1beta1/collection.py
firestore/google/cloud/firestore_v1beta1/query.py
firestore/tests/system.py
firestore/tests/unit/test_query.py

Firestore: make cursor-related 'Query' methods accept lists

---

firestore/google/cloud/firestore_v1beta1/query.py
firestore/tests/unit/test_query.py

~~Uses #6697 as a base:  please review that PR first.~~
Closes #6704.

Firestore: prevent use of transforms as cursor values.

---

bigquery_storage/setup.py

The bigquery_storage release job failed with 
```HTTPError: 400 Client Error: Invalid value for classifiers. Error: '3 - Alpha' is not a valid choice for this field for url: https://upload.pypi.org/legacy/```

Correct release_status for bigquery_storage

---

firestore/google/cloud/firestore_v1beta1/query.py
firestore/tests/unit/test_query.py

Firestore: prevent use of transforms as values passed to 'Query.where'.

---

dns/noxfile.py
resource_manager/google/__init__.py
resource_manager/google/cloud/__init__.py
resource_manager/google/cloud/resource_manager/__init__.py
resource_manager/google/cloud/resource_manager/_http.py
resource_manager/google/cloud/resource_manager/client.py
resource_manager/google/cloud/resource_manager/project.py
resource_manager/noxfile.py
resource_manager/tests/unit/test__http.py
resource_manager/tests/unit/test_client.py
resource_manager/tests/unit/test_project.py
runtimeconfig/noxfile.py
translate/noxfile.py

add blacken to noxfile

---

bigquery/google/cloud/bigquery/table.py
bigquery/tests/unit/test_table.py

Per internal bug report 120204617.

BigQuery: allow setting None as partition expiration

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.6.0

---

ndb/.coveragerc

These were added in #6642 but I think they should be there:
- We actually need to have a faithful reproduction of `__repr__` for the original source
- The original `__repr__` implementations are verbose
- Right now, there are lots of virtual methods and test they are virtual, hence the coverage for `raise NotImplementedError`
I also think that `fail_under = 100` should be removed from `[report]`. It causes the `pytest ...` invocation to fail, and so `session.notify("cover")` never gets triggered and the actual coverage report of missing lines is no longer printed.

NDB: No longer excluding `__repr__` and abstract methods in coverage.
