- gcloud/datastore/dataset.py
- gcloud/datastore/query.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_dataset.py
- gcloud/datastore/test_query.py
- regression/clear_datastore.py
- regression/datastore.py
Split ``Query`` (abstract constraints) from excution/iteration (cursor, etc.)
Also, rip out the protobuf attributes:  doing the ongoing bookkeeping on them was painful (and a bug magnet).  Instead, build the protobuf when we need it (just before fetching data), using values from both the query and the iterator.
Fixes #439.
> Fix #439: split query vs. iterator apart.

- gcloud/datastore/__init__.py
- gcloud/datastore/_implicit_environ.py
- gcloud/datastore/test___init__.py
This allows methods which rely on a connection to be used with no arguments.
Fixes first part of #477.
> Address first part of 477: Implements datastore.set_default_connection.

- gcloud/datastore/dataset.py
- gcloud/datastore/test_dataset.py
- regression/datastore.py
**NOTE**: Has #478 as diffbase.
> Address second part of 477: Remove query(), entity(), and transaction() methods from Dataset.

- gcloud/datastore/query.py
- gcloud/datastore/test_query.py
Sets the projection to include only entity keys.
Supercedes #466.
> Add 'keys_only' method to Query.

- gcloud/datastore/__init__.py
- gcloud/datastore/dataset.py
- gcloud/datastore/entity.py
- gcloud/datastore/key.py
- gcloud/datastore/test___init__.py
- gcloud/datastore/test_dataset.py
- gcloud/datastore/test_entity.py
- gcloud/datastore/test_key.py
- pylintrc_default
- regression/datastore.py
**NOTE**: Has #479 as diffbase.
Also, fixes #464
> Address third part of 477: Move Dataset.get_entity to Key.

- gcloud/datastore/connection.py
- gcloud/datastore/entity.py
- gcloud/datastore/key.py
- gcloud/datastore/test_dataset.py
- gcloud/datastore/test_entity.py
- gcloud/datastore/test_key.py
- regression/datastore.py
**NOTE**: Has #480 as diffbase.
> Address fourth part of 477: Moving Entity.delete to Key (for datastore).

- gcloud/datastore/__init__.py
- gcloud/datastore/connection.py
- gcloud/datastore/entity.py
- gcloud/datastore/helpers.py
- gcloud/datastore/key.py
- gcloud/datastore/query.py
- gcloud/datastore/test___init__.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_entity.py
- gcloud/datastore/test_helpers.py
- gcloud/datastore/test_key.py
- gcloud/datastore/test_query.py
- regression/datastore.py
Also:
- Dropping `dataset` and `kind` from `Entity` constructor.
- Dropping `Entity.from_path` factory.
- Removing `Connection.dataset()` quasi-factory.
- `helpers.entity_from_protobuf()` no longer accepts / needs `dataset`.
- Making `Entity.key` a data attribute instead of a getter/setter method.
- Removing `Entity.dataset()` (since no longer stored).
- Making `Entity.kind()` and `Entity.exclude_from_indexes()` into `@property`'s.
- Removing `Entity._must_dataset` (no longer needed).
- Adding optional connection argument to `Entity.save()` and `Entity.reload()`.
- Making `Entity.save()` and `Entity.reload()` return nothing.
- Updating `regression/datastore.py` for changes.
Fix #484 
**NOTE**: Has #483 as diffbase.
> Fix #484: Remove dataset from entity

- gcloud/datastore/query.py
- gcloud/datastore/test_query.py
> Avoid copying a limit to query protobuf unless explicitly passed.

- gcloud/datastore/__init__.py
- gcloud/datastore/test___init__.py
Cleanups needed prior to landing fix for #485.
> Quick cleanups 20140107

- gcloud/datastore/query.py
- gcloud/datastore/test_query.py
- regression/clear_datastore.py
Instead, `dataset_id` and `connection` are passed in, or derived from
the implicit environ.
Fixes #485.
> #485: Drop Query use of Dataset object

- gcloud/datastore/_implicit_environ.py
- gcloud/datastore/connection.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_entity.py
- gcloud/datastore/test_helpers.py
- gcloud/datastore/test_key.py
- gcloud/datastore/test_transaction.py
- gcloud/datastore/transaction.py
> Remove Transaction dependency on Dataset.

- gcloud/datastore/__init__.py
- gcloud/datastore/connection.py
- gcloud/datastore/entity.py
- gcloud/datastore/key.py
- gcloud/datastore/test___init__.py
- gcloud/datastore/test_key.py
- Make `require_dataset_id` and '_require_connection' take the passed object, and test explicitly against None.
- Tweak docstrings to reflect API changes.
- Clarify implicit environ tests.
- Clarify dependency on implicit environ in key tests.
> Cherry pick cleanups from #499.

- run_pylint.py
This was removed in e998859d8dba24a97be97ead6edc759c77a22375 since
it broke pylint by removing a module.
> Putting back lint speedups for pull requests.

- regression/clear_datastore.py
- regression/datastore.py
- regression/populate_datastore.py
Will wait until #501 is in and then rebase after.
See [previous remarks][1] for context.
Also fixes #453.
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/500#issuecomment-69088202
> Update regression scripts to work with new API.

- gcloud/storage/key.py
- gcloud/storage/test_key.py
For issue #311 
storage.key.get_contents_to_filename will sync file's mtime and metadata's updated time
> Sync mtime with updated time

- gcloud/datastore/test_helpers.py
Rename several testcases to make their intent clearer in the NWO.
See:  https://github.com/GoogleCloudPlatform/gcloud-python/pull/500/files#r22611632
> Remove now-redundant testcase.

- docs/datastore-batches.rst
- docs/index.rst
- gcloud/datastore/batch.py
- gcloud/datastore/connection.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_connection.py
> Add a 'Batch': collects non-transactional saves / deletes.

- gcloud/datastore/batch.py
- gcloud/datastore/test_batch.py
> Add 'insert_auto_ids' support to 'Batch'.

- gcloud/datastore/test_transaction.py
- gcloud/datastore/transaction.py
As a side effect, `Transaction` gets `put` and `delete` methods.
> Derive 'Transaction' from 'Batch'.

- gcloud/datastore/batch.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/transaction.py
> Push batch / transaction onto a thread-local stack inside 'with'.

- gcloud/datastore/__init__.py
- gcloud/datastore/key.py
- gcloud/datastore/test___init__.py
Since we require `Key` to have a dataset ID, these methods should not be allowed to ignore this value.
For `allocate_ids` this is cut and dry but for `get_entities` we may want to allow the user to provide `dataset_id` since there are potentially **many** keys to check. (Performance sensitive.)
--------
@pcostell 
In the `get_entities` change, we check that the `dataset_id` of every `Key` in a list is identical.
This can cause all kinds of trouble, just in comparing prefixed and un-prefixed alone. Do you think this check can be avoided? Due to GoogleCloudPlatform/google-cloud-datastore#59 it's not possible to just set the dataset ID on the `Key` protobuf and let the backend do the checking for us.
OTOH, creating the protobufs for each `Key` will be the same O(n) work that checking the …
> Removing dataset_id from allocate_ids and get_entities

- gcloud/datastore/__init__.py
- gcloud/datastore/api.py
- gcloud/datastore/demo/demo.py
- gcloud/datastore/key.py
- gcloud/datastore/test_api.py
- regression/datastore.py
> Rename get_entities() to get().

- gcloud/datastore/api.py
- gcloud/datastore/test_api.py
> Allow get() to take a single key (in addition to a list)

- gcloud/datastore/__init__.py
- gcloud/datastore/connection.py
- gcloud/datastore/entity.py
- gcloud/datastore/key.py
- gcloud/datastore/test_entity.py
- gcloud/datastore/test_key.py
- pylintrc_default
- regression/datastore.py
Has #521 as diffbase.
Removed `Entity.reload()` because it relied on the existence of `Key.get()`. Replacing it would have required another cyclic import.
See #490 RE: removing `Entity.reload()`.
Fixes #517.
> Remove Key.get() and Entity.reload()

- README.rst
- docs/_components/datastore-getting-started.rst
- docs/index.rst
- gcloud/datastore/__init__.py
- gcloud/datastore/connection.py
- gcloud/datastore/demo/__init__.py
- gcloud/datastore/test___init__.py
- gcloud/datastore/transaction.py
- regression/clear_datastore.py
- regression/datastore.py
- regression/populate_datastore.py
This will be the most common auth / setup path for typical users.
It may make sense at some point to create a config class in [`datastore/_implicit_environ.py`][1] to allow lots of config at once / swappable setting for multi-tenant applications.
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/0525530ad7a76e408ca2e842b883d49c353ed56d/gcloud/datastore/_implicit_environ.py
> Adding umbrella datastore.set_defaults().

- README.rst
- docs/_components/datastore-getting-started.rst
- docs/_components/datastore-quickstart.rst
- docs/index.rst
- gcloud/datastore/__init__.py
- gcloud/datastore/connection.py
- gcloud/datastore/demo/demo.py
- regression/clear_datastore.py
- regression/datastore.py
- regression/populate_datastore.py
Also updating docs to reflect this.
> Moving public classes into datastore package.

- gcloud/datastore/batch.py
- gcloud/datastore/test_batch.py
> Factor out mutation-setting logic from 'Connection'.

- gcloud/datastore/__init__.py
- gcloud/datastore/api.py
- gcloud/datastore/batch.py
- gcloud/datastore/connection.py
- gcloud/datastore/demo/demo.py
- gcloud/datastore/key.py
- gcloud/datastore/test_api.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_key.py
- regression/clear_datastore.py
- regression/datastore.py
Also:
- Changing api.get() back to accept only `keys` and
returns only a list (a lot of headache for not much
gain).
- Factored out behavior to extract shared dataset_id from
a set of keys into _get_dataset_id_from_keys().
- Updated docstrings and other tests that rely on changed /
removed methods.
See #518 for some context.
> Adding api.delete() and removing Key.delete().

- gcloud/datastore/connection.py
- gcloud/datastore/helpers.py
- gcloud/datastore/test_connection.py
for issue #403
Previous PR
https://github.com/GoogleCloudPlatform/gcloud-python/pull/404
> Property with empty list 4

- docs/_components/datastore-getting-started.rst
- docs/_components/datastore-quickstart.rst
- docs/index.rst
- gcloud/datastore/__init__.py
- gcloud/datastore/api.py
- gcloud/datastore/demo/demo.py
- gcloud/datastore/entity.py
- gcloud/datastore/test_api.py
- gcloud/datastore/test_entity.py
- gcloud/datastore/transaction.py
- regression/datastore.py
- regression/populate_datastore.py
Similar to the `delete` API added in #522.
> #514: add `datastore.put` API, remove `Entity.save'

- run_pylint.py
Was removed in #542.
Also modifying `lint_fileset` so that removing / renaming files does not give `run_pylint` fits.
> Restore pylint speedup for PRs

- gcloud/datastore/helpers.py
- gcloud/datastore/test_helpers.py
> Preserving indexed=False from parsed proto `Value`s.

- gcloud/storage/acl.py
- gcloud/storage/connection.py
- gcloud/storage/test_connection.py
- setup.py
Requires `oauth2client>=1.4.6` (@tseaver should I put this in `setup.py`?)
Also had to update storage/acl.py due to a change in
PyLint that didn't like `self` as a kwarg to a str instance
method
Fixes #537
> Removing hard dependency on PyOpenSSL.

- regression/datastore.py
This is to address flaky test failures.
See #535 for more discussion.
> Making regression test put()'s transactional.

- regression/storage.py
Adds a `safe_delete()` which respects objects which are still listed for a bucket but have already been deleted. (This is because the object list is eventually consistent and we delete some objects in our regression tests.)
Fixes #531. See #535 for context.
Fix based on [comment][1] from @thobrla.
This is a "temporary" stop-gap and the safe delete can likely be folded into `Connection.delete_bucket()`. For now, we want to eliminate flaky regression test failures.
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/535#issuecomment-71078224
> Making sure delete does not fail in regression tests.

- README.rst
- docs/_components/storage-getting-started.rst
- docs/_components/storage-quickstart.rst
- docs/index.rst
- docs/storage-api.rst
- docs/storage-blobs.rst
- docs/storage-keys.rst
- gcloud/storage/__init__.py
- gcloud/storage/_helpers.py
- gcloud/storage/acl.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/connection.py
- gcloud/storage/demo/demo.py
- gcloud/storage/iterator.py
- gcloud/storage/test_acl.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
- gcloud/storage/test_connection.py
- pylintrc_default
- regression/storage.py
This involves changes in all documentation, renaming a module
and a test module, and updating the calls and variable names in
a regression test module.
Addresses #544.
See https://github.com/dhermes/gcloud-python/tree/fix-544-many-commits for a more digestible version of these commits (though it's still not very digestible).
To "check" I was finished I manually inspected the output of "git grep -i key".
> Changing Key noun to be Blob in storage package.

- gcloud/datastore/key.py
- gcloud/datastore/test_key.py
- regression/datastore.py
Using an ancestor in queries to ensure consistency.
See #562 for context.
> Fixing flaky datastore queries in regression tests.

- README.rst
- docs/_components/storage-getting-started.rst
- docs/_components/storage-quickstart.rst
- gcloud/storage/__init__.py
- gcloud/storage/blob.py
- gcloud/storage/demo/demo.py
- regression/storage.py
Removing storage Blob / Object boto naming aliases.
Addresses part of #544. Uses #560 as diffbase.
> Remove boto aliases

- gcloud/datastore/__init__.py
- gcloud/datastore/_implicit_environ.py
- gcloud/datastore/test___init__.py
> Adding implicit dataset ID support for GAE and GCE.

- gcloud/datastore/api.py
- gcloud/datastore/batch.py
- gcloud/datastore/helpers.py
- gcloud/datastore/test_api.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_helpers.py
> Require that keys for 'put' / 'delete' match the 'dataset_id' of the batch

- docs/_components/storage-getting-started.rst
- docs/gcloud-api.rst
- docs/storage-api.rst
- gcloud/datastore/connection.py
- gcloud/datastore/test_connection.py
- gcloud/exceptions.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/connection.py
- gcloud/storage/test_acl.py
- gcloud/storage/test_bucket.py
- gcloud/storage/test_connection.py
- gcloud/test_exceptions.py
- regression/storage.py
Address #508:
- Move `gcloud.storage.exceptions` -> `gcloud.exceptions`:  make the base class `GCloudError` rather than `StorageError`.
-  Fix response status codes for Unauthorized (401) and Forbidden (403).
- Use `make_exception` from `datastore.connection.Connection._request`
> Fix #508: unify http exceptions

- gcloud/datastore/_implicit_environ.py
- gcloud/datastore/test___init__.py
Fixes #575.
Feel free to run the bash script I [included][1] in the bug to torture test the fix.
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/575#issuecomment-71943675
> Using httplib instead of httplib2 to get GCE metadata.

- gcloud/datastore/connection.py
- gcloud/datastore/test_connection.py
This is in line with our decision in `api.get` / `api.put` / `api.delete` to only take a list and not over-use `isinstance()`.
> Requiring Connection.lookup to take a list in datastore.

- gcloud/storage/__init__.py
- gcloud/storage/_implicit_environ.py
- gcloud/storage/test___init__.py
This is in preparation for using the default bucket in the Blob constructor.
> Using a default bucket instead of bucket name in storage.

- gcloud/storage/bucket.py
- gcloud/storage/connection.py
- gcloud/storage/test_bucket.py
- gcloud/storage/test_connection.py
- regression/storage.py
> Making Bucket.delete() work in face of eventual consistency.

- gcloud/storage/bucket.py
- gcloud/storage/connection.py
- gcloud/storage/test_connection.py
This was seldom being used and didn't actually create a new bucket.
~~**NOTE**: Has #581 as a diffbase. (NOW MERGED).~~
> Ditch Connection.new_bucket method in storage

- gcloud/datastore/api.py
- gcloud/datastore/connection.py
- gcloud/datastore/test_api.py
- gcloud/datastore/test_connection.py
**NOTE**: Has #582 as a diffbase.
@tseaver This is based on my [comment][1] in the other PR. If you disagree, we can torpedo this PR. (FWIW I don't see a reason why we'd want this behavior on the `Connection` rather than associated with `datastore.get`, but maybe I'm missing something.)
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/582#issuecomment-72292244
> Connection lookup single request

- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
Also making bucket required to exit the constructor.
~~**NOTE**: Has #584 as diffbase. (NOW MERGED)~~
> Falling back to implicit bucket in Blob constructor.

- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
> Ensure bucket upload methods return the blob.

- gcloud/datastore/test_transaction.py
- gcloud/datastore/transaction.py
Fixes #496.
NOTE: Some of these changes may belong on `Batch`, but the concept
of "tombstone"-ing is unique to a Transaction (i.e. once started,
can only be committed once and the transaction ID can never be
used again).
@tseaver I initially tried to do this stuff in `Batch.__enter__` and `Batch.__exit__` but the re-use policies differ and I wanted this to work outside of context managers. LMK what you think.
> Tracking status of Transaction as well as success / failure.

- gcloud/datastore/demo/demo.py
- gcloud/datastore/helpers.py
- gcloud/storage/demo/demo.py
Only surfaced on Travis, or with 'tox --recreate -e lint'.
> Fix errors under pep8 1.6.1.

- tox.ini
> Add py33 to tox.

- docs/_components/storage-getting-started.rst
- gcloud/storage/bucket.py
- gcloud/storage/connection.py
- gcloud/storage/test_bucket.py
- gcloud/storage/test_connection.py
> Removing __iter__ and __contains__ from Connection in storage.

- gcloud/storage/bucket.py
Fixes #60.
Much of the discussion in #60 focuses on dunder-methods which no longer exist. This documents the remaining ones that don't have docstrings, hence don't show up in our API docs.
> Documenting dunder (e.g. __iter__) methods without docstrings.

- gcloud/storage/connection.py
- gcloud/storage/test_connection.py
Making it clear in the docstring that the Connection itself only handles `storage.bucket...` API methods and that the other classes handle the other 30 (give or take) methods of the API.
@tseaver This documents our decision from earlier today (about the responsibilities of `Connection`).
Also note
- We don't directly support `storage.buckets.update` anywhere (but `Connection.api_request` would allow it)
- We don't support `storage.buckets.patch` on `Connection`. Only via `Bucket` (through `_PropertyMixin._patch_properties()`).
- Both `Bucket._reload_properties()` (via `_PropertyMixin`) and `Connection.get_bucket` implement `storage.buckets.get`.
For your reference: [discovery document][1].
[1]: https://gist.github.com/dhermes/86b1dc89ebd8afd7a506#file-storage-v1-rest-json
> Storage: updating Connection docstring; turning make_request private.

- run_pylint.py
This surfaced as a false negative in #611.
> Repeating pylint after failures.

- gcloud/datastore/helpers.py
- gcloud/datastore/test_helpers.py
> Only parsing protobuf entity key if field is set.

- gcloud/storage/_helpers.py
- gcloud/storage/test__helpers.py
- regression/storage.py
May make sense to swap out for `hashlib.md5` (though they seem to
be equivalent).
In preparation for #547.
> Moving MD5 hash method from regression to storage helpers.

- gcloud/connection.py
- gcloud/test_connection.py
This will allow libraries other than httplib2 to be used.
Fixes #551.
@tseaver I dream of tearing `httplib2` out as a dependency (also would need to come out of `oauth2client`) and using something simple like `httplib` for the default `http` object. Sigh.
But really this is to support users in specialized environments like `twisted` or people who prefer `requests`
> Allow http as an argument to base Connection class.

- regression/datastore.py
> Update datastore regression to use Entity/Key equality.

- gcloud/_localstack.py
- gcloud/datastore/batch.py
- gcloud/datastore/test_batch.py
- gcloud/test__localstack.py
Preparing to tackle #15, which needs similar support in storage.
> Move the 'thread-local stack' implementation up from datastore.

- gcloud/datastore/connection.py
- gcloud/datastore/test_connection.py
- gcloud/exceptions.py
> Making json.loads() optional in gcloud.exceptions.make_exception.

- gcloud/storage/blob.py
- gcloud/storage/test_blob.py
This is instead of using the mimetype for all files (the Python
mimetypes.guess_type method is a bit limited).
Fixes #536.
> DISCUSSION PR: Uses Blob's current content type (in an upload) when present.

- docs/_static/css/main.css
> Fixed #634 - Formatting on admonitions looked off.

- gcloud/connection.py
I noticed this during the discussion in #639.
This change is borderline not requiring a PR, but I figured it couldn't hurt as an FYI.
> Removing unused _EMPTY sentinel from base Connection.

- setup.py
This is for a Friday minor release cycle.
@tseaver I'll handle pushing the tag as well. Preference for tag names? Current is:
```
0.3.0
v0.4.0
```
> Upgrading version to 0.4.1.

- gcloud/credentials.py
- gcloud/test_credentials.py
Fixes #638.
@jgeewax PTAL
I thought about wrapping JSON key and PKCS12 key into one method but the JSON key is actual a JSON payload with everything needed, e.g.
```JSON
{
"private_key_id": "0996.....",
"private_key": "-----BEGIN PRIVATE KEY-----\nMIICdgIBADA.....\n-----END PRIVATE KEY-----\n",
"client_email": "32578400.......@developer.gserviceaccount.com",
"client_id": "32578400.........apps.googleusercontent.com",
"type": "service_account"
}
```
whereas a P12 key is just the bytes in `private_key` (and created for PKCS12 rather than PEM).
I don't think it's worth trying to smash together the two API surfaces:
```python
get_for_service_account_json(private_key_path, scope=None)
get_for_service_account_p12(client_email, private_key_path, scope=None)
```
> Adding get_for_service_account_json function in credentials.

- scripts/merge.sh
A tag is not associated with a branch inherently so
TRAVIS_BRANCH == master is the wrong check.
See my previous [comment][1] for context.
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/472#issuecomment-74357165
> Making sure new docs get built on tags.

- gcloud/datastore/dataset.py
- gcloud/datastore/test_dataset.py
Wrapper around 'datastore.api.{get,put,delete}', plus the 'Key',
'Batch', 'Transaction', and 'Query' factories.
Per @jgeewax in #659.
> Restore 'Dataset' class.

- gcloud/connection.py
- gcloud/datastore/__init__.py
- gcloud/datastore/connection.py
- gcloud/datastore/test___init__.py
- gcloud/datastore/test_api.py
- gcloud/datastore/test_connection.py
- gcloud/storage/connection.py
Enabling
- set_default_dataset_id() support for DATASTORE_DATASET environment
variable name
- gcloud.datastore.Connection.API_BASE_URL override for
DATASTORE_HOST environment variable name
Fixes #650.
> Adding support for GCD dev server in datastore package.

- gcloud/datastore/__init__.py
- gcloud/datastore/_implicit_environ.py
- gcloud/datastore/api.py
- gcloud/datastore/batch.py
- gcloud/datastore/key.py
- gcloud/datastore/query.py
- gcloud/datastore/test__implicit_environ.py
This is in preparation to add lazy loading.
> Using getters in _implicit_environ instead of direct access.

- index.html
**NOTE**: Has #661 as a diffbase
Fixes #646 (originally I accidentally said #553).
Uses the Python snippet
```python
from gcloud import datastore
datastore.set_defaults()
product_key = datastore.Key('Product', 123)
print datastore.get([product_key])
```
and
```bash
pygmentize -f html gcloud_landing_snippet.py
```
to create the highlighted HTML.
I initially tried to find a place to put these, but the nothing really felt appropriate since the main `index.html` is not part of any build stage.
> Adding a code snippet to the landing page.

- .gitignore
- scripts/get_version.py
- scripts/update_docs.sh
- scripts/update_versions.py
- scripts/versions.html.template
Relates to #472
Requires #661 to be merged before this can be.
> Adding update stage for static versions page in docs.

- .gitignore
Can't add a submodule to a path that is `.gitignore`d.
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/51413887
> Fixing broken build.

- gcloud/datastore/__init__.py
- gcloud/datastore/_implicit_environ.py
- gcloud/datastore/test___init__.py
- gcloud/datastore/test__implicit_environ.py
- gcloud/datastore/test_api.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_entity.py
- gcloud/datastore/test_helpers.py
- gcloud/datastore/test_key.py
- gcloud/datastore/test_query.py
- gcloud/datastore/test_transaction.py
This is so that a container instance can have lazily loaded properties.
**NOTE**: Has #663 as a diffbase
> Replacing _implicit_environ module globals with a container.

- gcloud/datastore/_implicit_environ.py
- gcloud/datastore/_testing.py
- gcloud/datastore/test___init__.py
- gcloud/datastore/test__implicit_environ.py
- gcloud/datastore/test_api.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_entity.py
- gcloud/datastore/test_helpers.py
- gcloud/datastore/test_key.py
- gcloud/datastore/test_query.py
- gcloud/datastore/test_transaction.py
**NOTE**: Has #664 as diffbase
Introduces
- concept of `implicit` for `_DefaultsContainer`.
- testing module for datastore for patching
Verified all test cases that would accidentally rely on _DEFAULTS implicit
behavior by using a custom `_DefaultsContainer` that raises when the
instance is implicit.
Main delta for the custom properties:
```diff
diff --git a/gcloud/datastore/_implicit_environ.py b/gcloud/datastore/_implicit_environ.py
index 3afc954..1d38562 100644
--- a/gcloud/datastore/_implicit_environ.py
+++ b/gcloud/datastore/_implicit_environ.py
@@ -38,9 +38,37 @@ class _DefaultsContainer(object):
:param dataset_id: Persistent implied dataset ID from environment.
"""
-    def __init__(self, connection=None, dataset_id=None):
-        self.connection = connection
- …
```
> Adding datastore _DEFAULTS stubs in all tests that use it.

- gcloud/datastore/_implicit_environ.py
- gcloud/datastore/_testing.py
- gcloud/datastore/test__implicit_environ.py
- pylintrc_default
- regression/clear_datastore.py
- regression/datastore.py
- regression/populate_datastore.py
**NOTE**: Has #666 as diffbase.
Still need to support connection (and eventually do the same
in storage).
Again verified only the lazy loading tests used implicit
behavior via
```diff
diff --git a/gcloud/datastore/_implicit_environ.py b/gcloud/datastore/_implicit_environ.py
index 6e61636..6d67be6 100644
--- a/gcloud/datastore/_implicit_environ.py
+++ b/gcloud/datastore/_implicit_environ.py
@@ -177,6 +177,10 @@ class _LazyProperty(object):
self._method = method
def __get__(self, obj, objtype):
+        class FooError(Exception):
+            pass
+        raise FooError
+
if obj is None or objtype is not _DefaultsContainer:
return self
```
> Adding lazy loading support for dataset ID.

- CONTRIBUTING.rst
- README.rst
@jgeewax PTAL
Holding off on Authorization until we finalize this behavior and unify across services.
Styled after https://github.com/GoogleCloudPlatform/gcloud-node
See https://github.com/dhermes/gcloud-python/blob/standardize-readme/README.rst for updated version.
Partially addresses #591.
Needs #668 to be done among other things before Authorization can be documented (not a very unified approach right now)
> Updating README to meet unified gcloud-* format.

- docs/_templates/layout.html
Fixes #472. (This is the last piece needed after #625 and #662)
> Adds link to versions on every doc page.

- tox.ini
Allows us to work on more issues until a release is available that fixes https://github.com/google/oauth2client/issues/125.
> Use a development checkout of oauth2client in regresion3.

- gcloud/datastore/api.py
- gcloud/datastore/test_api.py
> #649: Raise ValueError if single entity is passed to 'datastore.put'.

- gcloud/datastore/__init__.py
- gcloud/datastore/_implicit_environ.py
- gcloud/datastore/batch.py
- gcloud/datastore/connection.py
- gcloud/datastore/helpers.py
- gcloud/datastore/test___init__.py
- gcloud/datastore/test__implicit_environ.py
**NOTE**: Has #667 as diffbase.
Happens in 4 phases:
- Remove `datastore.helpers` import in `connection`. (this would have caused a cycle if `Connection` was used in `_implicit_environ`)
- Moving `get_connection()` from `datastore.__init__` to `_implicit_environ`.
- Moving `set_default_connection()` from `datastore.__init__` to `_implicit_environ`.
- Adding lazy loading support for the connection property
Note that I had to copy `_prepare_key_for_request` from `helpers` into `connection` to avoid cyclic imports (#528 would be nice, since we could just remove `_prepare_key_for_request` all together)
> Adding lazy loading support for datastore connection.

- regression/clear_datastore.py
- regression/datastore.py
- regression/populate_datastore.py
This makes sure that our setup for auth / connection / dataset_id works without ever calling `set_defaults()`.
> Using fully implicit auth in datastore regression.

- docs/_static/css/main.css
- docs/_templates/layout.html
- docs/conf.py
Fixes #98.
A typical "Report an Issue" button will link to:
https://github.com/GoogleCloudPlatform/gcloud-python/issues/new?title=%5BDocumentation+Issue%5D+&body=Page+Name%3A+datastore-api%0ARelease%3A%200.4.1
The `release` in the link will either be a stable release (as in http://googlecloudplatform.github.io/gcloud-python/0.4.1/index.html) or will be a commit hash (as in http://googlecloudplatform.github.io/gcloud-python/master/)
(The "release" may need some URL escaping.)
> Make it easy to open a documentation bug from the docs themselves

- setup.py
This is for a minor release cycle.
> Upgrading version to 0.4.2.

- gcloud/datastore/_implicit_environ.py
- gcloud/datastore/test__implicit_environ.py
**NOTE**: Has #668 as diffbase
Tests previously were mixing the logic of the 4 possible environments while the simple ordering of them in `set_default_dataset_id()` and now `_determine_default_dataset_id()`.
This PR separates that logic and makes sure each environ helper is called in a specific order.
In order to do this it also introduces two one-line functions `_get_production_dataset_id()` and `_get_gcd_dataset_id()` in the implicit environ module.
> Unwinding cases in Test_set_default_dataset_id and having better test separation

- gcloud/storage/batch.py
- gcloud/storage/connection.py
- gcloud/storage/test_batch.py
- regression/storage.py
Step #2 in https://github.com/GoogleCloudPlatform/gcloud-python/issues/15#issuecomment-74151347
> #15: Add `storage.batch.Batch`

- gcloud/storage/acl.py
- gcloud/storage/test_acl.py
Apparently, the back-end can (in some cases, at least) omit empty 'acl'
elements from the returned resource.
Fixes #652.
> #652: Harden ACL 'save'/'reload' against missing element in server response.

- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
@tseaver there is plenty to discuss here and I will enumerate.
In the immediately relevant category is my uses of `self.patch()` in several of the methods. I was unclear if we think they should be setters or actual API requests.
Relates to #632.
> Separating _patch_properties and PATCH on Bucket.

- README.rst
- docs/_components/datastore-getting-started.rst
- docs/index.rst
- gcloud/datastore/__init__.py
- gcloud/datastore/connection.py
- gcloud/datastore/demo/__init__.py
- gcloud/datastore/transaction.py
Fixes #685.
**NOTE**: I did not remove the actual method from `datastore.__init__` but easily could.
Here are the remaining uses of it.
In `datastore`:
```
$ git grep set_defaults 
gcloud/datastore/__init__.py:def set_defaults(dataset_id=None, connection=None):
gcloud/datastore/test___init__.py:class Test_set_defaults(unittest2.TestCase):
gcloud/datastore/test___init__.py:        from gcloud.datastore import set_defaults
gcloud/datastore/test___init__.py:        return set_defaults(dataset_id=dataset_id, connection=connection)
```
And `storage`:
```
gcloud/storage/__init__.py:def set_defaults(bucket=None, project=None, connection=None):
gcloud/storage/test___init__.py:class Test_set_defaults(unittest2.TestCase):
gcloud/storage/test___init__.py:        from gcloud.storage import …
```
> Removing datastore.set_defaults() from all docs.

- gcloud/storage/__init__.py
- regression/storage.py
This is towards removing Bucket.new_blob(). It is currently
used only in Bucket to coerce from string OR a Blob object
and then perform some action on the Blob object:
- Bucket.get_blob()
- Bucket.delete_blob()
- Bucket.upload_file()
- Bucket.upload_file_object()
But we can move most of this behavior onto Blob (no coercion
necessary).
> Removing uses of Bucket.new_blob from regression tests.

- regression/storage.py
See my [comment][1] on #15 for context.
I was in general playing around with ditching `_PropertyBatch` (or just merging that functionality into `Batch`) and trying to figure out how to [properly handle][2] the 204 response in a patch within a batch.
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/15#issuecomment-77965089
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/683#issuecomment-76275986
> Removing use of non-batchable request in storage regression.

- gcloud/datastore/_implicit_environ.py
- gcloud/storage/__init__.py
- gcloud/storage/_implicit_environ.py
- gcloud/storage/_testing.py
- gcloud/storage/blob.py
- gcloud/storage/test___init__.py
- gcloud/storage/test_blob.py
- regression/storage.py
This is in preparation to have lazy-loading auth and other settings as is done in the datastore.
> Using defaults container in storage (for implicit).

- docs/conf.py
This warning occurs in Sphinx 1.3 (and we treat all warnings as
errors). Thus it broke the most recent builds:
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/54014910
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/54015649
> Updating Sphinx theme from default to classic.

- gcloud/storage/__init__.py
- gcloud/storage/test___init__.py
Also removing the same fallback in `set_default_connection` since it calls `get_connection()`.
--------
FWIW: I came across this while trying to make implicit auth work in storage. The fact that `get_connection` requires arguments doesn't work well with [`_LazyProperty`][1].
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/8ac28d16a5f2537579df297df477263a58aa1e45/gcloud/datastore/_implicit_environ.py#L226-L227
> STORAGE: Adding default project in get_connection.

- gcloud/storage/__init__.py
- gcloud/storage/api.py
- gcloud/storage/test_api.py
This was originally removed in #588.
@tseaver I'd like to remove all the bucket functions from `Connection` and move them into `api`. WDYT?
Also it seems we'd eventually want to add a `_require_connection` as in `datastore.api`. It would be nice to come with a re-factor for re-usability (the `Batch` is the part which needs to be package specific).
--------
FWIW: I came across this while trying to make implicit auth work in storage. Importing `Connection` in `_implicit_environ` creates a cycle, essentially because `Connection` imports `Bucket`.
> Adding back storage.lookup_bucket.

- docs/datastore-dataset.rst
- docs/index.rst
> Adding datastore.dataset module to docs index.

- gcloud/datastore/__init__.py
- gcloud/datastore/batch.py
Also adding Dataset class as a documented import in the
datastore package __init__.
Fixes #709.
Fixes #710.
> Fixing Batch class docstring (referenced dead code).

- docs/_components/storage-getting-started.rst
- docs/_components/storage-quickstart.rst
- gcloud/storage/__init__.py
- gcloud/storage/api.py
- gcloud/storage/connection.py
- gcloud/storage/demo/demo.py
- gcloud/storage/test_api.py
- gcloud/storage/test_connection.py
- regression/storage.py
See comments in #700 for context.
@tseaver I figured it would be easier to digest moving one method at a time instead of all 4 at once. Still remaining:
```bash
$ git grep -e '^    def' -- gcloud/storage/connection.py
gcloud/storage/connection.py:    def __init__(self, project, *args, **kwargs):
gcloud/storage/connection.py:    def build_api_url(self, path, query_params=None, api_base_url=None,
gcloud/storage/connection.py:    def _make_request(self, method, url, data=None, content_type=None,
gcloud/storage/connection.py:    def _do_request(self, method, url, headers, data):
gcloud/storage/connection.py:    def api_request(self, method, path, query_params=None,
gcloud/storage/connection.py:    def get_bucket(self, bucket_name):
gcloud/storage/connection.py:    def create_bucket(self, …
```
> STORAGE: Making Connection.get_all_buckets a standalone method.

- gcloud/datastore/query.py
- gcloud/datastore/test_query.py
Also updating docstring in Query.fetch() to reflect this.
Partially addresses #704.
> Swapping the order of kind and dataset_id in Query constructor.

- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
This decouples Bucket.exists() from Connection.get_bucket().
@tseaver This came up when I was to [removing][1] `Connection.get_bucket()`. I opted to just use `connection.api_request` instead of dealing with the potential cycle caused by importing `storage.api` anywhere but `__init__`.
As it turns out (as I mention in #632), this is a way to reduce the response payload for checking existence (unfortunately, the headers still are  overwhelmingly verbose).
[1]: https://github.com/dhermes/gcloud-python/tree/storage-move-bucket-methods
> Using 'fields' in Bucket.exists().

- gcloud/storage/_helpers.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/test__helpers.py
- gcloud/storage/test_bucket.py
- regression/storage.py
~~**NOTE 1**: Has #683 as diffbase.~~
**NOTE 2**: There are many places here where the tests just give up and call `_reload_properties()`. This should not be. We should be clear on which methods should be just returning local data and which should make an HTTP request (e.g. update to `Bucket.get_logging()` here). (I also partially point out this type of problem in #683)
Also removing dead code:
- `_PropertyMixin.CUSTOM_PROPERTY_ACCESSORS` (and subclasses use of this)
- `_PropertyMixin._get_property` (only consumer of `CUSTOM_PROPERTY_ACCESSORS`)
> Removing HTTP request in _PropertyMixin.properties.

- gcloud/storage/_helpers.py
- gcloud/storage/bucket.py
- gcloud/storage/test__helpers.py
- gcloud/storage/test_blob.py
~~**NOTE**: Has #688 as diffbase.~~
Also updating `_PropertyBatch` to call patch on `__exit__`.
It seems removing `_patch_properties` outright is a possibility
> Moving Bucket._patch_properties (and patch) to _PropertyMixin.

- gcloud/storage/batch.py
- gcloud/storage/test_batch.py
- regression/storage.py
~~**NOTE**: Has #721 as diffbase.~~
Also removing last explicit use of the implicit connection in storage regression test.
> STORAGE: Allowing Batch() constructor to fall back to implicit.

- setup.py
@tseaver This is just in preparation for cutting a release tomorrow.
I am just going to start writing the release notes and hopefully we can get most of the pending PRs merged before we cut `0.4.3`.
----
Using last release PR (#678) as a template.
> Upgrading version to 0.4.3.

- docs/_components/storage-getting-started.rst
- docs/_components/storage-quickstart.rst
- docs/index.rst
- gcloud/storage/_helpers.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/demo/demo.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
Was not necessary, `Blob()` constructor suffices.
> Remove Bucket.new_blob

- docs/_components/storage-getting-started.rst
- gcloud/storage/__init__.py
- gcloud/storage/acl.py
- gcloud/storage/api.py
- gcloud/storage/batch.py
- gcloud/storage/bucket.py
- gcloud/storage/connection.py
- gcloud/storage/demo/__init__.py
- gcloud/storage/demo/demo.py
- gcloud/storage/test___init__.py
- gcloud/storage/test_api.py
- gcloud/storage/test_batch.py
- gcloud/storage/test_connection.py
Only needed for create_bucket() and get_all_buckets().
Fixes #726.
> STORAGE: Removing project from Connection.

- regression/storage.py
@tseaver Sorry for introducing this. I blame it on no free internet in my hotel in SLC.
> Fixing regression failure introduced in #725.

- gcloud/storage/__init__.py
- gcloud/storage/bucket.py
- gcloud/storage/test_acl.py
- gcloud/storage/test_bucket.py
- regression/storage.py
This is to allow Bucket('foo') in the implicit connection case, which we want to be an easy to use default for most.
> Making name= the first argument in Bucket() constructor.

- docs/conf.py
- docs/index.rst
- docs/pubsub-api.rst
- gcloud/pubsub/__init__.py
- gcloud/pubsub/api.py
- gcloud/pubsub/connection.py
- gcloud/pubsub/test_api.py
- gcloud/pubsub/test_connection.py
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
Following #691.
- Updates the API docs slightly (making batching explicit).
- Adds a connection lifted from `gcloud.storage.connection`.
- Adds `Topic` class and `list_topics` API function.
Does *not* handle implicit connection / project ID stuff (which should be shared, as called for in #741).
> Flesh out pubsub topics

- gcloud/pubsub/api.py
- gcloud/pubsub/subscription.py
- gcloud/pubsub/test_api.py
- gcloud/pubsub/test_subscription.py
> Flesh out pubsub subscriptions

- gcloud/_helpers.py
- gcloud/_testing.py
- gcloud/storage/__init__.py
- gcloud/storage/_implicit_environ.py
- gcloud/storage/api.py
- gcloud/storage/test__implicit_environ.py
- gcloud/storage/test_api.py
- gcloud/test__helpers.py
- regression/storage.py
> #741: hoist project detection/setup into 'gcloud._helpers'.

- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/test_blob.py
- regression/storage.py
This prevents unnecessary `reload_properties()` calls for objects which should already have all metadata loaded.
This was discussed a fair amount in #536 
Also, I made the 5MB file a 5.1MB file by appending random bytes. It turns out 5MB is the resumable [threshold][1] for `apitools` and being exactly 5MB didn't push us over it.
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/9c09ced326b9da55e40d3296b89cfd949b019ec4/_gcloud_vendor/apitools/base/py/transfer.py#L25
> Using copy and upload responses in storage.

- gcloud/datastore/demo/demo.py
- gcloud/demo.py
- gcloud/storage/demo/demo.py
~~Also removing license from datastore demo.~~
Also putting license below the fold (adding back to storage demo). This is so that the user sees the message
> You don't need to do anything, just keep hitting enter...
printed first.
@jgeewax Is it OK to remove the license from the `demo.py` files? Without the opening line (in the demo) of:
```python
```
it is unclear what to do next (e.g. if it starts with a giant glob of license text).
See my [previous comment][1] for some context.
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/716#issue-60879127
> Fixing demo runner: used to print empty newline at beginning of demo.

- gcloud/pubsub/connection.py
- gcloud/pubsub/test_connection.py
- regression/pubsub.py
- regression/run_regression.py
- scripts/run_regression.sh
> Begin pubsub regression suite

- gcloud/connection.py
- gcloud/credentials.py
- gcloud/datastore/test_connection.py
- gcloud/exceptions.py
- gcloud/storage/batch.py
- gcloud/storage/test_api.py
- gcloud/storage/test_batch.py
- gcloud/test_connection.py
- gcloud/test_credentials.py
- gcloud/test_exceptions.py
- regression/storage.py
- tox.ini
- Uses latest release of `oauth2client` which incorporates google/oauth2client#126
- Pulling from `HEAD` in `httplib2` until jcgregorio/httplib2#291 and jcgregorio/httplib2#296 are incorporated
- Updating bytes/unicode handling, mostly as in #724 
- Updating `storage.batch._unpack_batch_response` to straddle Py2/Py3. The email native `str` dependency is tricky there.
- Added some more tests to cover unicode/bytes branching in library code
- Updated regression for storage to explicitly use binary when `str` is insufficient in Py3
**NOTE**: As in google/oauth2client#126, using `%s` for a Py2 and Py3 codebase caused us issues in `_unpack_batch_response`
> Making regression3 pass

- gcloud/connection.py
- gcloud/credentials.py
- gcloud/datastore/test_connection.py
- gcloud/exceptions.py
- gcloud/storage/batch.py
- gcloud/storage/test_api.py
- gcloud/storage/test_batch.py
- gcloud/test_connection.py
- gcloud/test_credentials.py
- gcloud/test_exceptions.py
- regression/storage.py
- tox.ini
**NOTE**: Has #756 as diffbase. I'm happy to roll this into that PR if desired.
> Using correct format of exceptions from JSON based APIs.

- gcloud/storage/_helpers.py
- gcloud/storage/api.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/iterator.py
- gcloud/storage/test_api.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
**NOTE**: Has #759 as a diffbase.
This is an implementation detail intended to make internal code have an easier time constructing entities, but never had a story for end-users.
The only real changes are effectively:
```diff
-            yield Bucket(properties=item, connection=self._ctor_connection)
+            name = item.get('name')
+            bucket = Bucket(name, connection=self._ctor_connection)
+            bucket._properties = item
+            yield bucket
```
For test conveniences, I've allowed `_makeOne()` to delegate the `properties=` keyword in the way it used to be used in the actual constructors.
> Remove properties= from Blob and Bucket constructors

- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
> Adding Bucket.lifecycle_rules property to replace methods.

- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
Fixes #752.
I realize there was never any discussion in #752, but here is my argument for this:
> The constructors have a tiny memory footprint and make no HTTP request.
> Ditching lazy loading for ACLs attached to Blob/Bucket.

- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
@tseaver based on your [comment][1], this drops one of the non-`property` data access pairs. More importantly, it drops one of the internal users of `patch()`.
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/728#issuecomment-86621610
> Making cors a property instead of having two separate methods.

- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
> Removing HTTP requests from Bucket logging methods.

- gcloud/storage/__init__.py
- gcloud/storage/api.py
- gcloud/storage/batch.py
- gcloud/storage/test_api.py
- regression/storage.py
Allows fallback in this order:
- explicit connection
- current batch
- default connection
- raise exception
Also adding Batch.current() to determine the top batch in context.
Also making `storage.Batch` publicly visible (reduces number of imports).
This was peeled off from #759
> Adding storage.api._require_connection to allow fallback behavior.

- gcloud/storage/_helpers.py
- gcloud/storage/test__helpers.py
@tseaver This doesn't seem to be necessary any longer given the presence of `storage.Batch()` and the declarative nature of sending updates (e.g. `blob.patch()`)
> Removing _PropertyBatch from storage.

- gcloud/connection.py
- gcloud/datastore/batch.py
- gcloud/pubsub/api.py
- gcloud/pubsub/subscription.py
- gcloud/pubsub/topic.py
- gcloud/storage/_helpers.py
- gcloud/storage/acl.py
- gcloud/storage/blob.py
- gcloud/storage/test__helpers.py
- gcloud/storage/test_acl.py
Fixes #776.
Remaining uses of `return self` are in tests, __enter__ in
context managers and the _LazyProperty descriptor.
> Remove uses of 'return self' that don't return copies.

- gcloud/datastore/transaction.py
> Removing outdated Transaction.succeeded docs.

- gcloud/storage/_helpers.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/test__helpers.py
> Renaming _patch_properties->_patch_property and accepting key, value.

- gcloud/storage/_helpers.py
- gcloud/storage/test__helpers.py
> Making _PropertyMixin.patch() and reload() reset the changes.

- gcloud/datastore/helpers.py
- gcloud/datastore/test_helpers.py
@tseaver I just peeled off the part of #528 that determines the ID without using it anywhere.
I pinged
https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/59
to determine the necessity of this.
The real "bug" here is having to use `_prepare_key_for_request`.
> Adding one-time RPC to find unaliased / true dataset ID.

- gcloud/exceptions.py
- gcloud/storage/_helpers.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
Also replacing uses of dict.copy() (shallow) with copy.deepcopy().
> Making all Blob/Bucket getters fail gracefully if keys don't exist.

- gcloud/pubsub/__init__.py
- gcloud/pubsub/api.py
- gcloud/pubsub/subscription.py
- gcloud/pubsub/test_api.py
- gcloud/pubsub/test_subscription.py
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
- regression/pubsub.py
Includes regression tests for subscription creation, as well as fixes for bugs found via the regression tests.
See: #744
> #744: return Subscription instances from `pubsub.list_subscriptions()`

- regression/pubsub.py
Based on #794.
Publish one message to a topic and pull it via a subscription.
> #744: Add E2E regression test for message publication + pull

- docs/pubsub-surface.rst
- gcloud/pubsub/api.py
- gcloud/pubsub/message.py
- gcloud/pubsub/subscription.py
- gcloud/pubsub/test_message.py
- gcloud/pubsub/test_subscription.py
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
- regression/pubsub.py
Also, convert factory helper functions for topics and subscriptions into `from_api_repr` class methods.
> #744: Add 'pubsub.message.Message' class

- gcloud/pubsub/subscription.py
- gcloud/pubsub/test_subscription.py
Work around #799 (leaving open while @tmatsuo investigates).
(UPDATED by @dhermes when original commit was amended)
> Fix #799: Don't pass 'fields' query param to possibly non-existing subscription.

- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
- regression/pubsub.py
- Message payload must be bytes, base64ed, but then must be serializable to JSON.
- Likewise, 'attributes' values must be serializable to JSON.
> Fix regression3 failures in pubsub

- docs/_components/storage-getting-started.rst
- docs/_components/storage-quickstart.rst
- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
- regression/storage.py
Also adding page_token, projection and fields as arguments to the newly creating function (list_blobs).
This is "proposed" in #761. If there are issues we don't have to move forward with it.
> Combining get_all_blobs and Bucket.iterator.

- docs/_components/storage-getting-started.rst
- docs/_components/storage-quickstart.rst
- gcloud/storage/__init__.py
- gcloud/storage/api.py
- gcloud/storage/demo/__init__.py
- gcloud/storage/demo/demo.py
- gcloud/storage/test_api.py
- regression/storage.py
Also adding support for optional query parameters of `storage.buckets.list`.
Note this rename is "proposed" in #761. If there are issues we don't have to move forward with it.
Relates to #802.
> Renaming storage.get_all_buckets to storage.list_buckets.

- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
Note this was almost in #793 but dropped due to RFC3339 questions.
@craigcitro @thobrla can you vet an assumption for me? Will timestamps returned conform to
```python
_GOOGLE_TIMESTAMP_FORMAT = '%Y-%m-%dT%H:%M:%S.%fZ'
TIME_DELETED = '2014-11-05T20:34:37.000Z'
```
I ask because `'2014-11-05T20:34:37Z'` is also totally valid according to RFC3339 and I'm wondering if we can get away with using `datetime` alone (and not having to use the [`strict-rfc3339`][1] library for the full generality of RFC3339).
[1]: https://pypi.python.org/pypi/strict-rfc3339/
> Returning native datetime objects for Bucket/Blob time properties.

- gcloud/storage/blob.py
- gcloud/storage/test_blob.py
Fixes #546.
See #606 for old discussion. This was made possible by #811.
> Make storage upload/download have no chunk size by default.

- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
> Issue #797: support auto-adding timestamp to pubsub messages.

- gcloud/storage/_helpers.py
- gcloud/storage/api.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/iterator.py
Wraps setting/getting of object `_properties` in custom methods. This will allow centralized detection of a future in a response and will also allow replacing with the value on access if it is ready.
Towards #775 
----
@tseaver LMK what you think of this. The next step (I have yet to write it) is to make `Batch._do_request` return a future object. These objects will be owned and kept in order by the `Batch` and eventually populated. (This may be an issue because `JSONConnection.api_request` will try to parse the response if we use `expect_json=True`. We simultaneously want to parse the non-batched JSON responses and just ignore the futures)
> Preparing to use futures in storage.

- setup.py
- tox.ini
Release 0.9.1 of httplib2 has the fix required to make oauth2client actually work in Python 3.
> Using httplib2 from PyPI in regression3.

- gcloud/storage/test__helpers.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
> Removing superfluous HTTP requests in tests of local setters/getters.

- README.rst
- docs/index.rst
- gcloud/pubsub/test__implicit_environ.py
- gcloud/storage/__init__.py
- gcloud/storage/_implicit_environ.py
- gcloud/storage/api.py
- gcloud/storage/test___init__.py
- gcloud/storage/test__implicit_environ.py
- regression/storage.py
Also note that `gcloud/pubsub/test__implicit_environ.py` was testing a storage function, not a `pubsub` one ~~origin~~.
> Adding connection lazy loading in storage.

- gcloud/storage/test_api.py
> Fix #833 - Failing test due to querystring order.

- gcloud/storage/_helpers.py
- gcloud/storage/api.py
- gcloud/storage/blob.py
- gcloud/storage/test__helpers.py
- gcloud/storage/test_api.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
~~**NOTE**: Has #822 as diffbase.~~
Towards #728 
@tseaver I made a separate commit for each method with used `Blob.connection` but can combine them if you like.
I wanted to get rid of the `Blob.connection` property, but `_PropertyMixin.reload()` and `_PropertyMixin.patch()` use it as well as `ObjectACL.reload()` and `ObjectACL.save()`.
> Decouple connection from Blob

- gcloud/pubsub/message.py
- gcloud/pubsub/test_message.py
- regression/pubsub.py
Based on #809.
Allows subscribers of timestamping topics to sort messages.
> #797:  Add sortable message timestamp

- gcloud/_helpers.py
- gcloud/pubsub/message.py
- gcloud/pubsub/test_message.py
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
Use consistently across `storage` and `pubsub`.
Fixes #818.
~~Uses #816 as a diffbase.~~
> #818: unify RFC 3339 timestamp format strubg

- docs/index.rst
- docs/pubsub-usage.rst
- Rename to `pubsub-usage`.
- Update title to "Using the API".
Fixes #828.
> #828: Clarify nature of `pubsub-surface` document.

- docs/pubsub-usage.rst
- gcloud/pubsub/__init__.py
Uses #847 as a base.
Per #827.
@jgeewax, PTAL (particuarly at 4e1d2c9).
> #827: Use short form imports in pubsub docs

- docs/pubsub-usage.rst
- gcloud/test__helpers.py
- regression/pubsub.py
- regression/regression_utils.py
- regression/run_regression.py
Also, rename `regression_utils.get_environ` -> `check_environ`, and drop return value (which only caller was ignoring).
> For consistency, replace all use of `project_id` w/ `project`.

- gcloud/storage/api.py
- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
Towards #728 and #825 
Still left using `Bucket.connection` is `Bucket.list_blobs` (since the `_BlobIterator` constructor needs to be changed for that). Still using an attached connection is `Bucket.make_public`, but I wasn't sure how to attack it.
As in other cases all the double-under methods have to fall back to implicit as their only option.
> Removing most remaining uses of self.connection in Bucket

- setup.py
- tox.ini
Works around https://github.com/google/protobuf/issues/333.
> Pin 'protobuf==3.0.0-alpha-1'.

- gcloud/storage/blob.py
- gcloud/storage/test_blob.py
See #825.
Needs #843 as a base ('Bucket.copy_blob' and 'Bucket.delete_blob' must also take optional 'connection').
> #825: Allow passing explicit connection to 'Blob.{rename,delete}'.

- gcloud/storage/_helpers.py
- gcloud/storage/api.py
- gcloud/storage/test__helpers.py
> #825: Allow passing explicit connection to '_PropertyMixin.{reload,patch}'.

- gcloud/connection.py
- gcloud/storage/_helpers.py
- gcloud/storage/batch.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/test__helpers.py
- gcloud/storage/test_batch.py
- gcloud/storage/test_bucket.py
- gcloud/test_connection.py
~~Has #810 as diffbase.~~
@tseaver Note this does not support the `Iterator` subclasses, but I have tested with a fair amount of other requests.
It **does** enable `GET` requests, but does so in a somewhat incomplete way.
The main issues are
1.  In `Iterator.get_next_page_response`
```python
self.next_page_token = response.get('nextPageToken')
```
fails when `response` is a `_Future`
1.  In `_BucketIterator.get_items_from_response`
```python
for item in response.get('items', []):
```
fails when `response` is a `_Future`
The first is easy to deal with (e.g. `hasattr(response, 'get')`) but the second is not as easy because we need to start an ~~and~~ iterator before knowing what will end up in the response.
> Using futures in batched requests

- gcloud/storage/acl.py
- gcloud/storage/test_acl.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
> #825: Allow passing explicit connection to `ACL.{reload,save}`

- gcloud/pubsub/_implicit_environ.py
- gcloud/pubsub/api.py
- gcloud/pubsub/subscription.py
- gcloud/pubsub/test__implicit_environ.py
- gcloud/pubsub/test_subscription.py
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
> #825: Allow passing explicit connection to pubsub API methods

- gcloud/storage/blob.py
- gcloud/storage/test_blob.py
Requires #853 as a base.
See #825.
> #825:  Allow passing explicit connection to 'Blob.make_public'

- gcloud/storage/api.py
- gcloud/storage/blob.py
Also returning the _BucketIterator directly in
storage.api.list_buckets() rather than wrapping it in iter().
@tseaver As mentioned https://github.com/GoogleCloudPlatform/gcloud-python/pull/812#issuecomment-99170688 I said I'd fix `Blob.exists()` while making sure the iterators didn't work in batches.
It turns out they were already not working. Here is a working get request
```python
>>> from gcloud import _helpers
>>> from gcloud import storage
>>> 
>>> _helpers._PROJECT_ENV_VAR_NAME = 'GCLOUD_TESTS_PROJECT_ID'
>>> storage.set_defaults()
>>>
>>> with storage.Batch() as batch:
...     bucket = storage.get_bucket('bucket-name')
...     print bucket._properties
... 
<gcloud.storage.batch._FutureDict object at 0x7f7ce19f4a10>
>>> bucket._properties
{u'kind': u'storage#bucket', u'name': …
```
> Making Blob.exists() work as Bucket.exists().

- gcloud/storage/blob.py
- gcloud/storage/test_blob.py
commondatastorage.googleapis.com has long been out of use.
> Using storage.googleapis.com in public URL.

- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
> #825: Allow passing explicit connection to 'Bucket.{list_blobs,make public}'

- gcloud/storage/blob.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
> Remove 'Blob.connection' property.

- tox.ini
~~Just a test PR for #874~~
Fixes #874. As of tox 2.0, no environment variables are passed through by default.
> Adding passenv to tox.ini.

- gcloud/storage/__init__.py
- gcloud/storage/api.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/test___init__.py
- gcloud/storage/test_api.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
- regression/storage.py
Uses #873 as a diffbase.
Also, remove `Bucket.__iter__` and `Bucket.__contains__`, as they provide no means of passing an explicit connection.
See #825.
> Remove 'Bucket.connection' property

- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
> Really remove 'Bucket._connection' bits.

- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
Applying the same limit for number of blobs to iterate through
that Bucket.delete(force=True) has.
> Limiting Bucket.make_public(recursive=True).

- gcloud/storage/test_bucket.py
Caused by #878 and #879 passing by each other simultaneously.
> Fixing broken bucket test (using connection).

- _landing-page-static/css/main.css
Adds more padding around the code snippet on the landing page.
> Updated padding of code snippet on landing page.

- gcloud/connection.py
- gcloud/datastore/__init__.py
- gcloud/datastore/_implicit_environ.py
- gcloud/datastore/connection.py
- gcloud/datastore/test__implicit_environ.py
- gcloud/datastore/test_connection.py
- gcloud/pubsub/__init__.py
- gcloud/pubsub/connection.py
- gcloud/storage/__init__.py
- gcloud/storage/_implicit_environ.py
- gcloud/storage/connection.py
- gcloud/test_connection.py
- gcloud/test_credentials.py
This also obsoletes get_scoped_connection() so it is removed.
FYI @jgeewax thanks for nudging in this direction. It moves the scope adding behavior into the `Connection` constructors.
> Adding scope to credentials in Connection constructors.

- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
Both are "sugar" over other methods, but do not allow passing an explicit connection.
In addition, `Bucket.__iter__` has scaling issues, which cannot be mitigated using the filtering parameters accepted by `Bucket.list_blobs`.
Moved to a new PR from #876.
> Remove 'Bucket.__iter__' and 'Bucket.__contains__'.

- gcloud/connection.py
- gcloud/datastore/_implicit_environ.py
- gcloud/pubsub/__init__.py
- gcloud/storage/_implicit_environ.py
- gcloud/test_connection.py
This allows us to load a Connection and a set of credentials simultaneously.
~~**NOTE**: Has #840 as diffbase.~~
> Adding Connection factories for credentials.

- docs/datastore-api.rst
- docs/pubsub-api.rst
- docs/storage-api.rst
- gcloud/datastore/__init__.py
- Drop the `__init__` from them.
- Include the ones imported from `_implicit_environ'`
Fixes #845.
> Improve autodocs for top-level package names.

- docs/index.rst
This just moves the heading under the right section. Not 100% certain if this is the best way to do it, let me know if it looks wrong...
> Fix #890 - Move PubSub usage doc under the right heading.

- docs/pubsub-usage.rst
Explicit paging is required for scalability.
> Fix up pubsub API docs to show returned 'next_page_token'.

- gcloud/datastore/__init__.py
- gcloud/datastore/api.py
- gcloud/datastore/connection.py
- gcloud/datastore/dataset.py
- gcloud/datastore/demo/demo.py
- gcloud/datastore/test_api.py
- gcloud/datastore/test_dataset.py
- regression/datastore.py
Makes distinction between an iterable of keys and a single
key for get requests and re-purposes the get() name for the
single key case.
Fixes #701.
> Implementing get_multi in datastore.

- docs/_components/datastore-getting-started.rst
- docs/_components/datastore-quickstart.rst
- docs/index.rst
- gcloud/datastore/__init__.py
- gcloud/datastore/api.py
- gcloud/datastore/dataset.py
- gcloud/datastore/demo/demo.py
- gcloud/datastore/entity.py
- gcloud/datastore/test_api.py
- gcloud/datastore/test_dataset.py
- gcloud/datastore/transaction.py
- regression/clear_datastore.py
- regression/datastore.py
> Making put/delete_multi in datastore.

- gcloud/_helpers.py
- gcloud/datastore/entity.py
- gcloud/datastore/query.py
- gcloud/datastore/test_entity.py
- gcloud/datastore/test_query.py
- gcloud/test__helpers.py
This is due to repeated reports of issues using a string by mistake (which is an iterable), so we'd get
```python
'foobar' --> ['f', 'o', 'o', 'b', 'a', 'r']
```
Ensuring query constructor args are correct types.
Check exclude from indexes type in Entity ctor.
Fixes #819 and #887 
> Only allowing tuple or list for ctor inputs which assume a sequence

- gcloud/pubsub/subscription.py
- gcloud/pubsub/test_subscription.py
> #899: Harden 'Subscription.pull' against missing 'receivedMessages' in response

- gcloud/datastore/batch.py
- gcloud/datastore/connection.py
- gcloud/datastore/test_api.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_transaction.py
> #903: Ensure transaction ID is passed through to connection during commit.

- gcloud/datastore/query.py
- gcloud/datastore/test_query.py
Also checking in `Query` constructor that all the filters are valid.
Fixes #917.
----
@pcostell Can you verify that key inequality filters work? (The docs clearly state they do, just want to be careful.) This has been in the codebase longer than I've been working on the project, so maybe it was introduced before inequality filters were allowed?
> Removing datastore key query filter restriction.

- gcloud/storage/blob.py
- gcloud/storage/test_blob.py
In storage, file upload will now fail if no size is passed in and if the file object does not have a fileno
which can be stat'ed.
Fixes #900.
> Makes checking fstat for file optional.

- README.rst
Hey, guys!
RE: https://github.com/GoogleCloudPlatform/gcloud-node/issues/637
@jgeewax thinks it makes more sense to point the Service links (Google Cloud Datastore and Google Cloud Storage) to their respective sections in the readme.
> readme: point service links to readme intro documentation

- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
- regression/storage.py
Also making some bucket tests use explicit arguments instead of monkey patching implicit settings.
Fixes #920.
> Making _BlobIterator accumulate prefixes.

- scripts/cover.sh
- tox.ini
> Removing cover-min-percentage=100 from coveralls.

- gcloud/iterator.py
- gcloud/storage/api.py
- gcloud/storage/bucket.py
- gcloud/test_iterator.py
> Moving storage iterator into core modules.

- gcloud/datastore/dataset.py
- gcloud/datastore/test_dataset.py
This does not add support for namespace in `_implicit_environ`.
Related to #902.
----
As a result of #861 we will likely be removing `_implicit_environ` which makes this the actual resolution of #902.
> Adding namespace to dataset class.

- docs/storage-api.rst
Error was introduced in #941 mistakenly.
> Removing non-existent storage module from autodocs.

- gcloud/credentials.py
- gcloud/test_credentials.py
Also refactoring `_get_signed_query_params` and the related tests so that the signing process and service account name determination are isolated methods.
Fixes #607.
> Adding ability to sign URL from GAE.

- docs/datastore-client.rst
- docs/index.rst
- gcloud/datastore/__init__.py
- gcloud/datastore/client.py
- gcloud/datastore/test_client.py
> Rename 'dataset.Dataset' -> 'client.Client'.

- gcloud/connection.py
- gcloud/credentials.py
- gcloud/datastore/_implicit_environ.py
- gcloud/datastore/batch.py
- gcloud/datastore/connection.py
- gcloud/datastore/key.py
- gcloud/iterator.py
- gcloud/pubsub/message.py
- gcloud/pubsub/topic.py
- gcloud/storage/_helpers.py
- gcloud/storage/_implicit_environ.py
- gcloud/storage/acl.py
- gcloud/storage/api.py
- gcloud/storage/batch.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- pylintrc_default
- run_pylint.py
- tox.ini
Also
- Updated docstrings which don't pass / are invalid.
- Integrated plugin with `tox lint` rule and `run_pylint`.
- Fixed a `elif _GAECreds is not None and isinstance(credentials, _GAECreds):` in `gcloud.credentials._get_service_account_name`.
For now, pulling directly from the mercurial source repository to get the `check_docs` pylint extension. The maintainer mentioned this will be released July 15-17, 2015.
See:
http://www.bitbucket.org/logilab/pylint/pull-request/143/
> Adding Pylint plugin to check Sphinx docstrings.

- docs/pubsub-usage.rst
- gcloud/pubsub/_helpers.py
- gcloud/pubsub/subscription.py
- gcloud/pubsub/test__helpers.py
- gcloud/pubsub/test_subscription.py
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
- system_tests/pubsub.py
Also using `topic.subscription` factory in docs and regression
tests instead of instantiating a `Subscription`.
Fixes #912.
> Implementing `topic.subscription` factory.

- gcloud/datastore/client.py
- gcloud/datastore/test_client.py
> Move implicit majyk inside 'Client.__init__'.

- tox.ini
Without it, the `master` docs just show the last version rather than the last commit.
See #880 for context.
> Adding passenv for tox -e docs.

- gcloud/client.py
- gcloud/connection.py
- gcloud/pubsub/client.py
- gcloud/pubsub/test_client.py
- gcloud/test_client.py
This is pre-work in #952, but came up in #933 as well.
> Adding base client class in core.

- tox.ini
Caused by merging a rename commit (#954) and a change to
tox before the rename (#951).
> Fixing broken tox.ini

- gcloud/connection.py
- gcloud/exceptions.py
@jgeewax Taking #938 over since it lingered.
@tseaver I rebased and will shortly send another commit addressing review feedback.
> Fixes #937 - Adds HTTP method and URL to exceptions.

- tox.ini
Once a release comes out, will just use that version
From:
https://bitbucket.org/logilab/pylint/pull-request/143/
"My plan is to have 1.5 released on 15-17 july."
Fixes #968.
> Tagging pylint at working pre-release commit.

- gcloud/datastore/client.py
- gcloud/datastore/test_client.py
> Update 'Client' to hold stack of connection/batch/transaction objects.

- gcloud/datastore/batch.py
- gcloud/datastore/client.py
- gcloud/datastore/query.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_query.py
- gcloud/datastore/test_transaction.py
- gcloud/datastore/transaction.py
Update batch/transaction to push themselves onto client's stack, rather
than batches.
Updated API-invoking methods to take 'client', rather than 'connection',
falling back to the client held by self.
See #944.
> Update batch/transaction/query to hold client.

- system_tests/clear_datastore.py
- system_tests/populate_datastore.py
This were broken by the change to clients from implicit behavior.
Probably should wait until #944 is in, but I had to reload the data (got mucked up somehow) for the system tests.
> Fix datastore test plumbing modules.

- gcloud/storage/_helpers.py
- gcloud/storage/acl.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/client.py
- gcloud/storage/test__helpers.py
- gcloud/storage/test_acl.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
- system_tests/storage.py
Towards #952.
Did this for all but `Bucket.create` (since it also requires a project, built for just a `client`)
Will continue to remove `connection` from the `Bucket` and `Batch` constructors in forthcoming PR.
> Replace optional connection with client in storage methods and functions.

- gcloud/credentials.py
- gcloud/storage/blob.py
> Documenting exclusion of GCE for generate_signed_url.

- gcloud/storage/__init__.py
- gcloud/storage/batch.py
- gcloud/storage/bucket.py
- gcloud/storage/client.py
- gcloud/storage/test_batch.py
- gcloud/storage/test_bucket.py
- system_tests/storage.py
Has #984 as diffbase.
Also updating storage.Batch to accept a client.
Introduced temporary hack to allow system-tests to continue passing. Implicit environment has still not been completely removed.
> Replace connection in bucket constructor.

- gcloud/storage/blob.py
`tox -e docs` broken in merge of #993.
@dhermes PTAL:  I'd like to merge ASAP.
> Fix broken docstring indentation.

- gcloud/iterator.py
- gcloud/storage/bucket.py
- gcloud/storage/client.py
- gcloud/storage/test_bucket.py
- gcloud/storage/test_client.py
- gcloud/test_iterator.py
> Making iterators accept client instead of connection.

- docs/bigquery-usage.rst
> Add DX docs for managing datasets

- gcloud/datastore/client.py
- gcloud/storage/batch.py
- gcloud/storage/blob.py
- gcloud/storage/client.py
- gcloud/storage/test_batch.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_client.py
- system_tests/storage.py
> Change LocalStack of batches from global to client-local in storage

- gcloud/storage/_helpers.py
- gcloud/storage/acl.py
- gcloud/storage/test__helpers.py
- gcloud/storage/test_acl.py
- gcloud/storage/test_batch.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
> Fixing outdated storage test names and test cases.

- setup.py
Using last release PR (#907) as a template.
> Upgrading version to 0.7

- README.rst
- docs/_components/storage-getting-started.rst
- docs/index.rst
- gcloud/storage/__init__.py
- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
- system_tests/storage.py
Redundant since these are already defined on Blob.
@tseaver @jgeewax This doesn't have to be merged, just trying to adhere to PEP20 / `import this`:
> There should be one-- and preferably only one --obvious way to do it.
> Removing redundant Bucket.upload* methods.

- scripts/pep8_on_repo.sh
- tox.ini
I always end up having local Python files lying around that make `pep8` unhappy.
> Making tox lint target ignore files outside the git repo.

- gcloud/datastore/client.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_connection.py
> Refresh #955:  make datastore.Client derive from base client.

- README.rst
- docs/_components/storage-getting-started.rst
- docs/_components/storage-quickstart.rst
- docs/index.rst
- gcloud/storage/__init__.py
- gcloud/storage/bucket.py
- gcloud/storage/client.py
- gcloud/storage/demo/demo.py
- gcloud/storage/test_bucket.py
- gcloud/storage/test_client.py
- system_tests/storage.py
This includes
- `Bucket<--Client` (bucket owned by client)
- `Batch<--Client`
- `Blob<--Bucket`
I refrained from implementing factories for
- `BucketACL<--Bucket`
- `ObjectACL<--Blob`
> Adding storage factories for owned objects.

- gcloud/datastore/query.py
> Documenting Iterator constructor in datastore.

- docs/bigquery-usage.rst
Note:  this doc does not address loading / retrieving table data.
Uses #1000 as a base.
> Add usage docs for table management.

- gcloud/storage/bucket.py
Fixes #997.
@tseaver LMK if you think I should do a comprehensive search of `@property`s to see if there are other readability issues.
> Moving Bucket.client property closer to constructor.

- gcloud/_environment_vars.py
- gcloud/_helpers.py
- gcloud/datastore/client.py
- gcloud/datastore/connection.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_connection.py
- gcloud/environment_vars.py
- gcloud/test__helpers.py
- system_tests/__init__.py
- system_tests/clear_datastore.py
- system_tests/datastore.py
- system_tests/local_test_setup.sample
- system_tests/populate_datastore.py
- system_tests/pubsub.py
- system_tests/run_system_test.py
- system_tests/storage.py
- system_tests/system_test_utils.py
This is so we can give a quick overview of all environment variables used.
Inspired by the `gcloud-*` wide discussion of env. vars. I'm not sure if this is worth doing, so @tseaver feel free to shoot this down.
/cc @jgeewax
> Bringing all environment variables into a single place.

- tox.ini
This is to make it so that we have continued support of pylint upstream (hopefully they cut a release soon).
They mentioned that they'd cut a release around July 17 on the PR that added support for docstring checking.
@tseaver FYI after we merge you should rebase your PRs on top of this.
> Manually pinning logilab-common<=0.63.0.

- gcloud/client.py
- gcloud/storage/test_client.py
- gcloud/test_client.py
See https://github.com/GoogleCloudPlatform/gcloud-python/pull/1018#discussion_r35562516
> Defend against non-string 'project' passed to 'JSONClient()'.

- gcloud/bigquery/__init__.py
- gcloud/bigquery/client.py
- gcloud/bigquery/dataset.py
- gcloud/bigquery/test_client.py
- gcloud/bigquery/test_dataset.py
> Implement 'bigquery.dataset.Dataset'.

- docs/bigquery-usage.rst
- gcloud/bigquery/__init__.py
- gcloud/pubsub/__init__.py
> Add examples for browsing / copying / exporting table data.

- gcloud/bigquery/_helpers.py
- gcloud/bigquery/dataset.py
- gcloud/bigquery/table.py
- gcloud/bigquery/test__helpers.py
- gcloud/bigquery/test_table.py
Support missing for:
- `schema` (next PR)
- `externalDataConfiguration` (experimental feature, deferring for now).
> BQ Tables:  ctor, scalar property definitions

- README.rst
- scripts/update_docs.sh
- scripts/versions.html.template
We've noticed that "latest" is expected to be the TIP rather than the latest stable release.
As described by READTHEDOCS:
https://docs.readthedocs.org/en/latest/versions.html
latest should indeed refer to TIP and instead of using latest for the last release, use "stable".
NOTE: This can't be merged until the docs are renamed in gh-pages branch. PR forthcoming.
> Switching to readthedocs naming conventions.

- gcloud/bigquery/table.py
- gcloud/bigquery/test__helpers.py
- gcloud/bigquery/test_table.py
> Bigquery: add table schemas

- docs/_static/css/main.css
- docs/_static/js/main.js
- docs/_templates/layout.html
- docs/conf.py
- docs/index.rst
- tox.ini
Using caption with different toc sections instead of JS/CSS hack.
This fits within the Sphinx construct and would allow our docs to be built on readthedocs.org.
----
Building with `tox -e docs` we get:
----
Building with `LOCAL_RTD=True tox -e docs` we get:
AFAICT, by using `:titlesonly:` and some other rules we can get rid of the expandable sections (or just not use h1, or change maxdepth).
> Using caption with different toc sections instead of JS/CSS hack.

- docs/conf.py
This was preventing readthedocs.org from using the latest theme.
See #1025 for some context.
> Removing classic theme from Sphinx conf.

- gcloud/bigquery/dataset.py
- gcloud/bigquery/table.py
- gcloud/bigquery/test_dataset.py
- gcloud/bigquery/test_table.py
> Bigquery table api methods

- docs/_templates/layout.html
> Drops unnecessary "Python" title in docs.

- gcloud/bigquery/table.py
- gcloud/bigquery/test_table.py
- Add `Table.insert_all()` and `Table.data` for synchronous load / browse.
- Ensure that `Table.schema` is re-populated from server responses.
> Add tabledata API methods

- docs/conf.py
~~**NOTE**: Has #1035 as base.~~
> Add intersphinx for docs linking.

- system_tests/run_system_test.py
- system_tests/system_test_utils.py
Preparatory to adding system tests for `gcloud.bigquery`.
> Generalize requirements check for system tests.

- gcloud/_helpers.py
- gcloud/bigquery/_helpers.py
- gcloud/bigquery/test__helpers.py
- gcloud/bigquery/test_dataset.py
- gcloud/bigquery/test_table.py
- gcloud/credentials.py
- gcloud/datastore/helpers.py
- gcloud/datastore/test_helpers.py
- gcloud/pubsub/message.py
- gcloud/pubsub/test_message.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
- gcloud/test__helpers.py
- gcloud/test_credentials.py
- setup.py
- system_tests/datastore.py
This was inspired by #1009.
Our methods for signing strings with credentials / crypto will likely be moved into `oauth2client`, so this is a pre-emptive move to avoid having `pytz` as a dependency for `oauth2client`.
As an added benefit, we avoid having `pytz` as a dependency, which helps for people wanting to use `gcloud-python` on App Engine.
/cc @nathanielmanistaatgoogle
> Removing use of pytz module / implementing our own UTC.

- gcloud/bigquery/__init__.py
- gcloud/bigquery/client.py
- gcloud/bigquery/dataset.py
- gcloud/bigquery/table.py
- gcloud/bigquery/test_client.py
- gcloud/bigquery/test_dataset.py
- gcloud/bigquery/test_table.py
- Add missing top-level convenience imports
- Add missing `Client.list_datasets` and `Dataset.list_tables` methods.
> Flesh out bigquery API

- gcloud/bigquery/dataset.py
- gcloud/bigquery/test_dataset.py
~~Uses #1045 as a base.~~
- Adds `Dataset.access_grants` property.
- Marshals values to/from that property in `Dataset` API requests/responses.
> Add Dataset access support

- gcloud/datastore/demo/__init__.py
- gcloud/datastore/demo/demo.py
- gcloud/storage/demo/__init__.py
Fixes #1048.
Also making a tiny tweak to the storage demo (to use our env vars module).
> Updating datastore demo for client pattern.

- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/storage/test_blob.py
- gcloud/storage/test_bucket.py
This is to fit the pattern already in place for Bucket.copy_blob. The philosophy being to treat copy and rename as operations associated with the container (Bucket) rather than with the object itself (Blob).
Fixes #1007.
> Moving rename() from Blob to Bucket.

- scripts/run_system_tests.sh
- system_tests/bigquery.py
- system_tests/run_system_test.py
> Initial BQ system tests

- setup.py
@tseaver Are we close enough on BQ to release this?
> Upgrading version to 0.7.1.

- gcloud/datastore/query.py
- gcloud/datastore/test_query.py
> #1054: Set query cursor to 'None' when returned as empty string.

- system_tests/datastore.py
This intentionally forces data contention in a transaction (by updating the entity outside of the transaction).
This is to prevent regressions like #903.
> Adding system test for datastore failed transactions.

- docs/conf.py
The previous one has been taken out of commision.
See google/oauth2client#249 for the removal and http://google.github.io/oauth2client/ for evidence of the removal.
> Updating oauth2client intersphinx link.

- docs/_templates/layout.html
- docs/index.rst
This is to bring the readthedocs version and custom layout closer together. (Maybe they can converge?)
Before:
After:
> Putting external links in toctree.

- gcloud/bigquery/client.py
- gcloud/bigquery/job.py
- gcloud/bigquery/table.py
- gcloud/bigquery/test_client.py
- gcloud/bigquery/test_job.py
- gcloud/bigquery/test_table.py
- system_tests/bigquery.py
Add support for jobs loading table data from CloudStorage files.
> Jobs: load from storage

- gcloud/bigquery/client.py
- gcloud/bigquery/job.py
- gcloud/bigquery/test_client.py
- gcloud/bigquery/test_job.py
> Add job for extracting tables to CloudStorage

- system_tests/bigquery.py
> #1071: fix BQ system tests under Py3k

- gcloud/bigquery/job.py
- gcloud/bigquery/test_job.py
Addresses point `#3` of:
https://github.com/GoogleCloudPlatform/gcloud-python/pull/1072#issuecomment-132682862
> Replace validating property boilerplate w/ custom descriptors.

- README.rst
Fixes #1076.
See it staged at https://github.com/dhermes/gcloud-python/blob/fix-1076/README.rst
> Adding BigQuery and Pub/Sub to README.

- CONTRIBUTING.rst
- Adding note about potential drop of 2.6
- Making it clear that Python 3.3/3.4 are fully supported
- Adding note about absolute links in README
- Adding instruction on building for RTD
> Updating CONTRIBUTING.

- docs/gcloud-auth.rst
- docs/index.rst
@jgeewax This is the simple start I mentioned to get #805 and #830 in slowly but surely.
> Basic beginning of authentication module.

- docs/gcloud-auth.rst
@jgeewax Here is a little more auth (towards #805 and #830)
To view my and your original PRs (as we go), here are some hosted files:
www.googledrive.com/host/0B8el7dRo8mVOUVlkSEJKN3pQdkk (dhermes)
www.googledrive.com/host/0B8el7dRo8mVOOHE4NzFXSmhHUWs (jgeewax)
> Add basic discussion of clients to auth doc.

- docs/gcloud-auth.rst
Also adding subsection (`<h3>`) headers within the material about clients.
@jgeewax Here is a little more auth (towards #805 and #830)
To view my and your original PRs (as we go), here are some hosted files:
www.googledrive.com/host/0B8el7dRo8mVOUVlkSEJKN3pQdkk (dhermes)
www.googledrive.com/host/0B8el7dRo8mVOOHE4NzFXSmhHUWs (jgeewax)
> Adding section about order used for app. default creds.

- index.html
> Updating landing page to use datastore client.

- docs/index.rst
> Updating index.rst to use datastore client.

- docs/gcloud-auth.rst
Also moving the `from_service_account_*` factory descriptions into the newly added sections.
@jgeewax The only thing I plan on adding after this is
- Short snippet about how to get a JSON / P12 keyfile
- Short tip about scopes in GCE
- "Advanced Customization" section about using a custom implementation for auth (see https://github.com/GoogleCloudPlatform/gcloud-python/issues/908#issuecomment-110811556 as an example)
----
As before (towards #805 and #830)
To view my and your original PRs (as we go), here are some hosted files:
www.googledrive.com/host/0B8el7dRo8mVOUVlkSEJKN3pQdkk (dhermes)
www.googledrive.com/host/0B8el7dRo8mVOOHE4NzFXSmhHUWs (jgeewax)
> Describing how to create credentials explicitly in auth doc.

- docs/index.rst
- docs/resource-manager-api.rst
- docs/resource-manager-client.rst
- docs/resource-manager-project.rst
- gcloud/resource_manager/__init__.py
- gcloud/resource_manager/client.py
- gcloud/resource_manager/connection.py
- gcloud/resource_manager/project.py
- gcloud/resource_manager/test_client.py
- gcloud/resource_manager/test_connection.py
- gcloud/resource_manager/test_project.py
FYI @jgeewax this is "reclaimed" from #933.
@tseaver We can either review as-is or I can break off each commit as a PR.
I'm unclear how we can run system tests on Travis since they require a user account. We could always create a fake Google user account, but that may be frowned upon. For the `oauth2client` system tests, there is just a refresh token for my personal GMail account (only scope on there is `email`).
> Implementing resource manager API

- docs/gcloud-auth.rst
Starting out with section about downloading keyfiles, borrowed from gcloud-common:
https://github.com/GoogleCloudPlatform/gcloud-common/blob/master/authorization/readme.md
@jgeewax Still to come is another subsection in troubleshooting about GCE auth/scopes and then an "Advanced Customization" section about using custom `http` objects (not from `oauth2client`).
> Adding troubleshooting to auth doc.

- scripts/cover.sh
- tox.ini
We realized we didn't need xcover recently in a PR over on oauth2client.
H/T to @jonparrott
> Using standard nose coverage instead of xcover.

- gcloud/bigquery/__init__.py
- gcloud/bigquery/connection.py
- gcloud/connection.py
- gcloud/datastore/__init__.py
- gcloud/datastore/connection.py
- gcloud/pubsub/__init__.py
- gcloud/pubsub/connection.py
- gcloud/resource_manager/__init__.py
- gcloud/resource_manager/connection.py
- gcloud/storage/__init__.py
- gcloud/storage/connection.py
- gcloud/test_connection.py
Every package's subclass calls this method, so we just moved it to the parent.
Fixes #974.
> Moving self._create_scoped_credentials call to base Connection.__init__.

- docs/_templates/layout.html
This PR updates the links to gcloud-java (from the docs pages) to reflect gcloud-java's shorter URL.
After a build, the link from the docs pages will look like this (see bottom of screenshot):
> Update link to gcloud-java's landing page

- index.html
The link to gcloud-java's landing page has been shortened, and the longer URL will be removed (after all references to it are removed).  This PR shortens the link on the landing page.  
Note: links to gcloud-java in the docs pages in the "latest" folder haven't been updated.  Can these can be updated by rebuilding the docs (once the link is updated in `master`)?
You can see the updated link at the bottom of this screenshot:
> Shorten the link to gcloud-java from the landing page

- docs/gcloud-auth.rst
Mostly borrowed from gcloud-common:
https://github.com/GoogleCloudPlatform/gcloud-common/blob/04a8ecd48b5bfb48b1264cf5cd74f6de7e767aab/authorization/readme.md
with some updates for missing scopes.
@jgeewax Still to come is an "Advanced Customization" section about using custom `http` objects (not from `oauth2client`).
> Adding a "Using GCE" section to auth troubleshooting.

- gcloud/storage/test_batch.py
Noticed this while documenting the httplib2.Http.request() interface and our use of it
> Change order of arguments in mock http.request.

- docs/gcloud-auth.rst
> Adding "Advanced Customization" section to auth doc.

- CONTRIBUTING.rst
- README.rst
TO do this, moving Semantic Versioning section to CONTRIBUTING document and removing the majority of the Python Versions section. The remaining parts were moved up to the Quick Start section.
Fixes #591.
----
See the rendered updates:
https://github.com/dhermes/gcloud-python/blob/update-readme/CONTRIBUTING.rst
https://github.com/dhermes/gcloud-python/blob/update-readme/README.rst
> Updating README to match gcloud-node.

- gcloud/test_credentials.py
Works around: https://github.com/google/oauth2client/issues/302
> Add 'webapp2' alias for 'google.appengine.ext.webapp'.

- _testing/grpc/__init__.py
- _testing/grpc/_adapter/__init__.py
- _testing/grpc/_adapter/_c.py
- _testing/grpc/early_adopter/__init__.py
- _testing/grpc/early_adopter/implementations.py
- _testing/grpc/framework/__init__.py
- _testing/grpc/framework/alpha/__init__.py
- _testing/grpc/framework/alpha/utilities.py
- gcloud/bigtable/__init__.py
- tox.ini
Initial commit just adds the basic import time check for gRPC and testing for all possible install states. It also adds a shadowed _testing/grpc that we can use to mock the installed library for tests.
----
We can discuss alternatives to mocking out `grpc` imports in dhermes/gcloud-python-bigtable#10 or right here. As far as I know, there is no way to globally (i.e. between / before modules) step in front of `__import__` without doing some serious engineering.
----
@nathanielmanistaatgoogle Any better ideas than this one for allowing unit tests that "depend" on grpc to run? (None of the gRPC code is ever called in unit tests, just in system tests. Though the gRPC objects get mocked out, the imports need to work so `nose` doesn't get angry.)
> Adding gcloud.bigtable package.

- system_tests/bigquery.py
Addresses https://github.com/GoogleCloudPlatform/gcloud-python/issues/1104#issuecomment-136493628
> Use a unique dataset ID for each run of BQ system tests.

- gcloud/bigquery/table.py
- gcloud/bigquery/test_table.py
> Fix conversion of backend-generated timestamps

- gcloud/dns/__init__.py
- gcloud/dns/client.py
- gcloud/dns/test_client.py
- gcloud/dns/test_zone.py
- gcloud/dns/zone.py
> Add 'ManagedZone' and related support

- docs/gcloud-api.rst
- gcloud/bigtable/client.py
- gcloud/bigtable/test_client.py
- gcloud/client.py
- gcloud/test_client.py
FYI @tseaver I am essentially done with the package in https://github.com/dhermes/gcloud-python-bigtable so will now be porting over the code in (hopefully) easy to review chunks.
I'd really like to get this all in by the end of September (end of the quarter).
/cc @jgeewax 
----
**NOTE**: I am holding off on bringing in documentation until there is working code in here.
> Adding basic Bigtable client.

- gcloud/bigtable/_helpers.py
- gcloud/bigtable/client.py
- gcloud/bigtable/test__helpers.py
- gcloud/bigtable/test_client.py
~~NOTE: Uses #1152 as diffbase (though doesn't need to, as I discovered while writing)~~
> Adding helpers to make gRPC stubs from a client.

- README.rst
- docs/bigquery-usage.rst
- docs/gcloud-auth.rst
- docs/pubsub-usage.rst
Also fixing some broken links caused by a similar change
in `gcloud-common`.
> Changing "authorization" to "authentication".

- docs/bigquery-usage.rst
- docs/pubsub-usage.rst
Fixing broken build:
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/83478227
PS I broke the build with #1166. Sorry.
> Lengthening underlines for titles in BQ and Pub/Sub docs.

- docs/index.rst
- docs/search-usage.rst
Forked from @jgeewax's version in #972, and updated to match patterns from PubSub/BigQuery/DNS.
> Add initial search usage doc.

- gcloud/bigquery/client.py
- gcloud/client.py
- gcloud/dns/client.py
- gcloud/pubsub/client.py
- gcloud/storage/client.py
> Use consistent branding / phrasing in client module docstrings.

- gcloud/search/__init__.py
- gcloud/search/client.py
- gcloud/search/connection.py
- gcloud/search/test_client.py
- gcloud/search/test_connection.py
> Add search connection / client

- gcloud/search/client.py
- gcloud/search/index.py
- gcloud/search/test_client.py
- gcloud/search/test_index.py
> Add search indexes

- gcloud/datastore/query.py
- gcloud/datastore/test_query.py
Fixes [getting-started-python#8](https://github.com/GoogleCloudPlatform/getting-started-python/issues/8)
> Switching datastore cursors to URLsafe base64 encoding.

- gcloud/pubsub/subscription.py
- gcloud/pubsub/test_subscription.py
- system_tests/pubsub.py
> Speling: pass 'ack_deadline' as 'ackDeadlineSeconds' everywhere.

- docs/pubsub-usage.rst
> #1188L Fix speling of 'gcloud.pubsub.message.Message.message_id'.

- .coveragerc
- gcloud/_apitools/__init__.py
- gcloud/_apitools/buffered_stream.py
- gcloud/_apitools/exceptions.py
- gcloud/_apitools/http_wrapper.py
- gcloud/_apitools/stream_slice.py
- gcloud/_apitools/transfer.py
- gcloud/_apitools/util.py
- gcloud/storage/blob.py
- gcloud/storage/test_blob.py
- pylintrc_default
- setup.py
- tox.ini
Towards #1186.
Subsequent work to include:
- From-scratch unit test coverage -> 100%.
- Renamings to match coding standards.
- Full lint compliance.
- Folding in the current `gcloud.storage.batch` implementation.
> #1186: Revendor apitools as 'gcloud._apitools'

- gcloud/_apitools/test_util.py
- gcloud/_apitools/util.py
> Coverage for 'gcloud._apitools.util'

- gcloud/_apitools/test_exceptions.py
> Coverage for 'gcloud._apitools.exceptions'

- gcloud/_apitools/buffered_stream.py
- gcloud/_apitools/test_buffered_stream.py
> Coverage for 'gcloud._apitools.buffered_stream'

- gcloud/_apitools/http_wrapper.py
- gcloud/_apitools/test_http_wrapper.py
> Coverage for 'gcloud._apitools.http_wrapper'

- gcloud/datastore/client.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_transaction.py
- gcloud/datastore/transaction.py
- system_tests/datastore.py
Propagate it through to `Connection.begin_transaction`.
Closes #1204.
> Add 'serializable' flag to Transaction.

- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
> Allow setting 'bucket.storage_class'.

- gcloud/bigquery/table.py
- gcloud/bigquery/test_table.py
If the table has been created through the web UI and set mode for field `NULLABLE `, the `mode` in API will not be returned
Request:
```
GET https://www.googleapis.com/bigquery/v2/projects/test-project/datasets/test-dataset/tables/test-table?fields=schema&key={API_KEY}
```
Response:
```json
{
"schema": {
"fields": [{
"name": "redate",
"type": "TIMESTAMP"
}, {
"name": "bar",
"type": "RECORD",
"fields": [{
"name": "foo",
"type": "STRING"
}]
}]
}
}
```
> Missing 'mode' in table scheme

- gcloud/_apitools/test_transfer.py
- gcloud/_apitools/transfer.py
- gcloud/storage/blob.py
- tox.ini
Apologies:  this PR is a ginormous pile of tests, with more cleanups than the earlier ones.
Looking forward to the sound of the chainsaw to get rid of deadwood now that coverage is complete.
N.B.:  due to https://github.com/nose-devs/nose/blob/00ae0930e3bfad41279a0899e8c699f2ac1ff209/nose/loader.py#L164, the default `tox -e cover` misses *all* these tests.  I believe I'm going to have to rename the sub-package (`gcloud/_apitools` -> `gcloud/streaming`, maybe).  Workaround is to run the following *after* `tox -e cover`:
```bash
$ .tox/cover/bin/nosetests  \
--with-coverage   --cover-package=gcloud   --cover-tests   --cover-branches   \
gcloud/_apitools
............................................................................................................................................ …
```
> Add coverage for 'gcloud._apitools.transfer'

- gcloud/bigtable/client.py
- gcloud/bigtable/test_client.py
~~NOTE: Uses #1153 as diffbase~~
> Adding gRPC stubs to Bigtable clients

- gcloud/storage/acl.py
- gcloud/storage/test_acl.py
Allows setting ACL to a named, predefined value.
Closes: #651.
> Add 'ACL.save_predefined' method.

- gcloud/_testing.py
- gcloud/datastore/test_client.py
- gcloud/storage/test_blob.py
- gcloud/test__helpers.py
- gcloud/test_credentials.py
This is so that tests can run successfully on Windows.
In addition, using generic integer types (from `six`) for `gcloud._helpers._millis_from_datetime` since it returns a `long` on Windows and `int` on Linux. Also monkey patching the GCE ID check in `test_ctor_w_dataset_id_no_environ` since some CI environments will give a "false positive" on that test.
> Using custom named temporary file.

- gcloud/datastore/client.py
- gcloud/datastore/test_client.py
If datastore id comes back prefixed from the API, and `Client.datastore_id` is not prefixed, the `'Keys do not match dataset ID'` exception is raised.
Fixed to use `_dataset_ids_equal` for the comparison instead, which compares ignoring valid prefixes and seems to be the preferred comparison method used elsewhere in the code.
> Fix datastore: unprefixed ids in client

- gcloud/storage/blob.py
- gcloud/storage/test_blob.py
- gcloud/streaming/buffered_stream.py
- gcloud/streaming/exceptions.py
- gcloud/streaming/http_wrapper.py
- gcloud/streaming/stream_slice.py
- gcloud/streaming/test_buffered_stream.py
- gcloud/streaming/test_exceptions.py
- gcloud/streaming/test_http_wrapper.py
- gcloud/streaming/test_stream_slice.py
- gcloud/streaming/test_transfer.py
- gcloud/streaming/test_util.py
- gcloud/streaming/transfer.py
- gcloud/streaming/util.py
- tox.ini
> Streaming: add pep8 / pylint goodness

- gcloud/_helpers.py
- gcloud/bigtable/client.py
- gcloud/bigtable/cluster.py
- gcloud/bigtable/column_family.py
- gcloud/bigtable/row.py
- gcloud/bigtable/table.py
- gcloud/bigtable/test_client.py
- gcloud/bigtable/test_cluster.py
- gcloud/bigtable/test_column_family.py
- gcloud/bigtable/test_row.py
- gcloud/bigtable/test_table.py
- gcloud/test__helpers.py
The `Cluster`, `Table`, `Row` and `ColumnFamily` classes (and modules) are introduced, but without any functionality except for other nested factories.
> Adding Bigtable factories and shell classes.

- gcloud/streaming/test_transfer.py
This fails on Windows when shutil.rmtree is used (does not fail on Linux).
> Closing resources that remain open before test clean-up.

- gcloud/streaming/buffered_stream.py
- gcloud/streaming/exceptions.py
- gcloud/streaming/stream_slice.py
- gcloud/streaming/test_buffered_stream.py
- gcloud/streaming/test_stream_slice.py
- gcloud/streaming/test_transfer.py
- gcloud/streaming/test_util.py
- gcloud/streaming/transfer.py
- gcloud/streaming/util.py
> Strip excess custom exceptions from 'gcloud.streaming'

- gcloud/bigtable/client.py
- gcloud/bigtable/column_family.py
- gcloud/bigtable/row.py
- gcloud/bigtable/test_client.py
Also adding test helper for faking behavior from gRPC stubs.
> Adding list zones request to Bigtable client.

- .travis.yml
- setup.cfg
We use `universal = 1` in `setup.cfg` since our codebase works without change in both Python 2 and Python 3.
Change inspired by reading http://docs.travis-ci.com/user/deployment/pypi/ and http://pythonwheels.com/
> Add wheels to Travis deploy step.

- gcloud/bigtable/cluster.py
- gcloud/bigtable/test_cluster.py
For creating a Cluster object from a protobuf cluster returned from the API.
Also adding a helper for making sure properties are set on a protobuf object.
> Adding Bigtable Cluster.from_pb factory.

- gcloud/bigtable/cluster.py
- gcloud/bigtable/test_cluster.py
**NOTE**: This is in preparation for testing equality in unit tests of `Client.list_clusters()`.
> Adding Bigtable Cluster.__eq__.

- docs/bigquery-usage.rst
> Catch BQ usage docs up to client API speling change.

- gcloud/bigtable/_helpers.py
- gcloud/bigtable/client.py
- gcloud/bigtable/test__helpers.py
@tseaver Sorry I missed this in #1245. After this I'll get back to actually bringing features over.
> Changing Bigtable stub factories to use beta stubs.

- gcloud/streaming/http_wrapper.py
- gcloud/streaming/test_http_wrapper.py
- gcloud/streaming/transfer.py
- Catch only explicitly retryable exceptions, and handle retry count /  interval explicitly in `make_api_request`.
- Delete the `handle_heep_exceptions` helper, and the `retry_func` argument which used it as a default.
- Rename `_rebuild_http_connections` -> `_reset_http_connections` for clarity.
Closes #1223.
> Refactor 'gcloud.streaming.http_wrapper' exception handling

- gcloud/_helpers.py
- gcloud/bigquery/dataset.py
- gcloud/bigquery/job.py
- gcloud/bigquery/table.py
- gcloud/client.py
- gcloud/credentials.py
- gcloud/datastore/entity.py
- gcloud/datastore/key.py
- gcloud/datastore/test_client.py
- gcloud/search/document.py
- gcloud/storage/_helpers.py
- gcloud/storage/batch.py
- gcloud/storage/test__helpers.py
- gcloud/streaming/transfer.py
- gcloud/test_client.py
- gcloud/test_exceptions.py
- pylintrc_default
- run_pylint.py
- system_tests/storage.py
- tox.ini
Pylint 1.5 brought with it much more than
```
pylint.extensions.check_docs
```
The changes for this PR are
- checking import order
- checking `self._foo` is set in `__init__`
- complaining about methods that don't use `self`
- complaining about not calling `super().__init__` (for
the virtual base class we used)
- complaining about `not (self == other)` in `__ne__`,
suggested `(self != other)` instead
- complaining about unit tests checking `None` result from methods
which are known (by static analysis?) to return `None`
- complaining about not over-riding virtual method in storage
`_PropertyMixin`
- aggressively checking `redefined-variable-type` when variables
can be optionally `float` /`int` / `Entity` / `Key` / etc.
- checking that `GCloudError` constructor is called correctly
in unit …
> Updated source for Pylint 1.5.

- gcloud/bigquery/table.py
- gcloud/bigquery/test_table.py
- system_tests/bigquery.py
> Fix handling of timestamps in BigQuery insert data method

- gcloud/bigquery/table.py
- gcloud/bigquery/test_table.py
Also fixing `Table.expires` docstring typo.
> Returning ints from BigQuery Table.num_rows/num_bytes.

- gcloud/bigtable/__init__.py
- gcloud/bigtable/_testing.py
- gcloud/bigtable/client.py
- gcloud/bigtable/cluster.py
- gcloud/bigtable/test_client.py
- gcloud/bigtable/test_cluster.py
Also
- Implementing `Cluster.name` property which is used to identify the cluster in API requests
- Moving `_FakeStub` and `_MethodMock` to a shared testing module for Bigtable.
- Adding `Client` to root `bigtable` package.
- Fixing typo in Bigtable `Client` docstring
> Implementing Cluster.reload().

- gcloud/_helpers.py
- gcloud/credentials.py
- pylintrc_default
Able to address by reducing the complexity of the `except` blocks to make Pylint happy.
@tseaver This was a follow up to #1248, which I realized was possible after filing some issues with the Pylint folks.
> Removing wrong-import-position Pylint ignore statements.

- gcloud/bigtable/cluster.py
- gcloud/bigtable/test_cluster.py
Description pulled from the [proto contents][1] along
with the request and response types.
[1]: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/8e363d72eb39d921dfdf5daf4a36032aa9d003e2/bigtable-protos/src/main/proto/google/bigtable/admin/cluster/v1/bigtable_cluster_service.proto#L97-L109
> Implementing Bigtable Cluster.delete().

- gcloud/bigtable/cluster.py
- gcloud/bigtable/test_cluster.py
A `CreateCluster` request response doesn't actually indicate
success or failure. Rather it returns a `Cluster` message with
the validated request parts inside and a `current_operation`
attached.
We implement `_process_operation` so that we can determine the
ID of that long-running operation (so it can be checked for
completion / success, if desired by the user). In addition
we seek to notify the user when the request began.
From the [service definition][1] we know that the `current_operation`
is a [long-running operation][2] and that:
>  The embedded operation's "metadata" field type is `CreateClusterMetadata`,
>  The embedded operation's "response" field type is `Cluster`, if successful.
The [`Operation` metadata][3] is of type [`Any`][4] (which uses a `type_url`
and raw bytes to provide …
> Adding helpers to parse Bigtable create cluster operation.

- gcloud/bigtable/cluster.py
- gcloud/bigtable/table.py
- gcloud/bigtable/test_cluster.py
- gcloud/bigtable/test_table.py
This uses the table stub instead of the cluster stub. This
method is actually talking to a different service than
every method until now.
Also implementing `Table.__eq__` so table comparison succeeds
in unit tests.
> Implementing Bigtable Cluster.list_tables().

- gcloud/bigtable/cluster.py
- gcloud/bigtable/test_cluster.py
Used to provide an object as a response to Bigtable cluster operations (create, update and
undelete).
See #1270 remarks from @tseaver for details.
> Implementing Bigtable Operation class.

- gcloud/bigtable/cluster.py
- gcloud/bigtable/test_cluster.py
This method is intended to be used to check if a create, update or undelete operation has completed.
> Implementing Bigtable Operation.finished().

- docs/bigquery-usage.rst
Note:  the `client.jobs()` example is science fiction, to be addressed in #1260.
Fixes #1259.
> Sync BigQuery usage docs with current API

- gcloud/bigtable/cluster.py
- gcloud/bigtable/test_cluster.py
Also adding utility for processing `UpdateClusterMetadata`.
> Implementing Bigtable Cluster.update().

- gcloud/bigtable/cluster.py
- gcloud/bigtable/test_cluster.py
Also adding utility for processing `UndeleteClusterMetadata`.
> Implemented Bigtable Cluster.undelete().

- gcloud/bigtable/cluster.py
- gcloud/bigtable/test_cluster.py
In particular, updating the class docstring and passing the current cluster in when creating a new `Operation` from a cluster operation.
These were noticed when updating the system tests in the `gcloud-python-bigtable` project.
> Put finishing touches on Bigtable Cluster.

- gcloud/bigtable/table.py
- gcloud/bigtable/test_table.py
In the process, also implementing `Table.name` property used for sending the `delete()` request.
> Implementing Bigtable Table.delete().

- gcloud/bigquery/client.py
`name` -> `dataset_name` for `dataset()`.
`name` -> `job_name` for `load_table_from_storage()`, `copy_table()`,
`extract_table_to_storage()`, and `run_async_query`.
Closes #1268.
> Change 'name' arguments to 'Client' factories for clarity.

- gcloud/bigquery/client.py
- gcloud/bigquery/job.py
> Document URI format for loading/extracting Cloud Storage objects.

- tox.ini
See:
https://bitbucket.org/hpk42/tox/issues/294/tox-23-regression.
> Workaround tox 2.3.0 regression.

- gcloud/resource_manager/project.py
Link currently points to a non-existent page in the pub/sub docs.
> Fixing pub/sub link in resource manager.

- gcloud/datastore/connection.py
This can be seen as a bug-fix where a sub-class may not be able to impact the URIs generated.
In addition, we added the (repeated) value of the base connection's `API_BASE_URL` in advance of swapping it out for `v1beta3`.
> Explicitly using API_BASE_URL from current connection in datastore.

- gcloud/_helpers.py
- gcloud/bigtable/cluster.py
- gcloud/bigtable/column_family.py
- gcloud/bigtable/table.py
- gcloud/bigtable/test_column_family.py
- gcloud/test__helpers.py
- setup.py
- tox.ini
These are used as settings when creating new column
families within a table.
Also slipping in 3 small Bigtable docstring updates.
> Adding primitive Bigtable garbage collection rule classes.

- gcloud/datastore/client.py
- gcloud/datastore/connection.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_transaction.py
- gcloud/datastore/transaction.py
- system_tests/datastore.py
This is in advance of the option being removed in v1beta3. Since in v1beta3:
> All transactions are now serializable
we set the isolation to always be serializable.
-----
@pcostell Is this "safe" to do as prep for the version upgrade?
Also, is there an equivalent replacement in `v1beta3`? AFAICT the isolation level is just gone.
> Removing serializable option from datastore Transaction.

- gcloud/datastore/_entity_pb2.py
- gcloud/datastore/connection.py
- gcloud/datastore/helpers.py
- gcloud/datastore/key.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_helpers.py
- gcloud/datastore/test_key.py
- gcloud/datastore/test_query.py
- gcloud/datastore/test_transaction.py
This is just a superficial rename in preparation for v1beta3.
See plan in #1288 for an idea why.
> Replacing datastore pb uses with entity shim.

- gcloud/bigtable/column_family.py
- gcloud/bigtable/row.py
- gcloud/bigtable/test_column_family.py
- gcloud/bigtable/test_row.py
Also adding regex filters for a row key (bytes) and a family name (string).
These come from
https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/6a498cd3e660c7ed18299e980c1658d67661e69b/bigtable-protos/src/main/proto/google/bigtable/v1/bigtable_data.proto#L321-L404
In addition to more classes for primitive properties, parent classes are forthcoming to handle the non-primitive cases of filter Chain, Interleave and Condition (ternary).
Also renaming some redunant unit test names in `test_column_family.py` and ditching use of `NotImplementedError` in bigtable base classes (for both GC rule and row filter).
> Adding Bigtable RowFilter base class.

- gcloud/datastore/_query_pb2.py
- gcloud/datastore/client.py
- gcloud/datastore/connection.py
- gcloud/datastore/query.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_query.py
This is just a superficial rename in preparation for v1beta3.
> Replacing datastore pb uses with query shim.

- gcloud/datastore/batch.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_transaction.py
This mutation type has been removed in v1beta3 so we
just use Batch.put() to handle the previous duty.
Also simplifying the helper which populates a protobuf entity
from a gcloud-python Entity.
> Removing datastore Batch.add_auto_id_entity.

- gcloud/bigtable/row.py
- gcloud/bigtable/test_row.py
Row filter for a column name (irrespective of column family)
and a value (in any cell).
> Adding remaining Bigtable regex row filters.

- gcloud/datastore/_datastore_pb2.py
- gcloud/datastore/batch.py
- gcloud/datastore/connection.py
- gcloud/datastore/helpers.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_helpers.py
- gcloud/datastore/test_transaction.py
This is just a superficial rename in preparation for v1beta3.
In particular, we went from a single datastore.proto file in v1beta2
to entity.proto, query.proto and datastore.proto in v1beta3, so
this shim is intended to be the third of these files.
> Replacing datastore pb uses with "datastore" shim.

- gcloud/bigtable/column_family.py
- gcloud/bigtable/test_column_family.py
Also adding equality check for column family
instances.
> Adding GC Rule to Bigtable Column Family class.

- gcloud/bigquery/client.py
- gcloud/bigquery/test_client.py
We can't parse/create job instances w/o full configuration.
> Fix 'Client.list_jobs' to use 'full' projection.

- gcloud/bigquery/client.py
- gcloud/bigquery/job.py
- gcloud/bigquery/test_client.py
Uses #1311 as a base.
E.g., the jobs created via 'Table.upload_from_file' do not have source URIs.
> Allow for 'sourceUris' to be missing in load job config.

- gcloud/datastore/_datastore_pb2.py
- gcloud/datastore/batch.py
- gcloud/datastore/entity.py
- gcloud/datastore/helpers.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_helpers.py
To do this, added `entity_to_protobuf` method that could be used recursively. Also solves #1206 since recursively serializing nested entities to protobuf was being done incorrectly.
Fixes #1065. Fixes #1206.
> Properly handling entity meanings in datastore.

- gcloud/datastore/batch.py
- gcloud/datastore/connection.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_transaction.py
Also moving out the response parsing into a helper which can
be monkey-patched out during testing.
This is for the `v1beta2` to `v1beta3` change. Currently the
`CommitResponse` object contains a single `MutationResult` that holds
an integer `index_updates` field and a repeated field (`insert_auto_id_key`)
of partial `Key`s that were completed in the `commit`.
In `v1beta3`, the `CommitResponse` directly holds the integer `index_updates`
as well as a list of `MutationResult`s. Additionally, the definition of
`MutationResult` no longer has `index_updates` (obviously given the last
sentence) and no longer holds a list of `Key`s. Instead, it holds a single
`Key` in the `key` field. What's more, the list of `MutationResult`s
corresponds to every single `Entity` modified in the commit. For those …
> Reducing datastore commit reliance on structure of response.

- scripts/rewrite_imports.py
There were some manual (via `sed` with the command line) edits made for certain gRPC related parts of `*_pb2.py` files that used dispatch tables to map service names onto request/response protobuf types. For example
```python
request_deserializers = {
('google.longrunning.Operations', 'CancelOperation'): google.longrunning.operations_pb2.CancelOperationRequest.FromString,
('google.longrunning.Operations', 'DeleteOperation'): google.longrunning.operations_pb2.DeleteOperationRequest.FromString,
('google.longrunning.Operations', 'GetOperation'): google.longrunning.operations_pb2.GetOperationRequest.FromString,
('google.longrunning.Operations', 'ListOperations'): google.longrunning.operations_pb2.ListOperationsRequest.FromString,
}
```
needed to be transformed into
```python …
```
> Bringing auto-gen import re-writing up to date with files.

- gcloud/datastore/batch.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_transaction.py
This is towards the switch to `v1beta3` where the `Mutation`
container no longer holds a list of insert/update/upsert/etc.
mutations (as `Entity` pb's) but instead holds a single one.
The list is moved onto the `CommitRequest` message definition.
Plan to follow up with methods to abstract away getting the
list of inserts, upserts, deletes, etc. as well as a method
for adding a new mutation of a given type to the `changes`
accumulator.
> Renaming datastore Batch.mutation to mutations.

- gcloud/datastore/batch.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_client.py
Also adding test helpers to extract a single mutation (of
a given type) from a mutation protobuf object.
This is in advance of `v1beta3` where the structure of the
`CommitRequest` is significantly different.
> Puting helpers in datastore Batch for getting new mutations.

- gcloud/bigtable/row.py
- gcloud/bigtable/test_row.py
Also implementing a separate `TimestampRange` class since it will need to be used to limit data requests to certain ranges (e.g. in ``Mutation.DeleteFromColumn.time_range`` in the Bigtable
data `.proto` spec).
> Implementing Bigtable TimestampRangeFilter.

- gcloud/bigtable/_helpers.py
- gcloud/bigtable/column_family.py
- gcloud/bigtable/row.py
- gcloud/bigtable/table.py
- gcloud/bigtable/test_row.py
- gcloud/bigtable/test_table.py
Also
-   Adding `filter` to `Table`'s row factory
-   Bringing in some changes from original `gcloud-python-bigtable`
project
- Adding `SSL_CERT_FILE` path for Mac OS X (installed via
`homebrew`)
- Fixing some docstring typos / missing docstring list of
class functionality
> Adding filter to Bigtable Row constructor.

- gcloud/_helpers.py
- gcloud/client.py
- gcloud/test__helpers.py
- gcloud/test_client.py
It seems this was intended to be done awhile ago and fell through
the cracks.
@tseaver This relates to / was discovered in #1330
> Updating default project to also use App Engine and Compute Engine.

- gcloud/pubsub/client.py
- gcloud/pubsub/message.py
- gcloud/pubsub/subscription.py
- gcloud/pubsub/topic.py
These links were valid in v1beta2 but when the upgrade to
v1 occurred they started to give 404s. Fixes #1211.
Replaced mostly with
```
git grep -l v1beta2 -- gcloud/pubsub | xargs sed -i s/v1beta2/v1/g
git grep -l 'v1/projects/' -- gcloud/pubsub | \
xargs sed -i 's/v1\/projects\//v1\/projects\./g'
```
but manually replaced
```
/pubsub/reference/rest/v1beta2/projects/topics/subscriptions/list
-> /pubsub/reference/rest/v1/projects.topics.subscriptions/list
/pubsub/reference/rest/google/pubsub/v1beta2/PubsubMessage
-> /pubsub/reference/rest/v1/PubsubMessage
```
after the fact.
> Fixing broken links in Pub/Sub docs.

- gcloud/bigtable/test_row.py
Doing this to match the order that the tested filters occur in `row.py`.
@tseaver Sorry this happened, I think it might've been caused by fly-by merges? I know you said the tests should come in the same order as the filters, which come in the same order as the fields in the proto spec.
-----
To "verify" the order
```bash
$ cat gcloud/bigtable/row.py | grep -e '^class'
class Row(object):
class RowFilter(object):
class _BoolFilter(RowFilter):
class SinkFilter(_BoolFilter):
class PassAllFilter(_BoolFilter):
class BlockAllFilter(_BoolFilter):
class _RegexFilter(RowFilter):
class RowKeyRegexFilter(_RegexFilter):
class RowSampleFilter(RowFilter):
class FamilyNameRegexFilter(_RegexFilter):
class ColumnQualifierRegexFilter(_RegexFilter):
class TimestampRange(object):
class …
```
> Moving Bigtable TestColumnRangeFilter within unit test file.

- gcloud/_helpers.py
- gcloud/dns/changes.py
- gcloud/pubsub/message.py
- gcloud/pubsub/topic.py
- gcloud/search/document.py
- gcloud/storage/blob.py
- gcloud/storage/bucket.py
- gcloud/test__helpers.py
Adding helpers for conversion both to and from strings. Fixes #1146.
> Consolidate parsing of RFC 3339 datetime strings.

- gcloud/bigtable/row.py
- gcloud/bigtable/test_row.py
This is a [`Condition`][1] filter, which is effectively a ternary operator (predicate determines if the true or false filter is applied).
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/9e2b07d92bbbf8640a3a767ccf4796245ba5b51c/gcloud/bigtable/_generated/_bigtable_data.proto#L232-L245
> Implementing Bigtable ConditionalRowFilter.

- system_tests/bigquery.py
- system_tests/storage.py
Three of the four uses were fully removed: these simply checked how factories created owned objects. The fourth just used a public property to access the same value. Fixes #1059.
> Removing uses of non-public attributes in system tests.

- gcloud/datastore/helpers.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_helpers.py
- gcloud/datastore/test_query.py
This is because the repeated `property` message field in `Entity` becomes a `properties` map field in `v1beta3`. This makes adding new properties and iterating through all properties very different, so we add a helper to ease the transition from `v1beta2` to `v1beta3`.
> Adding helpers for interacting with properties in Entity protobuf.

- docs/datastore-transactions.rst
- gcloud/datastore/batch.py
- gcloud/datastore/client.py
- gcloud/datastore/connection.py
- gcloud/datastore/key.py
- gcloud/datastore/query.py
- gcloud/datastore/transaction.py
Somewhat inspired by #1069 (or at least the branch referenced there, which I recently deleted).
Also follows on #1345.
> Datastore docs clean-up.

- gcloud/datastore/batch.py
- gcloud/datastore/connection.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_transaction.py
This is towards #1288 in preparation for the upgrade to `v1beta3`. In particular, a single `Mutation` protobuf instance in `v1beta3` is not sufficient to contain all changes to be committed, so we use the container that is up one level in the hierarchy.
> Using protobuf CommitRequest in datastore Connection.commit.

- gcloud/bigtable/happybase/__init__.py
- gcloud/bigtable/happybase/connection.py
- gcloud/bigtable/happybase/test_connection.py
Starting off with a bare `Connection` class that has the same arguments as the HappyBase `Connection` class.
> Adding Bigtable HappyBase sub-package.

- system_tests/datastore.py
This way, the results are in the same order in both production and the emulator.
See [comment][1] in #1369 for context.
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/1369/files#r49241254
> Using query order in test_projection_query.

- gcloud/datastore/__init__.py
- gcloud/datastore/batch.py
- gcloud/datastore/client.py
- gcloud/datastore/connection.py
- gcloud/datastore/demo/__init__.py
- gcloud/datastore/demo/demo.py
- gcloud/datastore/helpers.py
- gcloud/datastore/key.py
- gcloud/datastore/query.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_entity.py
- gcloud/datastore/test_helpers.py
- gcloud/datastore/test_key.py
- gcloud/datastore/test_query.py
- gcloud/datastore/test_transaction.py
- gcloud/datastore/transaction.py
- system_tests/datastore.py
This is done in advance of `v1beta3` where `PartitionId.dataset_id` becomes `PartitionId.project_id`.
@tseaver This is part of the plan in #1288. It's a bit of a mouthful, maybe you have some suggestions on how to make it easier to review? (I'm happy to make the necessary changes)
Also note that I haven't changed the use of `GCLOUD_TESTS_DATASET_ID` and similar for finding the default project. IMO that should come in a separate PR. I feel that that separate PR will be complicated enough without throwing in **ALL** these renames. (I also realized that we only check the env. var. for the project with every other service, though we could check the App Engine ID or the Compute Engine ID as well.)
> Replace dataset id with project in datastore

- gcloud/dns/test_changes.py
- gcloud/dns/test_zone.py
- gcloud/dns/zone.py
Was previously assumed to be a float (seconds from the epoch). Also using core timestamp utilities in `dns` tests.
Fixes #1362.
----
@kvdb I found I couldn't even create a managed zone to test if this was possible. How did you create your pre-existing zones? (I'm curious if you have a test domain or if you are actually using the service to manage DNS rules for a live domain.)
> Treating DNS zone creation time as an RFC 3339 string. 

- system_tests/clear_datastore.py
- system_tests/datastore.py
- system_tests/populate_datastore.py
Caused by #1330 and #1369 crossing paths.
> Fixing incorrect use of dataset_id in system tests.

- gcloud/bigquery/dataset.py
- gcloud/bigquery/test_dataset.py
> Only allow one entity to come from a BQ access grant.

- system_tests/datastore.py
Using a namespace for any key which is changed (inserted/deleted) so that concurrent tests don't operate on the same data. The one exception is `TestDatastoreQuery` which depends on entities which need to be already stored and indexed before running. For this test case, a new client is created without any namespace.
**NOTE**: Has #1369 as diffbase.
Inspired by #1363.
> Updating datastore system test to allow concurrent runs.

- gcloud/datastore/batch.py
- gcloud/datastore/connection.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/transaction.py
This is so that commit request protos are not re-used, so we can re-use and modify them when passed into `Connection.commit`.
Fixes #1366.
----
@tseaver The tests still pass (as well as coverage) dude to transitive use of the newly moved code. What sort of tests would you like to see added?
> Moving Transaction tombstone behavior onto Batch.

- gcloud/environment_vars.py
- gcloud/pubsub/connection.py
- gcloud/pubsub/test_connection.py
Also changing how the variable is used. Now, pre-pending the protocol in front. (Assumes the user does something like `localhost:8888`.)
/cc @hbchai
> Changing use of PUBSUB_HOST env. var. to PUBSUB_EMULATOR_HOST.

- gcloud/_testing.py
- gcloud/credentials.py
- gcloud/storage/_helpers.py
- gcloud/storage/test__helpers.py
- gcloud/test_credentials.py
- setup.py
This was done because `PyCrypto` does not install easily on Windows. `pyOpenSSL` is managed by PyCA (the Python crypto authority) and has a mature release process.
This change was influenced by discussions about #1009.
> Swapping PyCrypto for pyOpenSSL.

- Makefile
@tseaver As you'll notice, this is quite nasty. I'm open to suggestions for making this better. Some simple options:
- We are content that this is "good enough"
- I become competent using `bash`
- I rewrite this script in Python with judicious use of some system calls
FWIW, this is in advance of `v1beta3` for datastore, which will re-use some of these components (e.g. `timestamp`) so we need this pipeline to be a bit more polished.
> Making pb2 auto-gen script also copy over .proto files.

- scripts/run_pylint.py
- tox.ini
It's unclear why this wasn't failing sooner, but it is causing the build to fail.
> Ignored datastore/_generated directory in lint.

- gcloud/_helpers.py
- gcloud/bigtable/cluster.py
- gcloud/bigtable/test_cluster.py
- gcloud/test__helpers.py
This is in advance of `v1beta3`, where it will be needed to parse `Value.timestamp_value` (which is of type `timestamp_pb2.Timestamp`). Also adding `_datetime_to_pb_timestamp` for the other direction.
----
~~**NOTE**: Has #1353 as diffbase.~~
> Moving _pb_timestamp_to_datetime into core.

- CONTRIBUTING.rst
- system_tests/datastore.py
- system_tests/run_system_test.py
Currently, the `GOOGLE_APPLICATION_CREDENTIALS` is used and an access token is minted even though requests to the emulator require no authentication.
> Allowing datastore system test to run on emulator with no connection.

- gcloud/bigtable/row.py
- gcloud/bigtable/test_row.py
This accumulates a row mutation without actually sending a request (this is similar to a batch in datastore).
> Adding Bigtable Row.append_cell_value.

- gcloud/bigtable/row.py
- gcloud/bigtable/test_row.py
Also adding _get_mutations helper to grab mutations relevant to the non-conditional/`True`/`False` state of a mutation.
> Adding tracking mutations to Bigtable row.

- gcloud/bigtable/row.py
- gcloud/bigtable/test_row.py
Similar to #1388. The API accepts integers and then encodes them as bytes when stored in the table.
> Adding Bigtable Row.increment_cell_value.

- CONTRIBUTING.rst
- scripts/datastore_emulator.py
- tox.ini
See discussion in #1374 for context.
/cc @pcostell
> Adding tox env for datastore sys tests w / emulator.

- system_tests/pubsub.py
Fixes #1363.
-----
@tseaver Note #1370 does the same for `datastore`. Should we do the same for `storage` and `bigquery`? At the very least we should re-visit retries (especially for doing a "clean up everything" in `tearDownModule`) so that our system tests don't leave resources around.
> Use runtime specific topic names in Pub/Sub system tests.

- CONTRIBUTING.rst
- gcloud/connection.py
- gcloud/storage/test_batch.py
- gcloud/test_connection.py
- system_tests/datastore.py
- system_tests/pubsub.py
- system_tests/system_test_utils.py
Modeled after #1369 and #1386. Holding off on adding parts similar to #1393 (until that PR is reviewed and merged).
-----
**NOTE**: Has #1395 as a diffbase.
> Adding support for pubsub emulator in system test.

- gcloud/connection.py
- gcloud/storage/test_batch.py
- gcloud/test_connection.py
@tseaver I discovered this while outfitting the Pub/Sub system tests to run with the emulator. When using an un-authorized client [like in `datastore`][1], it caused an error in `httplib2`. We have never experience this because `oauth2client` has [bailed us out][2] until this point.
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/ffe5869aa7c31bd82483e4d52adacbf83cf0fd69/system_tests/datastore.py#L75
[2]: https://github.com/google/oauth2client/blob/8f8df1f5977ec76d50cb3dca9a31044cfd1fb9b4/oauth2client/client.py#L464-L465
> Making the content length header a string.

- gcloud/bigquery/table.py
> Add more detail to BigQuery Table.insert_data().

- scripts/datastore_emulator.py
- system_tests/datastore.py
@tseaver This remedies the "wrong" import in #1393. The system test should've been doing everything at runtime anyhow, that was one of the main points of #1349
> Making datastore system test use env. at runtime rather than import time.

- gcloud/_helpers.py
- gcloud/bigtable/cluster.py
- gcloud/bigtable/test_cluster.py
- gcloud/datastore/connection.py
- gcloud/datastore/helpers.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_helpers.py
- gcloud/datastore/test_key.py
- gcloud/test__helpers.py
Doing this so that we can factor out `_has_field` and use it across
packages. This is because `HasField()` works differently in
`proto3` and we use this behavior from time to time.
This is as part of plan in #1288
> Moving _get_pb_property_value from bigtable into core.

- CONTRIBUTING.rst
- README.rst
- tox.ini
Fixes #1410.
NOTE: We never ran `tox -e py33` in Travis and this does not add `tox -e py35` (for now). It seems it'd be best to wait until https://github.com/travis-ci/travis-ci/issues/4794 is resolved before adding it.
> Dropping Py33 support, adding Py35.

- gcloud/bigquery/dataset.py
- gcloud/bigquery/test_dataset.py
- system_tests/bigquery.py
> Allowing missing tables key in BigQuery list tables response.

- CONTRIBUTING.rst
- scripts/run_emulator.py
- tox.ini
Also manually handling clean-up of child processes spawned. The ``gcloud`` tool was orphan-ing some processes.
----
~~**NOTE**: Has #1400 as diffbase.~~
Filed https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/87 in response to orphan-ed processes.
> Making emulator scripts wait until emulators are ready.

- gcloud/credentials.py
- gcloud/storage/blob.py
- gcloud/storage/test_blob.py
- gcloud/test_credentials.py
Allows customization of the experience for end users of the signed URI.
----
I noticed https://github.com/GoogleCloudPlatform/gcloud-node/pull/1058 and thought we should implement as well, at which point I realized we didn't support the response content type/disposition either.
> Adding optional arguments to generate signed URI method.

- gcloud/datastore/connection.py
- gcloud/datastore/test_connection.py
In `v1beta3` all transactions are serializable.
> Removing use of isolation level in datastore.

- README.rst
- gcloud/datastore/connection.py
- gcloud/datastore/test_connection.py
Also updating the docs link in the README.
Was #1339 but this PR targets the `v1beta3` branch instead.
> Updating datastore URI template for v1beta3.

- appveyor.yml
- appveyor/install.ps1
- appveyor/run_with_env.cmd
Towards #1124.
Worked out the kinks in #1220. Huge thanks to [`python-appveyor-demo`][1].
My current plan is to turn off AppVeyor for general PRs and just run it on merges to master
and then use [tags only][2] to push build artifacts to PyPI.
[1]: https://github.com/ogrisel/python-appveyor-demo
[2]: https://www.appveyor.com/docs/branches#build-on-tags-github-only
> Adding AppVeyor configuration.

- gcloud/resource_manager/client.py
- gcloud/resource_manager/connection.py
- gcloud/resource_manager/test_client.py
- gcloud/resource_manager/test_connection.py
> Removing restriction to only user accounts in resource manager.

- docs/bigquery-usage.rst
- gcloud/bigquery/client.py
- gcloud/bigquery/table.py
- gcloud/bigquery/test_client.py
- gcloud/bigquery/test_table.py
Handles both single-request (multipart) and resumable uploads.
Closes #1261
> Add 'Table.upload_from_file'.

- gcloud/datastore/query.py
- gcloud/datastore/test_query.py
- system_tests/clear_datastore.py
- system_tests/datastore.py
- system_tests/populate_datastore.py
Also updating system tests and system test helpers to avoid direct use of `__key__`.
Fixes #1432.
> Adding key_filter to datastore Query.

- README.rst
- setup.py
Also adding a shield to README that has all of our supported versions and removing the text with the same content.
> Updating setup.py to showcase current status and version support.

- gcloud/bigquery/test_table.py
> Strips multipart messages in BigQuery before comparing.

- gcloud/credentials.py
- gcloud/test_credentials.py
> Allowing pyOpenSSL import to fail for GAE.

- MANIFEST.in
- scripts/attempt_system_tests.py
@tseaver I noticed this while trying to `from system_tests import populate_datastore` and the import failed due to reasons that were "resolved" in #1349.
Then I peaked and realized that the error was coming from
```
/usr/local/lib/python2.7/dist-packages/system_tests/populate_datastore.py
/usr/local/lib/python2.7/dist-packages/gcloud/datastore/client.py
```
Notice that in our repo:
```python
>>> from setuptools import find_packages
>>> find_packages()
['gcloud',
'system_tests',
'gcloud.storage',
'gcloud.pubsub',
'gcloud.dns',
'gcloud.bigtable',
'gcloud.bigquery',
'gcloud.resource_manager',
'gcloud.search',
'gcloud.datastore',
'gcloud.streaming',
'gcloud.storage.demo',
'gcloud.bigtable.happybase',
'gcloud.bigtable._generated',
'gcloud.datastore.demo',
'gcloud.datastore._generated']
``` …
> Excluding system tests from being installed.

- gcloud/bigtable/happybase/connection.py
- gcloud/bigtable/happybase/test_connection.py
~~@tseaver By adding this I go from 10 to 11 arguments (10 are part of the [original interface][1]) and I make [`pylint` angry][2].~~
----
Would you prefer I
- Use `**kwargs` for supporting the legacy signature (this breaks any argument order unless we also use `*args` and manually do the mapping, which would break existing code that uses `happybase`)
- Raise the global limit from 10 to 11
- `pylint: disable=` locally
----
@jgeewax How important is having the signature of our `gcloud.bigtable.happybase.Connection` the same as `happybase.Connection`?
[1]: https://github.com/wbolster/happybase/blob/9cbd718c10a3089f234f1eac1236b631e1f8e7cd/happybase/connection.py#L105-L108
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/896044579b5dfaddb75e8c7cbf72b614b0d04c5e/scripts/pylintrc_ …
> Adding cluster argument to Bigtable HappyBase connection.

- gcloud/datastore/connection.py
- gcloud/datastore/helpers.py
- gcloud/datastore/key.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_helpers.py
- gcloud/datastore/test_key.py
- gcloud/datastore/test_query.py
- gcloud/datastore/test_transaction.py
Was #1359, but now is being merged into the `v1beta3` branch
> Handle datastore renames on PartitionId

- docs/bigquery-query.rst
- docs/datastore-helpers.rst
- docs/gcloud-api.rst
- docs/index.rst
- docs/storage-batch.rst
- scripts/run_pylint.py
- scripts/update_docs.sh
- scripts/verify_included_modules.py
- tox.ini
Fixes #714.
Also: making prints to `stderr` Python 3 friendly in `run_pylint.py`.
----
@tseaver Note the `docs` rule will fail here. This was intentional. I wanted to display which modules were still undocumented so we could discuss if they should be added to the `IGNORED_MODULES` set or if we should add them to an `rst` file.
> Adding check that all public modules are documented.

- gcloud/datastore/connection.py
- gcloud/datastore/query.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_query.py
- system_tests/datastore.py
> Handling datastore renames on Query and QueryResultBatch.

- gcloud/datastore/query.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_query.py
> Handling datastore renames on CompositeFilter and PropertyFilter.

- gcloud/datastore/batch.py
- gcloud/datastore/client.py
- gcloud/datastore/helpers.py
- gcloud/datastore/key.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_helpers.py
- gcloud/datastore/test_key.py
- gcloud/datastore/test_query.py
- gcloud/datastore/test_transaction.py
> Renaming path_element->path in Key.

- gcloud/datastore/connection.py
- gcloud/datastore/test_connection.py
A repeated `Key` field occurs on:
- `AllocateIdsResponse`
- `AllocateIdsRequest`
- `LookupRequest`
----
Was #1358
> Handling datastore renames key -> keys

- gcloud/datastore/batch.py
- gcloud/datastore/connection.py
- gcloud/datastore/helpers.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_client.py
- gcloud/datastore/test_connection.py
- gcloud/datastore/test_helpers.py
- gcloud/datastore/test_transaction.py
- gcloud/datastore/transaction.py
@jonparrott It's been a bit since all these commits got merged, but after this `v1beta3` should be "stable".
> Updating CommitRequest, Mutation and helpers for v1beta3.

- gcloud/datastore/helpers.py
~~NOTE: Has #1461 as diffbase.~~
Relates to discussion in #1402.
> Using WhichOneof when parsing a Value protobuf.

- gcloud/datastore/helpers.py
- gcloud/datastore/test_helpers.py
- system_tests/datastore.py
~~NOTE: Has #1462 as diffbase.~~
> Adding support for null and geo point values in v1beta3.

- CONTRIBUTING.rst
- gcloud/datastore/client.py
- gcloud/datastore/demo/__init__.py
- gcloud/datastore/test_client.py
- gcloud/environment_vars.py
- scripts/pylintrc_default
- system_tests/clear_datastore.py
- system_tests/datastore.py
- system_tests/local_test_setup.sample
- system_tests/populate_datastore.py
- system_tests/run_system_test.py
- system_tests/system_test_utils.py
This is no longer needed since the project ID is used by the datastore `v1beta3` API.
> Removing custom dataset ID environment variable.

- gcloud/pubsub/client.py
- gcloud/pubsub/test_client.py
- system_tests/pubsub.py
> Harden pubsub client against keys omitted in back-end responses

- gcloud/_helpers.py
Suppresses output from pylint 1.5.4 like:
```
lint runtests: commands[1] | python /home/tseaver/projects/agendaless/Google/src/gcloud-python/scripts/run_pylint.py
Diff base not specified, listing all files in repository.
************* Module gcloud._helpers
I: 28, 0: Locally disabling import-error (E0401) (locally-disabled)
I: 90, 0: Locally disabling unused-argument (W0613) (locally-disabled)
I:100, 0: Locally disabling unused-argument (W0613) (locally-disabled)
I:104, 0: Locally disabling unused-argument (W0613) (locally-disabled)
I:392, 0: Locally disabling unused-import (W0611) (locally-disabled)
I:392, 0: Locally disabling wrong-import-position (C0413) (locally-disabled)
C:392, 4: external import "from pytz import UTC" comes before "from gcloud.environment_vars import PROJECT" …
```
> Rename suppressed pylint error to match value expected by 1.5.4.

- docs/bigquery-usage.rst
- gcloud/bigquery/job.py
- gcloud/bigquery/test_client.py
- gcloud/bigquery/test_job.py
Uses #1468 as a base.
Match actual usage patterns.
Closes #1398, #1399.
> Clean up bigquery usage docs

- gcloud/bigtable/row.py
- gcloud/bigtable/test_row.py
- scripts/run_pylint.py
Sends a `ReadModifyWriteRowRequest` and needs some helpers for parsing the result.
This concludes up the implementation of `row.py`.
> Implementing Bigtable Row.commit_modifications().

- gcloud/bigtable/happybase/connection.py
- gcloud/bigtable/happybase/test_connection.py
Also using `open()` in constructor and `close()` in destructor, as is done in the thrift version of HappyBase.
> Implementing open()/close() on HappyBase connection.

- gcloud/bigtable/row_data.py
- gcloud/bigtable/test_row_data.py
- scripts/verify_included_modules.py
Used to hold data in rows retrieved.
@tseaver This module could definitely use some design review (none of the content here yet, but worth discussing now or at least thinking about).
Right now, the implementation is as follows:
- Rows are read from a `Table` (and a `Cell` is like a "column" in a row, so there can be many), so the helpers needed to parse a row that was read are in `row_data.py`
- Mutations (in rows) are created directly on a `Row`, and this is all done in `row.py` (all code submitted or merged)
> Adding Bigtable Cell class.

- gcloud/credentials.py
- gcloud/test_credentials.py
- setup.py
> Upgrading to oauth2client 2.0.

- gcloud/bigtable/row_data.py
- gcloud/bigtable/test_row_data.py
These objects will be used when data is read from a table.
> Adding Bigtable PartialRowData.

- gcloud/pubsub/message.py
- gcloud/pubsub/test_message.py
e2b3ef7 also cleans up the order of testcase methods to match the actual order of `Message` methods.
Closes #1480
> Harden 'Message.from_api_repr' against missing 'data'

- gcloud/bigtable/row_data.py
- gcloud/bigtable/test_row_data.py
Used to consume an iterator that yields data row-by-row.
Will parse the stream and yield PartialRowData objects.
> Adding Bigtable PartialRowsData.

- gcloud/bigtable/row_data.py
- gcloud/bigtable/test_row_data.py
Also adding some helper properties for public use.
> Adding clear() to Bigtable row data.

- gcloud/bigtable/row_data.py
- gcloud/bigtable/test_row_data.py
These methods read from a stream of `ReadRowsResponse`'s, parse them and then store them on the `PartialRowsData` instance.
@tseaver The implementation of `PartialRowData.update_from_read_rows` is coming soon. It depends on #1492. I held off on including it there because it has a non-trivial amount of code.
> Implementing consume_*() methods on Bigtable PartialRowsData.

- gcloud/bigtable/happybase/connection.py
- gcloud/bigtable/happybase/table.py
- gcloud/bigtable/happybase/test_connection.py
- gcloud/bigtable/happybase/test_table.py
- scripts/verify_included_modules.py
Also adding a `Table` factory to HappyBase connection and adding two `NotImplemented` methods to the `table` module (to populate the namespace so that it is the same as the HappyBase implementation).
> Adding Bigtable HappyBase Table class.

- docs/gcloud-auth.rst
- gcloud/credentials.py
FYI @tseaver I didn't realize the App Engine import was busted. I am once and for all going to push that stuff upstream into `oauth2client` and hopefully we can get a `2.0.1` release there.
> Accomodating oauth2client moves of GCE/App Engine modules.

- gcloud/bigtable/table.py
- gcloud/bigtable/test_table.py
FYI @tseaver This is the last of the non-HappyBase PRs!
> Adding Bigtable Table.read_rows().

- gcloud/bigtable/happybase/connection.py
- gcloud/bigtable/happybase/table.py
- gcloud/bigtable/happybase/test_connection.py
- gcloud/bigtable/happybase/test_table.py
Providing the methods for interface compatibility.
> Implementing HappyBase methods that aren't functional in Bigtable.

- appveyor.yml
[Build][1] has been broken since #1463, my bad.
[1]: https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.199.master
> Adding nose-exclude as an AppVeyor dependency.

- gcloud/client.py
- gcloud/test_client.py
> Allow bytes or string as project value in clients.

- gcloud/exceptions.py
- gcloud/test_exceptions.py
> Handle expected JSON errors that can't be parsed.

- setup.py
This is necessitated by the broken GCE support in oauth2client 2.0.0.
Fixes #1484 
/cc @jgeewax @JeremyGrosser
> Upgrading version to 0.10.1.

- gcloud/bigtable/client.py
- gcloud/bigtable/test_client.py
- gcloud/connection.py
- gcloud/credentials.py
- gcloud/test_connection.py
- gcloud/test_credentials.py
@tseaver 
1. Maybe this isn't the best way to solve #1412? Happy to hear suggestions.
1. I also realized that we don't really need the `get_for_service_account_p12` and `get_for_service_account_json` helpers any more since the `ServiceAccountCredentials` factories do everything in a nice short way.
> Allowing credentials that don't implement create_scoped().

- gcloud/client.py
- gcloud/credentials.py
- gcloud/test_client.py
- gcloud/test_credentials.py
After `oauth2client` 2.0.0 the are just thin wrappers around factory constructors, so no longer needed.
Note that `gcloud.credentials.get_credentials()` is also a very thin wrapper, however, it has useful documentation.
----
@tseaver Do you think I should also remove `get_credentials()` and try to push to documentation into `oauth2client`? (I need to do a side-by-side, I can't quite remember the state of things.)
> Removing get_for_service_account_* helpers.

- gcloud/datastore/__init__.py
- gcloud/datastore/batch.py
- gcloud/datastore/connection.py
- gcloud/datastore/entity.py
- gcloud/datastore/query.py
- gcloud/datastore/transaction.py
> Update datastore docstrings to use client pattern.

- gcloud/bigtable/happybase/pool.py
- gcloud/bigtable/happybase/test_pool.py
- scripts/run_pylint.py
- scripts/verify_included_modules.py
FYI @jgeewax this is the last `bigtable` module that needs to be added. (This isn't the last PR, the modules are being built up piece by piece, but getting closer and closer.)
----
For comparison: https://github.com/wbolster/happybase/blob/9cbd718c10a3089f234f1eac1236b631e1f8e7cd/happybase/pool.py
> Adding HappyBase connection pool.

- gcloud/bigtable/happybase/batch.py
- gcloud/bigtable/happybase/test_batch.py
- scripts/verify_included_modules.py
For comparison: https://github.com/wbolster/happybase/blob/9cbd718c10a3089f234f1eac1236b631e1f8e7cd/happybase/batch.py
> Beginning of HappyBase batch module.

- gcloud/bigtable/happybase/connection.py
- gcloud/bigtable/happybase/test_connection.py
@tseaver sorry #1501 got closed. I did a `git push -f` after rebase-ing and it just pushed the `HEAD` of `master` (which GitHub interpreted as a delete).
> Adding HappyBase Connection.create_table().

- gcloud/bigtable/happybase/connection.py
- gcloud/bigtable/happybase/table.py
- gcloud/bigtable/happybase/test_table.py
@jonparrott I figured this would be good for you to get a sense of why I'd be sending PRs for helpers before actually implementing the methods themselves. The [helpers][1] themselves contain quite a bit of code (HappyBase is a nice abstraction and the work is worth it).
[1]: https://github.com/dhermes/gcloud-python-bigtable/blob/b2c61ee0d105013e4152711c8563cc3365ea58d7/gcloud_bigtable/happybase/table.py#L97-L334
> Adding virtual implementations for remaining HappyBase Table methods.

- gcloud/bigtable/happybase/batch.py
- gcloud/bigtable/happybase/test_batch.py
This completes the `Batch()` implementation.
----
All that is left is finishing `Table`! w00t! (And bringing over the HappyBase system tests.)
> Adding HappyBase batch delete().

- gcloud/bigtable/client.py
- gcloud/bigtable/test_client.py
- system_tests/bigtable_happybase.py
- system_tests/run_system_test.py
Also in the process modifying Bigtable `Client.copy()` since the crypto signer objects used in `ServiceAccountCredentials` can't be copied (`cffi` won't allow it).
> Implementing basic HappyBase system test.

- gcloud/bigtable/happybase/table.py
- gcloud/bigtable/happybase/test_table.py
w00t!
This is the last PR that isn't system tests, docs or new stuff!
> Adding HappyBase Table.scan().

- gcloud/bigtable/happybase/table.py
- gcloud/bigtable/happybase/test_table.py
I took the [note][1] from HappyBase
> Note that application code should *never* store a incremented or decremented counter value directly; use the atomic `Table.counter_inc` and `Table.counter_dec` methods for that.
one step further and just made this `NotImplemented`.
[1]: https://github.com/wbolster/happybase/blob/9cbd718c10a3089f234f1eac1236b631e1f8e7cd/happybase/table.py#L531-L534
> Adding HappyBase Table.counter_set().

- docs/bigtable-client-intro.rst
- docs/bigtable-client.rst
- docs/bigtable-cluster-api.rst
- docs/bigtable-cluster.rst
- docs/bigtable-column-family.rst
- docs/bigtable-data-api.rst
- docs/bigtable-row-data.rst
- docs/bigtable-row.rst
- docs/bigtable-table-api.rst
- docs/bigtable-table.rst
- docs/bigtable-usage.rst
- docs/happybase-batch.rst
- docs/happybase-connection.rst
- docs/happybase-package.rst
- docs/happybase-pool.rst
- docs/happybase-table.rst
- docs/index.rst
- gcloud/bigtable/client.py
- gcloud/bigtable/cluster.py
- gcloud/bigtable/column_family.py
- gcloud/bigtable/happybase/__init__.py
- gcloud/bigtable/happybase/batch.py
- gcloud/bigtable/happybase/connection.py
- gcloud/bigtable/happybase/pool.py
- gcloud/bigtable/happybase/table.py
- gcloud/bigtable/row.py
- gcloud/bigtable/table.py
- gcloud/bigtable/test_cluster.py
- gcloud/bigtable/test_row.py
- scripts/verify_included_modules.py
Docs serving (for now at least, as of 12:45pm Pacific on Feb. 26): https://blog.bossylobster.com/gcloud-python/latest/bigtable-usage.html
> Adding Bigtable docs.

- gcloud/storage/blob.py
- gcloud/storage/test_blob.py
Cleaner alternative to PR #1556, with coverage.
> #1555: reload missing properties before blob download

- setup.py
- tox.ini
`grpcio` can only be installed with Python 2.7, so the `py27` tox environment is the only one that doesn't need to run without mocks.
FYI @jgeewax the `grpcio` install [fails][1] on Python 2.6 and 3.4 (didn't try 3.5).
- This won't run Py2.7 tests on AppVeyor with `grpcio` but will at least install it. I tried to tackle but can't write faithful powershell without a test machine
- If this works, I'll conditionally add the Bigtable tests (in Py2.7) in `attempt_system_tests.py`
[1]: https://gist.github.com/dhermes/74e5b8641375951f188a
> Adding grpcio to setup.py as an extra.

- gcloud/credentials.py
- gcloud/test_credentials.py
- setup.py
Fixes #1408.
-----
Woohoo it feels so good to delete so much code!
This PR is "just for display" until the next release of `oauth2client`, since it relies on https://github.com/google/oauth2client/pull/421.
/cc @nathanielmanistaatgoogle
> Removing crypto code and just relying on oauth2client helpers.

- setup.py
- tox.ini
See: https://github.com/GoogleCloudPlatform/gcloud-python/issues/1570
> Avoid protobuf 3.0.0.b2.post1.

- setup.py
We need to cut this release ASAP because of #1570.
> Upgrading version to 0.11.0

- gcloud/_helpers.py
- gcloud/connection.py
- gcloud/credentials.py
- gcloud/storage/blob.py
- gcloud/streaming/http_wrapper.py
- scripts/pylintrc_default
Nice bonus:  we get to remove a bunch of '# pylint: disable=E0401'.
> Hide 'six' and 'google.protobuf' from pylint's borked import sniffing.

- docs/bigtable-client-intro.rst
- docs/bigtable-cluster-api.rst
- docs/bigtable-data-api.rst
- docs/bigtable-row.rst
- gcloud/bigtable/happybase/table.py
- gcloud/bigtable/happybase/test_table.py
- gcloud/bigtable/row.py
- gcloud/bigtable/table.py
- gcloud/bigtable/test_row.py
- gcloud/bigtable/test_table.py
- scripts/pylintrc_default
- scripts/run_pylint.py
- system_tests/bigtable.py
Docs are still being updated, but I wanted to get this out there to speed up the review. Alternate implementation based on #1550.
I strongly urge reviewers to examine this commit-by-commit. The commit messages are fairly helpful (for the most part) and the diff of the PR as a whole is not so easy on the eyes.
Fixes #1548.
/cc @jonparrott @jgeewax
> Splitting Bigtable Row into 3 classes based on the mutation type / RPC method used in commit()

- gcloud/logging/logger.py
- gcloud/logging/test_logger.py
Doesn't yet expose any of the optional parameters (see #1566).
> Add 'Logger.log_text' method.

- gcloud/storage/bucket.py
- gcloud/storage/test_bucket.py
> Pass mutated properties through to 'bucket.create' API call.

- docs/pubsub-usage.rst
- gcloud/_helpers.py
- gcloud/pubsub/_helpers.py
- gcloud/pubsub/client.py
- gcloud/pubsub/test__helpers.py
- gcloud/pubsub/test_client.py
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
- gcloud/test__helpers.py
- system_tests/pubsub.py
Make it handle the fact that the API returns only subscription paths,
not resources.
Drop the 'topic_name' argument to 'Client.list_subscriptions'.
Fixes #1485.
> Add 'Topic.list_subscriptions'.

- gcloud/logging/logger.py
- gcloud/logging/test_logger.py
> Add 'Logger.log_struct'

- gcloud/logging/logger.py
- gcloud/logging/test_logger.py
> Add 'Logger.delete' method.

- gcloud/_helpers.py
- gcloud/pubsub/_helpers.py
- gcloud/pubsub/test__helpers.py
Zawinski's Law strikes again!
Fix bug introduced in #1580, and surfaced in the [system test failures following its merge](https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/114873442).
Project IDs have embedded hyphens;  topic / subscription names can have other punctuation.
This commit doesn't attempt to enforce the allowed punctuation, because we aren't validation user input with these patterns:  we only use them to parse out project IDs / topic names / subscription names from values emitted by the back-end.
> Fix topic subscription path patterns

- docs/logging-usage.rst
- gcloud/logging/logger.py
- gcloud/logging/test_logger.py
> Add 'Logger.list_entries'.

- docs/bigtable-row.rst
- gcloud/bigtable/row.py
- gcloud/bigtable/test_row.py
This is a follow-up to #1557 and prevents strange-ly true statements like `isinstance(cond_row, DirectRow)`.
Sorry it took me so many days. Code has been completely written for 2+ days but I haven't ever had my laptop near internet long enough to push it.
> Making common subclass for Bigtable DirectRow and ConditionalRow.

- docs/index.rst
- docs/logging-sink.rst
- gcloud/logging/client.py
- gcloud/logging/sink.py
- gcloud/logging/test_client.py
- gcloud/logging/test_sink.py
This PR punts on any answer to #1591.
> Add 'Sink.create' API wrapper and 'Client.sink' factory.

- gcloud/logging/sink.py
- gcloud/logging/test_sink.py
> Add 'Sink.reload' API wrapper.

- gcloud/logging/sink.py
- gcloud/logging/test_sink.py
> Add 'Sink.update' API wrapper.

- gcloud/bigtable/happybase/test_table.py
- gcloud/bigtable/row_filters.py
- gcloud/bigtable/test_row_filters.py
- system_tests/bigtable_happybase.py
These tests exposed an issue with regex filters. When a protobuf bytes field received a unicode object, bad things happened.
> Adding HappyBase system tests for families and counters.

- gcloud/logging/client.py
- gcloud/logging/sink.py
- gcloud/logging/test_client.py
- gcloud/logging/test_sink.py
> Add 'Client.list_sinks' API wrapper.

- gcloud/logging/metric.py
- gcloud/logging/test_metric.py
> Add 'Metrics.reload' API wrapper.

- docs/logging-usage.rst
- gcloud/logging/metric.py
- gcloud/logging/test_metric.py
> Add 'Metrics.update' API wrapper.

- gcloud/bigquery/table.py
- gcloud/bigquery/test_table.py
Enable the use of template tables by adding the `template_suffix` parameter. 
Documentation: https://cloud.google.com/bigquery/streaming-data-into-bigquery#template-tables
Would love tips on how you feel this should be tested.
> Add a template_suffix parameter to BigQuery Table.insert_data

- gcloud/logging/client.py
- gcloud/logging/metric.py
- gcloud/logging/test_client.py
- gcloud/logging/test_metric.py
Also, add 'Client.metric' factory.
~~Uses #1588 as a base.~~
> Add 'Client.list_metrics' API wrapper.

- system_tests/bigtable_happybase.py
This is the last PR to consider Bigtable ready to go. (There are a few more changes coming, but they aren't release-blocking.)
> Adding system tests for HappyBase Table.put() and delete().

- gcloud/logging/metric.py
- gcloud/logging/sink.py
- gcloud/logging/test_metric.py
- gcloud/logging/test_sink.py
- Spec mandates 'POST' to the container, rather than 'PUT' to the putative URL of the entity itself.
- Note that metric creation worked before;  sink creation is blocked due to permission issues (see #1614).
> Fix verb / target for 'Metric.create' / 'Sink.create'.

- gcloud/datastore/helpers.py
- gcloud/datastore/test_helpers.py
The protobuf itself will raise the error when an out-of-bounds int/long value is assigned.
Addresses:
https://github.com/google/protobuf/issues/1307#issuecomment-197596703.
> Drop look-before-leap use of protobuf-internal type checker.

- gcloud/pubsub/message.py
- gcloud/pubsub/test_message.py
Set via the back-end set 'publishTimestamp' field in the 'PubsbuMessage' resource.
Fixes #1623.
> Add 'Message.service_timestamp' property.

- system_tests/logging_.py
> Add system test for 'Client.metric' / 'Metric.create'.

- gcloud/bigtable/client.py
Cloud Bigtable scopes are of the form
`https://www.googleapis.com/auth/bigtable.*`
per the docs: https://cloud.google.com/bigtable/docs/creating-vm-instance
Previously, they were listed with the form
`https://www.googleapis.com/auth/cloud-bigtable.*` which are invalid,
leading to user-reported errors.
> Fix Cloud Bigtable scopes.

- gcloud/datastore/query.py
Update the documentation for `add_filter` to make it clear that filtering by key is also possible.
> Documentation: Filtering Query by key is also possible.

- gcloud/datastore/connection.py
- gcloud/datastore/test_connection.py
Addresses #1617 
Note that status has other information too that likely should get exposed. This is just an example of what the expected response is.
> Use status_pb2.Status to parse error messages from Datastore

- gcloud/logging/metric.py
- gcloud/logging/test_client.py
- gcloud/logging/test_metric.py
- system_tests/logging_.py
~~Uses #1610 as a base.~~
Note the changes to `gcloud.logging`:  the system test revealed that the API [returns "simple" names for the `LogMetric` resource](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/projects.metrics#LogMetric) (as documented, but which I misread as returning fully-qualified paths).
> Add system test for 'Client.list_metrics'.

- system_tests/attempt_system_tests.py
- tox.ini
Second (and third) attempt at #1633
> Adding Bigtable system tests to tox environment (for Py2.7 only).

- system_tests/logging_.py
> Add system test for 'Metric.update'.

- gcloud/client.py
- gcloud/datastore/client.py
- gcloud/test_client.py
Fixes #1625. Was "fixed" in #1505 but missed datastore.
FYI @pcostell
> Allow bytes or string as project value in datastore clients.

- gcloud/logging/client.py
- gcloud/logging/entries.py
- gcloud/logging/test_client.py
- gcloud/logging/test_entries.py
Uses #1574 as a base.
Note that we can't feasibly allow writing such entries until we have an answer for #1577.
> Add support for parsing log entries w/ 'protoPayload' from resources

- docs/index.rst
- docs/pubsub-iam.rst
- docs/pubsub-usage.rst
- gcloud/pubsub/iam.py
- gcloud/pubsub/test_iam.py
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
Returns an instance of `gcloud.pusub.iam.Policy`, parsed from the API response.
Toward #1073.
> Add 'Topic.get_iam_policy' API wrapper.

- system_tests/logging_.py
> Add system test for 'Sink.create', w/ Storage bucket destination

- docs/pubsub-usage.rst
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
> Add 'Topic.set_iam_policy' API wrapper.

- docs/pubsub-usage.rst
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
~~Uses #1641 as a base.~~
Toward #1073.
> Add 'Topic.test_iam_permissions' API wrapper.

- docs/pubsub-usage.rst
- gcloud/pubsub/subscription.py
- gcloud/pubsub/test_subscription.py
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
~~Uses #1644 as a base.~~
Toward #1073.
> Add 'Subscription.set_iam_policy' API wrapper.

- docs/pubsub-iam.rst
- docs/pubsub-usage.rst
- gcloud/pubsub/iam.py
- gcloud/pubsub/subscription.py
- gcloud/pubsub/test_iam.py
- gcloud/pubsub/test_subscription.py
- gcloud/pubsub/test_topic.py
~~Uses #1645 as a base.~~
Closes #1073.
> Add 'Subscription.test_iam_permissions' API wrapper.

- docs/dns-usage.rst
> Renaming type->record_type in DNS doc.

- gcloud/logging/entries.py
- gcloud/logging/logger.py
- gcloud/logging/test_entries.py
- gcloud/logging/test_logger.py
Also, add a helper to parse an entry's payload into a protobuf message object.
Closes #1577
> #1577:  allow logging protobuf entries

- tox.ini
Sphinx 1.4 dropped the dependency.
> Add explicit dep on 'sphinx_rtd_theme' for 'tox -e docs'.

- gcloud/storage/acl.py
- gcloud/storage/test_acl.py
Convert names from the XML API to the equivalent JSON names.
Fixes #1659.
> Allow predefined ACL names from either XML or JSON APIs.

- gcloud/logging/logger.py
- gcloud/logging/test_logger.py
Can be used as a context manager.
See:  #1565.
> Add 'logger.Batch' for logging multiple entries via a single API call.

- gcloud/logging/entries.py
- gcloud/logging/logger.py
- gcloud/logging/test_entries.py
- gcloud/logging/test_logger.py
Fetched entries expose labels set on the back-end.
When logging, labels can be passed in explicitly to the `log_text`, `log_struct`, or `log_proto` methods.  If not passed, any default values configured on the logger instance will be used.
See: #1566.
> Support entry labels

- gcloud/dns/client.py
I documented the error in the [issue](https://github.com/GoogleCloudPlatform/gcloud-python/issues/1650).
> Fix: Error Calling DNS#QOUTAS Issue: #1650

- gcloud/logging/entries.py
- gcloud/logging/logger.py
- gcloud/logging/test_entries.py
- gcloud/logging/test_logger.py
- `insert_id`
- `severity`
- `http_request`
See: #1566.
> Add support for logging w/ per-request metadata.

- docs/bigquery-usage.rst
Address three separate cases:
- Query finishes within timeout, with all rows present.
- Query finishes within timeout, but result set is too large for initial response.
- Query times out.
Closes #1551.
> Expand/clarify synchronous query usage docs.

- docs/pubsub-usage.rst
- gcloud/pubsub/iam.py
- gcloud/pubsub/subscription.py
- gcloud/pubsub/test_iam.py
- gcloud/pubsub/test_subscription.py
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
- system_tests/pubsub.py
The tests uncover a wart in the API:  `setIamPermissions` takes an extra wrapper element (`policy`) around the actual `Policy` resource.  I don't know where to report that issue.
The new system tests fail repeatedly for my system account with 503s:  adding retries (interspersed with `time.sleep(1)`) doesn't seem to help.  @tmatsuo can you comment?  (Note that I have made that account an owner of my project).
> Add system tests for topic/subscription IAM policy get/set methods.

- gcloud/bigquery/query.py
- gcloud/bigquery/test_query.py
> Cache job constructed for a synchronous query.

- system_tests/logging_.py
Fixes order-based failure between 'log_struct' and 'log_test'.
#1657 still breaks the teardown.
> Avoid reusing logger name in logging system tests 

- system_tests/logging_.py
Uses the Bigquery destination because that one runs quickest.
> Add system test for 'Sink.reload'.

- system_tests/logging_.py
Fixes: #1657.
Note for potential broader use toward #1619.
> Add exponential backoff for deletion failures.

- setup.py
@tseaver I'm going to start on the release notes. Can you draft the release notes for logging?
> Upgrading version to 0.12.0

- gcloud/pubsub/subscription.py
- gcloud/pubsub/test_subscription.py
- system_tests/pubsub.py
Problem observed when trying to clean up subscriptions after failing system tests:  the API returns '_deleted-topic_' for the topic path, which prevented us from unmarshalling the subscription.
We can't use `None` for the topic, because the subscription delegates some of its behavior through its topic.
> Handle subscriptions w/ deleted topics cleanly.

- docs/dns-usage.rst
Update usage docs for managing 'zone.changes'.
Closes #1603.
---------------------------
Fix example calls to 'zone.client' to pass required 'dns_name' argument.
Closes #1653.
> DNS docs cleanup

- gcloud/iterator.py
- gcloud/test_iterator.py
> Create a generic iterator wrapping 'list_*' methods of client-side objects

- setup.py
- tox.ini
Bump minimum required 'grpc' version to 0.13.1, which supports UCS-4 and UCS-2 builds on Linux.
Closes #1572.
> Restore 'grpc' extra for testing on Python 2.7.

- gcloud/test__helpers.py
I'm assuming the intent of test_module_property() is
to check that gcloud._helpers.UTC is defined and has
the right sort of value. It was failing if pytz
happened to be installed.
Note that the current test environment does _not_
install pytz. The gcloud package uses pytz if it is
available but does not depend on it.
> Allow unit tests to pass if pytz is installed.

- gcloud/bigquery/table.py
- gcloud/bigquery/test_table.py
> Omit 'schema' as part of 'Table.{create,update}' when 'view_query` is set

- gcloud/datastore/connection.py
- gcloud/datastore/test_connection.py
> Add /datastore/ in emulator URI path.

- CONTRIBUTING.rst
- docs/index.rst
- setup.py
> Stop requiring pyOpenSSL.

- gcloud/storage/blob.py
- gcloud/storage/test_blob.py
> Raise appropriate exception when upload fails.

- gcloud/dns/client.py
- gcloud/dns/test_client.py
- gcloud/dns/test_zone.py
- gcloud/dns/zone.py
> Allow constructing 'ManagedZone' instance w/o 'dns_name'.

- gcloud/dns/client.py
- gcloud/dns/test_client.py
- gcloud/dns/test_zone.py
- gcloud/dns/zone.py
~~Uses #1728 as a base.~~
Likewise, allow passing 'description' to 'Client.zone'.
Closes: #1721
> Allow passing 'description' 'ManagedZone.__init__'

- gcloud/dns/test_zone.py
- gcloud/dns/zone.py
~~Uses #1729 as a base.~~
Closes #1720.
> Update 'zone.dns_name' during 'zone.reload'. 

- setup.py
Starting release notes!
355899fb16bbdbc83aea6281e7535e21c70e8319
$ git log 0.12.0..HEAD \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
#1694
#1697
#1698
#1699
#1706
#1708
#1709
#1716
#1717
#1727
#1728
#1729
#1730
> Upgrading version to 0.12.1

- docs/_static/css/main.css
This allows the side-nav background color to extend
to the bottom of the screen.
**Before:**
**After:**
> Fix docs side-nav background.

- gcloud/_helpers.py
- gcloud/bigquery/test_query.py
- gcloud/bigtable/happybase/test_pool.py
- gcloud/datastore/test_helpers.py
- gcloud/logging/test_metric.py
- gcloud/logging/test_sink.py
- gcloud/search/test_index.py
- gcloud/storage/batch.py
- gcloud/storage/test_acl.py
- gcloud/storage/test_batch.py
- gcloud/storage/test_bucket.py
@tseaver These came up in discussion in #1691.
> Removing some YAGNI test fixtures and no cover pragmas.

- gcloud/pubsub/client.py
- gcloud/pubsub/connection.py
- gcloud/pubsub/subscription.py
- gcloud/pubsub/test_client.py
- gcloud/pubsub/test_connection.py
- gcloud/pubsub/test_subscription.py
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
- scripts/pylintrc_default
Encapsulate JSON/REST-specific knowledge inside the connection, allowing later use of a gRPC-based connection.
Toward #851 and #1696.
> Add methods to connection mapping API requests

- gcloud/pubsub/client.py
- gcloud/pubsub/connection.py
- gcloud/pubsub/subscription.py
- gcloud/pubsub/test_client.py
- gcloud/pubsub/test_connection.py
- gcloud/pubsub/test_subscription.py
- gcloud/pubsub/test_topic.py
- gcloud/pubsub/topic.py
~~Uses #1700 as a base.~~
Toward #851 / #1696.
> Factor out API helper classes from 'pubsub.Connection'.

- gcloud/bigtable/happybase/table.py
- gcloud/datastore/test_batch.py
- gcloud/datastore/test_connection.py
- gcloud/exceptions.py
- gcloud/search/document.py
- scripts/pylintrc_default
- system_tests/clear_datastore.py
- system_tests/populate_datastore.py
In the process, refactoring places where builtins were used intentionally or un-intentionally.
Inspired by discussion with @rimey in #1691.
> Re-enabling redefined-builtin for Pylint.

- tox.ini
FYI @rimey I'm not sure if you intended to make `py27-pandas` one of the default environments but the install takes quite a bit of time / it isn't strictly necessary.
> Removing py26 and pandas from default tox environments.

- setup.py
```
f227fdc96287d92ba7232f005a447b6af06a7525
$ git log 0.12.1..HEAD \
> | grep 'Merge pull request ' \
> | awk -F ' ' '{print $4}' \
> | sort
```
yields
#1700
#1733
#1734
#1736
#1737
#1738
#1691 didn't show up (because I merged it with GitHub's squash commit feature). If we use this feature I'll need to refine my release process to capture all PRs since the last release (maybe something already exists from GitHub that I don't know about).
> Upgrading version to 0.13.0.

- docs/pubsub-subscription.rst
- docs/pubsub-topic.rst
- docs/pubsub-usage.rst
- docs/pubsub_snippets.py
- gcloud/pubsub/client.py
- gcloud/pubsub/subscription.py
- gcloud/pubsub/test_subscription.py
- gcloud/pubsub/topic.py
- scripts/run_pylint.py
Toward #212, #1141, etc.
@dhermes, @jgeewax Not-yet-complete transformation, but worth discussing.
I'm basically ripping off the [snippet format](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/edcff8082a2c62b4e1866b28795f3dac92f8baaf/datastore/api/snippets.py) from @pcostell.
The snippets can be tested by running the file as a script, under an appropriately configured environment:
```bash
$ .tox/system-tests/bin/python docs/pubsub_snippets.py 
client_list_topics       : List topics for a project.
client_list_subscriptions: List all subscriptions for a project.
topic_create             : Create a topic.
topic_exists             : Test existence of a topic.
topic_delete             : Delete a topic.
topic_iam_policy         : Fetch / set a topic's IAM policy. …
```
> Make pubsub example snippets testable.

- gcloud/monitoring/__init__.py
This is so that "from gcloud.monitoring import *" doesn't import
the package's module names.
> Define __all__ in gcloud/monitoring/__init__.py.

- gcloud/monitoring/client.py
- gcloud/monitoring/metric.py
- gcloud/monitoring/test_metric.py
- system_tests/monitoring.py
@supriyagarg Could you please also take a look at this?
> Allow convenient filtering of metric descriptors by type prefix.

- system_tests/bigquery.py
- system_tests/bigtable.py
- system_tests/bigtable_happybase.py
- system_tests/clear_datastore.py
- system_tests/datastore.py
- system_tests/logging_.py
- system_tests/populate_datastore.py
- system_tests/pubsub.py
- system_tests/run_emulator.py
- system_tests/run_system_test.py
- system_tests/storage.py
- system_tests/system_test_utils.py
> Adding Travis build ID to resource names in system tests.

- system_tests/pubsub.py
> Skipping IAM system tests when running in emulator.

- docs/pubsub_snippets.py
- gcloud/pubsub/connection.py
In response to #1756.
Tweaking pubsub snippets to ensure that running them actually passes:
- Dropping a long-hanging example, never pulled into the Sphinx docs.
- Adding a `time.sleep(1)` between the last `topic.publish` call and the `subscription.pull`.
Also, fixes a bug exposed by running the snippets:  the API object's `subscription_pull` method was not tolerant of an empty response.
> Pubsub snippet fixups

- gcloud/datastore/helpers.py
- gcloud/datastore/test_helpers.py
> Allowing heterogeneous meanings for datastore list properties.

- gcloud/bigtable/happybase/__init__.py
> Removing mention of undocumented HappyBase functions.

- gcloud/bigquery/client.py
- gcloud/bigquery/table.py
- gcloud/logging/client.py
- gcloud/monitoring/query.py
- gcloud/monitoring/timeseries.py
- gcloud/storage/batch.py
- gcloud/streaming/http_wrapper.py
- There were just a couple typos with a semi-colon instead of a colon.
- Also, in the files that I had touched I converted types from `string` to `str` which is better supported by the documentation parsers.
> Docstring parse errors and switch from 'string' to 'str'

- gcloud/pubsub/iam.py
- gcloud/pubsub/test_iam.py
- gcloud/pubsub/test_subscription.py
- gcloud/pubsub/test_topic.py
Capture pubsub-specific 'publisher' and 'subscriber' roles.
See: https://cloud.google.com/pubsub/access_control#permissions
#1687 points out that `pubsub.topics.testIamPermissions` and `pubsub.subscriptions.testIamPermissions` take lists of *permissions*, rather than the roles which imply them.
> Enumerate all roles / permissions for Pubsub IAM.

- gcloud/bigquery/table.py
- gcloud/bigquery/test_table.py
- gcloud/streaming/test_transfer.py
- scripts/pylintrc_default
- scripts/run_pylint.py
- system_tests/bigtable.py
- Removing some ignore statements by moving some grpc sub-packages/sub-modules into "ignored-modules"
- Increasing test lines limit to 1900 and removing a line limit ignore at the top of the file
- Making remaining disables use verbose names instead of short names
- Locally re-enabling too-many-statements in `gcloud/bigquery/test_table.py` (was disabled at a scope but never re-enabled)
@tseaver This was inspired by #1779 (e.g. my [comment][1] made me wonder about this)
[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/1779/files#r62353060
> Small pylint clean-up.

- system_tests/pubsub.py
~~Uses #1776 as a base.~~
Closes #1687.
Closes #1743.
> Avoid get / set of IAM policy if current account doesn't have permission

- gcloud/_helpers.py
- gcloud/test__helpers.py
> Tolerate timestamps w/ truncated nanos.

- gcloud/bigquery/table.py
- gcloud/bigquery/test_table.py
- gcloud/streaming/test_transfer.py
- gcloud/streaming/transfer.py
Loosely based on [@joar's gist](https://gist.github.com/joar/ce5e54c0befd5ff24c312fcd62caab10)
Fixes #1760.
> Ensure that mulitpart bodies are always bytes.

- gcloud/pubsub/_gax.py
- gcloud/pubsub/connection.py
- gcloud/pubsub/test__gax.py
- gcloud/pubsub/test_connection.py
- setup.py
- tox.ini
Note:  paging methods (`list_topics` and `list_topic_subscriptions`) are only partially implemented, because the GAX API does not permit passing in a page token (it cam be coerced into *returning* only a single page of results, and its token, though).  See:
- googleapis/gax-python#86
- googleapis/gax-python#94
>  Implement a GAX version of '_PublisherAPI'.

- gcloud/pubsub/_gax.py
- gcloud/pubsub/connection.py
- gcloud/pubsub/test__gax.py
> Add GAX-based _SubscriberAPI.

- gcloud/pubsub/_gax.py
- gcloud/pubsub/test__gax.py
Ensure that mappings returned match those from the JSON API:  surfaced while exercising the `pubsub` system tests w/ `Gax`/`gRPC` binding enabled.
@dhermes the last diff below is an example of the downside of mocking the protobufs.  OTOH, the mock `_SubscriptionPB` is easier to construct than the "real" protobuf.
> Fix Gax marshalling of Subscription protobufs.

- gcloud/bigtable/client.py
- gcloud/bigtable/test_client.py
This allows using the Bigtable Client class in a `with` statement.
Fixes https://github.com/GoogleCloudPlatform/gcloud-python/issues/1793.
@dhermes Please take a look.
> Add context manager for Bigtable client.

- setup.py
```bash
e38b28e2972aeaf32e788850fd4b930c1f5f4a42
$ git log 0.13.0..HEAD | grep 'Merge pull request ' |  awk -F ' ' '{print $4}' | sort
```
#1690
#1741
#1745
#1746
#1747
#1748
#1750
#1751
#1752
#1753
#1757
#1758
#1759
#1764
#1765
#1769
#1773
#1776
#1779
#1780
#1782
#1785
#1794
#1795
#1798
> Cut 0.14.0 release.

- gcloud/datastore/connection.py
- gcloud/datastore/query.py
- gcloud/datastore/test_query.py
> Reducing limit or the life of a datastore query iterator.

- gcloud/bigtable/client.py
- gcloud/bigtable/test_client.py
This makes the `as` keyword work correctly in a with statement.
I missed this when fixing https://github.com/GoogleCloudPlatform/gcloud-python/issues/1793.
> Return self in Bigtable client __enter__.

- gcloud/_helpers.py
- gcloud/logging/_helpers.py
- gcloud/logging/entries.py
- gcloud/logging/test__helpers.py
- gcloud/test__helpers.py
The back-end apparently returns numeric project IDs in some cases.
Update `gcloud._helpers._name_from_project_path` to allow passing its `project` argument as `None` to disable the validation.
Closes: #1806.
> Don't enforce project ID validation when unmarshallig log entries

- docs/index.rst
- docs/translate-client.rst
- docs/translate-usage.rst
- gcloud/connection.py
- gcloud/pubsub/connection.py
- gcloud/translate/__init__.py
- gcloud/translate/client.py
- gcloud/translate/connection.py
- gcloud/translate/test_client.py
- gcloud/translate/test_connection.py
- scripts/verify_included_modules.py
- system_tests/attempt_system_tests.py
- system_tests/run_system_test.py
- system_tests/translate.py
~~Test forthcoming after API discussion.~~
Tests added in 2nd commit.
/cc @daspecster
> Basic implementation of Translate API.

- gcloud/logging/client.py
- gcloud/logging/connection.py
- gcloud/logging/logger.py
- gcloud/logging/metric.py
- gcloud/logging/sink.py
- gcloud/logging/test_client.py
- gcloud/logging/test_connection.py
- gcloud/logging/test_logger.py
- gcloud/logging/test_metric.py
- gcloud/logging/test_sink.py
Modeled on the `pubsub` changes in #1700 and #1736.
> Factor API-related calls into service-specific helpers.

- gcloud/logging/client.py
- gcloud/logging/test_client.py
Broken in #1820.  Borked logging system tests pass with this patch.
> Repair logging client 'list_*' methods.

- gcloud/logging/metric.py
- gcloud/logging/sink.py
- gcloud/logging/test_client.py
- gcloud/logging/test_metric.py
- gcloud/logging/test_sink.py
- system_tests/logging_.py
Resource's `name` field is not a path (like metric).
Also, drop the no-longer-needed name-from-path regexps/helpers for metric and sink.
Add a system test for `Client.list_sinks` which exercises `Sink.from_api_repr` against real resource data.
Closes #1817.
> Fix 'Sink.from_api_repr'.

- docs/pubsub_snippets.py
- gcloud/bigquery/__init__.py
- gcloud/bigquery/dataset.py
- gcloud/bigquery/table.py
- gcloud/bigquery/test_dataset.py
- gcloud/bigquery/test_table.py
Toward a real fix for #1786 and related issues (usage docs out-of-sync with API surface).
> Prepare for making snippets testable

- gcloud/bigquery/query.py
- gcloud/bigquery/test_query.py
Hi,
I needed to get an estimated cost for some bigquery queries and found that there is a dryRun option for queries.
Unfortunately the dryRun option wasn't exposed via gcloud, so here is a PR to add that ability.
Thanks
> Dry Run for bigquery queries

- setup.py
/cc @waprin
---
```
b27907be562e81a10abe258ee32d039146e65768
$ git log 0.14.0..HEAD | grep 'Merge pull request ' |  awk -F ' ' '{print $4}' | sort
```
yields
#1772
#1787
#1802
#1804
#1805
#1808
#1810
#1820
#1823
#1825
#1831
#1834
> Cut 0.15.0 release.

- _testing/grpc/beta/interfaces.py
- _testing/grpc/framework/interfaces/face/face.py
- gcloud/bigtable/happybase/connection.py
- gcloud/bigtable/happybase/test_connection.py
Fixes #1818.
NOTE: For now I just used a `happybase` import so that I could get the tests passing locally via `nosetests`. However, these tests will fail on Travis. I don't think we should take on the [Happybase][1] library as a dependency. Maybe @tswast has some opinions?
Potential option: try to import it (like we do with `pytz` / `pandas` / etc.) and then use it if it's there for the "native" exception
/cc @tswast 
[1]: https://pypi.python.org/pypi/happybase
> Wrapping gRPC "already exists" with a HappyBase exception.

- docs/logging-usage.rst
- gcloud/logging/logger.py
- gcloud/logging/test_logger.py
Two changes here:
logger.list_entries() was using just the logger name rather than the fully qualified name, you can see an example on [the docs ](https://cloud.google.com/logging/docs/view/advanced_filters#names)that from v1 to v2 the change from log to logName also changed to expect fully qualified name.
The query was also using the colon operator, which is a "has" operator. Problem 1 is that this is a slower query because it's not indexed, problem 2 is that I'm pretty sure there's a bug because it's not working.
Second set of changes is the docs, just some random small discrepancies between them and the actual API. The biggest discrepancy was in the Sink constructor, the samples all use keyword arguments and special names for different sink types, the actual code seems to take these …
> logger.list_entries optimization using equals  and docs update

- docs/gcloud-auth.rst
gcloud  has a new command for creating ADC. The idea is that `gcloud auth login` is for authenticating the CLI and `gcloud beta auth application-default login` creates credentials for client code. After a transition period, `gcloud auth login` will no longer write credentials to a well-known file and so will not work.
> Recommend new ADC command

- .coveragerc
- gcloud/pubsub/_gax.py
- gcloud/pubsub/test__gax.py
- setup.py
- tox.ini
Fixes failures on `master` following Friday's release of `gax-google-pubsub-v1 0.7.6`.
@daspecster PTAL.
> Add support for controlled paging via Gax.

- gcloud/pubsub/client.py
- gcloud/pubsub/test_client.py
Not yet ready to merge, as the system tests will break until new versions of `grpcio` and `google-gax-pubusb-v1` are released (see #1814).
@dhermes PTAL at the overall approach to choosing gRPC vs. JSON-over-HTTP.
> Select API helper based on presence of grpcio + optional environment marker

- gcloud/_helpers.py
- gcloud/storage/blob.py
- gcloud/storage/test_blob.py
- gcloud/test__helpers.py
Possible solution to resolve #1841.
I think my tests could use some feedback.
> Add customer-supplied encryption to storage

- docs/bigtable-client-intro.rst
- docs/bigtable-client.rst
- docs/bigtable-cluster-api.rst
- docs/bigtable-cluster.rst
- docs/bigtable-column-family.rst
- docs/bigtable-data-api.rst
- docs/bigtable-row-data.rst
- docs/bigtable-row-filters.rst
- docs/bigtable-row.rst
- docs/bigtable-table-api.rst
- docs/bigtable-table.rst
- docs/bigtable-usage.rst
- docs/happybase-batch.rst
- docs/happybase-connection.rst
- docs/happybase-package.rst
- docs/happybase-pool.rst
- docs/happybase-table.rst
- gcloud/bigtable/__init__.py
- scripts/verify_included_modules.py
- setup.py
- Adding an import error with a nice failure message in `gcloud.bigtable` in the absence of `grpcio`
- Making `setup.py` include `grpcio` conditional on being Python 2.7
- Adding a warning to every single Bigtable docs page explaining that it can't be used outside of Python 2.7
/cc @jgeewax
> Making grpcio install require fewer keystrokes.

- gcloud/datastore/client.py
- gcloud/datastore/test_client.py
- system_tests/datastore.py
> Add support for serialized/transactional read in 'Client.get{,_multi}'.

- docs/pubsub_snippets.py
Exercising `grpcio` and related packages under Python 3.4, per https://github.com/grpc/grpc/issues/282#issuecomment-226014975
> Py3k compatibility for snippet execution.

- docs/gcloud-auth.rst
- docs/gcloud-config.rst
- docs/index.rst
- gcloud/_helpers.py
- gcloud/test__helpers.py
This is a possible resolution to #1792, making it easier to follow along with the documentation.
I looked for a way to clarify the documentation for this but it looks like this should make it work in the way that the documentation shows already.
> Get project ID from JSON credentials file

- gcloud/logging/client.py
- gcloud/logging/metric.py
- gcloud/logging/sink.py
- gcloud/logging/test_client.py
- gcloud/logging/test_metric.py
- gcloud/logging/test_sink.py
Closes #1856.
@daspecster PTAL
> Ease construction of 'Sink'/'Metric' instances to be reloaded.

- setup.py
Possible solution for grpcio not compiling on docs generation.
See: #1864
/cc @dhermes @tseaver
> Exclude grpcio when generating docs.

- gcloud/test__helpers.py
Partial fix for https://github.com/GoogleCloudPlatform/gcloud-python/issues/1863.
https://ci.appveyor.com/project/daspecster/gcloud-python-utjkc
Thanks for the fix @dhermes!
LMKWYT @tseaver
> Fix IO Permissions on Appveyor.

- gcloud/test__helpers.py
Simultaneous / parallel runs could compete for it.
Also fixes coverage gap in the teardown.
> Avoid a clash over temporary '.config' directory.

- gcloud/pubsub/_gax.py
- gcloud/pubsub/connection.py
- gcloud/pubsub/test__gax.py
Work toward fixing Pubsub system tests using GAX.
Correcting incomplete fixes in #1855.
Note that `Topic.pull` is still problematic (#1869).
> More gax paging fixes

- gcloud/pubsub/client.py
Re-enable via environment variable, 'GCLOUD_ENABLE_GAX'.
See #1873 for post-0.16.0 follow-up.
> Disable pubsub-over-gax by default.

- setup.py
There's a few things we need to do before we cut this.
> Update to version 0.16.0

- appveyor.yml
> WAG:  try to preinstall 'grpcio' on appveyor.

- appveyor.yml
`grpcio` 0.14.0 installs without errors on Python 3.4+.
See #1863, failures after merging #1877.
> Drop Python 2.6 on appveyor, install 'grpcio' unconditionally.

- gcloud/logging/_gax.py
- gcloud/logging/test__gax.py
- gcloud/logging/test_connection.py
> Implement GAX Sinks API helper.

- gcloud/logging/_gax.py
- gcloud/logging/test__gax.py
> Implement GAX Metrics API helper.

- gcloud/logging/_gax.py
- gcloud/logging/test__gax.py
> _LoggingAPI: impedance matching with JSON API.

- docs/bigtable-table-api.rst
- gcloud/bigtable/table.py
- gcloud/bigtable/test_table.py
- system_tests/bigtable.py
It was never actually implemented on the back-end in V1, and has been dropped altogether in V2.
> Drop 'Table.rename'.

- gcloud/bigtable/read-rows-acceptance-test.json
- gcloud/bigtable/row_data.py
- gcloud/bigtable/test_row_data.py
~~Uses #1903 as a base.~~
Adds tests based on [JSON acceptance tests](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core/src/test/resources/com/google/cloud/bigtable/grpc/scanner/v2/read-rows-acceptance-test.json)/
> Add 'ReadRowsResponseV2' wrapper

- gcloud/bigtable/client.py
- gcloud/bigtable/cluster.py
- gcloud/bigtable/column_family.py
- gcloud/bigtable/row.py
- gcloud/bigtable/row_filters.py
- gcloud/bigtable/table.py
- gcloud/bigtable/test_client.py
- gcloud/bigtable/test_cluster.py
- gcloud/bigtable/test_column_family.py
- gcloud/bigtable/test_row.py
- gcloud/bigtable/test_row_data.py
- gcloud/bigtable/test_row_filters.py
- gcloud/bigtable/test_table.py
Indicate their V1 source in their names.
Prepratory to converting to V2 equivalents.
> Alias Bigtable V1 imports / factories / entry point constants.

- gcloud/_testing.py
- gcloud/pubsub/_gax.py
- gcloud/pubsub/test__gax.py
Closes #1869.
Works around https://github.com/googleapis/gax-python/issues/113.
/cc @bjwatson, @geigerj
> Disable GAX bundling for 'Topic.publish'.

- gcloud/bigtable/column_family.py
- gcloud/bigtable/test_column_family.py
~~Uses #1912 as a base.~~
Note that `{Create,Update,Delete}ColumnFamily` messages all collapse to `ModifyColumnFamilies`.
> Update bigtable.column_family to use V2 protos

- docs/_static/css/main.css
The fixed header isn't accounted for when scrolling to anchor points so the original anchor text is obscured.
I would actually prefer to remove the fixed header instead of merging this PR. If it's ok to remove the fixed header let me know and I can do that instead!
> Adjust anchor scroll in docs to show actual line.

- gcloud/bigtable/row_data.py
- gcloud/bigtable/test_row_data.py
Distinguish response-level errors from invalid chunks.
JSON testcases ending in an incomplete row should not raise errors.
For "invalid" JSON testcases, verify that completed, non-error rows match expected results.
> Clarify handling of V2 'ReadRowsResponse' error cases

- README.rst
@tseaver LMKWYT and if there's anything I should add.
/cc @dhermes
> Add Logging to README.md.

- docs/logging-usage.rst
Attempted solution for https://github.com/GoogleCloudPlatform/gcloud-python/issues/1890#issuecomment-228491822
> Add docs, exporting logging to storage permissions.

- README.rst
@tseaver there might be a better example to throw in here. If so just let me know and I'll add it.
/cc @dhermes
> Add BigQuery example to README.md.

- gcloud/bigtable/row.py
- gcloud/bigtable/row_data.py
- gcloud/bigtable/row_filters.py
- gcloud/bigtable/table.py
- gcloud/bigtable/test_row.py
- gcloud/bigtable/test_row_data.py
- gcloud/bigtable/test_row_filters.py
- gcloud/bigtable/test_table.py
Folds new `ReadRowsResponse` logic from #1907, #1915 into table row handling.
Apologies for the size of this PR:  it turned out to be a bit of a "take one sip from a spittoon" problem.
> Convert non-instance-admin protos to Bigtable V2

- gcloud/logging/_gax.py
- gcloud/logging/client.py
- gcloud/logging/test__gax.py
- gcloud/logging/test_client.py
Uses #1892 as a base.
Available when `grpcio` and related packages are importable.
Enable via `GCLOUD_ENABLE_GAX` environment variable.  Disabled by default due to #1873.
> Enable logging-over-gRPC

- .gitignore
- Makefile.bigtable_v1
- Makefile.bigtable_v2
- Makefile.datastore
- gcloud/bigtable/_generated_v2/_bigtable.proto
- gcloud/bigtable/_generated_v2/_bigtable_instance_admin.proto
- gcloud/bigtable/_generated_v2/_bigtable_table_admin.proto
- gcloud/bigtable/_generated_v2/_common.proto
- gcloud/bigtable/_generated_v2/_data.proto
- gcloud/bigtable/_generated_v2/_instance.proto
- gcloud/bigtable/_generated_v2/_table.proto
- gcloud/bigtable/_generated_v2/bigtable_instance_admin_pb2.py
- gcloud/bigtable/_generated_v2/bigtable_pb2.py
- gcloud/bigtable/_generated_v2/bigtable_table_admin_pb2.py
- gcloud/bigtable/_generated_v2/operations_grpc_pb2.py
- gcloud/bigtable/_generated_v2/table_pb2.py
- gcloud/bigtable/cluster.py
- gcloud/bigtable/instance.py
- gcloud/bigtable/table.py
- gcloud/bigtable/test_cluster.py
- gcloud/bigtable/test_instance.py
- gcloud/bigtable/test_table.py
- scripts/make_datastore_grpc.py
- scripts/make_operations_grpc.py
- scripts/rewrite_imports.py
See #1918.
In order to make the generation process repeatable, I updated the makefiles to create a virtualenv and install the latest `grpcio` / `grpcio-tools`:  the latter can then be used to generate gRPC-aware stubs from protos, without relying on any other `protoc` compiler.
Note that I don't actually update the generated code for `datastore` or `bigtable` V1 protos: although they do generate cleanly, examinig the diffs closely is off my radar for now.
> Regenerate from final Bigtable v2  v2 protos

- gcloud/_helpers.py
- gcloud/test__helpers.py
`os.path.expanduser` imports the `pwd` module which is [not supported by GAE](https://cloud.google.com/appengine/kb/?csw=1#libraries).
This should resolve #1922.
> Resolve issues with GAE and os.path.expanduser()

- CONTRIBUTING.rst
- docs/index.rst
- docs/logging-handlers.rst
- docs/logging-usage.rst
- gcloud/logging/handlers.py
- gcloud/logging/test_handlers.py
- system_tests/logging_.py
New PR for #1497 , replaces #1881 .
> Add Logging Handler

- gcloud/bigtable/_generated_v2/operations_grpc_pb2.py
- gcloud/bigtable/client.py
- gcloud/bigtable/column_family.py
- gcloud/bigtable/instance.py
- gcloud/bigtable/row.py
- gcloud/bigtable/test_client.py
- gcloud/bigtable/test_column_family.py
- gcloud/bigtable/test_instance.py
- gcloud/bigtable/test_row.py
- system_tests/bigtable.py
/cc @garye, @lesv, @sduskis, @tswast, @mbrukman, @jgeewax
> Bigtable system tests passing against V2 endpoints
