gcloud/datastore/__init__.py, gcloud/datastore/_implicit_environ.py, gcloud/datastore/test___init__.py
=> Derive implicit dataset ID from environment.

gcloud/storage/blob.py, gcloud/storage/bucket.py, gcloud/storage/connection.py, gcloud/storage/iterator.py, gcloud/storage/test_blob.py, gcloud/storage/test_bucket.py
See #545 for context.
**NOTE**: Has #560 as a diffbase.
=> Folding Blob.from_dict and Bucket.from_dict into constructors.

gcloud/storage/__init__.py, gcloud/storage/_implicit_environ.py, gcloud/storage/test___init__.py
=> Adding methods for default / implicit behavior in storage.

regression/regression_utils.py, regression/storage.py
**NOTE**: Uses #570 as diffbase.
=> Uses implicit behavior in storage regression

setup.py
@tseaver It [seems][1] I'll need to create the tag after this PR is accepted (can't bring in tags in PRs).
After that I'll create and document a [release][2].
[1]: http://stackoverflow.com/a/12279290/1068170
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/releases
=> Updating to version 0.4.0 for PyPI release.

run_pylint.py
Added check for breaking around a binary operator.
=> Appease pylint 1.6.2:

index.html
=> Removing set_defaults() from landing page.

gcloud/storage/bucket.py, gcloud/storage/test_bucket.py
=> Removing patch() from Bucket.configure_website.

gcloud/storage/api.py, gcloud/storage/bucket.py, gcloud/storage/test_bucket.py
=> Adding Bucket.create() method.

docs/_static/js/main.js, docs/index.rst, docs/pubsub-api.rst, docs/pubsub-subscription.rst, docs/pubsub-surface.rst, docs/pubsub-topic.rst
Also removing tabs from `docs/_static/js/main.js`
@tseaver Do we want to leave the doc you wrote in place? Certain things in there like `# API request` need to be cleaned up if it's going to be permanent.
=> Adding Pub/Sub docs and JS to dedent for the section header.

setup.py
Also changing author to something more official / encompassing. (or at least aspiring to do so)
@jgeewax What should the author be?
----
Using last release PR (#723) as a template.
=> Upgrading version to 0.5.0.

tox.ini
=> Adding passenv to tox coveralls rule.

setup.py
Using last release PR (#813) as a template.
=> Upgrading version to 0.6.0.

docs/datastore-client.rst, docs/index.rst
=> Fixing location and name of dataset doc.

docs/pubsub-usage.rst
=> Fixes non-blocking example in pub/sub usage doc.

gcloud/storage/client.py, gcloud/storage/test_client.py
=> Adding basic client class in storage.

gcloud/datastore/client.py, gcloud/datastore/test_client.py, system_tests/datastore.py
See: https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/70509954
=> Restore system-test fixes lost in merge.

gcloud/pubsub/connection.py, gcloud/pubsub/subscription.py, gcloud/pubsub/test_subscription.py
=> Upgrading pubsub to v1.

docs/index.rst
=> Re-order pubsub subscription vs. topic in headers.

system_tests/bigquery.py
Late commit (3e10352) in #1056.
@dhermes PTAL -- I'd like to merge this soonest to unbreak the trunk.
=> Fix broken system test

index.html
=> Making docs dropdown in alphabetical order on landing page.

docs/_templates/layout.html
=> Making docs dropdown in alphabetical order.

gcloud/dns/__init__.py, gcloud/dns/client.py, gcloud/dns/connection.py, gcloud/dns/test_client.py, gcloud/dns/test_connection.py
=> Add DNS client / connection

docs/resource-manager-api.rst
=> Separating client construction from method calls in Resource Mgr. Docs.

setup.py
@tseaver We should hold off on this until the DNS docs are in.
=> Upgrading version to 0.8.0.

CONTRIBUTING.rst
It might make sense to have both ways of authenticating here.
=> Add both P12 config and JSON credentials

gcloud/_apitools/stream_slice.py, gcloud/_apitools/test_stream_slice.py
=> Coverage for 'gcloud._apitools.stream_slice'

docs/bigquery-usage.rst
Also fix a long-line usage for the service account
factory constructor.
=> Fix formatting on BigQuery usage methods.

gcloud/bigtable/column_family.py, gcloud/bigtable/table.py, gcloud/bigtable/test_column_family.py, gcloud/bigtable/test_table.py
In the process, also upgrading the column family factor on the
`Table` class and adding a `ColumnFamily.name` property for
comparison with the retrieved protobuf.
=> Implementing Bigtable list_column_families().

gcloud/connection.py, gcloud/datastore/connection.py, gcloud/datastore/test_connection.py, gcloud/environment_vars.py, gcloud/pubsub/connection.py, gcloud/pubsub/test_connection.py
See https://github.com/GoogleCloudPlatform/gcloud-common/issues/48
=> Support Pub/Sub emulator environment var.

gcloud/datastore/entity.py, gcloud/datastore/test_entity.py
=> Adding excludes and meanings to Entity equality check.

Makefile, gcloud/bigtable/_generated/bigtable_cluster_data_pb2.py, gcloud/bigtable/_generated/bigtable_cluster_service_messages_pb2.py, gcloud/bigtable/_generated/bigtable_data_pb2.py, gcloud/bigtable/_generated/bigtable_service_messages_pb2.py, gcloud/bigtable/_generated/bigtable_table_data_pb2.py, gcloud/bigtable/_generated/bigtable_table_service_messages_pb2.py
~~**NOTE**: Has #1353 as diffbase.~~
Also re-running the generate rule and updating the files that don't need gRPC.
=> Updating Makefile to only use gRPC when needed.

gcloud/bigquery/client.py, gcloud/bigquery/test_client.py
=> #1424: Defend against missing 'datasets' key in datasets/list response.

gcloud/datastore/helpers.py, gcloud/datastore/test_helpers.py
=> Upgrading Entity.property to properties map in datastore.

gcloud/datastore/helpers.py, gcloud/datastore/test_helpers.py
=> Upgrading timestamp_microseconds_value to timestamp_value.

setup.py
Release notes will be forthcoming
=> Upgrading version to 0.10.0.

gcloud/bigtable/happybase/batch.py, gcloud/bigtable/happybase/table.py, gcloud/bigtable/happybase/test_batch.py, gcloud/bigtable/happybase/test_table.py
Also implementing HappyBase Table.batch() factory.
=> Adding HappyBase batch send() and batch context manager.

docs/bigquery-usage.rst
=> Updating SchemaField creation in BigQuery usage doc.

gcloud/logging/sink.py, gcloud/logging/test_sink.py
=> Add 'Sink.exists' API wrapper.

gcloud/logging/sink.py, gcloud/logging/test_sink.py
=> Add 'Sink.delete' API wrapper.

gcloud/logging/metric.py, gcloud/logging/test_metric.py
=> Add 'Metrics.exists' API wrapper.

gcloud/logging/metric.py, gcloud/logging/test_metric.py
=> Add 'Metrics.delete' API wrapper.

gcloud/datastore/query.py
Missing colon prevented the rST from rendering properly.
=> Fix broken docs for `Query.add_filter`

gcloud/pubsub/message.py
@dhermes I will merge as soon as Travis passes.
=> Typo fix lost merging #1627.

system_tests/attempt_system_tests.py
Reverts GoogleCloudPlatform/gcloud-python#1633
=> Revert "Adding Bigtable system tests to list of default system tests."

system_tests/logging_.py
=> Add system test for 'Metric.reload'.

docs/pubsub-usage.rst, gcloud/pubsub/subscription.py, gcloud/pubsub/test_subscription.py
=> Add 'Subscription.get_iam_policy' API wrapper.

docs/pubsub-usage.rst, gcloud/pubsub/subscription.py, gcloud/pubsub/test_subscription.py, gcloud/pubsub/test_topic.py, gcloud/pubsub/topic.py
=> Rename 'Topic.test_iam_permissions' -> 'check_iam_permissions.'

system_tests/logging_.py
@dhermes Resumed from #1656.  Squashed, as well.
=> Add system test for 'Sink.create' using a Pubsub topic

gcloud/pubsub/subscription.py
=> Fix ref link in 'modify_ack_deadline' docstring.

docs/search-usage.rst
=> Adding note about Search API whitelist.

system_tests/attempt_system_tests.py
=> Add logging and monitoring to the set of system tests run by default.

setup.py
PyPI:  https://pypi.python.org/pypi/gax-google-pubsub-v1
Github: https://github.com/googleapis/googleapis
=> Add 'gax-google-pubsub-v1' dependency to 'grpc' extra.

docs/monitoring-resource.rst, docs/monitoring-usage.rst, gcloud/monitoring/client.py, gcloud/monitoring/label.py, gcloud/monitoring/metric.py, gcloud/monitoring/query.py, gcloud/monitoring/resource.py, gcloud/monitoring/test_client.py, gcloud/monitoring/test_label.py, gcloud/monitoring/test_metric.py, system_tests/monitoring.py
=> Add support for creating and deleting descriptors for custom metrics.

docs/dns-usage.rst
=> DNS usage: fix name of method used to initiate a changeset

LICENSE
http://www.apache.org/licenses/LICENSE-2.0.txt
Specifically, fix the brackets. All other changes are just whitespace.
=> Fix LICENSE to match http://www.apache.org/licenses/LICENSE-2.0.txt

.travis.yml, setup.cfg
See https://github.com/GoogleCloudPlatform/gcloud-python/issues/1879#issuecomment-229444782
=> Disable broken wheel building

docs/bigtable-instance-api.rst
@tseaver this addresses my own comments on PR #1932.
=> Fixed spelling and formatting.

docs/resource-manager-api.rst
=> Fix #1957 - Typo in RM docs

docs/bigquery-usage.rst, docs/bigquery_snippets.py
~~Uses #1832 as a base.~~
Toward a real fix for #1786 and related issues (usage docs out-of-sync with API surface).
=> Make table snippets testable

docs/_static/images/icon-lang-dotnet.svg, docs/_templates/layout.html
Closes https://github.com/GoogleCloudPlatform/gcloud-common/issues/151
=> Add dotnet link to navigation

_landing-page-static/images/icon-lang-dotnet.svg, index.html
=> Adding .NET to landing page.

docs/pubsub-usage.rst
AFAICT, this wasn't supposed to be there?
Let me know if it is and I can account for it in #1775.
=> Remove unused doctest directive.

.travis.yml, tox.ini
My oversight, this fails outside of tox because it doesn't have some of the deps installed.
=> Switch to using tox for calling json docs update script

docs/json/json/home.html
Fixes #2193 
Preview: http://daspecster.github.io/gcloud-python/#/
=> Too much whitespace on home example.

docs/bigquery-usage.rst
=> Fix 'destination_table' attribute typo in BQ usage docs.

system_tests/language.py
=> Making sure language system test teardown deletes bucket.

docs/bigquery-usage.rst
=> Replace 'job.submit' w/ 'job.begin' in usage docs.

google/cloud/bigquery/_helpers.py
Addresses:
https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2321#pullrequestreview-204862
=> Review tweak.

README.rst
This should be fine to LGTM with no CI, since the README is the only change.
=> Adding AppVeyor badge.

google/cloud/bigquery/table.py, unit_tests/bigquery/test_table.py
=> Support `r+` mode files when uploading to table

.travis.yml
From discussion with @jonparrott (hence the assignment)
=> Grouping pip upgrades on Travis.

google/cloud/bigquery/job.py, unit_tests/bigquery/test_job.py
=> Add 'dry_run' support for async query jobs

README.rst, core/google/cloud/iterator.py, google/cloud/monitoring/group.py, google/cloud/resource_manager/client.py, scripts/generate_json_docs.py, storage/google/cloud/storage/__init__.py, storage/google/cloud/storage/acl.py, storage/google/cloud/storage/bucket.py, storage/google/cloud/storage/client.py
**NOTE**: I should probably just wait until the re-packaging stuff is done to merge.
=> Making prints Python 3 friendly.

docs/requirements.txt
See #2444, in particular https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2444#issuecomment-249918422
=> Re-ordering local docs directories based on dependency order.

bigquery/README.rst, bigquery/google/cloud/bigquery/__init__.py, bigquery/google/cloud/bigquery/connection.py, docs/bigquery_snippets.py
**NOTE**: There are no code changes so Travis CI shouldn't matter (though `tox -e docs` might)
=> Changing all "Cloud BigQuery" mentions to "BigQuery".

docs/logging-usage.rst
Currently kwargs are not supported, though adding them would probably be a good feature.
=> Fix log_struct usage

logging/google/cloud/logging/_gax.py, logging/setup.py, pubsub/google/cloud/pubsub/_gax.py, pubsub/setup.py
This resolves the `google-gax` 0.14.* conflict.
As a side effect this should finally fix the RTD build breakage.
/cc @bjwatson
=> Upgrading versions of GAPIC and gRPC generated libraries.

_landing-page-static/css/main.css
=> Removing button rotation

monitoring/tox.ini, tox.ini
=> Moving pandas tox env. into monitoring config.

bigquery/README.rst, bigtable/README.rst, core/README.rst, datastore/README.rst, dns/README.rst, error_reporting/README.rst, language/README.rst, logging/README.rst, monitoring/README.rst, pubsub/README.rst, resource_manager/README.rst, speech/README.rst, storage/README.rst, translate/README.rst, vision/README.rst
Also removing duplicate "Homepage" links (duplicate of "API Documentation" links).
h/t to @tswast for pointing out the issue
=> Updating package README's with more useful doc links.

scripts/pycodestyle_on_repo.py, tox.ini
=> Adding back local dependencies to system test tox envs.

storage/google/cloud/storage/blob.py, storage/unit_tests/test_blob.py, system_tests/storage.py
=> Add 'Blob.compose' API wrapper method.

bigquery/google/cloud/bigquery/client.py, bigquery/unit_tests/test_client.py, docs/bigquery_snippets.py, system_tests/bigquery.py
~~Alternative to #2554 with #2558 as diffbase.~~
Still to be covered:
- `bigquery.dataset.Dataset.list_tables`
- `bigquery.query.QueryResults.fetch_data`
- `bigquery.query.QueryResults._build_resource`
- `bigquery.table.Table.fetch_data`
=> Updating Client.list_* methods in BigQuery to use Iterators.

core/google/cloud/client.py
Noticed this in the docs. Small, but every bit helps.
=> Fixes typo

docs/storage-blobs.rst, docs/storage-buckets.rst
=> Surface inherited members for Bucket/Blob.

speech/google/cloud/speech/_gax.py, speech/google/cloud/speech/client.py, speech/unit_tests/test_client.py
Preparation for adding async gapic. Separating this into the `_JSONSpeechAPI` class.
=> Move async JSON logic to _JSONSpeechAPI.

logging/google/cloud/logging/_gax.py, logging/google/cloud/logging/client.py, logging/google/cloud/logging/connection.py, logging/google/cloud/logging/entries.py, logging/google/cloud/logging/logger.py, logging/google/cloud/logging/metric.py, logging/google/cloud/logging/sink.py
Follow-on to #2625.
/cc @omaray
=> Fix up logging docs URLs after 'v2beta1' -> 'v2' transition.

system_tests/speech.py
Forgot to update references after making AUDIO_FILE global.
=> Fix forgotten reference to AUDIO_FILE.

system_tests/logging_.py
See: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds/172150060
=> Fix error-handling in Logging system test.

runtimeconfig/README.rst, runtimeconfig/setup.py
=> runtimeconfig: mark package as alpha

.coveragerc, core/google/cloud/_testing.py
See for example: https://coveralls.io/builds/8709614
=> Getting umbrella coverage back to 100%.

CONTRIBUTING.rst
Add link to article @dhermes mentioned about streamlining pull requests.
=> Add link to Kubernetes faster pull request review article.

bigquery/google/cloud/bigquery/_helpers.py, bigquery/unit_tests/test__helpers.py
Alias for 'BOOLEAN' in legacy SQL.
=> Add support for standard SQL 'BOOL' type.

README.rst
@dhermes sorry about that, this time I looked and it looks right.
=> Fix Markdown syntax in README to RST

datastore/google/cloud/datastore/__init__.py
It turns out Sphinx allows this outside of a sandbox.
=> Removing os.environ patching in doctest.

README.rst, bigtable/README.rst, dns/README.rst, error_reporting/README.rst, language/README.rst, runtimeconfig/README.rst, translate/README.rst, vision/README.rst
=> Removing links to "stable" build of RTD.

vision/tox.ini
Follow up from https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2826#discussion_r91187095.
=> Remove unneeded dependency.

system_tests/vision.py
Towards #2753
Adds system tests for `detect_safe_search()`.
Only `detect_properties()` and `detect_text()` remaining.
=> Add Vision system tests for detect_safe_search().

core/google/cloud/_testing.py, core/unit_tests/streaming/test_transfer.py, logging/unit_tests/test_client.py
Addresses:
https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2847/files#r91715191
=> Plug tempdir leak

docs/language-usage.rst
=> Change language usage doc polarity -> score.

README.rst, docs/translate-client.rst, docs/translate-usage.rst, translate/README.rst, translate/google/cloud/translate/__init__.py, translate/google/cloud/translate/client.py, translate/google/cloud/translate/connection.py, translate/setup.py
=> Update Translation API branding.

language/google/cloud/language/syntax.py, language/unit_tests/test_syntax.py
Not sure if I did the pydoc stuff right.
=> Fixes #2858

_landing-page-static/images/icon-lang-go.svg, index.html
=> Add Go to dropdown.

docs/translate-usage.rst
=> Remove API key from Translate usage docs.

README.rst
(It felt left out, since all its friends were clearly upgraded.)
=> Switch to SVG for coverage badge.

docs/vision-usage.rst
Add missing property in Vision usage docs.
@dhermes @tseaver since this is a one-liner docs change, I'm just going to merge it after CI passes.
Closes #2924
=> Add missing colors property in vision usage.

docs/bigquery-usage.rst
from 'truncate' to 'WRITE_TRUNCATE'
'truncate' is not one of the supported values
=> change job.write_disposition usage

docs/bigquery-job.rst
=> Document BigQuery inherited members.

.coveragerc
/cc FYI @lukesneeringer @geigerj
=> Adding google.cloud.proto to list of ignored packages for coverage.

core/setup.py
/fyi @lukesneeringer @bjwatson 
Working on release notes now
=> Cutting google-cloud-core==0.23.0.

bigquery/google/cloud/bigquery/schema.py
=> Fixed typo

bigquery/setup.py, bigtable/setup.py, datastore/setup.py, dns/setup.py, error_reporting/setup.py, language/setup.py, logging/setup.py, monitoring/setup.py, pubsub/setup.py, resource_manager/setup.py, runtimeconfig/setup.py, speech/setup.py, storage/setup.py, translate/setup.py, vision/setup.py
Updates 'google-cloud-core >= 0.23.0, < 0.24dev' dependencies in services.
=> Update core dependency to google-cloud-core >= 0.23.0, < 0.24dev.

logging/google/cloud/logging/_gax.py, logging/setup.py, logging/unit_tests/test__gax.py
=> Bump logging dependencies to 0.91.0

datastore/google/cloud/datastore/_http.py, datastore/unit_tests/test__http.py
Also sending DEFAULT_USER_AGENT header instead of relying on the Connection.USER_AGENT property.
=> Moving build_api_url() off of datastore Connection.

system_tests/bigquery.py
=> Add an explicit test for records nested in records.

language/google/cloud/language/document.py, language/google/cloud/language/entity.py
=> Add documentation from language proto to document.

docs/speech-usage.rst
Thanks to @FCtj for finding this.
=> Update speech usage document for streaming.

system_tests/bigquery.py
=> Add BigQuery system test for nested-nested records.

bigquery/google/cloud/bigquery/_helpers.py, bigquery/unit_tests/test__helpers.py, system_tests/bigquery.py
Might be easier to review commit-by-commit.
Closes #2906, #3029.
=> Add bigquery system tests for query parameters with nested types

datastore/google/cloud/datastore/batch.py
Super tiny update.
I was going to batch any changes together in one PR but since there might be some discussion on some of the other changes (#3181) I'll just get this in.
=> Update datastore batch API doc reference.

CONTRIBUTING.rst
H/T to @jonparrott for finally getting me to send this PR. The old link has been redirecting to this new one for at least two weeks and I keep noticing and forgetting.
=> Updating "Faster Pull Request Reviews" link.

docs/language-usage.rst
=> Update NL documentation references.

speech/google/cloud/speech/encoding.py
=> Fix broken speech link.

docs/logging-usage.rst, error_reporting/google/cloud/error_reporting/client.py, logging/google/cloud/logging/_gax.py, logging/google/cloud/logging/_http.py, logging/google/cloud/logging/client.py, logging/google/cloud/logging/entries.py, logging/google/cloud/logging/logger.py, logging/google/cloud/logging/metric.py, logging/google/cloud/logging/sink.py
These links were 301 redirecting.
/cc @waprin (I know you're OOO, just wanted this in your inbox for later.)
=> Logging docs, update references that were 301 redirecting.

vision/tests/system.py
=> Be forgiving on a flaky test.

spanner/tests/system.py
=> Make flaky tests retry.

.travis.yml, README.rst, test_utils/test_utils/system.py
The only remaining are in `CONTRIBUTING.rst` and @lukesneeringer had mentioned he would tackle that (via #3205) soonish.
=> Removing most remnants of Travis CI.

test_utils/scripts/update_docs.sh
Evidence, the carnage of failed builds:
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1482
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1483
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1484
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1485
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1486
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1487
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1488
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1489
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1490
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1491
- …
=> Not pushing docs on tag builds.

language/google/cloud/language/sentiment.py
=> Make sentiment.score optional.

speech/google/cloud/speech/sample.py, speech/tests/unit/test_sample.py
=> Do not validate sample rate.

speech/google/cloud/speech/sample.py, speech/tests/unit/test_sample.py
=> Do not force LRO to be FLAC only in Speech.

speech/setup.py
Release notes coming momentarily.
=> Bump Speech to 0.25.1 [ci skip]

core/google/cloud/_helpers.py, pubsub/google/cloud/pubsub/_gax.py, pubsub/google/cloud/pubsub/_http.py, pubsub/google/cloud/pubsub/subscription.py, pubsub/google/cloud/pubsub/topic.py, pubsub/tests/system.py, pubsub/tests/unit/test__gax.py, pubsub/tests/unit/test__http.py, pubsub/tests/unit/test_subscription.py
Also simplify a helper method to use built-in logic from
google.protobuf to convert between Duration and timedelta
=> Add new subscription fields

core/google/cloud/iam.py, core/tests/unit/test_iam.py, pubsub/google/cloud/pubsub/iam.py, pubsub/tests/unit/test_iam.py, storage/google/cloud/storage/bucket.py, storage/google/cloud/storage/iam.py, storage/tests/unit/test_bucket.py, storage/tests/unit/test_iam.py
Uses #3308 as a base.
Toward #1679.
=> Add IAM methods for buckets.

.circleci/config.yml, README.rst
Also making sure that it gets checked on builds.
=> Making the google-cloud setup.py valid.

spanner/tests/system.py
=> Add tests for all parameter types.

spanner/tests/system.py
~~Uses #3399 as a base.~~
Closes #3017.
=> Add tests for range reads and reads with limits. 

spanner/tests/system/test_system.py, spanner/tests/system/utils/populate_streaming.py, spanner/tests/system/utils/streaming_utils.py
=> Test streaming of various payload row sizes.

error_reporting/tests/system.py
Some recent failures:
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1901
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1906
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1907
- https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1924
/cc @waprin
=> Increasing retries from 4 to 6 for error reporting system test.

videointelligence/README.rst
reported by a customer. the package name in public python packager is google-cloud-videointelligence
tested
=> corrected package name

README.rst
Someone changed auth link and broke this link
=> Someone changed auth link and broke this link

core/google/cloud/client.py
=> Fix broken link in the client Google Auth credentials help text

bigquery/pylint.config.py, bigtable/pylint.config.py, core/pylint.config.py, datastore/pylint.config.py, dns/pylint.config.py, error_reporting/pylint.config.py, language/pylint.config.py, logging/pylint.config.py, monitoring/pylint.config.py, pubsub/pylint.config.py, resource_manager/pylint.config.py, runtimeconfig/pylint.config.py, spanner/pylint.config.py, speech/pylint.config.py, storage/pylint.config.py, translate/pylint.config.py, videointelligence/google/cloud/gapic/videointelligence/v1beta1/enums.py, videointelligence/pylint.config.py, vision/google/cloud/gapic/vision/v1/enums.py, vision/pylint.config.py
This PR is **srs** *bznz*!
(I'm not crazy, I just noticed this when quickly closing one file and the one under it had a different indent level in the same spot.)
=> Making all LICENSE headers "uniform".

error_reporting/setup.py
See #3579 and #3584 for context.
=> Making requirements tighter for "stable" packages in error reporting 0.24.3 release.

bigquery/tests/unit/test_table.py
See breakage: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/2340
=> Fixing "long line" lint violation in BigQuery unit tests.

bigquery/setup.py, bigtable/setup.py, core/setup.py, datastore/setup.py, dns/setup.py, error_reporting/setup.py, language/setup.py, logging/setup.py, monitoring/setup.py, pubsub/setup.py, resource_manager/setup.py, runtimeconfig/setup.py, setup.py, spanner/setup.py, speech/setup.py, storage/setup.py, test_utils/setup.py, translate/setup.py, videointelligence/setup.py, vision/setup.py
Done via:
```
$ git grep -l author_email | \
> xargs sed -i s/jjg+google-cloud-python@google.com/googleapis-publisher@google.com/g
```
and manually editing `videointelligence/setup.py` and `vision/setup.py`.
----
Context: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3590#discussion_r126523389
----
After this change, to make sure everything is "OK":
```
015365648425b1cc7bf8e7811f2b4ff797741b6f
$
$ git grep -n author_email
bigquery/setup.py:30:    'author_email': 'googleapis-publisher@google.com',
bigtable/setup.py:30:    'author_email': 'googleapis-publisher@google.com',
core/setup.py:30:    'author_email': 'googleapis-publisher@google.com',
datastore/setup.py:30:    'author_email': 'googleapis-publisher@google.com',
dns/setup.py:30: …
```
=> Updating author_email in all setup.py.

bigquery/google/cloud/bigquery/table.py, bigquery/tests/unit/test_table.py
=> Add bigquery job_name parameter to Table.upload_from_file

videointelligence/README.rst, videointelligence/nox.py
Currently the RST does not get rendered:
=> Adding badge images to Video Intelligence README.

spanner/google/cloud/spanner/session.py, spanner/google/cloud/spanner/transaction.py, spanner/tests/unit/test_transaction.py
=> Unbind transaction from session on commit/rollback.

vision/setup.py
~~Also bumping the version on the uber-package.~~
=> Cut release of vision API.

docs/translate/client.rst, nox.py
Fixes a tiny problem with building the translate docs.
=> Fix translate docs build.

spanner/google/cloud/spanner/__init__.py, spanner/google/cloud/spanner/_helpers.py, spanner/google/cloud/spanner/types.py
=> Create parameter type aliases for scalar field types.

speech/google/cloud/gapic/speech/v1/enums.py, speech/google/cloud/gapic/speech/v1/speech_client.py, speech/google/cloud/gapic/speech/v1/speech_client_config.json, speech/google/cloud/proto/speech/v1/cloud_speech_pb2.py
This pull request was generated by artman. Please review it thoroughly before merging.
=> Python GAPIC: Speech v1

speech/setup.py
This release adds `WordTimeOffset`, the ability to have timestamps on the output.
=> Bump Speech to 0.27.1

logging/nox.py
These hose our builds. (See my branch name.)
FWIW Someone should also deal with the eventual-consistency issue with Pub/Sub snapshot system tests.
=> Allowing logging system tests to fail.

logging/nox.py, logging/tests/system.py
=> Reduce the max tries for logging system tests

README.rst, docs/index.rst, docs/trace/index.rst
Fixes #3717.
@dhermes, can you merge this and manually update docs?
=> Do not show Trace documentation.

docs/vision/index.rst
=> fixed typo DETECTION

core/setup.py
=> Explicitly depend on setuptools >= 34.0.0

bigquery/setup.py, core/setup.py, storage/setup.py
=> Bump requests minimum bound to 2.18.0

CONTRIBUTING.rst
=> Make CONTRIBUTING.rst be up to date.

CONTRIBUTING.rst
=> Accurately document system test permissions.

_landing-page-static/css/main.css
=> Change color scheme for call-to-action button

translate/tests/system.py
I really really want a green build before I merge #3859, and it [failed](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3047?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) on this unrelated system test for Translate.
=> Make system tests not care about case.

README.rst, pubsub/setup.py
This commit bumps the Pub/Sub version number and marks the release level as beta.
=> Mark Pub/Sub as beta; bump version number.

pubsub/README.rst
=> Documentation fix.

core/setup.py
=> Require six 1.10.0

.github/CODEOWNERS
This tells GitHub who to suggest as a reviewer.
Everyone look over this and make sure it looks sane/correct. Tell me if I should make changes (or just add commits to the PR :-p).
-----
This PR will operate on "lazy consensus". I will merge it on Thursday, August 31 unless someone voices an objection.
=> Add a CODEOWNERS file.

bigquery/google/cloud/bigquery/_helpers.py
I'm running into the issue mentioned here [#3870](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3870)
This patch seems to be working for me.
=> BigQuery Support for Sub Second Datetimes

docs/pubsub/subscriber/index.rst
=> Typo correction.

docs/requirements.txt
=> Try requiring current Sphinx in requirements.txt

docs/requirements.txt, pubsub/setup.py
* Fixes a namespace package declaration on Pub/Sub.
* Adds missing packages to `docs/requirements.txt`
=> Pubsub 0.28.3

bigquery/google/cloud/bigquery/job.py, bigquery/tests/unit/test_job.py
Uses #3801 as a base.
Cherry-picked / fixed up from PR #3721.
=> Add 'QueryJob.undeclared_query_parameters' property.

bigquery/google/cloud/bigquery/dataset.py, bigquery/google/cloud/bigquery/table.py, bigquery/tests/unit/test_dataset.py, bigquery/tests/unit/test_table.py
The base of this commit is https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3938
=> BigQuery: Add TestReference class. Add table function to DatasetReference

language/setup.py
Uses #3969 as a base.
(release notes coming shortly)
=> Natural Language 0.29.0

videointelligence/google/cloud/videointelligence.py
=> Video Intelligence: Change default version to v1beta2.

docs/language/usage.rst
This PR adds documentation for the new `analyze_entity_sentiment` method added in the new version of language.
I hope Mona actually likes jogging. :-p (No clue whether she does or not.)
=> Add documentation: language analyze_entity_sentiment

bigquery/google/cloud/bigquery/client.py, bigquery/google/cloud/bigquery/dataset.py, bigquery/tests/system.py, bigquery/tests/unit/test_client.py, bigquery/tests/unit/test_dataset.py
=> bigquery: add client.delete_dataset

spanner/google/cloud/spanner/streamed.py
Fixes #3981
Fixes #3998
Closes #4009
=> Merge dates and timestamps properly.

bigquery/google/cloud/bigquery/dataset.py, bigquery/tests/system.py, bigquery/tests/unit/test_client.py, bigquery/tests/unit/test_dataset.py
Add a labels property to Dataset, gettable and settable.
=> bigquery: dataset labels

docs/spanner/instance-usage.rst
Addresses the second of @jonparrott's documentation comments (in the final bullet list).
=> Provide correct API for monitoring an LRO (instances).

vision/google/cloud/vision/safe_search.py
=> Vision: Fix "medical_likelihood" typo.

storage/tests/system.py
=> Test blob CRUD methods w/ 'user_project' set.

translate/google/cloud/translate_v2/client.py, translate/tests/unit/test_client.py
=> Use POST with Translate API

test_utils/scripts/get_version.py
See https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/3584
=> Fix docs helper script for getting version.

bigquery/google/cloud/bigquery/client.py, bigquery/google/cloud/bigquery/table.py, bigquery/tests/unit/test_client.py, bigquery/tests/unit/test_table.py
=> bigquery: add Client.list_partitions

storage/google/cloud/storage/bucket.py, storage/google/cloud/storage/notification.py, storage/nox.py, storage/tests/system.py, storage/tests/unit/test_bucket.py, storage/tests/unit/test_notification.py
Merges already-reviewed work on the `3956-storage-notifications` branch to `master`,
Closes #3956.
=> Add support for bucket notifications

bigquery/google/cloud/bigquery/__init__.py, bigquery/google/cloud/bigquery/_helpers.py, bigquery/google/cloud/bigquery/client.py, bigquery/google/cloud/bigquery/query.py, bigquery/tests/system.py, bigquery/tests/unit/test__helpers.py, bigquery/tests/unit/test_client.py
Rows are represented by a new class, Row, which allows access by position or field name.
=> bigquery: add Row class

docs/language/usage.rst
=> Fix usage documentation.

bigquery/google/cloud/bigquery/client.py, bigquery/tests/system.py, bigquery/tests/unit/test_client.py
Addresses client library requirement to "provide an option for JSON as argument"
=> BigQuery: Adds client.create_rows_json()

bigquery/google/cloud/bigquery/client.py, bigquery/tests/unit/test_client.py
Support filtering datasets by label.
=> bigquery: add filter to list_datasets

.circleci/config.yml
=> Add trace to CircleCI list of packages

storage/setup.py
- Add header enabling gzip downloads. (#3380)
- `Bucket.user_project` support:  APIs for such buckets and their blobs are billed to the specified project. (#4056) 
- `Bucket.requester_pays` property:  requires that operations in the bucket be made with `user_project` set. (#4056)
-  Add support for publishing notifications of bucket / blob operations to `google.cloud.pubsub` topics. (#4127)
- Validate checksums during download: when a validation error is detected, delete corrupt file. (#4133)
=> Prep 'storage-1.5.0' release.

README.rst
Fixes #4229.
/cc @danoscarmike
=> Adding Firestore to project README.

firestore/tests/unit/test__helpers.py
=> Skip tests that hit known bug in Python pre-3.4.4 interpreters.

.github/ISSUE_TEMPLATE
I'm not sure if the non-API types are the best suggestions, but it's a start to making things more uniform?
=> Add standard title format for issue reporting to the template

CHANGELOG.md
=> Updating CHANGELOG for `google-cloud` package.

spanner/README.rst
In particular, adding badges and a "documentation" link near the top.
Made changes based on the datastore README.
=> Bringing Spanner README more in line with others.

trace/setup.cfg
Hi @lukesneeringer @dhermes Does this work? #4307 Or will I need to add some more stuff?  I'm not familiar with this setup thing.
=> Trace: #4307 setup config

trace/README.rst
Fixes #4301.
- Broken: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/8ec0e5d70a7e76deb6df117a4b858499fda4ad1b/trace/README.rst
- Fixed: https://github.com/dhermes/google-cloud-python/blob/fix-4301/trace/README.rst
=> "Cleaning up" README for `google-cloud-trace`.

bigtable/CHANGELOG.md, bigtable/setup.py, docs/bigtable/releases.rst
=> Cutting release 0.28.1 for Bigtable.

README.rst, docs/language/releases.rst, docs/language/usage.rst, language/README.rst, language/setup.py, setup.py
Staging release notes in the GitHub releases UI.
=> Bump natural language to GA.

CHANGELOG.md, language/CHANGELOG.md, language/setup.py, setup.py
Also updating the CHANGELOG files to match the release notes.
=> Post-release version update for google-cloud-language.

logging/google/cloud/logging/handlers/transports/background_thread.py, logging/tests/unit/handlers/transports/test_background_thread.py
closes #4365 - Not sure if this is autogenerated though.
=> Logging: pass in parameters to workers

docs/speech/index.rst, speech/tests/system.py
If someone can point me how else to simply grab a really big audio file, that could make the test simpler.
=> Speech: long_run_recognize document update

datastore/google/cloud/datastore/client.py
=> Update datastore doctests to reflect change in cursor behavior.

spanner/tests/system/test_system.py
- switched positive and negative infinities maintaining order [-inf, +inf, NaN]
=> Spanner: minor typo 

pubsub/README.rst
I need to use pub/sub client. But this example out of date, it's not working. I tried to fix it. It only contains minor changes in the readme file.
=> The subscription example in the readme of Pub/Sub has been updated.

core/README.rst, pubsub/README.rst, trace/README.rst, videointelligence/README.rst, vision/README.rst
Hi, I reviewed the readme files on the whole project and fixed the broken links.
=> Unreachable links in the readme files have been fixed

docs/trace/apis.rst, docs/trace/index.rst
=> Make docs build again.

pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
=> Adding log message when Pub/Sub `maintain_leases` exits.

docs/vision/releases.rst, vision/setup.py
=> Post-release hygiene for Vision.

pubsub/google/cloud/pubsub_v1/subscriber/client.py, pubsub/tests/unit/pubsub_v1/subscriber/test_subscriber_client.py
=>  PubSub: Raises TypeError on noncallable callback in subscriber client

spanner/tests/system/test_system.py
=> Spanner: Empty Read

bigquery/tests/system.py
=> BigQuery: fixes python 2.7 system test error caused by PR 4354

spanner/tests/system/test_system.py
To help writing tests with multiple rows.
=> Spanner: Row check allow multiple rows to be unordered in check

logging/tests/system.py
I'm fairly certain this is a sign that the `logging` system tests are broken in some worse way, but this PR is just to make sure that we stop leaking created topics.
=> Adding cleanup for Pub / Sub topic in logging system test.

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py, pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
This functionality was removed in #4537, so this puts it back.
However, this puts it back in a way that is much more straightforward.
=> Make sure Pub / Sub BIDI consumer doesn't try to join itself.

bigquery/google/cloud/bigquery/external_config.py, bigquery/google/cloud/bigquery/job.py, bigquery/tests/unit/test_job.py, spanner/google/cloud/spanner_v1/param_types.py
Fixes issues identified in https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4548
=> Fixes broken URLs and typos identified in #4548

pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py, pubsub/tests/unit/pubsub_v1/subscriber/test_policy_base.py
I messed this up during #4549, and as a result, there is no lease maintenance in the `0.29.3` release.
Yay Friday releases!
=> Un-confuse the "active"<->"stopped" relationship in Pub/Sub consumer.

logging/README.rst, logging/google/cloud/logging/sink.py
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4578
=> Added doc to highlight missing `uniqueWriterIdentity` field

docs/bigquery/snippets.py
=> BQ: snippets for table_exists and dataset_exists

container/CHANGELOG.md, container/docs/index.rst, container/docs/releases.rst
Release notes in the changelog, also staged in the GitHub UI.
=> Kubernetes Engine 0.1.0

pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
Also adding a note explaining a bit why they extra check was there to begin with.
Fixes #4496.
=> Removing redunant "active" check in Pub / Sub policy.

pubsub/google/cloud/pubsub_v1/subscriber/message.py
=> Add more explicit documentation for Pub / Sub Message.attributes.

pubsub/google/cloud/pubsub_v1/subscriber/message.py, pubsub/tests/unit/pubsub_v1/subscriber/test_message.py
=> Make Pub / Sub `Message.__repr__` a bit prettier / more useful.

docs/spanner/snapshot-usage.rst
=> Spanner: Multi-use snapshot doc

spanner/google/cloud/spanner_v1/keyset.py, spanner/tests/unit/test_keyset.py
=> Spanner: partial key range and bug fix with single key

spanner/tests/system/test_system.py
Merge #4618 first.  I still need to test this.
=> Spanner: System test partial range

datastore/google/cloud/datastore/entity.py, datastore/tests/unit/test_entity.py
See #3832.  Just following up with it.
I'm going to leave the document in place as it is the same as the other function.  I can make a separate pull request to remove implementation details.
=> Datastore: id from #3832 pull request with unit test

datastore/google/cloud/datastore/entity.py
=> Datastore: Entity doc update

api_core/setup.py, pubsub/CHANGELOG.md, pubsub/setup.py
Also adding a newly added note to Pub / Sub release notes (I already added this in the official release).
=> Adding back `.dev1` suffix after #4644.

docs/bigquery/snippets.py, docs/bigquery/usage.rst
Several people have asked for this sample, finally making one for the official docs.
=> BigQuery: sample for writing query results to a destination table

docs/bigquery/snippets.py
Missed it in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4722
=>  BQ: appease flake8 in snippets.py

bigquery/google/cloud/bigquery/client.py, bigquery/tests/system.py, bigquery/tests/unit/test_client.py
=> BigQuery: expose delete contents

runtimeconfig/google/cloud/runtimeconfig/variable.py, runtimeconfig/tests/unit/test_variable.py
=> RuntimeConfig: Set default variable state to Unspecified

spanner/google/cloud/spanner_v1/database.py
=> Spanner: Database update_ddl missing ddl_statements param in documentation

docs/bigquery/snippets.py
Previously, the visible portion of this snippet did not show setting the schema. This made it non-obvious that the schema has to be defined somehow in order to load a table from the file. I chose to change it to autodetect the schema rather than moving the explicit schema definition into the snippet because I didn't see other snippets in this file using autodetect.
=> BigQuery Docs: Autodetects schema in load table from file snippet

oslogin/docs/index.rst
@jbolinger I got this link from @ethanbao in an email last night.
=> Point OS Login to actual docs.

vision/google/cloud/vision_v1/gapic/enums.py, vision/google/cloud/vision_v1/gapic/image_annotator_client.py, vision/google/cloud/vision_v1/proto/image_annotator_pb2.py, vision/google/cloud/vision_v1/proto/text_annotation_pb2.py, vision/google/cloud/vision_v1/proto/web_detection_pb2.py, vision/google/cloud/vision_v1/types.py, vision/setup.py, vision/tests/unit/gapic/v1/test_image_annotator_client_v1.py
The changes are:
* Updated autogen surface.
* New web detection features: title, full matching images, partial matching images, visually similar images, best guess labels.
GAX is already excised from Vision.
=> Vision updates.

bigquery/tests/system.py
I believe this shows that #3602 is not a problem any more.
=> BigQuery: Confirm loading avro from gcs is ok

logging/google/cloud/logging/handlers/app_engine.py, logging/google/cloud/logging/handlers/handlers.py, logging/tests/unit/handlers/test_app_engine.py
Closes #4823. See discussion in #3359.
=> Move the code path of get_gae_labels() to emit()

speech/google/cloud/speech_v1/helpers.py
@jonparrott feel free to merge.
=> Speech: Fix documentation for helpers gapic

pubsub/google/cloud/pubsub_v1/subscriber/message.py
[source request](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4648#issuecomment-362427757)
=> clarify that modify_ack_deadline resets the deadline

spanner/google/cloud/spanner_v1/batch.py, spanner/google/cloud/spanner_v1/keyset.py, spanner/google/cloud/spanner_v1/snapshot.py, spanner/tests/unit/test_keyset.py, spanner/tests/unit/test_snapshot.py
This might be considered a breaking change?
See #4710
=> Spanner: make to_pb private in keyset

storage/google/cloud/storage/_signing.py, storage/tests/unit/test_blob.py
Modified `generate_signed_url` to support a similar feature in
gsutil for generating signed URLs that enable clients to initiate
an upload, particularly in their region rather than in the
server's.
=> Add support for resumable signed url generation

firestore/tests/system.py
@lukesneeringer This fixes the system tests in master.
=> Firestore: System test fix, changed ALREADY_EXISTS and MISSING_ENTITY to DOCUMENT_EXISTS and MISSING_DOCUMENT and updated wording

docs/pubsub/publisher/index.rst
=> Pub/Sub: Update docs to be clear about threading.

CONTRIBUTING.rst
I addressed the comments in #4241, so if I may pull the trigger on that, someone can look at the diff here.
=> Fix contrib note (based from #4241)

bigtable/google/cloud/bigtable/client.py, bigtable/setup.py
=> Remove gax usage from BigTable

dlp/CHANGELOG.md
=> Release DLP 0.1.0

spanner/tests/system/utils/populate_streaming.py
I'm just going to merge this since this is just a test util.
feel free to revert if anyone thinks otherwise.
=> Spanner: Fix system test util to populate streaming

logging/CHANGELOG.md, logging/setup.py
=> Release logging 1.5.0

pubsub/CHANGELOG.md, pubsub/setup.py
=> Release pubsub 0.31.0

docs/monitoring/usage.rst
=> Fix line extension character breaking links

bigquery/google/cloud/bigquery/table.py, bigquery/tests/unit/test_table.py
=> Update format in `Table.full_table_id` and `TableListItem.full_table_id` docstrings.

datastore/tests/system/test_system.py, datastore/tests/system/utils/clear_datastore.py, datastore/tests/system/utils/populate_datastore.py
Attempt to reproduce #4264.
This test does pass for me.
=> Exercise datastore query result paging

pubsub/google/cloud/pubsub_v1/subscriber/policy/thread.py, pubsub/tests/unit/pubsub_v1/subscriber/test_policy_thread.py
=> Add support for streaming pull receipts.

monitoring/google/cloud/monitoring/client.py
=> [Monitoring] Convert label values to str in client.metric()

docs/spanner/usage.rst
@vkedia Is this good for now?  I will update it as I find out more information.
=> Multiprocessing warning in documentation

pubsub/CHANGELOG.md
=> Release pubsub 0.32.0

api_core/google/api_core/future/polling.py, api_core/google/api_core/operation.py
=> Add ability to specify retry for `Operation` and `polling.Future`.

firestore/google/cloud/firestore_v1beta1/_helpers.py, firestore/google/cloud/firestore_v1beta1/client.py, firestore/tests/system.py, firestore/tests/unit/test__helpers.py
=> All non-simple field names are converted into unicode

api_core/CHANGELOG.md, api_core/setup.py
=> Release api_core 1.0.0

vision/CHANGELOG.md, vision/setup.py
=> Release vision 0.30.1

videointelligence/CHANGELOG.md, videointelligence/setup.py
=> Release videointelligence 1.0.1

translate/CHANGELOG.md, translate/setup.py
=> Release translate 1.3.1

trace/CHANGELOG.md, trace/setup.py
=> Release trace 0.19.0

speech/CHANGELOG.md, speech/setup.py
=> Release speech 0.32.1

spanner/CHANGELOG.md, spanner/setup.py
=> Release spanner 1.1.0

runtimeconfig/CHANGELOG.md, runtimeconfig/setup.py
=> Release runtimeconfig 0.28.1

resource_manager/CHANGELOG.md, resource_manager/setup.py
=> Release resource_manager 0.28.1

pubsub/CHANGELOG.md, pubsub/setup.py
=> Release pubsub 0.32.1

oslogin/CHANGELOG.md, oslogin/setup.py
=> Release oslogin 0.1.1

monitoring/CHANGELOG.md, monitoring/setup.py
=> Release monitoring 0.28.1

logging/CHANGELOG.md, logging/setup.py
=> Release logging 1.6.0

language/CHANGELOG.md, language/setup.py
=> Release language 1.0.1

firestore/CHANGELOG.md, firestore/setup.py
=> Release firestore 0.29.0

error_reporting/CHANGELOG.md, error_reporting/setup.py
=> Release error_reporting 0.29.1

dns/CHANGELOG.md, dns/setup.py
=> Release dns 0.29.0

dlp/CHANGELOG.md, dlp/setup.py
=> Release dlp 0.1.1

datastore/CHANGELOG.md, datastore/setup.py
=> Release datastore 1.6.0

dataproc/CHANGELOG.md, dataproc/setup.py
=> Release dataproc 0.1.1

container/CHANGELOG.md, container/setup.py
=> Release container 0.1.1

bigtable/CHANGELOG.md, bigtable/setup.py
=> Release bigtable 0.29.0

bigquery_datatransfer/CHANGELOG.md, bigquery_datatransfer/setup.py
=> Release bigquery_datatransfer 0.1.1

bigquery/CHANGELOG.md, bigquery/setup.py
=> Release bigquery 0.31.0

storage/CHANGELOG.md, storage/setup.py
=> Release storage 1.8.0

translate/google/cloud/translate_v2/client.py, translate/tests/unit/test_client.py
=> Move request data from query string to body, allowing larger requests to work.

core/CHANGELOG.md, core/setup.py
=> Release core 0.28.1

vision/google/cloud/vision_helpers/decorators.py, vision/tests/unit/test_decorators.py
=> Add max results to feature

docs/bigquery/snippets.py, docs/bigquery/usage.rst
Updates existing snippets and adds new snippets for inclusion in [/bigquery/docs/tables](https://cloud.google.com/bigquery/docs/tables)
=> BigQuery: Updates table snippets

monitoring/google/cloud/monitoring/query.py
Closes #5010 
@dpebot merge on green
=> Monitoring: move aligner and reducer links from timeSeries.list to alertPolicies

test_utils/scripts/get_target_packages.py
=> Use better merge base for detecting changed packages

spanner/google/cloud/spanner_v1/_helpers.py, spanner/tests/system/test_system.py, spanner/tests/unit/test__helpers.py
=> Remove Timestamp from Spanner

docs/bigquery/snippets.py, docs/bigquery/usage.rst
Updates table samples for cloud.google.com site How-to Guides sections "Working with Tables" and "Working with Table Schemas"
=> BigQuery: Updates table management snippets

docs/bigquery/snippets.py, docs/bigquery/usage.rst
Updates dataset samples for the following docs pages: 
+ [Creating and Using Datasets](https://cloud.google.com/bigquery/docs/datasets)
+ [Managing Datasets](https://cloud.google.com/bigquery/docs/managing-datasets)
=> BigQuery: Updates dataset samples

spanner/google/cloud/spanner_v1/database.py, spanner/google/cloud/spanner_v1/gapic/spanner_client.py, spanner/google/cloud/spanner_v1/gapic/spanner_client_config.py, spanner/google/cloud/spanner_v1/keyset.py, spanner/google/cloud/spanner_v1/proto/spanner_pb2.py, spanner/google/cloud/spanner_v1/proto/spanner_pb2_grpc.py, spanner/google/cloud/spanner_v1/proto/transaction_pb2.py, spanner/google/cloud/spanner_v1/snapshot.py, spanner/tests/system/test_system.py, spanner/tests/unit/gapic/v1/test_spanner_client_v1.py, spanner/tests/unit/test_database.py, spanner/tests/unit/test_keyset.py, spanner/tests/unit/test_snapshot.py
=> Add batch query support

api_core/CHANGELOG.md, api_core/setup.py
=> Release api_core 1.1.0

spanner/google/cloud/spanner_v1/database.py
=> minor typo

spanner/CHANGELOG.md, spanner/setup.py
=> Release spanner 1.2.0

pubsub/google/cloud/pubsub_v1/subscriber/policy/base.py
Fixes https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5035#issuecomment-373233381
=> Fix maintain leases to not modack messages it just dropped

pubsub/nox.py
=> pubsub nox.py cleanup

videointelligence/CHANGELOG.md, videointelligence/setup.py
=> Release videointelligence 1.1.0

texttospeech/CHANGELOG.md
=> Release texttospeech 0.1.0

dlp/CHANGELOG.md, dlp/setup.py
=> Release dlp 0.2.0

pubsub/CHANGELOG.md, pubsub/setup.py
=> Release pubsub 0.33.0

pubsub/CHANGELOG.md, pubsub/setup.py
Reverts GoogleCloudPlatform/google-cloud-python#5074
=> Revert "Release pubsub 0.33.0"

bigquery/google/cloud/bigquery/job.py, bigquery/tests/system.py, bigquery/tests/unit/test_job.py
=> BigQuery: Don't use `selected_fields` for listing query result rows

storage/tests/unit/test_batch.py
=> Storage: Fix unit test moving batch to batch/storage/v1

pubsub/google/cloud/pubsub_v1/subscriber/_consumer.py, pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
=> Properly handle graceful stop in request generator

bigquery/nox.py
=> BigQuery: simplify test name

bigquery/google/cloud/bigquery/client.py, bigquery/google/cloud/bigquery/dbapi/cursor.py, bigquery/google/cloud/bigquery/table.py, bigquery/tests/system.py, bigquery/tests/unit/test_client.py, bigquery/tests/unit/test_table.py
Closes #4260?
@tswast I'm not sure if there's more that needs to be done here.  But here's a stab at it.
=> Bigquery: adds `page_size` parameter for `list_rows` and use in DB-API for `arraysize`

pubsub/tests/unit/pubsub_v1/subscriber/test_consumer.py
=> Remove extra print statement

dlp/CHANGELOG.md, dlp/setup.py
=> Release dlp 0.3.0

pubsub/CHANGELOG.md, pubsub/setup.py
=> Release pubsub 0.33.1

vision/CHANGELOG.md, vision/setup.py
=> Release vision 0.31.0

runtimeconfig/tests/unit/test_variable.py
=> RuntimeConfig: tests with microseconds and nanoseconds

dlp/CHANGELOG.md, dlp/setup.py, dlp/tests/system/gapic/v2/test_system_dlp_service_v2.py
=> Release dlp 0.4.0

videointelligence/CHANGELOG.md, videointelligence/setup.py
=> Release videointelligence 1.2.0

speech/CHANGELOG.md, speech/setup.py
=> Release speech 0.33.0

storage/google/cloud/storage/blob.py
Closes #4087.
Language for the new note is from @frankyn .
=> Replace link to 404 object IAM docs with a note on limited utility.

bigquery/CHANGELOG.md, bigquery/setup.py
=> Release bigquery 1.0.0

bigquery/nox.py, bigquery/tests/data/people.csv, docs/bigquery/snippets.py, docs/bigquery/usage.rst
This PR accomplishes the following:
+ Updates non-standard region tags to the applicable standard
+ Standardizes commented out variables at the top of each sample with the intent that the sample can be copied and pasted and "just work" after uncommenting and customizing the variables
+ Deletes samples not used on cloud.google.com
+ Refactors samples that do not follow the canonical sample
=> BigQuery: Samples update and region tag standardization

bigquery/CHANGELOG.md, bigquery/setup.py
=> Release bigquery 1.0.1

api_core/CHANGELOG.md, api_core/setup.py
=> Release api_core 1.1.1

bigquery/CHANGELOG.md, bigquery/setup.py
=> Release bigquery 1.1.0

_landing-page-static/css/main.css
Fix issues with narrow screens #5213 and issue with transition point to two columns
=> Fix issues with narrow screens #5213

monitoring/CHANGELOG.md, monitoring/setup.py
=> Release monitoring 0.29.0

docs/bigquery/snippets.py, docs/bigquery/usage.rst
Reduces repetition in load samples discussed [here](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5003#issuecomment-382127756)
=> BigQuery: Reduces repetition in load samples

speech/CHANGELOG.md, speech/setup.py
=> Release speech 0.34.0

bigquery/google/cloud/bigquery/job.py, bigquery/tests/system.py, bigquery/tests/unit/test_job.py
=> Fix docstring for 'ExtractJob.destination_uri_file_counts'.

storage/google/cloud/storage/blob.py, storage/tests/unit/test_blob.py
=> Expose 'Blob.kms_key_name' as read-only property

pubsub/google/cloud/pubsub_v1/subscriber/_protocol/bidi.py, pubsub/tests/unit/pubsub_v1/subscriber/test_bidi.py
=> Fix race condition in bidi.BackgroundConsumer

pubsub/CHANGELOG.md, pubsub/setup.py
=> Release pubsub 0.34.0

datastore/google/cloud/datastore/__init__.py
=> Add example showing explicit unicode for text values in entities.

language/CHANGELOG.md, language/setup.py
=> Release language 1.0.2

vision/CHANGELOG.md, vision/setup.py
=> Release vision 0.31.1

websecurityscanner/CHANGELOG.md
=> Release websecurityscanner 0.1.0

bigquery/google/cloud/bigquery/__init__.py, bigquery/google/cloud/bigquery/job.py, bigquery/google/cloud/bigquery/table.py, bigquery/tests/unit/test_client.py, bigquery/tests/unit/test_job.py, bigquery/tests/unit/test_table.py, docs/bigquery/snippets.py
Adds client library support for column based time partitioning
Closes https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4658
=> BigQuery: Column based time partitioning

bigquery/CHANGELOG.md, bigquery/setup.py
=> Release bigquery 1.2.0

storage/CHANGELOG.md, storage/setup.py
=> Release storage 1.9.0

redis/CHANGELOG.md
=> Release redis 0.1.0

api_core/google/api_core/grpc_helpers.py, api_core/tests/unit/test_grpc_helpers.py
grpcio updated their package and seem to have added a close method. This PR updates the stub.
=> Fix tests after grpcio update

api_core/CHANGELOG.md, api_core/setup.py
=> Release api_core 1.2.0

storage/CHANGELOG.md, storage/setup.py
=> Release storage 1.10.0

tasks/CHANGELOG.md, tasks/google/cloud/tasks_v2beta2/gapic/cloud_tasks_client.py, tasks/setup.py
=> Release tasks 0.1.0

bigquery/tests/system.py
See @tswast's [analysis](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5003#issuecomment-385049005).
Toward #5003.
=> Prune BigQuery systests identified as reduntant to snippets.

error_reporting/CHANGELOG.md, error_reporting/setup.py
=> Release error_reporting 0.30.0

pubsub/google/cloud/pubsub_v1/subscriber/client.py
=> Fix example in subscribe's documentation

pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
=> Initialize references to helper threads before starting them

pubsub/google/cloud/pubsub_v1/subscriber/_protocol/helper_threads.py, pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py, pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
=> Send requests during streaming pull over a separate unary RPC

pubsub/CHANGELOG.md, pubsub/setup.py
=> Release pubsub 0.35.0

pubsub/CHANGELOG.md, pubsub/setup.py
=> Release pubsub 0.35.2

docs/index.rst, docs/redis, docs/requirements.txt, redis/docs/index.rst, redis/google/cloud/redis_v1beta1/gapic/cloud_redis_client.py
=> Add redis documentation to main index.rst

monitoring/google/cloud/monitoring.py
=> Add aliases for new V3 service clients.

bigquery/google/cloud/bigquery/client.py, bigquery/tests/unit/test_client.py
=> BigQuery: Adds time filtering to client.list_jobs()

bigquery/google/cloud/bigquery/client.py, docs/bigquery/snippets.py
Fixes https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5430
=> BigQuery: Adds examples of optional params for client.list_jobs() snippet

pubsub/CHANGELOG.md, pubsub/setup.py
=> Release pubsub 0.35.3

bigquery/nox.py, bigquery/setup.py
Closes https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5441
=> BigQuery: Exclude PyArrow from Windows Python 2.7 tests

docs/bigquery/snippets.py
Adds 7 missing samples as well as some misc cleanup
=> BigQuery: Adds missing label and cache samples

pubsub/google/cloud/pubsub_v1/subscriber/_protocol/bidi.py, pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py, pubsub/tests/unit/pubsub_v1/subscriber/test_bidi.py
=> Recover streams during the gRPC error callback

pubsub/CHANGELOG.md, pubsub/setup.py
=> Release pubsub 0.35.4

bigtable/google/cloud/bigtable/client.py, bigtable/tests/system.py, bigtable/tests/unit/test_client.py
=> Make 'Client.list_instances' return actual instance objects, not protos.

datastore/README.rst
update example for strong consistency (i.,e key-get vs query).  
fixes https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2023
=> minor fix to datastore example

spanner/CHANGELOG.md, spanner/setup.py
=> Release spanner 1.4.0

vision/CHANGELOG.md, vision/setup.py
=> Release vision 0.32.0

bigtable/tests/system.py
=> Fix Py3 breakage in new system test.

texttospeech/CHANGELOG.md, texttospeech/setup.py
=> Release texttospeech 0.2.0

tasks/CHANGELOG.md, tasks/setup.py
=> Release tasks 0.2.0

.circleci/config.yml, test_utils/scripts/get_target_packages.py
Reverts GoogleCloudPlatform/google-cloud-python#5482
=> Revert "Redo 5018: run only needed systests"

.circleci/config.yml, test_utils/scripts/get_target_packages.py
Also, revive whole-line search for target packages from #5482.
=> Use 'git merge-base --fork-point' to try to find common ancestor. 

logging/tests/system/test_system.py
=> Harden system tests against 'ResourceExhausted' quota errors.

api_core/CHANGELOG.md, api_core/setup.py
=> Release api_core 1.2.1

bigquery/CHANGELOG.md, docs/bigquery/usage.rst
Also dedents snippets in usage page
=> Add load_table_from_dataframe() to usage docs and changelog

monitoring/CHANGELOG.md, monitoring/setup.py
=> Release monitoring 0.30.0

bigtable/tests/unit/test_instance.py
Adding checks to make sure that the create_instance requests are as expected.
=> Bigtable: Improve testing of create instance

storage/google/cloud/storage/blob.py, storage/google/cloud/storage/bucket.py
=> Clarify 'None' values for resource-backed properties.

bigtable/google/cloud/bigtable/table.py, bigtable/tests/unit/test_table.py
table.exist() implemented. Unit test added for exist()
=> table.exists() implemented. Unit test added for exists()

logging/tests/system/test_system.py
=> Harden '_list_entries' further against backoff failure.

speech/CHANGELOG.md, speech/setup.py
=> Release speech 0.35.0

bigquery/tests/system.py, docs/bigquery/snippets.py
Workaround for #5588 and #5589.
=> Skip update_table and update_dataset tests until etag issue is resolved.

monitoring/google/cloud/monitoring_v3/gapic/alert_policy_service_client.py, monitoring/google/cloud/monitoring_v3/gapic/group_service_client.py, monitoring/google/cloud/monitoring_v3/gapic/metric_service_client.py, monitoring/google/cloud/monitoring_v3/gapic/notification_channel_service_client.py, monitoring/google/cloud/monitoring_v3/gapic/transports/alert_policy_service_grpc_transport.py, monitoring/google/cloud/monitoring_v3/gapic/transports/group_service_grpc_transport.py, monitoring/google/cloud/monitoring_v3/gapic/transports/metric_service_grpc_transport.py, monitoring/google/cloud/monitoring_v3/gapic/transports/notification_channel_service_grpc_transport.py, monitoring/google/cloud/monitoring_v3/gapic/transports/uptime_check_service_grpc_transport.py, monitoring/google/cloud/monitoring_v3/gapic/uptime_check_service_client.py, monitoring/synth.py
=> Monitoring: Add Transports Layer, Remove gRPC size restrictions (4MB default)

bigtable/google/cloud/bigtable/table.py, bigtable/tests/system.py
=> Fixing the broken Bigtable system test.

bigtable/google/cloud/bigtable/instance.py, bigtable/tests/unit/test_instance.py
=> Adding optional app profile on instance.table()

bigquery/CHANGELOG.md, bigquery/setup.py
=> Release bigquery 1.4.0

monitoring/CHANGELOG.md, monitoring/setup.py
=> Release monitoring 0.30.1

videointelligence/CHANGELOG.md, videointelligence/setup.py
=> Release videointelligence 1.3.0

docs/bigquery/snippets.py
Sample is no longer in the docs
=> Remove unnecessary sample

bigquery/google/cloud/bigquery/client.py, docs/bigquery/snippets.py
Add/refactor snippets for [managing jobs](https://cloud.google.com/bigquery/docs/managing-jobs)
=> Add/refactor snippets for managing BigQuery jobs

automl/CHANGELOG.md
=> Release automl 0.1.0

bigtable/google/cloud/bigtable/cluster.py, bigtable/google/cloud/bigtable/instance.py, bigtable/tests/unit/test_cluster.py, bigtable/tests/unit/test_instance.py
Updated instance create() method to accept clusters list. 
#5454
=> Bigtable: Ability to create an instance with multiple clusters

automl/CHANGELOG.md, automl/docs/index.rst, automl/setup.py
=> Release automl 0.1.1

dlp/CHANGELOG.md, dlp/setup.py
=> Release dlp 0.6.0

bigquery/google/cloud/bigquery/__init__.py, bigquery/google/cloud/bigquery/external_config.py, bigquery/google/cloud/bigquery/job.py, docs/bigquery/reference.rst
=> Add 'ExternalSourceFormat' enum.

bigtable/google/cloud/bigtable/enums.py, bigtable/google/cloud/bigtable/instance.py, bigtable/google/cloud/bigtable_admin_v2/gapic/enums.py, bigtable/tests/system.py, bigtable/tests/unit/test_instance.py
refactored update_app_profile() to remove update_mask argument
added asserts to unit tests
added system tests
=> Bigtable: refactor update_app_profile() to remove update_mask argument

api_core/CHANGELOG.md, api_core/setup.py
=> Release api_core 1.3.0

docs/bigquery/snippets.py
I received external feedback that the sample was not clear that a full table with a defined schema needed to be used, so I added additional context.
=> Adds more context to sample

docs/bigquery/snippets.py
=> BigQuery: bounds verification for bigquery_undelete_table

bigquery/google/cloud/bigquery/client.py, bigquery/tests/unit/test_client.py
=> Add support/tests for loading tables from 'gzip.GzipFile'.

bigquery/CHANGELOG.md, bigquery/setup.py
=> Release bigquery 1.5.0

docs/spanner/usage.rst
Hope this fixes it.
Closes #5724.
=> Fix usage.rst multiprocessing docs in spanner

bigtable/google/cloud/bigtable/instance.py, bigtable/tests/system.py, bigtable/tests/unit/test_instance.py
1. Added _state to Instance class constructor.
2. Added a property "state".
3. Updated methods from_pb() and _update_from_pb() to use state.
=> Bigtable : Adding _state to instance.py

bigtable/tests/system.py
Setting `instance.labels` in the form of `{'python-system': timestamp}`
Adding logic to clean undeleted `instance`s from previous runs where `timestamp` is older then 2 hours.
=> Bigtable: adding labels {'python-system': ISO-timestamp} to instance object

redis/README.rst
=> Redis: Fix README.md links

dataproc/CHANGELOG.md, dataproc/setup.py
=> Release dataproc 0.2.0

docs/bigquery/snippets.py
Closes #5746.
Closes #5747.
Closes #5748.
=> BigQuery: Harden snippets vs. 429 TooManyRequests.

pubsub/CHANGELOG.md, pubsub/setup.py
=> Release pubsub 0.36.0

bigquery_datatransfer/CHANGELOG.md, bigquery_datatransfer/setup.py
=> Release bigquery_datatransfer 0.2.0

bigtable/google/cloud/bigtable/instance.py, bigtable/tests/system.py, bigtable/tests/unit/test_instance.py
Added Instance.exists() method
Unit tests
System tests
=> Bigtable: add 'Instance.exists()'

pubsub/CHANGELOG.md, pubsub/setup.py
=> Release pubsub 0.37.1

dlp/CHANGELOG.md, dlp/setup.py
=> Release dlp 0.7.0

docs/spanner/database-usage.rst
=> Spanner: fix copy-pasta in database usage docs.

pubsub/google/cloud/pubsub_v1/publisher/client.py
=> Fix Sphinx rendering for publisher client.

pubsub/google/cloud/pubsub_v1/gapic/publisher_client.py, pubsub/google/cloud/pubsub_v1/gapic/subscriber_client.py, pubsub/synth.py, pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py, pubsub/tests/unit/pubsub_v1/subscriber/test_subscriber_client.py
=> Re-generate library, removing obsolete synth modifications.

pubsub/CHANGELOG.md, pubsub/setup.py
=> Release pubsub 0.37.2

bigtable/tests/system.py
=> Fix failing systest: 'test_create_instance_w_two_clusters'.

bigtable/CHANGELOG.md, bigtable/setup.py
=> Release bigtable 0.30.0

storage/CHANGELOG.md, storage/setup.py
=> Prep storage-1.11.0 release.

tasks/CHANGELOG.md, tasks/setup.py
=> Release tasks 0.3.0

storage/tests/system.py
See: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/7930
=> Storage: Harden systest teardown further.

vision/CHANGELOG.md, vision/setup.py
=> Release vision 0.34.0

speech/CHANGELOG.md, speech/setup.py
=> Release speech 0.36.0

api_core/CHANGELOG.md
=> Release api_core 1.4.0

storage/README.rst, storage/docs/index.rst
=> Storage docs: fix typos.

README.rst
- Move reference links closer to point of use, and sort for ease of comparison to match lists.
- Normalize PyPI URLs.
=> Docs: Add new alpha libraries to README

texttospeech/google/cloud/texttospeech.py, texttospeech/google/cloud/texttospeech_v1/__init__.py, texttospeech/google/cloud/texttospeech_v1/gapic/enums.py, texttospeech/google/cloud/texttospeech_v1/gapic/text_to_speech_client.py, texttospeech/google/cloud/texttospeech_v1/gapic/transports/text_to_speech_grpc_transport.py, texttospeech/google/cloud/texttospeech_v1/types.py, texttospeech/google/cloud/texttospeech_v1beta1/__init__.py, texttospeech/google/cloud/texttospeech_v1beta1/gapic/enums.py, texttospeech/google/cloud/texttospeech_v1beta1/gapic/text_to_speech_client.py, texttospeech/google/cloud/texttospeech_v1beta1/gapic/transports/text_to_speech_grpc_transport.py, texttospeech/google/cloud/texttospeech_v1beta1/types.py, texttospeech/synth.py, texttospeech/tests/unit/gapic/v1/test_text_to_speech_client_v1.py, texttospeech/tests/unit/gapic/v1beta1/test_text_to_speech_client_v1beta1.py
No longer scribble on `README.rst`, `docs/index.rst`. 
Regenerate from curren protos / generator.
=> Texttospeech: fix up autosynth

pubsub/CHANGELOG.md, pubsub/setup.py
=> Release pubsub 0.38.0
