googleapis/google-cloud-python

asset/CHANGELOG.md
asset/docs/changelog.md
asset/docs/index.rst
asset/setup.py

~~Blocked on merge of #5987.~~
Closes #5985.
@danoscarmike Note that I've made the change to the PyPI name I suggested in #5985.

Prep asset-0.1.0 release.

---

.circleci/config.yml
appveyor.yml
asset/CHANGELOG.md
asset/setup.py

Asset: fix PyPI name.

---

asset/README.rst
asset/docs/conf.py
asset/google/cloud/asset_v1beta1/gapic/asset_service_client.py
asset/synth.py

- In docs.
- In synth-derived code.

Asset: finish rename 'cloudasset' -> 'asset'.

---

bigtable/google/cloud/bigtable_admin_v2/gapic/bigtable_instance_admin_client_config.py
bigtable/google/cloud/bigtable_admin_v2/gapic/bigtable_table_admin_client_config.py
bigtable/google/cloud/bigtable_admin_v2/gapic/enums.py

Bigtable: re-synth to pick up new deadline configuration.

---

videointelligence/CHANGELOG.md
videointelligence/setup.py

Release videointelligence 1.4.0

---

kms/synth.py

KMS: exclude 'setup.py' from synth.

---

resource_manager/google/cloud/resource_manager/_http.py

Resource Manager: bump API version from 'v1beta1' to 'v1'.

---

vision/README.rst
vision/docs/index.rst

Vision: Harmonize / DRY 'README.rst' / 'docs/index.rst'.

---

automl/README.rst
automl/docs/changelog.md
automl/docs/index.rst

AutoML: Harmonize / DRY 'README.rst' / 'docs/index.rst'.

---

bigquery_datatransfer/README.rst
bigquery_datatransfer/docs/index.rst

BigQuery Data Transfer: Harmonize / DRY 'README.rst' / 'docs/index.rst'.

---

container/README.rst
container/docs/changelog.md
container/docs/index.rst

Container: harmonize / DRY 'README.rst' / 'docs/index.rst'.

---

dataproc/README.rst
dataproc/docs/changelog.md
dataproc/docs/index.rst

Dataproc: harmonize / DRY 'README.rst' / 'docs/index.rst'.

---

kms/README.rst
kms/docs/changelog.md
kms/docs/index.rst

KMS: harmonize / DRY 'README.rst' / 'docs/index.rst'.

---

bigquery/CHANGELOG.md
bigquery/setup.py

Closes https://github.com/GoogleCloudPlatform/google-cloud-python/issues/6053

Release bigquery 1.5.1

---

language/google/cloud/language_v1/gapic/enums.py
language/google/cloud/language_v1/gapic/language_service_client.py
language/google/cloud/language_v1/gapic/transports/language_service_grpc_transport.py
language/google/cloud/language_v1/proto/language_service_pb2.py
language/google/cloud/language_v1beta2/gapic/enums.py
language/google/cloud/language_v1beta2/gapic/language_service_client.py
language/google/cloud/language_v1beta2/gapic/transports/language_service_grpc_transport.py
language/google/cloud/language_v1beta2/proto/language_service_pb2.py
language/synth.py

Language: add 'synth.py'.

---

iot/google/cloud/iot_v1/__init__.py
iot/google/cloud/iot_v1/gapic/device_manager_client.py
iot/google/cloud/iot_v1/gapic/enums.py
iot/google/cloud/iot_v1/gapic/transports/device_manager_grpc_transport.py
iot/google/cloud/iot_v1/types.py
iot/synth.py

IoT: add 'synth.py'.

---

websecurityscanner/google/cloud/websecurityscanner_v1alpha/gapic/enums.py
websecurityscanner/google/cloud/websecurityscanner_v1alpha/gapic/transports/web_security_scanner_grpc_transport.py
websecurityscanner/google/cloud/websecurityscanner_v1alpha/gapic/web_security_scanner_client.py
websecurityscanner/synth.py

Websecurityscanner: add 'synth.py'.

---

bigtable/tests/system.py

Bigtable: Harden systest instance teardown against '429 Too Many Requests'.

---

dlp/CHANGELOG.md
dlp/setup.py

Release dlp 0.8.0

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.4.1

---

logging/google/cloud/logging/_helpers.py
logging/google/cloud/logging/entries.py
logging/google/cloud/logging/logger.py
logging/tests/unit/test__helpers.py
logging/tests/unit/test_entries.py
logging/tests/unit/test_logger.py

Closes #6063.
/cc  @salrashid123

Accomodate payload-less log entries.

---

storage/CHANGELOG.md
storage/setup.py

Release storage 1.13.0

---

docs/conf.py
trace/docs/starting.html

Trace: Add static HTML redirect page for 'starting.html'.

---

bigquery/CHANGELOG.md
bigquery/setup.py

Release bigquery 1.6.0

---

.kokoro/build.sh

Add PROJECT_ID environment variable

---

bigtable/google/cloud/bigtable/row_data.py
bigtable/google/cloud/bigtable/table.py
bigtable/tests/unit/test_row_data.py
bigtable/tests/unit/test_table.py

Refactor `read_row` to call `read_rows`

Bigtable: read_row to call read_rows

---

bigtable/CHANGELOG.md
bigtable/setup.py

Release bigtable 0.31.0

---

language/CHANGELOG.md
language/setup.py

Release language 1.1.0

---

spanner/CHANGELOG.md
spanner/setup.py

Release spanner 1.6.0

---

logging/tests/unit/handlers/test_app_engine.py

Logging: fix lint errors.

---

bigquery/docs/snippets.py

BigQuery:  harden snippets against transient GCS errors.

---

.circleci/config.yml
noxfile.py

@busunkim96   needs a new docker image in '.circleci/config.yaml' to make this work on CircleCI.
Closes #6170.

Update root noxfile to new 'nox' patterns.

---

dns/README.rst

DNS: Fix copy-pasta from datastore README.

---

firestore/CHANGELOG.md
firestore/setup.py

Release firestore 0.30.0

---

storage/tests/system.py

Storage: fix lint failure.

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.5.0

---

videointelligence/CHANGELOG.md
videointelligence/setup.py

Release videointelligence 1.5.0

---

storage/tests/system.py

Skip public bucket test in VPCSC

---

tasks/synth.py

Don't update nox in 'tasks/synth.py'.

---

kms/synth.py

Don't update nox in 'kms/synth.py'.

---

README.rst
asset/README.rst
automl/README.rst
bigquery/README.rst
bigquery_datatransfer/README.rst
bigtable/README.rst
container/README.rst
dataproc/README.rst
datastore/README.rst
dlp/README.rst
dns/README.rst
firestore/README.rst
iot/README.rst
kms/README.rst
language/README.rst
pubsub/README.rst
redis/README.rst
resource_manager/README.rst
runtimeconfig/README.rst
spanner/README.rst
speech/README.rst
storage/README.rst
tasks/README.rst
texttospeech/README.rst
trace/README.rst
translate/README.rst
videointelligence/README.rst
vision/README.rst
websecurityscanner/README.rst

Docs: normalize use of support level badges

---

pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py

Pubsub: fix path for patch of 'bidi' elements.

---

logging/CHANGELOG.md
logging/setup.py

Release logging 1.8.0

---

redis/synth.py

Redis: don't synth 'README.rst'.

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.6.0a1

---

bigtable/google/cloud/bigtable/client.py
bigtable/tests/unit/test_client.py

Bigtable: deprecate 'channel' arg to 'Client'

---

ndb/MIGRATION_NOTES.md
ndb/src/google/cloud/ndb/model.py
ndb/src/google/cloud/ndb/query.py
ndb/tests/conftest.py
ndb/tests/unit/test_model.py

~~**NOTE**: This has #6275 as diffbase.~~
- Correct validation / conversion of `value` in `Property._comparison` and `Property._IN` (via `_do_validate` and `_call_to_base_type`)
- `Property._do_validate`
- `Property._call_to_base_type`
- `Property._call_shallow_validation`
- `Property._find_methods`
- `Property._apply_list`

Continuation of `ndb` Property implementation

---

datastore/CHANGELOG.md
datastore/setup.py

Release datastore 1.7.1

---

api_core/CHANGELOG.md
api_core/setup.py

Release 'api_core-1.5.1'

---

asset/synth.py

Fix Cloud Asset synth config

---

pubsub/google/cloud/pubsub_v1/publisher/client.py
pubsub/google/cloud/pubsub_v1/subscriber/client.py

Closes #6334.
/cc @anguillanneuf

Pubsub: fix imports for hand-written client docstring examples.

---

securitycenter/CHANGELOG.md

Release securitycenter 0.1.0

---

firestore/MANIFEST.in

Firestore: fix path of tests-to-include in MANIFEST.in

---

bigquery/CHANGELOG.md
bigquery/setup.py

Release bigquery 1.7.0

---

ndb/MIGRATION_NOTES.md
ndb/src/google/cloud/ndb/model.py
ndb/tests/unit/test_model.py

This is done in several commits, so the review is likely better done commit-by-commit.

Implementing `BlobProperty` in `ndb`.

---

logging/google/cloud/logging_v2/gapic/config_service_v2_client.py
logging/google/cloud/logging_v2/gapic/enums.py
logging/google/cloud/logging_v2/gapic/logging_service_v2_client.py
logging/google/cloud/logging_v2/gapic/metrics_service_v2_client.py
logging/google/cloud/logging_v2/gapic/transports/config_service_v2_grpc_transport.py
logging/google/cloud/logging_v2/gapic/transports/logging_service_v2_grpc_transport.py

Logging: fix client_info bug, update docstrings via synth.

---

vision/google/cloud/vision_v1/gapic/enums.py
vision/google/cloud/vision_v1/gapic/image_annotator_client.py
vision/google/cloud/vision_v1/gapic/product_search_client.py
vision/google/cloud/vision_v1/gapic/transports/image_annotator_grpc_transport.py
vision/google/cloud/vision_v1/gapic/transports/product_search_grpc_transport.py
vision/google/cloud/vision_v1p1beta1/gapic/enums.py
vision/google/cloud/vision_v1p1beta1/gapic/image_annotator_client.py
vision/google/cloud/vision_v1p2beta1/gapic/enums.py
vision/google/cloud/vision_v1p2beta1/gapic/image_annotator_client.py
vision/google/cloud/vision_v1p2beta1/gapic/transports/image_annotator_grpc_transport.py
vision/google/cloud/vision_v1p3beta1/gapic/enums.py
vision/google/cloud/vision_v1p3beta1/gapic/image_annotator_client.py
vision/google/cloud/vision_v1p3beta1/gapic/product_search_client.py
vision/google/cloud/vision_v1p3beta1/gapic/transports/image_annotator_grpc_transport.py
vision/google/cloud/vision_v1p3beta1/gapic/transports/product_search_grpc_transport.py
vision/synth.py

Remove now-spurious replacements in synth.
Closes #6374.

Vision: fix client_info bug, update docstrings via synth.

---

websecurityscanner/google/cloud/websecurityscanner_v1alpha/gapic/enums.py
websecurityscanner/google/cloud/websecurityscanner_v1alpha/gapic/web_security_scanner_client.py

Websecurityscanner: fix client_info bug, update docstrings via synth.

---

ndb/src/google/cloud/ndb/model.py
ndb/tests/unit/test_model.py

**NOTE**: This has #6448 as diffbase.

Implementing `DateProperty` and `TimeProperty` in `ndb`.

---

asset/noxfile.py
automl/noxfile.py
iot/noxfile.py
kms/noxfile.py
oslogin/noxfile.py
tasks/noxfile.py
texttospeech/noxfile.py
videointelligence/noxfile.py

In anticipation of landing https://github.com/googleapis/gapic-generator/pull/2407.

Add 'mock' to unit test dependencies for autogen libs.

---

bigtable/google/cloud/bigtable/client.py
bigtable/tests/unit/test_client.py

This is fix for https://github.com/googleapis/google-cloud-python/issues/6287

Bigtable: Emulator fixes

---

bigtable/CHANGELOG.md
bigtable/setup.py

Release bigtable 0.31.1

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.5.2

---

videointelligence/CHANGELOG.md
videointelligence/setup.py

Release videointelligence 1.6.0

---

spanner/CHANGELOG.md
spanner/setup.py

Release spanner 1.6.1

---

vision/CHANGELOG.md
vision/setup.py

Release vision 0.35.0

---

scheduler/CHANGELOG.md

Release scheduler 0.1.0

---

language/google/cloud/language_v1/gapic/language_service_client.py
language/google/cloud/language_v1/gapic/transports/language_service_grpc_transport.py
language/google/cloud/language_v1beta2/gapic/language_service_client.py
language/google/cloud/language_v1beta2/gapic/transports/language_service_grpc_transport.py
language/synth.py
language/tests/system/gapic/v1beta2/test_system_language_service_v1beta2.py
language/tests/unit/gapic/v1/test_language_service_client_v1.py
language/tests/unit/gapic/v1beta2/test_language_service_client_v1beta2.py

Closes #6500.
- https://github.com/googleapis/gapic-generator/pull/2407
- https://github.com/googleapis/gapic-generator/pull/2396
Includes generated test changes.

Language: pick up fixes to GAPIC generator.

---

iot/google/cloud/iot_v1/gapic/device_manager_client.py
iot/google/cloud/iot_v1/gapic/transports/device_manager_grpc_transport.py
iot/synth.py
iot/tests/system/gapic/v1/test_system_device_manager_v1.py
iot/tests/unit/gapic/v1/test_device_manager_client_v1.py

Closes #6498.
- https://github.com/googleapis/gapic-generator/pull/2407
- https://github.com/googleapis/gapic-generator/pull/2396.

IoT: pick up fixes to GAPIC generator.

---

ndb/src/google/cloud/ndb/_datastore_types.py
ndb/src/google/cloud/ndb/model.py
ndb/src/google/cloud/ndb/query.py

NDB: Use type(o) instead of o.__class__

---

videointelligence/google/cloud/videointelligence_v1/gapic/transports/video_intelligence_service_grpc_transport.py
videointelligence/google/cloud/videointelligence_v1/gapic/video_intelligence_service_client.py
videointelligence/google/cloud/videointelligence_v1beta1/gapic/transports/video_intelligence_service_grpc_transport.py
videointelligence/google/cloud/videointelligence_v1beta1/gapic/video_intelligence_service_client.py
videointelligence/google/cloud/videointelligence_v1beta2/gapic/transports/video_intelligence_service_grpc_transport.py
videointelligence/google/cloud/videointelligence_v1beta2/gapic/video_intelligence_service_client.py
videointelligence/google/cloud/videointelligence_v1p1beta1/gapic/transports/video_intelligence_service_grpc_transport.py
videointelligence/google/cloud/videointelligence_v1p1beta1/gapic/video_intelligence_service_client.py
videointelligence/google/cloud/videointelligence_v1p2beta1/gapic/transports/video_intelligence_service_grpc_transport.py
videointelligence/google/cloud/videointelligence_v1p2beta1/gapic/video_intelligence_service_client.py
videointelligence/synth.py
videointelligence/tests/unit/gapic/v1/test_video_intelligence_service_client_v1.py
videointelligence/tests/unit/gapic/v1beta2/test_video_intelligence_service_client_v1beta2.py
videointelligence/tests/unit/gapic/v1p1beta1/test_video_intelligence_service_client_v1p1beta1.py
videointelligence/tests/unit/gapic/v1p2beta1/test_video_intelligence_service_client_v1p2beta1.py

- googleapis/gapic-generator#2407 (closing googleapis/gapic-generator#2389)
- googleapis/gapic-generator#2396 (for #5523 and dupes).
Closes #6512.

Videointelligence: pick up fixes to GAPIC generator.

---

bigtable/google/cloud/bigtable_admin_v2/gapic/bigtable_instance_admin_client.py
bigtable/google/cloud/bigtable_admin_v2/gapic/bigtable_table_admin_client.py
bigtable/google/cloud/bigtable_admin_v2/gapic/enums.py
bigtable/google/cloud/bigtable_admin_v2/gapic/transports/bigtable_instance_admin_grpc_transport.py
bigtable/google/cloud/bigtable_admin_v2/gapic/transports/bigtable_table_admin_grpc_transport.py
bigtable/google/cloud/bigtable_v2/gapic/bigtable_client.py
bigtable/google/cloud/bigtable_v2/gapic/transports/bigtable_grpc_transport.py
bigtable/tests/unit/gapic/v2/test_bigtable_client_v2.py
bigtable/tests/unit/gapic/v2/test_bigtable_instance_admin_client_v2.py
bigtable/tests/unit/gapic/v2/test_bigtable_table_admin_client_v2.py

Bigtable: pick up fixes to GAPIC generator.

---

logging/google/cloud/logging_v2/gapic/config_service_v2_client.py
logging/google/cloud/logging_v2/gapic/logging_service_v2_client.py
logging/google/cloud/logging_v2/gapic/metrics_service_v2_client.py
logging/google/cloud/logging_v2/gapic/transports/config_service_v2_grpc_transport.py
logging/google/cloud/logging_v2/gapic/transports/logging_service_v2_grpc_transport.py
logging/google/cloud/logging_v2/gapic/transports/metrics_service_v2_grpc_transport.py
logging/synth.py
logging/tests/unit/gapic/v2/test_config_service_v2_client_v2.py
logging/tests/unit/gapic/v2/test_logging_service_v2_client_v2.py
logging/tests/unit/gapic/v2/test_metrics_service_v2_client_v2.py

Logging: pick up fixes to GAPIC generator.

---

websecurityscanner/google/cloud/websecurityscanner_v1alpha/gapic/transports/web_security_scanner_grpc_transport.py
websecurityscanner/google/cloud/websecurityscanner_v1alpha/gapic/web_security_scanner_client.py
websecurityscanner/synth.py
websecurityscanner/tests/unit/gapic/v1alpha/test_web_security_scanner_client_v1alpha.py

Websecurityscanner: pick up fixes to GAPIC generator.

---

container/google/cloud/container_v1/gapic/cluster_manager_client.py
container/google/cloud/container_v1/gapic/cluster_manager_client_config.py
container/google/cloud/container_v1/gapic/enums.py
container/google/cloud/container_v1/gapic/transports/cluster_manager_grpc_transport.py
container/google/cloud/container_v1/proto/cluster_service_pb2.py
container/google/cloud/container_v1/proto/cluster_service_pb2_grpc.py
container/synth.py
container/tests/unit/gapic/v1/test_cluster_manager_client_v1.py

Includes synth replacements to work around generated docstring issue:
- googleapis/gapic-generator/issues/2449
Closes #6483.

Container: pick up fixes to GAPIC generator.

---

vision/CHANGELOG.md
vision/setup.py

Release vision 0.35.1

---

pubsub/CHANGELOG.md
pubsub/setup.py

Release pubsub 0.39.0

---

firestore/google/cloud/firestore_v1beta1/client.py
firestore/tests/unit/test_client.py

Lists top-level collections in the client's database.
Closes #6553.

Firestore: add 'Client.collections' method.

---

bigquery_storage/CHANGELOG.md

Release bigquery_storage 0.1.0

---

monitoring/CHANGELOG.md
monitoring/setup.py

Release monitoring 0.31.0

---

dlp/google/cloud/dlp_v2/proto/storage_pb2.py
dlp/synth.metadata
dlp/synth.py

DLP: pick up docstring fix via synth.

---

trace/CHANGELOG.md
trace/setup.py

Release trace 0.20.1

---

bigtable/CHANGELOG.md
bigtable/setup.py

Release bigtable 0.32.0

---

bigquery/CHANGELOG.md
bigquery/setup.py

Release bigquery 1.8.0

---

datastore/CHANGELOG.md
datastore/setup.py

Release datastore 1.7.2

---

dns/CHANGELOG.md
dns/setup.py

Release dns 0.29.1

---

resource_manager/CHANGELOG.md
resource_manager/setup.py

Release resource_manager 0.28.2

---

iam/CHANGELOG.md

Release iam 0.1.0

---

api_core/CHANGELOG.md

Release api_core 1.7.0

---

automl/CHANGELOG.md
automl/setup.py

Release automl 0.1.2

---

asset/CHANGELOG.md
asset/setup.py

Release asset 0.1.2

---

bigtable/CHANGELOG.md
bigtable/setup.py

Release bigtable 0.32.1

---

core/CHANGELOG.md
core/setup.py

Release core 0.29.1

---

datastore/CHANGELOG.md
datastore/setup.py

Release datastore 1.7.3

---

container/CHANGELOG.md
container/setup.py

Release container 0.2.1

---

dataproc/CHANGELOG.md
dataproc/setup.py

Release dataproc 0.3.0

---

iot/CHANGELOG.md
iot/setup.py

Release iot 0.2.0

---

pubsub/CHANGELOG.md
pubsub/setup.py

Release pubsub 0.39.1

---

redis/CHANGELOG.md
redis/setup.py

Release redis 0.2.1

---

firestore/CHANGELOG.md
firestore/setup.py

Release firestore 0.31.0

---

trace/CHANGELOG.md
trace/setup.py

Release trace 0.20.2

---

translate/CHANGELOG.md
translate/setup.py

Release translate 1.3.3

---

dns/CHANGELOG.md
dns/setup.py

Release dns 0.29.2

---

runtimeconfig/CHANGELOG.md
runtimeconfig/setup.py

Release runtimeconfig 0.28.3

---

resource_manager/CHANGELOG.md
resource_manager/setup.py

Release resource_manager 0.28.3

---

storage/CHANGELOG.md
storage/setup.py

Release storage 1.13.2

---

tasks/CHANGELOG.md
tasks/setup.py

Release tasks 0.4.0

---

texttospeech/CHANGELOG.md
texttospeech/setup.py

Release texttospeech 0.3.0

---

bigquery_datatransfer/CHANGELOG.md
bigquery_datatransfer/setup.py

Release bigquery_datatransfer 0.3.0

---

bigquery_storage/CHANGELOG.md
bigquery_storage/setup.py

Release bigquery_storage 0.1.1

---

securitycenter/CHANGELOG.md
securitycenter/setup.py

Release securitycenter 0.1.1

---

speech/CHANGELOG.md
speech/setup.py

Release speech 0.36.1

---

dlp/CHANGELOG.md
dlp/setup.py

Release dlp 0.10.0

---

oslogin/CHANGELOG.md
oslogin/setup.py

Release oslogin 0.1.2

---

videointelligence/CHANGELOG.md
videointelligence/setup.py

Release videointelligence 1.6.1

---

vision/CHANGELOG.md
vision/setup.py

Release vision 0.35.2

---

monitoring/CHANGELOG.md
monitoring/setup.py

Release monitoring 0.31.1

---

logging/CHANGELOG.md
logging/setup.py

Release logging 1.9.1

---

websecurityscanner/CHANGELOG.md
websecurityscanner/setup.py

Release websecurityscanner 0.1.1

---

error_reporting/CHANGELOG.md
error_reporting/setup.py

Release error_reporting 0.30.1

---

language/CHANGELOG.md
language/setup.py

Release language 1.1.1

---

kms/CHANGELOG.md
kms/setup.py

Release kms 0.2.1

---

ndb/src/google/cloud/ndb/_eventloop.py
ndb/src/google/cloud/ndb/tasklets.py
ndb/tests/unit/test__eventloop.py
ndb/tests/unit/test_tasklets.py

NDB: gRPC Integration

---

error_reporting/docs/usage.rst

Small fix to formatting - a line that ended up formatted as code that shouldn't

Fix formatting

---

ndb/src/google/cloud/ndb/tasklets.py
ndb/tests/unit/test_tasklets.py

NDB: Implement parallel yield from tasklet

---

ndb/src/google/cloud/ndb/tasklets.py
ndb/tests/unit/test_tasklets.py

The base for diff is #7031 
The docstring punts to the to-be-written/copied main documentation for an explanation of how to actually use tasklets.

NDB: Implement tasklet decorator

---

bigquery_storage/google/cloud/bigquery_storage_v1beta1/gapic/transports/big_query_storage_grpc_transport.py
bigquery_storage/noxfile.py
bigquery_storage/synth.metadata
bigquery_storage/synth.py

BigQuery Storage: run 'blacken' during synth

---

logging/google/cloud/logging_v2/gapic/enums.py
logging/google/cloud/logging_v2/gapic/transports/config_service_v2_grpc_transport.py
logging/google/cloud/logging_v2/gapic/transports/logging_service_v2_grpc_transport.py
logging/google/cloud/logging_v2/gapic/transports/metrics_service_v2_grpc_transport.py
logging/synth.metadata

Logging: manual synth to get 'blacken' working.

---

bigtable/docs/snippets.py
bigtable/google/cloud/bigtable_admin_v2/gapic/enums.py
bigtable/google/cloud/bigtable_admin_v2/gapic/transports/bigtable_instance_admin_grpc_transport.py
bigtable/google/cloud/bigtable_admin_v2/gapic/transports/bigtable_table_admin_grpc_transport.py
bigtable/google/cloud/bigtable_v2/gapic/transports/bigtable_grpc_transport.py
bigtable/synth.metadata

Bigtable: manual synth

---

speech/google/cloud/speech_v1/proto/cloud_speech_pb2.py
speech/google/cloud/speech_v1p1beta1/proto/cloud_speech_pb2.py
speech/synth.metadata

Manual synth, to fix transient DOcker issue.
Closes #7102.

Speech: protoc-generated serialization update.

---

speech/CHANGELOG.md
speech/setup.py

Release speech 0.36.2

---

ndb/src/google/cloud/ndb/_eventloop.py
ndb/src/google/cloud/ndb/tasklets.py

NDB: A little more internal documentation

---

ndb/src/google/cloud/ndb/model.py
ndb/tests/unit/test_model.py

Function to serialize NDB entity to datastore protocol buffer.

 NDB: _entity_to_protobuf

---

logging/CHANGELOG.md
logging/setup.py

Release logging 1.10.0

---

storage/google/cloud/storage/_signing.py
storage/google/cloud/storage/blob.py

Improves the `generate_signed_url` function documentation.

Storage: Improve docs for 'generate_signed_url'.

---

bigquery_storage/CHANGELOG.md
bigquery_storage/setup.py

Release bigquery_storage 0.2.0

---

logging/docs/snippets.py
logging/docs/usage.rst

Add sample snippet for cloud logging with `Resource`
/cc @theacodes

Add cloud Logging Resource sample

---

bigquery/CHANGELOG.md
bigquery/setup.py

Release bigquery 1.9.0

---

storage/CHANGELOG.md
storage/setup.py

Release storage 1.14.0

---

texttospeech/CHANGELOG.md
texttospeech/setup.py

Release texttospeech 0.4.0

---

kms/CHANGELOG.md
kms/setup.py

Release kms 1.0.0

---

bigquery/google/cloud/bigquery/table.py

Update docstring of RowIterator's to_dataframe

---

dataproc/CHANGELOG.md
dataproc/setup.py

Release dataproc 0.3.1

---

ndb/docs/stats.rst
ndb/src/google/cloud/ndb/stats.py
ndb/tests/conftest.py
ndb/tests/unit/test_stats.py

Ported the whole module, with unit tests. Wanted to add system tests, but it seems we need more functionality before that can be done.

NDB: port stats module from old ndb code

---

ndb/src/google/cloud/ndb/context.py
ndb/src/google/cloud/ndb/exceptions.py
ndb/src/google/cloud/ndb/model.py
ndb/tests/unit/test_context.py

Not super exciting. Just some infrastructure to build on.

NDB: Stub out Context class.

---

ndb/src/google/cloud/ndb/query.py
ndb/tests/unit/test_query.py

Just porting over code with comments on what needs to be next.

NDB: Query constructor

---

api_core/CHANGELOG.md

Release api_core 1.8.0

---

videointelligence/CHANGELOG.md
videointelligence/setup.py

Release videointelligence 1.7.0

---

.circleci/config.yml

Release jobs have been moved to Kokoro.

Remove push to PyPI from CircleCI

---

vision/CHANGELOG.md
vision/setup.py

Release vision 0.36.0

---

talent/CHANGELOG.md

Release talent 0.1.0

---

videointelligence/CHANGELOG.md
videointelligence/setup.py

Release videointelligence 1.8.0

---

bigquery/CHANGELOG.md
bigquery/setup.py

Release bigquery 1.10.0

---

tasks/CHANGELOG.md
tasks/setup.py

Release tasks 0.5.0

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.8.1

---

pubsub/CHANGELOG.md
pubsub/setup.py

Release pubsub 0.40.0

---

speech/CHANGELOG.md
speech/setup.py

Release speech 1.0.0

---

logging/google/cloud/logging/_helpers.py

use fqdn for gce metadata endpoint

---

asset/CHANGELOG.md
asset/setup.py

Release asset 0.2.0

---

api_core/CHANGELOG.md

Release api_core 1.8.2

---

tasks/CHANGELOG.md
tasks/setup.py

Release tasks 0.6.0

---

docs/requirements.txt

Use sphinx < 2.0dev.

---

language/CHANGELOG.md
language/setup.py

Release language 1.2.0

---

docs/index.rst

Hello,
The list is not sorted, so navigation is difficult. 
The author of the idea is @crwilcox 
Reference: 
https://github.com/googleapis/google-cloud-python/pull/7624
Best regards,

Sort index in alphabetical order

---

datalabeling/CHANGELOG.md

Release datalabeling 0.1.0

---

datalabeling/setup.py

Fix for https://github.com/googleapis/google-cloud-python/pull/7641

Fix release classifier.

---

datalabeling/CHANGELOG.md
datalabeling/setup.py

Release datalabeling 0.1.1

---

firestore/google/cloud/firestore_v1/watch.py
firestore/tests/system.py

/documents is required as of V1

Fix issue with Watch Queries on V1

---

bigquery_storage/README.rst
bigquery_storage/setup.py

* Update release status to beta, reflecting the product status.

Fix links to BigQuery Storage API docs

---

scheduler/CHANGELOG.md
scheduler/setup.py

Release scheduler 0.2.0

---

translate/CHANGELOG.md
translate/setup.py

Release translate 1.4.0

---

bigquery_storage/CHANGELOG.md
bigquery_storage/setup.py

Release bigquery_storage 0.3.0

---

automl/CHANGELOG.md
automl/setup.py

Release automl 0.2.0

---

bigquery/CHANGELOG.md

Release bigquery 1.11.0

---

bigquery/CHANGELOG.md
bigquery/setup.py

Release bigquery 1.11.1

---

bigquery/CHANGELOG.md
bigquery/setup.py

Release bigquery 1.11.2

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.9.0

---

firestore/CHANGELOG.md
firestore/setup.py

Release firestore 0.32.1

---

tasks/CHANGELOG.md
tasks/setup.py

Release tasks 0.7.0

---

datacatalog/CHANGELOG.md

Release datacatalog 0.1.0

---

bigquery_storage/CHANGELOG.md
bigquery_storage/setup.py

Release bigquery_storage 0.4.0

---

webrisk/CHANGELOG.md
webrisk/setup.py

Release webrisk 0.1.0

---

dlp/CHANGELOG.md
dlp/setup.py

Release dlp 0.11.0

---

spanner/google/cloud/spanner_admin_database_v1/gapic/database_admin_client.py
spanner/google/cloud/spanner_admin_instance_v1/gapic/instance_admin_client.py
spanner/google/cloud/spanner_admin_instance_v1/gapic/transports/instance_admin_grpc_transport.py
spanner/google/cloud/spanner_v1/gapic/spanner_client.py
spanner/synth.metadata
spanner/tests/unit/test_client.py
spanner/tests/unit/test_instance.py

Spanner: add routing header to method metadata (via synth).

---

README.rst

Link to subdirectory
Link to pypi project page

add links to Cloud Scheduler

---

iam/README.rst

IAM: fix client lib docs link in README.

---

storage/setup.py

Storage: Require google-auth >= 1.2.0.

---

firestore/CHANGELOG.md
firestore/setup.py

Release firestore 1.0.0

---

firestore/CHANGELOG.md
firestore/setup.py

Release firestore 1.1.0

---

README.rst
tasks/CHANGELOG.md
tasks/README.rst
tasks/setup.py

Release tasks 1.0.0

---

monitoring/noxfile.py
monitoring/synth.py

Monitoring: Set environment variables for VPCSC system tests.

---

scheduler/tests/system.py

Add smoke test for scheduler.

---

README.rst
scheduler/CHANGELOG.md
scheduler/README.rst
scheduler/setup.py

Release scheduler 1.0.0

---

bigtable/docs/snippets.py

Delete cluster was still remaining. Got skipped while fixing others.
@tseaver please review.

Bigtable: fix rendering of instance admin snippets for Delete cluster

---

dns/google/cloud/dns/_http.py
dns/google/cloud/dns/client.py
dns/tests/unit/test__http.py
dns/tests/unit/test_client.py

DNS: Add 'client_info' support to client / connection.

---

resource_manager/google/cloud/resource_manager/_http.py
resource_manager/google/cloud/resource_manager/client.py
resource_manager/tests/unit/test__http.py
resource_manager/tests/unit/test_client.py

Resource Manager: Add 'client_info' support to client / connection.

---

runtimeconfig/google/cloud/runtimeconfig/_http.py
runtimeconfig/google/cloud/runtimeconfig/client.py
runtimeconfig/noxfile.py
runtimeconfig/tests/unit/test__http.py
runtimeconfig/tests/unit/test_client.py

Runtime Config: add client_info support to client / connection.

---

translate/google/cloud/translate_v2/_http.py
translate/google/cloud/translate_v2/client.py
translate/tests/unit/test__http.py
translate/tests/unit/test_client.py

Translate: add client_info support to client / connection.

---

talent/CHANGELOG.md
talent/setup.py

Release talent 0.2.0

---

scheduler/CHANGELOG.md
scheduler/setup.py

Release scheduler 1.1.0

---

dns/CHANGELOG.md
dns/setup.py

DNS: Widen range for 'google-cloud-core'.

---

firestore/CHANGELOG.md
firestore/setup.py

Firestore: Widen range for 'google-cloud-core'.

---

logging/CHANGELOG.md
logging/setup.py

Logging: Widen range for 'google-cloud-core'.

---

resource_manager/CHANGELOG.md
resource_manager/setup.py

Resource Manager: Widen range for 'google-cloud-core'.

---

spanner/CHANGELOG.md
spanner/setup.py

Spanner: Widen range for 'google-cloud-core'.

---

storage/CHANGELOG.md
storage/setup.py

Storage: Widen range for 'google-cloud-core'.

---

translate/CHANGELOG.md
translate/setup.py

Translate: Widen range for 'google-cloud-core'.

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.11.0

---

.github/CODEOWNERS

Remove @theacodes from CODEOWNERS

---

core/CHANGELOG.md
core/setup.py

Release core 1.0.0

---

pubsub/CHANGELOG.md
pubsub/setup.py

Release pubsub 0.41.0

---

.gitignore
bigquery/setup.py
bigtable/setup.py
datastore/setup.py
dns/setup.py
firestore/setup.py
logging/setup.py
resource_manager/setup.py
runtimeconfig/setup.py
spanner/setup.py
storage/setup.py
trace/setup.py
translate/setup.py

Omnibus: pin new core 1.0.0

---

dns/CHANGELOG.md
dns/setup.py

Release dns 0.30.0

---

firestore/CHANGELOG.md
firestore/setup.py

Release firestore 1.2.0

---

logging/CHANGELOG.md
logging/setup.py

Release logging 1.11.0

---

runtimeconfig/CHANGELOG.md
runtimeconfig/setup.py

Release runtimeconfig 0.29.0

---

spanner/CHANGELOG.md
spanner/setup.py

Release spanner 1.9.0

---

storage/CHANGELOG.md
storage/setup.py

Release storage 1.16.0

---

translate/CHANGELOG.md
translate/setup.py

Release translate 1.5.0

---

bigquery/CHANGELOG.md
bigquery/setup.py

Release bigquery 1.12.0

---

datastore/CHANGELOG.md
datastore/setup.py

Release datastore 1.8.0

---

storage/docs/index.rst

Storage: fix docs typo

---

error_reporting/google/cloud/error_reporting/client.py

Error Reporting: fix typo.

---

bigquery_storage/CHANGELOG.md
bigquery_storage/setup.py

Release bigquery_storage 0.5.0

---

bigquery/CHANGELOG.md
bigquery/setup.py

Release bigquery 1.12.1

---

firestore/google/cloud/firestore_v1/_helpers.py
firestore/google/cloud/firestore_v1/batch.py
firestore/google/cloud/firestore_v1/client.py
firestore/google/cloud/firestore_v1/collection.py
firestore/google/cloud/firestore_v1/document.py
firestore/google/cloud/firestore_v1/field_path.py
firestore/google/cloud/firestore_v1/gapic/firestore_client.py
firestore/google/cloud/firestore_v1/gapic/transports/firestore_grpc_transport.py
firestore/google/cloud/firestore_v1/query.py
firestore/google/cloud/firestore_v1/transaction.py
firestore/google/cloud/firestore_v1beta1/_helpers.py
firestore/google/cloud/firestore_v1beta1/batch.py
firestore/google/cloud/firestore_v1beta1/client.py
firestore/google/cloud/firestore_v1beta1/collection.py
firestore/google/cloud/firestore_v1beta1/document.py
firestore/google/cloud/firestore_v1beta1/field_path.py
firestore/google/cloud/firestore_v1beta1/gapic/firestore_client.py
firestore/google/cloud/firestore_v1beta1/gapic/transports/firestore_grpc_transport.py
firestore/google/cloud/firestore_v1beta1/query.py
firestore/google/cloud/firestore_v1beta1/transaction.py

Reverts googleapis/google-cloud-python#8039

Revert "Firestore: expand tildes in class refs FBO static analysis / autocomplete."

---

redis/docs/README.rst
redis/docs/conf.py
redis/docs/index.rst

Redis: finsh setup for 'docs' session in nox.

---

phishingprotection/docs/conf.py
phishingprotection/google/cloud/phishingprotection.py
phishingprotection/google/cloud/phishingprotection_v1beta1/__init__.py
phishingprotection/google/cloud/phishingprotection_v1beta1/gapic/phishing_protection_service_client.py
phishingprotection/google/cloud/phishingprotection_v1beta1/gapic/phishing_protection_service_client_config.py
phishingprotection/google/cloud/phishingprotection_v1beta1/gapic/transports/phishing_protection_service_grpc_transport.py
phishingprotection/google/cloud/phishingprotection_v1beta1/types.py
phishingprotection/synth.metadata
phishingprotection/synth.py
phishingprotection/tests/unit/gapic/v1beta1/test_phishing_protection_service_client_v1beta1.py

Phishing protection: fix dist name used to compute 'gapic_version'.

---

spanner/google/cloud/spanner_admin_database_v1/gapic/database_admin_client.py
spanner/google/cloud/spanner_admin_database_v1/gapic/enums.py
spanner/google/cloud/spanner_admin_database_v1/gapic/transports/database_admin_grpc_transport.py
spanner/google/cloud/spanner_admin_instance_v1/gapic/enums.py
spanner/google/cloud/spanner_admin_instance_v1/gapic/instance_admin_client.py
spanner/google/cloud/spanner_admin_instance_v1/gapic/transports/instance_admin_grpc_transport.py
spanner/google/cloud/spanner_v1/gapic/enums.py
spanner/google/cloud/spanner_v1/gapic/spanner_client.py
spanner/google/cloud/spanner_v1/gapic/transports/spanner_grpc_transport.py
spanner/synth.metadata
spanner/synth.py
spanner/tests/unit/gapic/v1/test_database_admin_client_v1.py
spanner/tests/unit/gapic/v1/test_instance_admin_client_v1.py
spanner/tests/unit/gapic/v1/test_spanner_client_v1.py

Spanner: harden synth replacement against template adding whitespace.

---

api_core/google/api_core/general_helpers.py

Unbreak pytype by silencing a false positive.

---

storage/tests/system.py

Storage: retry harder in face of 409/429 during module teardown.

---

bigtable/google/cloud/bigtable_admin_v2/__init__.py
bigtable/google/cloud/bigtable_admin_v2/gapic/bigtable_instance_admin_client.py
bigtable/google/cloud/bigtable_admin_v2/gapic/bigtable_table_admin_client.py
bigtable/google/cloud/bigtable_admin_v2/gapic/enums.py
bigtable/google/cloud/bigtable_admin_v2/gapic/transports/bigtable_instance_admin_grpc_transport.py
bigtable/google/cloud/bigtable_admin_v2/gapic/transports/bigtable_table_admin_grpc_transport.py
bigtable/google/cloud/bigtable_admin_v2/types.py
bigtable/google/cloud/bigtable_v2/__init__.py
bigtable/google/cloud/bigtable_v2/gapic/bigtable_client.py
bigtable/google/cloud/bigtable_v2/gapic/transports/bigtable_grpc_transport.py
bigtable/google/cloud/bigtable_v2/types.py
bigtable/synth.metadata
bigtable/synth.py
bigtable/tests/unit/gapic/v2/test_bigtable_client_v2.py
bigtable/tests/unit/gapic/v2/test_bigtable_instance_admin_client_v2.py
bigtable/tests/unit/gapic/v2/test_bigtable_table_admin_client_v2.py

Bigtable: docstring / formatting tweaks (via synth).

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.11.1

---

core/CHANGELOG.md
core/setup.py

Release core 1.0.1

---

dataproc/CHANGELOG.md

Release dataproc 0.4.0

---

storage/CHANGELOG.md
storage/setup.py

Release storage 1.16.1

---

dns/CHANGELOG.md
dns/setup.py

Release dns 0.30.1

---

resource_manager/CHANGELOG.md
resource_manager/setup.py

Release resource_manager 0.29.1

---

runtimeconfig/CHANGELOG.md
runtimeconfig/setup.py

Release runtimeconfig 0.29.1

---

bigquery/CHANGELOG.md
bigquery/setup.py

Release bigquery 1.14.0

---

vision/CHANGELOG.md
vision/setup.py

Release vision 0.37.0

---

videointelligence/CHANGELOG.md
videointelligence/setup.py

Release videointelligence 1.9.0

---

vision/tests/system.py

Verifies ProductSearch is blocked by VPC SC when trying to access a resource outside of a secure perimeter when run from within a secure perimeter.

Vision: Add negative Vision API Product Search tests for VPC SC

---

datacatalog/CHANGELOG.md
datacatalog/setup.py

Release datacatalog 0.2.0

---

bigquery/CHANGELOG.md
bigquery/setup.py

Release bigquery 1.15.0

---

pubsub/CHANGELOG.md
pubsub/setup.py

Release pubsub 0.42.0

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.12.0

---

pubsub/CHANGELOG.md
pubsub/setup.py

Release pubsub 0.42.1

---

storage/google/cloud/storage/hmac_key.py
storage/tests/unit/test_hmac_key.py

~~Uses #8041 as a base.~~
Toward #7851.

Storage: Add 'HMACKeyMetadata.{exists,reload,update,delete}' API methods.

---

.kokoro/docs/common.cfg
.kokoro/docs/iot.cfg
.kokoro/publish-docs.sh
test_utils/scripts/get_package_version.py

Once this works, I'll send a follow up PR to create identical configs for the rest of the APIs. :)

IoT: Fix publish docs build.

---

containeranalysis/CHANGELOG.md

Release containeranalysis 0.1.0

---

containeranalysis/setup.py

Bad setup.py resulted in a failed release #8431. 
This is take 2.

Release containeranalaysis 0.1.0

---

README.rst
speech/README.rst

Speech: Update READMEs to show 'google-cloud-speech' is GA.

---

automl/CHANGELOG.md
automl/setup.py

Release automl 0.3.0

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.13.0

---

kms/CHANGELOG.md
kms/setup.py

Release kms 1.1.0

---

storage/tests/system.py

Storage: Retry bucket creation in signing setup.

---

vision/CHANGELOG.md
vision/setup.py

Release vision 0.38.0

---

datalabeling/README.rst

Data Labeling: Fix links in README.rst

---

firestore/CHANGELOG.md
firestore/setup.py

Release firestore 1.3.0

---

translate/CHANGELOG.md
translate/setup.py

Release translate 1.6.0

---

bigquery_storage/CHANGELOG.md
bigquery_storage/setup.py

Release bigquery_storage 0.6.0

---

videointelligence/google/cloud/videointelligence_v1/gapic/enums.py
videointelligence/google/cloud/videointelligence_v1/gapic/video_intelligence_service_client_config.py
videointelligence/google/cloud/videointelligence_v1/proto/video_intelligence.proto
videointelligence/google/cloud/videointelligence_v1/proto/video_intelligence_pb2.py
videointelligence/synth.metadata
videointelligence/synth.py

Reverts googleapis/google-cloud-python#8666
I've been told folks working with the Video Intelligence team that this change is likely to get rolled back.

Revert "Videointelligence: Remove face detection feature from V1 client (via synth)."

---

containeranalysis/CHANGELOG.md
containeranalysis/setup.py

Release containeranalysis 0.2.0

---

dns/CHANGELOG.md
dns/setup.py

Release dns 0.30.2

---

datalabeling/CHANGELOG.md
datalabeling/setup.py

Release datalabeling 0.2.1

---

bigquery_datatransfer/CHANGELOG.md
bigquery_datatransfer/setup.py

Release bigquery_datatransfer 0.4.0

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.14.0

---

dlp/docs/README.rst
error_reporting/docs/README.rst
runtimeconfig/docs/index.rst

Fix doc navigation issue for DLP, Error Reporting and Runtime config.
https://googleapis.github.io/google-cloud-python/latest/index.html

Fix docs navigation issues.

---

automl/CHANGELOG.md
automl/setup.py

Release automl 0.4.0

---

storage/CHANGELOG.md
storage/setup.py

Release storage 1.17.0

---

asset/CHANGELOG.md
asset/setup.py

Release asset 0.3.0

---

pubsub/CHANGELOG.md
pubsub/setup.py

Release pubsub 0.43.0

---

language/google/cloud/language_v1/gapic/language_service_client.py
language/google/cloud/language_v1beta2/gapic/language_service_client.py

Hello,
The reference to this class is not correct. This PR introduces the correct reference.
Thanks

Language: Fix reference to EncodingType

---

webrisk/CHANGELOG.md
webrisk/setup.py

Release webrisk 0.2.0

---

vision/CHANGELOG.md
vision/setup.py

Release vision 0.38.1

---

trace/CHANGELOG.md
trace/setup.py

Release trace 0.22.0

---

tasks/CHANGELOG.md
tasks/setup.py

Release tasks 1.2.0

---

speech/CHANGELOG.md
speech/setup.py

Release speech 1.2.0

---

dataproc/CHANGELOG.md
dataproc/setup.py

Release dataproc 0.5.0

---

dlp/CHANGELOG.md
dlp/setup.py

Release dlp 0.12.1

---

error_reporting/CHANGELOG.md
error_reporting/setup.py

Release error_reporting 0.32.0

---

iam/CHANGELOG.md
iam/setup.py

Release iam 0.2.0

---

kms/CHANGELOG.md
kms/setup.py

Release kms 1.2.0

---

language/CHANGELOG.md
language/setup.py

Release language 1.3.0

---

monitoring/CHANGELOG.md
monitoring/setup.py

Release monitoring 0.32.0

---

oslogin/CHANGELOG.md
oslogin/setup.py

Release oslogin 0.2.0

---

datacatalog/CHANGELOG.md
datacatalog/setup.py

Release datacatalog 0.3.0

---

redis/CHANGELOG.md
redis/setup.py

Release redis 0.3.0

---

resource_manager/CHANGELOG.md
resource_manager/setup.py

Release resource_manager 0.29.2

---

runtimeconfig/CHANGELOG.md
runtimeconfig/setup.py

Release runtimeconfig 0.29.2

---

scheduler/CHANGELOG.md
scheduler/setup.py

Release scheduler 1.2.0

---

securitycenter/CHANGELOG.md
securitycenter/setup.py

Release securitycenter 0.3.0

---

videointelligence/CHANGELOG.md
videointelligence/setup.py

Release videointelligence 1.10.0

---

language/synth.metadata
language/synth.py

See PR #8779.
Supersedes #8794.

Language: Preserve fixed enum reference from PR #8779 during synth.

---

renovate.json

See https://renovatebot.com/docs/configuration-options/#rangestrategy

Reconfigure Renovate to preserve semver ranges.

---

datastore/CHANGELOG.md
datastore/setup.py

Release datastore 1.9.0

---

pubsub/google/cloud/pubsub_v1/publisher/client.py
pubsub/google/cloud/pubsub_v1/subscriber/client.py

Please comment if this is enough documentation for showing how to configure regional endpoint. 
I could take this opportunity to document other `kwargs` if needed, but it's recommended that users don't touch those.

Pub/Sub: document regional endpoint

---

logging/CHANGELOG.md
logging/setup.py

Release logging 1.12.0

---

renovate.json

Tweak renovate.json moar.

---

core/CHANGELOG.md
core/setup.py

Release core 1.0.3

---

websecurityscanner/CHANGELOG.md
websecurityscanner/setup.py

Release websecurityscanner 0.3.0

---

bigtable/CHANGELOG.md
bigtable/setup.py

Release bigtable 0.34.0

---

container/CHANGELOG.md
container/setup.py

Release container 0.3.0

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.14.1

---

trace/README.rst

Trace: Fix pip / usage examples in README.rst.

---

api_core/CHANGELOG.md
api_core/setup.py

Release api_core 1.14.2

---

pubsub/CHANGELOG.md
pubsub/setup.py

Release pubsub 0.45.0

---

logging/docs/snippets.py

Logging: Fix 'list_entries' example snippet with projects.

---

storage/google/cloud/storage/client.py
storage/noxfile.py
storage/setup.py
storage/tests/unit/test_blob.py
storage/tests/unit/test_client.py

- Pin version of black.
- Enforce blackening in lint.

Storage: Normalize 'lint' / 'blacken' support under nox.

---

bigquery_datatransfer/CHANGELOG.md
bigquery_datatransfer/setup.py

Release bigquery_datatransfer 0.4.1

---

bigquery_storage/CHANGELOG.md
bigquery_storage/setup.py

Release bigquery_storage 0.7.0

---

logging/CHANGELOG.md
logging/setup.py

Release logging 1.12.1

---

monitoring/google/cloud/monitoring_v3/gapic/alert_policy_service_client.py
monitoring/google/cloud/monitoring_v3/gapic/group_service_client.py
monitoring/google/cloud/monitoring_v3/gapic/metric_service_client.py
monitoring/google/cloud/monitoring_v3/gapic/notification_channel_service_client.py
monitoring/google/cloud/monitoring_v3/gapic/notification_channel_service_client_config.py
monitoring/google/cloud/monitoring_v3/gapic/transports/alert_policy_service_grpc_transport.py
monitoring/google/cloud/monitoring_v3/gapic/transports/group_service_grpc_transport.py
monitoring/google/cloud/monitoring_v3/gapic/transports/metric_service_grpc_transport.py
monitoring/google/cloud/monitoring_v3/gapic/transports/notification_channel_service_grpc_transport.py
monitoring/google/cloud/monitoring_v3/gapic/transports/uptime_check_service_grpc_transport.py
monitoring/google/cloud/monitoring_v3/gapic/uptime_check_service_client.py
monitoring/synth.metadata
monitoring/synth.py
monitoring/tests/unit/gapic/v3/test_notification_channel_service_client_v3.py

Monitoring: Add notification channel verification; remove send/recv msg size limt (via synth).

---

grafeas/grafeas/grafeas_v1/gapic/grafeas_client.py
grafeas/grafeas/grafeas_v1/gapic/transports/grafeas_grpc_transport.py
grafeas/synth.metadata
grafeas/synth.py

Grafeas: Remove send/recv msg size limit (via synth).

---

firestore/CHANGELOG.md
firestore/setup.py

Release firestore 1.4.0

---

storage/CHANGELOG.md
storage/setup.py

Release storage 1.18.0

---

bigquery_storage/tests/system/conftest.py
bigquery_storage/tests/system/test_reader.py
bigquery_storage/tests/system/test_reader_dataframe.py

Use parameterized tests for different source formats.
Towards https://github.com/googleapis/google-cloud-python/issues/8983

BigQuery Storage: Refactor system tests.

---

asset/CHANGELOG.md
asset/setup.py

Release asset 0.4.0

---

asset/.repo-metadata.json
asset/README.rst
kms/.repo-metadata.json
kms/README.rst
scheduler/.repo-metadata.json
scheduler/README.rst
tasks/.repo-metadata.json
tasks/README.rst
trace/.repo-metadata.json
trace/README.rst

Closes #8993 
Will be followed by release PRs to update links on PyPI.

Docs: Fix links to googleapis.dev

---

videointelligence/CHANGELOG.md
videointelligence/setup.py

Release videointelligence 1.11.0

---

vision/CHANGELOG.md
vision/setup.py

Release vision 0.39.0

---

monitoring/CHANGELOG.md
monitoring/setup.py

Release monitoring 0.33.0

---

scheduler/CHANGELOG.md
scheduler/setup.py

Release scheduler 1.2.1

---

trace/CHANGELOG.md
trace/setup.py

Release trace 0.22.1

---

tasks/CHANGELOG.md
tasks/setup.py

Release tasks 1.2.1

---

kms/CHANGELOG.md
kms/setup.py

Release kms 1.2.1

---

asset/CHANGELOG.md
asset/setup.py

Release asset 0.4.1

---

automl/synth.metadata
automl/synth.py

AutoML: Fix synth replace to add TablesClient.

---

runtimeconfig/docs/conf.py
runtimeconfig/google/cloud/runtimeconfig/_http.py
runtimeconfig/google/cloud/runtimeconfig/client.py
runtimeconfig/tests/unit/test__http.py
runtimeconfig/tests/unit/test_client.py

Runtime Config: Add client_options

---

error_reporting/.repo-metadata.json
error_reporting/README.rst
iam/.repo-metadata.json
iam/README.rst

Two more fixes to get the docs to be available at the DNS name. Will be followed by releases to get updated links on PyPI.

Docs: Fix documentation links for iam and error-reporting.

---

CONTRIBUTING.rst

I noticed while setting up my computer that the contributing doc is out of date. I removed the references to `system_tests/local_test_setup` since they were confusing and no longer relevant.

Update contributing doc

---

firestore/docs/conf.py
firestore/google/cloud/firestore_v1/client.py
firestore/tests/unit/v1/test_client.py

Firestore: Add client_options to v1.

---

README.rst
bigtable/CHANGELOG.md
bigtable/README.rst
bigtable/setup.py

Release bigtable 1.0.0

---

README.rst
pubsub/.repo-metadata.json
pubsub/CHANGELOG.md
pubsub/README.rst
pubsub/setup.py

Release PubSub 1.0.0

---

securitycenter/docs/snippets_findings.py
securitycenter/docs/snippets_list_assets.py
securitycenter/docs/snippets_orgs.py
securitycenter/docs/snippets_security_marks.py
securitycenter/noxfile.py

This should complete the snippets needed for the initial version of the documentation.  I'm going through now and adding them to staging, so there might be one or two that need to be refined.

SecurityCenter: update Code Snippets.

---

README.rst

Docs: Update README authentication link to current URL.

---

bigquery/google/cloud/bigquery/job.py

The current doc link results in a 404.

BigQuery: Fix doc link

---

speech/google/cloud/speech_v1/proto/cloud_speech.proto
speech/google/cloud/speech_v1/proto/cloud_speech_pb2.py
speech/synth.metadata
speech/synth.py

Also, exclude 'noxfile.py' from synth (to preserve 'samples').
Supersedes #9196.

Speech: Add speaker diarization configuration support (via synth).

---

language/synth.metadata
language/synth.py

Language: Exclude noxfile from synth.

---

bigquery/CHANGELOG.md
bigquery/setup.py

Release bigquery 1.20.0

---

storage/tests/system.py

Storage: Retry bucket creation on 503 responses.

---

dlp/noxfile.py
dlp/tests/system/gapic/v2/test_system_dlp_service_v2_vpcsc.py

Add VPC integration tests for DLP API.

DLP: Add vpcsc tests

---

dlp/synth.metadata
dlp/synth.py

DLP: Exclude 'noxfile.py' from synth.

---

firestore/README.rst

docs(firestore): remove duplicated word in README

---

bigquery_storage/google/cloud/bigquery_storage_v1beta1/gapic/big_query_storage_client.py
bigquery_storage/google/cloud/bigquery_storage_v1beta1/gapic/transports/big_query_storage_grpc_transport.py
bigquery_storage/google/cloud/bigquery_storage_v1beta1/proto/storage.proto
bigquery_storage/google/cloud/bigquery_storage_v1beta1/proto/storage_pb2.py
bigquery_storage/google/cloud/bigquery_storage_v1beta1/proto/table_reference.proto
bigquery_storage/google/cloud/bigquery_storage_v1beta1/proto/table_reference_pb2.py
bigquery_storage/synth.metadata
bigquery_storage/synth.py

chore(bigquery_storage): fix up protobuf messages w/o summary docstrings

---

speech/tests/system/gapic/v1/test_system_speech_v1.py

New Test Case which tests 3 APIs.

test(speech): add v1 systests for longrunning / streaming recognize

---

error_reporting/tests/system/test_system.py

tests(error_reporting): increase 'max_tries'

---

phishingprotection/setup.py

Should fix the b0rken release build from #9447.

fix(phishingprotection): use correct release status

---

storage/tests/perf/benchwrapper.py

fix(storage): storage_emulator_host should not necessitate google_application_credentials

---

bigquery/tests/system.py

No need to filter by time in the scripting system tests. Rather, we only
care about filtering by parent job when testing those features.
This addresses flakiness encountered:
* https://source.cloud.google.com/results/invocations/a29867f9-6492-4477-85d4-d9de8d9ff85b/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-python%2Fpresubmit%2Fbigquery/log
* https://source.cloud.google.com/results/invocations/cdb77d4a-b0e3-4339-ab55-ae08fb2b297d/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-python%2Fpresubmit%2Fbigquery/log

test(bigquery): simplify scripting system test to reduce flakiness

---

api_core/docs/auth.rst
error_reporting/google/cloud/error_reporting/_logging.py
error_reporting/google/cloud/error_reporting/client.py
spanner/google/cloud/spanner_v1/client.py
storage/google/cloud/storage/blob.py
storage/google/cloud/storage/bucket.py
translate/tests/system/test_vpcsc.py

docs: remove references to the old authentication credentials

---

spanner/tests/system/test_system.py

tests(spanner): harden 'test_transaction_batch_update_w_syntax_error'

---

spanner/tests/system/test_system.py

tests(spanner): harden 'test_reload_instance' against EC

---

trace/google/cloud/trace/_gapic.py
trace/google/cloud/trace/client.py
trace/google/cloud/trace/v1/_gapic.py
trace/google/cloud/trace/v1/client.py
trace/tests/unit/v1/test__gapic_v1.py
trace/tests/unit/v1/test_client_v1.py
trace/tests/unit/v2/test__gapic_v2.py
trace/tests/unit/v2/test_client_v2.py

feat(trace): add `client_options` to constructor

---

dns/google/cloud/dns/_http.py
dns/google/cloud/dns/client.py
dns/tests/unit/test__http.py
dns/tests/unit/test_client.py

feat(dns): add 'client_options' argument to client ctor

---

datacatalog/noxfile.py
datacatalog/samples/tests/conftest.py
datacatalog/samples/tests/test_create_entry_group.py
datacatalog/samples/v1beta1/create_entry_group.py
datacatalog/synth.py

Fixes https://github.com/googleapis/google-cloud-python/issues/9583

feat(datacatalog): add sample to create an entry group

---

automl/google/cloud/automl_v1beta1/tables/tables_client.py

Typo in AutoML Tables code example at https://googleapis.dev/python/automl/latest/gapic/v1beta1/tables.html

docs(automl): fix typo in code example for AutoML Tables

---

automl/google/cloud/automl_v1beta1/tables/tables_client.py

Fix the missing comma in AutoML Tables's doc

docs(automl): add missing comma to the doc

---

CONTRIBUTING.rst

docs(all): add commits convention description in CONTRIBUTING.rst

---

bigquery/google/cloud/bigquery/dataset.py

feat(bigquery): add iamMember entity in access class of dataset

---

bigquery/setup.py

fix(bigquery): add six dependency in setup file

---

automl/google/cloud/automl_v1beta1/tables/tables_client.py

Local render result: https://screenshot.googleplex.com/P8Yat8M4zdF

doc(automl): add example for creating a TablesClient for EU in docstring

---

cloudbuild/synth.py

chore(cloudbuild): fix syntax errors in synth.py

---

recommender/synth.py

Fixes #9884 (broken Autosynth runs)

chore(recommender): correct config path in synth file for recommender

---

runtimeconfig/setup.py
runtimeconfig/tests/unit/test__http.py

fix(runtimeconfig): update test assertion and core version pins

---

resource_manager/setup.py
resource_manager/tests/unit/test__http.py

fix(resourcemanager): update test assertion and core version pin

---

translate/setup.py
translate/tests/unit/v2/test__http.py

fix(translate): update test assertion and core version pins

---

storage/setup.py

This update the Storage dependency on the core module which contains the latest api-core which is needed to support Conditional/version3 IAM policy.
@busunkim96

chore(storage): bump core dependency to 1.2.0

---

storage/CHANGELOG.md
storage/setup.py

chores(storage): release 1.25.0

---

bigquery/google/cloud/bigquery/job.py

Just a tiny spelling fix. Did find this typo accidentally

docs(bigquery): typo fix

---

README.rst

DOCS: Fix Google Cloud OS Login pypi link in readme

---

README.rst

Fix: Fix link to BigQuery Storage Documentation

---

README.rst

Fixes #<issue_number_goes_here> 🦕

docs: add access approval to README

---

README.rst

chore: update README doc

---

scripts/split_repo_migration/single-library.git-migrate-history.sh

chore: Revert restriction in monorepo migration script

---

scripts/split_repo_migration/single-library.git-migrate-history.sh

This was blocking the migration of dialogflow

fix(migration): Prevent failure when git filter encounters no files

---

containers/python-bootstrap-container/.repo-metadata.json

chore: use the package name in the docs url for new packages

---

containers/python-bootstrap-container/.repo-metadata.json
containers/python-bootstrap-container/entrypoint.sh

chore: fix docs url for new non-cloud libraries

---

packages/google-apps-script-type/docs/index.rst
packages/google-apps-script-type/noxfile.py
packages/google-apps-script-type/scripts/client-post-processing/docs-index-rst-for-unversioned-apis.yaml
scripts/client-post-processing/docs-index-rst-for-unversioned-apis.yaml

build: fix docs build for google-apps-script-type

---

.github/workflows/configure_release_please.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/main.yml
.github/workflows/scripts.yml
.github/workflows/unittest.yml
.github/workflows/updatechangelog.yml

build: add fetch depth when using actions/checkout

---

packages/google-ai-generativelanguage/google/ai/generativelanguage_v1beta/types/retriever.py
packages/google-ai-generativelanguage/google/ai/generativelanguage_v1beta3/services/permission_service/async_client.py
packages/google-ai-generativelanguage/google/ai/generativelanguage_v1beta3/services/permission_service/client.py
packages/google-ai-generativelanguage/google/ai/generativelanguage_v1beta3/services/permission_service/transports/rest.py
packages/google-ai-generativelanguage/google/ai/generativelanguage_v1beta3/types/permission.py

chore: fix the docs build in google-ai-generativelanguage

---

packages/google-cloud-network-management/google/cloud/network_management_v1/types/connectivity_test.py

chore: fix the docs build in google-cloud-network-management

---

packages/google-cloud-dms/google/cloud/clouddms_v1/types/conversionworkspace_resources.py

chore: fix the docs build for google-cloud-dms

---

packages/google-cloud-securitycentermanagement/google/cloud/securitycentermanagement_v1/types/security_center_management.py

chore: fix the docs in fix-google-cloud-securitycentermanagement

---

packages/google-cloud-alloydb/google/cloud/alloydb_v1/types/resources.py
packages/google-cloud-alloydb/google/cloud/alloydb_v1alpha/types/resources.py
packages/google-cloud-alloydb/google/cloud/alloydb_v1beta/types/resources.py

chore: fix the docs build in google-cloud-alloydb

---

packages/google-cloud-dialogflow-cx/google/cloud/dialogflowcx_v3beta1/types/tool.py

chore: fix docs build in google-cloud-dialogflow-cx

---

packages/google-cloud-documentai/google/cloud/documentai_v1beta3/types/document_service.py

chore: fix docs build in google-cloud-documentai 

---

packages/google-cloud-enterpriseknowledgegraph/google/cloud/enterpriseknowledgegraph_v1/types/service.py

chore: fix docs build in google-cloud-enterpriseknowledgegraph

---

packages/google-cloud-service-control/google/cloud/servicecontrol_v1/types/service_controller.py

chore: fix docs build in google-cloud-service-control

---

packages/google-cloud-workflows/docs/index.rst

chore: fix docs build in google-cloud-workflows

---

packages/google-shopping-merchant-reports/google/shopping/merchant_reports_v1beta/types/reports.py

chore: fix docs build in google-shopping-merchant-reports 

---

packages/google-maps-routing/google/maps/routing_v2/types/toll_passes.py

chore: fix docs build in google-maps-routing

---

packages/google-cloud-commerce-consumer-procurement/.repo-metadata.json
packages/google-cloud-datacatalog-lineage/.repo-metadata.json
packages/google-cloud-support/.repo-metadata.json

See 
https://github.com/googleapis/googleapis/blob/eb1a043852e0894c135201a4917b8210ad7bb4fc/google/cloud/support/v2/cloudsupport_v2.yaml#L3
https://github.com/googleapis/googleapis/blob/eb1a043852e0894c135201a4917b8210ad7bb4fc/google/cloud/commerce/consumer/procurement/v1/cloudcommerceconsumerprocurement_v1.yaml#L3
https://github.com/googleapis/googleapis/blob/eb1a043852e0894c135201a4917b8210ad7bb4fc/google/cloud/datacatalog/lineage/v1/datalineage_v1.yaml#L3

chore: Update api_ids in .repo-metadata.json

---

.github/workflows/main.yml

Fixes #<issue_number_goes_here> 🦕

chore: update workflow permissions to read-only

---

.github/workflows/docs.yml

chore(presubmits): block only merge PRs on doc check failures

---

.github/workflows/docs.yml

chore(process): Fix github.action in docs workflows

---

packages/google-cloud-storage-control/.repo-metadata.json
packages/google-cloud-storage-control/README.rst
packages/google-cloud-storage-control/docs/index.rst
packages/google-cloud-storage-control/docs/summary_overview.md

Fixes b/347745571 🦕
Also see related issue to improve the process of promoting clients to stable: #10876

chore: update release level to stable

---

.kokoro/release-single.sh
.kokoro/release/common.cfg

build: release script update

---

packages/google-cloud-dialogflow-cx/CHANGELOG.md

feat: add options of client_certificate_settings, bigquery_export_settings, bearer_token_config and boost_control_spec; add support of ALAW encoding
Add conventional commits for PR https://github.com/googleapis/google-cloud-python/pull/13242

chore: update changelog

---

.github/release-trigger.yml

See https://github.com/googleapis/synthtool/pull/2033

build: use multiScm for Kokoro release builds

---

.github/.OwlBot.lock.yaml

Reverts googleapis/google-cloud-python#13490

chore(revert): revert update post processor image

---

packages/google-cloud-automl/setup.py

See https://pypi.org/project/google-cloud-storage/3.0.0/

fix: allow google-cloud-storage 3.x

---

packages/googleapis-common-protos/pyproject.toml

Fixes https://github.com/googleapis/google-cloud-python/issues/13602

fix: exclude docs in tool.setuptools.packages.find

---

packages/grpc-google-iam-v1/pyproject.toml

See https://github.com/googleapis/google-cloud-python/issues/13585

fix: resolve issue where pre-release versions of dependencies are installed

---

packages/google-maps-routeoptimization/.repo-metadata.json
packages/google-maps-routeoptimization/README.rst

docs: fix typo in README

---

packages/google-cloud-datacatalog/.repo-metadata.json

----------
Update the repo metadata to remove unnecessary whitespace
Fixes b/367426932 🦕

chore: Update .repo-metadata.json

---

packages/google-cloud-iam/.OwlBot.yaml

Include `v3` and `v3beta` in IAM owlbot config.

chore: include v3 in iam owlbot config

---

packages/google-cloud-compute-v1beta/.OwlBot.yaml
packages/google-cloud-compute-v1beta/.repo-metadata.json

Towards https://github.com/googleapis/google-cloud-python/issues/12471

chore: add initial files for google/cloud/compute_v1beta

---

packages/google-apps-events-subscriptions/.OwlBot.yaml

Reverts googleapis/google-cloud-python#13962
See b/421467004

chore: remove events subscription v1beta

---

.generator/cli.py
.generator/test_cli.py

This PR adds support for CLI arguments `librarian`, `input`, `output` and `source`

chore: add support for cli arguments

---

packages/google-shopping-merchant-lfp/.repo-metadata.json
packages/google-shopping-merchant-lfp/README.rst
packages/google-shopping-merchant-lfp/docs/index.rst
packages/google-shopping-merchant-lfp/google/shopping/merchant_lfp/__init__.py

feat: set `google.shopping.merchant_lfp_v1` as the default import for `google.shopping.merchant_lfp`

feat: update release level to stable

---

packages/google-shopping-merchant-products/.repo-metadata.json
packages/google-shopping-merchant-products/README.rst
packages/google-shopping-merchant-products/docs/index.rst
packages/google-shopping-merchant-products/google/shopping/merchant_products/__init__.py

feat!: set `google.shopping.merchant_products_v1` as the default import for `google.shopping.merchant_products`

feat!: update release level to stable

---

packages/google-shopping-type/.repo-metadata.json
packages/google-shopping-type/README.rst

feat: bump release level to stable

---

.release-please-manifest.json

chore: update release-please-manifest

---

.generator/cli.py
.generator/test_cli.py

This PR fixes the issue to run the generate command with the build flag.

fix: add repo argument to the build handler

---

.librarian/state.yaml

chore: fix source_roots

---

.librarian/state.yaml
scripts/configure_state_yaml/configure_state_yaml.py

This PR incudes the following changes:
- Update `scripts/configure_state_yaml/configure_state_yaml.py` to reflect the change in https://github.com/googleapis/google-cloud-python/pull/14297
- Add `tag_format` as per https://github.com/googleapis/librarian/blob/main/doc/language-onboarding.md

chore: polish state.yaml

---

.generator/cli.py
.generator/test_cli.py

This PR adds support for the librarian language specific `release-init` commit following https://github.com/googleapis/librarian/blob/main/doc/language-onboarding.md
Towards https://github.com/googleapis/librarian/issues/886

chore: add support for librarian release init

---

.generator/cli.py
.generator/test_cli.py

This PR builds on top of https://github.com/googleapis/google-cloud-python/pull/14378. Please review #14378 first
This PR addresses the feedback in https://github.com/googleapis/google-cloud-python/pull/14353#discussion_r2331353376

chore(librarian): refactor function to create changelog header

---

.generator/cli.py

This PR addresses the following feedback:
- https://github.com/googleapis/google-cloud-python/pull/14353#discussion_r2331362015
- https://github.com/googleapis/google-cloud-python/pull/14353#discussion_r2331366590
- https://github.com/googleapis/google-cloud-python/pull/14353#discussion_r2331367757
- https://github.com/googleapis/google-cloud-python/pull/14353#discussion_r2331372304
- https://github.com/googleapis/google-cloud-python/pull/14353#discussion_r2331385104

chore(librarian): various refactoring following #14353

---

.librarian/generator-input/client-post-processing/add-missing-dependencies-to-setup-py-constraints.yaml
.librarian/generator-input/client-post-processing/bigquery-storage-integration.yaml
.librarian/generator-input/client-post-processing/doc-formatting.yaml

Sync post processing scripts in [.librarian/generator-input](https://github.com/googleapis/google-cloud-python/tree/main/.librarian/generator-input) with [scripts/client-post-processing](https://github.com/googleapis/google-cloud-python/tree/main/scripts/client-post-processing).

chore(librarian): sync post processing scripts

---

.librarian/state.yaml
scripts/configure_state_yaml/packages_to_onboard.yaml

Onboard `google-cloud-video-live-stream` to librarian
Towards https://github.com/googleapis/librarian/issues/761

chore(librarian): add google-cloud-video-live-stream to state.yaml

---

packages/google-cloud-bigquery-storage/testing/.gitignore

Similar to https://github.com/googleapis/google-cloud-python/pull/13761 and https://github.com/googleapis/google-cloud-python/pull/13746

chore: remove testing/.gitignore

---

.generator/cli.py
.generator/test_cli.py

This PR adds the name and the default_version fields to the generated `.repo-metadata.json` file within the librarian workflow.

chore: add name and default_version to metadata

---

.librarian/state.yaml
scripts/configure_state_yaml/packages_to_onboard.yaml

Towards https://github.com/googleapis/librarian/issues/762
How the generated changes look like when we run `librarian generate`: https://github.com/googleapis/google-cloud-python/pull/14580

chore(librarian): onboard 10 libraries

---

.generator/cli.py
.librarian/state.yaml
scripts/configure_state_yaml/packages_to_onboard.yaml

This PR depends on https://github.com/googleapis/google-cloud-python/pull/14551. Please review #14551 first
Towards https://github.com/googleapis/librarian/issues/1061

chore(librarian): onboard google-cloud-access-context-manager

---

.generator/cli.py
.librarian/state.yaml
scripts/configure_state_yaml/packages_to_onboard.yaml

This PR depends on https://github.com/googleapis/google-cloud-python/pull/14551 and https://github.com/googleapis/google-cloud-python/pull/14587. Please review those PRs first.
Towards https://github.com/googleapis/librarian/issues/1076

chore(librarian): onboard google-cloud-audit-log
