googleapis/google-cloud-python

- core/CHANGELOG.md
- core/setup.py
> Release core 0.29.0

- firestore/google/cloud/firestore_v1beta1/query.py
- firestore/tests/unit/test_query.py
> Firestore: for queries ordered on '__name__', expand field values to full paths.

- ndb/src/google/cloud/ndb/key.py
- ndb/src/google/cloud/ndb/model.py
- ndb/src/google/cloud/ndb/query.py
- ndb/tests/unit/test_model.py
~~**NOTE**: This has #6694 as diffbase.~~
I have removed some features of comparison that depend on `StructuredProperty` or `Expando` being implemented. I added a note to #6251 to go back and add the behavior when relevant.
> Implement comparison helpers for `ndb.Model`

- spanner/google/cloud/spanner_v1/database.py
- spanner/tests/system/test_system.py
- spanner/tests/unit/test_database.py
The operation_id im update_ddl method is missing. The parameter is in the documentation https://googleapis.github.io/google-cloud-python/latest/spanner/database-usage.html#update-an-existing-database but it was missing in the implementation. 
I've run system tests manually - even if the update_ddl system tests are skipped  due to flakyness (I removed the skip annotations and increased timeouts) so I confirm it works :).
Closes #6737.
> Spanner: add 'operation_id' parameter 'Database.update_ddl' (#6737)

- bigquery/docs/snippets.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/noxfile.py
- bigquery/setup.py
- bigquery/tests/unit/test_job.py
- bigquery/tests/unit/test_table.py
This makes it easier to use the new BigQuery Storage API (currently in
Alpha) in combination with the BigQuery API.
> Add to_bqstorage to convert from Table[Reference] google-cloud-bigquery-storage reference

- container/CHANGELOG.md
- container/setup.py
> Release container 0.2.0

- trace/CHANGELOG.md
- trace/setup.py
> Release trace 0.20.0

- bigquery/google/cloud/bigquery/client.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/system.py
- bigquery/tests/unit/test_table.py
This is a faster method to read a dataframe from a table using the
(alpha) BigQuery Storage API. Supply a BQ Storage API to to_dataframe()
to use the faster method.
Currently it cannot read data from (small) anonymous query results
tables, thus why the system test has a destination table for the query.
> Add option to use BQ Storage API with to_dataframe

- ndb/MIGRATION_NOTES.md
- ndb/src/google/cloud/ndb/__init__.py
- ndb/src/google/cloud/ndb/model.py
- ndb/tests/conftest.py
- ndb/tests/unit/test_model.py
Deserialization is largely delegated to Datastore, so it's really just a matter of adapting an NDB entity to a Datastore entity.
> Deserialize an entity from a protobuffer.

- .gitignore
- api_core/google/api_core/iam.py
- api_core/setup.cfg
- api_core/tests/unit/test_iam.py
> API Core: fix pytype build

- trace/google/cloud/trace/client.py
- trace/google/cloud/trace/v1/client.py
- trace/tests/unit/v1/test_client_v1.py
- trace/tests/unit/v2/test_client_v2.py
cc @liyanhui1228 
@bogdandrutu and I are seeing a persistent [memory leak](https://github.com/census-instrumentation/opencensus-python/issues/334) in projects using the [opencensus stackdriver exporter](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/stats/exporters/stackdriver_exporter.py), which uses `google.cloud.trace.client.Client` and repeatedly calls [`batch_write_spans`](https://github.com/googleapis/google-cloud-python/blob/92465cbc4d9c0ba251838e9cd17f61d14b470e04/trace/google/cloud/trace/client.py#L57-L100).
Reusing the trace client's API object fixes the leak.
> Fix trace client memory leak

- api_core/google/api_core/iam.py
- docs/core/iam.rst
Napoleon-ize docstrings in `google.api_core.iam`.
Order the `core/iam` docs page entries in source order.
Closes #6161.
> API Core: add usage example for 'google.api_core.iam.Polcy'.

- spanner/CHANGELOG.md
- spanner/setup.py
> Release spanner 1.7.0

- logging/CHANGELOG.md
- logging/setup.py
> Release logging 1.9.0

- firestore/google/cloud/firestore_v1beta1/query.py
- firestore/tests/unit/test_query.py
- Snapshot cursors imply on ordering on `__name__`, if not already present.  Implied ordering is added at the end of the list, matching the direction of the prior entry (`ASCENDING` if none exist).
- Snapshots copy their document reference into the `__name__` field of their document values.
- Disallow use of snapshots from foreign collections as query cursors.
- In a query with one or more `where` clauses using ordering operators, and including a snapshot cursor, we must add ordering on the field(s) used (IFF the field is not already in the query's `order_by`).
Closes #6665.
> Firestore: impose required semantics for snapshots as cursors.

- firestore/google/cloud/firestore_v1beta1/query.py
- firestore/tests/unit/test_cross_language.py
- firestore/tests/unit/test_query.py
~~Uses #6837 as a base:  please review that PR first.~~
Toward #6533.
Fix confusion (from #6829) between `__name__` fields as simple strings and as `DocumentReference` instances.
> Firestore: add driver for query conformance tests.

- storage/google/cloud/storage/blob.py
- storage/tests/system.py
- storage/tests/unit/test_blob.py
Fixes #6524
Test code (`test_6524.py`) -
```
from google.cloud import storage
client = storage.Client()
bucket = client.get_bucket('test_cloud-python_6524')
blob = bucket.get_blob('big_file.bin')
blob.update_storage_class('NEARLINE')
```
Create a 5GB file `big_file.bin` in the `test_pr6524` bucket -
```
dd if=/dev/urandom of=big_file.bin bs=1k count=5000000
gsutil cp big_file.bin gs://test_cloud-python_6524/big_file.bin
```
Test using `google-cloud-storage==1.13.0` -
```
$ virtualenv 6524-old
...
$ ./6524-old/bin/pip install -r requirements.txt
$ gsutil ls -L gs://test_cloud-python_6524/big_file.bin | grep 'Storage class:'
Storage class:          MULTI_REGIONAL
$ ./6524-old/bin/python test_6524.py
File "test_6524.py", line 10, in <module> …
```
> Storage: Update Blob.update_storage_class to support rewrite tokens

- api_core/google/api_core/datetime_helpers.py
- api_core/tests/unit/test_datetime_helpers.py
> Api_core: Convert 'DatetimeWithNanos' to / from 'google.protobuf.timestamp_pb2.Timestamp'

- firestore/google/cloud/firestore_v1beta1/collection.py
- firestore/google/cloud/firestore_v1beta1/query.py
> Firestore: document timeouts for 'Query.get' / 'Collection.get'.

- index.html
> Remove mentions / links of 'google-cloud' from Github landing page.

- container/README.rst
Also, use new 'Google Kubernetes Engine' branding for the back-end API.
Closes #5777
> Container: Improve linkage between container docs pages.

- pubsub/docs/publisher/index.rst
- pubsub/google/cloud/pubsub_v1/publisher/client.py
/cc  @anguillanneuf 
Closes #6201.
> Pubsub: emphasize that returned futures may differ from stdlib futures.

- bigquery/google/cloud/bigquery/client.py
- bigquery/google/cloud/bigquery/table.py
- dns/google/cloud/dns/client.py
- dns/google/cloud/dns/zone.py
- firestore/google/cloud/firestore_v1beta1/document.py
- logging/google/cloud/logging/client.py
- logging/google/cloud/logging/logger.py
- monitoring/google/cloud/monitoring_v3/query.py
- resource_manager/google/cloud/resource_manager/client.py
- runtimeconfig/google/cloud/runtimeconfig/config.py
- spanner/google/cloud/spanner_v1/client.py
- spanner/google/cloud/spanner_v1/instance.py
- storage/google/cloud/storage/bucket.py
- storage/google/cloud/storage/client.py
> Docs/fixit: normalize docs for 'page_size' / 'max_results' / 'page_token'

- logging/google/cloud/logging/client.py
- logging/google/cloud/logging/handlers/app_engine.py
- logging/google/cloud/logging/handlers/container_engine.py
- logging/google/cloud/logging/handlers/handlers.py
- logging/tests/unit/handlers/test_app_engine.py
- logging/tests/unit/handlers/test_container_engine.py
- logging/tests/unit/handlers/test_handlers.py
- logging/tests/unit/test_client.py
> Logging: allow setting name, args on default handler (post-blacken)

- dns/google/cloud/dns/zone.py
- dns/tests/unit/test_zone.py
The behaviour of the [`MangedZones: get`](https://cloud.google.com/dns/docs/reference/v1/managedZones/get) endpoint is such that when only the `id` field of a non-existent `ManagedZone` is requested, a 200 status code response with body `{}` is returned.
This is arguably undesirable behaviour, however this patch serves to ensure that the Python SDK behaves expectedly with the API in its current state.
Is anyone aware of where the best place to leave feedback on the API would be? Is the "Leave Feedback" section on the documentation page appropriate? Is it an open-source project?
> [DNS] Ensure that `ManagedZone:exists()` does not misreport `True` result.

- ndb/noxfile.py
- ndb/src/google/cloud/ndb/__init__.py
- ndb/src/google/cloud/ndb/client.py
- ndb/tests/conftest.py
- ndb/tests/unit/test_client.py
This is patterned off of `datastore.client.Client` and depends heavily on `google.cloud.client`.
> NDB: Start in on `ndb.client.Client`

- datastore/google/cloud/datastore/batch.py
This should have an email that matches a CLA.
> Storage: add missing call to batch.begin() in example.

- firestore/google/cloud/firestore_v1beta1/batch.py
- firestore/tests/unit/test_batch.py
- firestore/tests/unit/test_collection.py
- firestore/tests/unit/test_document.py
> Firestore: enable use of 'WriteBatch' as a context manager.

- firestore/google/cloud/firestore_v1beta1/_helpers.py
- firestore/tests/unit/test__helpers.py
Uses #6919 as a base:  please review only the last commit here until rebased after merging that PR.
Closes #6547.
> Firestore: preserve timestamp nanos in document data

- firestore/google/cloud/firestore_v1beta1/watch.py
- firestore/tests/unit/test_cross_language.py
- firestore/tests/unit/test_watch.py
Fixes two bugs in the watch code:
- always-truthiness of protobufs foiled a delete/remove document case.
- change map would receive keys that were document snapshots instead of document names sometimes,
foiling the reset code.
Closes #6533
> Firestore: implement listen conformance

- firestore/google/cloud/firestore_v1beta1/_helpers.py
- firestore/google/cloud/firestore_v1beta1/collection.py
- firestore/google/cloud/firestore_v1beta1/document.py
- firestore/google/cloud/firestore_v1beta1/query.py
- firestore/google/cloud/firestore_v1beta1/transforms.py
- firestore/tests/unit/test__helpers.py
- firestore/tests/unit/test_collection.py
- firestore/tests/unit/test_document.py
- firestore/tests/unit/test_query.py
- firestore/tests/unit/test_transforms.py
Adds `__eq__` for the following types:
- `ArrayRemove`
- `ArrayUnion`
- `CollectionReference`
- `DocumentSnapshot`
- `ExistsOption`
- `LastUpdatedOption`
- `Query`
Closes #6552.
> Firestore: implement equality semantics for public types

- firestore/setup.py
That release added the `from_timestamp_pb` / `to_timestamp_pb` methods to `DatetimeWithNanos`.
> Firestore: pin 'google-api_core >= 1.7.0'.

- bigquery/google/cloud/bigquery/magics.py
- bigquery/tests/unit/test_magics.py
This update will result in better consistency with other Jupyter magics and also allow the user to avoid displaying large results when using the BigQuery cell magic.
Resolves https://github.com/googleapis/google-cloud-python/issues/6907
> BigQuery: Do not return results of query magic when assigned to variable

- bigtable/tests/system.py
> Bigtable: plug systest instance leaks

- ndb/src/google/cloud/ndb/_api.py
- ndb/src/google/cloud/ndb/client.py
- ndb/tests/unit/test__api.py
A helper function which takes a `client.Client` instance and returns an instance of the gRPC "stub" for the Google Datastore API. Based off of #6876
> NDB: Get Datastore gRPC API stub

- ndb/MIGRATION_NOTES.md
- ndb/src/google/cloud/ndb/tasklets.py
- ndb/tests/unit/test_tasklets.py
Legacy NDB does some work to maintain debugging state which hasn't been reproduced here, yet. I've updated #6251 to include the methods that would implement this. I'm not 100% certain we need it.
> NDB: Implement ``Future`` base class.

- securitycenter/README.rst
Remove spurious boilerplate.
Closes #7039.
> Security Center: Fix 404 for 'Client Library Documentation' link.

- ndb/src/google/cloud/ndb/__init__.py
- ndb/src/google/cloud/ndb/tasklets.py
- ndb/tests/conftest.py
- ndb/tests/unit/test_tasklets.py
``TaskletFuture`` is a ``Future`` subclass which wraps the generator
returned by calling a tasklet and provides a means of advancing the
tasklet when results of dependent futures are ready.
> NDB: Implement ``TaskletFuture``.

- bigquery/tests/system.py
- Centralize bucket creation in BQ systests.
- Add retry for transient errors from 'bucket.create', blob operations
Closes #7005.
> BigQuery: Harden systests against transient GCS errors.

- tasks/google/cloud/tasks_v2beta3/gapic/cloud_tasks_client.py
This example is consistent with a similar change implemented in nodejs version here: googleapis/nodejs-tasks#142
> Tasks: Add working example for 'create_queue'

- spanner/google/cloud/spanner_admin_database_v1/gapic/transports/database_admin_grpc_transport.py
- spanner/google/cloud/spanner_admin_instance_v1/gapic/transports/instance_admin_grpc_transport.py
- spanner/google/cloud/spanner_v1/gapic/enums.py
- spanner/google/cloud/spanner_v1/gapic/transports/spanner_grpc_transport.py
- spanner/synth.metadata
- spanner/synth.py
> Spanner: pick up stub docstring fix from GAPIC generator.

- pubsub/google/cloud/pubsub_v1/publisher/client.py
- pubsub/google/cloud/pubsub_v1/subscriber/client.py
- pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_subscriber_client.py
Silences pending deprecation warnings for passing channel.
Closes #6887.
> Pub/sub: pass transport w/ custom channel to GAPIC API clients.

- tasks/google/cloud/tasks_v2beta3/gapic/cloud_tasks_client.py
- tasks/synth.metadata
- tasks/synth.py
Also, remove now-spurious replacements.
Supersedes #7057.
> Tasks: restore expanded example from PR #7025 after synth.

- logging/noxfile.py
Closes #7063.
In autosynth runs, the `blacken` step for logging fails with the following:
```
Running session blacken
Session blacken skipped: Python interpreter 3.7 not found.
synthtool > Cleaned up 2 temporary directories.
synthtool > Wrote metadata to synth.metadata.
```
> Logging: use 'python-3.6' for 'blacken' run.

- texttospeech/README.rst
Was pointed to https://googlecloudplatform.github.io/google-cloud-python/latest/texttospeech/api.html which has no content.
The correct URL appears to be https://googlecloudplatform.github.io/google-cloud-python/latest/texttospeech/index.html
Not sure if the README is hand-written or generated, but a user reported the bug
> Fix `Client Library Documentation` link

- pubsub/google/cloud/pubsub_v1/publisher/_batch/thread.py
- pubsub/tests/unit/pubsub_v1/publisher/batch/test_thread.py
in `google.cloud.pubsub_v1.publisher._batch.thread.Batch` [`self._client.api.publish(self._topic, self._messages)`](https://github.com/googleapis/google-cloud-python/pull/7071/files#diff-13577f0feaf50916f99888dc4258f6dcL201) may [raise `google.api_core.exceptions.RetryError`](https://github.com/googleapis/google-cloud-python/blob/master/api_core/google/api_core/retry.py#L163).
if `Batch._commit` does not catch an error then `Batch._futures` may never complete.
`google.api_core.exceptions.RetryError` and `google.api_core.exceptions.GoogleAPICallError` are the only inheritors of `google.api_core.exceptions.GoogleAPIError`, so that seemed like the appropriate error to catch.
> PubSub: Propagate RetryError in PublisherClient.publish

- firestore/google/cloud/firestore_v1beta1/collection.py
- firestore/tests/system.py
- firestore/tests/unit/test_collection.py
> fix: respect transform values passed into collection.add

- ndb/docs/conf.py
- ndb/docs/index.rst
- ndb/docs/tasklets.rst
- ndb/noxfile.py
- ndb/src/google/cloud/ndb/__init__.py
- ndb/src/google/cloud/ndb/_datastore_api.py
- ndb/src/google/cloud/ndb/_runstate.py
- ndb/src/google/cloud/ndb/context.py
- ndb/src/google/cloud/ndb/exceptions.py
- ndb/src/google/cloud/ndb/key.py
- ndb/src/google/cloud/ndb/model.py
- ndb/src/google/cloud/ndb/tasklets.py
- ndb/tests/conftest.py
- ndb/tests/system/test_system.py
- ndb/tests/unit/test__datastore_api.py
- ndb/tests/unit/test_context.py
- ndb/tests/unit/test_key.py
- ndb/tests/unit/test_model.py
- ndb/tests/unit/test_tasklets.py
This includes the first system tests. We can now retrieve an NDB entity from a Datastore backend.
The system tests uncovered a few bugs in some already committed code, and these were fixed. Mostly for this reason, this has a lot more changes than I usually like to include in a single PR. Sorry about that.
> NDB: Implement Key.get() and Key.get_async()

- ndb/MIGRATION_NOTES.md
- ndb/src/google/cloud/ndb/__init__.py
- ndb/src/google/cloud/ndb/tasklets.py
- ndb/tests/unit/test_tasklets.py
In general, I only anticipate users interacting with futures created
for them by NDB, and then only with the interface defined by
``tasklets.Future``.
> NDB: Make ``TaskletFuture`` and ``MultiFuture`` private.

- ndb/src/google/cloud/ndb/tasklets.py
- ndb/tests/unit/test_tasklets.py
These were originally implemented as class methods on the `tasklets.Future` class. I've made them standalone functions in `tasklets` but added static methods to `tasklets.Future` for backwards compatibility.
> NDB: Implement wait_any and wait_all.

- ndb/src/google/cloud/ndb/tasklets.py
This fixes the failing Sphinx docs build. The failure snuck in via merging of disparate branches.
> NDB: Fix sneaky bug in Sphinx docs build.

- bigquery/google/cloud/bigquery/table.py
- bigquery/noxfile.py
- bigquery/setup.py
- bigquery/tests/system.py
- bigquery/tests/unit/test_table.py
- bigquery_storage/google/cloud/bigquery_storage_v1beta1/reader.py
- bigquery_storage/noxfile.py
- bigquery_storage/setup.py
- bigquery_storage/tests/system/test_system.py
- bigquery_storage/tests/unit/test_reader.py
This allows pandas users to select different sized floats for
performance at the expense of accuracy. With pandas 0.24, it will also
allow pandas users to use the new pandas.Int64Dtype() for nullable
integer columns.
Closes #7049
> Add option to choose dtypes by column in to_dataframe.

- pubsub/google/cloud/pubsub_v1/subscriber/client.py
Close #7042 
I wonder if there's a systematic way to update these broken links in the documentation?
> Pub/Sub doc: fix broken links

- firestore/google/cloud/firestore_v1beta1/query.py
- firestore/tests/unit/test_query.py
> Firestore: remove bogus error checking of query response stream.

- bigquery/docs/snippets.py
In response to feedback internally Bug 123578325, add a sample (acts as a system test, too) which shows how to populate the `total_rows` value.
> Add sample for fetching total_rows from query results.

- bigquery_storage/README.rst
- bigquery_storage/docs/index.rst
- bigquery_storage/docs/quickstart.py
- bigquery_storage/docs/quickstart_test.py
- bigquery_storage/noxfile.py
This snippet will be included at the bottom of the client
library index page for the BigQuery Storage API. It will
also be included in the docs at cloud.google.com.
Adds a new session for nox to run the tests for samples
in the docs directory. Acts as a system test of the rows()
method.
> Add quickstart demonstrating most BQ Storage API read features

- firestore/google/cloud/firestore_v1beta1/document.py
- firestore/tests/unit/test_document.py
Returns database-relative path.
Closes #6554.
> Firestore: add 'DocumentReference.path' property.

- firestore/google/cloud/firestore_v1beta1/collection.py
- firestore/tests/system.py
- firestore/tests/unit/test_collection.py
> Firestore: add 'Collection.list_documents' method.

- bigtable/google/cloud/bigtable/table.py
I changed some of the documentation of some methods like table.read_rows() because the parameter row_set in type is ok, but not in param. It was a little confuse to me.
> Update table.py docs

- bigquery/tests/system.py
We used to get BadRequest for querying with the wrong location. Now we
get NotFound. I update the test to just look for the base class of
GoogleAPICallError, since it seems we aren't guarnteed the actual status
code.
> Update error in system tests that expect error for wrong location

- firestore/google/cloud/firestore_v1beta1/collection.py
- firestore/google/cloud/firestore_v1beta1/query.py
- firestore/tests/system.py
- firestore/tests/unit/test_collection.py
- firestore/tests/unit/test_query.py
Leave `Query.get` as a deprecated alias for `Query.stream`.
Closes #6558.
> Firestore: rename 'Query.get' -> 'stream'.

- storage/google/cloud/storage/blob.py
- storage/google/cloud/storage/bucket.py
- storage/tests/system.py
- storage/tests/unit/test_blob.py
- storage/tests/unit/test_bucket.py
@frankyn Still working on system tests.  I can test creating a new bucket with BPO enabled, but am unable to update a newly-created non-BPO bucket to have BPO set:  the `PATCH` request returns:
```
google.api_core.exceptions.BadRequest: 400 PATCH https://www.googleapis.com/storage/v1/b/set-bpo-1546903462976?projection=full: Cannot disable object policies because default object acls are not empty
```
> Storage: add 'bucket_policy_only' IAM property

- spanner/google/cloud/spanner_v1/param_types.py
Workaround for @pjenvy's blockage on CLA:  this is clearly a trivial / non-copyrightable change.
Closes #7125.
> Spanner: fix typo in exported param type name.

- bigquery/google/cloud/bigquery/_helpers.py
- bigquery/tests/unit/test__helpers.py
> BigQuery:  allow nested records w/ nulls

- bigquery/google/cloud/bigquery/query.py
- bigquery/tests/unit/test_query.py
> BigQuery: harden 'ArrayQueryParameter.from_api_repr' against missing 'parameterValue'.

- third_party/sphinx/sphinx/ext/autosummary/templates/autosummary/class.rst
This fixes the issue where the base class for RowIterator could not be navigated to.
Fixes #7293
> Show inheritance and inherited members in BQ docs.

- spanner/docs/batch-usage.rst
Correctly specify  that a Batch object is constructed from a Database object, not a Client.
(these docs caused confusion leading to [a StackOverflow question](https://stackoverflow.com/questions/54683140/how-do-i-batch-upsert-data-into-google-cloud-spanner-using-the-python-client-lib)
> Fix Batch object creation instructions

- bigtable/google/cloud/bigtable/batcher.py
Fix lint
`is not` to `!=` as per flake8 F632 code
> bigtable: fix lint

- api_core/tests/unit/test_page_iterator.py
```
F632 use ==/!= to compare str, bytes, and int literals.
```
> api_core: fix new lint failure

- bigquery/google/cloud/bigquery/table.py
W293 blank line contains whitespace.
> BigQuery: fix lint.

- bigtable/google/cloud/bigtable/instance.py
- bigtable/google/cloud/bigtable/policy.py
- bigtable/tests/unit/test_instance.py
- bigtable/tests/unit/test_policy.py
> Bigtable: improve 'Policy' interchange w/ JSON, gRPC payloads.

- api_core/google/api_core/operation.py
- api_core/tests/unit/test_operation.py
This commit adds a `deserialize` method to the Operation object. The class method is a helper to deserialize the serialized protobuf operation messages.
We previously released this in `1.6.0a1` so I could make sure this was needed and the correct thing before committing to it. I am now requesting that we promote it. :-)
> Add `Operation.deserialize`.

- api_core/google/api_core/protobuf_helpers.py
- api_core/tests/unit/test_protobuf_helpers.py
This commit adds support for unwrapping wrapped pb2 objects  from Anys (needed for LRO support with wrapping).
> Add support to unwrap Anys into wrapped pb2 objects.

- bigtable/docs/snippets_table.py
- bigtable/google/cloud/bigtable/batcher.py
- bigtable/google/cloud/bigtable/instance.py
- bigtable/google/cloud/bigtable/table.py
- bigtable/tests/unit/test_table.py
In some cases, we need to set a greater timeout to wait for a request, right now it isn't a way to change this value.
setting the timeout in the `mutation batcher` we can set this time or set it in blank to take the default value.
```
def test_mutate_rows_timeout(self):
table = _Table(self.TABLE_NAME)
mutation_batcher = MutationsBatcher(table=table, timeout=600000)
row = DirectRow(row_key=b"row_key")
row.set_cell("cf1", b"c1", 1)
row.set_cell("cf1", b"c2", 2)
row.set_cell("cf1", b"c3", 3)
row.set_cell("cf1", b"c4", 4)
mutation_batcher.mutate(row)
mutation_batcher.flush()
self.assertEqual(table.mutation_calls, 1)
```
> Way to change the mutation timeout in bigtable.

- storage/tests/system.py
Also, try even harder to delete the shared bucket.
Closes #7478.
> Storage: un-flake KMS integration tests expecting empty bucket.

- storage/tests/system.py
> Storage: increase number of retries for 429 errors.

- bigquery/google/cloud/bigquery/dataset.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_dataset.py
- bigquery/tests/unit/test_table.py
This removes the another need to manually create a TableReference or
DatasetReference. Instead, a developer can pass in a string to the
constructor and then set the needed properties on the resource.
Closes #7477
> Accept a string in Table and Dataset constructors.

- spanner/CHANGELOG.md
- spanner/setup.py
> Release spanner 1.8.0

- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/unit/test_client.py
In create_dataset and create_table, exists_ok ignores errors when a
dataset/table already exists. It makes a GET request to get the existing
resource if it already exists.
In delete_dataset and delete_table, not_found_ok ignores errors when a
dataset/table doesn't exist.
Closes #7476.
> Add options to ignore errors when creating/deleting datasets/tables.

- README.rst
> Docs: fix link for 'getting-started-python' repo.

- dataproc/docs/README.rst
- dataproc/docs/conf.py
- dataproc/docs/index.rst
- dataproc/noxfile.py
Adds a nox session `docs` in dataproc which builds the dataproc documentation. This does not break the top-level docs build. This is in preparation for the new documentation site and repo split. 
I'd like to make similar changes in the other directories and wanted to get input on this first.
> Dataproc: Add nox session `docs`

- api_core/google/api_core/bidi.py
Adds a ready event to BackgroundConsumer to allow waiting for the background thread to start
> Adds a ready event to BackgroundConsumer to wait on start.

- .kokoro/release/common.cfg
These credentials will be used by the releasetool reporter.
> Fetch credentials for magic github proxy

- bigquery/google/cloud/bigquery/table.py
The `from_api_repr` method does not take a `Dataset` object.
> Remove typo in Table.from_api_repr docstring.

- storage/google/cloud/storage/_helpers.py
- storage/google/cloud/storage/blob.py
- storage/google/cloud/storage/bucket.py
- storage/tests/unit/test__helpers.py
- storage/tests/unit/test_blob.py
- storage/tests/unit/test_bucket.py
> Storage: ensure that 'Blob.reload' passes encryption headers.

- storage/google/cloud/storage/_helpers.py
- storage/google/cloud/storage/blob.py
- storage/google/cloud/storage/bucket.py
- storage/tests/system.py
- storage/tests/unit/test__helpers.py
- storage/tests/unit/test_blob.py
- storage/tests/unit/test_bucket.py
- Uses #7441 as a base.
- Merges in @jmcarp's work from #7023, with my requested changes from that PR.
- Closes #7023.
- Implements #5546, #5781, #2463, #2538.
> Storage: add generation arguments (from #7023).

- pubsub/google/cloud/pubsub_v1/gapic/publisher_client_config.py
- pubsub/google/cloud/pubsub_v1/gapic/subscriber_client_config.py
- pubsub/google/cloud/pubsub_v1/proto/pubsub.proto
- pubsub/google/cloud/pubsub_v1/proto/pubsub_pb2.py
- pubsub/google/cloud/pubsub_v1/proto/pubsub_pb2_grpc.py
- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/noxfile.py
- pubsub/synth.metadata
Add `ABORT` to the set of retryable stream errors, per updates to the googleapis GAPIC config.
Pick up proto linting / comment changes.
Closes #7399.
> Add 'authentication_method' to 'PushConfig' (via synth).

- bigquery/google/cloud/bigquery/dataset.py
The method and docstring for the table() method are identical for
Dataset, DatasetReference, and DatasetListItem. This commit moves the
implementation to a shared method to reduce code duplication.
> Refactor table() methods into shared implementation.

- spanner/tests/system/test_system.py
Unmatched tag are at line 780/781. 
It would be nice to know why this worked (so that I can be sure this fix is doing something meanful) or if I can just remove the start tags which are otherwise unused
> Add matching END tags

- bigtable/docs/snippets_table.py
found with grep -ri "def test" bigtable/docs/snippets_table.py | sort | uniq -c | sort -n
these tests are duplicated inside the file
`test_bigtable_column_family_name` was at line 415 and line 491
`test_bigtable_create_update_delete_column_family` was at line 438 and line 514
`test_bigtable_row_clear` was at line 1084 and line 1239
Part of #7522
> Remove duplicate tests

- talent/README.rst
The current [client library documentation link](https://googleapis.github.io/google-cloud-python/latest/jobs/usage.html) throws a 404 error. Changed to proper redirection [link](https://googleapis.github.io/google-cloud-python/latest/talent/index.html).
> google-cloud-python/talent - Broken talent client library documentation link

- bigquery/docs/snippets.py
- bigquery/google/cloud/bigquery/client.py
- bigquery/noxfile.py
- bigquery/setup.py
- bigquery/tests/unit/test_client.py
This fixes a bug where `load_table_from_dataframe` could not be used
with the `fastparquet` library. It should also use less memory when
uploading large dataframes.
Fixes #7543
> Use temporary file in load_table_from_dataframe

- bigtable/google/cloud/bigtable/instance.py
- bigtable/google/cloud/bigtable/table.py
- bigtable/tests/unit/test_instance.py
- bigtable/tests/unit/test_table.py
Fixes #7531 
* some cleanup
* add deprecation warnings for backwards compatible features that will go away
> Bigtable: cleanup unused variable and add deprecation warnings for to be removed features

- securitycenter/docs/snippets_list_assets.py
- securitycenter/noxfile.py
This pull requests starts adding snippets for Cloud Security Command Center (in particular the list_assets call).  I tried to follow the contributing guide but apologize if I missed something.
> Add Snippets for security center list_assets call

- bigquery/google/cloud/bigquery/client.py
- bigquery/google/cloud/bigquery/job.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_client.py
- bigquery/tests/unit/test_job.py
This removes a few more cases where it was required to create a
`TableReference` or `DatasetReference`.
* Allow a string for `destination` in `QueryJobConfig` .
* Allow a string for `default_dataset` in `QueryJobConfig` .
* Allow a list of strings for `sources` in `Client.copy_table`.
Closes https://github.com/googleapis/google-cloud-python/issues/7558
> Allow string for copy sources, query destination, and default dataset

- test_utils/scripts/update_docs.sh
The docs generation script was removing the whole "generated"
directory before. Now it only removes the rst files, which correspond
to the files created by autosummary.
> Restore redirect from magics module.

- bigquery_storage/google/cloud/bigquery_storage_v1beta1/proto/storage_pb2.py
- bigquery_storage/setup.py
- bigquery_storage/synth.metadata
- bigquery_storage/synth.py
Turns out that without the latest googleapis-common-protos all the
tests pass, but Sphinx docs builds still fail. Remove the hack I
added to exclude this dependency and bump the minimum version of
googleapis-common-protos instead.
Apologies, I think I broke the docs build with https://github.com/googleapis/google-cloud-python/pull/7550
> Add dependency for resource proto.

- .github/CODEOWNERS
There are more than one set of BigQuery APIs, add all BigQuery DPEs as code owners to all of them.
> Add rest of BigQuery DPEs to code owners via team

- spanner/docs/snapshot-api.rst
- spanner/docs/transaction-api.rst
Rather than showing the private, and hence non-generated `_SnapshotBase` class, just show the members inherited from it.
Closes #7607.
> Spanner: expand API ref for snapshot / transaction.

- bigquery/google/cloud/bigquery/job.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_job.py
Oops. Missed adding this in #7552.
> Actually use the progress_bar_type argument in QueryJob.to_dataframe()

- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/system.py
- bigquery/tests/unit/test_table.py
The tabledata.list API works for more kinds of tables, including small
anonymous query results tables. By falling back to this API, we enable
a developer to always specify a `bqstorage_client` even when they
aren't writing their query results to a destination table and don't
know how large their query results will be.
> Fallback to BQ API when there are problems reading from BQ Storage.

- api_core/setup.cfg
The next version of pytype will change the default name of the pytype
output directory from pytype_output to .pytype, and `pytype_output/` is
in google-cloud-python's .gitignore. The easiest way to avoid being
affected by this change is to specify a custom output dir.
> API Core: specify a pytype output directory in setup.cfg.

- firestore/CHANGELOG.md
- firestore/setup.py
> Release firestore 0.32.0

- bigquery/setup.py
This is required for the generated classes from the Models API.
Closes #7667
> Add dependency on protobuf.

- api_core/google/api_core/datetime_helpers.py
- api_core/tests/unit/test_datetime_helpers.py
`rfc3339` with nanoseconds wasn't prepending leading zeros so if an object had less than 100,000,000 nanoseconds, the nanoseconds string field would be incorrectly set.
> Prepend leading zeros

- bigquery_storage/google/cloud/bigquery_storage_v1beta1/gapic/transports/big_query_storage_grpc_transport.py
- bigquery_storage/synth.py
- currently limited to 4MiB
- compare to https://github.com/googleapis/google-cloud-python/pull/5594/commits/f636c8d7756a470719d114e8d77dd169e39906f3 which does the same for the monitoring API
> remove gRPC size limit for bigquery storage

- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_table.py
Don't hide errors such as insufficient permissions to create
a read session, or the API is not enabled. Both of those are
clearly problems if the developer has explicitly asked for
BigQuery Storage API support.
Closes #7661.
> Don't mask auth errors in `to_dataframe` with BQ Storage API

- bigquery_storage/tests/system/test_system.py
The semantics of split are changing. See internal CL 242136870.
> Remove system test for split rows

- bigquery/noxfile.py
- bigquery/setup.py
An [all] extra will be useful for convenience to get all the "bonus"
features like progress bars, pandas integration, and BigQuery Storage
API integration.
I also blacken the setup.py file and simplify the noxfile by using this
new [all] extra.
This is a pattern I've seen in other projects that have a lot of "extras", such as Apache Airflow (though they have a lot more the `google-cloud-bigquery`).
https://github.com/apache/airflow/blob/6cb735c6d301a5689ff9666349abdb6387abc7a1/setup.py#L335
> Add [all] extras to install all extra dependencies

- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_table.py
Closes #5117 
@tswast @engelke
> Adding creationTime and expirationTime properties to TableListItem

- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_table.py
> Adding `clustering_fields` property to TableListItem

- bigquery/google/cloud/bigquery/job.py
- bigquery/tests/unit/test_job.py
> Adding missing properties from LoadJobConfig to LoadJob library

- bigquery_storage/google/cloud/bigquery_storage_v1beta1/reader.py
- bigquery_storage/tests/unit/test_reader.py
This allows readers to read blocks (called pages for compatibility with
BigQuery client library) one at a time from a stream. This enables use
cases such as progress bar support and streaming workers that expect
pandas DataFrames.
Towards https://github.com/googleapis/google-cloud-python/issues/7654
> Add page iterator to ReadRowsStream

- scheduler/CHANGELOG.md
- scheduler/setup.py
> Release scheduler 0.3.0

- storage/google/cloud/storage/_signing.py
- storage/google/cloud/storage/blob.py
- storage/google/cloud/storage/bucket.py
- storage/tests/system.py
- storage/tests/unit/test__signing.py
- storage/tests/unit/test_blob.py
- storage/tests/unit/test_bucket.py
- storage/tests/unit/url_signer_v4_test_account.json
- storage/tests/unit/url_signer_v4_test_data.json
Partial support for the new feature:  adds a `version` argument to `Blob.generate_signed_url`, and uses it to switch between the two signing algorithms.
Remaining work:
Deferred work:
- Add system tests for V4 bucket signed URLs (in place, but currently skipped due to back-end case-flattening issue for the `X-Goog-Signed` header) (#7625).
- Add support for signing URLs on GCE following Frank's [Ruby PoC](https://gist.github.com/frankyn/1a537900c0689903f157740a0a9e36aa#file-v4_signed_urls-rb-L56-L68). (#7267)
- Add system tests for CSEK upload / download using V4 blob-signed URLs (blocked by a similar back-end bug as above). (#7626).
No longer in scope:
- ~Add `Client.generate_signed_url`, to permit listing buckets.~
> Storage: add support for V4 signed URLs

- bigtable/google/cloud/bigtable/instance.py
google.cloud.bigtable.enums.InstanceType does not exist; it's actually google.cloud.bigtable.enums.Instance.Type
> FIX documentation

- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_table.py
Move the BigQuery Storage API optional dependency imports to the top of
the module, following the existing pattern for other optional
dependencies.
> BigQuery: Raise ValueError when BQ Storage is required but missing

- bigquery/google/cloud/bigquery/table.py
- bigquery/setup.py
- bigquery/tests/unit/test_table.py
I noticed in manually testing `to_dataframe` that it would stop
the current cell when I hit Ctrl-C, but data kept on downloading in the
background. Trying to exit the Python shell, I'd notice that it would
hang until I pressed Ctrl-C a few more times.
Rather than get the DataFrame for each stream in one big chunk, loop
through each block and exit if the function needs to quit early. This
follows the pattern at https://stackoverflow.com/a/29237343/101923
This depends on:
* ~https://github.com/googleapis/google-cloud-python/pull/7680, new `.pages` feature in BQ Storage client~
* https://github.com/googleapis/google-cloud-python/pull/7726, aligns optional import for BQ Storage client with pattern used elsewhere in the client.
> BigQuery: ensure that `KeyboardInterrupt` during `to_dataframe`no longer hangs.

- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_table.py
Otherwise it stays blue (incomplete) in the `tqdm_notebook` version. Not sure that it makes a difference in plain `tqdm`.
> BigQuery: Close the to_dataframe progress bar when finished.

- datalabeling/docs/index.rst
The body of [the Datalabeling index.rst](https://googleapis.github.io/google-cloud-python/latest/datalabeling/index.html) describes BigQuery Data Transfer rather than DataLabeling.
> Datalabeling: Update index.rst

- firestore/google/cloud/firestore_v1/watch.py
- firestore/tests/unit/v1/test_cross_language.py
- firestore/tests/unit/v1/test_watch.py
Avoids hard-coding the root document, to enable queries on nested
collections.
Closes #7515.
Supersedes #7613.
> Use parent path for watch on queries.

- bigquery/google/cloud/bigquery/job.py
This explicitly documents the QueryJob.query property and also aligns it
with the other resource properties in the BigQuery client.
> Refactor QueryJob.query to read from resource dictionary

- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_table.py
When the BigQuery Storage API was used in `to_dataframe`, the `progress_bar_type` argument was ignored. This PR fixes that by creating a concurrent queue that worker threads can send progress updates to.
A fake queue is created for the case with no progress bar to prevent filling a queue but never reading from it.
This fix depends on:
* ~https://github.com/googleapis/google-cloud-python/pull/7680 adds `.pages` to BQ Storage. Must be merged and released.~ Released in `google-cloud-bigquery-storage` version 0.4.0!
* ~https://github.com/googleapis/google-cloud-python/pull/7698 adds loop over `.pages` to fix issue with `KeyboardInterrupt` (discovered while working on this progress bar feature).~
Closes #7654
> BigQuery: `to_dataframe` respects `progress_bar_type` when used with BQ Storage API

- .github/CODEOWNERS
> The `docs/*` pattern will match files like `docs/getting-started.md`
> but not further nested files like `docs/build-app/troubleshooting.md`.
See: https://help.github.com/en/articles/about-code-owners
P.S. I realize this whole file is probably out-of-date. I'm only making this mechanical change so that the right code reviewers get added on BigQuery updates.
> Remove `folder/*` pattern, since it only matches immediate child files

- pubsub/google/cloud/pubsub_v1/subscriber/scheduler.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_scheduler.py
This PR makes the `ThreadScheduler` to subclass the base `Scheduler` (and not `object`).
Carefully gaze at the `scheduler.ThreadScheduler` class definition for about 3.14 seconds and await _the_ Enlightenment. :wink: 
I see no apparent reason, why `ThreadScheduler` subclasses `object` directly, instead of the ABC defined in the very same file, as the interfaces of these two classes match.
> Pub/Sub ThreadScheduler should inherit from the base Scheduler ABC

- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/unit/test_client.py
Part of feature request: #3419
@tswast @engelke
> Phase 1 for storing schemas for later use.

- bigquery/tests/unit/test_client.py
This removes a lot of repeated code that wasn't relevant to the actual tests.
> Cleanup client tests with method to create minimal table resource

- api_core/google/api_core/gapic_v1/client_info.py
- api_core/setup.cfg
- api_core/tests/unit/gapic/test_client_info.py
This provides a way for partners to define a prefix identifying their
tool or application, as required by many cloud partnership agreements.
> Add `user_agent` property to `ClientInfo`

- api_core/CHANGELOG.md
- api_core/setup.py
> Release api_core 1.10.0

- tasks/docs/index.rst
- tasks/tests/system/gapic/v2/test_system_tasks_v2.py
In preparation for Tasks v2 GA.
> Tasks: Add smoke test and correct docs/index.rst.

- bigquery/google/cloud/bigquery/_http.py
- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/unit/test__http.py
- bigquery/tests/unit/test_client.py
This aligns BigQuery's behavior regarding the User-Agent and
X-Goog-Api-Client headers with that of the GAPIC-based clients.
Old:
X-Goog-API-Client: gl-python/3.7.2 gccl/1.11.2
User-Agent: gcloud-python/0.29.1
New:
X-Goog-API-Client: optional-application-id/1.2.3 gl-python/3.7.2 grpc/1.20.0 gax/1.9.0 gapic/1.11.2 gccl/1.11.2
User-Agent: optional-application-id/1.2.3 gl-python/3.7.2 grpc/1.20.0 gax/1.9.0 gapic/1.11.2 gccl/1.11.2
In order to set the `optional-application-id/1.2.3`, the latest version
of `api_core` is required, but since that's an uncommon usecase and it
doesn't break, just ignore the custom User-Agent if an older version is
used, I didn't update the minimum version `setup.py`.
This PR depends on:
- https://github.com/googleapis/google-cloud-python/pull/7799 for unit test …
> Add `client_info` to BigQuery constructor for user-amenable user agent headers

- bigtable/docs/snippets.py
Fix issue
https://github.com/googleapis/google-cloud-python/issues/7003
> Bigtable: fix instance leaks from snippets

- bigquery/google/cloud/bigquery/job.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_job.py
This fixes an issue where due to reading from multiple stream in
parallel, the order of rows is not preserved. Normally this isn't an
issue, but it is when the rows are query results from an `ORDER BY` query.
Note: The detection of `ORDER BY` is not perfect. It will have false positives (such as `ORDER BY` in a string or sub-query), but hopefully no false negatives. Since a false positive only means we read from a single stream, behavior is correct but perhaps slower than expected.
Closes #7759
> Preserve order in `to_dataframe` with BQ Storage from queries containing `ORDER BY`

- firestore/google/cloud/firestore_v1/client.py
- firestore/google/cloud/firestore_v1/query.py
- firestore/tests/system.py
- firestore/tests/unit/v1/test_client.py
- firestore/tests/unit/v1/test_query.py
- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/tests/system.py
CollectionGroup queries add support for queries to Firestore that query documents by collection ID rather than by collection path. 
Java: googleapis/google-cloud-java#4652
Node: googleapis/nodejs-firestore#578
> Firestore: add support for CollectionGroup queries.

- storage/google/cloud/storage/bucket.py
- storage/google/cloud/storage/client.py
- storage/tests/unit/test_client.py
Part of issue: #7762
@tswast 
@engelke
> Phase 1 Update create_bucket to take Bucket object within Storage Client

- phishingprotection/CHANGELOG.md
- phishingprotection/README.rst
- phishingprotection/setup.py
> Release phishingprotection 0.1.0

- bigtable/docs/snippets.py
- bigtable/docs/snippets_table.py
> Bigtable: fix rendering of instance admin snippets.

- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/tests/system.py
Cleanup bebugging code from #7758.  
This closes #7841.
> Clean up bebugging code

- monitoring/tests/system/test_vpcsc.py
This new file is added in order to test client lib compatibility of VPC SC. The tests are auto-generated from the service definition of the monitoring API. The tests can be run inside or outside of VPC service perimeter. The input to the script should be the following environment variables. 
1. PROJECT_ID: a project that is inside the VPC perimeter. 
2. GOOGLE_CLOUD_TESTS_VPCSC_OUTSIDE_PERIMETER_PROJECT: a project that is outside the VPC perimeter.
> Monitoring: add VPCSC system test.

- monitoring/tests/system/test_vpcsc.py
Hi, this is a refresh of the auto-generated VPC tests. I've tested it locally and it is working as intended. This pull request is sent on behalf of @michaelsafyan.
> Monitoring: regenerate VPCSC tests to include NotificationChannelService and UptimeCheckService.

- storage/google/cloud/storage/client.py
- storage/tests/unit/test_client.py
Part of issue: #7762
@tswast
@engelke
> Phase 1 Update get_bucket to take Bucket object within Storage Client

- api_core/google/api_core/client_info.py
- api_core/tests/unit/gapic/test_client_info.py
- api_core/tests/unit/test_client_info.py
- bigquery/google/cloud/bigquery/_http.py
- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/unit/test__http.py
- bigquery/tests/unit/test_client.py
- core/google/cloud/_http.py
- core/tests/unit/test__http.py
- docs/core/client_info.rst
- docs/core/index.rst
Hoist `client_info` support from `google.cloud.bigquery._http.Connection` into core's `google.cloud._http.Connection`.
Toward #7825.
> Core, BigQuery: refactor 'client_info' support.

- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Closes #7709.
If a gRPC channel is in `TRANSIENT_FAILURE` state for too long, the retry timeout configured in [subscriber client config](https://github.com/googleapis/google-cloud-python/blob/master/pubsub/google/cloud/pubsub_v1/gapic/subscriber_client_config.py#L9) kicks in, and a `RetryError` is raised in a background thread, but the client keeps running, and the error is not propagated to the top level code.
This PR makes sure that the following happens:
- The streaming pull manager shutdown is triggered, shutting down all background threads.
- The reason for the shutdown (RetryError) is propagated to the main thread that awaits `future.result()`, allowing the user code a chance to catch the error and react to it.
I was not able to reproduce the actual error users reported in a real …
> PubSub: Fix pubsub Streaming Pull shutdown on RetryError

- storage/google/cloud/storage/_http.py
- storage/google/cloud/storage/client.py
- storage/tests/unit/test__http.py
- storage/tests/unit/test_client.py
> Storage: add client_info support to client / connection.

- logging/google/cloud/logging/_http.py
- logging/google/cloud/logging/client.py
- logging/tests/unit/test__http.py
- logging/tests/unit/test_client.py
> Logging: add client_info support to client / connection.

- bigtable/google/cloud/bigtable/client.py
- bigtable/tests/unit/test_client.py
Forward when constructing GAPIC API client objects.
Toward #7825.
> Bigtable: add 'client_info' support to client.

- firestore/google/cloud/firestore_v1/client.py
- firestore/tests/unit/v1/test_client.py
Forward when constructing GAPIC API client object.
Toward #7825.
> Firestore: add client_info support to V1 client.

- spanner/google/cloud/spanner_v1/client.py
- spanner/google/cloud/spanner_v1/database.py
- spanner/tests/unit/test_client.py
- spanner/tests/unit/test_database.py
Forward through when creating GAPIC API wrappers.
Toward #7825.
> Spanner: add client_info support to client.

- bigtable/google/cloud/bigtable/client.py
- firestore/google/cloud/firestore_v1/client.py
@tswast Addressing your comments which  I missed seeing before merging #7876 / #7877.
> Bigtable, Firestore: fix client_info type in GAPIC-based client docstrings.

- logging/google/cloud/logging/_gapic.py
- logging/google/cloud/logging/client.py
- logging/tests/unit/test__gapic.py
- logging/tests/unit/test_client.py
> Logging: plumb 'Client._client_info' through to GAPIC API wrapper.

- trace/google/cloud/trace/_gapic.py
- trace/google/cloud/trace/client.py
- trace/google/cloud/trace/v1/_gapic.py
- trace/google/cloud/trace/v1/client.py
- trace/tests/unit/v1/test__gapic_v1.py
- trace/tests/unit/v1/test_client_v1.py
- trace/tests/unit/v2/test__gapic_v2.py
- trace/tests/unit/v2/test_client_v2.py
> Trace: add client_info support to clients.

- error_reporting/google/cloud/error_reporting/_gapic.py
- error_reporting/google/cloud/error_reporting/_logging.py
- error_reporting/google/cloud/error_reporting/client.py
- error_reporting/tests/unit/test__gapic.py
- error_reporting/tests/unit/test__logging.py
- error_reporting/tests/unit/test_client.py
> Error reporting: add 'client_info' support to Client.

- bigquery/google/cloud/bigquery/table.py
- bigquery/noxfile.py
- bigquery/tests/unit/test_table.py
As reported in internal bug 131167013, calling `table.time_partitioning`
can sometimes fail with `KeyError: 'type'` when attempting to read this
property on a non-partitioned table.
> Prevent error when time partitioning is populated with empty dict

- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_table.py
When loading large datasets from BIgQuery as pandas DataFrames, sometimes the index contains duplicates. This happens when the results are collected as multiple DataFrames and then concatenated without resetting the index.
As an example, we get `0, 1` repeated in the index:
```python
In [1]: import pandas as pd
In [2]: x = pd.DataFrame({"a": [1, 2]})
...: pd.concat([x, x])
Out[2]:
a
0  1
1  2
0  1
1  2
```
which has some unintended consequences when we try to subset:
```python
In [3]: pd.concat([x, x]).loc[0]
Out[3]:
a
0  1
0  1
```
Instead, by setting `ignore_index=True` we get:
```python
In [4]: pd.concat([x, x], ignore_index=True)
Out[4]:
a
0  1
1  2
2  1
3  2
```
From the pandas documentation https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html:
> …
> BigQuery: Fixed pandas DataFrames being returned with incorrect index.

- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/google/cloud/pubsub_v1/subscriber/client.py
- pubsub/tests/system.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_subscriber_client.py
Closes #7917.
This PR implements a user request to propagate exceptions from streaming pull callbacks to the main thread awaiting the result of the future returned by the `subscriber.subscribe()` call.
- Prerequsite: Have a working service account, pubsub topic, and subscription created.
- Publish a message to the topic.
- Run the sample subscriber code posted under the [issue](https://github.com/googleapis/google-cloud-python/issues/7917) (adjust subscription name as necessary).
- Nothing happens in the main thread. The exception is raised in the callback, but the main thread keeps waiting for for `fut.result()`.
- An exception from the callback is propagated to `fut.result()`, and the main …
> PubSub: Propagate subscribe callback errors to main thread

- bigquery/CHANGELOG.md
- bigquery/setup.py
See https://github.com/googleapis/google-cloud-python/issues/7968, "Prep Releases".
> BigQuery: Widen range for 'google-cloud-core'.

- bigtable/CHANGELOG.md
- bigtable/setup.py
> Bigtable: Widen range for 'google-cloud-core'.

- datastore/CHANGELOG.md
- datastore/setup.py
> Datastore: Widen range for 'google-cloud-core'.

- runtimeconfig/CHANGELOG.md
- runtimeconfig/setup.py
> Runtimeconfig: Widen range for 'google-cloud-core'.

- trace/CHANGELOG.md
- trace/setup.py
> Trace: Widen range for 'google-cloud-core'.

- storage/google/cloud/storage/client.py
- storage/tests/unit/test_client.py
Part of issue: #7762
@tswast
@engelke
> Phase 1 Added new method download_blob_to_file within Storage Client

- core/setup.py
Toward #7968.
Needed for new 'client_info' support.
> Core: update dep on 'api_core' >= 1.11.0.

- tasks/CHANGELOG.md
- tasks/setup.py
> Release tasks 1.1.0

- translate/tests/system.py
Fixes #7892.
`hvala ti` (Croatian) and `dankon` (Esperanto) mean `thank you`. This word seems to be susceptible to changing translations. I've changed them to `petnaest` and `dek kvin` which mean `fifteen`.
> Translation: Change system test.

- websecurityscanner/CHANGELOG.md
- websecurityscanner/setup.py
> Release websecurityscanner 0.2.0

- trace/noxfile.py
- trace/synth.py
- trace/tests/system/gapic/v1/test_system_trace_service_v1_vpcsc.py
- trace/tests/system/gapic/v2/test_system_trace_service_v2_vpcsc.py
This new file is added in order to test client lib compatibility of VPC SC. The tests can be run inside or outside of VPC service perimeter. The input to the script should be the following environment variables.
PROJECT_ID: a project that is inside the VPC perimeter.
GOOGLE_CLOUD_TESTS_VPCSC_OUTSIDE_PERIMETER_PROJECT: a project that is outside the VPC perimeter.
> Trace: add VPCSC system test.

- bigtable/CHANGELOG.md
- bigtable/setup.py
> Release bigtable 0.33.0

- error_reporting/setup.py
> Error Reporting: pin 'google-cloud-logging >= 1.11.0'.

- resource_manager/CHANGELOG.md
- resource_manager/setup.py
> Release resource_manager 0.29.0

- trace/CHANGELOG.md
- trace/setup.py
> Release trace 0.21.0

- datastore/google/cloud/datastore/_gapic.py
- datastore/google/cloud/datastore/_http.py
- datastore/google/cloud/datastore/client.py
- datastore/tests/unit/test__gapic.py
- datastore/tests/unit/test__http.py
- datastore/tests/unit/test_client.py
> Datastore: Add `client_info` support to client.

- error_reporting/CHANGELOG.md
- error_reporting/setup.py
> Release error_reporting 0.31.0

- automl/docs/conf.py
- bigquery/docs/conf.py
- bigquery_storage/docs/conf.py
- bigtable/docs/conf.py
- container/docs/conf.py
- logging/docs/conf.py
- redis/docs/conf.py
- securitycenter/docs/conf.py
'sphinx_rtd_theme' is no longer installed by default.
See this [failed docs build](https://source.cloud.google.com/results/invocations/2c812072-8095-4de2-aec5-b0b1f874dfc5/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-python%2Fpresubmit%2Fautoml/log).
> Docs: use alabaster theme everwhere.

- firestore/noxfile.py
- firestore/synth.metadata
- firestore/synth.py
Firestore's system tests use a [different environment variable](https://github.com/googleapis/google-cloud-python/blob/a65ed778770e045c0b26bb98d64cd0beec25703e/firestore/tests/system.py#L37) (because firestore vs. datastore hysterical raisins).
> Firestore: use correct environment variable to guard the 'system' part.

- storage/google/cloud/storage/bucket.py
Closes #7875.
Supersedes #7897.
> Storage: improve docs for 'fields' argument to 'Bucket.list_blobs'.

- bigquery_storage/google/cloud/bigquery_storage_v1beta1/reader.py
- bigquery_storage/tests/unit/test_reader.py
DEADLINE_EXCEEDED should not be resumed. Currently, you can set a
timeout on reads, but the reader will reconnect after the timeout value
finishes.
Always resuming the stream masked internal issue 132959978 from clients,
where the default deadline is much too low for read streams.
Wait for the deadline configuration fix for read rows to go in before
merging.
> Respect timeout on `client.read_rows`. Don't resume on `DEADLINE_EXCEEDED` errors.

- storage/google/cloud/storage/bucket.py
Follow-on to #8023.
I plan to merge this one-word, docstring-only change as soon as CI is green.
> Storage: tweak 'fields' docstring further.

- storage/google/cloud/storage/hmac_key.py
- storage/tests/unit/test_hmac_key.py
@jkwlui Note that this PR targets the `storage-add-hmac-key-support-feature` branch, which will be merged to `master` once all the steps in #7851 are completed.
Toward #7851.
> Storage: add 'google.cloud.storage.hmac_keys.HMACKeyMetadata' resource class.

- bigquery/google/cloud/bigquery/model.py
- bigquery/tests/unit/model/test_model.py
- bigquery/tests/unit/model/test_model_reference.py
As new fields are added, the JSON -> Protobuf conversion should not
fail. Instead, it should ignore unknown fields. So that this data is not
discarded, use _properties as is the convention in our REST libraries.
It's private, but can be used as a workaround to get access to fields
that haven't yet been added to the client library.
Closes #8082.
> BigQuery: avoid errors from unknown fields in Models API.

- pubsub/docs/subscriber/index.rst
> Pub/Sub: drop mention of long-removed 'policy' object from docs.

- firestore/google/cloud/firestore_v1/_helpers.py
- firestore/google/cloud/firestore_v1/batch.py
- firestore/google/cloud/firestore_v1/client.py
- firestore/google/cloud/firestore_v1/collection.py
- firestore/google/cloud/firestore_v1/document.py
- firestore/google/cloud/firestore_v1/field_path.py
- firestore/google/cloud/firestore_v1/gapic/firestore_client.py
- firestore/google/cloud/firestore_v1/gapic/transports/firestore_grpc_transport.py
- firestore/google/cloud/firestore_v1/query.py
- firestore/google/cloud/firestore_v1/transaction.py
- firestore/google/cloud/firestore_v1beta1/_helpers.py
- firestore/google/cloud/firestore_v1beta1/batch.py
- firestore/google/cloud/firestore_v1beta1/client.py
- firestore/google/cloud/firestore_v1beta1/collection.py
- firestore/google/cloud/firestore_v1beta1/document.py
- firestore/google/cloud/firestore_v1beta1/field_path.py
- firestore/google/cloud/firestore_v1beta1/gapic/firestore_client.py
- firestore/google/cloud/firestore_v1beta1/gapic/transports/firestore_grpc_transport.py
- firestore/google/cloud/firestore_v1beta1/query.py
- firestore/google/cloud/firestore_v1beta1/transaction.py
Generated via:
```bash
$ for f in $(git grep -l "~\." firestore/); do sed -i -e "s/~\./google.cloud./" $f; done
```
Closes #8035.
> Firestore: expand tildes in class refs FBO static analysis / autocomplete.

- pubsub/google/cloud/pubsub_v1/_gapic.py
- pubsub/tests/unit/pubsub_v1/test__gapic.py
The GAPIC wrapper (code snippet below with comments) in [`pubsub/google/cloud/pubsub_v1/_gapic`](https://github.com/googleapis/google-cloud-python/blob/master/pubsub/google/cloud/pubsub_v1/_gapic.py) falsely recognizes static methods as instance methods. 
```python
def wrap(wrapped_fx):
"""Wrap a GAPIC method; preserve its name and docstring."""
#
instance_method = True
self = getattr(wrapped_fx, "__self__", None) # <-- this would return None for staticmethod
if issubclass(type(self), type):             # <-- this would return False for staticmethod
instance_method = False                  # <-- resulting in instance_method = True for staticmethod
if instance_method:
fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
return functools.wraps(wrapped_fx)(fx)
fx = lambda *a, …
```
> Pub/Sub: staticmethod check

- storage/tests/system.py
> Storage: add more retries for 429s during teardown operations.

- firestore/docs/batch.rst
- firestore/docs/client.rst
- firestore/docs/collection.rst
- firestore/docs/document.rst
- firestore/docs/field_path.rst
- firestore/docs/query.rst
- firestore/docs/transaction.rst
- firestore/docs/transforms.rst
- firestore/docs/types.rst
- firestore/google/cloud/firestore_v1/_helpers.py
- firestore/google/cloud/firestore_v1/batch.py
- firestore/google/cloud/firestore_v1/client.py
- firestore/google/cloud/firestore_v1/collection.py
- firestore/google/cloud/firestore_v1/document.py
- firestore/google/cloud/firestore_v1/field_path.py
- firestore/google/cloud/firestore_v1/query.py
- firestore/google/cloud/firestore_v1/transaction.py
- firestore/google/cloud/firestore_v1beta1/_helpers.py
- firestore/google/cloud/firestore_v1beta1/batch.py
- firestore/google/cloud/firestore_v1beta1/client.py
- firestore/google/cloud/firestore_v1beta1/collection.py
- firestore/google/cloud/firestore_v1beta1/document.py
- firestore/google/cloud/firestore_v1beta1/field_path.py
- firestore/google/cloud/firestore_v1beta1/query.py
- firestore/google/cloud/firestore_v1beta1/transaction.py
Expand tildes in docstring refs.
FBO Sphinx (missing ref links), static analysis, autocompletion.
Closes #8035.
> Firestore: normalize docstring class refs.

- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/leaser.py
- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/google/cloud/pubsub_v1/subscriber/message.py
- pubsub/tests/system.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_message.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Closes #7677.
This PR fixes how subscriber client handles the [FlowControl.max_messages](https://github.com/googleapis/google-cloud-python/blob/master/pubsub/google/cloud/pubsub_v1/types.py#L56) setting. It makes sure that subscriber only delivers (i.e. invokes callbacks) `max_messages` at a time, and resumes invoking callbacks only when the user code acknowledges some of the previously delivered messages.
- Prerequsite: Have a working service account, pubsub topic, and subscription created.
- Publish 50 - 100 messages to that topic in batches of random size - [example script](https://github.com/plamut/google-cloud-python/blob/iss-7677-debug-app/pubsub/reproduce_pub.py).
- Run a test subscriber script ([example](https://github.com/plamut/google-cloud-python/blob/iss …
> PubSub: Fix streaming pull incorrectly handling FlowControl max_messages setting

- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Closes #6130.
This PR fixes errors in background threads that might happen on user-initiated streaming pull shutdown, i.e. cancelling the future returned by the `subscriber.subscribe()` call.
- Follow the steps in the [issue description](https://github.com/googleapis/google-cloud-python/issues/6130#issue-364719645).
- Preferably set the log level of the test script to `logging.DEBUG`. FWIW, I used the following config during development:
```py
import logging
log_format = (
"%(levelname)-8s [%(asctime)s] %(threadName)-33s "
"[%(name)s] [%(filename)s:%(lineno)d][%(funcName)s] %(message)s"
)
logging.basicConfig(level=logging.DEBUG, format=log_format)
```
An error can be observed in `Thread-CallbackRequestDispatcher` (the one listed …
> PubSub: Prevent unhandled background error on SPM shutdown

- api_core/google/api_core/retry.py
- api_core/setup.py
- api_core/tests/unit/test_retry.py
- core/setup.py
> Core: Classify 503 Service Unavailable errors as transient.

- storage/google/cloud/storage/client.py
- storage/tests/unit/test_client.py
Incorporates commits from #8042.
Toward #7851.
> Storage: add 'Client.list_hmac_keys' method.

- bigquery/google/cloud/bigquery/_pandas_helpers.py
- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/system.py
- bigquery/tests/unit/test__pandas_helpers.py
- bigquery/tests/unit/test_client.py
Use the BigQuery schema to inform encoding of file used in load job.
This fixes an issue where a dataframe with ambiguous types (such as an
`object` column containing all `None` values) could not be appended to
an existing table, since the schemas wouldn't match in most cases.
Closes #7370.
> Use `job_config.schema` for data type conversion if specified in `load_table_from_dataframe`.

- bigquery/google/cloud/bigquery/magics.py
- bigquery/tests/unit/helpers.py
- bigquery/tests/unit/test__helpers.py
- bigquery/tests/unit/test_client.py
- bigquery/tests/unit/test_magics.py
As recommended by: https://github.com/googleapis/google-cloud-python/issues/8024#issuecomment-493593234.
> Adds _connection object to bigquery magics context.

- storage/google/cloud/storage/client.py
The file object name is incorrect in the method documentation.
> Documentation fix in download_blob_to_file

- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/unit/test_client.py
Breaking change (require pyarrow) was introduced in #8105.
Follow-up to issue #7370.
> Fix breaking change. Don't require pyarrow if schema is set, but warn.

- bigquery/CHANGELOG.md
- bigquery/setup.py
> Release bigquery 1.13.0

- dataproc/setup.py
Not sure why releasetool missed this, but I didn't notice the version hadn't been updated until the release build failed. 
Follow up to #8195
> Dataproc: Update version number to 0.4.0

- bigquery/google/cloud/bigquery/magics.py
- bigquery/tests/unit/test_magics.py
> BigQuery: Fix Add maximum_bytes_billed option to magics

- datastore/google/cloud/datastore/client.py
- datastore/tests/unit/test_client.py
> Datastore:  expose 'reserveIds' API.

- bigquery/setup.py
- dns/setup.py
- resource_manager/setup.py
- runtimeconfig/setup.py
- storage/setup.py
Apparently, at least some versions of pip treat the more relaxed version of the `google-api-core` pin in these packages as license to ignore the transitive, stricter pin in `google-cloud-core 1.0.0`.
Closes #8085.
> Omnibus: don't pin 'google-api-core' in libs using 'google-cloud-core'.

- pubsub/google/cloud/pubsub_v1/futures.py
- pubsub/google/cloud/pubsub_v1/publisher/futures.py
- pubsub/google/cloud/pubsub_v1/subscriber/futures.py
- pubsub/tests/unit/pubsub_v1/publisher/test_futures_publisher.py
This closes #7816. 
This PR aims to fix the docstrings for certain methods on `pubsub_v1.publisher.futures.Future` and `pubsub_v1.subscriber.futures.StreamingPullFuture`. There are cases where the methods would share the same docstrings, but that's not always true. For example, calling `result()` on a publish future should return a message ID, but calling it on a StreamingPullFuture doesn't return a value, it simply keeps the RPC channel open for receiving messages.
> Pubsub: Separate subscriber and publish future documentation.

- bigquery/google/cloud/bigquery/job.py
- bigquery/tests/system.py
- bigquery/tests/unit/test_job.py
Makes the user control page size for a bigquery job.
> Bigquery: Add `page_size` parameter to `QueryJob.result`.

- CONTRIBUTING.rst
Update commands from python 3.6 to python 3.7 since system tests can only be run in python 3.7. Still possible to run unit tests in 3.6, but updating that command to 3.7 as well to be consistent.
> Update commands from python 3.6 to python 3.7

- core/google/cloud/client.py
- core/tests/unit/test_client.py
The auth library defaults to timeout of None, effectively having no timeout. This adds a default timeout of 5 minutes for all users of the core._http implementation
b/132819217
> Prevent requests from hanging on SSL handshake issue by adding a max t.o.

- pubsub/google/cloud/pubsub_v1/gapic/publisher_client.py
- pubsub/noxfile.py
- pubsub/synth.metadata
- pubsub/synth.py
This closes #6641. 
This PR updates the GAPIC publisher client using `synth.py`.
> Pub/Sub: Expose publish retry settings

- pubsub/docs/publisher/api/futures.rst
- pubsub/docs/publisher/index.rst
- pubsub/google/cloud/pubsub_v1/publisher/futures.py
This makes sure that the Publish Future documentation shows up [here](https://googleapis.github.io/google-cloud-python/latest/pubsub/index.html#api-documentation), and users can navigate to its own page.
> Pub/Sub: surface publish future in documentation

- logging/google/cloud/logging/handlers/transports/background_thread.py
There's no easy way to inject your own Worker thread that I can see, but I don't know why you wouldn't want to know the original time of the log entry.
Closes #8222
> Logging: Set the 'timestamp' on log records created by handler.

- bigquery_storage/google/cloud/bigquery_storage_v1beta1/reader.py
This will enable us to use alternative libraries and wire formats.
Previously, ReadRowsPage was closely coupled to the fastavro library.
Towards #7805 since we'll want an alternative parser and/or wire format in the future to improve performance.
> Refactor reader.ReadRowsPage to use _StreamParser.

- bigquery/google/cloud/bigquery/_pandas_helpers.py
- bigquery/tests/system.py
- bigquery/tests/unit/test__pandas_helpers.py
If a BigQuery schema is supplied as part of the `job_config`, it can be
used to set the `nullable` bit correctly on the serialized parquet file.
Closes #8093.
> BigQuery: Fix bug where `load_table_from_dataframe` could not append to REQUIRED fields.

- error_reporting/docs/usage.rst
Fixing mistake in documentation regarding issue: https://github.com/googleapis/google-cloud-python/issues/8270. 
Changed code examples on chapter:[Reporting an error without an exception]( https://googleapis.github.io/google-cloud-python/latest/error-reporting/usage.html#reporting-an-error-without-an-exception) to call `report()` method of the instance of Client-class, instead of method within error_reporting module.
> Error reporting: fixed mistake in documentation

- vision/tests/system.py
Verifies accessing a gcs bucket via Vision API outside of a secure perimeter is blocked.
> Vision: Add negative Vision API system tests for accessing GCS

- container/google/cloud/container_v1/__init__.py
- container/google/cloud/container_v1/gapic/cluster_manager_client.py
- container/google/cloud/container_v1/gapic/enums.py
- container/google/cloud/container_v1/gapic/transports/cluster_manager_grpc_transport.py
- container/google/cloud/container_v1/types.py
- container/noxfile.py
- container/synth.metadata
- container/synth.py
- container/tests/unit/gapic/v1/test_cluster_manager_client_v1.py
> Container: Blacken (via synth).

- pubsub/README.rst
These are the only two remaining links to readthedocs (deprecated).
> Replace readthedocs links to github docs

- pubsub/google/cloud/pubsub_v1/publisher/_batch/thread.py
- pubsub/tests/unit/pubsub_v1/publisher/batch/test_thread.py
Closes #8036.
Supersedes #7686 (the fix here is essentially the same, but also adds tests and a few minor things).
This PR makes sure that calls to `publisher.publish()` are not unnecessarily blocked while the underlying API publish call is in progress - the latter can take a substantial amount of time, especially on network errors when retries kick in.
The fix makes sure that the lock in the `_commit()` method is held for no longer than necessary. The details on why releasing the lock earlier is fine are listed in the [comment](https://github.com/googleapis/google-cloud-python/pull/7686#discussion_r284314182) on the original PR.
- Set the total publish timeout [setting](https://github.com/googleapis/google-cloud-python/blob/master/pubsub/google/cloud/pubsub_v1/gapi …
> PubSub: Release the state lock before calling the publish api

- speech/google/cloud/speech_v1/gapic/transports/speech_grpc_transport.py
- speech/synth.metadata
- speech/synth.py
Closes #5819
This PR increases the default max received message size for speech messages to 256 MiB.
Hardcoded, indeed, but that setting was already not directly available to end users (a full `SpeechGrpcTransport` needs to be passed instead). This PR does not address this aspect.
- Install the [synthtool](https://github.com/googleapis/synthtool),
- Revert the changes in `transports/speech_grpc_transport.py`,
- Got to the `speech` library directory and run the synthtool.
- The generated code changes in `transports/speech_grpc_transport.py` are the same as those submitted with this PR.
- The problem described in the [issue description](https://github.com/googleapis/google-cloud-python/issues/5819#issue-351776995) is also resolved, because the old 4 MiB max message size …
> Speech: Increase speech max received msg size to 256 MiB

- pubsub/google/cloud/pubsub_v1/types.py
- pubsub/synth.metadata
- pubsub/synth.py
Closes #7043.
This PR makes sure that FlowControl settings are properly documented in the generated documentation.
**Steps to perform:**
(from inside the `pubsub/` directory)
- Install the [synthtool](https://github.com/googleapis/synthtool) and run it,
- Generate the pubsub docs locally:
```
$ nox -f noxfile.py -s docs
```
- Open the generated docs for `FlowControl`:
```
$ chromium-browser "file://$GOOG_CLOUD_PYTHON_DIR/pubsub/docs/_build/html/types.html#google.cloud.pubsub_v1.types.FlowControl"
```
`FlowControl` settings have nice descriptions (as opposed to the [current docs](https://googleapis.github.io/google-cloud-python/latest/pubsub/types.html?highlight=flowcontrol#google.cloud.pubsub_v1.types.FlowControl)).
> PubSub: Document FlowControl settings

- api_core/google/api_core/bidi.py
- api_core/tests/unit/test_bidi.py
- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Closes #7910.
This PR fixes the issue with `ResumableBidiRpc` that can enter a busy re-open loop consuming lots of CPU in the process . The [comment](https://github.com/googleapis/google-cloud-python/issues/7910#issuecomment-494987224) on the issue explains this in more detail.
- (optional) Configure more verbose logging in the subscriber script:
```py
import logging 
log_format = (
"%(levelname)-8s [%(asctime)s] %(threadName)-33s "
"[%(name)s] [%(filename)s:%(lineno)d][%(funcName)s] %(message)s"
)
logging.basicConfig(
level=logging.DEBUG,
format=log_format,
)
```
- Disable your internet connection
- Start the streaming pull using a susbscriber client instance:
```py
subscriber.subscribe(SUBSCRIPTION_PATH, callback=my_callback)
while True:
try:
time.sleep(60) …
```
> Core: Mitigate busy reopen loop in ResumableBidiRpc consuming 100% CPU

- bigquery/docs/snippets.py
Remove location as it is now autodetected.
See bug b/116968956 .
> BigQuery Snippets: Use autodetected location

- bigtable/tests/system.py
> Bigtable: Increase timeout for app profile update operation.

- storage/google/cloud/storage/blob.py
> Storage: Add generation to 'Blob.__repr__'.

- texttospeech/docs/api.rst
Supersedes #7645.
Fixes #7629.
> Text-to-Speech: Repair top-level API reference page.

- firestore/google/cloud/firestore_v1/client.py
> Firestore: Fix docstring example for 'Client.collection_group'.

- storage/google/cloud/storage/blob.py
- storage/tests/unit/test_blob.py
> Storage: Avoid escaping tilde in blob public / signed URLs.

- bigtable/docs/snippets.py
- bigtable/tests/system.py
@busunkim96, @sduskis I think this would be easier to review commit-by-commit.
Closes #8378.
Closes #7003.
> Bigtable: plug systest / snippet instance leaks.

- bigtable/docs/snippets.py
- bigtable/tests/system.py
> Bigtable: Force timeout for table creation to 90 seconds (in systests).

- bigtable/google/cloud/bigtable/row_data.py
- bigtable/tests/unit/test_row_data.py
- spanner/README.rst
Fixes #7760.
Introducing a "stop" flag into the iterable PartialRowsData() class. Setting this flag to True results in cancelling of the iteration the next time the iterator is called.
> Bigtable: Add 'PartialRowsData.cancel'.

- pubsub/tests/system.py
Closes #4031.
The title says it all - this PR adds the missing system tests mentioned in the issue description:
- Listing topics and subscriptions in the client's project.
- Creating subscriptions with non-default settings.
- Listing subscriptions bound to a topic.
- Setting / getting IAM policy for topics and subscriptions
- ~~Creating / seeking snapshots.~~ :arrow_left: Removed, because the server only guarantees eventual re-delivery, and a test cannot wait for a fixed amount of time, causes flakiness.
> PubSub: Add system tests for PubSub clients

- pubsub/README.rst
- pubsub/docs/subscriber/index.rst
Closes #7128.
This PR documents different PubSub received message types depending on whether a synchronous or asynchronous method is used to pull messages.
> ~~**Disclaimer:** I was not able to generate the docs locally due to network timeouts when downloading intersphinx inventory files from external sources. Please double check that the generated intra-doc links work.~~
**Steps to perform:**
- Generate the pubsub docs locally (from inside the `pubsub/` directory):
```
$ nox -f noxfile.py -s docs
```
- Open the generated docs for subscriber:
```
$ google-chrome "file://$GOOG_CLOUD_PYTHON_DIR/pubsub/docs/_build/html//subscriber/index.html"
```
The different received message type are clearly described, the code samples are valid, and the intra-doc links work.
> PubSub: Document different PubSub received message types

- pubsub/README.rst
Closes #8137.
Describes a possible workaround for #7387, however, it does not close it, the PR just fulfills a GA  requirement (documenting a possible workaround).
**Steps to perform:**
- Generate the pubsub docs locally (from inside the `pubsub/` directory):
```
$ nox -f noxfile.py -s docs
```
- Open the generated docs for authentication:
```
$ google-chrome "file://$GOOG_CLOUD_PYTHON_DIR/pubsub/docs/_build/html/index.html#authentication"
```
The example is understandable and correct, the links point to correct locations.
The issue itself is hard to reproduce in practice, but it was discovered in other PubSub clients that using JWT-based authentication avoids the issue. The goal of this PR is to document how different auth methods can be used with the Python client.
> PubSub: Document how to choose the PubSub auth method

- logging/google/cloud/logging/handlers/transports/background_thread.py
- logging/tests/unit/handlers/transports/test_background_thread.py
Fixes internal issue 134713268.
> Logging: Fix tests.

- storage/google/cloud/storage/client.py
- storage/tests/system.py
> Storage: fix Client download_blob_to_file fails

- test_utils/scripts/get_target_packages_kokoro.py
Rather than computing a diff from the squirrely baseref hash (as provided by `ci_diff_helper`), just use the Github API directly to query for the [list of files for a PR](https://developer.github.com/v3/pulls/#list-pull-requests-files).  We should run many fewer spurious test suites if this works as expected.  I've tested the new `get_changed_files_from_pr` function manually against both small and large PRs (which involve pagination).
> Infrastructure: Use the Github API to compute changed files for PRs.

- firestore/google/cloud/firestore_v1/client.py
- firestore/tests/system.py
- firestore/tests/unit/v1/test_client.py
> Firestore: Preserve reference to missing documents in 'Client.get_all'.

- bigtable/docs/README.rst
- bigtable/docs/client-intro.rst
- bigtable/docs/conf.py
- bigtable/docs/index.rst
- bigtable/google/cloud/bigtable/row_data.py
- bigtable/noxfile.py
- core/docs/config.rst
- dns/docs/README.rst
- dns/docs/conf.py
- dns/docs/index.rst
- dns/noxfile.py
- iam/.repo-metadata.json
- logging/docs/README.rst
- logging/docs/conf.py
- logging/docs/index.rst
- logging/noxfile.py
- resource_manager/docs/README.rst
- resource_manager/docs/conf.py
- resource_manager/docs/index.rst
- resource_manager/noxfile.py
- runtimeconfig/docs/README.rst
- runtimeconfig/docs/conf.py
- runtimeconfig/docs/index.rst
- runtimeconfig/noxfile.py
- storage/docs/README.rst
- storage/docs/conf.py
- storage/docs/index.rst
- storage/noxfile.py
Towards the docs migration to googleapis.dev
> Add nox session 'docs' to remaining manual clients.

- bigquery_datatransfer/samples/create_scheduled_query.py
This allows imports to render at the same indentation as the rest of the code. Whitespace doesn't matter for the actual SQL.
> BigQuery Data Transfer: Adjust indentation on scheduled query sample.

- speech/CHANGELOG.md
- speech/setup.py
> Release speech 1.1.0

- bigquery_storage/google/cloud/bigquery_storage_v1beta1/gapic/big_query_storage_client.py
- bigquery_storage/synth.metadata
- bigquery_storage/tests/unit/test_client.py
> BigQuery Storage: Add 'client_options' support (via synth).

- firestore/google/cloud/firestore_v1/client.py
- firestore/google/cloud/firestore_v1beta1/client.py
- firestore/tests/unit/v1/test_client.py
- firestore/tests/unit/v1beta1/test_client.py
In order to run a listen for longer than one our, gRPC needs to be configured to keep the connection alive. These changes are in generated code here though and shouldn't be merged.
b/130522486
> Firestore: Add gRPC keepalive to Client Init.

- bigquery/setup.py
- bigquery/tests/unit/test__pandas_helpers.py
- bigquery/tests/unit/test_magics.py
- bigquery/tests/unit/test_table.py
`fastparquet` is an optional dependency, and is redundant with `pyarrow`. It is not necessary to include in in the `[all]` extras. This avoids an issue where the `fastparquet` dependency pulls in a pre-release version of numpy.
Closes https://github.com/googleapis/google-cloud-python/issues/8549
Version 5.0.0 of pytest modifies the behavior of `str` on the `pytest.raises()` context manager. Update the tests to call `str` on the actual exception (`context.value`), instead.
> BigQuery: Fix unit tests for new versions of fastparquet and pytest

- bigquery/CHANGELOG.md
- bigquery/setup.py
> Release bigquery 1.16.0

- firestore/google/cloud/firestore.py
- firestore/tests/unit/test_firestore_shim.py
Add a unit test that asserts the shim stays in sync with 'google.cloud.firestore_v1'.
Closes #8173.
> Firestore: Add missing transforms to 'google.cloud.firestore' shim.

- firestore/google/cloud/firestore_v1/field_path.py
- firestore/tests/system.py
- firestore/tests/unit/v1/test_field_path.py
> Firestore: Add 'FieldPath.documentId()'.

- asset/noxfile.py
- asset/synth.py
- asset/tests/system/test_vpcsc.py
The tests can be run inside or outside of VPC service perimeter. The input to the script should be the following environment variables.
PROJECT_ID: a project that is inside the VPC perimeter.
GOOGLE_CLOUD_TESTS_VPCSC_OUTSIDE_PERIMETER_PROJECT: a project that is outside the VPC perimeter.
> Asset: Add VPCSC tests.

- storage/tests/system.py
Back-end fix for the issue expected 2019-07-12.
See #8552.
> Storage: Skip failing 'test_bpo_set_unset_preserves_acls' systest.

- datalabeling/CHANGELOG.md
- datalabeling/setup.py
> Release datalabeling 0.2.0

- dlp/CHANGELOG.md
- dlp/setup.py
> Release dlp 0.12.0

- bigquery/google/cloud/bigquery/_helpers.py
- bigquery/google/cloud/bigquery/_pandas_helpers.py
- bigquery/google/cloud/bigquery/job.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/samples/query_to_arrow.py
- bigquery/samples/tests/test_query_to_arrow.py
- bigquery/setup.py
- bigquery/tests/unit/test__pandas_helpers.py
- bigquery/tests/unit/test_job.py
- bigquery/tests/unit/test_table.py
An Arrow `Table` supports a richer set of types than a pandas `DataFrame`,
and is the basis of many data analysis systems. It can be used in
conjunction with pandas through the `Table.to_pandas()` method or the
pandas extension types provided by the `fletcher` package.
Towards #5204.
> Add `to_arrow` to get a `pyarrow.Table` from query results.

- storage/google/cloud/storage/client.py
The argument passed to `download_blob_to_file` is `file` although it was defined as `file_obj`.
> Storage: Fix example in 'Client.download_blob_to_file' docstring.

- firestore/tests/system.py
> Firestore: Avoid sharing top-level collection across test cases / CI runs.

- firestore/tests/system.py
H/t to @pchauhan-qlogic for identifying the need to unsubscribe.
Supersedes #8497.
Closes #6605, #7130.
> Firestore: Improve cleanups for 'watch' system tests.

- dns/google/cloud/dns/_http.py
Towards domain split.
The discovery document already lists the base url as dns.googleapis.com
https://www.googleapis.com/discovery/v1/apis/dns/v1/rest
https://www.googleapis.com/discovery/v1/apis/dns/v1beta2/rest
https://www.googleapis.com/discovery/v1/apis/dns/v2beta1/rest
> DNS: Change base url to dns.googleapis.com

- asset/setup.py
- bigtable/setup.py
- container/setup.py
- containeranalysis/setup.py
- datacatalog/setup.py
- iot/setup.py
- kms/google/cloud/kms_v1/gapic/transports/key_management_service_grpc_transport.py
- kms/setup.py
- kms/synth.py
- pubsub/google/cloud/pubsub_v1/gapic/transports/publisher_grpc_transport.py
- pubsub/google/cloud/pubsub_v1/gapic/transports/subscriber_grpc_transport.py
- pubsub/setup.py
- pubsub/synth.py
- securitycenter/setup.py
- spanner/setup.py
- tasks/setup.py
For pubsub / kms, also update the import of the 'IAMPolicy' stub, which
is no longer exported from the same location.
Supersedes: #8639
Supersedes: #8640
Closes: #8574
Closes: #8576
Closes: #8577
Closes: #8585
Closes: #8587
Closes: #8591
Closes: #8594
Closes: #8595
Closes: #8598
> Update pin for 'grpc-google-iam-v1' to 0.12.3+.

- bigquery/CHANGELOG.md
- bigquery/setup.py
> Release bigquery 1.17.0

- storage/google/cloud/storage/bucket.py
- storage/tests/unit/test_bucket.py
- Add named constants for allowed 'storage_class' values.
- Un-deprecate STANDARD storage class.
- Docs-deprecate storage classes implying location type.
- Add 'Bucket.location_type' property.
- Add named constants for allowed 'location_type' values.
> Storage: Add 'Bucket.location_type' property.

- videointelligence/google/cloud/videointelligence_v1/gapic/enums.py
- videointelligence/google/cloud/videointelligence_v1/gapic/video_intelligence_service_client_config.py
- videointelligence/google/cloud/videointelligence_v1/proto/video_intelligence.proto
- videointelligence/google/cloud/videointelligence_v1/proto/video_intelligence_pb2.py
- videointelligence/synth.metadata
- videointelligence/synth.py
> Videointelligence: Remove face detection feature from V1 client (via synth).

- firestore/google/cloud/firestore_v1/transaction.py
- firestore/tests/unit/v1/test_transaction.py
> Firestore: Add 'Transaction.get' / 'Transaction.get_all'.

- bigquery/google/cloud/bigquery/job.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_signature_compatibility.py
Closes #5204.
This PR adds the [last missing piece](https://github.com/googleapis/google-cloud-python/issues/5204#issuecomment-511906029) of the feature, i.e. the `bqstorage_client` parameter that was still missing from one of the methods.
Check that the signatures for various `to_arrow()` methods match (and the same for the `to_dataframe()` methods).
> BigQuery: Complete the to_arrow() method feature request

- api_core/google/api_core/bidi.py
- api_core/tests/unit/test_bidi.py
- firestore/google/cloud/firestore_v1/watch.py
- firestore/tests/unit/v1/test_cross_language.py
- firestore/tests/unit/v1/test_watch.py
Stream exceptions which pass this predicate will cause clean shutdown of the BiDi thread.
Closes #7826.
Note to reviewers: I recommend looking at this commit-by-commit.
> Firestore: Add 'should_terminate' predicate for clean BiDi shutdown.

- bigquery/tests/unit/test__pandas_helpers.py
- bigquery/tests/unit/test_magics.py
I noticed that running BigQuery unit tests issues some warning, and some of them are caused by using a "skipIf" marker with `pytest`, while the name of that marker is actually "skipif" (all lowercase).
Run bigquery unit tests, e.g.:
```
$ nox -f noxfile.py -s unit-3.6
```
Five warnings are reported, including the _"Unknown pytest.mark.skipIf - is this a typo? ..."_.
Only three warnings are reported, but none of them related to pytest markers.
> BigQuery: Fix the names of several pytest "skip if" markers

- bigtable/google/cloud/bigtable/row_data.py
To improve the developer experience when printing `Cell` instances.
> Bigtable: Add Cell.__repr__

- api_core/setup.py
- bigquery_storage/setup.py
> API Core / BigQuery Storage: Fix pins of 'googleapis-common-protos.

- datacatalog/synth.py
Enable Sample Generator Tool for Data Catalog. See https://github.com/googleapis/google-cloud-python/issues/8702 for details.
> Enable Sample Generator Tool for Data Catalog

- docs/index.rst
Hello,
It is recommended to use the official name of the service.
This PR is similar to:
https://github.com/googleapis/google-cloud-python/pull/7624
Regards,
Kamil
> Update Cloud Memorystore service link

- firestore/google/cloud/firestore_v1/client.py
- firestore/tests/system.py
- firestore/tests/unit/v1/test_client.py
Add undocumented-but-required `/documents` to the database path.
Closes #8717.
> Firestore: Fix V1 'Client.collections' method.

- bigquery/google/cloud/bigquery/magics.py
- bigquery/tests/unit/test_client.py
- bigquery/tests/unit/test_magics.py
Closes #8696.
See issue description - the Client should be instantiated with a custom user agent string when used from an IPython cell.
No, this is primarily used with Kaggle datasets, thus the overridden user agent string should take precedence.
> BigQuery: Set IPython user agent when running queries with IPython cell magic

- bigquery/tests/unit/test_magics.py
Closes #8719 
This PR properly mocks external calls in one of the tests.
1. Clear environment credentials config:
```sh
$ unset GOOGLE_APPLICATION_CREDENTIALS
```
1. Run bigquery unit tests, check the result of `test_bigquery_magic_w_maximum_bytes_billed_invalid`.
The test fails with `DefaultCredentialsError`.
The code under tests raises `ValueError` as expected, and the test passes.
> BigQuery: Mock external calls in one of BigQuery unit tests

- api_core/google/api_core/future/polling.py
- api_core/tests/unit/future/test_polling.py
> API Core: Forward 'timeout' arg from 'exception' to '_blocking_poll'.

- firestore/google/cloud/firestore_v1/watch.py
- firestore/noxfile.py
- firestore/tests/system/test_system.py
- firestore/tests/system/util/cleanup_firestore_documents.py
- firestore/tests/unit/v1/test_watch.py
See:
https://github.com/googleapis/google-cloud-python/pull/8650#pullrequestreview-261830931
> Firestore: Treat 'None' as EOF in 'Watch.on_snapshot'.

- firestore/synth.metadata
- firestore/synth.py
> Firestore: Preserve manual change in noxfile (run systests verbosely).

- datacatalog/.repo-metadata.json
- datacatalog/README.rst
Data Catalog: Fix client documentation links from nodejs version to python version
> Data Catalog: Fix client documentation links

- spanner/CHANGELOG.md
- spanner/setup.py
> Release spanner 1.10.0

- iot/CHANGELOG.md
- iot/setup.py
> Release iot 0.3.0

- texttospeech/CHANGELOG.md
- texttospeech/setup.py
> Release texttospeech 0.5.0

- bigquery/noxfile.py
- bigquery/tests/unit/test__pandas_helpers.py
Fixes broken unit tests from latest pyarrow release.
> BigQuery: Treat NaN as NULL when converting from pandas to arrow.

- talent/CHANGELOG.md
- talent/setup.py
> Release talent 0.3.0

- core/google/cloud/_http.py
See #8737.
> Hmm, that `@classmethod` looks a little bogus to me. All actual uses of it are via instances:
> 
> ```shell
> $ git grep "\.build_api_url"
> bigquery/tests/unit/test__http.py:        self.assertEqual(conn.build_api_url("/foo"), URI)
> bigquery/tests/unit/test__http.py:        uri = conn.build_api_url("/foo", {"bar": "baz"})
> bigquery/tests/unit/test__http.py:        expected_uri = conn.build_api_url("/rainbow")
> bigquery/tests/unit/test__http.py:        expected_uri = conn.build_api_url("/rainbow")
> core/google/cloud/_http.py:        url = self.build_api_url(
> core/tests/unit/test__http.py:        self.assertEqual(conn.build_api_url("/foo"), URI)
> core/tests/unit/test__http.py:        uri = conn.build_api_url("/foo", {"bar": "baz", "qux": ["quux", "corge"]})
> …
```
> Core: Make build_api_url an instance method.

- bigquery/google/cloud/bigquery/job.py
- bigquery/tests/unit/test_job.py
Closes #5408.
As per user request, this PR adds additional info to any errors that might happen when calling `job.result()`.
- Use BigQuery client to run a query that results in an error - e.g. invalid SQL syntax, unknown table/dataset, etc.
The error output only contains the exception traceback.
**Actual result (after the fix):**
The error output contains *all* of the following: exception traceback, job ID, the SQL query itself with lines enumerated. The type of the exception with the modified message is the same as the original exception type.
> BigQuery: Include SQL query and job ID in job errors

- firestore/google/cloud/firestore_v1/client.py
- firestore/tests/unit/v1/test_client.py
Adds support for using the firestore emulator with the client library. 
Fixes #7500
> Firestore: support emulator in client.

- pubsub/google/cloud/pubsub_v1/subscriber/message.py
- pubsub/google/cloud/pubsub_v1/types.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_message.py
As per offline email thread, this PR marks several aspects of the Python PubSub client as deprecated. The PR assumes that deprecation will happen in version `0.43.1` (current version: `0.43.0`)
**Steps to perform:**
Verify that all discussed features are properly marked as deprecated, and that this is reflected in the docs.
To generate the docs, run the following from inside the `pubsub/` directory:
```
$ nox -f noxfile.py -s docs
```
... and open the generated docs in the browser:
```
$ google-chrome docs/_build/html/index.html 
```
> PubSub: Deprecate several FlowControl settings and things in Message class

- bigquery/tests/system.py
This allows the VPC-SC team to use their private mirror which is within
the security boundary when testing BigQuery VPC-SC support.
Closes #8550.
> BigQuery: Use configurable bucket name for GCS samples data in systems tests.

- pubsub/CHANGELOG.md
- pubsub/setup.py
**Comment:** It is primarily meant to mark several things in the PubSub client as deprecated.
> Release pubsub 0.44.0

- api_core/google/api_core/bidi.py
> API Core: Remove error log entry on clean BiDi shutdown.

- translate/google/cloud/translate_v2/_http.py
- translate/google/cloud/translate_v2/client.py
- translate/setup.py
- translate/tests/unit/test__http.py
- translate/tests/unit/test_client.py
> Translate: Add client options to translate_v2.

- pubsub/google/cloud/pubsub_v1/publisher/client.py
- pubsub/google/cloud/pubsub_v1/subscriber/client.py
> Pub/Sub docs: double back-ticks for ReST correctness.

- bigquery/google/cloud/bigquery/magics.py
- bigquery/tests/unit/helpers.py
- bigquery/tests/unit/test_magics.py
Closes #8696 
This is a follow-up to #8713, it adds the same user-agent string to the optional BQ storage client, if the latter is used.
See issue description and the subsequent [comment](https://github.com/googleapis/google-cloud-python/issues/8696#issuecomment-513882649) about adding the user-agent info to the other client, too.
> BigQuery: Set BQ storage client user-agent when in Jupyter cell

- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py
- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/google/cloud/pubsub_v1/subscriber/message.py
- pubsub/google/cloud/pubsub_v1/types.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_message.py
As per offline email thread, this PR removes deprecated PubSub client features (as a follow-up to #8796). It is a pre-release step for the upcoming `0.45.0` release.
Nothing much except for making sure that all traces of the deprecated things are indeed gone.
It is probably best to review this commit by commit.
> PubSub: Remove deprecated methods and settings

- bigquery/noxfile.py
- bigquery/tests/unit/helpers.py
- bigquery/tests/unit/test_magics.py
- test_utils/test_utils/imports.py
Following a [recent discussion](https://github.com/googleapis/google-cloud-python/pull/8734#discussion_r307532267), this PR moves a test utility from BigQuery to the top-level test utils, since it is considered useful outside of BigQuery, too.
Primarily verify that the promoted utility function is general enough for the promotion.
> Move maybe_fail_import() to top level test utils

- logging/google/cloud/logging/_helpers.py
- logging/google/cloud/logging/handlers/transports/background_thread.py
- logging/google/cloud/logging/handlers/transports/sync.py
- logging/tests/system/test_system.py
- logging/tests/unit/handlers/transports/test_background_thread.py
- logging/tests/unit/handlers/transports/test_sync.py
- logging/tests/unit/test__helpers.py
Rather than relying on `logging.LogRecord.levelname`, which can be changed to arbitrary values, map `logging.LogRecord.levelno` to the corresponding enum value.
Closes #7213.
> Logging: Map stdlib loglevels to Stackdriver severity enum values.

- bigquery/google/cloud/bigquery/magics.py
- bigquery/tests/unit/test_magics.py
Closes #6848.
This PR makes sure that long tracebacks are hidden on exceptions when using `%%bigquery` cell magic, and only the relevant info is printed out.
- Run IPython from the virtualenv and load the `%%bigquery` cell magic:
```
%load_ext google.cloud.bigquery
```
- Run a query that triggers an error, e.g. a syntax error, unknown dataset, etc. Example:
```
%%bigquery 
SELECT 1 SELECT
```
An error is printed out, including the full traceback of internal calls.
Only the relevant error info is printed out, i.e. _without_ the traceback, as the latter can be considered an internal detail of the cell magic.
No, as no one should be using the `%%bigquery` magic outside of a Jupyter environment
> BigQuery: Hide error traceback in BigQuery cell magic

- logging/google/cloud/logging_v2/gapic/transports/config_service_v2_grpc_transport.py
- logging/google/cloud/logging_v2/gapic/transports/logging_service_v2_grpc_transport.py
- logging/google/cloud/logging_v2/gapic/transports/metrics_service_v2_grpc_transport.py
- logging/synth.metadata
- logging/synth.py
Applies fix from #5594 (in response to #5574) to Logging.
Also opened PR https://github.com/grpc/grpc/pull/19810 to see if the defaults can be changed for grpcio.
> Logging: Remove gRPC size restrictions (4MB default)

- firestore/google/cloud/firestore_v1/watch.py
- firestore/tests/unit/v1/test_watch.py
`delete_changes` on the changed line is a list of string, not a list of DocumentSnapshots, so it should not be sorted with the query comparator function (see https://github.com/googleapis/google-cloud-python/blob/master/firestore/google/cloud/firestore_v1/watch.py#L575)
For context, I'm getting this error in one of my snapshot listeners in google-cloud-firestore==1.3.0
```
Thread-ConsumeBidirectionalStream caught unexpected exception 'str' object has no attribute 'reference' and will exit.
File ".../venv/lib/python3.5/site-packages/google/api_core/bidi.py", line 635, in _thread_main
self._on_response(response)
File ".../venv/lib/python3.5/site-packages/google/cloud/firestore_v1/watch.py", line 443, in on
_snapshot
meth(proto)
File …
```
> Firestore: Fix sorting 'delete_changes' in 'Watch._compute_snapshot'.

- bigquery/google/cloud/bigquery/_pandas_helpers.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_table.py
With BQ Storage API and `logging.basicConfig(level=logging.DEBUG)`:
```python
import google.cloud.bigquery_storage_v1beta1
import google.cloud.bigquery
client = google.cloud.bigquery.Client()
bqstorage = google.cloud.bigquery_storage_v1beta1.BigQueryStorageClient()
rows = client.list_rows("schema_examples.scalar_fields")
import logging
logging.basicConfig(level=logging.DEBUG)
df = rows.to_dataframe(bqstorage_client=bqstorage)
```
Outputs:
```
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.googleapis.com:443
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG:google.cloud.bigquery._pandas_helpers:Started reading table …
```
> BigQuery: Add debug logging statements to track when BQ Storage API is used.

- firestore/google/cloud/firestore_v1/query.py
- firestore/tests/unit/v1/test_query.py
Closes #8633.
Supersedes #8810.
> Firestore: Allow snapshot cursors from other collections for collection group queries.

- storage/google/cloud/storage/bucket.py
The old storage classes are actually legacy, not yet deprecated
> Storage: Mark old storage classes as legacy, not deprecated.

- iam/google/cloud/iam_credentials_v1/gapic/iam_credentials_client.py
- iam/google/cloud/iam_credentials_v1/gapic/transports/iam_credentials_grpc_transport.py
- iam/synth.metadata
Reverts googleapis/google-cloud-python#8908.
Tests passed on IAM because there are no system tests. Options are not getting passed correctly to create_channel
Currently generated as:
```
options={
"grpc.max_send_message_length": -1,
"grpc.max_receive_message_length": -1,
},
```
vs.
https://github.com/googleapis/google-cloud-python/blob/edcbf6f90a1bd4e3d5781219786994a4a807021d/monitoring/google/cloud/monitoring_v3/gapic/transports/alert_policy_service_grpc_transport.py#L101-L104
> Revert "IAM: Remove send/recv msg size limit (via synth)."

- logging/google/cloud/logging_v2/gapic/config_service_v2_client.py
- logging/google/cloud/logging_v2/gapic/logging_service_v2_client.py
- logging/google/cloud/logging_v2/gapic/metrics_service_v2_client.py
- logging/synth.metadata
- logging/synth.py
Now handled via gapic-generator.
Closes #8931.
> Logging: Delete custom synth removing gRPC send/recv msg size limits.

- bigquery/docs/snippets.py
Remove this sample in favor of the sample added in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2312.
> BigQuery: Remove redundant service account key code sample.

- bigquery_storage/google/cloud/bigquery_storage_v1beta1/gapic/big_query_storage_client.py
- bigquery_storage/google/cloud/bigquery_storage_v1beta1/gapic/transports/big_query_storage_grpc_transport.py
- bigquery_storage/synth.metadata
- bigquery_storage/synth.py
> BigQuery Storage: Remove send/recv msg size limit (via synth).

- bigquery/google/cloud/bigquery/_pandas_helpers.py
- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/unit/test__pandas_helpers.py
- bigquery/tests/unit/test_client.py
Closes #7701.
This PR adds an optional parameter to `Client.load_table_from_dataframe()` method that allows selecting the compression method if directly serializing a dataframe to a parquet file.
The issue description should be self-explanatory, but mind one of the [comments](https://github.com/googleapis/google-cloud-python/issues/7701#issuecomment-486021029):
> Also I'm actually a bit wary of exposing compression, since I'd like to keep the option open to change the file format we serialize to. Parquet happens to be the best match to BigQuery's data types right now, but it'd be good to keep the option open to move to something else in the future.
I opted for the name `parquet_compression` instead of `compression` to indicate that the parameter is specific to parquet serialization, and …
> BigQuery: Allow choice of compression when loading from dataframe

- bigtable/google/cloud/bigtable_admin_v2/gapic/bigtable_instance_admin_client.py
- bigtable/google/cloud/bigtable_admin_v2/gapic/bigtable_table_admin_client.py
- bigtable/google/cloud/bigtable_admin_v2/gapic/transports/bigtable_instance_admin_grpc_transport.py
- bigtable/google/cloud/bigtable_admin_v2/gapic/transports/bigtable_table_admin_grpc_transport.py
- bigtable/google/cloud/bigtable_v2/gapic/bigtable_client.py
- bigtable/google/cloud/bigtable_v2/gapic/transports/bigtable_grpc_transport.py
- bigtable/synth.metadata
- bigtable/synth.py
> Bigtable: Remove send/recv msg size limit (via synth).

- storage/google/cloud/storage/client.py
- storage/google/cloud/storage/hmac_key.py
- storage/tests/system.py
- storage/tests/unit/test_blob.py
- storage/tests/unit/test_client.py
- storage/tests/unit/test_hmac_key.py
@jkwlui This PR is for merging the HMAC keys feature branch to `master`:  you have already-reviewed the changes in PRs #8041, #8043, and #8045.
I still need to:
Closes #7851.
> Storage: add HMAC key support

- firestore/google/cloud/firestore_v1/query.py
- firestore/tests/system/test_system.py
- firestore/tests/unit/v1/test_query.py
> Firestore: Expand dotted keys in mappings used as cursors.

- bigtable/docs/snippets.py
Fixes #8480 
We used to observe this issue while working on Bigtable. As per our understanding, this used to occur intermittently when Google Cloud takes longer than expected to create instance or table. So we added some cool down time. Now we have added a retry logic to [exponentially] factor in the cool down time, if the table creation fails. As of right now, the max retry count is 4, though it can be configured.
> Bigtable: 'test_bigtable_create_table' snippet flakes with '504 Deadline Exceeded'.

- storage/google/cloud/storage/_signing.py
- storage/google/cloud/storage/blob.py
> Storage: Fix documentation misleading response_type signed_url

- bigtable/docs/snippets.py
Issue #8479
Bigtable: 'test_bigtable_list_tables' snippet flakes with '504 Deadline Exceeded'.
_Issue:_
As per my understanding this used to occur intermittently when Google cloud takes longer than expected to create instance or table. So we added cool down time before creating table in an instance.
We used to observe this issue sometimes while working on bigtable issues. 
_Fix:_
This fix is added to avoid creating and deleting table for single test. 
Instead, common table can be created and used in tests which require table specific tests, except table creation test.
_Fix tested with following approaches:_
This issue is not consistent in production i suppose. And I was not able to reproduce even once.
I tried different approach to hit this issue,
1. Created multiple tables(>100) in test …
> Bigtable: Create table in list_table test, deadline exceed error fix

- storage/tests/system.py
> Storage: Harden 'test_access_to_public_bucket' against 429 / 503 errors.

- bigquery/CHANGELOG.md
- bigquery/setup.py
> Release bigquery 1.18.0

- bigquery/docs/snippets.py
Closes #9007.
This PR adjust am example from the docs so that it works unmodified under Python 2.7, too.
- Create a BigQuery table with columns as in the screenshot posted in the issue description.
- Run the [load DataFrame example](https://googleapis.github.io/google-cloud-python/latest/bigquery/usage/pandas.html#load-a-pandas-dataframe-to-a-bigquery-table) from the docs using Python 2.7.
The server responds with a 400 error (as reported in the issue).
The adjusted example from the docs runs fine under Python 2.7, no error from the server.
> BigQuery: Fix Pandas DataFrame load example under Python 2.7

- bigquery/google/cloud/bigquery/query.py
- bigquery/tests/unit/test_query.py
Closes #9027.
For `None` parameters, the back-end does not return the parameter value in response, causing an error when deserializing ScalarQueryParameter from JSON.
Run the example from the issue description. With the fix applied, the error should not occur anymore, and the resulting `query_parameters` object is correct.
> BigQuery: Fix deserializing None QueryParameters

- automl/README.rst
- automl/docs/gapic/v1beta1/helper.rst
- automl/docs/gapic/v1beta1/tables.rst
- automl/docs/index.rst
- automl/google/cloud/automl_v1beta1/__init__.py
- automl/google/cloud/automl_v1beta1/helper/tables.py
- automl/google/cloud/automl_v1beta1/tables/tables_client.py
- automl/synth.py
- automl/tests/system/gapic/v1beta1/test_system_tables_client_v1.py
- automl/tests/unit/gapic/v1beta1/test_tables_client_v1beta1.py
AutoML tables is heavily used by datascientists in jupyter notebooks. Based on feedback we've gotten, the existing client is hard to use, obtuse, not notebook-friendly. This wrapper client aims to fix that.
```python
from google.cloud import automl_v1beta1
client = automl_v1beta1.TablesClient(project='my-project-123')
client.list_datasets()
dataset = client.create_dataset('my_dataset')
client.import_data(dataset=dataset, gcs_input_uris='gs://my-data/data.csv').result()
client.set_target_column(dataset=dataset, column_spec_display_name='output')
model = client.create_model(dataset=dataset, train_budget_milli_node_hours=1000).result()
```
Most testing is done in unit tests, however we have some integration tests covering the common user flows as well (create dataset -> import data -> train …
> AutoML: Add a TablesClient for automl-tables specific behavior.

- bigquery/google/cloud/bigquery/_pandas_helpers.py
- bigquery/google/cloud/bigquery/schema.py
- bigquery/tests/unit/test_schema.py
A struct field can be referred to as "RECORD" or "STRUCT", and this commit assures that the `to_api_repr()` logic is correct. It also moves `STRUCT_TYPES` from `_pandas_helpers` to `schema` where it belongs more naturally IMO.
Discovered this while writing the "all types" system test, and tried to create a STRUCT field using the  standard SQL type name `"STRUCT"`.
- Using the BigQuery client, try to create a table with a "STRUCT" column (using that particular type name):
```py
from google.cloud import bigquery
bq_client = bigquery.Client()
schema = [
bigquery.SchemaField(
"person_struct_field",
"STRUCT",
fields=(
bigquery.SchemaField("name", "STRING"),
bigquery.SchemaField("age", "INT64"),
)
),
]
bq_table = bigquery.table.Table(
table_ref="{}.{}.active_users".format(PROJECT_ID, …
```
> BigQuery: Fix schema recognition of struct field types

- containeranalysis/CHANGELOG.md
- containeranalysis/setup.py
> Release containeranalysis 0.3.0

- firestore/docs/index.rst
Seems like it should be google-cloud-firestore instead of google-cloud-datastore
> Fix reference to library name

- api_core/google/api_core/retry.py
> API Core: about of time -> amount of time

- bigquery/google/cloud/bigquery/enums.py
Closes #7632.
This PR adds an enum of legacy SQL type names that can be used with in schema fields.
@tswast This enum is a bit different from the existing `StandardSqlDataTypes` enum which maps type names to their gapic integer codes. Let me know if I misunderstood the ticket.
Make sure all of the [legacy SQL type names](https://cloud.google.com/bigquery/data-types#legacy_sql_data_types) are included in the enum (and nothing else).
> BigQuery: Add enum with SQL type names allowed to be used in SchemaField

- bigquery/tests/unit/test_table.py
Closes #8855.
This PR removes references to avro schemas in unit tests for table.
Just make sure there are no avro schemas used in `test_table.py` anymore, and that test semantics have not changed.
> BigQuery: Replace avro with arrow schemas in test_table.py

- bigquery_storage/noxfile.py
- bigquery_storage/tests/system/assets/people_data.csv
- bigquery_storage/tests/system/conftest.py
- bigquery_storage/tests/system/test_reader.py
Closes #8983.
This PR adds additional system tests for BigQuery Storage. It _does not_ include the last item from the issue description, i.e. the long-running test, at least not until decided otherwise.
Created #9066 for that.
> BigQuery Storage: Add more in-depth system tests 

- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/unit/test_client.py
Closes #9024.
This PR detects if loading table data from a dataframe with STRUCT columns, and raises a helpful error before doing any more work.
It also issues a pending deprecation warning if schema is not provided as discussed separately.
**Edit:** Now seeing the specs for no-schema deprecation in #9042, this PR can be viewed as a step towards it (the additional logic for when to issue a warning will be added separately). If the warning should be removed altogether in this PR, please let me know.
- Create a table matching the schema from the issue description.
- Run the example from the issue description.
Instead of an uninformative `FileNotFoundError`, a `ValueError` with a clear message is raised.
> BigQuery: Raise helpful error when loading table from dataframe with STRUCT columns

- bigquery/google/cloud/bigquery/dataset.py
- bigquery/tests/unit/test_dataset.py
> BigQuery: Add support to Dataset for project_ids with org prefix.

- bigquery/google/cloud/bigquery/job.py
- bigquery/tests/unit/test_job.py
Closes #9074.
This PR adds a public way of unsetting a schema from a `LoadJobConfig`.
Create a `LoadJobConfig` with a `schema` attribute, then set `schema` to `None` --> the schema should be cleared.
> BigQuery: Add support for unsetting LoadJobConfig schema

- bigquery/google/cloud/bigquery/_pandas_helpers.py
- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/system.py
- bigquery/tests/unit/test_client.py
Closes #8140 
- ~Update snippets to show overriding schema for columns whose types can't be autodetected.~ Blocked by https://github.com/googleapis/google-cloud-python/issues/5572#issuecomment-524012299.
~This PR is branched from https://github.com/googleapis/google-cloud-python/pull/9049.~
> BigQuery: Allow subset of schema to be passed into `load_table_from_dataframe`.

- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/system.py
- bigquery/tests/unit/test_client.py
Closes #4553.
This PR adds a helper client method `load_table_from_json()`. Is supersedes #9070, because GitHub did not detect updates in my topic branch.
Check that the method is similar to e.g. `client.load_table_from_dataframe()` and in line with the requirements.
P.S.: I will address the last [issue comment](https://github.com/googleapis/google-cloud-python/issues/4553#issuecomment-521577646) separately once this is approved (replacing the `_add_rows()` helper in system tests is a separate refactoring task IMO).
> BigQuery: Add load_table_from_json() method to BQ client

- monitoring/noxfile.py
- monitoring/tests/system/test_vpcsc.py
Follow up to #8295.
CC @steinwaywhw
> Monitoring: Fix environment variables for VPC tests.

- bigquery_storage/noxfile.py
- bigquery_storage/synth.metadata
- bigquery_storage/synth.py
Follow-up to: https://github.com/googleapis/google-cloud-python/pull/8992, which adds BigQuery as a system test dependency.
Replaces https://github.com/googleapis/google-cloud-python/pull/9068.
> BigQuery Storage: Add BigQuery to extra test dependencies.

- bigquery/google/cloud/bigquery/_pandas_helpers.py
- bigquery/tests/unit/test__pandas_helpers.py
- bigquery/tests/unit/test_client.py
I found it to be difficult to debug typos in column/index names in the
schema, so I have hardened the error messages to indicate when unknown
field values are found.
Split from #9084
Follow-up to #8140
> Raise with extra or missing columns in `load_table_from_dataframe` schema.

- bigquery_storage/tests/system/conftest.py
- bigquery_storage/tests/system/test_reader.py
This PR addresses https://github.com/googleapis/google-cloud-python/pull/8992#discussion_r314076857. It replaces the system tests helper method `_add_rows()` with a very similar method from BigQuery client.
> BigQuery Storage: Replace obsolete test helper method

- storage/google/cloud/storage/blob.py
- storage/google/cloud/storage/bucket.py
- storage/google/cloud/storage/client.py
- storage/tests/unit/test_blob.py
- storage/tests/unit/test_bucket.py
- storage/tests/unit/test_client.py
> Storage: Add `Blob.from_string` and `Bucket.from_string`.

- bigquery/docs/snippets.py
`test_copy_table_cmek()` snippets test results in internal error on the backend and fails, blocking the PRs, and this PR marks the test as skipped.
Currently awaiting more information from the backend team. If the issue is not fixed soon, we will temporarily disable the test, but until then please do not merge this PR just yet.
> BigQuery: Disable failing snippets test

- bigquery/google/cloud/bigquery/client.py
For [google.cloud.bigquery.client.Client.create_dataset](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client.create_dataset)
The documentation reference URL should be 
https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets/insert
instead of
https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/insert
> Docs: fix the reference URL for BigQuery create_dataset()

- iam/.repo-metadata.json
(Python's JSON support is sensitive to trailing commas)
> IAM: Fix typo in repository metadata JSON.

- api_core/docs/auth.rst
- dns/README.rst
- language/README.rst
- runtimeconfig/README.rst
- webrisk/README.rst
Fix following broken links:
- 'Google Cloud DNS ' on https://googleapis.github.io/google-cloud-python/latest/dns/index.html
- 'Product Documentation' on https://googleapis.github.io/google-cloud-python/latest/language/index.html
- 'Enable the Google Cloud RuntimeConfig API.' on https://googleapis.github.io/google-cloud-python/latest/runtimeconfig/index.html
- 'Product Documentation', 'Enable the Web Risk API.' and 'Web Risk API' on https://googleapis.github.io/google-cloud-python/latest/webrisk/index.html
- 'oauth2client' on https://googleapis.github.io/google-cloud-python/latest/core/auth.html
> Docs: Fix broken links for Core, DNS, Language, RuntimeConfig and WebRisk

- storage/google/cloud/storage/_signing.py
> Storage; Fix deep / broken URL for service account setup.

- bigquery/CHANGELOG.md
- bigquery/setup.py
> Release bigquery 1.19.0

- tasks/google/cloud/tasks_v2/gapic/cloud_tasks_client.py
Hi,
The reference to class seems wrong.
PR introduces the correct reference.
Connected issue:
https://github.com/googleapis/google-cloud-python/issues/7503
Connected PR:
https://github.com/googleapis/google-cloud-python/pull/8779
Kind regards
> Tasks: Fix reference to View

- logging/google/cloud/logging/handlers/container_engine.py
It looks like this was broken here: https://github.com/googleapis/google-cloud-python/commit/aee5ceca1561e7f2c92a71b7be026851c5cb5d41#diff-c49b1ce108fd52ae2640bc8afc4415d7R40
> Logging: Pass 'stream' argument to super in 'ContainerEngineHandler.__init__'.

- bigquery/google/cloud/bigquery/job.py
- bigquery/tests/unit/test_job.py
First of 3 PRs towards resolving #9105 as described in review for #9147
> BigQuery: Add 'max_results' param to 'QueryJob.result()'.

- datastore/google/cloud/datastore/client.py
- datastore/setup.py
- datastore/tests/unit/test_client.py
> Datastore: Add `client_options` to constructors for manual clients.

- vision/tests/system.py
…. Fixes broken Vision tests since returned logo result is "Google".
> Vision: Flatten case of logo text in systest.

- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/system.py
- bigquery/tests/unit/test_table.py
Closes #9174.
This PR fixes the issue with `max_results` if BQ storage API is used by falling back to the `tabledata.list` API endpoint, and issuing a user warning.
Run the code sample from the issue description, and verify that indeed only 100 rows is returned regardless of which client (BQ or BQ storage) is used.
> BigQuery, BigQuery Storage: Fix list_rows() max results with BQ storage client

- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/unit/test_client.py
Closes #9042.
This PR adds a deprecation warning if a schema cannot be autodetected in full, and a fallback to `to_parquet` logic is needed.
Try loading data into a new table from a dataframe with at least one column whose dtype is "object" (e.g. a STRING column), and without providing an explicit schema in JobConfig. The `load_table_from_dataframe()` method should issue a (pending) deprecation warning.
> BigQuery: Deprecate automatic schema conversion in load_table_from_dataframe()

- bigquery/google/cloud/bigquery/dbapi/_helpers.py
- bigquery/tests/unit/test_dbapi__helpers.py
Closes #9177.
This PR adds support for array-like query parameters.
Run the example from the issue description (slightly modified, see below). Binding an array-like parameter to a parametrized query should not raise an error, and the following should work as expected:
```py
curr.execute(query, (('NY', 'TX'), ))
```
Mind that scanning arrays requires using `IN UNNEST(...)` construct ([docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/arrays#scanning-arrays)), thus the `UNNEST` function needs to be added to the query from the issue description:
```py
query = """
SELECT name, state
FROM `bigquery-public-data.usa_names.usa_1910_2013`
WHERE state IN UNNEST(%s)
LIMIT 2
"""
```
- No nested arrays support, only for arrays of scalar types.
- Detecting if a value is "array-like" …
> BigQuery: Add support for array parameters to Cursor.execute()

- storage/docs/constants.rst
- storage/docs/index.rst
- storage/google/cloud/storage/blob.py
- storage/google/cloud/storage/bucket.py
- storage/google/cloud/storage/constants.py
- storage/tests/unit/test_blob.py
- storage/tests/unit/test_bucket.py
Exceptions are for tests of setters, which exercise allowed values.
Closes #9191.
> Storage: Avoid using 'REGIONAL'/'MULTI_REGIONAL' in examples, tests.

- storage/setup.py
- storage/tests/unit/test_blob.py
Reverts googleapis/google-cloud-python#9204
Should fix tests for #9239.
> Storage: Revert "Fix tests b0rken by 'google-resumable-media 0.4.0' release."

- firestore/README.rst
See [this report](https://github.com/googleapis/google-cloud-python/issues/7534#issuecomment-531969738).
> Firestore: Update README example to use non-deprecated 'query.get'.

- bigquery/google/cloud/bigquery/magics.py
- bigquery/tests/unit/test_magics.py
Third of 3 PRs towards resolving #9105 as described in review for #9147
Screenshot of feature in notebook:
> BigQuery: Add ability to pass in a table ID instead of a query to the %%bigquery magic.

- spanner/google/cloud/spanner_v1/database.py
Summary:
These docs used to be correct, but `Session.run_in_transaction` was
changed from returning the commit timestamp to returning the function
value in #3753, and the upstream docs were not updated.
The docs for `run_in_transaction` are now identical across `Database`
and `Session`.
The tests for `run_in_transaction` (in `test_database.py`) are wrong, as
they mock out the session object instead of using a real session, and
they also were not updated in #3753. This change does not fix them.
Test Plan:
```
$ virtualenv -q -p python3.6 ./ve
$ . ./ve/bin/activate
(ve) $ pip install -q google-cloud-spanner==1.10.0
(ve) $ pip freeze | grep google-cloud-spanner
google-cloud-spanner==1.10.0
(ve) $ cat test.py; echo
from google.cloud import spanner_v1
client = spanner_v1.Client()
instance = …
```
> Spanner: Fix `run_in_transaction` return value docs

- dlp/noxfile.py
Fixes bug reported by siddinesh@, in which `True` is passed rather than `true`. Causes Kokoro tests to break outside of git. This will ensure GOOGLE_CLOUD_TESTS_IN_VPCSC is always tested against `true` as is the expected behavior.
> test(dlp): ensure GOOGLE_CLOUD_TESTS_IN_VPCSC is down cast for env variables

- core/google/cloud/client.py
This PR fixes the wrong URL link in `_GOOGLE_AUTH_CREDENTIALS_HELP`
> docs(core): fix Google Auth Credentials help link

- storage/google/cloud/storage/_helpers.py
Fixed a typo in line 46 "las" -> "last".
> Storage: Fix typo in _helpers.py

- storage/google/cloud/storage/client.py
- storage/google/cloud/storage/hmac_key.py
- storage/tests/unit/test_client.py
- storage/tests/unit/test_hmac_key.py
> Storage: HMAC add user_project param

- bigquery/google/cloud/bigquery/dbapi/cursor.py
- bigquery/tests/unit/test_dbapi_cursor.py
My change allows to support `use_legacy_sql`.
> feat(bigquery): add support for custom QueryJobConfig in BigQuery.cursor.execute method

- bigquery/google/cloud/bigquery/client.py
Closes #9203.
This PR documents how to load table data from a JSON string. This will make it less likely for the users to try loading JSON string data with the `load_table_from_json()` method (the latter expects an iterable of dicts.
We opted not to add a yet another load method `load_table_from_string`, as that will more or less just repeat the logic from `load_table_from_file()`, and because wrapping string data into a file-like object is straightforward.
> docs(bigquery): document how to load data as JSON string

- bigquery/noxfile.py
Closes #9081.
This PR makes sure that the code samples, too, undergo the lint check (`flake8` specifically, as black already checks the samples).
After experimenting with the synth tool a bit, I realized that the BigQuery's noxfile is _not_ generated by synth from the [template](https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/noxfile.py.j2), thus modified it directly.
Introduce a few `flake8`-specific (i.e. not relevant to `black`) lint errors to some of the files in `docs/samples`, such as an unused import, and run the lint check:
```sh
$ nox -f noxfile.py -s lint
```
The check passes despite the lint issues.
**Expected result (before the fix):**
The check correctly fails and complains about the lint issues.
> style(bigquery): add code samples to lint check

- bigquery/google/cloud/bigquery/job.py
- bigquery/google/cloud/bigquery/magics.py
- bigquery/tests/unit/test_job.py
- bigquery/tests/unit/test_magics.py
Closes #9091.
This PR changes the Jupyter notebook magic to store the relevant QueryJob instance on errors to the specified destination variable (if any).
Start an `ipython` session from the `bigquery/` directory, and try to execute a query that results in an error:
```
In [1]: from google.cloud import bigquery
In [2]: %load_ext google.cloud.bigquery
In [3]: %%bigquery target_var --dry_run 
SELECT SELECT * FROM `bigquery-public-data.samples.shakespeare` LIMIT 5; 
```
If an error occurs, the target variable is set to a QueryJob instance, allowing further introspection. This happens both in dry runs and actual runs.
> feat(bigquery): store QueryJob to destination variable on error

- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/tests/system.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Closes #9252. 
This PR mitigates the reported issue by using the subscription's max ACK deadline when establishing a streaming pull, instead of the previous optimistic ACK deadline of 10 seconds.
(when creating a streaming pull, the ACK timing histogram has no data yet, thus its 99 % value defaults to 10 seconds... also see the commit message for some extra info)
Additionally, it adds a debug log message with the ACK deadline used for the streaming pull, as that important piece of information was missing previously.
Run the example from the issue description, and verify that the backend does not send any duplicate messages, and the subscription's ACK deadline is respected (300 s in that particular case).
The cause of the bug was that the client overrode the max ACK deadline on the …
> fix(pubsub): set default stream ACK deadline to subscriptions'

- bigquery/google/cloud/bigquery/client.py
- bigquery/google/cloud/bigquery/job.py
- bigquery/tests/system.py
- bigquery/tests/unit/test_client.py
- bigquery/tests/unit/test_job.py
Closes #9190.
This PR adds the parent job filter to `client.list_jobs()`.
Prerequisite: The (alpha) scripting feature must be enabled for your BigQuery project.
Create and run an SQL script on your project, then list jobs for that project. Find the parent job, i.e. the one whose `num_child_jobs` property is greater than zero, and use its ID to list the jobs again using the `parent_job` filter. That call should correctly return only the parent job's child jobs.
See the new system test in this PR for an example.
**Note**
There currently seems to be a backend bug - the job's `parentJobId` information is only returned when the [jobs.list](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/list) API endpoint is invoked with the `parentJobId` filter, but not when fetching jobs with a …
> feat(bigquery): add support for listing jobs by parent job

- storage/docs/snippets.py
- storage/google/cloud/storage/blob.py
Specify that the returned value is bytes in the summary, and note the
historical reason for the confused method name.
Closes #9290.
> docs(storage): clarify docstring for 'Blob.download_as_string'

- error_reporting/google/cloud/error_reporting/_gapic.py
- error_reporting/google/cloud/error_reporting/_logging.py
- error_reporting/google/cloud/error_reporting/client.py
- error_reporting/tests/unit/test__gapic.py
- error_reporting/tests/unit/test__logging.py
- error_reporting/tests/unit/test_client.py
Towards #8475 
A release of logging needs to be made before this is merged.
> Error Reporting: Add client_options to constructor.

- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/tests/system.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Closes #9339 
Re-introduces #9252. 
This PR fixes a [regression](https://github.com/googleapis/google-cloud-python/pull/9268) from the `1.0.1` release that caused the streaming pull to additionally require the `subscriptions.get` permission (the default `pubsub.subscriber` role was not sufficient anymore for the streaming pull).
By avoiding the call that fetched a subscription and read its ACK deadline, and replacing that deadline with a fixed value of 60 seconds, this *will* re-introduce #9252, albeit in a less severe manner.
Using an account that has no roles assigned other than `roles/pubsub.subscriber`, try opening a streaming pull (`subscriber.subscribe()`). That call should succeed without a permission error.
> fix(pubsub): streaming pull shouldn't require subscriptions.get permission

- speech/tests/system/gapic/v1p1beta1/test_system_speech_v1p1beta1.py
New test case for v1p1beta1 which tests 3 APIs.
> test(speech): add v1p1beta1 systests for longrunning / streaming recognize

- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Toward clean shutdown of the subscriber's background thread.
See: #8616.
> fix(pubsub): add 'StreamingPullManager._should_terminate'.

- api_core/google/api_core/bidi.py
- api_core/tests/unit/test_bidi.py
Avoid blocking for ill-behaved daemon threads during BiDi shutdown.
Closes #8616, #9008.
> fix(api_core): finalize during close of 'ResumableBidiRpc'.

- bigquery/google/cloud/bigquery/job.py
- bigquery/tests/unit/test_job.py
In addition to the parent ID property, the new scripting feature adds a new `scriptStatistics` property. This can be calling jobs.get on a script child job in the APIs Explorer.
Follow-up to https://github.com/googleapis/google-cloud-python/issues/9190 🦕
> feat(bigquery): add script statistics to job resource

- storage/google/cloud/storage/blob.py
- storage/tests/system.py
- storage/tests/unit/test_blob.py
> fix(storage): enable CSEK w/ V4 signed URLs

- bigtable/setup.py
- dns/setup.py
- firestore/setup.py
- logging/setup.py
- runtimeconfig/setup.py
- spanner/setup.py
- trace/setup.py
> chore: pin `google-cloud-core >= 1.0.3, < 2.0.0dev`.

- storage/google/cloud/storage/bucket.py
- storage/tests/unit/test_bucket.py
> feat(storage): support predefined ACLs in 'Bucket.create'

- bigquery/google/cloud/bigquery/dataset.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/samples/tests/test_update_dataset_default_partition_expiration.py
- bigquery/samples/tests/test_update_table_require_partition_filter.py
- bigquery/samples/update_dataset_default_partition_expiration.py
- bigquery/samples/update_table_require_partition_filter.py
- bigquery/tests/unit/test_dataset.py
- bigquery/tests/unit/test_table.py
Samples double as system tests. I aim to use them here:
* https://cloud.google.com/bigquery/docs/managing-partitioned-tables#require-filter
* https://cloud.google.com/bigquery/docs/updating-datasets#partition-expiration
Note: this also (silently) deprecates
TimePartitioning.require_partition_filter, as that's duplicating the
same functionality.
I was curious why the expiration_ms wasn't also moving up, but then I
realized that property only makes sense if a partition is assocatied
with a timestamp.
> feat(bigquery): add Dataset.default_partition_expiration_ms and Table.require_partition_filter properties

- dlp/noxfile.py
- dlp/tests/system/gapic/v2/test_system_dlp_service_v2_vpcsc.py
Ensure env variable is always set. If GOOGLE_CLOUD_TESTS_IN_VPCSC check fails, we will pass in an unset variable. Additionally, correct conent -> content in test_deidentify_content, preventing noisy failures.
> test(dlp): ensure env is always set; fix typo in test_deidentify_content

- bigquery/docs/reference.rst
- bigquery/google/cloud/bigquery/__init__.py
- bigquery/google/cloud/bigquery/encryption_configuration.py
- bigquery/google/cloud/bigquery/job.py
- bigquery/google/cloud/bigquery/model.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/model/test_model.py
- bigquery/tests/unit/test_client.py
- bigquery/tests/unit/test_encryption_configuration.py
- bigquery/tests/unit/test_job.py
- bigquery/tests/unit/test_table.py
> feat(bigquery): expose customer managed encryption key for ML models

- error_reporting/setup.py
> chore(error_reporting): pin 'google-cloud-logging >= 1.14.0, < 2.0.0dev

- bigquery/docs/reference.rst
- bigquery/google/cloud/bigquery/__init__.py
- bigquery/google/cloud/bigquery/job.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_job.py
- bigquery/tests/unit/test_table.py
These classes and properties add support for the integer range
partitioning feature. These offer more flexibility in partitioning
options than time-based partitioning.
Note: integer range partitioning is currently only available under whitelist.
> feat(bigquery): add range partitioning to tables, load jobs, and query jobs

- bigquery/google/cloud/bigquery/dataset.py
- bigquery/tests/unit/test_dataset.py
> feat(bigquery): implement defaultEncryptionConfiguration on datasets

- .github/CODEOWNERS
I'm the primary owner of Data Catalog for now, as it's needed for some BigQuery features.
> chore(datacatalog): add codeowners for data catalog

- spanner/google/cloud/spanner_v1/client.py
- spanner/google/cloud/spanner_v1/database.py
- spanner/tests/unit/test_client.py
- spanner/tests/unit/test_database.py
> feat(spanner): add client_options to constructor

- spanner/tests/system/test_system.py
That API can fail without raising an exception (it returns a status code
and a list of rows affected by each successfull DML statuement).
We would like for our retry mechanism to operate, so raise an exception
for non-zero status inside our unit-of-work function.
Closes #7504
> test(spanner): propagate errors from 'Transaction.batch_update'

- bigquery/google/cloud/bigquery/_pandas_helpers.py
- bigquery/tests/unit/test__pandas_helpers.py
Fixes #9485.
This PR fixes a warning that can be issued when downloading results as pyarrow record batches.
The warning was caused by `pyarrow`, because a `pyarrow` schema was passed as the `names` argument, instead of as the `schema` argument, and `pyarrow` started raising a warning for it in version `0.15.0` ([source code](https://github.com/apache/arrow/blob/master/python/pyarrow/table.pxi#L754-L760)).
- Make sure `pyarrow` 0.15.0+ is installed (there is no warning in prior versions),
- Run [query_to_arrow test](https://github.com/googleapis/google-cloud-python/blob/master/bigquery/samples/tests/test_query_to_arrow.py#L21),
A `pyarrow` FutureWarning is issued (as described in the issue description).
No warning is …
> fix(bigquery): fix arrow deprecation warning

- spanner/google/cloud/spanner_v1/pool.py
- spanner/tests/unit/test_pool.py
Currently, session pools are filled by creating single sessions. For large session pool sizes (>1000) this can be incredibly slow as it requires >1000 requests to be made to the server sequentially. Using batch_create_session calls to fill the pools will reduce the number of requests by a factor of 100 which will greatly reduce the start up time.
The BurstyPool does not use batch_create_session as it is designed to create sessions on an "as needed" basis rather than filling a queue.
> feat(spanner): add batch_create_session calls to session pools

- bigquery/google/cloud/bigquery/_helpers.py
- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/unit/test_client.py
> feat(bigquery): add TypeError if wrong job_config type is passed to client job methods

- datastore/README.rst
- error_reporting/README.rst
Noticed that `API` was repeated, possibly not caught since it was on a newline in the readme.
I could not find another reference to _Google Cloud Datastore API API_.
Reject my change if I am mistaken.
Thanks
> docs(datastore): remove duplication of API

- bigquery/docs/snippets.py
> refactor(bigquery): use multi-regional key path for CMEK in snippets

- storage/docs/hmac_key.rst
- storage/docs/index.rst
- storage/docs/notification.rst
Adding missing documentation for hmac_key and notification metadata objects. 
Fixes Issue: https://github.com/googleapis/google-cloud-python/issues/9528
> docs(storage): add hmac_key and notification documentation rst files.

- bigquery/noxfile.py
Fixes #9502.
This PR removes redundancy in BigQuery's `noxfile` that results in `test_utils` being installed twice.
(modifying the noxfile directly, as it is not generated by the synth tool in BigQuery)
- Run the following nox sessions: `snippets` and `system`. You do not have to wait for them to complete, just make sure the setup phase is completed and the relevant tests start running.
In both cases `test_utils` are installed twice. In the output:
```
...
nox > pip install -e ../test_utils
...
nox > pip install -e ../test_utils
```
`test_utils` are only installed once in a session.
> chore(bigquery): remove duplicate test dependencies

- bigtable/google/cloud/bigtable/client.py
- bigtable/tests/unit/test_client.py
Toward #8475.
Supersedes #9289.
> feat(bigtable): add 'client_options' / 'admin_client_options' to Client

- bigquery/google/cloud/bigquery/_helpers.py
- bigquery/google/cloud/bigquery/_pandas_helpers.py
- bigquery/google/cloud/bigquery/client.py
- bigquery/google/cloud/bigquery/dbapi/_helpers.py
- bigquery/google/cloud/bigquery/dbapi/cursor.py
- bigquery/google/cloud/bigquery/job.py
- bigquery/google/cloud/bigquery/query.py
- bigquery/google/cloud/bigquery/table.py
- core/google/cloud/_http.py
> refactor(bigquery): rewrite docs in Google style, part 2

- bigquery/docs/usage/queries.rst
- bigquery/samples/query_script.py
- bigquery/samples/tests/test_query_script.py
- bigquery/tests/system.py
This code sample initiates a scripting job and then demonstrates how to
fetch the results and the child jobs.
Removes system test for scripting, as it's redundant with the code
sample.
> doc(bigquery): add code sample for scripting

- automl/google/cloud/automl_v1beta1/tables/tables_client.py
- automl/tests/unit/gapic/v1beta1/test_tables_client_v1beta1.py
In automl_v1beta1.TablesClient.__init__(), the credentials are not given to AutoMlClient and PredictionServiceClient, causing inconsistency between the credentials that was passed and the credentials that was actually used for API calls.
This commit ensures that credentials are passed, and add two unittests to catch the behavior.
Fixes #9490
> fix(automl): pass credentials to underlying clients in TableClient

- storage/google/cloud/storage/_http.py
As storage libraries don't have a gapic layer we shouldn't indicate a version in our headers.
> fix: don't report a gapic version for storage

- spanner/google/cloud/spanner_v1/database.py
- spanner/google/cloud/spanner_v1/session.py
> docs(spanner): update description of the timeout_secs parameter

- firestore/google/cloud/firestore_v1/query.py
- firestore/tests/system/test_system.py
- firestore/tests/unit/v1/test_query.py
> feat(firestore): surface new 'IN' and 'ARRAY_CONTAINS_ANY' operators

- pubsub/tests/system.py
Fixes #9382.
Pulling the messages using a streaming pull should work with accounts having only the `pubsub.subscriber` role. This commits add a test that covers this aspect.
- Apply the following patch to the streaming pull manager:
```patch
diff --git pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
index d3b1d6f51eb..d73a6f9cdd8 100644
--- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
+++ pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
@@ -403,6 +403,7 @@ class StreamingPullManager(object):
stream_ack_deadline_seconds = _DEFAULT_STREAM_ACK_DEADLINE
+       subscription = self._client.api.get_subscription(self._subscription) …
```
> chore(pubsub): add subscriber role test for streaming

- api_core/.coveragerc
- api_core/google/api_core/page_iterator.py
- api_core/tests/unit/test_page_iterator.py
Some paginated response messages include additional fields that users
may wish to inspect. This change stores the raw page when constructing a page_iterator.Page and provides an accessor.
In addition to the new and modified unit tests, hand experimentation generates expected behavior:
```python
from google.cloud import automl
client = automl.AutoMlClient()
result = client.list_datasets(...)
for page in result.pages:
print(f"{page.raw_page}")
```
prints individual pages.
> feat(api_core): provide a 'raw_page' field for page_iterator.Page

- spanner/tests/system/test_system.py
> test(spanner): harden 'test_transaction_batch_update*' systests against partial success + abort

- bigquery/google/cloud/bigquery/_helpers.py
- bigquery/google/cloud/bigquery/_pandas_helpers.py
- bigquery/google/cloud/bigquery/job.py
- bigquery/google/cloud/bigquery/schema.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/samples/query_external_sheets_permanent_table.py
- bigquery/samples/query_external_sheets_temporary_table.py
- bigquery/tests/unit/test__helpers.py
- bigquery/tests/unit/test__pandas_helpers.py
- bigquery/tests/unit/test_client.py
- bigquery/tests/unit/test_job.py
- bigquery/tests/unit/test_schema.py
- bigquery/tests/unit/test_table.py
Fixes #8196.
This PR adds support for passing BigQuery schema as a sequence of plain dictionaries whose content match the API representation of `schema.SchemaField` instances.
THe ticket description should be self-explanatory. The functions/methods that accept a BigQuery schema should now also accept a sequence of well-formed dicts. That includes private helpers, as this new flexibility can be useful even for internal use cases.
> feat(bigquery): allow passing schema as a sequence of dicts

- datacatalog/samples/tests/conftest.py
- datacatalog/samples/tests/test_create_fileset_entry.py
- datacatalog/samples/v1beta1/create_fileset_entry.py
> feat(datacatalog): add sample to create a fileset entry

- bigquery/setup.py
- storage/google/cloud/storage/blob.py
- storage/setup.py
- storage/tests/system.py
- storage/tests/unit/test_blob.py
Note to reviewers:  this is likely better viewed commit-by-commit.
Bumps `google-resumable-media` dependency for `google-cloud-storage` to require >= 0.5.0, while `google-cloud-bigquery` just allows it (BigQuery doesn't use the download classes).
Closes #9565.
> feat(storage): add opt-in raw download support

- test_utils/test_utils/vpcsc_config.py
> tests: add centralized VPCSC config detection

- bigquery/google/cloud/bigquery/magics.py
- bigquery/tests/unit/test_magics.py
Sample use and test here: https://colab.research.google.com/drive/1vd_5IperzwBdqnzIPKd8fWkGZg4TO1Bb (google access only)
Fixes #9598 
@sshrdp FYI
> feat(bigquery): add `--destination_table` parameter to bigquery magic

- monitoring/noxfile.py
The actual environment variable value may be `True`, instead of `true`. So just make it case insensitive.
> fix(monitoring): make VPCSC env comparison case-insensitive

- containeranalysis/google/cloud/devtools/__init__.py
- containeranalysis/noxfile.py
- containeranalysis/setup.py
- containeranalysis/synth.metadata
- containeranalysis/synth.py
> fix(containeranalysis): make google.cloud.devtools a namespace

- automl/tests/system/gapic/v1beta1/test_system_tables_client_v1.py
> tests(automl): normalize VPCSC configuration in systests

- storage/tests/system.py
> tests(storage): normalize VPCSC configuration in systests.

- firestore/docs/index.rst
> docs(firestore): clarify client threadsafety

- firestore/google/cloud/firestore_v1/collection.py
- firestore/google/cloud/firestore_v1/document.py
> docs(firestore): add documentation for Document,Collection .on_snapshot

- pubsub/google/cloud/pubsub_v1/futures.py
- pubsub/google/cloud/pubsub_v1/publisher/_batch/thread.py
- pubsub/google/cloud/pubsub_v1/publisher/client.py
- pubsub/tests/unit/pubsub_v1/publisher/batch/test_thread.py
- pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py
Add `stop()` method, which sends all outstanding messages and waits until all futures resolved. Similar features in [Go](https://github.com/googleapis/google-cloud-go/blob/bdcd41efeb09c795b4c380d194b2a7a19f945176/pubsub/topic.go#L414-L426) and [Java](https://github.com/googleapis/google-cloud-java/blob/bec495ff9106f863098b0089c51cd6a21ca9f6b2/google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java#L492-L507).
Closes #4913
Closes #6883
> feat(pubsub): add stop method

- test_utils/test_utils/vpcsc_config.py
> tests: fix typos in new 'vpcsc_config' module.

- firestore/google/cloud/firestore_v1/collection.py
- firestore/tests/unit/v1/test_collection.py
> fix(firestore): simplify 'Collection.add', avoid spurious API call

- bigquery/docs/snippets.py
- bigquery/docs/usage/tables.rst
- bigquery/samples/tests/conftest.py
- bigquery/samples/tests/test_undelete_table.py
- bigquery/samples/undelete_table.py
This fixes a flakey system test, where sometimes we sent an invalid
timestamp as a snapshot to copy from.
Fixes #9633
> chore(bigquery): fix undelete table system test to use milliseconds in snapshot decorator

- pubsub/google/cloud/pubsub_v1/types.py
- pubsub/tests/unit/pubsub_v1/publisher/test_publisher_client.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Changes:
- Max batch size is reduced from 10 MB to 1 MB
- Max latency before a batch is sent is reduced from 50 ms to 10 ms
- Max messages in a batch is reduced from 1000 messages to 100 messages
- Max messages in flight is increased from 100 messages to 1000 messages
- Max ack extension is reduced from 2 hours to 1 hour
- Also fix tests
> fix(pubsub): update batching and flow control parameters to be same as the other client libraries

- translate/tests/system/test_vpcsc.py
> tests(translate): normalize VPCSC configuration in systests

- spanner/google/cloud/spanner_v1/pool.py
- spanner/tests/unit/test_pool.py
Change sessions order from FIFO to LIFO. Done only in those pool classes, which don't have priorities.
Towards #9392
> fix(spanner): return sessions from pool in LIFO order

- vision/tests/system.py
> tests(vision): normalize VPCSC configuration in systests

- storage/tests/unit/test_client.py
Note to reviewers:  commit-by-commit will make the cleanups / refactorings clearer.
Closes #9714.
> tests(storage): fix query-string order dependent assert

- trace/noxfile.py
- trace/tests/system/gapic/v1/test_system_trace_service_v1_vpcsc.py
- trace/tests/system/gapic/v2/test_system_trace_service_v2_vpcsc.py
> tests(trace): normalize VPCSC configuration in systests

- dlp/noxfile.py
- dlp/tests/system/gapic/v2/test_system_dlp_service_v2_vpcsc.py
> tests(dlp): normalize VPCSC configuration in systests

- asset/noxfile.py
- asset/tests/system/test_vpcsc.py
> tests(asset): normalize VPCSC configuration in systests

- spanner/google/cloud/spanner_admin_database_v1/gapic/database_admin_client.py
- spanner/google/cloud/spanner_admin_database_v1/proto/spanner_database_admin.proto
- spanner/google/cloud/spanner_admin_database_v1/proto/spanner_database_admin_pb2.py
- spanner/google/cloud/spanner_admin_database_v1/proto/spanner_database_admin_pb2_grpc.py
- spanner/google/cloud/spanner_admin_instance_v1/gapic/enums.py
- spanner/google/cloud/spanner_admin_instance_v1/gapic/instance_admin_client.py
- spanner/google/cloud/spanner_admin_instance_v1/proto/spanner_instance_admin.proto
- spanner/google/cloud/spanner_admin_instance_v1/proto/spanner_instance_admin_pb2.py
- spanner/google/cloud/spanner_admin_instance_v1/proto/spanner_instance_admin_pb2_grpc.py
- spanner/google/cloud/spanner_v1/gapic/spanner_client.py
- spanner/google/cloud/spanner_v1/gapic/transports/spanner_grpc_transport.py
- spanner/google/cloud/spanner_v1/proto/keys.proto
- spanner/google/cloud/spanner_v1/proto/keys_pb2.py
- spanner/google/cloud/spanner_v1/proto/mutation.proto
- spanner/google/cloud/spanner_v1/proto/mutation_pb2.py
- spanner/google/cloud/spanner_v1/proto/query_plan.proto
- spanner/google/cloud/spanner_v1/proto/query_plan_pb2.py
- spanner/google/cloud/spanner_v1/proto/result_set.proto
- spanner/google/cloud/spanner_v1/proto/result_set_pb2.py
- spanner/google/cloud/spanner_v1/proto/spanner.proto
- spanner/google/cloud/spanner_v1/proto/spanner_pb2.py
- spanner/google/cloud/spanner_v1/proto/spanner_pb2_grpc.py
- spanner/google/cloud/spanner_v1/proto/transaction.proto
- spanner/google/cloud/spanner_v1/proto/transaction_pb2.py
- spanner/google/cloud/spanner_v1/proto/type.proto
- spanner/synth.metadata
- spanner/synth.py
> feat(spanner): add instance replica info; annotate protos, update docstrings (via synth)

- monitoring/noxfile.py
- monitoring/tests/system/test_vpcsc_v3.py
> tests(monitoring): normalize VPCSC configuration in systests

- bigquery/google/cloud/bigquery/external_config.py
Fixes #9617.
This PR fixes the anchors in URLs in external config's docstrings. The links now point to the correct exact location of the relevant configuration field.
> chore(bigquery): fix link anchors in external config docstrings

- cloudbuild/README.rst
- cloudbuild/synth.metadata
- cloudbuild/synth.py
* Fixes the link to client lib docs
* Fixes a bad synth replace. (It was replacing the `google-cloud-cloudbuild` in synth.py :sweat_smile:)
> docs(cloudbuild): fix link to client lib docs

- automl/google/cloud/automl_v1beta1/tables/gcs_client.py
- automl/tests/unit/gapic/v1beta1/test_gcs_client_v1beta1.py
pandas.dataframe.to_csv() by default exports data index as an column
with empty column name. This causes uploading the export csv file to
fail because AutoML Tables does not allow empty column names. Given
that the data index is not useful for training the model. This PR
fixes the problem by setting the index argument to false so that the
index is not exported.
Fixes #9483
> fix(automl): fix uploading pandas dataframe to AutoML Tables

- .gitignore
*~ are the auto-save files generated when editing with emacs:
https://emacsredux.com/blog/2013/05/09/keep-backup-and-auto-save-files-out-of-the-way/
More reference: https://stackoverflow.com/a/28709885/11097495
> chore: add emacs' auto-save files to .gitignore

- automl/google/cloud/automl_v1beta1/tables/tables_client.py
Disable early stopping is turned off by default. It's defined in proto
here:
https://github.com/googleapis/google-cloud-python/blob/bfb4da8542981d2eedffe20f64e87ab528a17592/automl/google/cloud/automl_v1beta1/proto/tables.proto#L196
This PR:
- exposes disable_early_stopping option for TablesClient.create_model.
- changes the default value of create_model's parameter model_metadata
from empty dict to None. Default parameter values in Python is
non-intuitive: http://effbot.org/zone/default-values.htm
> feat(automl): expose disable_early_stopping option for create_model

- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/unit/test_client.py
Fixes #9727.
This PR fixes the client methods possibly modifying JobConfig instances passed to them.
Run the example from the ticket description in a debugger, and verify that the `job_config` instance is indeed not modified when passing it to `client.query()`. Ditto for any other public client methods that accepts job config as an argument, including the Client class initializer.
> fix(bigquery): preserve job config passed to Client methods

- automl/docs/conf.py
- automl/google/cloud/automl_v1beta1/proto/io_pb2.py
- automl/synth.metadata
- automl/synth.py
#9628 (unintentionally) changed v1beta1 AND v1 docstrings. This reverts that change and just preserves fixes to v1 docstrings.
The AutoML docstrings are still borked, but it appears sphinx can build them with these changes :woman_shrugging:
> docs(automl): fix docstring formatting

- videointelligence/google/cloud/videointelligence_v1/gapic/video_intelligence_service_client.py
- videointelligence/google/cloud/videointelligence_v1/gapic/video_intelligence_service_client_config.py
- videointelligence/tests/unit/gapic/v1/test_video_intelligence_service_client_v1.py
Creating this for a rollback.
Python sample code code was passing the keyword argument `input_uri` positionally before this change. Adding a required parameter changed the parameter order and broke existing code.
```
from google.cloud import videointelligence
video_client = videointelligence.VideoIntelligenceServiceClient()
features = [videointelligence.enums.Feature.LABEL_DETECTION]
operation = video_client.annotate_video(
'gs://cloud-samples-data/video/cat.mp4', features=features)
print('\nProcessing video for label annotations:')
But I have a problem with the video annotation function, I get the following error message:
TypeError                                 Traceback (most recent call last)
<ipython-input-24-5eb4216acaf7> in <module>
4 features = …
```
> fix(videointelligence): revert #9440; make `features` a keyword parameter

- automl/google/cloud/automl_v1beta1/tables/tables_client.py
- automl/tests/unit/gapic/v1beta1/test_tables_client_v1beta1.py
Previously feature importance is added with a params parameter, the
user has to set params = {"feature_importance": "true"}. This PR
simplifies the logic, the user just have to pass feature_importance =
True.
> feat(automl): add support for feature importance

- automl/setup.py
The current pandas version 0.24.0 is unnecessarily high. Pandas 0.17
was the version with the most breaking changes in recent history, so
something after that will get most customers. This also aligns with
BigQuery Python SDK.
More context: https://github.com/googleapis/google-cloud-python/pull/9647#issuecomment-553127471
> chore(automl): reduce Pandas version requirement

- bigquery/google/cloud/bigquery/dataset.py
- bigquery/google/cloud/bigquery/model.py
- bigquery/google/cloud/bigquery/routine.py
- bigquery/tests/unit/routine/test_routine.py
> feat(bigquery): add description for routine entities

- bigquery/google/cloud/bigquery/external_config.py
- bigquery/google/cloud/bigquery/job.py
- bigquery/tests/unit/test_external_config.py
- bigquery/tests/unit/test_job.py
Fixes #9610.
This PR adds support for configuring hive partitioning to `LoadJobConfig` and` ExternalConfig` classes.
> feat(bigquery): add support for hive partitioning options configuration

- bigquery/google/cloud/bigquery/job.py
- bigquery/tests/unit/test_job.py
> feat(bigquery): add support of use_avro_logical_types for extract jobs

- bigquery/google/cloud/bigquery/schema.py
Getting following deprecation warning in Bigquery:
```
File "/usr/local/lib/python3.7/dist-packages/google/cloud/bigquery/job.py", line 3216, in __iter__
return iter(self.result())
File "/usr/local/lib/python3.7/dist-packages/google/cloud/bigquery/job.py", line 3105, in result
dest_table = Table(dest_table_ref, schema=schema)
File "/usr/local/lib/python3.7/dist-packages/google/cloud/bigquery/table.py", line 335, in __init__
self.schema = schema
File "/usr/local/lib/python3.7/dist-packages/google/cloud/bigquery/table.py", line 400, in schema
value = _to_schema_fields(value)
File "/usr/local/lib/python3.7/dist-packages/google/cloud/bigquery/schema.py", line 284, in _to_schema_fields
if not isinstance(field, (SchemaField, collections.Mapping)):
File …
```
> fix(bigquery): import Mapping from collections.abc not from collections

- storage/google/cloud/storage/blob.py
- storage/google/cloud/storage/bucket.py
- storage/tests/unit/test_blob.py
- storage/tests/unit/test_bucket.py
> fix(storage): str() metadata for for blob

- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/tests/system.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Fixes #9252.
This PR addresses the problem with some of the messages being re-delivered too early, because their acknowledge deadline is set to short, and is not properly extended. 
The issue was sometimes happening to the received messages that exceeded the flow control limits, and were thus put on hold.
The fix adds **all** messages to the lease management, but at the same time adjusts the load calculation to not include the messages on hold. The core pause/resume logic effectively remains the same, except that now, the ACK deadlines are automatically being extended for all received messages, and a fixed stream ACK deadline is not needed anymore.
Contrary to the [original fix](https://github.com/googleapis/google-cloud-python/pull/9268), this PR does not require additional client …
> fix(pubsub): fix messages delivered multiple times despite a long ACK deadline

- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_dispatcher.py
Fixes #9103.
There is a server-side limit on the maximum size of ACK and modACK requests, which can be hit if the leaser tries to manage too many messages in a single requests. This PR avoids the problem by splitting such large requests into multiple smaller requests.
- publish a lot of messages to a topic (significantly more than 3000)
- subscribe to that topic using a streaming pull and a callback that processes messages for a non-negligible amount of time (e.g. 1 second)
- observe the DEBUG log
The following error can be observed in the log output:
```
google.api_core.exceptions.InvalidArgument: 400 Request payload size exceeds the limit: 524288 bytes.
```
There is no error, …
> fix(pubsub): split large (mod)ACK requests into smaller ones

- bigtable/docs/snippets_table.py
- bigtable/google/cloud/bigtable/table.py
- bigtable/tests/system.py
- bigtable/tests/unit/test_table.py
> feat(bigtable): add table level IAM policy controls

- bigquery/google/cloud/bigquery/client.py
- bigquery/google/cloud/bigquery/magics.py
- bigquery/noxfile.py
- bigquery/setup.py
- bigquery/tests/system.py
- bigquery/tests/unit/test_client.py
- bigquery/tests/unit/test_magics.py
Fixes #9790.
This PR fixes the client leaking open sockets by adding a `close()` method to the client for cleaning up after itself. It also fixes a similar leak in IPython magics - even if bqstorage client is used - when cell magic is run.
Run both code samples from the issue description, i.e. the one using magics, and the other one using a regular BigQuery client. In both cases the number of open connections at the end should be the same as at the beginning, meaning that no connections (sockets) are leaked.
The `magics._cell_magic()` needs refactoring, it's very long and several helper methods should be extracted from it. But that's out of this PR's scope.
> fix(bigquery): add close() method to client for releasing open sockets

- bigquery/noxfile.py
- bigquery/tests/unit/test__pandas_helpers.py
- bigquery/tests/unit/test_client.py
- bigquery/tests/unit/test_magics.py
- bigquery/tests/unit/test_schema.py
I had to decrease the required per-version coverage on account of the missing pyarrow dependency.
Towards #9878
> chore(bigquery): run unit tests with Python 3.8

- core/google/cloud/_http.py
- core/tests/unit/test__http.py
Fixes #9914.
Towards #7831.
As [discussed](https://github.com/googleapis/google-cloud-python/pull/9875#discussion_r351504480) on a related PR, a "clients gets stuck" fix needs a timeout in the transport layer where the blockage randomly occurs occasionally.
Keeping the existing default behavior the same for now (`timeout=None`), but if there is a "good" default timeout value that suits all client libraries, we can make the requests timeout by default to avoid randomly blocking indefinitely.
> feat(core): add timeout param to JSONConnection.api_request()

- pubsub/google/cloud/pubsub_v1/publisher/_batch/base.py
- pubsub/google/cloud/pubsub_v1/publisher/_batch/thread.py
- pubsub/google/cloud/pubsub_v1/publisher/exceptions.py
- pubsub/google/cloud/pubsub_v1/types.py
- pubsub/tests/system.py
- pubsub/tests/unit/pubsub_v1/publisher/batch/test_thread.py
Fixes #7108. 
This PR fixes the logic that computes the publish batch size overflow, taking the total request message size overhead into account. The improved logic prevents the server-side errors simular to the following:
> google.api_core.exceptions.InvalidArgument: 400 The value for request_size is too large. You passed 10000096 in the request, but the maximum value is 10000000.
(see also the system test in this PR)
- Create a pubisher client with `BatchSettings.max_bytes` substantially larger than 10_000_000, and `BatchSettings.max_latency` to one second (so that the publish autocommit does not kick in too soon).
- Quickly publish a few sizable messages to a topic. Their total size should slightly exceed 10_000_000 bytes.
The backend responds with a …
> fix(pubsub): include request overhead when computing publish batch size overflow

- api_core/google/api_core/retry.py
- api_core/tests/unit/test_retry.py
Fixes #9872.
Towards #7831.
This PR changes the behavior of Retry objects to complete retrying at the specified deadline.
Previously, Retry objects only checked if the next sleep period started before the deadline. This means that the last retry could happen considerably later than the deadline, which can be problematic if there is, say, a future sitting on top that cannot wait that long.
> feat(api_core): make the last retry happen at deadline

- bigquery/samples/query_pagination.py
- bigquery/samples/tests/test_query_pagination.py
This sample addresses internal issue 134774673, in which we recieved
feedback that it's not clear how to paginate through the results of a
query. This sample shows that all completed queries have a destination
table, which can be read from with tabledata.list.
Note: The client library avoids the extra call to `get_table` if query
results are read directly from the QueryJob, but it's confusing to show
that we're able to get the schema from a private API call to
getQueryResults.
> docs(bigquery): add sample to read from query destination table

- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Fixes #9975.
This PR fixes an error that can occur when the streaming pull manager is being shut down when the underlying RPC gets shut down.
When that happens, the StreamingPullManager's _on_response() method is invoked with `None` (as opposed to a `StreamingPullResponse` instance). This commit handles this case gracefully.
(this is how I managed to reproduce the error on my machine consistently)
- Use PubSub `v1.1.0` (the bug does reportedly not occur in an earlier version, e.g. `v1.0.2`)
- Create a topic and a subscription to that topic.
- (optional) Set logging level to DEBUG.
- Start pulling messages from the subscription using the subscriber's streaming pull.
- While pulling messages, generate a keyboard interrupt, and cancel the streaming pull future as a response to the interrupt. …
> fix(pubsub): handle None in on response callback

- bigquery/google/cloud/bigquery/client.py
- bigquery/google/cloud/bigquery/job.py
- bigquery/google/cloud/bigquery/table.py
- bigquery/samples/download_public_data.py
- bigquery/samples/download_public_data_sandbox.py
- bigquery/samples/tests/test_download_public_data.py
- bigquery/samples/tests/test_download_public_data_sandbox.py
- bigquery/tests/unit/test_client.py
- bigquery/tests/unit/test_table.py
When the `create_bqstorage_client` parameter is set to `True`, the BigQuery
client constructs a BigQuery Storage API client for you. This removes
the need for boilerplate code to manually construct both clients
explicitly with the same credentials.
Does this make the `bqstorage_client` parameter unnecessary? In most
cases, yes, but there are a few cases where we'll want to continue using
it. Specifically, when partner tools use `to_dataframe`, they should
continue to use `bqstorage_client` so that they can set the correct
amended user-agent strings. `bqstorage_client` is also needed for regional
API endpoints.
TODO
> feat(bigquery): add `create_bqstorage_client` param to `to_dataframe` and `to_arrow`

- automl/google/cloud/automl_v1beta1/tables/tables_client.py
- automl/tests/unit/gapic/v1beta1/test_tables_client_v1beta1.py
Ensures the ClientInfo object isn't passed in twice to the underlying clients (AutoMLClient and PredictionServiceClient) from the Table Client.
Fixes #9948 🦕
> fix(automl): fix TypeError when passing a client_info to automl TablesClient

- datacatalog/samples/quickstart/create_fileset_entry_quickstart.py
- datacatalog/samples/tests/conftest.py
- datacatalog/samples/tests/quickstart/test_create_fileset_entry_quickstart.py
> feat(datacatalog): add quickstart sample for creating fileset entry.

- bigquery/google/cloud/bigquery/client.py
- bigquery/google/cloud/bigquery/job.py
- bigquery/setup.py
- bigquery/tests/system.py
- bigquery/tests/unit/test_client.py
- bigquery/tests/unit/test_job.py
Fixes #7831.
Requires #9873.
This is a proposed fix for the `done()` method getting stuck. It makes sure that the underlying HTTP request does not block indefinitely when retrieving query results, and that any underlying `requests` exceptions are retriable.
> feat(bigquery): add timeout parameter to QueryJob.done() method

- storage/google/cloud/storage/batch.py
- storage/setup.py
- storage/tests/unit/test__http.py
- storage/tests/unit/test_batch.py
- storage/tests/unit/test_client.py
Add timeout to google cloud storage batch interface and address breakage caused by interface incompatibility.
Fixes #10009 
Related to #9915
> feat: add timeout parameter to Batch interface to match google-cloud-core

- bigquery/google/cloud/bigquery/client.py
- bigquery/google/cloud/bigquery/job.py
- bigquery/noxfile.py
- bigquery/tests/unit/test_client.py
- bigquery/tests/unit/test_job.py
Closes #9987.
This PR adds a `timeout` parameter to the public methods of client and job classes.
Done - #10005.
> feat(bigquery): add timeout parameter to client's and job's public methods

- firestore/google/cloud/firestore_v1/watch.py
Watch Retry is more permissive in Go. This PR replicates that in Python.
Fixes #9890 and b/144734355
> fix: recover watch stream on more error types

- storage/google/cloud/storage/blob.py
- storage/google/cloud/storage/bucket.py
- storage/google/cloud/storage/constants.py
- storage/tests/system.py
- storage/tests/unit/test_bucket.py
> feat(storage): add 'ARCHIVE' storage class

- bigtable/google/cloud/bigtable/row.py
- bigtable/tests/unit/test_row.py
Fixes #10018 🦕
Tested manually with the following script, no longer getting ` google.api_core.exceptions.FailedPrecondition: 400 Single-row transactions are not allowed by this app profile` and confirmed data was written to my test table.
```python
#!/usr/bin/env python
from google.cloud.bigtable.client import Client
from google.cloud.bigtable.row import ConditionalRow
from google.cloud.bigtable.row_filters import PassAllFilter
PROJECT_ID="<PROJECT_ID>"
INSTANCE_ID="<INSTANCE_ID>"
TABLE_ID="<TABLE_ID>"
APP_PROFILE_ID="<APP_PROFILE_ID>"
client = Client(project=PROJECT_ID)
instance = client.instance(instance_id=INSTANCE_ID)
table = instance.table(table_id=TABLE_ID, app_profile_id=APP_PROFILE_ID)
row_cond = ConditionalRow(b'test_conditional', table, PassAllFilter(True)) …
```
> fix: add ability to use single-row transactions

- bigquery/google/cloud/bigquery/client.py
- bigquery/google/cloud/bigquery/job.py
- bigquery/tests/unit/test_client.py
- bigquery/tests/unit/test_job.py
Fixes #10019.
This PR adds support for a retry to Client and Job methods where missing.
PR checklist:
> feat(bigquery): add retry parameter to public methods where missing

- README.rst
- datacatalog/.repo-metadata.json
- datacatalog/README.rst
- datacatalog/setup.py
Fixes internal issue 138402054 comment 35.
> chore(datacatalog): update README to reflect Beta launch status

- bigquery/setup.py
> fix(bigquery): fix minimum version of dependency

- api_core/google/api_core/iam.py
- api_core/tests/unit/test_iam.py
- bigtable/google/cloud/bigtable/policy.py
- bigtable/tests/unit/test_policy.py
This ~~proposal~~ change uses a list of (binding) dicts as the underlying data structure, while providing backwards compatibility for v1 Policy.
The `Policy` class is still inheriting from `MutableMapping`, but throws an exception if policy's version is `3` and the user try to access it as if it were a dict (via accessors, setter, iterator etc).
> feat(api_core): support version 3 policy bindings

- dns/setup.py
- dns/tests/unit/test__http.py
> fix(dns): update test assertion and core version pins

- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/unit/test_table.py
> feat(bigquery): make rowIterator._to_dataframe_iterable public

- logging/setup.py
- logging/tests/system/test_system.py
- logging/tests/unit/test__http.py
> fix(logging): update test assertion and core version pins

- spanner/google/cloud/spanner_v1/instance.py
> docs(spanner): fix instance docstrings

- bigquery_storage/google/cloud/bigquery_storage_v1beta1/reader.py
- bigquery_storage/tests/unit/test_reader.py
…to_arrow + to_pandas, internally
Towards https://issuetracker.google.com/140579733
> refactor(bigquerystorage): `to_dataframe` on an arrow stream uses faster `to_arrow` + `to_pandas`, internally

- bigquery/google/cloud/bigquery/table.py
- bigquery/tests/system.py
- bigquery/tests/unit/test_table.py
…pyarrow is available
Related to similar PR https://github.com/googleapis/google-cloud-python/pull/9997 but for the `google-cloud-bigquery` library.
Fixes https://issuetracker.google.com/140579733
> refactor(bigquery): `to_dataframe` uses faster `to_arrow` + `to_pandas` when `pyarrow` is available

- logging/tests/unit/handlers/test__helpers.py
- pubsub/synth.py
- storage/google/cloud/storage/batch.py
- storage/tests/unit/test__signing.py
Fixes #10158.
- [trivial] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-cloud-python/issues) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
(edit by @plamut: opened the [issue](https://github.com/googleapis/google-cloud-python/issues/10158) for better traceability)
- [n/a] Appropriate docs were updated (if necessary)
---
We don't yet know if 3.10 or 4.0 will follow Python 3.9, but whichever it is, it will probably happen in [2020 when Python 3.9 reaches beta](https://www.python.org/dev/peps/pep-0596/#schedule) and work begins on Python 3.9+1.
There's some code …
> fix: replace unsafe six.PY3 with PY2 for better future compatibility with Python 4

- bigquery_storage/google/cloud/bigquery_storage_v1beta1/reader.py
- bigquery_storage/tests/unit/test_reader.py
It's infeasible for the backend to change the status of `EOS on DATA`
internal errors, so instead we check the error message to see if it's
an error that is resumable. We don't want to try to resume on *all*
internal errors, so inspecting the message is the best we can do.
This fixes the same error as https://issuetracker.google.com/143292803 but for Python.
> fix(bigquerystorage): resume reader connection on `EOS` internal error

- language/samples/v1/language_syntax_gcs.py
- language/samples/v1/language_syntax_text.py
Fixes a typo ("speech" instead of "spech") in Natural Languages samples.
Fixes #10133 🦕
> Fixes typo in Natural Language samples

- pubsub/setup.py
Fixes #10167.
This PR declaratively drops Python 3.4 support by constraining installation on Python 3.4 with the corresponding option in `setup.py`.
> chore(pubsub): declaratively drop Python 3.4 support

- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/unit/test_client.py
> feat(bigquery): check json_rows arg type in insert_rows_json()

- spanner/google/cloud/spanner_v1/streamed.py
- spanner/tests/unit/test_streamed.py
> fix(spanner): be permissive about merging an empty struct

- bigquery/google/cloud/bigquery/client.py
- bigquery/tests/unit/test_client.py
Continuation of https://github.com/googleapis/google-cloud-python/pull/10162
Adding arg type check into `insert_rows()` method
> feat(bigquery): check rows arg type in insert_rows()

- bigquery/google/cloud/bigquery/client.py
- bigquery/google/cloud/bigquery/magics.py
- bigquery/tests/unit/test_client.py
Now that all client methods that take a `DatasetReference` or
`TableReference` also take a string, the `client.dataset()` method is
unnecessary and confusing.
Closes #8989.
> deprecate(bigquery): deprecate `client.dataset()` in favor of `DatasetReference`

- automl/google/cloud/automl_v1beta1/tables/tables_client.py
- automl/setup.py
- automl/tests/unit/gapic/v1beta1/test_tables_client_v1beta1.py
The Predict request payload is proto. Previously Python dict is
automatically converted to proto. However, the conversion failed for
list item and dict item. Changing the structure of the Python dict might
fix the problem. However, this PR fixes the problem by generating the
proto message directly. So there is no auto conversion step.
FIXES #9887
> fix(automl): fix TablesClient.predict for array and struct

- core/google/cloud/_http.py
- core/tests/unit/test__http.py
Closes #10217.
As discussed - we want to have a non-`None` default timeout, but still allow overriding it with `None` if somebody wants so.
> feat(core): change default api_request() timeout to non-None

- bigquery/tests/unit/test__http.py
Fixes #10221.
This PR adjusts a few unit test assertions to the new default timeout in `core`.
- Run unit tests on the latest `master` branch.
**Actual result** (before the fix):
A few tests fail due to the `timeout` argument mismatch.
**Expected result** (after the fix):
All tests pass as they should.
> chore(bigquery): adjust test assertions to new default timeout

- storage/tests/unit/test__http.py
Fixes #10250 
This PR adjusts a few unit test assertions to the new default timeout in core.
- Run unit tests on the latest master branch.
One test failed due to the timeout argument mismatch.
All tests pass.
> chore(storage): adjust test assertions to new default timeout

- pubsub/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
- pubsub/google/cloud/pubsub_v1/subscriber/message.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_message.py
- pubsub/tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
- Exposes the delivery-attempt counter for a message.
- Add tests for plumbing + message property.
- In the future, we should modify the system test test_creating_subscriptions_with_non_default_settings or create a new one to test setting a dead letter policy on a subscription. Such a modification would make the test fail now since DLQ isn't enabled for all projects. (Only a DLQ-enabled project would pass the modified test.)
Fixes #10161
> feat(pubsub): add delivery attempt property to message object received by user code

- api_core/google/api_core/grpc_helpers.py
- api_core/tests/unit/test_grpc_helpers.py
In the Node.js SDK, there's code that explicitly waits until at least one result has been observed and retries the underlying stream until then. This doesn't handle the case where the connection is interrupted mid-stream but has been good enough to resolve this class of issues. https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/index.ts#L1127
The Firestore Python SDK needs equivalent code to make it resilient to this class of failure.
This PR causes init of the streaming response iterator to consume the first result immediately which will cause the error to occur while under the retry context. Once the iterator is created it is returned and future access is no longer in a retry context.
> fix: consume part of StreamingResponseIterator to support failure while under a retry context

- storage/google/cloud/storage/_signing.py
- storage/google/cloud/storage/blob.py
- storage/noxfile.py
- storage/tests/system.py
- storage/tests/unit/test__signing.py
- storage/tests/unit/test_blob.py
> feat(storage): add support for signing URLs using token

- spanner/google/cloud/spanner_v1/client.py
- spanner/google/cloud/spanner_v1/database.py
- spanner/tests/system/test_system.py
- spanner/tests/unit/test_client.py
- spanner/tests/unit/test_database.py
Implement resource based routing.
When creating a SpannerClient, check for suggested endpoints. 
If endpoints are returned, use the first one. 
If no endpoints are returned, use default endpoint (either global endpoint or user-specified endpoint).
Endpoints are cached per instance on the Client.
This feature is disabled by default and is enabled by setting the environment variable to true.
To enable:
export GOOGLE_CLOUD_SPANNER_ENABLE_RESOURCE_BASED_ROUTING=true
> feat(spanner): add resource based routing implementation

- bigquery/tests/unit/test_table.py
Closes #8044.
This PR adds tests for concatenating multiple-page results that contain categorical column data (both with or without `pyarrow` available).
It appears that the code already works, provided that a correct explicit categorical `dtype` is passed to `to_dataframe()` method.
If `dtypes` are not specified, a default pandas concatenating behavior results in categorical columns ending up with the dtype "object", but that's already explained in the `dtypes` parameter's docstring, meaning that the code behaves as advertised.
> test(bigquery): add tests for concatenating categorical columns

- bigquery/google/cloud/bigquery/_helpers.py
- bigquery/tests/unit/test__helpers.py
- bigquery/tests/unit/test_client.py
Fixes #9602.
This PR fixes the issue when inserting rows with missing REPEATED fields. Omitting a REPEATED field from the request does not result in an error anymore.
Best to run the ready-made script from one of the [issue comments](https://github.com/googleapis/google-cloud-python/issues/9602#issuecomment-572259971).
**MIND:**
Omitting `None` values only happens when the code needs to convert the data to JSON by itself, i.e. in `insert_rows()`. The following thus still fails when `insert_rows_json()` is used:
```py
rows = [{"int_col": 9, "repeated_col": None}
errors = client.insert_rows_json(TABLE_PATH, rows)
```
If this inconsistency is not desired, we need to sync the logic in these two methods.
> fix(bigquery): fix inserting missing repeated fields

- firestore/google/cloud/firestore_v1/watch.py
- firestore/tests/unit/v1/test_watch.py
> fix: update resume token for restarting BiDi streams

- spanner/docs/advanced-session-pool-topics.rst
- spanner/docs/batch-usage.rst
- spanner/docs/client-usage.rst
- spanner/docs/database-usage.rst
Majority of the suggested imports would cause ImportErrors if you copied them. This fixes them to import correctly.
> fix(spanner): fix imports for doc samples

- recommender/synth.py
Switches back to Artman as there seems to be something missing in the dependencies with `GAPICBazel`.
Closes #10346
> chore(recommender): use artman for generation instead of bazel

- asset/synth.py
closes #10278 
I chose not to add the results of the synth run here to keep the diff small.
> chore(asset): fix `artman_output_name`

- README.rst
all links in the Community section of the README were broken, so I just removed the section.
> fix: removing Community section of broken links in README

- README.rst
MERGE AFTER: https://github.com/googleapis/python-phishingprotection/pull/22
> chore: bump support for phishing-protection to beta

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support_request.md
- README.rst
- synth.metadata
- synth.py
- Use a lightly modified version of google-cloud-java's [synth.py](https://github.com/googleapis/google-cloud-java/blob/master/synth.py) to generate a table of libraries 
- Edit issue templates to nudge folks towards the split repos.
> docs: automate library list generation

- scripts/main_migration/migratemain.sh
- scripts/main_migration/migratemainowlbot
Adding migration scripts to a special migration branch.
`scripts/main_migration/migratemain.sh references the URI of `scripts/main_migration/migratemainowlbot`, so that no unzipping is necessary to drive the migration.
To migrate a repo, run:
```bash
curl https://raw.githubusercontent.com/nicain/google-cloud-python/main-migration/scripts/main_migration/migratemain.sh -o migratemain.sh && chmod +x migratemain.sh && migratemain.sh
```
> chore: add migration scripts

- .github/workflows/main.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> ci: GitHub Workflows security hardening

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/unittest.yml
- ci/run_conditional_tests.sh
- ci/run_single_test.sh
This PR adds CI for the packages in the `google-cloud-python` repo. The files in the directory `ci` were copied from https://github.com/googleapis/google-cloud-node/tree/main/ci
> ci: add ci for packages directory

- containers/python-bootstrap-container/entrypoint.sh
In PR https://github.com/googleapis/google-cloud-python/pull/10682, the owlbot bootstrapper failed to generate a client library because the path to `.OwlBot.yaml` was incorrect. The `.OwlBot.yaml` file is in the root of the directory which contains the package. For example, `packages/google-cloud-discoveryengine/.OwlBot.yaml` not `packages/google-cloud-discoveryengine/.github/.OwlBot.yaml`
> chore: fix path to .OwlBot.yaml

- containers/python-bootstrap-container/.repo-metadata.json
- containers/python-bootstrap-container/entrypoint.sh
This PR fixes an issue where the owlbot post processor fails to run on PRs created by the owlbot bootstrapper. The reason is that `default_version` is not set in `.repo-metadata.json` in those PRs. The `default_version` needs to be set for the post processor to run. The issue can be seen in https://github.com/googleapis/google-cloud-python/pull/10685. I was able to resolve the issue by setting the `default_version` in [this commit](https://github.com/googleapis/google-cloud-python/pull/10685/commits/d449124de3b430b4a87f811820d805c1a0d95840).
> chore: populate default_version in .repo-metadata.json

- scripts/split_repo_migration/split-repo-post-process.common-files.sh
We actually do still need to copy the release-please-manifest.json value from the split repo, since that contains the real version number last released. Relying on the owl-bot generated version would reset the version numbering.
> chore(migration): Revert #11113, to process release-please-manifest

- scripts/split_repo_migration/single-library.git-migrate-history.sh
Apparently, the OwlBot post-processor is not handling directory structures that don't match the distribution name: https://github.com/googleapis/google-cloud-python/issues/11137
For APIs that would trigger this issue, the script change here will just fail early.
> fix(migration): avoid triggering mismatch issue in #11137

- scripts/split_repo_migration/single-library.post-process.api-files.sh
Previously, attempting to commit with no changes, which returns a non-zero code, was causing the script to abort early.
> chore(migration): permit non-zero exit codes when nothing to commit

- scripts/split_repo_migration/delete-everything-split-repo.sh
This makes it more predictable to now where the cloned repo is, when we want to automate creating PRs.
> chore(migration): accept SPLIT_REPO_DIR in deletion script

- scripts/split_repo_migration/delete-everything-split-repo.sh
This helps when we have to re-run the migration scripts as we are not required to delete the old branch/PR.
> chore(migration): use unique-enough name for split repo delete branch

- scripts/split_repo_migration/single-library.post-process.api-files.sh
This is motivated by the need to include the mono-repo package name in `deep-preserve-regex` expressions as well.
The solution here simplifies the post-processing code, and assumes that every `  /owl-bot-staging/` needs to become
`  /owl-bot-staging/PACKAGE/`
> chore(migration): ensure package name is added in .OwlBot.yaml paths

- scripts/split_repo_migration/single-library.git-migrate-history.sh
1. We add a note in the PR body that the PR should be merged and not squashed.
2. We simplify the trailing out put so that we can more easily use the PR URL outputby the `gh` command to scriptify CLI-based merge-commit commands.
> chore(migration): help remember/automate merge-commits of git history

- scripts/split_repo_migration/single-library.post-process.common-files.sh
This PR modifies `scripts/split_repo_migration/single-library.post-process.common-files.sh` to allow git tags to be force created so that the script can be run more than once, in case of failure. 
Another alternative is to move the `git tag` command outside of the `scripts/split_repo_migration/single-library.post-process.common-files.sh` script so that the script can be run more than once if required.
> chore(migration): allow git tags to be force created when running the migration script

- .github/.OwlBot.lock.yaml
Updating the default template version based on https://github.com/googleapis/synthtool/pull/1832.
Towards b/291087837 🦕
> chore: update default template

- packages/google-ai-generativelanguage/.repo-metadata.json
- packages/google-ai-generativelanguage/docs/index.rst
- packages/google-ai-generativelanguage/google/ai/generativelanguage/__init__.py
- packages/google-ai-generativelanguage/google/ai/generativelanguage/gapic_version.py
- packages/google-ai-generativelanguage/google/ai/generativelanguage_v1beta2/gapic_version.py
- packages/google-ai-generativelanguage/google/ai/generativelanguage_v1beta3/services/permission_service/transports/rest.py
- packages/google-ai-generativelanguage/samples/generated_samples/snippet_metadata_google.ai.generativelanguage.v1beta2.json
Here are the steps that I followed to generate this PR
- Update the `default_version` in `.repo-metadata.json` here
https://github.com/googleapis/google-cloud-python/blob/eca60c3027820c97fc12590d0709b8fe3eb54034/packages/google-ai-generativelanguage/.repo-metadata.json#L14
- Work around the docs issue mentioned in https://github.com/googleapis/gapic-generator-python/issues/1776 by applying this change locally
- Build the `v1beta2` and `v1beta3` clients locally in a clone of [googleapis/googleapis](https://github.com/googleapis/googleapis) using `bazel build //google/ai/generativelanguage/v1beta3:ai-generativelanguage-v1beta2-py` and `bazel build //google/ai/generativelanguage/v1beta3:ai-generativelanguage-v1beta3-py`
- Run the docker containers for the owlbot copy-code and owlbot post …
> fix: set google.ai.generativelanguage_v1beta3 as the default import

- scripts/split_repo_migration/single-library.post-process.api-files.sh
- scripts/split_repo_migration/single-library.post-process.common-files.sh
Internally, we recently decided to allow migration of a few system tests into this repository, until we have a better overall testing infrastructure in place.
> chore(migration): allow system tests to be migrated

- .github/.OwlBot.lock.yaml
This PR updates the post processor image to the latest one which is `gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo@sha256:eeaeabb180cbcf1300469ae7621cc1dd24f06b48e4cd2962008bd5150c5f7c1e`.
The latest image includes the following fixes:
https://github.com/googleapis/synthtool/pull/1861
https://github.com/googleapis/synthtool/pull/1867
```
```
```
partheniou@partheniou-vm-3:~/git/google-cloud-python$ docker inspect --format='{{.RepoDigests}}' gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo:latest
[gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo@sha256:eeaeabb180cbcf1300469ae7621cc1dd24f06b48e4cd2962008bd5150c5f7c1e] …
```
> build: update owlbot post processor image

- .github/.OwlBot.lock.yaml
This PR updates the post processor image to the latest one which is `gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo@sha256:590e38040466dced83fa3f0817b8b79723ca3a55ce8c61243d911fe253662f04`.
The latest image includes the following fixes:
https://github.com/googleapis/synthtool/pull/1856
https://github.com/googleapis/synthtool/pull/1881
```
```
```
partheniou@partheniou-vm-3:~$ docker inspect --format='{{.RepoDigests}}' gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo:latest
[gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo@sha256:590e38040466dced83fa3f0817b8b79723ca3a55ce8c61243d911fe253662f04]
```
> build: update post processor image

- containers/python-bootstrap-container/entrypoint.sh
Addresses https://github.com/googleapis/google-cloud-python/pull/11959#discussion_r1379060517
> chore: bootstrapper code clean up

- .github/.OwlBot.lock.yaml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/main.yml
- .github/workflows/scripts.yml
This PR updates the post processor image to the latest one which is `gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo@sha256:2425930c45520a5acb255bd2876c078681f90e6e259dee2739e86d60a94a2a10`.
The latest image includes the following fix to update the default python version to 3.10 in `noxfile.py`:
https://github.com/googleapis/synthtool/pull/1891
```
```
```
partheniou@partheniou-vm-3:~/git/google-cloud-python$ docker inspect --format='{{.RepoDigests}}' gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo:latest
[gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo@sha256:2425930c45520a5acb255bd2876c078681f90e6e259dee2739e86d60a94 …
```
> chore: update post processor image

- .kokoro/docs/common.cfg
The default timeout for Kokoro jobs is 3 hours. Specifying the timeout will help increase it to 24 hours.
24 should be good for all latest versions for the foreseeable future. We can increase it now, or try to optimize it in the future if we run into the problem again.
Fixes #12084 🦕
> build: Update common.cfg

- .github/.OwlBot.lock.yaml
- packages/google-cloud-config/noxfile.py
- packages/google-cloud-securitycentermanagement/noxfile.py
This PR updates the post processor image to the latest one which is `gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo@sha256:1f42c1d6b70210540f55110662ae80e22b03dfb897782b09e546148599d3336c`.
The latest image fixes an issue with the docs and docfx builds. See https://github.com/googleapis/synthtool/pull/1916
```
```
```
docker inspect --format='{{.RepoDigests}}' gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo:latest
[gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo@sha256:1f42c1d6b70210540f55110662ae80e22b03dfb897782b09e546148599d3336c]
```
> build: fix docs and docfx builds

- ci/run_single_test.sh
A bug was introduced in https://github.com/googleapis/google-cloud-python/pull/12273 and https://github.com/googleapis/google-cloud-python/pull/12274 which prevents docs failures from appearing in presubmits
> ci: resolve issue where docs failures do not appear in presubmits

- packages/google-cloud-monitoring/tests/unit/test_query.py
https://pypi.org/project/mock/ library is not needed anymore on modern
Python installation, since it is now part of the Python standard
library, available as `unittest.mock`.
Reuse approach used in generated `tests/unit/gapic/monitoring_v3/` for
manually written `tests/unit/test_query.py`.
This issue and solution was found as a part of packaging the library for
Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=2263960.
Fixes #12316 🦕
> fix: make google-cloud-monitoring tests work without `mock`

- packages/google-cloud-gke-hub/.OwlBot.yaml
- packages/google-cloud-gke-hub/google/cloud/gkehub_v1beta1/gapic_version.py
- packages/google-cloud-gke-hub/google/cloud/gkehub_v1beta1/services/gke_hub_membership_service/async_client.py
- packages/google-cloud-gke-hub/google/cloud/gkehub_v1beta1/services/gke_hub_membership_service/client.py
- packages/google-cloud-gke-hub/google/cloud/gkehub_v1beta1/services/gke_hub_membership_service/transports/base.py
- packages/google-cloud-gke-hub/google/cloud/gkehub_v1beta1/services/gke_hub_membership_service/transports/grpc.py
- packages/google-cloud-gke-hub/google/cloud/gkehub_v1beta1/services/gke_hub_membership_service/transports/grpc_asyncio.py
- packages/google-cloud-gke-hub/google/cloud/gkehub_v1beta1/services/gke_hub_membership_service/transports/rest.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_create_membership_async.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_create_membership_sync.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_delete_membership_async.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_delete_membership_sync.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_generate_connect_manifest_async.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_generate_connect_manifest_sync.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_generate_exclusivity_manifest_async.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_generate_exclusivity_manifest_sync.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_get_membership_async.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_get_membership_sync.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_list_memberships_async.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_list_memberships_sync.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_update_membership_async.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_update_membership_sync.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_validate_exclusivity_async.py
- packages/google-cloud-gke-hub/samples/generated_samples/gkehub_v1beta1_generated_gke_hub_membership_service_validate_exclusivity_sync.py
- packages/google-cloud-gke-hub/samples/generated_samples/snippet_metadata_google.cloud.gkehub.v1beta1.json
- packages/google-cloud-gke-hub/tests/unit/gapic/gkehub_v1beta1/test_gke_hub_membership_service.py
This PR fixes the issue where the client for [google.cloud.gkehub_v1beta1](https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-gke-hub/google/cloud/gkehub_v1beta1) was not being updated automatically. 
I followed the steps below to generate the changes in this PR:
1. Run the commands below in a clone of [googleapis/googleapis](https://github.com/googleapis/googleapis)
```
bazelisk build //google/cloud/gkehub/v1:gkehub-v1-py
bazelisk build //google/cloud/gkehub/v1/configmanagement:configmanagement-v1-py
bazelisk build //google/cloud/gkehub/v1/multiclusteringress:multiclusteringress-v1v1beta1-py
bazelisk build //google/cloud/gkehub/v1beta1:gkehub-v1beta1-py
```
2. Run the command below in a clone of this repository. The docker container will copy code from the …
> feat(v1beta1): Allow users to explicitly configure universe domain

- packages/google-cloud-deploy/google/cloud/deploy_v1/types/cloud_deploy.py
> chore: fix the docs in google-cloud-deploy 

- packages/google-analytics-admin/google/analytics/admin_v1alpha/services/analytics_admin_service/async_client.py
- packages/google-analytics-admin/google/analytics/admin_v1alpha/services/analytics_admin_service/client.py
- packages/google-analytics-admin/google/analytics/admin_v1alpha/types/analytics_admin.py
> chore: fix docs build in google-analytics-admin

- packages/google-cloud-datacatalog/google/cloud/datacatalog_v1beta1/types/usage.py
> chore: fix docs build in google-cloud-datacatalog 

- packages/google-geo-type/docs/index.rst
> chore: fix docs build in google-geo-type

- .github/workflows/main.yml
> build: update python and ubuntu versions to fix the README API list workflow

- packages/google-cloud-backupdr/.repo-metadata.json
Updating the repo.metadata.json for documentation path: https://cloud.google.com/python/docs/reference/backupdr/latest
The current link doesn't work.
Please let me know if this can be manually fixed or if it needs to be updated from the serviceconfigs.
> chore(docs): Update .repo-metadata.json for backupdr

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/unittest.yml
Googlers see approved doc in b/300959810
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group which mentions the following:
>More than one activity type triggers this event. Although only the checks_requested activity type is supported, specifying the activity type will keep your workflow specific if more activity types are added in the future. 
>If your repository uses GitHub Actions to perform required checks on pull requests in your repository, you need to update the workflows to include the merge_group event as an additional trigger. Otherwise, status checks will not be triggered when you add a pull request to a merge queue. The merge will fail as the required status check will not be reported. The merge_group event is separate from the …
> build: Trigger presubmit workflows on GitHub merge queue events

- README.rst
- scripts/updateapilist.py
Towards #11147
Towards #12679 🦕
> chore: update script for generating README

- .github/.OwlBot.lock.yaml
This PR updates the post processor image to the latest one which is `gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo@sha256:93fe03a099be9aa70157b95f5600473602d53b34983488ccdcd37cecb6a9ba3e`.
The latest image updates `noxfile.py` to test all 3 protobuf implementations `upb`, `python` and `cpp`. See https://github.com/googleapis/synthtool/pull/1974
```
```
```
docker inspect --format='{{.RepoDigests}}' gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo:latest
[gcr.io/cloud-devrel-public-resources/owlbot-python-mono-repo@sha256:93fe03a099be9aa70157b95f5600473602d53b34983488ccdcd37cecb6a9ba3e]
```
> build: update to the latest post processor image

- ci/run_single_test.sh
This PR fixes the `No space left on device` error seen in presubmits in https://github.com/googleapis/google-cloud-python/pull/12860 
The specific failure can be seen in [this presubmit run](https://github.com/googleapis/google-cloud-python/actions/runs/9797847588?pr=12860)
I tested the fix in https://github.com/googleapis/google-cloud-python/pull/12875
> build: clean up __pycache__ directories

- ci/run_single_test.sh
The `.nox` directory is created when `nox` is run and is more than 100MB for some packages. This PR removes the `.nox` directory after presubmit tests run to free up disk space.
As an example,
1. cd to `packages/google-cloud-access-approval`
2. run `nox -s unit-3.9`
3. run `du -sh .nox` which shows the directory is 152 MB
> build: clean up .nox directory

- packages/google-ai-generativelanguage/scripts/client-post-processing/doc-formatting.yaml
- packages/google-cloud-datacatalog/scripts/client-post-processing/doc-formatting.yaml
- packages/google-cloud-edgenetwork/scripts/client-post-processing/doc-formatting.yaml
- packages/google-cloud-network-connectivity/scripts/client-post-processing/doc-formatting.yaml
- packages/google-cloud-retail/scripts/client-post-processing/doc-formatting.yaml
- packages/google-cloud-securitycentermanagement/scripts/client-post-processing/doc-formatting.yaml
- packages/google-cloud-visionai/scripts/client-post-processing/doc-formatting.yaml
- scripts/client-post-processing/doc-formatting.yaml
This attempts to configure post-processing for the repeated docs failures we're seeing. This is a short-term workaround, listing the individual cases with violations.
We envision eventually implementing  a proper fix, probably involving stricter upstream standards, but that will take a while, and these failures are drudge work at the moment.
Note that I was only able to apply the first of these changes in my local client to the cloned PRs that were generating these errors; I'm not sure what's wrong with my incantation. Feedback welcome!
(At the very least, this is a listing of the specific docs fixes we need to implement.)
> chore(docs): add doc formatting post-processing fixes

- .kokoro/publish-docs-single.sh
The staging bucket is no longer used (b/374954111). Changing to dev instead.
Towards b/374991608 🦕
> chore: update staging bucket to dev

- packages/google-cloud-run/CHANGELOG.md
feat: support advanced configurations options for cloud storage volumes by setting mount_options in the GCSVolumeSource configuration
docs: Update docs for field `value` in message `.google.cloud.run.v2.EnvVar` to reflect Cloud Run product capabilities
docs: A comment for field `max_instance_request_concurrency` in message `.google.cloud.run.v2.RevisionTemplate` is changed
docs: For field `invoker_iam_disabled` in message `.google.cloud.run.v2.Service`, clarify that feature is available by invitation only
Add conventional commits for PR https://github.com/googleapis/google-cloud-python/pull/13245
See https://github.com/googleapis/googleapis/commit/b478ea33bf0a30765db8ee1d05c51b8bda7b4974
> chore: update changelog

- .github/workflows/unittest.yml
- packages/google-cloud-servicehealth/CHANGELOG.md
This PR resolves the following issue [when running Python 3.7 tests](https://github.com/googleapis/google-cloud-python/actions/runs/12406551833/job/34635201044?pr=13374) :
```
Version 3.7 was not found in the local cache
Error: The version '3.7' with architecture 'x64' was not found for Ubuntu 24.04.
```
> build: use ubuntu 22.04 for tests

- packages/google-cloud-monitoring/tests/unit/test_query.py
Towards https://github.com/googleapis/google-cloud-python/issues/13356
This PR fixes the issue seen in PR https://github.com/googleapis/google-cloud-python/pull/13359 where presubmits fail with 
```
>   thunk = lambda m: self._channel.unary_unary(
m,
request_serializer,
response_deserializer,
_registered_method,
)
E   TypeError: ChannelStub.unary_unary() takes from 2 to 4 positional arguments but 5 were given
```
The reason for the failures is that in https://github.com/googleapis/gapic-generator-python/pull/2284/files support for debug logging was added, which required using grpc [intercept_channel](https://github.com/googleapis/gapic-generator-python/blob/e050f4eb3eddfe150f028a2a2bd901899afb965a/gapic/templates/%25namespace/%25name_%25version/%25sub/services/%25service/transports/grpc.py …
> tests: forward compatible fix for google-cloud-monitoring

- packages/google-cloud-org-policy/.OwlBot.yaml
This PR fixes an issue in the `.OwlBot.yaml` for `google-cloud-org-policy` where there is an erroneous folder `$2` in `/owl-bot-staging/google-cloud-org-policy/google/cloud/orgpolicy/v1`
To reproduce the issue run the following commands in a clone of https://github.com/googleapis/googleapis
```
bazelisk build //google/cloud/orgpolicy/v1:orgpolicy-v1-py
bazelisk build //google/cloud/orgpolicy/v2:orgpolicy-v2-py
```
Then in this repository run the following command to copy code from `bazel-bin`
```
docker run --rm --user $(id -u):$(id -g)   -v $(pwd):/repo   -v <path to your bazel-bin>:/bazel-bin   gcr.io/cloud-devrel-public-resources/owlbot-cli:latest copy-bazel-bin   --source-dir /bazel-bin --dest /repo   --config-file=/packages/google-cloud-org-policy/.OwlBot.yaml 
```
and then run the …
> build: update .OwlBot.yaml for google-cloud-org-policy

- .github/workflows/unittest.yml
- ci/run_conditional_tests.sh
- ci/run_single_test.sh
This PR adds a new presubmit `core_deps_from_source` which depends on https://github.com/googleapis/synthtool/pull/2061
The presubmit will install core dependencies from source in order to get early feedback on changes made at HEAD of dependencies.
> build: add a new presubmit core_deps_from_source

- packages/googleapis-common-protos/pyproject.toml
- packages/googleapis-common-protos/setup.py
Tracking issue https://github.com/googleapis/google-cloud-python/issues/13171
Previous PR: https://github.com/googleapis/python-api-common-protos/pull/255
Fixes #<issue_number_goes_here> 🦕
> feat: migrate to pyproject.toml

- scripts/client-post-processing/integrate-isolated-handwritten-code.yaml
Towards https://github.com/googleapis/google-cloud-python/issues/13585
Remove `dev` from post processing scripts
> build: remove dev from post processing scripts

- packages/googleapis-common-protos/.OwlBot.yaml
Towards https://github.com/googleapis/google-cloud-python/issues/13545
This PR depends on https://github.com/googleapis/gapic-generator-python/pull/2349
> build: allow *.proto files to be copied for google/longrunning

- packages/google-cloud-storage-control/.repo-metadata.json
- packages/google-cloud-storage-transfer/.repo-metadata.json
- packages/google-cloud-storageinsights/.repo-metadata.json
Clean up outdated cloud-storage-dpe team
> chore: set gcs-sdk-team as storage codeowners

- renovate.json
The files `setup.py` and `pyproject.toml` which exist in subfolders under the `packages` directory are automatically generated and do not require updates from `renovate-bot`. In addition, PR https://github.com/googleapis/google-cloud-python/pull/13623 does not contain the desired change. 
We see `protobuf>=6.30.0,<6.30.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5` instead of `protobuf>=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5`
`setup.py` is already excluded in the renovate-bot configuration for split repositories via this configuration: https://github.com/googleapis/synthtool/blob/bb0a3506602525f63c7002f8d13345be3678effb/synthtool/gcp/templates/python_library/renovate.json#L8
> chore: exclude setup.py and pyproject.toml in renovate-bot config

- packages/google-cloud-access-context-manager/noxfile.py
- packages/google-cloud-access-context-manager/setup.py
- packages/google-cloud-audit-log/setup.py
- packages/googleapis-common-protos/pyproject.toml
- packages/grpc-google-iam-v1/pyproject.toml
Apply changes from https://github.com/googleapis/gapic-generator-python/pull/2352 and https://github.com/googleapis/gapic-generator-python/pull/2347 to 4 packages containing protobuf stubs which are not automatically generated using `gapic-generator-python`
fix: Allow protobuf 6.x
fix: resolve issue where pre-release versions of dependencies are installed
> fix: Allow protobuf 6.x

- packages/google-cloud-compute/tests/system/base.py
`debian-10` no longer exists in https://cloud.google.com/compute/docs/images/os-details#debian
https://github.com/googleapis/google-cloud-python/blob/3609c907cf4c03bf08418de150c84c32da9dae1e/packages/google-cloud-compute/tests/system/base.py#L44
This will fix an issue in the system tests for `google-cloud-compute` which is failing because `projects/debian-cloud/global/images/family/debian-10` doesn't exist. We should use `projects/debian-cloud/global/images/family/debian-12` instead.
```
E           google.api_core.exceptions.NotFound: 404 POST https://compute.googleapis.com/compute/v1/projects/<REDACTED>/zones/us-central1-a/instances: The resource 'projects/debian-cloud/global/images/family/debian-10' was not found
```
See the build log …
> build: fix system test

- packages/googleapis-common-protos/pyproject.toml
This PR fixes an issue in `googleapis-common-protos` where `excludes` is set in `tool.setuptools.packages.find`, without specifying `include` which may cause strange installation behaviour as seen in this [build log](https://github.com/googleapis/google-cloud-python/actions/runs/13822574147/job/38671145919) from PR https://github.com/googleapis/google-cloud-python/pull/13657.
https://github.com/googleapis/google-cloud-python/blob/a2466af25d832eab04153e8bde446a9e9e523d2b/packages/googleapis-common-protos/pyproject.toml#L53-L54
See the following from the log
```
2025-03-13T02:08:01.5380028Z       copying google/type/timeofday.proto -> build/lib/google/type
2025-03-13T02:08:01.5380508Z       copying google/type/timeofday_pb2.pyi -> build/lib/google/type
2025-03-13T02:08:01.5381044Z …
```
> fix: set `include` in `tool.setuptools.packages.find`

- packages/google-cloud-iam/samples/snippets/README.md
The README originally pointed to a PR that only adds deny-based samples, and not actually linking the base folder. I experienced friction when discovering this link (originally from the docs link in https://cloud.google.com/python/docs/reference/iam/latest#code-samples-and-snippets), thinking that there were no Python IAM role/service related snippets (only Deny), but then finding the folder the PR added to full of samples.
> docs: Update suggested source of IAM samples

- packages/google-cloud-modelarmor/.repo-metadata.json
- packages/google-cloud-securitycentermanagement/.repo-metadata.json
- packages/google-cloud-websecurityscanner/.repo-metadata.json
On https://cloud.google.com/python/docs/reference, the Security Command Center _product_ should be listed with the client libraries for all of the _services_ that it provides, including the following:
* [modelarmor.googleapis.com](https://cloud.google.com/security-command-center/docs/reference/model-armor/rest)
* [securitycenter.googleapis.com](https://cloud.google.com/security-command-center/docs/reference/rest)
* [securitycentermanagement.googleapis.com](https://cloud.google.com/security-command-center/docs/reference/security-center-management/rest)
* [securityposture.googleapis.com](https://cloud.google.com/security-command-center/docs/reference/securityposture/rest) (no client libraries yet)
* [websecurityscanner.googleapis.com](https://cloud.google.com/security-command-center/docs/ref …
> docs: group Security Command Center packages together on cloud.google.com

- .github/workflows/lint.yml
This fixes an issue seen in https://github.com/googleapis/google-cloud-python/pull/13772 where the `lint` presubmit fails with `nox > Session lint failed: Python interpreter 3.13 not found.`
> build: use python 3.13 for lint session

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/unittest.yml
`PY_VERSION` is only used when `TEST_TYPE` environment variable is set to `unit`. We can set `PY_VERSION` to `unused` otherwise to reflect that it is not being. See https://github.com/googleapis/google-cloud-python/issues/13775 to follow up on supporting `PY_VERSION` for all values of `TEST_TYPE`, rather than just `unit`
> chore: restore PY_VERSION

- packages/googleapis-common-protos/.OwlBot.yaml
This PR disables automated gencode updates for `googleapis-common-protos`.
> chore: disable gencode updates for common-protos

- packages/google-cloud-access-context-manager/.OwlBot.yaml
Similar to these PRs:
https://github.com/googleapis/google-cloud-python/pull/13868
https://github.com/googleapis/google-cloud-python/pull/13867
https://github.com/googleapis/google-cloud-python/pull/13866
https://github.com/googleapis/google-cloud-python/pull/13865
Towards b/413654538
> chore: disable gencode updates for google-cloud-access-context-manager

- packages/google-cloud-compute/.OwlBot.yaml
Ensure that only `google/cloud/compute/v1` is copied from `googleapis-gen`. `google/cloud/compute/v1beta` will be a separate package `google-cloud-compute-beta`
Towards https://github.com/googleapis/google-cloud-python/issues/12471
> chore: update .OwlBot.yaml in google-cloud-compute

- packages/google-cloud-dataplex/google/cloud/dataplex/gapic_version.py
- packages/google-cloud-dataplex/google/cloud/dataplex_v1/gapic_version.py
- packages/google-cloud-dataplex/google/cloud/dataplex_v1/types/catalog.py
- packages/google-cloud-dataplex/samples/generated_samples/snippet_metadata_google.cloud.dataplex.v1.json
- packages/google-cloud-dataplex/scripts/fixup_dataplex_v1_keywords.py
- packages/google-cloud-dataplex/tests/unit/gapic/dataplex_v1/test_catalog_service.py
This splits the changes that were joined together in https://github.com/googleapis/google-cloud-python/pull/14063 so that releases can have proper release notes.
feat: A new field semantic_search is added to message.google.cloud.dataplex.v1.SearchEntriesRequest
PiperOrigin-RevId: 778817135
> chore: updates to dataplex

- packages/google-cloud-network-services/google/cloud/network_services/gapic_version.py
- packages/google-cloud-network-services/google/cloud/network_services_v1/gapic_version.py
- packages/google-cloud-network-services/google/cloud/network_services_v1/types/service_lb_policy.py
- packages/google-cloud-network-services/samples/generated_samples/snippet_metadata_google.cloud.networkservices.v1.json
- packages/google-cloud-network-services/tests/unit/gapic/network_services_v1/test_network_services.py
This splits the changes that were joined together in https://github.com/googleapis/google-cloud-python/pull/14063 so that releases can have proper release notes.
feat: Add isolation support to prevent cross-region overflow by adding a new field "isolation_config" to message "ServiceLbPolicy"
> chore: updates to networkservices

- packages/google-cloud-private-ca/google/cloud/security/privateca/__init__.py
- packages/google-cloud-private-ca/google/cloud/security/privateca/gapic_version.py
- packages/google-cloud-private-ca/google/cloud/security/privateca_v1/__init__.py
- packages/google-cloud-private-ca/google/cloud/security/privateca_v1/gapic_version.py
- packages/google-cloud-private-ca/google/cloud/security/privateca_v1/services/certificate_authority_service/async_client.py
- packages/google-cloud-private-ca/google/cloud/security/privateca_v1/services/certificate_authority_service/client.py
- packages/google-cloud-private-ca/google/cloud/security/privateca_v1/types/__init__.py
- packages/google-cloud-private-ca/google/cloud/security/privateca_v1/types/resources.py
- packages/google-cloud-private-ca/google/cloud/security/privateca_v1/types/service.py
- packages/google-cloud-private-ca/google/cloud/security/privateca_v1beta1/gapic_version.py
- packages/google-cloud-private-ca/samples/generated_samples/snippet_metadata_google.cloud.security.privateca.v1.json
- packages/google-cloud-private-ca/samples/generated_samples/snippet_metadata_google.cloud.security.privateca.v1beta1.json
- packages/google-cloud-private-ca/tests/unit/gapic/privateca_v1/test_certificate_authority_service.py
This splits the changes that were joined together in https://github.com/googleapis/google-cloud-python/pull/14063 so that releases can have proper release notes.
feat: add RDN sequence
feat: add User Defined Access URLs
feat: add backdate duration
feat: adds tbs_certificate_digest to CertificateDescription
> chore: updates to privateca

- .librarian/state.yaml
- scripts/configure_state_yaml/configure_state_yaml.py
- scripts/configure_state_yaml/packages_to_onboard.yaml
Fixes https://github.com/googleapis/librarian/issues/867
> chore: add librarian state.yaml

- packages/google-cloud-storage-control/.repo-metadata.json
> fix: Set API shortname storagecontrol to storage

- .librarian/generator-input/client-post-processing/add-dependency-google-cloud-common.yaml
- .librarian/generator-input/client-post-processing/add-missing-dependencies-to-setup-py-constraints.yaml
- .librarian/generator-input/client-post-processing/containeranalysis-grafeas-integration.yaml
- .librarian/generator-input/client-post-processing/doc-formatting.yaml
- .librarian/generator-input/client-post-processing/docs-index-rst-for-unversioned-apis.yaml
- .librarian/generator-input/client-post-processing/integrate-isolated-handwritten-code.yaml
- .librarian/generator-input/client-post-processing/mypy-error-with-org-policy-as-dependency.yaml
- .librarian/generator-input/client-post-processing/proto-plus-dependency-with-modified-namespace.yaml
- .librarian/generator-input/client-post-processing/remove-erroneous-client.yaml
- .librarian/generator-input/client-post-processing/remove-unused-imports.yaml
- .librarian/generator-input/client-post-processing/revert-reserved-words.yaml
- .librarian/generator-input/client-post-processing/sub-api-versioned-namespace.yaml
- .librarian/generator-input/client-post-processing/unique-grafeas-client.yaml
- .librarian/generator-input/client-post-processing/update-readme-with-pycharm-workaround.yaml
This PR adds a `client-post-processing` directory and corresponding post-processing files to `.librarian/generator-input` as these files are needed for client library generation.
This PR was created using the following commands
```
mkdir .librarian/generator-input/client-post-processing
cp -r scripts/client-post-processing/* .librarian/generator-input/client-post-processing
```
The directory `scripts/client-post-processing` can be removed once all of the `.OwlBot.yaml` files have been removed and [owlbot automation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/owl-bot) is no longer used.
> chore: add client post-processing to .librarian/generator-input

- .generator/Dockerfile
- cloudbuild.yaml
This PR updates the Dockerfile to include the missing pieces such as:
- Running `bazelisk build` command in the builder stage to warm up the bazel cache.
- Allowing a user to be configured when building the docker image.
- Using a virtual env to fix the missing nox error when running the post processor.
- Creating custom directories for bazel cache to be used by `bazelisk build`.
- Adding permissions to the cli.py file.
Fixes #14142
> feat: use kaniko build and add container changes

- packages/google-shopping-merchant-reports/.repo-metadata.json
- packages/google-shopping-merchant-reports/README.rst
- packages/google-shopping-merchant-reports/docs/index.rst
- packages/google-shopping-merchant-reports/google/shopping/merchant_reports/__init__.py
feat: set `google.shopping.merchant_reports_v1` as the default import for `google.shopping.merchant_reports`
> feat: update release level to stable

- packages/google-shopping-type/CHANGELOG.md
- packages/google-shopping-type/google/shopping/type/gapic_version.py
Towards #14230 (see [comment](https://github.com/googleapis/google-cloud-python/pull/14230#issuecomment-3185953202)).
> chore: release google-shopping-type

- .librarian/config.yaml
Add a [.librarian/config.yaml](https://github.com/googleapis/librarian/blob/main/doc/language-onboarding.md#configyaml) file to allow the [language specific container](https://github.com/googleapis/librarian/blob/main/doc/language-onboarding.md#container-contracts) to access the `CHANGELOG.md` file when the [librarian release init](https://github.com/googleapis/librarian/blob/main/doc/language-onboarding.md#release-init) command is used.
The proposed `config.yaml` is similar to the examples in https://github.com/googleapis/librarian/blob/main/doc/language-onboarding.md#release-init
This is needed to update the root [CHANGELOG.md](https://github.com/googleapis/google-cloud-python/blob/main/CHANGELOG.md) file which is currently updated using the Github action …
> chore: add .librarian/config.yaml

- packages/google-shopping-merchant-notifications/.repo-metadata.json
- packages/google-shopping-merchant-notifications/README.rst
- packages/google-shopping-merchant-notifications/docs/index.rst
- packages/google-shopping-merchant-notifications/google/shopping/merchant_notifications/__init__.py
- packages/google-shopping-merchant-notifications/scripts/client-post-processing/add-missing-dependencies-to-setup-py-constraints.yaml
- packages/google-shopping-merchant-notifications/testing/constraints-3.7.txt
- scripts/client-post-processing/add-missing-dependencies-to-setup-py-constraints.yaml
feat!: set `google.shopping.merchant_notifications_v1` as the default import for `google.shopping.merchant_notifications`
> feat!: update release level to stable

- .generator/cli.py
- .librarian/state.yaml
This PR fixes the following error when running librarian locally
```
2025/08/29 23:26:15 ERROR failed to generate library id=google-cloud-language err="failed to copy google-cloud-language to /usr/local/google/home/partheniou/git/google-cloud-python/packages/google-cloud-language: open .repo-metadata.json: permission denied"
2025/08/29 23:26:15 all 1 libraries failed to generate
```
> chore: preserve .repo-metadata.json

- .generator/cli.py
- .generator/test_cli.py
This PR addresses the feedback in https://github.com/googleapis/google-cloud-python/pull/14353#discussion_r2331351946
> chore(librarian): rename `package_name` to `library_id`

- .generator/cli.py
Fixes the following error when running `librarian release init`
```
Release init failed: [Errno 2] No such file or directory: '/output/packages/google-cloud-language/google/cloud/language/gapic_version.py'
```
> chore(librarian): resolve issue where gapic_version.py cannot be written

- .kokoro/system.sh
- packages/google-cloud-dlp/CHANGELOG.md
Currently the system test runs for all packages. This PR adds logic to check if there is a change to the package level `CHANGELOG.md` so that we only runs system tests for packages that have changed. We are only interested in `packages/<package>/CHANGELOG.md` changing as we only want to run system tests on release PRs.
Fixes https://github.com/googleapis/librarian/issues/2067
> chore: run system tests only for modified packages

- .generator/cli.py
- .generator/test_cli.py
This PR reduces the runtime of `librarian generate --build` by removing tests. These tests still run as presubmits on the librarian PR. I've opened https://github.com/googleapis/librarian/issues/2211 to follow up on improving performance and restoring these tests.
> chore(librarian): reduce runtime of `librarian generate --build`

- .librarian/state.yaml
- scripts/configure_state_yaml/packages_to_onboard.yaml
Onboard `google-ads-admanager` to librarian
Towards https://github.com/googleapis/librarian/issues/761
> chore(librarian): onboard google-ads-admanager

- .generator/cli.py
- .librarian/state.yaml
- scripts/configure_state_yaml/configure_state_yaml.py
This commit fixes a regression where snippet_metadata files, such as `packages/google-cloud-video-live-stream/samples/generated_samples/snippet_metadata_google.cloud.video.livestream.v1.json`, were not being updated during generation (e.g., in PR #14465).
The root cause was the inclusion of `samples/generated_samples/snippet_metadata_` in the preserve_regex list. While this regex was initially used to reduce diffs during the transition from OwlBot to Librarian, it inadvertently prevented necessary updates to the generated snippet metadata.
> chore(librarian): remove samples/generated_samples/snippet_metadata_from preserve_regex

- .generator/cli.py
Towards https://github.com/googleapis/librarian/issues/466 🦕
> feat: add cli args for configure

- .generator/cli.py
- .generator/test_cli.py
This PR creates a basic `.repo-metadata.json` file for a package that is to be generated using librarian. Note that if a `.repo-metadata.json` file for a package exists in `generator-input`, then the generated metadata file will be overriden.
There will be follow up PRs to address the TODO comments.
Towards https://github.com/googleapis/librarian/issues/2262 🦕
> feat: create repo-metadata during generation

- .generator/cli.py
- .generator/test_cli.py
Fixes https://github.com/googleapis/librarian/issues/2332 🦕
> feat: create repo metadata from service config

- .generator/cli.py
- .generator/test_cli.py
Thid PR fixes the the formatting of `tag_format` field of a library in `state.yaml`.
> fix: update tag_format to the correct format

- .generator/cli.py
- .generator/test_cli.py
This PR fixes the following error when running  `librarian generate --build` for a `proto-only` library such as `googleapis-common-protos`  
```
File "/app/./cli.py", line 977, in handle_build
_verify_library_namespace(library_id, repo)
File "/app/./cli.py", line 913, in _verify_library_namespace
raise ValueError(
ValueError: Error: namespace cannot be determined for googleapis-common-protos. Library is missing a `gapic_version.py`.
The above exception was the direct cause of the following exception:
File "/app/./cli.py", line 1404, in <module>
args.func(librarian=args.librarian, repo=args.repo)
File "/app/./cli.py", line 981, in handle_build
raise ValueError("Build failed.") from e
ValueError: Build failed. …
```
> chore(librarian): Add exception namespaces for googleapis-common-protos

- .librarian/state.yaml
Add `tag_format` to `googleapis-common-protos` which was accidentally removed in https://github.com/googleapis/google-cloud-python/pull/14589/files
> chore(librarian): add tag_format  for googleapis-common-protos

- .librarian/generator-input/client-post-processing/doc-formatting.yaml
Sync post processing scripts in [.librarian/generator-input](https://github.com/googleapis/google-cloud-python/tree/main/.librarian/generator-input) with [scripts/client-post-processing](https://github.com/googleapis/google-cloud-python/tree/main/scripts/client-post-processing).
> chore(librarian): sync post processing

- .librarian/state.yaml
This library is failing when running `librarian generate`. This will be re-added later.
> chore(librarian): remove google-apps-script-type from state.yaml

- ci/run_single_test.sh
Remove hardcoded python runtime for the prerelease presubmit to resolve the failure in https://github.com/googleapis/google-cloud-python/pull/14606 where we want to run prerelease tests with python 3.14
> chore: remove hardcoded python runtime in prerelease presubmit

- .generator/cli.py
- .generator/test_cli.py
- .librarian/state.yaml
This fixes the following stack trace with generation for `google-cloud-common` which caused generation to fail
```
2025-10-01 16:23:35,628 synthtool [WARNING] > No replacements made in packages/google-cloud-common/docs/index.rst for pattern API Reference
-------------
.. toctree::
:maxdepth: 2
common/services_
common/types_
, maybe replacement is no longer needed?
2025-10-01 16:23:35,628 synthtool [WARNING] > No replacements made in packages/google-cloud-common/docs/index.rst for pattern API Reference
-------------
.. toctree::
:maxdepth: 2
common/services_
common/types_
, maybe replacement is no longer needed?
README.rst
Skipping: docs/index.rst
docs/summary_overview.md
File "/app/./cli.py", line 535, in handle_generate
_run_post_processor(output, …
```
> chore(librarian): fix generation for google-cloud-common

- packages/google-cloud-scheduler/samples/snippets/README.md
- packages/google-cloud-securitycenter/samples/snippets/README.md
This PR cleans up the unused snippets README files to minimize the diff against the librarian generation.
> chore: remove unused snippets readme files

- .github/workflows/unittest.yml
This PR fixes the error `Python interpreter 3.14 not found.` when running pre-release tests. See https://github.com/googleapis/google-cloud-python/actions/runs/18178779332/job/51750304401?pr=14616
> chore: run prerelease tests with Python 3.14

- .librarian/state.yaml
- scripts/configure_state_yaml/packages_to_onboard.yaml
This PR onboards `google-cloud-locationfinder` to librarian and should be merged after https://github.com/googleapis/google-cloud-python/pull/14625
Towards https://github.com/googleapis/librarian/issues/762
> chore(librarian): onboard `google-cloud-locationfinder`

- .generator/parse_googleapis_content.py
This PR resolves the following stack traces which appear in the last `librarian generate` job
```
File "/app/./cli.py", line 532, in handle_generate
_generate_api(api_path, library_id, source, output, version)
File "/app/./cli.py", line 764, in _generate_api
py_gapic_config = _read_bazel_build_py_rule(api_path, source)
File "/app/./cli.py", line 556, in _read_bazel_build_py_rule
result = parse_googleapis_content.parse_content(content)
File "/app/parse_googleapis_content.py", line 149, in parse_content
sl.eval(mod, ast, glb, sl.FileLoader(load))
starlark.StarlarkError: error: Variable `proto_library` not found
--> BUILD.bazel:28:1
|
28 | proto_library(
| ^^^^^^^^^^^^^
|
The above exception was the direct cause of the following exception:
Traceback (most …
```
> chore(librarian): fix `proto_library/py_test not found` error

- .generator/Dockerfile
- .generator/requirements.in
Temporarily pin `gapic-generator` to reduce the diff for libraries being onboarded to librarian
> chore(librarian): temporarily pin GAPIC generator

- packages/google-cloud-capacityplanner/google/cloud/capacityplanner_v1beta/types/usage_service.py
These changes reflect the current state of generation using `librarian`
> chore(librarian): fix formatting in google-cloud-capacityplanner

- .librarian/state.yaml
This PR adds a forward slash to the `remove_regex` to provide clarity that the regex is for the full directory name not partial name. 
For example, for `google-cloud-compute` , where there also exists `google-cloud-compute-v1beta`
We would have
```
remove_regex:
- packages/google-cloud-compute/
```
which would only match `google-cloud-compute`  
instead of
```
remove_regex:
- packages/google-cloud-compute
```
Which would match both  `google-cloud-compute`  and `google-cloud-compute-v1beta`
> chore(librarian): Add forward slash to remove regex

- .librarian/state.yaml
This PR fixes the path for `google/maps/fleetengine` to match googleapis
https://github.com/googleapis/googleapis/tree/master/google/maps/fleetengine
> chore(librarian): fix path for google/maps/fleetengine
